### PR TITLE
[db] Add index for all queries on DBPrebuildWorkspaceUpdatable

### LINKED ISSUE #7997: PrebuildWorkspaceUpdateable missing indexes
We had [an incident](https://app.incident.io/incidents/101) which turned out to be caused by missing indexes on the table `d_b_prebuild_workspace_updateable`.

We should:
 - check all queries for the table and create indexes if needed
 - double-check that we're not missing more indexes: We had similar indexes in the past, and it feels like we just lost our indexes at some point in time. We can compare typeorm generated output to the current schema.

### PR DESCRIPTION
**Pull request by geropl**
## Related Issue(s)

Fixes #7997

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** after the PR has been reviewed.

Associated issue: *#7997*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by AlexTugarev** [comment]
/lgtm

thanks for the explanation in code!

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/8001#issuecomment-1028860378" title="LGTM">AlexTugarev</a>*

Associated issue: *#7997*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)~~ [AlexTugarev]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 1416064534781d04f9b950ef5ec5f52af0d709c9</details>

**Pull request merged**
