### PR TITLE
chore(install): retire broken docker installation instructions

### PR DESCRIPTION
**Pull request by ghuntley**
Related to https://github.com/gitpod-io/gitpod/pull/5144.

I'm all for a `/install/` folder and these docker installation instructions but currently they lead people down the wrong path because the contents are not supported/maintained.

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **corneliusludmann** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ghuntley** [comment]
> At least the `install/docker` thing is something that I maintain (and use) currently. That should work at least for the `0.10.0` release. If we really want to drop it from this repo I would create an additional repo to maintain it there.

💭 let's relocate `install/docker` to `contrib/docker`?

- removes the confusion about install/ 
- removes the need to manage an additional repo
- enables maintaining it (something that is desired)

Yay/Nay?

**Comment by corneliusludmann** [comment]
>  let's relocate `install/docker` to `contrib/docker`?

Sounds great!

> additionally - I would <3 to see the contents of `install/docker` promoted to a first-class citizen that is supported

+1

**Comment by ghuntley** [comment]
`install/docker` relocated to `contrib/docker` but the build is failing. I need a werft/leeway consult to fix ❤️.

**Comment by corneliusludmann** [comment]
@ghuntley Took the liberty and pushed a commit that fixes the werft/leeway issue. Feel free to squash with your commit and let me know whether this is ready for review.

_By the way: Currently, the stuff in contrib will be built only when the `/werft with-contrib` (was `/werft with-installer`) command has been added to the most recent commit or to the pull request._

**Comment by ghuntley** [comment]
> @ghuntley Took the liberty and pushed a commit that fixes the werft/leeway issue. Feel free to squash with your commit and let me know whether this is ready for review.

**Comment by ghuntley** [comment]
LGTM - do the magic `/approve no-issue` and lets go!

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5145#issuecomment-911749033" title="LGTM">corneliusludmann</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5145#issuecomment-911749356" title="Approved">corneliusludmann</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/5145#issuecomment-911749356" title="Approved">corneliusludmann</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
