### PR TITLE
[dashboard] Add George as a dashboard OWNER

### PR DESCRIPTION
**Pull request by jankeromnes**
Thanks for the consistently outstanding PRs and code reviews @gtsiolis! 🎖️ 🎯 

I don't see why @roboquat won't let you approve dashboard Pull Requests. I vote more power to you! 😁 🚀

(Alternatively, we could create a `ux` or `product` team in https://github.com/gitpod-io/gitpod/blob/main/OWNERS_ALIASES, but we can also do that later.)

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jankeromnes** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jankeromnes** [comment]
> This PR is NOT APPROVED

> please ask for approval from jankeromnes after the PR has been reviewed

Lol, I approve my own PR!

/approve no-issue

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5192#issuecomment-898459769" title="Approved">jankeromnes</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/5192#issuecomment-898459769" title="Approved">jankeromnes</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by gtsiolis — COMMENTED** [review]
Thanks, @jankeromnes! 🧡

⬆️ For more context in case anyone reads this, I can still approve changes but @roboquat won't allow merging these PRs without an extra approval from someone from the engineering team (see [`engineering-meta`](https://github.com/gitpod-io/gitpod/blob/6f15a4355420eddec28478b175311c843e4a1198/OWNERS_ALIASES#L11-L19)). We could merge this if this could help us move faster and better as a team, especially since we currently have basic triage operations and code review workflows. 🤖 

🚨 If we merge this I may have to be a bit more frugal with PR approvals and loop in others when a deeper dive into the code changes is needed as well as make good use of labels like `do-not-merge/hold`. 🤠 

⬇️ However, I'm also fine with not being part of the approvers as most of the times we'll also need a review from someone else who can take a deeper dive into the code changes besides the ones affecting the visual aspect of the changes. 🖍️

**Review by svenefftinge — APPROVED** [review]
of course!

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: c033eba33f4b8597054182d86809278916d24921</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5192#issuecomment-898459769" title="Approved">jankeromnes</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/5192#pullrequestreview-746548432" title="Approved">svenefftinge</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/5192#issuecomment-898459769" title="Approved">jankeromnes</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [jankeromnes,svenefftinge]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by gtsiolis** [comment]
Thanks, everyone! 🙂 

artworks-000583566434-tws230-t500x500

**Pull request merged**
