### PR TITLE
[content-service] Fix checkout local HEAD branch

### LINKED ISSUE #13284: Cannot open the workspace when open from the issue
### Bug description

image

### Steps to reproduce

When running the [integration test](https://github.com/gitpod-io/gitpod/blob/9aa153e559070b28547d3ceff055d90898088994/test/tests/workspace/contexts_test.go#L44-L49), it can't open the workspace success.

We create a preview env from the main branch and open the workspace with the URL `github.com/gitpod-io/gitpod-test-repo/issues/88`, the workspace can't be up.

### Workspace affected

_No response_

### Expected behavior

The workspace can open from the issue (LocalBranch mode)

### Example repository

_No response_

### Anything else?

Related to https://github.com/gitpod-io/gitpod/pull/13241

### PR DESCRIPTION
**Pull request by aledbf**
## How to test
- https://aledbf-head.preview.gitpod-dev.com/#https://github.com/gitpod-io/dazzle
- https://aledbf-head.preview.gitpod-dev.com/#https://github.com/gitpod-io/dazzle/commit/ddbf82c1a4dc95bda26c9f299d8e3b8f84eb659d
- https://aledbf-head.preview.gitpod-dev.com/#prebuild/https://github.com/gitpod-io/dazzle
- https://aledbf-head.preview.gitpod-dev.com/#https://github.com/NixOS/nixpkgs
- https://aledbf-head.preview.gitpod-dev.com/#prebuild/https://github.com/NixOS/nixpkgs
- https://aledbf-head.preview.gitpod-dev.com/#https://github.com/gitpod-io/spring-petclinic/tree/ak/vmoptions_test
- https://aledbf-head.preview.gitpod-dev.com/#prebuild/https://github.com/gitpod-io/empty
- https://aledbf-head.preview.gitpod-dev.com/#github.com/gitpod-io/gitpod-test-repo/issues/88

## Related Issue(s)

Fixes #13284

## Release Notes
```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@aledbf: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by utam0k** [comment]
/werft run with-integration-tests=workspace

We should pass this test case
https://github.com/gitpod-io/gitpod/blob/153726046a4ffad746ab7e27ab201683a9100d7f/test/tests/workspace/contexts_test.go#L44-L49

**Review by jenting — APPROVED** [review]

**Comment by atduarte** [comment]
@aledbf added a release note as this is very relevant to the end user

**Comment by utam0k** [comment]
> @aledbf added a release note as this is very relevant to the end user

@atduarte 
This is a fix for a problem that occurred in the refactoring, and from the user's point of view, there should be no change because we didn't release them. WDYT?

**Comment by atduarte** [comment]
@utam0k ah, got it! Thanks for sharing. Will revert back. Sorry @aledbf!

**Pull request merged**
