### PR TITLE
[usage] Add server address to config - WEB-94

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

* Adds server address to usage config - needed for usage to talk to server
* Refactors ClusterAddress construction to use common

## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by atduarte** [comment]
/reviewpad robin prompt review these changes and suggest improvements

**Review by svenefftinge — APPROVED** [review]

**Comment by aledbf** [comment]
/hold

(to unblock the merge queue)

**Comment by aledbf** [comment]
@easyCZ please rebase. I've tried to hold/unhold after several PRs being merged and it still doesn't work

**Pull request merged**
