### PR TITLE
dev/preview:deploy

### PR DESCRIPTION
**Pull request by mads-hartmann**
## Description

This moves the logic related to deploying Gitpod to preview environments into `leeway run dev/preview:deploy-gitpod` - this moves us closer to our goal of [R3: The preview-environment DevLoop should not require CI](https://www.notion.so/gitpod/R3-The-preview-environment-DevLoop-should-not-require-CI-35a93bf299f048a28286ac0e78ace2f7)

### Implementation notes

Generally I maintained the "structure" we had before. We generate the default config, modify it to match our needs, use the installer to render manifests to a file, post-process the manifests to match our needs. We can (and must) simplify this further at a later point. In this PR I just tried to achieve parity with the existing solution, only doing cleanup when I thought it necessary.

There are a few noteworthy changes:

- I deleted `.werft/jobs/build/helm` as most of the files were related to node affinity hacks from when we used core-dev to host preview environments. The few values there were still relevant I managed to inline in the appropriate places instead, removing the indirection.
- We would previously find random pots for `ws-manager` and `registry-facade` and then try to re-use those random ports in subsequent installs. I believe we only had that functionality to support core-dev preview environments, so I simply hardcoded the ports instead.
- There are a few secrets that we mounted in the Werft job. These are now directly read from the `core-dev` cluster instead. 

## Related Issue(s)

Part of https://github.com/gitpod-io/ops/issues/6256

### Using Werft

[Job](https://werft.gitpod-dev.com/job/gitpod-build-mads-dev-preview-deploy.57)

```sh
# with-preview is enabled in the PR description
werft job run github
```

### Using a Gitpod Workspace

From a workspace on this branch

```sh
leeway run dev/preview:create-preview
leeway run dev/preview:build

# Currently it expects the kubectx to be installed. 
# In a workspace that happens in the background automatically but you can trigger it manually using
# previewctl install-context
leeway run dev/preview:deploy-gitpod
```

### Testing the preview environment

So far I tested the happy path. I logged in with GH and opened a workspace (using [gitpod-io/template-typescript-node](https://github.com/gitpod-io/template-typescript-node)) in the preview environment. It worked just fine.

However, this PR indirectly touches some features of preview environments that I'm less familiar with:

- **EE license** - it's enabled by default ([source](https://github.com/gitpod-io/gitpod/blob/df9b12dcf8a0a3a2d6044a97258534bc2dff26be/.werft/jobs/build/job-config.ts#L99)) but the license is now read directly from the secret in core-dev instead of being mounted by werft. I don't know how to test if this is working or not.
- **Agent smith token** - it's generated in a different way and I modified the leeway script which adds it to a preview environment. I don't know how to test if agent-smith works as intended.
- **Workspace feature flags** - from post-process.sh I found a few examples `ws-feature-flags=registry_facade,full_workspace_backup` but I don't know how to test if any of these feature flags are still passed along in the same manner as before.
- **Analytics** - if you pass `-a analytics=segment|<TOKEN>` to a job we enable analytics. I don't know how to test if analytics is working or not.

## Release Notes

```release-note
NONE
```

## Documentation

N/A

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@mads-hartmann: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mads-hartmann** [comment]
⬆️ It's not a secret, but I can understand why it would think so. It's a random string I generated.

**Review by meysholdt — APPROVED** [review]
Code changes LGTM! 🚀

**Review by vulkoingim — APPROVED** [review]
image
❤️ 

We can reduce the big bash script even further - but let's get it merged and we'll deal with it later :) 🚀

**Review by Pothulapati — APPROVED** [review]
LGTM! The analytics stuff need a much bigger change as passing the token through werft is not a great idea (as it gets leaked).

@mads-hartmann and I scheduled a call to brainstrom on the same. So, Shouldn't be a blocker for this PR

**Pull request merged**
