### PR TITLE
Fixed some spelling errors in README.md

### PR DESCRIPTION
**Pull request by AMetIR**
## Description

Fixed the spelling errors in the README.md 
## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@AMetIR: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by gtsiolis — APPROVED** [review]
Thanks for contributing, @AMetIR! 🍊 

Changes [LGTM](https://en.wiktionary.org/wiki/LGTM).

Approving to unblock merging but holding as you'll also need to sign a Contributor License Agreement (CLA)[[1](https://en.wikipedia.org/wiki/Contributor_License_Agreement)] once before merging your first contribution. Looping in @meysholdt to reach out about the CLA. 🏓

/hold

**Comment by meysholdt** [comment]
hi @AMetIR, and thank you for your contribution! Can you please sign our CLA via [this DocuSign form](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=30e1aa46-cce5-4bc6-a933-ad02cd8d5ada&env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&v=2)? If there are any questions, you can reach me via moritz@gitpod.io.

**Comment by meysholdt** [comment]
Thank you for singing the CLA!

**Comment by gtsiolis** [comment]
Thanks @meysholdt @AMetIR! Let's merge this!

/werft run

**Pull request merged**
