### PR TITLE
[supervisor] add http binding for create private ssh keys

### PR DESCRIPTION
**Pull request by akosyakov**
## Description

There is not grcp web client for Java.
I would like to use plain http request to resolve it in order to establish SSH over Web Socket tunnel.

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖 Generated by Copilot at e09fd26</samp>

This pull request adds HTTP support for the CreateSSHKeyPair method of the control service in the supervisor API, using Google API annotations in the proto file. It also updates the generated code for Go and Java to use the annotations and fixes some minor issues in the Go code.

</details>

## Related Issue(s)

Fixes #

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by akosyakov** [comment]
@mustard-mh Could you review it please? I'm short on time, sorry.

**Review by mustard-mh — APPROVED** [review]
LGTM

**Comment by mustard-mh** [comment]
No preview to test, but code LGTM, generate.sh / generate-java.sh exec ok

**Pull request merged**
