### PR TITLE
registry-facade: fix typo

### PR DESCRIPTION
**Pull request by jenting**
## Description

Fix typo

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/pull/14042/files#r1001296126

## Release Notes

```release-note
None
```

## Documentation

None

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Review by utam0k — APPROVED** [review]

**Review by aledbf — APPROVED** [review]

**Comment by jenting** [comment]
/hold
CI not pass

**Pull request merged**
