### PR TITLE
[server] Add project and branch to bitbucket prebuilds

### PR DESCRIPTION
**Pull request by wezzle**
## Description
Prebuilds for Bitbucket are currently in a weird space because of the missing project and branch. They don't show up in the dashboard, because they are missing the project id. If Bitbucket triggers a rebuild that's not showing in the dashboard you're not allowed to start a prebuild yourself as there's already a prebuild linked to the current commit hash.

Prebuilds triggered by Bitbucket do not inject the project variables because of the missing project id. This causes my prebuild to fail but also blocks me from running one from the dashboard that would inject the project variables.

## Related Issue(s)
[TODO in code](https://github.com/gitpod-io/gitpod/blob/d418735136fe1e7c2f6cbac6cab4bc993e5c5949/components/server/ee/src/prebuilds/bitbucket-app.ts#L93)

## How to test
1. Link bitbucket account
2. Create project
3. Add a `.gitpod.yml` with a prebuild step like `echo $PROJECT_VAR`
4. Fill in a value for `PROJECT_VAR` in the dashboard's project settings
5. Push a change to Bitbucket to trigger the webhook and prebuild

## Release Notes

```release-note
```

### CODE REVIEW

**Comment by roboquat** [comment]
@wezzle: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankeromnes** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankeromnes` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by wezzle** [comment]
This is untested. I have no idea how to test the code in an actual working gitpod server environment.

**Comment by AlexTugarev** [comment]
Thanks for the contribution! I‘m afraid this is already tackled in https://github.com/gitpod-io/gitpod/pull/7833 in parallel.

**Comment by JanKoehnlein** [comment]
Siew @AlexTugarev's comment

**Comment by jankeromnes** [comment]
Hi @wezzle, just wanted to say THANK YOU again for raising this important issue, and even submitting a Pull Request to fix it. 💯 x 🙏

**Pull request closed without merging**
