### PR TITLE
Update buildkit to v0.10.0

### PR DESCRIPTION
**Pull request by aledbf**
## Description

Update buildkit to [v0.10.0](https://github.com/moby/buildkit/releases/tag/v0.10.0)

From the release:
- Layers can now be exported with eStargz compression type -o compression=estargz https://github.com/moby/buildkit/pull/2246 https://github.com/moby/buildkit/pull/2603 https://github.com/moby/buildkit/pull/2352 **https://github.com/moby/buildkit/pull/2674**

We should also see an improvement in build times

## How to test

- Builds should keep working
 
## Release Notes

```release-note
Update buildkit to v0.10.0
```

### CODE REVIEW

**Review by MrSimonEmms — APPROVED** [review]

**Comment by princerachit** [comment]
Changes lgtm. Did we test it in a preview cluster? Asking as we had an issue few months back due to kernel version mismatch in core-dev vs production cluster for seccomp related library IIRC

**Comment by princerachit** [comment]
/hold

Feel free to remove the hold label @aledbf

**Review by princerachit — APPROVED** [review]

**Comment by kylos101** [comment]
I tried opening the `dazzle` [[1](https://aledbf-buildkit.staging.gitpod-dev.com/#https://github.com/gitpod-io/dazzle)] and `workspace-images` [[2](https://aledbf-buildkit.staging.gitpod-dev.com/#https://github.com/gitpod-io/workspace-images)] repos but get an error:

image

In the [logs](https://cloudlogging.app.goo.gl/tfP4zFfcDvmcSu5N6), I see this [message](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-03-22T22:10:33Z;query=%22aledbf-buildkit%22%0A%22image-builder-mk3%22%0Atimestamp%3D%222022-03-22T22:10:33Z%22%0AinsertId%3D%22p9ux18gwzdehcx6j%22;timeRange=PT30M?project=gitpod-core-dev):

```json
 {
host: "eu.gcr.io"
level: "info"
message: "trying next host - response was http.StatusNotFound"
}
```

Need to grab a bite for now, but, wanted to share.

**Comment by aledbf** [comment]
That's fine. Let's see if we can pull and run the images

**Comment by kylos101** [comment]
Pulls and runs with Docker, from within a Gitpod workspace (below).

@aledbf did you mean for us to pull and run with `nerdctl` too, or use it as a base image in a Gitpod workspace, too?

```bash
gitpod /workspace/template-python-flask $ docker pull gitpod/workspace-base:2022-03-22-23-33-48
2022-03-22-23-33-48: Pulling from gitpod/workspace-base
7c3b88808835: Pull complete 
1a6c7d47e350: Pull complete 
9b9520697272: Pull complete 
1053a3433f50: Pull complete 
ec9286dc5cb1: Pull complete 
deddeec0851f: Pull complete 
7239558c491a: Pull complete 
144a66bbcecf: Pull complete 
dba6875c6cab: Pull complete 
db7fd1dc56ad: Pull complete 
c0f79738a6ca: Pull complete 
cf2dda9310a4: Pull complete 
4c0bb169f4fa: Pull complete 
c150e288551f: Pull complete 
2bf42b2cf4e4: Pull complete 
6af2bf264877: Pull complete 
0f56f319ee7f: Pull complete 
12f57f1f477a: Pull complete 
Digest: sha256:7a77532e8c2c0eead2f80bf992c5a9f6f5cc193b866f62e714a94e3a0add28b5
Status: Downloaded newer image for gitpod/workspace-base:2022-03-22-23-33-48
docker.io/gitpod/workspace-base:2022-03-22-23-33-48

gitpod /workspace/template-python-flask $ docker run -it --rm gitpod/workspace-base:2022-03-22-23-33-48
gitpod ~ $ ls
gitpod ~ $ pwd
```

**Pull request merged**
