### PR TITLE
[installer] Refactor generation of templates configmap

### PR DESCRIPTION
**Pull request by aledbf**
## Description

With the introduction of workspace classes and the default `gitpod.io/internal/xl` we need to change the path to not contain "directories".

``` 
"templates": {
  "defaultPath": "/workspace-templates/gitpod.io-internal-xl-default.yaml",
  "regularPath": "/workspace-templates/gitpod.io-internal-xl-regular.yaml",
  "prebuildPath": "/workspace-templates/gitpod.io-internal-xl-prebuild.yaml",
  "imagebuildPath": "/workspace-templates/gitpod.io-internal-xl-imagebuild.yaml"
},
```

## Release Notes
```release-note
[installer] Refactor generation of templates configmap #9868
```

### CODE REVIEW

**Comment by roboquat** [comment]
@aledbf: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by utam0k — APPROVED** [review]

**Comment by csweichel** [comment]
We could still use directories - just sanitise the class name as done here in this PR

**Comment by aledbf** [comment]
> We could still use directories - just sanitise the class name as done here in this PR

that is not a valid name in a configmap (fails with a similar error to label values)

**Comment by csweichel** [comment]
superseeded by https://github.com/gitpod-io/gitpod/pull/9895?

**Pull request closed without merging**
