### PR TITLE
[workspace] change iface name to eth0

### PR DESCRIPTION
**Pull request by iQQBot**
## Description

[workspace] change iface name to eth0

part of #16363

## Related Issue(s)

Fixes #

## How to test

Test in #16363

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-slow-database
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft with-integration-tests=workspace
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by kylos101** [comment]
/werft run with-integration-tests=workspace with-large-vm=true

**Comment by akosyakov** [comment]
@Furisto I've rebased it.

**Comment by aledbf** [comment]
Someone needs to update the [docker compose PR](https://github.com/docker/compose/compare/v2...gitpod-io:compose:custom-mtu#diff-1f4d596600c620b3df55dbfbc63e50a6f43b356865fae411c553d0937fbb6d91R1121), publish a release and [update the code like](https://github.com/gitpod-io/gitpod/pull/12280)  or docker-compose will break in the next deployment

cc @kylos101

**Comment by kylos101** [comment]
Thanks @aledbf , I will do soon, appreciate the heads up!

**Pull request merged**
