### PR TITLE
[server] allow configure timeouts via featureflag

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description

Introduces `disable_set_timeout` (boolean) feature flag that allow to set whether users can change/extend the timeouts of a workspace when in in PAYG mode.

## Related Issue(s)

Fixes https://linear.app/gitpod/issue/ENT-447/org-wide-timeout-default

## How to test

The feature flag `disabled_set_timeout` is set to `true` for the preview env.
Test: 
- Start a workspace and try to change the timeout. You'll see an error message.

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - se-org-widc1faf03bd1</li>
	<li><b>🔗 URL</b> - <a href="https://se-org-widc1faf03bd1.preview.gitpod-dev.com/workspaces" target="_blank">se-org-widc1faf03bd1.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - se-org-wide-timeout-limit-gha.27433</li>
	<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-se-org-widc1faf03bd1%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws-manager-mk2%22%0A;duration=P1D?project=gitpod-dev-preview" target="_blank">GCP Logs Explorer</a></li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by filiptronicek** [comment]
@svenefftinge according to our simple feature flag guidelines:

> we never use feature flags to distinguish between different environments (preview, gitpod.io, Dedicated)

If we want to go ahead with this, can we at least get the feature flags into the [ff doc](https://www.notion.so/gitpod/Cleanup-Feature-Flags-for-Enterprise-ebcfb63f7cbd472eabe9cf8fe4a858e9?pvs=4) along with an explanation why it's necessary?

**Comment by svenefftinge** [comment]
We are disabling a feature (setTimeout) and allowing to change a default (workspaceTimeout)
I don't think this change breaks with this rule 
> we never use feature flags to distinguish between different environments (preview, gitpod.io, Dedicated)

**Comment by svenefftinge** [comment]
> If we want to go ahead with this, can we at least get the feature flags into the [ff doc](https://www.notion.so/gitpod/Cleanup-Feature-Flags-for-Enterprise-ebcfb63f7cbd472eabe9cf8fe4a858e9?pvs=4) along with an explanation why it's necessary?

I have added information about the semantics of the feature flags in configcat itself, which is the source of truth IMHO.

**Comment by filiptronicek** [comment]
> We are disabling a feature (setTimeout) and allowing to change a default (workspaceTimeout)
I don't think this change breaks with this rule

You're right, it's not directly inferring the environment and hence fine. I think it just looked to me a bit like we're abusing feature flags :P

**Review by filiptronicek — APPROVED** [review]
Approving to unblock. Code looks good

**Comment by svenefftinge** [comment]
I have removed the option to change the default for now as that was not original requested by the customer.

**Pull request merged**
