### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by lucasvaltl**
## Description
Changed the wording to point to the default installation method we want people to use.

Related to https://github.com/gitpod-io/website/pull/1975

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by corneliusludmann — APPROVED** [review]
Looks good. Go for it! 🚀

**Comment by geropl** [comment]
@lucasvaltl Sorry, had to move back to draft bc it was blocking the merge queue. :confused:

**Comment by corneliusludmann** [comment]
Wanted to do this as well right now. Thanks Gero! :pray: 

@lucasvaltl I guess you need to rebase this PR anyways to fix the build error as soon as https://github.com/gitpod-io/gitpod/pull/9648 is in.

**Comment by felladrin** [comment]
@lucasvaltl I confirm that rebasing the branch will solve the problem of Werft failing to build.

**Comment by lucasvaltl** [comment]
Eeeeh I tried rebasing, let's just say I'm just going to start with a fresh PR :D Feels like that is easier. Closing this and restarting this :)

**Pull request closed without merging**
