### PR TITLE
chore: capitalize proper noun Git in dashboard components

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Description

- Capitalize proper noun Git in dashboard components

## Related Issue(s)

Driveby PR, not closing any issue with this.

## How to test

1. Review changes in the PR for correct spelling/capitalization.
1. Find way to preview dashboard components on a dev server.
1. Find way to run the tests, to confirm I'm not breaking any Jest snapshots or other test files.

This is my first contribution to the Gitpod program itself.
I did not find any developer documentation on how to run a dev server which shows me the components, so I can verify my changes myself.

Also please review/edit my Release Notes below, I hope this is the correct format.

## Release Notes

```release-note
capitalize proper noun Git in dashboard components
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankoehnlein** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankoehnlein` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by jankeromnes — APPROVED** [review]
Wow, thanks a lot for the attention to detail and thoroughness! This contribution is awesome and makes me very happy. ✨

Code changes look perfect to me:

/lgtm

There is also no need for an issue:

/approve no-issue

One question that I'm a bit unclear on is whether signing a Contributor License Agreement is needed here. So, pausing the auto-merger until we've clarified this:

/hold

Many thanks! 🙏

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 7b1fe79cc2470a00e921f009715b8a4d8cdfcc37</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5990#pullrequestreview-770675816" title="Approved">jankeromnes</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/5990#pullrequestreview-770675816" title="Approved">jankeromnes</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by HonkingGoose** [comment]
I think Werft doesn't like my long branch name:

```
cannot handle job for gitpod-build-chore-capitalize-proper-noun-git-in-dashboard-fork.0: Pod "gitpod-build-chore-capitalize-proper-noun-git-in-dashboard-fork.0" is invalid: metadata.labels: Invalid value: "gitpod-build-chore-capitalize-proper-noun-git-in-dashboard-fork.0": must be no more than 63 characters
```

How do you want me to proceed?

**Comment by jankeromnes** [comment]
Ah, excellent find @HonkingGoose! That's indeed the problem (I think too-long branch names cause problems in Werft while generating certificates).

Could you please push your commit to a shorter branch name and re-open this PR? I'm happy to approve it again. 🙏

**Comment by HonkingGoose** [comment]
Superseded by #6039.

**Pull request closed without merging**
