### PR TITLE
fix: new project widget broken if 'null' item(s) received from gh api

### PR DESCRIPTION
**Pull request by szab100**
## Description
The |Team or persona scope| / Projects / New Project widget has been super slow since the feature's debut when running against large Github Enterprise instances with 10s of thousands of repositories under many-100 git-orgs. Since the current implementation is filtering to show only the repos where the current user has 'admin' permissions only after all pages are fetched and it makes the UI wait for the entire result set to be fetched before returning, the UI is frozen for 5-10+ minutes.

Still, even as being frozen / super slow (added a TODO to fix / optimize), this feature remained usable, since it is a one-time project setup. However, since we upgraded to GH Enterprise v 3.x, it seems that some returned pages might contain one or more null items, where the current filter expression fails. This PR simply aims at fixing this blocking issue, while not giving a remedy yet for the slowness of this API call.

## Related Issue(s)
https://github.com/gitpod-io/gitpod/issues/11628
https://github.com/gitpod-io/gitpod/issues/11629

Fixes #
https://github.com/gitpod-io/gitpod/issues/11629

## How to test
The fix should be trivial, simply ensure the feature still works after applying this change.

## Release Notes
```release-note
fix: new project widget broken if 'null' item(s) received from gh api
```

### CODE REVIEW

**Review by andrew-farries — APPROVED** [review]
Thanks @szab100. The change looks good. This feels like a bug in GHE or octokit - perhaps worth following up with those projects.

/hold for CLA

**Comment by meysholdt** [comment]
hi @szab100, and thank you for your contribution! Can you please sign our CLA via [this DocuSign form](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=30e1aa46-cce5-4bc6-a933-ad02cd8d5ada&env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&v=2)? If there are any questions, you can reach me via moritz@gitpod.io.

**Comment by szab100** [comment]
> hi @szab100, and thank you for your contribution! Can you please sign our CLA via [this DocuSign form](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=30e1aa46-cce5-4bc6-a933-ad02cd8d5ada&env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&v=2)? If there are any questions, you can reach me via [moritz@gitpod.io](mailto:moritz@gitpod.io).

done.

**Comment by meysholdt** [comment]
Thx for signing the CLA!

**Comment by szab100** [comment]
> Thanks @szab100. The change looks good. This feels like a bug in GHE or octokit - perhaps worth following up with those projects.
> 
> /hold for CLA

I agree, that octokit client lib should never really return 'null' values, perhaps it is due to failed / retried paginated requests.

About the other mentioned issue (performance): it would be nice to see an improvement on that too soon, a few more comments / suggestions for that:
- a pure typeahead search would probably provide a great user experience as it could completely eliminate waiting..
- we might want to return the current_user != admin repos as well, marking the objects, so the UI can show them as greyed out / unselectable (with a comment explaining this action needs admin) => less confusing than not seeing the repository the user is looking for.
- returning a stream could be good too, the UI could interactively load the results & show the progress (not sure if octokit returns the counter or # of total pages upfront to show a deterministic progress bar).
- I have not tested, but I believe even just adding the 'affiliation: collaborator' (server-side) filter to the current octokit call would make it much better than today as - although it is a lower permission level than we need - it should greatly decrease the number of pages to fetch & further filter on, skipping the prob 10s of thousands of repositories where the user is not even a collaborator.

**Comment by andrew-farries** [comment]
> a few more comments / suggestions for that:

Thanks for these 👍. I've added them to https://github.com/gitpod-io/gitpod/issues/11628 so they don't get lost.

**Pull request merged**
