### PR TITLE
Use prebuild workspace class for regular workspaces

### PR DESCRIPTION
**Pull request by Furisto**
## Description
Ensure that if a prebuild is used to create a workspace a class is used that is appropriate for the workspace; meaning if the prebuild has a workspace class greater than the currently configured one by the customer the prebuild class is used, otherwise the class configured by the customer is used. 

## Related Issue(s)
Fixes #https://github.com/gitpod-io/gitpod/issues/11972
Needs https://github.com/gitpod-io/ops/pull/3728

## How to test
- Select workspace class g1-large
- Start a prebuild 
- Select workspace class g1-standard
- Create a regular workspace from prebuild
- The workspace should have g1-large 
--
- Start a prebuild for another repository (with g1-standard)
- Select workspace class g1-large
- Create a regular workspace from prebuild
- The workspace should have g1-large

## Release Notes

```release-note
None
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@Furisto: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jankeromnes** [comment]
> if the prebuild has a workspace class greater than the currently configured one by the customer the prebuild class is used

Apologies for the drive-by thought, but can't this have potentially unwanted consequences like:
- one user prefers XL but has also set up Prebuilds for a project, thus "forcing" every project member to also use XL?
- a team on a business plan using XL for an open source project, thus forcing every external contributor to also use XL?

Not blocking for this PR, but we'll probably need to figure out a good UX for these cases. 🤔

**Comment by Furisto** [comment]
@jankeromnes You are absolutely correct. This needs better UX, but we will enable this feature for only a very limited number of customers first, where it is understood that this is the current behavior. See https://gitpod.slack.com/archives/C02F19UUW6S/p1659639905273709 for some internal discussion about this.

**Review by laushinka — APPROVED** [review]
Works as advertised!

**Pull request merged**
