### PR TITLE
added support for cleanSlateDeployment

### LINKED ISSUE #7542: Support `with-clean-slate-deployment`
When the Werft job creates preview environments on Harvester, it should honor the `with-clean-slate-deployment` flag.

Proposed solution: When the flag is set, the job should delete the preview-namespace on Harvester before proceeding to create the VM. This should force the job to effectively to a "clean slate install", because deleting the namespace also deletes the VM.

### PR DESCRIPTION
**Pull request by wulfthimm**
## Description

This adds clean-slate-deployment for preview-environments on Harvester.

## Related Issue(s)

Fixes #7542

## How to test

Make two commits on a new branch with the comment `/werft with-vm=true`. The first one will create a new prev-environment, the second one will do remove the previous installation when the comment `/werft with-clean-slate-deployment=true` is added.

## Release Notes

```release-note
None
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jeanp413** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jeanp413` in a comment when ready.

Associated issue: *#7542*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by mads-hartmann — COMMENTED** [review]
Thanks Wulf! So far I have just been deleting the namespace, what's the benefit of deleting the manifest explicitly before deleting the namespace? ☺️

**Comment by wulfthimm** [comment]
> Thanks Wulf! So far I have just been deleting the namespace, what's the benefit of deleting the manifest explicitly before deleting the namespace? relaxed

When a complete namespace is removed at once it might get stuck in the terminating phase. Therefor I would like to remove the resources one after anthor to make debuggung easier.

**Review by mads-hartmann — APPROVED** [review]
Based on Wulf's comment, this LGTM

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: f8bf0cd581548505d363e652d7dbd1de69f51c65</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7614#pullrequestreview-855332242" title="Approved">mads-hartmann</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jeanp413** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jeanp413` in a comment when ready.

Associated issue: *#7542*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Review by mads-hartmann — APPROVED** [review]

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: c5f174b34a5e26a8296ad863a52be008d9bc9633</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7614#pullrequestreview-855433013" title="Approved">mads-hartmann</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jeanp413** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jeanp413` in a comment when ready.

Associated issue: *#7542*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7614#pullrequestreview-855433013" title="Approved">mads-hartmann</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7614#issuecomment-1015419485" title="Approved">wulfthimm</a>*

Associated issue: *#7542*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
