### PR TITLE
Debug: Experimenting with Werft annotation behaviours

### PR DESCRIPTION
**Pull request by mads-hartmann**
## Related Issue(s)

Fixes #

## Release Notes

```release-note
```

## Werft options:

/werft foo=bar

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@mads-hartmann: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mads-hartmann** [comment]
Testing to see how it merges annotations, e.g. will the one below still contain "with-preview"?

/werft run foo=test

**Comment by mads-hartmann** [comment]
I'm going to force push now to see what happens (if it uses the annotations in the PR description or not) - we previously saw that it didn't (https://github.com/gitpod-io/ops/issues/3913) so I'm trying to reproduce

**Comment by mads-hartmann** [comment]
Last experiment. The `werft` cli acts the same was a the `/werft` comments

```
werft job run github
# https://werft.gitpod-dev.com/job/gitpod-build-mads-testing-werft-annotations.4

werft job run github -a foo=test
# https://werft.gitpod-dev.com/job/gitpod-build-mads-testing-werft-annotations.5
```
Screenshot 2022-10-04 at 10 14 17
Screenshot 2022-10-04 at 10 14 23

**Pull request closed without merging**
