### PR TITLE
[code] feat(gitpod): adjust community links

### PR DESCRIPTION
**Pull request by ghuntley**
related to https://github.com/gitpod-io/vscode/pull/22/commits/b7f0408623b78cfcce2c354ecd00e8f67bb6b649

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **fntlnz** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @fntlnz` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by akosyakov** [comment]
@ghuntley ping me when it is good for review

**Comment by akosyakov** [comment]
will be a part of https://github.com/gitpod-io/gitpod/pull/5107

**Pull request closed without merging**
