### PR TITLE
[server] Introduce and use a ErrorCodes.INTERNAL_SERVER_ERROR

### PR DESCRIPTION
**Pull request by jankeromnes**
## Description

Refactor hard-coded `ResponseError(500, msg)` --> `ResponseError(ErrorCodes.INTERNAL_SERVER_ERROR, msg)`

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/pull/10378#discussion_r892048343

## How to test

- Should build

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]

**Comment by easyCZ** [comment]
@jankeromnes In the PR, you can set the base of this PR to be another branch. That way you create stacked PRs. It allows you to make changes on top of the previous one and have this one (almost) automatically rebased once the previous lands.

**Comment by jankeromnes** [comment]
Interesting -- I know you could make PRs target other branches, but if the other branch's PR gets merged, does this PR automatically re-target to `main`?

**Comment by easyCZ** [comment]
For the above to work, normally the following works:

```
git checkout my-first-branch

git checkout -b my-stacked-branch

# make some changes

#commit and push
# the push now contains my-first-branch and also my-stacked-branch changes
# set the PR base to my-first-branch

```

> does this PR automatically re-target to main?

Try it. But yes, it does.

**Pull request merged**
