### PR TITLE
[dashboard] Add more actions to workspace ready page

### LINKED ISSUE #6769: Simplify button labels on desktop IDE open page
**suggestion**: Although I appreciate the accuracy here, I still think this could be simplified as mentioned in https://github.com/gitpod-io/gitpod/pull/6270#discussion_r734679322 but do not want to go back and forth. I'd like to suggest once more going with something like _Open in XYZ_ but I'll leave this to you to decide.

**thought**: Also, happy to discuss this in a new follow up issue or https://github.com/gitpod-io/gitpod/issues/6602. Maybe updating the design here to be less verbose or using different elements could help facilitate more verbose options like _Open in VS Code Insiders on Desktop_. Cc @loujaybee  🏓 

In this case it would become _Open in VS Code Insiders_ while the secondary option would be :a: _Open in Browser_ or  :b: _Open in Gitpod_. See also https://github.com/gitpod-io/gitpod/pull/6270#discussion_r735492810.

| BEFORE | AFTER :a: | AFTER :b: |
|-|-|-|
| Screenshot 2021-11-18 at 1 16 17 AM (2) | Screenshot 2021-11-18 at 1 18 17 AM (2) | Screenshot 2021-11-18 at 1 16 35 AM (2) |

_Originally posted by @gtsiolis in https://github.com/gitpod-io/gitpod/pull/6671#discussion_r751724993_

### LINKED ISSUE #6841: Return to Dashboard link on the Your Workspace is Ready screen
## Is your feature request related to a problem? Please describe

No
## Describe the behaviour you'd like

It would be nice to have a "Return to Dashboard" button on the "Your Workspace is Ready!" screen.

image

### PR DESCRIPTION
**Pull request by corneliusludmann**
## Description

This PR adds more actions to the “Your Workspace is Ready” page and adds a hint to the preferences [proposed by Lou](https://github.com/gitpod-io/gitpod/issues/6769#issuecomment-975317543).

image

image

## Related Issue(s)

Fixes #6769 and fixes #6841

## How to test

Open a workspace with a desktop IDE enabled in the preferences and check that all links are working.

## Release Notes

```release-note
The “Your Workspace is Ready” page for desktop IDEs now has “Stop Workspace” and “Go to Dashboard” actions.
```

## Documentation

@loujaybee Any docs updates needed?

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **geropl** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @geropl` in a comment when ready.

Associated issue: *#6769*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**
- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by JanKoehnlein** [comment]
/lgtm

Sorry for the late review

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 9c53315b8ba69a2e4eed4363a8ab614ce09f654b</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6847#issuecomment-977855210" title="LGTM">JanKoehnlein</a>*

Associated issue: *#6769*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [JanKoehnlein]
- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [JanKoehnlein]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
