### PR TITLE
[local-companion-app] Fix ssh_config generation on Windows

### LINKED ISSUE #4759: ssh connection: customizing ssh key
(based on #1781)

now that we can connect to our workspace via vscode ssh remote it would be nice not to force a specific ssh key name/type on the user.

for example I am using: `~/.ssh/id_ed25519.pub`

therefore it would be great to configure this

### LINKED ISSUE #4768: Gitpod Local Companion doesn't write SSH config file on Windows
### Bug description

Attempting to run with windows executable for Gitpod Local Companion results in an error message:

time="2021-07-10T20:23:05+01:00" level=error msg="cannot write ssh config file" error="open /tmp/gitpod_ssh_config: The system cannot find the path specified." path=/tmp/gitpod_ssh_config

### Steps to reproduce

run `gitpod-local-companion-windows.exe` and see the above mentioned error message

### Expected behavior

Should successfully create the SSH Config so I can SSH into the workspaces :) 

### Example repository

_No response_

### Anything else?

Keep up the good work!

### PR DESCRIPTION
**Pull request by csweichel**
fixes #4768

This PR fixes the `ssh_config` file generation on Windows by introducing a more sensible default to the `--ssh-config` flag. Instead of hardcoding `/tmp` it defaults to `os.TmpDir()` if the `GOOS == "windows"`. 

fixes #4759 

In addition, this PR introduces fresh SSH keypair generation for each workspace. This way we don't rely on the user having a keypair generated already, and don't spread the user's `id_rsa.pub` content around. Also, the SSH public key upload is now properly synchronised (before it was just `time.Sleep(500 * time.Millisecond)`).

### How to test
1. Download the local app build from this branch
2. Run the local app (e.g. against prod).
3. SSH'ing into your workspace should work OOTB

### CODE REVIEW

**Comment by akosyakov** [comment]
@jmcelreavey @extrawurst Could you please give it a try?
```
# mac
curl -OL https://ak-vscode-tunnel-provider.staging.gitpod-dev.com/static/bin/gitpod-local-companion-darwin
chmod +x ./gitpod-local-companion-darwin
./gitpod-local-companion-darwin --mock-keyring

# linux
# curl -OL https://ak-vscode-tunnel-provider.staging.gitpod-dev.com/static/bin/gitpod-local-companion-linux
chmod +x ./gitpod-local-companion-linux
./gitpod-local-companion-linux --mock-keyring

# windows
# curl -OL https://ak-vscode-tunnel-provider.staging.gitpod-dev.com/static/bin/gitpod-local-companion-windows.exe
./gitpod-local-companion-windows.exe --mock-keyring
```

**Review by akosyakov — APPROVED** [review]
works well

**Comment by leodido** [comment]
Works like a charm! Thank you! 👏

**Comment by jmcelreavey** [comment]
Sorry the links above no longer work. How do I go about generating a new .exe file? :)

**Comment by akosyakov** [comment]
It should be deployed soon, you also can do following:
- open a new workspace https://gitpod.io/#https://github.com/gitpod-io/gitpod
- run `leeway build components/local-app:app-windows --serve=:8080`
- press open in browser for 8080 when notification appears and download latest distributable, i.e. `local-app.exe`

**Comment by jmcelreavey** [comment]
> It should be deployed soon, you also can do following:
> 
> * open a new workspace https://gitpod.io/#https://github.com/gitpod-io/gitpod
> * run `leeway build components/local-app:app-windows --serve=:8080`
> * press open in browser for 8080 when notification appears and download latest distributable, i.e. `local-app.exe`

You sir are a true hero, that worked perfectly! Thanks. 👍

**Pull request merged**
