### PR TITLE
Revert "[bridge] Fix wrong mapping of WorkspaceStatus to prebuild when "snapshot" is missing"

### PR DESCRIPTION
**Pull request by geropl**
Reverts gitpod-io/gitpod#9924

 - [x] /werft no-preview=true

### CODE REVIEW

**Comment by roboquat** [comment]
@geropl: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by csweichel** [comment]
What broke with the original change?

**Comment by geropl** [comment]
@csweichel no updates to prebuilds, at all. 😬

**Review by laushinka — APPROVED** [review]

**Pull request merged**
