### PR TITLE
try reconnect 15 times to ws on bad handshake with 3xx or 4xx status code

### LINKED ISSUE #5762: When server restart, running workspace is not allow pull/push git repo
### Bug description

When `server` restart, running workspace is not allow pull/push git repo.

see log in /tmp/gitpod-git-credential-helper.log
time="2021-09-20T04:36:59Z" level=info msg="error getting token from supervisior" error="rpc error: code = NotFound desc = no token available"

in supervisor log 
2021/09/19 16:46:28 jsonrpc2: protocol error: reconnecting-ws: bad handshake: code 200

websocket is not reconnect when server is start.

https://github.com/gitpod-io/gitpod/blob/9255ef2aa29e178603ace04dcc41da24e7e20915/components/gitpod-protocol/go/reconnecting-ws.go#L200-L203

### Steps to reproduce

delete server pod, then try git pull in any running workspace

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by akosyakov**
- [x] /werft with-clean-slate-deployment

## Description

Recently we changed the reconnecting web socket to allow propagate bad handshake errors to clients, that they can handle failed auth for instance in the case of the local app. It caused the issue thought that the bad handshake returned by some intermediate software like the proxy since it cannot proxy to the target host like in the case of server restart, and consequently complete breaks connection.

This PR changes the reconnecting web socket to propagate bad handshake only for 3xx or 4xx status code, otherwise it tries to reconnect 15 times, so around 5mins and then fails too.

## Related Issue(s)

fix #5762

## How to test

- Start a workspace, and monitor logs.
- Delete the server several times, each time checks that supervisor reconnects in ws logs.

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankoehnlein** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankoehnlein` in a comment when ready.

Associated issue: *#5762*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
Workspace logs are spilled with:
```
{"grpc.code":"OK","grpc.method":"ContentStatus","grpc.service":"supervisor.StatusService","grpc.start_time":"2021-09-20T09:52:43Z","grpc.time_ms":0.035,"level":"info","message":"finished unary call with code OK","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","span.kind":"server","system":"grpc","time":"2021-09-20T09:52:43Z"}
{"grpc.code":"OK","grpc.method":"ContentStatus","grpc.service":"supervisor.StatusService","grpc.start_time":"2021-09-20T09:52:44Z","grpc.time_ms":0.027,"level":"info","message":"finished unary call with code OK","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","span.kind":"server","system":"grpc","time":"2021-09-20T09:52:44Z"}
{"grpc.code":"OK","grpc.method":"ContentStatus","grpc.service":"supervisor.StatusService","grpc.start_time":"2021-09-20T09:52:45Z","grpc.time_ms":0.036,"level":"info","message":"finished unary call with code OK","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","span.kind":"server","system":"grpc","time":"2021-09-20T09:52:45Z"}
{"grpc.code":"OK","grpc.method":"ContentStatus","grpc.service":"supervisor.StatusService","grpc.start_time":"2021-09-20T09:52:46Z","grpc.time_ms":0.028,"level":"info","message":"finished unary call with code OK","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","span.kind":"server","system":"grpc","time":"2021-09-20T09:52:46Z"}
{"grpc.code":"OK","grpc.method":"ContentStatus","grpc.service":"supervisor.StatusService","grpc.start_time":"2021-09-20T09:52:47Z","grpc.time_ms":0.034,"level":"info","message":"finished unary call with code OK","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","span.kind":"server","system":"grpc","time":"2021-09-20T09:52:47Z"}
{"grpc.code":"OK","grpc.method":"ContentStatus","grpc.service":"supervisor.StatusService","grpc.start_time":"2021-09-20T09:52:48Z","grpc.time_ms":0.038,"level":"info","message":"finished unary call with code OK","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","span.kind":"server","system":"grpc","time":"2021-09-20T09:52:48Z"}
{"grpc.code":"OK","grpc.method":"ContentStatus","grpc.service":"supervisor.StatusService","grpc.start_time":"2021-09-20T09:52:49Z","grpc.time_ms":0.027,"level":"info","message":"finished unary call with code OK","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","span.kind":"server","system":"grpc","time":"2021-09-20T09:52:49Z"}
{"grpc.code":"OK","grpc.method":"ContentStatus","grpc.service":"supervisor.StatusService","grpc.start_time":"2021-09-20T09:52:50Z","grpc.time_ms":0.028,"level":"info","message":"finished unary call with code OK","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","span.kind":"server","system":"grpc","time":"2021-09-20T09:52:50Z"}
{"grpc.code":"OK","grpc.method":"ContentStatus","grpc.service":"supervisor.StatusService","grpc.start_time":"2021-09-20T09:52:51Z","grpc.time_ms":0.026,"level":"info","message":"finished unary call with code OK","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","span.kind":"server","system":"grpc","time":"2021-09-20T09:52:51Z"}
```

But I think this is unrelated.
/cc @aledbf

**Review by geropl — APPROVED** [review]
Code looks good, tested and works: :+1:

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 4318a854523e3daa507367161f9caa2b43850585</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5766#pullrequestreview-758441851" title="Approved">geropl</a>*

Associated issue: *#5762*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [geropl]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by akosyakov** [comment]
@geropl logs are expected, in debug we log all incoming grpc traces including probes.

**Pull request merged**
