### PR TITLE
content-service: fix incorrect user:group after git operation

### LINKED ISSUE #12420: [PVC] the files and folders under .git/ permission is incorrect
### Bug description

The files and folders under `.git/` permission are incorrect. Some files and folders permission under `.git/*` with correct permission `gitpod:gitpod`, but some folders permission under `.git/object/*` is `root:root`.

It causes when we want to git add the change, we encounter the permission error.
```console
$ git add .
error: insufficient permission for adding an object to repository database .git/objects
error: go.mod: failed to insert into database
error: unable to index file 'go.mod'
fatal: updating files failed
```

<details>
<summary>.git/* files and folders permission</summary>

```console
$ ls -al .git/
total 68
drwxr-xr-x  8 gitpod gitpod 4096 Aug 26 02:25 .
drwxr-xr-x 10 gitpod gitpod 4096 Aug 26 02:25 ..
-rw-r--r--  1 root   root     41 Aug 26 02:25 AUTO_MERGE
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 branches
-rw-r--r--  1 gitpod gitpod  643 Aug 26 02:25 config
-rw-r--r--  1 gitpod gitpod   73 Aug 10 05:17 description
-rw-r--r--  1 gitpod gitpod  111 Aug 26 02:25 FETCH_HEAD
-rw-r--r--  1 root   root     39 Aug 26 02:25 HEAD
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 hooks
-rw-r--r--  1 root   root   4753 Aug 26 02:25 index
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 info
drwxr-xr-x  3 gitpod gitpod 4096 Aug 10 05:17 logs
drwxr-xr-x 80 gitpod gitpod 4096 Aug 26 02:25 objects
-rw-r--r--  1 gitpod gitpod   41 Aug 24 03:12 ORIG_HEAD
-rw-r--r--  1 gitpod gitpod  808 Aug 24 03:12 packed-refs
drwxr-xr-x  5 gitpod gitpod 4096 Aug 26 02:25 refs
```
</details>

<details>
<summary>.git/objects/ files and folders permission</summary>

```console
$ ls -al .git/objects/
total 320
drwxr-xr-x 80 gitpod gitpod 4096 Aug 26 02:25 .
drwxr-xr-x  8 gitpod gitpod 4096 Aug 26 02:25 ..
drwxr-xr-x  2 root   root   4096 Aug 26 02:25 08
drwxr-xr-x  2 gitpod gitpod 4096 Aug 26 02:25 09
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 0d
drwxr-xr-x  2 gitpod gitpod 4096 Aug 26 02:25 10
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 12
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 13
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 1a
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 1b
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 1c
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 1d
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 1e
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 1f
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 20
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 25
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 28
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 2a
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 2b
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 2e
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 33
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 34
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 35
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 3e
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 41
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 42
drwxr-xr-x  2 gitpod gitpod 4096 Aug 26 02:25 43
drwxr-xr-x  2 gitpod gitpod 4096 Aug 26 02:25 44
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 45
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 46
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 4d
drwxr-xr-x  2 root   root   4096 Aug 26 02:25 4f
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 56
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 5b
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 64
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 7b
drwxr-xr-x  2 root   root   4096 Aug 26 02:25 7d
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 82
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 83
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 87
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 88
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 89
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 8e
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 92
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 95
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 96
drwxr-xr-x  2 root   root   4096 Aug 26 02:25 9d
drwxr-xr-x  2 root   root   4096 Aug 26 02:25 9e
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 a1
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 a3
drwxr-xr-x  2 gitpod gitpod 4096 Aug 26 02:25 a6
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 a8
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 ae
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 b3
drwxr-xr-x  2 root   root   4096 Aug 26 02:25 b8
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 b9
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 bd
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 c8
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 ca
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 cb
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 cc
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 d0
drwxr-xr-x  2 gitpod gitpod 4096 Aug 26 02:25 d1
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 d2
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 d5
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 d6
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 d7
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 da
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 de
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 e2
drwxr-xr-x  2 root   root   4096 Aug 26 02:25 e4
drwxr-xr-x  2 root   root   4096 Aug 26 02:25 ea
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 ec
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 ef
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 f9
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 fb
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 fd
drwxr-xr-x  2 gitpod gitpod 4096 Aug 24 03:12 ff
drwxr-xr-x  2 gitpod gitpod 4096 Aug 10 05:17 info
drwxr-xr-x  2 gitpod gitpod 4096 Aug 26 02:25 pack
```
</details>

### Steps to reproduce

- Enable the PVC feature flag
- Open my project's [PR](https://github.com/jenting/kucero/pull/33) with Gitpod
- Check the `.git/objects` folders permission

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

#7901

### PR DESCRIPTION
**Pull request by jenting**
## Description

- Revert the https://github.com/gitpod-io/gitpod/pull/12238/commits/32a0f897780ac0e7f5dc5e9a5d90ae9e1a8c1d8f
- Fix the files _user:group_ is  `root:gitpod` after `git checkout` operation.

## Related Issue(s)

Fixes #12420

## How to test

- Open preview env and enable the PVC feature flag
- Launch a workspace by PR
- Check all the files and directories under `.git/` folder, the `user:group` is `gitpod:gitpod`

## Release Notes

```release-note
experimental: enable the feature flag PVC, the files/folders under .git/ folder user:group permission is incorrect
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@jenting: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jenting** [comment]
Some files user:group `root:gitpod` seems not correct.

```console
$ ls -al .git/
drwxr-sr-x  2 gitpod gitpod 4096 Aug 26 04:39 branches
-rw-r--r--  1 root   gitpod  367 Aug 26 04:39 config
-rw-r--r--  1 gitpod gitpod   73 Aug 26 04:39 description
-rw-r--r--  1 root   gitpod  105 Aug 26 04:39 FETCH_HEAD
-rw-r--r--  1 root   gitpod   21 Aug 26 04:39 HEAD
drwxr-sr-x  2 gitpod gitpod 4096 Aug 26 04:39 hooks
-rw-r--r--  1 root   gitpod 4773 Aug 26 04:39 index
drwxr-sr-x  2 gitpod gitpod 4096 Aug 26 04:39 info
drwxr-sr-x  3 gitpod gitpod 4096 Aug 26 04:39 logs
drwxr-sr-x 46 gitpod gitpod 4096 Aug 26 04:39 objects
-rw-r--r--  1 gitpod gitpod  972 Aug 26 04:39 packed-refs
drwxr-sr-x  5 gitpod gitpod 4096 Aug 26 04:39 refs
-rw-r--r--  1 gitpod gitpod  615 Aug 26 04:39 shallow
```

**Comment by jenting** [comment]
```console
$  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> make
> }
go mod tidy
go: downloading github.com/sirupsen/logrus v1.9.0
go: downloading k8s.io/apimachinery v0.25.0
go: downloading k8s.io/api v0.25.0
go: downloading k8s.io/client-go v0.25.0
go: downloading k8s.io/kubectl v0.25.0
go: downloading github.com/spf13/cobra v1.5.0
go: downloading github.com/weaveworks/kured v0.0.0-20220820091106-774dc69e3bda
go: downloading sigs.k8s.io/yaml v1.3.0
go: downloading k8s.io/apiserver v0.25.0
go: downloading sigs.k8s.io/controller-runtime v0.12.3
go: downloading github.com/vmware-tanzu/velero v1.9.1
go: downloading golang.org/x/sys v0.0.0-20220722155257-8c9f86f7a55f
go: downloading github.com/stretchr/testify v1.8.0
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/google/gofuzz v1.2.0
go: downloading k8s.io/klog/v2 v2.70.1
go: downloading sigs.k8s.io/structured-merge-diff/v4 v4.2.3
go: downloading k8s.io/cli-runtime v0.25.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/imdario/mergo v0.3.12
go: downloading golang.org/x/term v0.0.0-20210927222741-03fcf44c2211
go: downloading k8s.io/utils v0.0.0-20220728103510-ee6ede2d64ed
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading github.com/evanphx/json-patch v4.12.0+incompatible
go: downloading github.com/fsnotify/fsnotify v1.5.4
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/google/go-cmp v0.5.8
go: downloading sigs.k8s.io/json v0.0.0-20220713155537-f223a00ba0e2
go: downloading github.com/go-logr/logr v1.2.3
go: downloading k8s.io/kube-openapi v0.0.0-20220803162953-67bda5d908f1
go: downloading k8s.io/component-base v0.25.0
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/google/gnostic v0.5.7-v3refs
go: downloading google.golang.org/protobuf v1.28.1
go: downloading golang.org/x/net v0.0.0-20220722155237-a158d28d115b
go: downloading golang.org/x/time v0.0.0-20220210224613-90d013bbcef8
go: downloading gopkg.in/check.v1 v1.0.0-20201130134442-10cb98267c6c
go: downloading golang.org/x/text v0.3.7
go: downloading sigs.k8s.io/kustomize/api v0.12.1
go: downloading sigs.k8s.io/kustomize/kyaml v0.13.9
go: downloading k8s.io/apiextensions-apiserver v0.24.2
go: downloading github.com/prometheus/client_golang v1.13.0
go: downloading github.com/onsi/ginkgo v1.16.5
go: downloading github.com/onsi/gomega v1.19.0
go: downloading go.uber.org/goleak v1.1.12
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/go-logr/zapr v1.2.3
go: downloading go.uber.org/zap v1.19.1
go: downloading github.com/google/uuid v1.2.0
go: downloading github.com/chai2010/gettext-go v1.0.2
go: downloading github.com/onsi/ginkgo/v2 v2.1.4
go: downloading github.com/MakeNowJust/heredoc v1.0.0
go: downloading github.com/mitchellh/go-wordwrap v1.0.0
go: downloading github.com/russross/blackfriday v1.5.2
go: downloading github.com/exponent-io/jsonpath v0.0.0-20151013193312-d6023ce2651d
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading golang.org/x/oauth2 v0.0.0-20220411215720-9780585627b5
go: downloading github.com/kr/pretty v0.3.0
go: downloading gomodules.xyz/jsonpatch/v2 v2.2.0
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/common v0.37.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading github.com/prometheus/procfs v0.8.0
go: downloading go.uber.org/atomic v1.7.0
go: downloading go.uber.org/multierr v1.6.0
go: downloading github.com/liggitt/tabwriter v0.0.0-20181228230101-89fcab3d43de
go: downloading github.com/gregjones/httpcache v0.0.0-20180305231024-9cad4c3443a7
go: downloading github.com/peterbourgon/diskv v2.0.1+incompatible
go: downloading github.com/go-openapi/jsonreference v0.19.5
go: downloading github.com/go-openapi/swag v0.19.14
go: downloading github.com/moby/term v0.0.0-20210619224110-3f7ff695adc6
go: downloading github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822
go: downloading github.com/go-errors/errors v1.0.1
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/rogpeppe/go-internal v1.6.1
go: downloading github.com/spf13/afero v1.8.2
go: downloading github.com/nxadm/tail v1.4.8
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.2-0.20181231171920-c182affec369
go: downloading github.com/google/btree v1.0.1
go: downloading github.com/PuerkitoBio/purell v1.1.1
go: downloading github.com/go-openapi/jsonpointer v0.19.5
go: downloading github.com/emicklei/go-restful/v3 v3.8.0
go: downloading github.com/google/shlex v0.0.0-20191202100458-e7afc7fbc510
go: downloading github.com/monochromegane/go-gitignore v0.0.0-20200626010858-205db1a8cc00
go: downloading github.com/xlab/treeprint v1.1.0
go: downloading github.com/mailru/easyjson v0.7.6
go: downloading google.golang.org/appengine v1.6.7
go: downloading github.com/stretchr/objx v0.4.0
go: downloading github.com/creack/pty v1.1.11
go: downloading github.com/emicklei/go-restful v2.9.5+incompatible
go: downloading gotest.tools/v3 v3.3.0
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: downloading github.com/moby/spdystream v0.2.0
go: downloading github.com/armon/go-socks5 v0.0.0-20160902184237-e75332964ef5
go: downloading github.com/elazarl/goproxy v0.0.0-20180725130230-947c36da3153
go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: downloading github.com/Azure/go-autorest/autorest v0.11.27
go: downloading github.com/Azure/go-autorest/autorest/adal v0.9.20
go: downloading github.com/Azure/go-ansiterm v0.0.0-20210617225240-d185dfc1b5a1
go: downloading github.com/josharian/intern v1.0.0
go: downloading go.starlark.net v0.0.0-20201006213952-227f4aabceb5
go: downloading github.com/sergi/go-diff v1.1.0
go: downloading cloud.google.com/go/compute v1.6.1
go: downloading github.com/Azure/go-autorest v14.2.0+incompatible
go: downloading github.com/Azure/go-autorest/tracing v0.6.0
go: downloading github.com/golang-jwt/jwt/v4 v4.2.0
go: downloading golang.org/x/crypto v0.0.0-20220411220226-7b82a4e95df4
go: downloading github.com/Azure/go-autorest/logger v0.2.1
go: downloading github.com/Azure/go-autorest/autorest/date v0.3.0
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/cespare/xxhash v1.1.0
go: downloading cloud.google.com/go v0.100.2
go: downloading gotest.tools v2.2.0+incompatible
go: updating go.sum: open /workspace/kucero/go.sum: permission denied
make: *** [Makefile:29: verify] Error 1
```

**Comment by andreafalzetti** [comment]
@jenting how can I enable the PVC feature flag?

**Comment by jenting** [comment]
> @jenting how can I enable the PVC feature flag?

I enable your account PVC feature flag and set you as an admin https://revert-12242a69fdec6.preview.gitpod-dev.com/

**Comment by mustard-mh** [comment]
I'm going to test it in prev env

**Comment by jenting** [comment]
> I'm going to test it in prev env

I enable your account PVC feature flag and set you as an admin https://revert-12242a69fdec6.preview.gitpod-dev.com/

**Review by andreafalzetti — APPROVED** [review]
works as advertised in prev env

```
drwxr-sr-x  8 gitpod gitpod 4096 Aug 26 10:19 ./
drwxr-sr-x  3 gitpod gitpod 4096 Aug 26 10:19 ../
drwxr-sr-x  2 gitpod gitpod 4096 Aug 26 10:19 branches/
-rw-r--r--  1 gitpod gitpod  279 Aug 26 10:19 config
-rw-r--r--  1 gitpod gitpod   73 Aug 26 10:19 description
-rw-r--r--  1 gitpod gitpod  114 Aug 26 10:19 FETCH_HEAD
-rw-r--r--  1 gitpod gitpod   21 Aug 26 10:19 HEAD
drwxr-sr-x  2 gitpod gitpod 4096 Aug 26 10:19 hooks/
-rw-r--r--  1 gitpod gitpod  225 Aug 26 10:19 index
drwxr-sr-x  2 gitpod gitpod 4096 Aug 26 10:19 info/
drwxr-sr-x  3 gitpod gitpod 4096 Aug 26 10:19 logs/
drwxr-sr-x 23 gitpod gitpod 4096 Aug 26 10:19 objects/
-rw-r--r--  1 gitpod gitpod  112 Aug 26 10:19 packed-refs
drwxr-sr-x  5 gitpod gitpod 4096 Aug 26 10:19 refs/
```

/hold 

waiting for @mustard-mh to finish her review

**Review by mustard-mh — APPROVED** [review]
Tested and code LGTM

/unhold

image

**Review by aledbf — APPROVED** [review]

**Comment by sagor999** [comment]
Nice!!! :heart:

**Pull request merged**
