### PR TITLE
clean up ide config map in helm

### LINKED ISSUE #7201: [server] clean up ide config map and installer
Some properties are not used anymore, see: https://github.com/gitpod-io/gitpod/blob/ced67ae93fc443ed60727dbe0cb9eca7a268b199/chart/templates/server-ide-configmap.yaml#L127

They should be removed from configmap and installer config.

@iQQBot feel free to grab

### PR DESCRIPTION
**Pull request by iQQBot**
## Description

clean up ide config map in helm

## Related Issue(s)

Fixes #7201 

## Release Notes

```release-note
NONE
```

## Documentation

/werft no-preview

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **loujaybee** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @loujaybee` in a comment when ready.

Associated issue: *#7201*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by akosyakov** [comment]
It is already removed in server?

**Comment by akosyakov** [comment]
we should remove from installer as well: https://github.com/gitpod-io/gitpod/blob/c27d245dfc4f83dc1b206c25a556cea1142f6245/installer/pkg/components/server/types.go#L14-L20 ?

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 9d4f79705ce33432d47837c2c88b9e9ddba7e22f</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7211#issuecomment-992693729" title="Approved">akosyakov</a>*

Associated issue: *#7201*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [akosyakov]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
