### PR TITLE
Update k8s dependencies to v0.24.3

### PR DESCRIPTION
**Pull request by aledbf**
## Description

- Update k8s dependencies to v0.24.3
- Remove empty `status` and `resource` definitions from manifests

## Related Issue(s)

fixes https://github.com/gitpod-io/gitpod/issues/8529
fixes https://github.com/gitpod-io/gitpod/issues/11136

## How to test
- Check workspaces work as usual
- Check the generated manifests do not contain empty `status` or `resource` definitions

```
docker run --entrypoint sh --rm \
  eu.gcr.io/gitpod-core-dev/build/installer:aledbf-k8s24.11 -c "cat /app/installer" >gitpod-installer

chmod +x gitpod-installer

cat <<EOF >values.yaml
apiVersion: v1
domain: fake.gitpod.io
EOF

./gitpod-installer render --use-experimental-config --config values.yaml > manifests.yaml
```

## Release Notes
```release-note
NONE
```

## Werft options:
- [X] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@aledbf: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by corneliusludmann** [comment]
It seems like this pull request implements item (3) as described in #11136, right?

I actually miss the discussion on this issue why we have decided to implement _that_ solution and not one of the other proposed ones? :thinking:

**Comment by corneliusludmann** [comment]
Would you mind also removing this:

https://github.com/gitpod-io/gitpod/blob/1b1248d2abed582f8bb5dd3d441e196ba121fd62/install/kots/manifests/gitpod-installer-job.yaml#L314-L318

**Comment by aledbf** [comment]
> It seems like this pull request implements item (3) as described in #11136, right?

Yes.

> I actually miss the discussion on this issue why we have decided to implement _that_ solution and not one of the other proposed ones? thinking

Sorry, I assumed the only "real" option is 3.

> 1. Post-process with yq

Too complex to maintain

> 2. Lock the versions to the Kubernetes versions we support

We already do that (to some extent), pinning the versions with leeway.

**Comment by aledbf** [comment]
> Would you mind also removing this:
> 
> https://github.com/gitpod-io/gitpod/blob/1b1248d2abed582f8bb5dd3d441e196ba121fd62/install/kots/manifests/gitpod-installer-job.yaml#L314-L318

done

**Comment by corneliusludmann** [comment]
> > 3\. Lock the versions to the Kubernetes versions we support
> 
> We already do that (to some extent), pinning the versions with leeway.

My hypothesis in [my comment](https://github.com/gitpod-io/gitpod/issues/11136#issuecomment-1174877593) was that we need to stick with version v0.22.x as long as we need to support Kubernetes 1.22 to avoid incompatibilities. And I raised the question of whether there is a reason that we need to update to v0.24.x. (In this case, your solution seems inevitable.)

Would you mind adding your thoughts in #11136 to have the discussion in a single place?

**Review by easyCZ — APPROVED** [review]

**Review by meysholdt — APPROVED** [review]

**Review by corneliusludmann — APPROVED** [review]

**Comment by aledbf** [comment]
@csweichel @Furisto @akosyakov @geropl friendly ping :)

**Review by Furisto — APPROVED** [review]

**Review by geropl — APPROVED** [review]

**Comment by AlexTugarev** [comment]
@aledbf, it seems this PR breaks the installer's render test. I see changes to the golden files of the installer tests, and I'm missing test run in the most recent build job of this PR.

Which version of the test data is correct?

**Comment by AlexTugarev** [comment]
> 📦  cached  install/installer:raw-app 

The tests were definitely not executed. Seems like cache control (invalidation) is broken in this area.

**Comment by aledbf** [comment]
@AlexTugarev https://github.com/gitpod-io/gitpod/pull/12299

**Pull request merged**
