### PR TITLE
Shift Org Selector to the right of main menu

### LINKED ISSUE #16046: [dashboard] Relayout navigation in dashboard
To simplify the UX and clarify what team context I'm acting as a user, we decided to move the org selector left and go back to a workspaces list per organization.

The current state of the design:

image

> This change also requires moving from a global workspaces list to one per team. It would be confusing to do that change separately.

### PR DESCRIPTION
**Pull request by selfcontained**
## Description

As part of the org nav design updates, this shifts the Organization Selector to the right. It also moves the `Admin` and `Feedback` links into the User menu.

image

image

Motivations for moving it are:
* Avoids having an org icon (and eventually logo) sit so close in proximity to the gitpod logo
* Allows the main nav links (Workspaces | Projects) to not shift as you change orgs (since org names vary in width)

## Related Issue(s)

Fixes #16046

## Release Notes

```release-note
The organization selector is now located in the top right of the header. Feedback can be accessed from the User menu, also in the top right of the header.
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-slow-database
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by gtsiolis** [comment]
Looking at this now! 👀

**Comment by svenefftinge** [comment]
Are we sure this is better? A reason we moved it left was that that is where our eyes go first thing.

**Comment by selfcontained** [comment]
Couple things that feel like an improvement with it on the left:

* Avoids having an org icon (and eventually logo) sit so close in proximity to the gitpod logo
* Allows the main nav links (Workspaces | Projects) to not shift as you change orgs (since org names vary in width)
* Moving the Admin | Feedback links into the User menu seems like an improvement regardless of the org menu moving.

**Comment by geropl** [comment]
I'm a bit out of touch with this change and it's motivation, thus have problems reviewing it. Let me start with dropping my thoughts here:

- Having both drop-downs on the right is very confusing. Also, I think that "Feedback" is way to hidden (Admin is not important as it's internal only anyway).
- I feel the biggest clash comes from the icons (Gtipod and org icon). Maybe we can improve that by switching to a color palette that does not include the "Gitpod kumquat orange/yellow!"? :shrug: 
- The varying name length is a problem atm. But maybe reserving some static placeholder length is enough? 
- I really like the org selector being close to "Workspaces" and "Projects" this demonstrates the strong connection I feel

**Comment by selfcontained** [comment]
Closing this based on some feedback and other options we'd like to try instead.

**Pull request closed without merging**
