### PR TITLE
[server] Bump gitpod-yml-inferrer

### PR DESCRIPTION
**Pull request by jankeromnes**
Diff: https://github.com/gitpod-io/gitpod-yml-inferrer/compare/b442c1c78af5e0279ee4228f5ef93753b24031a6...5df8b1a604da97f8e4b178dff10d4ea430771f06

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jankeromnes** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jankeromnes** [comment]
## Tests

### NextJS

**Repo**: https://github.com/gitpod-io/template-nextjs

**Guessed**:

```yml
tasks:
  - init: npm install && npm run build
    command: npm run start
```

**Actual**:

```yml
tasks:
  - name: Start development environment
    init: npm install
    command: npm run dev
```

### Java

**Repo**: https://github.com/gitpod-io/spring-petclinic

**Guessed**:

```yml
tasks:
  - init: ./mvnw install -DskipTests=false
```

**Actual**:

```yml
tasks:
- init: ./mvnw package -DskipTests
  command: java -jar target/*.jar
```

### Go

**Repo**: https://github.com/gitpod-io/template-golang-cli

**Guessed**:

```yml
tasks:
  - init: go get && go build ./... && go test ./...
    command: go run
```

**Actual**:

```yml
tasks:
  - init: |
      go get github.com/spf13/cobra/cobra
      go build
    command: |
      ./mycli --help
```


### C

**Repo**: https://github.com/gitpod-io/template-c

**Guessed**:

```yml
tasks:
  - init: make
```

**Actual**:

```yml
tasks:
  - init: |
      make
    command: |
      make help
```

### C++

**Repo**: https://github.com/gitpod-io/template-cpp

**Guessed**:

```yml
tasks:
  - init: cmake .
```

**Actual**:

```yml
tasks:
  - init: |
      cd build && make
    command: |
      cd build; conan info .
```

**Comment by csweichel** [comment]
@svenefftinge does it still make sense that this is a separate repository? If not, could we fold it in to gitpod-io?

**Comment by csweichel** [comment]
@jankeromnes are those tests automated?

**Comment by svenefftinge** [comment]
> @svenefftinge does it still make sense that this is a separate repository? If not, could we fold it in to gitpod-io?

No. We moved that out before we completely went open-source.

**Comment by jankeromnes** [comment]
Happy to inline the inferrer if you'd prefer that. 👍

> @jankeromnes are those tests automated?

No, they're very manual (fork the templates, delete `.gitpod.yml`, add as Projects in my PR deployment, see what the Configurator UI gives).

**Comment by svenefftinge** [comment]
Currently, the inferrer seems to create broken configuration.

Screenshot 2021-08-31 at 14 35 46

Is this solve din this PR?

**Comment by jankeromnes** [comment]
> Currently, the inferrer seems to create broken configuration.

Yes, this was on purpose. Ideally, the `# TODO` part should be underlined in red.

The goal was to nudge users into editing the `.gitpod.yml`, instead of "blindly" clicking `Next` `Next` `Next` (and ending up with another hundred setups that just say `echo "init"` forever 🙄).

Please let me know if you'd like this to be different.

**Comment by svenefftinge** [comment]
Ah ok, let's not put in such a stopper for users. 
Running into such an error without doing anything would be a frustrating experience.

**Review by svenefftinge — APPROVED** [review]
lgtm

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: eae05dbc5af5ec2bff6b512aa4614b0a1a163fb6</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5438#pullrequestreview-742904784" title="Approved">svenefftinge</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [svenefftinge]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [svenefftinge]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5438#pullrequestreview-742904784" title="Approved">svenefftinge</a>*

*No associated issue*. Requirement bypassed by manually added approval.

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [svenefftinge]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [svenefftinge]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
