### PR TITLE
[revamp] : feedback widget UX

### LINKED ISSUE #15760: Improve feedback widget UX
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/issues/10307, which contains a list of minor improvements for the feedback widget, there's also some text overlapping happening when a user is submitting feedback with long text where the feedback emojis are hiding parts of the text.

See also relevant discussions[[1](https://gitpod.slack.com/archives/C01KPEPQYE6/p1673735310904849)][[2](https://gitpod.slack.com/archives/C01KPEPNBD0/p1673877377941769)][[3](https://gitpod.slack.com/archives/C0420AN379Q/p1673725464390859)] (internal) Cc @loujaybee @mbrevoort 

Cc @jldec as we've briefly discussed this in a past sync.

| Feedback widget with long text |
|-|
| Screenshot 2023-01-16 at 4 30 28 PM (2) |

### Proposal

:a: A boring (simple) solution could be to limit the scrolling area above the feedback emojis.

:b: Alternatively, moving the feedback emojis in the bottom left corner inside the modal could also work.

Long term, we could probably spent some more time exploring a different design for the feedback widget.

| :a: | :b: |
|-|-|
| Screenshot 2023-01-16 at 4 40 39 PM (2) | Screenshot 2023-01-16 at 4 40 31 PM (2) |

### PR DESCRIPTION
**Pull request by vedant-jain03**
## Description
- Shift the position of `emojiGroup`.

## Related Issue(s)

Fixes #15760 

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by vedant-jain03** [comment]
cc @gtsiolis

**Comment by vedant-jain03** [comment]
> /werft run
> 
> +1 started the job as [gitpod-build-issue-15760-fork.0](https://werft.gitpod-dev.com/job/gitpod-build-issue-15760-fork.0) (with `.werft/` from `main`)

The checks for the job you mentioned are running fine but not for [gitpod-build-issue-15760.0](https://werft.gitpod-dev.com/job/gitpod-build-issue-15760.0)

**Review by andrew-farries — APPROVED** [review]
For reference, with these changes the modal now looks like this:

image

Code changes LGTM.

**Comment by andrew-farries** [comment]
It looks like you already signed the CLA (as part of [this PR](https://github.com/gitpod-io/gitpod/pull/15741#issuecomment-1387346873)), so I will remove the `cla-pending` label.

**Pull request merged**
