### PR TITLE
Use `dependency_update` again

### PR DESCRIPTION
**Pull request by JesterOrNot**
Use `dependency_update` as https://github.com/hashicorp/terraform-provider-helm/issues/459 has been fixed

### CODE REVIEW

**Review by geropl — CHANGES_REQUESTED** [review]
Thanks for keeping track, works!

Would be nice to have the version constraint in `versions.tf`:
```

    helm = {
        source = "hashicorp/helm"
        version = ">= 1.3.0"
    }
```

**Comment by JesterOrNot** [comment]
Done!

**Review by geropl — APPROVED** [review]
Looks good, tested and works: :heavy_check_mark:

**Comment by JesterOrNot** [comment]
hmm..TLS handshake timeout on werft

/werft run

**Comment by JesterOrNot** [comment]
Thanks, Merging! :rocket:

**Pull request merged**
