### PR TITLE
[ws-daemon] Re-establish IWS on restart

### LINKED ISSUE #5079: Suspicion: broken IWS after ws-daemon restart
### Bug description

It seems that when ws-daemon restarts it either doesn't serve IWS of existing workspaces, or workspacekit does not reconnect to the new IWS.

This results in non-functional Docker daemon and failing workspace teardown. Probably the cause of #4955 

### Steps to reproduce

1. Start a workspace
2. Restart ws-daemon
3. Try `docker run ...`

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by csweichel**
fixes #5079 

ws-daemon provides an in-workspace service (IWS) to workspacekit. We use this IWS to establish the UID/GID mapping, mount proc and sysfs, prepare the rootfs and unmount it all on shutdown. If the IWS is not available, the workspace does not function well. Prior to this change, ws-daemon would not re-establish the IWS for already running workspaces due to a missing call in the lifecycle hooks.

### How to test
1. Start a workspace
2. Restart the ws-daemon on the node where the workspace is running
3. Run `docker run --rm -it alpine:latest` in the workspace. The container should just run and not complain about procfs.

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **csweichel** after the PR has been reviewed.

Associated issue: *#5079*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by aledbf** [comment]
Works as described. The reconnection takes a bit more than 20 seconds.

/lgtm

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 88f8842ea55dcbdda6def4a3b945cc3cf01d35a8</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5130#issuecomment-895903696" title="LGTM">aledbf</a>*

Associated issue: *#5079*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [aledbf]
- ~~[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)~~ [aledbf]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
