### PR TITLE
[analytics] Add Track Event for user deletion in ee

### PR DESCRIPTION
**Pull request by jakobhero**
Make call to IAnalyticsWriter so that the deletion of the user account is tracked.

/werft analytics=segment|TEZnsG4QbLSxLfHfNieLYGF4cDwyFWoe

### CODE REVIEW

**Review by JanKoehnlein — APPROVED** [review]
LGTM

**Comment by AlexTugarev** [comment]
@jakobhero just a question, but why is this traced in `UserDeletionServiceEE` and not in `UserDeletionService`?

**Comment by jakobhero** [comment]
No particular reason, would you prefer it if I moved it there @AlexTugarev ?

**Comment by AlexTugarev** [comment]
@jakobhero, it appears to be random to put the event for account creation into the non-EE folder, while the account deletion event is in EE folder. yes, for the sake of consistency, it would be great to align if there is no good reason (e.g. dependency) to separate.

**Comment by jakobhero** [comment]
Thanks for the Insights @AlexTugarev, this makes sense to me. I'm closing this in favor of #4647.

**Pull request closed without merging**
