### PR TITLE
feat: add wrapping for contextUrl

### LINKED ISSUE #4556: [dashboard] text wrapping on "workspace is already running" dialog
### Steps to reproduce

1. Start workspace via https://gitpod.io/#EXAMPLE_DIR=typescript%2Fgraphql/https://github.com/ghuntley/prisma-examples/tree/gh/gitpodify
2. Start another workspace via https://gitpod.io/#EXAMPLE_DIR=typescript%2Fgraphql/https://github.com/ghuntley/prisma-examples/tree/gh/gitpodify

### Expected behavior

Design implementation accommodates long URLs

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #4556 

- added `truncate` className
- added `title` attribute

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankoehnlein** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankoehnlein` in a comment when ready.

Associated issue: *#4556*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by Cahllagerfeld** [comment]
Unfortunately I wasn't able to test it locally.
I didnt manage to get the dashbaord running locally/ in gitpod due to an error regarding wss :(

**Comment by gtsiolis** [comment]
Hey @Cahllagerfeld! Thanks for contributing! 🧡 

Changes look good so far. ✔️ 

I've triggered the preview environment in https://github.com/gitpod-io/gitpod/pull/5248#issuecomment-900881007, should be up and running in a few minutes. 👀

**Comment by Cahllagerfeld** [comment]
Thats awesome! :D

**Review by gtsiolis — APPROVED** [review]
UX looks good! 🌟 

@jankeromnes could you take a look when you are free and merge this?

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 4955d35bffde5d4d4076d7d0c8cd18c71bf39114</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5248#pullrequestreview-732558065" title="Approved">gtsiolis</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankoehnlein** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankoehnlein` in a comment when ready.

Associated issue: *#4556*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jankeromnes** [comment]
Many thanks for this contribution @Cahllagerfeld! 🎉

This is already reviewed and approved, so I'm just "rubberstamping" 😁 🚀 

/approve

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5248#pullrequestreview-732558065" title="Approved">gtsiolis</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/5248#issuecomment-900929393" title="Approved">jankeromnes</a>*

Associated issue: *#4556*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
