### PR TITLE
Add deprecation note to `github` node in .gitpod.yml – EXP-682

### PR DESCRIPTION
**Pull request by AlexTugarev**
## Description

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖 Generated by Copilot at b6d8eda</samp>

Deprecated some unused or redundant properties of the `github` field in the Gitpod schema file, to streamline the prebuild settings and UX.

</details>

## Related Issue(s)

Fixes EXP-682

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - at-depreca21c83f1c9b</li>
	<li><b>🔗 URL</b> - <a href="https://at-depreca21c83f1c9b.preview.gitpod-dev.com/workspaces" target="_blank">at-depreca21c83f1c9b.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - at-deprecate-github-in-config-gha.17568</li>
	<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-at-depreca21c83f1c9b%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws-manager-mk2%22%0A;duration=P1D?project=gitpod-core-dev" target="_blank">GCP Logs Explorer</a></li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Review by geropl — APPROVED** [review]
LGTM :broom: :heavy_check_mark:

**Comment by loujaybee** [comment]
👋 Hey Alex—do we want to [merge the documentation changes](https://github.com/gitpod-io/website/pull/3988) first before we merge this PR? Users might have questions and I'd want to avoid any confusion. What are your thoughts?

**Comment by AlexTugarev** [comment]
@loujaybee, I'm happy to sync the two updates, abolutely!

**Pull request merged**
