### PR TITLE
[supervisor] Fix IDE shutdown

### LINKED ISSUE #6530: supervisor segfaults (staging)
https://console.cloud.google.com/errors/CJjW3sXO0uz1SQ?time=P7D&project=gitpod-staging

### PR DESCRIPTION
**Pull request by corneliusludmann**
## Description
Fixes shutting down the IDE process in supervisor.

/werft with-clean-slate-deployment

## Related Issue(s)

Fixes #6530

## How to test
Stop a workspace and make sure that the segfauls error mentioned in the issue does not occur.

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **corneliusludmann** after the PR has been reviewed.

Associated issue: *#6530*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by akosyakov** [comment]
@corneliusludmann Unfortunately I cannot get prev envs for it. Code wise looks good though, would be nice to give a try at least once.

**Comment by corneliusludmann** [comment]
> @corneliusludmann Unfortunately I cannot get prev envs for it. Code wise looks good though, would be nice to give a try at least once.

I wonder what the motivation was to retrigger the werft build instead of just using the existing installation? Anyway, I restarted the werft job again and now it's green.

**Comment by corneliusludmann** [comment]
/hold

let us merge #6483 first and rebase this PR afterwards to prevent merge conflicts

**Comment by akosyakov** [comment]
> I wonder what the motivation was to retrigger the werft build instead of just using the existing installation? Anyway, I restarted the werft job again and now it's green.

There was not a link to preview for me. Sorry 😬

**Comment by corneliusludmann** [comment]
/unhold

It's done. It's rebased and the build went through.

**Comment by akosyakov** [comment]
@corneliusludmann 

> Stop a workspace and make sure that the segfauls error mentioned in the issue does not occur.

this seem to work, but for VS Code I also test what happens in IDE process gets OOM killed and it does not work with IntelliJ:
- if i kill launcher.sh workspace crashes
- if i kill startup.sh which is unlikely then it tries to start forever more and more instances and they crash immediately

Should it be addressed separately? Asking because it is related to the same code. please unhold if so

/lgtm
/hold

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: eb219c111a7a78baea3b5d3d82842de9c4b035f1</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6538#issuecomment-959503542" title="LGTM">akosyakov</a>*

Associated issue: *#6530*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [akosyakov]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by corneliusludmann** [comment]
> Should it be addressed separately?

Thanks for the hint! :+1:  I've created a separate issue for that.

/unhold

**Pull request merged**
