### PR TITLE
[supervisor] Remove trackEvent api method

### PR DESCRIPTION
**Pull request by jeanp413**
## Description

Remove `trackEvent` api method and add caching to `GetOwnerID`

## How to test

1. Open workspace check it starts sucessfully
2. Check `supervisor_readiness` event gets send

## Release Notes

```release-note
NONE
```

/werft with-preview
/werft analytics=segment

### CODE REVIEW

**Comment by jeanp413** [comment]
image

**Comment by andreafalzetti** [comment]
Code LGTM! I just want to try in prev env but getting this weird issue about pulling any image.

I will try to recreate the prev env..

Screenshot 2023-01-17 at 21 16 13

**Review by andreafalzetti — APPROVED** [review]
The changes look good, I wasn't able to test in prev env and see events in Segments but I can see that you've already tested so feel free to unhold, or I can try again testing once prev env is back up.

**Comment by andreafalzetti** [comment]
Screenshot 2023-01-17 at 22 02 31

🚀

**Pull request merged**
