### PR TITLE
Created a global prettier file to remove inconsistent linting configurations.

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
## Description
I have created a global .prettierrc.js file for Typescript and Js Files in order to remove inconsistent linting configurations which spanned across files.

### CODE REVIEW

**Comment by roboquat** [comment]
@Harry-Hopkinson: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by Harry-Hopkinson** [comment]
I have ran
```
prettier --config ./.prettierrc.js --write "./**/*.ts"
prettier --config ./.prettierrc.js --write "./**/*.tsx"
prettier --config ./.prettierrc.js --write "./**/*.js"
```

**Comment by mustard-mh** [comment]
Thanks! I want this linting too! 😄 https://github.com/gitpod-io/gitpod/pull/7653#issuecomment-1017589882

I think you can create a PR with `.prettierrc.js` file added only, then let members run re-format command
Too many files to review now

**Comment by Harry-Hopkinson** [comment]
@mustard-mh I will do just that.

**Comment by Harry-Hopkinson** [comment]
Continued #8607

**Pull request closed without merging**
