### PR TITLE
[ws-daemon] Enable workspace IP forwarding

### PR DESCRIPTION
**Pull request by csweichel**
to make the new nftables setup work

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by aledbf — APPROVED** [review]

**Review by utam0k — APPROVED** [review]

**Comment by kylos101** [comment]
@corneliusludmann @MrSimonEmms @Pothulapati @nandajavarma  you'll want to make sure that if you cut a version of the installer in the near future, that it includes the changes in this PR. Without which, it's possible that a customer may be unable to start workspaces due to the supervisor readiness check failing.

Assuming you'll be going from main, you should be okay, unless of course you're cherry picking hot fixes. In which case, consider these. :smile:

**Comment by MrSimonEmms** [comment]
@kylos101 does this need to be in before the [2022.04.0 release](https://github.com/gitpod-io/gitpod/milestone/22)

**Comment by kylos101** [comment]
> @kylos101 does this need to be in before the [2022.04.0 release](https://github.com/gitpod-io/gitpod/milestone/22)

We found this issue today in main, but, I'm not sure what the April release is based off of, and whether it includes [these PRs](https://github.com/gitpod-io/gitpod/pull/9270#issuecomment-1097315529).

I tried to find a branch that is related to the milestone, but did not have success. :cry: Can you share a link?

**Comment by MrSimonEmms** [comment]
The April release (like all releases) will be a release candidate taken from the head of `main`, tested and then released

**Pull request merged**
