### PR TITLE
[dashboard] Fix page titles

### PR DESCRIPTION
**Pull request by jankeromnes**
Fixes https://github.com/gitpod-io/gitpod/issues/3653

Note: This PR simply sets `document.title` in relevant places (as opposed to using something like React Helmet).

### How to test

- Open every dashboard page & verify the page title is correct

### CODE REVIEW

**Comment by AlexTugarev** [comment]
Let's use `—` instead of `-`. This would not just be good typography, but also aligned with Code:

Screen Shot 2021-05-27 at 07 45 14

**Comment by jankeromnes** [comment]
> Let's use `—` instead of `-`.

I love this suggestion, many thanks!

> This would not just be good typography, but also aligned with Code:

Actually I notice that Code uses an Em Dash (`—`) surrounded by spaces. My understanding is that you should choose between:
- Using an En Dash (`–`) surrounded by spaces (e.g. `Dashboard – Gitpod`)
- Usinig an Em Dash (`—`) without any spaces around it (e.g. `Dashboard—Gitpod`)

Which one do you prefer?

**Comment by AlexTugarev** [comment]
> EDIT: Went with an En Dash (–) surrounded by spaces for now.

On green field that would be my favorite. Given that we are aligning with VS Code, I'd actually vote for consistency over accuracy here.  🤷🏻‍♂️

**Comment by jankeromnes** [comment]
Ok, agreed then. Go consistency! 🙌

**Comment by AlexTugarev** [comment]
Seeing this while context parsing is in progress:

Screen Shot 2021-05-27 at 11 20 22

**Review by AlexTugarev — APPROVED** [review]
Looks much better now! ❤️ 

not sure how this fits into the picture: https://github.com/gitpod-io/gitpod/pull/4313#issuecomment-849480131

**Review by gtsiolis — APPROVED** [review]
Feels good to see this issue getting resolved! Thanks @jankeromnes @AlexTugarev! 🏀 

FWIW, I used to go for `mdash` for such cases but any dash should suffice! Also, noticed many have switched to a plain dash in titles recently. See also [relevant reference](https://www.grammarly.com/blog/dash/).

**Comment by jankeromnes** [comment]
Many thanks for the cool reviews! 🙏

> Seeing this while context parsing is in progress:

I believe this is supervisor setting the page title to the "description" of the workspace, before the IDE changes page titles again:

https://github.com/gitpod-io/gitpod/blob/d2ece4948d19ac71732bf81ab40dc58eb79b829d/components/supervisor/frontend/src/index.ts#L36

If we want to change this, I'd be very happy to do that in a follow-up. 😁

**Pull request merged**
