### PR TITLE
[server] Disable tracing errors

### PR DESCRIPTION
**Pull request by geropl**
## Description
 - server: don't use FOLLOWS_FROM references
 - replace references by manually enriching spans for websocket notifications
 - set `JAEGER_DISABLED` when tracing is not configured explicitly to avoid noisy error messages (for SH case, for example)

## Related Issue(s)

Fixes #

## How to test
 - as `with-observability` is [not working atm](https://github.com/gitpod-io/gitpod/issues/8194):
   - `kubectl logs server-79dfdf9bbd-f6fmn server -f`
   - start a workspace
   - note that the `server` logs do not contain any tracing-related errors/warnings

## Release Notes

```release-note
[tracing] avoid noisy error messages
```

## Documentation

- [ ] /werft with-observability=true
- [ ] /werft with-helm=true
- [x] /werft with-clean-slate-deployment

### CODE REVIEW

**Comment by geropl** [comment]
/werft run

with observability

**Comment by geropl** [comment]
/werft run

:crossed_fingers:

**Comment by geropl** [comment]
`with-observability` does not work at the moment, so we test the tracing changes in `server` by starting a workspace, which shows there are no errors (without checking the actual structure in honeycomb).

**Review by jankeromnes — APPROVED** [review]
Thanks for this Pull Request!

Already approved by Simon, thus simply skimmed briefly and rubber-stamping on behalf of Team WebApp. 🚀

**Pull request merged**
