### PR TITLE
Support specifying workspace class in gitpod.yml

### PR DESCRIPTION
**Pull request by Furisto**
## Description
Add support for specifying the workspace class in gitpod.yaml

```
workspaceRequirements:
  class: g1-standard
```

```
workspaceRequirements:
  class: 
    - g1-standard
    - g2-foo-bar
```

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/issues/10963

## How to test
1. Prebuild class is taken from gitpod.yml (single workspace class specified)
   - Trigger a prebuild with https://fo-class-repo-config.preview.gitpod-dev.com/#prebuild/https://github.com/Furisto/gitpod-repro/tree/single-workspace-class
   - Check running prebuilds. Prebuild should run with 'small' workspace class
2. Prebuild class is taken from gitpod.yml (multiple workspace classes specified)
   - Trigger a prebuild with https://fo-class-repo-config.preview.gitpod-dev.com/#prebuild/https://github.com/Furisto/gitpod-repro/tree/multi-workspace-class-array
   - Check running prebuilds. Prebuild should run with the first available workspace class (`small`)
3. Default class is used for Prebuild if gitpod.yml does not specify a class
   - Trigger a prebuild of a random repository in the preview environment. Prebuild should run with `default` workspace class

-> **Delete all prebuilds in the database to ensure that the prebuild class is not used for regular workspaces**
1. Regular workspace class is taken from gitpod.yml (single workspace class specified)
    - Open https://github.com/Furisto/gitpod-repro/tree/single-workspace-class. 
    - Workspace should run with s`mall `workspace class
2. Regular workspace class is taken from gitpod.yml (multiple workspace classes specified)
    -  Open https://github.com/Furisto/gitpod-repro/tree/single-workspace-class. 
    - Workspace should run with first available workspace class (`small`)

## Release Notes

```release-note
The workspace class for a workspace can now be specified in gitpod.yml
```

## Documentation
Does this PR require updates to the documentation at www.gitpod.io/docs?
Yes: https://github.com/gitpod-io/website/issues/2973

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@Furisto: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by svenefftinge** [comment]
I really think referencing workspace class names here is not the right approach. We should instead state what requirements in terms of resources are needed and then match it against the available classes.

**Comment by atduarte** [comment]
@svenefftinge thanks for your feedback. Let me share a bit more on why I think setting the workspace class right now makes sense:
1. both options are not mutually exclusive. The `.gitpod.yml` can allow to define the workspace classes explicitly or (later) set minimum resource requirements as you described. 
2. we need a quick win, because the current prebuild workspace class selection is terrible. Currently, prebuild workspace class is picked based on the user preference of whoever triggers it. This is the main motivation to push this change through asap

Re "I doubt they will be stable": I'm pretty sure of that, but that doesn't need to be a problem if when deprecating a workspace class we specify what new workspace class should be used instead. 

I also doubt that we are aware of all the resource dimensions we will have, particularly on customers' installations.  E.g. different CPU frequencies and performance, type of GPU, disk IOPS, network bandwidth, "security level", network proxy and access, ... So having the option to define explicitly the workspace class sounds reasonable and beneficial.

> A setting for picking a certain workspace class would make more sense in the project configuration

Mixing project configurations and .gitpod.yml sounds like a very bad idea to me. 😬  I understand the benefit of being able to change what shows in the UI/dropdown, and assume that's the reason for your preference (?) but I don't believe the interface should be the deciding factor on whether something is at the repository (file) or the project (UI) level.

**Comment by easyCZ** [comment]
FWIW, I'm also not convinced this is the right approach. I'm not sure what the alternative is, but I can at least outline how I think we should think about workspace class selection.

A customer is starting a workspace, they should be able to express preferences, and requirements of what they need in a Workspace.
This can take the form of 
```
preferences:
  cpu:
    min: 4 vCPU
  memory:
    min: 6 GBi
  architecture:
    - ...
  
  classChoiceStrategy:
    - cheapest
 
requirements:
  os:
    - linux
  gpu: true
```

Given such a request, apply constraint satisfaction to arrive at a set of possible workspace classes. These classes must strictly match `requirements`, and they should (if possible) satisfy preferences.
Given the set of eligible classes, we choose based on the strategy specified - cheapest, most powerful, whatever...

What this does is it flips the product space to the customers needs, rather than forcing them to know (and keep up-to-date) on the possible workspace classes, and whether they work for them.

Yes, it's not easy, or necessarily possible, to do this right now. But with this as a north-star, we probably wouldn't choose to put class preferences on the gitpod yaml.

**Comment by easyCZ** [comment]
Moving to draft due to ongoing discussion in https://gitpod.slack.com/archives/C02F19UUW6S/p1667389673842289. Feel free to move back to in-review if this should be actioned.

**Comment by svenefftinge** [comment]
As discussed I'm taking this over and move the implementation to be a project setting.

**Comment by kylos101** [comment]
Closing in favor of https://github.com/gitpod-io/gitpod/pull/14535

**Pull request closed without merging**
