### PR TITLE
Release 2022.01

### LINKED ISSUE #7658: Create 2022.01 release
## Summary

In order to improve the acceptance of Gitpod self-hosted by the community and enterprise users, a formalised and regular release cycle of the Gitpod Installer is critical. This will be the first release of the Installer binaries and will be the template for how the process will run in future.

## Context

Currently, the process is to instruct the community to find a specific (and arbitrary) build in Werft and use the build ID from there.

## Acceptance Criteria

A release of the Installer is made with binaries for all the supported architectures

## In Scope

 - Builds of the Go binary for the following os/architectures (see `go tool dist list`):
   - linux/amd64
   - linux/386
   - linux/arm
   - linux/arm64
   - ~darwin/amd64~
   - ~darwin/arm64~
   - ~windows/386~
   - ~windows/amd64~
 - Creation of a `2022.01` release in GitHub releases
 - Creation of a `2022.01` tag
 - Update the Gitpod guides to use the `2022.01` release
 - Tested and working with in-cluster and external dependencies in:
   - AWS
   - Azure
   - GCP

## Out of Scope

 - Automation of pipeline. This is about working out the desired process. Automation will come for February's `2022.02` release
 - Use of Replicated
 - Non-Linux machines:
   - darwin/amd64
   - darwin/arm64
   - windows/386
   - windows/amd64

## Tasks

- [x] #6766 
- [x] Create `releases/2022.01` branch
- [ ] Create a `2022.01` tag
- [x] #7789
- [x] Build binaries and add to GitHub releases
- [ ] #7880
- [ ] Test on and update AWS guide
- [ ] Test on and update Azure guide
- [ ] Test on and update GCP guide
- [x] #7497
- [x] Update the Installer readme to remove references to `./installer` etc and replace with downloaded binary
- [ ] #7820

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Description

The first proper release of the Installer 🎉 🎉 🥳 

This is mostly documentation and stuff to help the build. The only code change is to add in a build tag for `embedVersion`, to allow for the build step to incorporate the versions at build time. This is in addition to the previous two methods of bringing the versions (use of `--debug-version-file` flag and amending binary with `objcopy`) This was added because cannot run the `objcopy` when doing cross-platform builds.

## Related Issue(s)

Fixes #7658 

## How to test

All testing within AWS/Azure/GCP has been done as part of this PR, conforming to the tests defined in #7789 

## Release Notes

```release-note
[Installer]: release 2022.01
```

### CODE REVIEW

**Comment by roboquat** [comment]
@MrSimonEmms: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mrsimonemms** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**
- **[installer/pkg/config/versions/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/config/versions/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mrsimonemms** after the PR has been reviewed.

Associated issue: *#7658*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**
- **[installer/pkg/config/versions/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/config/versions/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by corneliusludmann — APPROVED** [review]
/lgtm
/approve

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: ceb3f74558c7e00d389ea3a1d8404f454d87ed45</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7873#pullrequestreview-865958414" title="Approved">corneliusludmann</a>*

Associated issue: *#7658*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)~~ [corneliusludmann]
- ~~[installer/pkg/config/versions/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/config/versions/OWNERS)~~ [corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
