### PR TITLE
[supervisor] add backuping and restoring user config via context-service

### PR DESCRIPTION
**Pull request by corneliusludmann**
This PR adds a feature to the supervisor to restore user-specific configurations (e.g. IDE config) on workspace start and backup user-specific configurations on workspace stop.

This PR is ready for review.

Two things are left:
- [x] ~Some `ws-manager` tests are failing for some reason.~
- [ ] The exact configuration of the globs that should be backuped. See: https://github.com/gitpod-io/gitpod/blob/7288df0ac67aa9f31096f93f925252fd62211514/components/supervisor/pkg/supervisor/content-store.go#L38

Feedback is very welcome.

### CODE REVIEW

**Comment by corneliusludmann** [comment]
@akosyakov With this PR, we could backup Code (and Theia) user settings to the content store. What it needs is a list of [glob patterns](https://github.com/bmatcuk/doublestar#patterns) for files that need to be backuped, see: https://github.com/gitpod-io/gitpod/blob/7288df0ac67aa9f31096f93f925252fd62211514/components/supervisor/pkg/supervisor/content-store.go#L38

**Comment by akosyakov** [comment]
@corneliusludmann Does glob also support exclusion, i.e. `"/home/gitpod/.theia/**/*","!/home/gitpod/.theia/layout" ? `!` - for exclusion?

**Comment by corneliusludmann** [comment]
@akosyakov: That's not supported yet but I can easily implement this if it helps.

**Comment by akosyakov** [comment]
It will be necessary for Code user data. We don't want to persist all of them.

**Comment by corneliusludmann** [comment]
@akosyakov: Exclusion support added in https://github.com/gitpod-io/gitpod/commit/9347750152b06963743128e4097020052c54f572: Sample glob config: https://github.com/gitpod-io/gitpod/blob/9347750152b06963743128e4097020052c54f572/components/supervisor/pkg/supervisor/content-store.go#L38

**Comment by csweichel** [comment]
We've decided to go another route for now (vs code resource sync).

**Pull request closed without merging**
