### PR TITLE
[supervisor] Increase sendHeartBeat to 30s plus a random additional wait

### PR DESCRIPTION
**Pull request by aledbf**
## Description

The current `sendHeartBeat` value is low

## Release Notes

```release-note
NONE
```

Screenshot from 2021-09-08 09-08-52

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **csweichel** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @csweichel` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by akosyakov** [comment]
Is there an explanation somewhere why it is too low? We should align it in VS Code Desktop then too: https://github.com/gitpod-io/vscode/blob/c92ea059cc91b7023afe1b998240b9b7a3abc8af/extensions/gitpod-remote/src/extension.ts#L205? And in new JetBrains integration we should also use the same value?

**Comment by aledbf** [comment]
> Is there an explanation somewhere why it is too low?

I could not find a reason for the value. I attached a screenshot of the behavior we have in prod

**Comment by csweichel** [comment]
Considering that our timeouts are in the order of minutes to hours, sampling activity at a 10s interval seems too much. 30s is a better choice imho, especially looking at the `findInstanceById` cost.

@akosyakov can we merge this one and follow up with a PR that aligns VS Code Desktop?

**Comment by akosyakov** [comment]
> @akosyakov can we merge this one and follow up with a PR that aligns VS Code Desktop?

Sure, can you file a follow up issue and add to groundwork? I can do it and release a new version of the extension.

**Review by akosyakov — APPROVED** [review]
/lgtm

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: a8a1bdc87232044fce13b1d0d4ee2b81914c18cb</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5613#pullrequestreview-751210358" title="LGTM">akosyakov</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [akosyakov]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5613#issuecomment-916757161" title="Approved">akosyakov</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/5613#issuecomment-916757161" title="Approved">akosyakov</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [akosyakov]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
