### PR TITLE
[wsman-bridge] Lint typescript files

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

Ran `pre-commit run --files components/ws-manager-bridge/**/*.ts` with bash expansion. Contains no logic changes.

## Related Issue(s)

Fixes #

## How to test

CI passes

## Release Notes

```release-note
NONE
```

## Documentation

NONE

### CODE REVIEW

**Review by geropl — APPROVED** [review]
:+1:

**Comment by easyCZ** [comment]
I am in https://github.com/gitpod-io/gitpod/pull/9422/files, but this is an intentional pre-pr.

**Comment by easyCZ** [comment]
@geropl I had to fix CI and rebase, would you be able to approve again, please?

**Review by geropl — APPROVED** [review]

**Pull request merged**
