### PR TITLE
[db] Remove usages of the `d_b_layout_data` table

### PR DESCRIPTION
**Pull request by andrew-farries**
## Description

Remove all usages of the `d_b_layout_data` table.

The table itself is dropped in a follow up PR: https://github.com/gitpod-io/gitpod/pull/13526

See ([Slack thread](https://gitpod.slack.com/archives/C01KGM9BH54/p1664290138597739)) for additional context.

## Related Issue(s)
Part of #9198 

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]
LGTM.

I'd personally feel more comfortable if we first remove usage in the codebase and only then added the table drop. 
As it stands, when we roll out we still run the old version of the services while we run the migrations. This can cause errors if something does write to it during the migration.

/hold for consideration to remove usage first, before dropping the table.

**Comment by andrew-farries** [comment]
> I'd personally feel more comfortable if we first remove usage in the codebase and only then added the table drop.

I've separated the code removal (this PR) and the table drop into  https://github.com/gitpod-io/gitpod/pull/13526.

**Review by Furisto — APPROVED** [review]

**Comment by jeanp413** [comment]
Just needed a rebuild, it's working fine :tada:

**Review by jeanp413 — APPROVED** [review]

**Pull request merged**
