### PR TITLE
[ws-manager-mk2] Run integration tests against mk2 by default in GHA (+ preview fixes)

### PR DESCRIPTION
**Pull request by WVerlaek**
## Description
Runs workspace integration tests against mk2 by default (both in the scheduled job, and in manual dispatch inputs)

Also includes several fixes and improvements needed to run the tests:
- Update `name` and `version` workflow inputs to not be required, and allow either one to be set without the other
- Remove previewctl hash, this was causing not-found errors when downloading the `previewctl` binary as the hash was constructed incorrectly. Not specifying any hash will also try to download the latest version which is what we want
- Fix preview environment sometimes failing to create with mk2 enabled, due to namespaces sometimes being applied after the manifests in that namespace, causing those manifests to fail to apply. Specifically this was failing for the `workspace-secrets` namespace used for mk2. Fixed by first applying namespaces to the preview env, and then all other manifests.
- Fix preview env creation failing with mk2 enabled, as it's waiting for the non-existent mk1 deployment
- Fix tests still trying to use the removed `image-builder-mk3-wsman` deploy

## Related Issue(s)

Fixes WKS-98

## How to test

1. Run the workspace integration tests GHA workflow from this branch, for mk1 and for mk2
2. Build a preview environment, ensure that flow still works

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - wv-mk2-rund31883caca</li>
	<li><b>🔗 URL</b> - <a href="https://wv-mk2-rund31883caca.preview.gitpod-dev.com/workspaces" target="_blank">wv-mk2-rund31883caca.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
</ul>

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

/hold

### CODE REVIEW

**Comment by WVerlaek** [comment]
Will add a temporary workflow to run the tests against mk1 on a schedule as well in a separate PR

**Comment by kylos101** [comment]
Taking a look now, will build a large preview in GCE to inspect the outcome

**Review by kylos101 — COMMENTED** [review]
:wave: when I build a preview environment using the check boxes :point_up: , I get the following error:

```
INFO: Applying manifests (installing)
Error from server (AlreadyExists): namespaces "werft" already exists
Error from server (NotFound): jobs.batch "migrations" not found
/github/workspace/dev/preview/temp-installer /github/workspace/dev/preview
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
time="2023-04-28T17:45:47Z" level=fatal msg="failed with exit code 1"
```

Recommendation:
Try iterating with:

```
TF_VAR_infra_provider="gce" TF_VAR_with_large_vm=true leeway run dev:preview
```

The environment GHA built looks like this:
```
gitpod /workspace/gitpod (wv/mk2-run-integration-tests) $ kubectx -c
wv-mk2-rund31883caca
gitpod /workspace/gitpod (wv/mk2-run-integration-tests) $ kubens -c
default
gitpod /workspace/gitpod (wv/mk2-run-integration-tests) $ k get pods
NAME               READY   STATUS    RESTARTS   AGE
fluent-bit-jwsjc   1/1     Running   0          4h44m
```

**Comment by kylos101** [comment]
Rerunning [here](https://github.com/gitpod-io/gitpod/actions/runs/4851396752?pr=17393) (removed large VM)

**Comment by kylos101** [comment]
Testing mk2 tests in https://github.com/gitpod-io/gitpod/actions/runs/4851865432 (the mk2 box gets checked automatically when you switch to this branch :heavy_check_mark: ).

Also, started a workspace in the preview env:
image

**Comment by kylos101** [comment]
Testing mk1 run in https://github.com/gitpod-io/gitpod/actions/runs/4851885456

**Comment by kylos101** [comment]
Testing mk2 run in https://github.com/gitpod-io/gitpod/actions/runs/4851903279

**Comment by kylos101** [comment]
mk1 deploys and tests start :heavy_check_mark: 
mk2 deploys and tests start :heavy_check_mark:

**Review by kylos101 — APPROVED** [review]
:shipit:

**Pull request merged**
