### PR TITLE
[dashboard] Correctly show loading state when subscribing a team to usage-based billing

### PR DESCRIPTION
**Pull request by jankeromnes**
## Description

Correctly show loading state when subscribing a team to usage-based billing.

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/issues/10656

## How to test

Same test process as in https://github.com/gitpod-io/gitpod/pull/10630
 
...except, after you've just submitted your credit card details:
- the state should not briefly show you "Billing: Not active" with a green button again
- instead, the UI should immediately be "pending"
- (and eventually become "Billing: Active" when the Stripe processing is done)

| 1. Inactive | 2. Add card | 3. Pending | 4. Active |
| --- | --- | --- | --- |
| Screenshot 2022-06-24 at 18 02 00 | Screenshot 2022-06-24 at 18 02 15 | Screenshot 2022-06-24 at 18 02 25 | Screenshot 2022-06-24 at 18 03 02 |

(Should not show 1. again between 2. and 3.)

## Release Notes

```release-note
NONE
```

## Documentation

- [x] /werft with-preview=true
- [x] /werft with-payment=true

### CODE REVIEW

**Comment by roboquat** [comment]
@jankeromnes: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jankeromnes** [comment]
**Hint**: Reviewing without whitespace/indentation changes is easier: https://github.com/gitpod-io/gitpod/pull/10658/files?w=1

Also, re-running with payment:

/werft run

**Comment by jankeromnes** [comment]
Hmm, the fix is not sufficient. We have two effects that race to set `isLoading(false)` 🤔 seems like another case of "isLoading boolean is bad practice" -- let's see if I can precisely determine the loading conditions based on what's actually happening.

**Review by geropl — APPROVED** [review]
Thank you, works nicely! :orange_heart: 
image

**Pull request merged**
