### PR TITLE
[installer]: promote experimental agent-smith config

### LINKED ISSUE #15837: Promote Agent Smith from experimental config

### PR DESCRIPTION
**Pull request by mrsimonemms**
## Description

> This depends upon #15773

Promote the agent-smith config from `experimental` to the mainline

## Related Issue(s)

Fixes #15837

## How to test

No changes in render tests except config change

## Release Notes

```release-note
[installer]: promote experimental agent-smith config
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by Furisto — APPROVED** [review]

**Review by Pothulapati — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
