### PR TITLE
Allow setting customTimeoutAnnotation for headless workspace pods

### PR DESCRIPTION
**Pull request by jankeromnes**
This changes two things:

- In `server`: Don't set `customTimeoutAnnotation` when starting headless pods (currently ignored by ws-manager)
- In `ws-manager`: Honor `customTimeoutAnnotation` for headless pods (when it is set)

See also [Slack discussion](https://gitpod.slack.com/archives/C0204GGRKT4/p1621342252000100) (internal)

And also (optionally):

- In `ws-manager`: When a workspace times out, log both how long it took and the expected timeout (new)

### How to test

1. Start a regular workspace (for any repo)
2. The workspace pod should still have a `gitpod/customTimeout` label (e.g. `30m` if you're on the Open Source / Free plan)
3. Start a prebuild (e.g. using the `#prebuild/` manual prefix)
4. The prebuild pod should **not** have a `gitpod/customTimeout` label
5. If you manually set a `gitpod/customTimeout` label on the prebuild pod (e.g. `1m`), the prebuild should honor it instead of the default headless timeout (which is `60m`)

### CODE REVIEW

**Comment by jankeromnes** [comment]
Failed with:

```
=== RUN   TestIsWorkspaceTimedout/testdata/timeout_regular_withActivityOK.json
    fixtures.go:128: fixture testdata/timeout_regular_withActivityOK.json: [Reason:  != workspace timed out after period of inactivity took longer than 00h01m]
--- FAIL: TestIsWorkspaceTimedout (0.00s)
    --- PASS: TestIsWorkspaceTimedout/testdata/timeout_customTimeout_invalidValue.json (0.00s)
    --- PASS: TestIsWorkspaceTimedout/testdata/timeout_customTimeout_noActivity.json (0.00s)
    --- PASS: TestIsWorkspaceTimedout/testdata/timeout_customTimeout_validValue.json (0.00s)
    --- PASS: TestIsWorkspaceTimedout/testdata/timeout_interrupted_noActivity.json (0.00s)
    --- PASS: TestIsWorkspaceTimedout/testdata/timeout_interrupted_withActivity.json (0.00s)
    --- PASS: TestIsWorkspaceTimedout/testdata/timeout_prebuild_Creating00.json (0.00s)
    --- PASS: TestIsWorkspaceTimedout/testdata/timeout_prebuild_Pending00.json (0.00s)
    --- PASS: TestIsWorkspaceTimedout/testdata/timeout_prebuild_overdue.json (0.00s)
    --- PASS: TestIsWorkspaceTimedout/testdata/timeout_probe_Creating00.json (0.00s)
    --- PASS: TestIsWorkspaceTimedout/testdata/timeout_regular_closed.json (0.00s)
    --- PASS: TestIsWorkspaceTimedout/testdata/timeout_regular_noActivity.json (0.00s)
    --- FAIL: TestIsWorkspaceTimedout/testdata/timeout_regular_withActivityOK.json (0.00s)
```

Not sure what this is about.

**Comment by jankeromnes** [comment]
Seems to work as expected! 🙌 @csweichel please take a look when you have time

**Comment by jankeromnes** [comment]
(I also snuck in a new test 😁 basically a copy of the timing-out prebuild, but with a custom timeout of 2h so that it doesn't time out.)

**Review by csweichel — APPROVED** [review]
LGTM

**Pull request merged**
