### PR TITLE
[baseserver] Serve pprof on /debug/pprof

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

Adds pprof https://pkg.go.dev/net/http/pprof

## Related Issue(s)

* Relates to https://github.com/gitpod-io/gitpod/issues/9229

## How to test

Unit tests

## Release Notes

```release-note
NONE
```

## Documentation

NONE

### CODE REVIEW

**Review by andrew-farries — APPROVED** [review]

**Comment by easyCZ** [comment]
@andrew-farries Thanks for the review. Had to rebase so lost the approval :/

**Review by andrew-farries — APPROVED** [review]

**Review by andrew-farries — APPROVED** [review]

**Comment by easyCZ** [comment]
/hold

And had to rebase again.. this is getting annoying. Also adding hold to remove it from the merge pool as it's blocking other PRs.

**Pull request merged**
