### PR TITLE
:wrench: Ambiguity of `New Workspace` option & :rocket: new `Settings` option 

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

:wrench: Ambiguity of `New Workspace ...` option & :rocket: new `Settings` option in Project List Item

## Related Issue(s)

Fixes [Internal Conversastion](https://gitpod.slack.com/archives/C01KPEPNBD0/p1677163519383559?thread_ts=1677151354.576229&cid=C01KPEPNBD0)

## How to test

- Open Preview
- Go to `/projects`
- And Click Menu Item (Three dots) of any Project. See 👀 
    - New `Settings` option
    - Modified `New Workspace ...`

## Release Notes

```release-note
Access Project Settings directly from Projects Page on Project Menu Items
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-slow-database
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

> Signed-off-by: Siddhant Khare <siddhant@gitpod.io>

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
🤔 🤷🏽‍♂️ 

https://user-images.githubusercontent.com/55068936/221090265-ea1f10c8-e052-4aa8-b482-7853608641c5.mov

**Comment by geropl** [comment]
Currently seeing this: 
image

Could you do a rebase @Siddhant-K-code ? :pray:

**Comment by Siddhant-K-code** [comment]
@geropl Done ✅

**Review by easyCZ — APPROVED** [review]
LGTM

/hold in case you want feedback from design

**Comment by Siddhant-K-code** [comment]
@easyCZ @geropl `Settings` doesn't seem to be working in Production also 🤔 


https://user-images.githubusercontent.com/55068936/221613310-05b1d33d-aa83-485e-87eb-8f92f691a6d1.mov

**Pull request merged**
