### PR TITLE
[installer]: add jaeger sampling options to the tracing object

### LINKED ISSUE #7698: [installer] There is no option to set a sampling strategy in the observability section
### Bug description

Right now we trace [100% of the events](https://github.com/gitpod-io/gitpod/blob/92a9fd5fb04cfe34d65c26611c37a886e85e593a/installer/pkg/common/common.go#L82-L85). This could be an issue in SaaS options (like honeycomb)

### Steps to reproduce

Initialize and render the manifests, using the installer. 
Check `JAEGER_SAMPLER_TYPE` is configured to `const` and `JAEGER_SAMPLER_PARAM` is `1`

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Description

Adds Jaeger sampling options to the new experimental (and unsupported) config section

The config object is now:

```yaml
observability:
  tracing: # The tracing object is required to activate the tracing option in the experimental
    endpoint: <url-of-endpoint> 
experimental:
  workspace:
    tracing:
      samplerType: const
      samplerParam: 1
```

This adds the ability to configure the sampler options for the tracing object. This validates the types/params against the [Jaeger client](https://github.com/jaegertracing/jaeger-client-go/blob/967f9c36f0fa5a2617c9a0993b03f9a3279fadc8/config/config.go#L71)

There is validation added to support this:
 - if `tracing` is omitted or `samplerType` or not configured, no error happens. This retains the same `const` and `1` default values as now
 - if `tracing.samplerType` is added, it ensures that the `samplerType` meets one of the options defined by Jaeger. It also requires the `tracing.samplerParam`, as this value is coupled to the `samplerType`

## Related Issue(s)

Fixes #7698

## How to test

Run `validate config` whilst changing the params to check the validation. Run `render` to generate a new Installer YAML

## Release Notes

```release-note
[installer]: add jaeger sampling options to the tracing object
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mrsimonemms** after the PR has been reviewed.

Associated issue: *#7698*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by MrSimonEmms** [comment]
/hold

@corneliusludmann I will need your approval for this to be merged. I would also like @aledbf's approval as well as this change has been requested by him

**Comment by corneliusludmann** [comment]
cross-posting a comment I just added to the issue: https://github.com/gitpod-io/gitpod/issues/7698#issuecomment-1018311264

**Review by corneliusludmann — APPROVED** [review]
/lgtm
/approve

Code looks code.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 562cbb58a1bd4425024bd7417597dc689617b238</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7727#pullrequestreview-863566812" title="Approved">corneliusludmann</a>*

Associated issue: *#7698*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)~~ [corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7727#pullrequestreview-863566812" title="Approved">corneliusludmann</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **aledbf** and additionally assign **jankeromnes** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankeromnes` in a comment when ready.

Associated issue: *#7698*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- ~~[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)~~ [corneliusludmann]
- **[installer/pkg/components/agent-smith/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/agent-smith/OWNERS)**
- **[installer/pkg/components/blobserve/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/blobserve/OWNERS)**
- **[installer/pkg/components/content-service/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/content-service/OWNERS)**
- **[installer/pkg/components/image-builder-mk3/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/image-builder-mk3/OWNERS)**
- **[installer/pkg/components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/registry-facade/OWNERS)**
- **[installer/pkg/components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/server/OWNERS)**
- **[installer/pkg/components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-daemon/OWNERS)**
- **[installer/pkg/components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-manager/OWNERS)**
- **[installer/pkg/components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-manager-bridge/OWNERS)**
- **[installer/pkg/components/ws-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-proxy/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sagor999 — APPROVED** [review]
@aledbf is on vacation, so approving on his behalf. LGTM.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 80e1d8e96bce3a7cb2e6d171476f33ebdaf2d674</details>

**Review by JanKoehnlein — APPROVED** [review]
LGTM

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7727#pullrequestreview-863566812" title="Approved">corneliusludmann</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7727#pullrequestreview-870336063" title="Approved">JanKoehnlein</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7727#pullrequestreview-869388946" title="Approved">sagor999</a>*

Associated issue: *#7698*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)~~ [corneliusludmann]
- ~~[installer/pkg/components/agent-smith/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/agent-smith/OWNERS)~~ [sagor999]
- ~~[installer/pkg/components/blobserve/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/blobserve/OWNERS)~~ [sagor999]
- ~~[installer/pkg/components/content-service/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/content-service/OWNERS)~~ [sagor999]
- ~~[installer/pkg/components/image-builder-mk3/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/image-builder-mk3/OWNERS)~~ [sagor999]
- ~~[installer/pkg/components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/registry-facade/OWNERS)~~ [sagor999]
- ~~[installer/pkg/components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/server/OWNERS)~~ [JanKoehnlein]
- ~~[installer/pkg/components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-daemon/OWNERS)~~ [sagor999]
- ~~[installer/pkg/components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-manager/OWNERS)~~ [sagor999]
- ~~[installer/pkg/components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-manager-bridge/OWNERS)~~ [JanKoehnlein]
- ~~[installer/pkg/components/ws-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-proxy/OWNERS)~~ [sagor999]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
