### PR TITLE
[code] Update code to 1.61

### LINKED ISSUE #6000: [code] update latest to VS Code 1.61
There is already a release branch: https://github.com/microsoft/vscode/tree/release/1.61
We should set up the same branch in our fork with changes from gp-code and test it.

### PR DESCRIPTION
**Pull request by jeanp413**
## Description
Updates code to 1.61
https://github.com/gitpod-io/openvscode-server/commit/bc3ac84b6b50a15dbcf845bdab46141ffbf8364e

## Related Issue(s)

Fixes #6000

## How to test

1. Switch to latest VS Code in settings.
2. Start a workspace.

Test following:
- terminals are preserved and resized properly between window reloads
- extension host process: check language smartness and debugging
- extension management (installing/uninstalling)
  - install VIM extension to test web extensions
- that user data are sync across workspaces as well as on workspace restart, especially for extensions
  - extensions from .gitpod.yml are not installed as sync
  - extensions installed as sync are actually sync in new workspaces
- settings should not contain any mentions of MS telemetry
- websockets and workers are properly proxied
  - diff editor should be operatable
  - trigger reconnection with window.WebSocket.disconnectWorkspace(), check that old websockets are closed and new opened of the same amount
- workspace specific commands should work, i.e. F1 → type Gitpod prefix
- that a PR view is preloaded on the PR url
- test gp open and preview
- test open in VS Code Desktop, check gp open and preview in task/user terminals

## Release Notes
```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jeanp413** after the PR has been reviewed.

Associated issue: *#6000*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by akosyakov** [comment]
I did usual testing and it looks good.

/lgtm

Please next time add testing steps and a link to Gitpod Code commit. thanks

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 4c27865fade78469ba682c04e6824f15029f7864</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6029#issuecomment-934223088" title="LGTM">akosyakov</a>*

Associated issue: *#6000*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)~~ [akosyakov]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by jeanp413** [comment]
@akosyakov updated the commit with the latest changes from upstream

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6029#issuecomment-935573704" title="LGTM">akosyakov</a>*

Associated issue: *#6000*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)~~ [akosyakov]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
