### PR TITLE
[content-service] Do not remove .docker-root

### PR DESCRIPTION
**Pull request by aledbf**
After the prebuild:
```console
gitpod /workspace/ddev-gitpod $ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
gitpod /workspace/ddev-gitpod $ docker images
REPOSITORY                        TAG                         IMAGE ID            CREATED             SIZE
drud/ddev-webserver               v1.16.7-ddev-gitpod-built   a027c9ae94f9        3 minutes ago       1.16GB
drud/ddev-dbserver-mariadb-10.3   v1.16.0-ddev-gitpod-built   0c5a74e58990        3 minutes ago       640MB
drud/ddev-ssh-agent               v1.16.0-built               1c63db0571b7        3 minutes ago       113MB
phpmyadmin                        5                           622471936dcc        4 days ago          477MB
busybox                           latest                      a9d583973f65        3 weeks ago        11.23MB
drud/ddev-webserver               v1.16.7                     48ca5db4a356        4 weeks ago         1.16GB
drud/ddev-router                  v1.16.2                     9f085cfd7877        3 months ago        243MB
drud/ddev-dbserver-mariadb-10.3   v1.16.0                     2f19a2bac03d        4 months ago        640MB
drud/ddev-ssh-agent               v1.16.0                     5995b3ec37aa        4 months ago        113MB
```

fixes https://github.com/gitpod-io/gitpod/issues/3671

### CODE REVIEW

**Comment by svenefftinge** [comment]
I think the idea was to don't leak anything from the prebuild if the initialization fails, but completely fall back to the git initialization. Did you figure out why the prebuild initialization failed, although it seems to have content?

**Comment by aledbf** [comment]
> did you figure out why the prebuild initialization failed, although it seems to have content?

If the rebuild uses `docker-up` we need to preserve `.docker-root`. Even if there is an error during the rebuild. 
Otherwise, the workspace will start from scratch.

**Comment by shaal** [comment]
Please let me know if I can help testing this (I'll need a working build I can access)

**Comment by csweichel** [comment]
Mind: prebuild failure here does not mean "tasks failed during the prebuild", but rather "restoring the prebuild snapshot failed". In this case we do not know in which state a `.docker-root` may be (we don't know for any file), hence we remove everything.

**Comment by aledbf** [comment]
> If it doesn't, that's a regression in how we shut down tasks/stuff running in a workspace.

`docker-up` does not receive the term signal (the sudo command returns permission denied)

**Comment by csweichel** [comment]
> docker-up does not receive the term signal (the sudo command returns permission denied)

That makes sense - and that's also what we should fix (see https://github.com/gitpod-io/gitpod/issues/3671#issuecomment-811938194)

**Comment by svenefftinge** [comment]
I still wonder why the initialization fails. Initialization should not fail on "failed prebuilds" as we want to present the user with the failed state.

**Comment by aledbf** [comment]
Closing. Replaced by https://github.com/gitpod-io/gitpod/pull/3684

**Comment by aledbf** [comment]
@svenefftinge this issue was related to lack of permissions restoring files

```console
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"snapshot initializer:\n    github.com/gitpod-io/gitpod/content-service/pkg/initializer.(*SnapshotInitializer).Run\n        /tmp/build/components-ws-daemon--content-initializer.6e8bdd09596656c765dfb837728ee8b5363709df/_deps/components-content-service--lib/pkg/initializer/snapshot.go:37\n  - tar /dst: tar /dst: exit status 2;tar: ./.docker-root/overlay2/2e8dd81a4d1a6aa336e6656e157ee8bf1ed41ffaec1af463595c9eb0f72b9f7d/diff/var/lib/apt/lists/auxfiles: Cannot mknod: Operation not permitted\n    tar: ./.docker-root/overlay2/7e06c0352b46a9f0f979d9e39a8d6353161dd23ceebefd571b37a6f5bf01f6d6/diff/etc/apache2/mods-enabled/mpm_event.conf: Cannot mknod: Operation not permitted\n    tar: ./.docker-root/overlay2/7e06c0352b46a9f0f979d9e39a8d6353161dd23ceebefd571b37a6f5bf01f6d6/diff/etc/apache2/mods-enabled/mpm_event.load: Cannot mknod: Operation not permitted\n    tar: ./.docker-root/overlay2/7e06c0352b46a9f0f979d9e39a8d6353161dd23ceebefd571b37a6f5bf01f6d6/diff/var/lib/apache2/module/enabled_by_maint/mpm_event: Cannot mknod: Operation not permitted\n    tar: Exiting with failure status due to previous errors:\n    github.com/gitpod-io/gitpod/ws-daemon/pkg/content.(*remoteContentStorage).Download\n        /tmp/build/components-ws-daemon--content-initializer.6e8bdd09596656c765dfb837728ee8b5363709df/pkg/content/initializer.go:334","level":"warning","location":"/dst","message":"prebuilt init was unable to restore snapshot workspaces/gold-dove-68ii4zbr/snapshot-1617290849981159738.tar@gitpod-user-bc48a6ed-5f54-4b59-8570-c7b3367b9b52. Resorting the regular Git init","severity":"WARNING","time":"2021-04-01T15:28:19Z"}
```

**Pull request closed without merging**
