### PR TITLE
[terraform] Give AWSS3FullAccess to s3 IAM users

### LINKED ISSUE #13017: [bug] Fix the S3 backend registry pre-flight check failure for eks automated test

### PR DESCRIPTION
**Pull request by nandajavarma**
## Description

This PR essentially reverts [this one](https://github.com/gitpod-io/gitpod/pull/12965/files). Even though with AWS CLI the permission seems enough, `mc` cli that we use for preflights(probably for other ops in Gitpod, not sure) requires a lot more permissions to do S3 ops. This is made clean in their documentation [here](https://github.com/minio/mc#example---amazon-s3-cloud-storage).

## Related Issue(s)

Fixes #13017 

## How to test

You can run the pipeline using:
```
werft run github -j .werft/eks-installer-tests.yaml -a deps=external -a domain=tests.doptig.com
```

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by mrzarquon** [comment]
@nandajavarma since we are handing this out to customers as example reference architecture, I don't think we should be including extremely broad permissions that only need to exist for our CI jobs to work properly.

**Comment by adrienthebo** [comment]
> @nandajavarma since we are handing this out to customers as example reference architecture, I don't think we should be including extremely broad permissions that only need to exist for our CI jobs to work properly.
> 
> Double checking - is this the S3 preflight check done in our CI or in KOTS? In either case, it these are the minimum required permissions for our services to function, requiring them to be more permissive just because of how we want to validate them isn't a good idea.

I believe that this is the [preflight check](https://github.com/gitpod-io/gitpod/blob/main/components/kots-config-check/storage/entrypoint.sh#L107-L139) in KOTS.

That said, I believe our reference architecture documentation uses a [reduced permission set](https://www.gitpod.io/docs/self-hosted/latest/reference-architecture/single-cluster-ref-arch#object-storage), will double check that.

**Comment by nandajavarma** [comment]
Have created these follow up issues to fix the preflight check and reduce the permissions:
- https://github.com/gitpod-io/gitpod/issues/13332
- https://github.com/gitpod-io/gitpod/issues/13333

@adrienthebo @mrzarquon Do you think we can ship this now for the sake of the release and take up the follow-ups after?

**Review by adrienthebo — APPROVED** [review]
Since the Terraform module isn't shipped as part of the KOTS release and we're running on a schedule this week, let's merge this change, cut the release branch, and then clean up the IAM permissions right after the release. We take on minimal liability with this and merging this change keeps the release on track.

🚢

**Pull request merged**
