### PR TITLE
[supervisor] Improve observability/error handling around openPort

### PR DESCRIPTION
**Pull request by geropl**
## Description
To move on with issue #7054 ("port stuck in observing bc of lost workspace updates") and identifying it's root cause, here are some constructive suggestions how to a) extend the logging increase observability of this issue and b) improve the stability around the `openPort` call:
 - when # of API call attempts are exceeded: print a warning and forward error to client (happen regularly, e.g. due to rate limiter)
 - log `.Warn`ings whenever there is a temporary disconnect. The code waits for 1 second before reconnect; could very well explain a leak - especially if we do not re-fetch afterwards
 - Fetch WorkspaceInstance after reconnection happened

@jeanp413 @iQQBot I hope that one of you can pick this up and complete it.

/cc @akosyakov 

## Related Issue(s)

Context: #7054 

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** and additionally assign **filiptronicek** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @filiptronicek` in a comment when ready.

Associated issue: *#7054*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jeanp413** [comment]
>  - when # of API call attempts are exceeded: print a warning and forward error to client (happen regularly, e.g. due to rate limiter)
>  - log `.Warn`ings whenever there is a temporary disconnect. The code waits for 1 second before reconnect; could very well explain a leak - especially if we do not re-fetch afterwards
>  - Fetch WorkspaceInstance after reconnection happened

@geropl @akosyakov  If you could leave some code pointers/steps required for this bullets points it would be great :slightly_smiling_face:

**Comment by geropl** [comment]
@jeanp413 The bullet points roughly correspond to the commits on this branch (in that order). What's left is IMO 1.) reviewing thoroughly, especially on side-effects (e.g., is the generated error handled somewhere?), and 2.) testing if this works.

One point is left todo, though: https://github.com/gitpod-io/gitpod/pull/7574/commits/ba11ad940fcc16bd76b38ff0e1bc26c448e0eedc#diff-922abba803b9a828f3c6ccb017a6080693880bd2f888ccceb1922aba6651f8e9R285

You could also argue that the level of abstraction for registering "reconnectionHandlers" is not the right one, but that's up to you. And I think the suggested approach would already help a ton.

**Comment by akosyakov** [comment]
> W.r.t. to the last commit one could also argue that the level of abstraction for registering "reconnectionHandlers" is to generic, and the whole "re-fetch WorkspaceInstance on reconnect for all listeners" could be lifted into the GitpodService. But that's up to you/the IDE team. And I think the suggested approach would already help a ton.

Yes I think we discussed something like that in another attempt by Cornelius here. Do you mean something like that https://github.com/gitpod-io/gitpod/pull/7058#discussion_r762761047?

**Comment by geropl** [comment]
> Yes I think we discussed something like that in another attempt by Cornelius here. Do you mean something like that 

@akosyakov Yes, like your suggestion! :dart: Not sure what triggers a sync in there, but it should be a "reconnection". Checking for order sounds also great.

**Comment by akosyakov** [comment]
@jeanp413 is working on it, relevant issue for IDE team: https://github.com/gitpod-io/gitpod/issues/6778

**Comment by akosyakov** [comment]
We figured out a root cause of undetected ports. But I think we still should apply at least some improvements in this PR, namely when we reconnect we should force sync otherwise we indeed can miss events.

**Pull request closed without merging**
