### PR TITLE
[installer]: add example for post-processing the YAML

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Description

Document an example of how to post-process the YAML. This should be thought of as a message to the community rather than comprehensive documentation.

Replaces #7280 

## How to test

Follow instructions.

## Release Notes

```release-note
[installer]: add example for post-processing the YAML
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mrsimonemms** after the PR has been reviewed.

Associated issue: *#7280*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by csweichel** [comment]
Are we sure we want to point this out? If so, we should make it drastically clear that by going down this path there will be no support available.

**Comment by MrSimonEmms** [comment]
@csweichel we have to put _something_* as there are lots of people in Discord etc saying "I can't do _x_ in the Installer that I could do in Helm and need it for <reasons>". For the most part, these are things that we're unlikely to want to add in and certainly not in the short term. By adding an example of what I mean by "you can post-process the YAML", that should reduce the support requests we need to detail

\* This is my opinion on "something". I'm happy to debate if it's the correct something

**Comment by MrSimonEmms** [comment]
@csweichel I added a "here be dragons" warning to the readme

**Comment by csweichel** [comment]
> @csweichel we have to put _something_* as there are lots of people in Discord etc saying "I can't do _x_ in the Installer that I could do in Helm and need it for ". For the most part, these are things that we're unlikely to want to add in and certainly not in the short term. By adding an example of what I mean by "you can post-process the YAML", that should reduce the support requests we need to detail
> 
> * This is my opinion on "something". I'm happy to debate if it's the correct something

That makes sense. It also means that for future interactions we need to ask if folks "customised" their rendered YAML.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 154067dd1bb3f07c78b8d7e8dc208d8f6cf950a8</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7364#issuecomment-1004075413" title="LGTM">corneliusludmann</a>*

Associated issue: *#7280*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)~~ [corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
