### PR TITLE
[dashboard] lint warnings: NewProject.tsx

### PR DESCRIPTION
**Pull request by trumbitta**
## Description

As per https://discord.com/channels/816244985187008514/885406100436951080/953232219261009950

This fixes the first bits of lint warnings.

Specifically: 
- adds ESLint and Prettier to the auto-installed VSCode extensions
- activates format on save for TypeScript and JavaScript
- adds a `.gp-link` Tailwind class to make buttons mimic links and avoid using `<a href="javascript:void(0)" ...>`
- fixes all the linting warnings for `projects/NewProject.tsx`

## Related Issue(s)

Re #3841 

## How to test

- launch the dashboard app
- try to create a new project: it should still work
- look in the console logs or in the terminal: there shouldn't be any lint warning for `projects/NewProject.tsx`
- if you are using VSCode, try opening a TypeScript file and check if "format on save" via the Prettier extension is working (remember Prettier won't work if there are syntax errors - red wiggles - in the file)

## Release Notes

```release-note
- [devx]: Added ESLint and Prettier to the auto-installed VSCode extensions
- [devx]: Activated "format on save" for TypeScript and JavaScript
- [dashboard]: Added a `.gp-link` Tailwind class to make buttons mimic anchor tags
- [dashboard]: Fixed all the linting warnings for `projects/NewProject.tsx`
```

### CODE REVIEW

**Comment by trumbitta** [comment]
👀🤞

**Comment by trumbitta** [comment]
Weekly ping to @jankeromnes  🤣

**Comment by jankeromnes** [comment]
Oh no 🙈 I thought I was better than that at noticing the pings. Having a look 👀

**Comment by jankeromnes** [comment]
Okay, let's have a look 👀 thanks for your patience!

/werft run

**Comment by trumbitta** [comment]
> 👎 cannot start job - please talk to whoever's in charge of your Werft installation

Oh no, werft's a it again!

`Invalid value: "gitpod-build-trumbitta-dashboard-lint-warnings-3841-new-pr-fork.0": must be no more than 63 characters`

I try to keep branch names short, but all the stuff gitpod and werft (?) add makes it difficult... could this 63 characters cap be raised a bit?

Brb renaming the branch.

**Comment by jankeromnes** [comment]
Indeed, sorry about that @trumbitta -- FYI, I've bypassed the branch name problem by pushing your commit directly to a shorter Gitpod branch. 😇

**Comment by jankeromnes** [comment]
> I also renamed the original branch and was going to open a new PR (I had hoped GitHub would cascade the name change but it didn't).

Yes, GitHub doesn't support renaming PR branches for some reason. 😅

> Should I go on and reopen the PR with my new branch?
> I can't find yours 🕵️‍♂️

Yes please! 🙏 (I didn't open a PR, but simply pushed your commit to [this branch](https://github.com/gitpod-io/gitpod/tree/pr-8842), which had the effect of making Werft build the commit without issues and even report the status here in this PR, since the commits were identical)

**Pull request closed without merging**
