### PR TITLE
[gp] Make 'gp open <file>' work in Code as well

### PR DESCRIPTION
**Pull request by jankeromnes**
Fixes https://github.com/gitpod-io/gitpod/issues/3309

### How to test

1. https://jx-gp-open-code.staging.gitpod-dev.com/#https://github.com/gitpod-io/sveltejs-template
2. `gp open package.json`

Should work in both Theia and Code.

### CODE REVIEW

**Comment by jankeromnes** [comment]
`gp open <file>` now works in Code:

Screenshot 2021-03-08 at 11 47 26

Also still works in Theia:

Screenshot 2021-03-08 at 11 47 39

**Comment by akosyakov** [comment]
Could you set up preview env variable too? I will make use of it later.

**Comment by jankeromnes** [comment]
> Could you set up preview env variable too?

@akosyakov Sure! But what should be the name & value of this preview variable? (Couldn't find a relevant example in the codebase).

**Comment by akosyakov** [comment]
`gp preview` should check `GP_PREVIEW` env variable as a fallback. Actually let's open another issue for it. It depends on https://github.com/gitpod-io/gitpod/issues/2806

**Comment by jankeromnes** [comment]
@akosyakov Thanks! Filed as https://github.com/gitpod-io/gitpod/issues/3382 -- please feel free to comment/edit/assign as relevant.

**Comment by jankeromnes** [comment]
Otherwise this PR is ready to go. @csweichel or @akosyakov please take a look when you have time. 🙏

**Review by csweichel — APPROVED** [review]
LGTM :)

**Review by akosyakov — APPROVED** [review]
LGTM too

**Pull request merged**
