### PR TITLE
[supervisor] fix addgroup adduser command not pair

### LINKED ISSUE #7071: Unable to use Fedora with Image builder mk3
### Bug description

Formerly it was necessary to setup the user environment for the image, which meant that the image took responsibility to create the `gitpod` user and the necessary `CMD` to run.

Since the move to Image builder mk3 it should be possible to use a Fedora image (upstream for Amazon Linux) as a base. However, I run into issues. When I create the user beforehand it complains there already is one... and when I let the builder take care of this, it is unable to locate `goupdadd` as on path. Modifying this has no use

### Steps to reproduce

 `.gitpod.Dockerfile`

```dockerfile
FROM registry.fedoraproject.org/fedora:latest
```

will result in the issue to not able to locate `/usr/sbin/groupadd`
adding `env PATH="/usr/sbin/:${PATH}"` make no difference

----

Running `groupadd` and/or user add will result in a conflict

```dockerfile
# Install user environment
RUN groupadd gitpod && adduser -g gitpod gitpod
```

This will run on the image buillder, but after the image is pulled it will fail as the group already exists.

### Workspace affected

_No response_

### Expected behavior

Being able to use any Fedora/RHEL/CentOS/Rocky/AlmaLinux/AmazonLinux based image,

### Example repository

Have been going back and forth on this already for quite some time: https://github.com/gbraad/gitpod-template-fedora/

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mustard-mh**
## Description

fix addgroup \ adduser command not pair in some os, like `fedora`

## Related Issue(s)

Relate #7071

## How to test

Create a [test repo](https://github.com/mustard-mh/test/tree/fedora) with files below and start a gitpod workspace

`.gitpod.yml`
```yaml
image:
  file: .gitpod.Dockerfile
```
`.gitpod.Dockerfile`
```Dockerfile
FROM registry.fedoraproject.org/fedora:latest
```

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **loujaybee** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @loujaybee` in a comment when ready.

Associated issue: *#7071*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by csweichel** [comment]
The change makes sense. Structurally I preferred the explicit flavours (enum) over the array index. Less chance of a panic at runtime due to out-of-bounds access.

**Comment by mustard-mh** [comment]
As the  [annotation](https://github.com/gitpod-io/gitpod/pull/7417/files#diff-65e6cbf2d2f666b22722ed4a0e4e613f9efb6235e0f18b6883370aaa4b40e77dR233) says, using index instead of enum is to read the data in order (map in go language does [not specify the order](https://go.dev/blog/maps))

> When iterating over a map with a range loop, the iteration order is not specified and is not guaranteed to be the same from one iteration to the next. If you require a stable iteration order you must maintain a separate data structure that specifies that order. 

So what if we sort it before get the value? @csweichel

**Comment by csweichel** [comment]
> As the [annotation](https://github.com/gitpod-io/gitpod/pull/7417/files#diff-65e6cbf2d2f666b22722ed4a0e4e613f9efb6235e0f18b6883370aaa4b40e77dR233) says, using index instead of enum is to read the data in order (map in golang does [not specify the order](https://go.dev/blog/maps))
> 
> > When iterating over a map with a range loop, the iteration order is not specified and is not guaranteed to be the same from one iteration to the next. If you require a stable iteration order you must maintain a separate data structure that specifies that order.
> 
> So what if we sort it before get the value? @csweichel

Did not see that comment. Good point, let's keep it as is :)

**Comment by mustard-mh** [comment]
/unhold

user\group added, but there still have some other problems while starting a `fedora` workspace #7071

**Comment by akosyakov** [comment]
@csweichel @iQQBot good to merge?

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 0762bb31c6bed40bf428a9c3dd336473526d2fd8</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7417#issuecomment-1007260479" title="LGTM">csweichel</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **loujaybee** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @loujaybee` in a comment when ready.

Associated issue: *#7071*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7417#issuecomment-1007260479" title="LGTM">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7417#issuecomment-1007303572" title="Approved">iQQBot</a>*

Associated issue: *#7071*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [iQQBot]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
