### PR TITLE
[usage] Add grafana dashboard

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

Initial dashboard showing ticks of the controller, and RPCs against the endpoints
You can observe it [in staging](https://grafana.gitpod-staging.com/d/8W7P-jg4z/component-usage?orgId=1)

## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Review by andrew-farries — APPROVED** [review]
Nice - RPC latency graph shows 'no data' on staging though - is that expected?

/hold

**Comment by easyCZ** [comment]
> Nice - RPC latency graph shows 'no data' on staging though - is that expected?
> 
> /hold

That's caused by the Usage Controller actually failing in staging. You can see that in the dasbhoard with the Reconcile Completed: Error. [If you go to 2 days, you'll see data](https://grafana.gitpod-staging.com/d/8W7P-jg4z/component-usage?orgId=1&from=now-2d&to=now)

**Comment by easyCZ** [comment]
Sorry, that wasn't the correct answer. The metrics do show it failing the controller tick but it doesn't answer why the RPC latency would show no data. 

The actual reason is that in the time window linked (6h), there were no requests made against the gRPC service.

**Comment by andrew-farries** [comment]
Thanks - the reason it's failing in staging is the object storage upload:

```
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"failed to upload usage report: failed to obtain signed upload URL: failed RPC to content service: rpc error: code = NotFound desc = cannot ensure storage exists: googleapi: Error 403: stag-meta-eu02-storage@gitpod-staging.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket., forbidden","level":"error","message":"Reconciliation run failed.","serviceContext":{"service":"usage","version":"commit-c7c7c058efc4bfad214f1e1a0806a21446b1141b"},"severity":"ERROR","time":"2022-07-26T02:54:16Z"}
```

I wonder if this is unique to staging or whether we are about to see the same failures in production too.

**Review by andrew-farries — APPROVED** [review]

**Pull request merged**
