### PR TITLE
Remove `console.log` statement

### PR DESCRIPTION
**Pull request by andrew-farries**
## Description

Remove a noisy `console.log` from the dashboard.

## Related Issue(s)

None

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]

**Comment by andrew-farries** [comment]
The build fails because `isExperimentEnabled` is now unused. Did you want to keep this `useEffect` as an illustration of how to use a feature flag, or can it be removed?

**Comment by ArthurSens** [comment]
/hold

The failed build is blocking our merge queue 😬

**Review by mustard-mh — CHANGES_REQUESTED** [review]
Need to update import, see werft job logs https://werft.gitpod-dev.com/job/gitpod-build-af-remove-noisy-dashboard-log.1

image

**Comment by laushinka** [comment]
Thanks for opening this, @andrew-farries! This was just to test the feature flag and can be removed.

**Review by laushinka — APPROVED** [review]

**Comment by easyCZ** [comment]
Fixed up the PR.

/unhold

**Pull request merged**
