### PR TITLE
[code] update stable code image to 1.70.1

### PR DESCRIPTION
**Pull request by jeanp413**
## Description

Updates code image for 1.70.1

## Related Issue(s)

Related https://github.com/gitpod-io/gitpod/issues/11638

## How to test

1. Check about dialog says 1.70.1

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Review by andreafalzetti — APPROVED** [review]
Shall we squash the commits before merge? /hold

**Comment by MrSimonEmms** [comment]
/hold

Not sure why, but @andreafalzetti's hold didn't take

**Review by MrSimonEmms — APPROVED** [review]
LGTM. I span it up in a self-hosted instance and opened a workspace ok

**Pull request merged**
