### PR TITLE
[server] snapshots for PVC workspaces

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description
Adds the server part to https://github.com/gitpod-io/gitpod/pull/14374

## Related Issue(s)

contributes to #14159

## How to test
1) Enable PVC 
2) start workspace 
3) take snapshot
4) start snapshot

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by svenefftinge** [comment]
@sagor999 Creating a snapshot takes very long (minutes). When trying to start the resulting snapshot an image build was triggered and the workspace then failed:
```
cannot pull image: rpc error: code = NotFound desc = failed to pull and unpack image "reg.se-pvc-snapshot.preview.gitpod-dev.com:30000/remote/f5e370a1-5c12-4c6c-ad0a-30173bef778b:latest": failed to resolve reference "reg.se-pvc-snapshot.preview.gitpod-dev.com:30000/remote/f5e370a1-5c12-4c6c-ad0a-30173bef778b:latest": reg.se-pvc-snapshot.preview.gitpod-dev.com:30000/remote/f5e370a1-5c12-4c6c-ad0a-30173bef778b:latest: not found
```

**Review by easyCZ — APPROVED** [review]
LGTM,

In the parent PR, I've raised a Q about the RPC being too property specific, and hard to extend. If we do change the RPC, we'll need to adjust this PR.

**Pull request merged**
