### PR TITLE
[ws-daemon] Remove old sandboxing behaviour

### LINKED ISSUE #4993: [ws-manager] Remove old `workspaceSizeLimit` behaviour
We used to produce "sandbox" files when the workspace size limit was set. With re-using this for backups, we inadvertently triggered this old behaviour.

We should remove this behaviour.

### PR DESCRIPTION
**Pull request by csweichel**
fixes #4993

We used to have some means to limit the size of a workspace by placing its content in a loopback-mounted file. This mechanism never worked well and we haven't enabled it in about a year's time. Now, with recent harmonisation on the config surface (https://github.com/gitpod-io/gitpod/pull/4969) we inadvertently re-enabled this old behaviour.

This PR does away with this broken "sandbox" mechanism.

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4994#" title="Author self-approved">csweichel</a>*

Associated issue: *#4993*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4994#issuecomment-888445134" title="LGTM">aledbf</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4994#" title="Author self-approved">csweichel</a>*

Associated issue: *#4993*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)~~ [aledbf,csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 55c2db6b078e74437d8a02bf15f1bc1ce4af4879</details>

**Comment by aledbf** [comment]
delete-all-the-things

**Pull request merged**
