### PR TITLE
Improve handling of missing files for BB and BBS

### PR DESCRIPTION
**Pull request by filiptronicek**
## Description

Merging blocked by #20264, that's why this is a draft

For GitLab, GitHub and Azure DevOps we have a unified error message for a missing file. This PR brings that to Bitbucket and Bitbucket Server.

Fixes ENT-851

## How to test

Try opening these two links:
- https://ft-bitbuck372abf7f33.preview.gitpod-dev.com/new#https://bitbucket.org/gitpod/spring-petclinic-new/commits/7476edc1befba51c404fb3bde195b33d3c3ee6d3 should result in an error message
- https://ft-bitbuck372abf7f33.preview.gitpod-dev.com/new#https://bitbucket.org/gitpod/spring-petclinic-new/commits/d799217742fb93ca27404071c5025485df9965ae should not :)

image

### CODE REVIEW

**Comment by filiptronicek** [comment]
Bitbucket Server seems to be working as expected as well
image

**Comment by filiptronicek** [comment]
Test results:

```
gitpod /workspace/gitpod/components/server (ft/bitbucket-files-not-found) $ yarn build && yarn mocha './**/bitbucket*-file-provider.spec.js' --exclude './node_modules/**' --exit 
yarn run v1.22.22
$ yarn generate && npx tsc
$ leeway run components/spicedb:generate-ts > src/authorization/definitions.ts && npx prettier --write src/authorization/definitions.ts
src/authorization/definitions.ts 174ms
Done in 7.96s.
yarn run v1.22.22
$ /workspace/gitpod/node_modules/.bin/mocha './**/bitbucket*-file-provider.spec.js' --exclude './node_modules/**' --exit


  TestBitbucketServerFileProvider
BBS GET https://bitbucket.gitpod-dev.com/rest/api/1.0/users/filip/repos/spring-petclinic/raw/.gitpod.yml?at=main - OK
    ✔ test_getGitpodFileContent_ok (90ms)
BBS: GET https://bitbucket.gitpod-dev.com/rest/api/1.0/users/filip/repos/spring-petclinic/commits?limit=1&path=.gitpod.yml&until=ft/invalid-docker - OK
    ✔ test_getLastChangeRevision_ok (78ms)
BBS: GET https://bitbucket.gitpod-dev.com/rest/api/1.0/users/filip/repos/spring-petclinic/commits?limit=1&path=gitpod.Dockerfile&until=ft/invalid-docker - OK
    ✔ test_getLastChangeRevision_not_found (68ms)

  TestBitbucketFileProvider
    ✔ testGetFileContents (273ms)
    ✔ testGetLastChangeRevision_ok (301ms)
    ✔ testGetLastChangeRevision_not_found (270ms)


  6 passing (1s)

Done in 1.88s.
```

**Comment by filiptronicek** [comment]
Spinning up a workspace to resolve the conflicts and clean up and also re-trigger the preview env

**Review by geropl — APPROVED** [review]
Changes LGTM tested and works :heavy_check_mark: :tada:

**Pull request merged**
