### PR TITLE
Run shellcheck against scripts

### PR DESCRIPTION
**Pull request by aledbf**
Fix errors reported by [shellcheck](http://shellcheck.net/) and also fix generation of swagger files in `supervisor-api`

### CODE REVIEW

**Comment by csweichel** [comment]
How did you run shellcheck - and how can we keep running this to prevent those problems from popping up again?

**Comment by aledbf** [comment]
> How did you run shellcheck - 

`for script in $(find . -name *.sh);do shellcheck $script;done`

and how can we keep running this to prevent those problems from popping up again?

with https://github.com/gitpod-io/gitpod/pull/4189 integrating `pre-commit` in the werft job
(or running `pre-commit run -a` before git push)

```console
pre-commit run -a
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Mixed line ending........................................................Passed
Forbid binaries..........................................................Passed
Non-executable shell script filename ends in .sh.........................Passed
Test shell scripts with shellcheck.......................................Failed
- hook id: shellcheck
- exit code: 1

In components/ide/theia/package-libs.sh line 26:
INTERPRETER_ORIG=$(patchelf --print-interpreter $BINARY 2>/dev/null)
                                                ^-----^ SC2086: Double quote to prevent globbing and word splitting.
```

**Review by csweichel — APPROVED** [review]
We're not really using swagger anyways - please remote it :)

Otherwise LGTM.

**Comment by ghuntley** [comment]
**convo fork:** shell-check was the recipient of $1690 USD of funding from http://devxconf.org/opensource as part of https://www.gitpod.io/blog/gitpod-open-source-sustainability-fund/



Now that we are using shell-check in our product I've set up an ongoing sponsorship of @koalaman on top of that one-time donation.

**Pull request merged**
