### PR TITLE
Installer config refactoring

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Related Issue(s)

Fixes #

## Release Notes

```release-note
```

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@MrSimonEmms: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by aledbf** [comment]
@MrSimonEmms can we have an option to set `fsShiftMethod = "shiftfs"` without `shiftfs.Container`?

Why? The stock Ubuntu image already has support for `shiftfs`, and loading a custom module is not required.

**Comment by MrSimonEmms** [comment]
@aledbf in theory, yes we could. This is just reworking what we have in the [existing job](https://github.com/gitpod-io/gitpod/blob/main/install/kots/manifests/gitpod-shiftfs-module-loader.yaml).

If someone installed it on a version of Ubuntu without it, what would happen? In my test instances, I run both AKS and k3s and neither of those return `true` as per the test

**Comment by MrSimonEmms** [comment]
@aledbf my GCP VM for "generic Ubuntu 20.04" doesn't contain the ShiftFS module. I think for self-hosted users, we have to have a test to cater for those who don't have it.

For the record, this is refactoring the KOTS `installer-job` not the ArgoCD job that we use for SaaS.

**Comment by MrSimonEmms** [comment]
> @MrSimonEmms let me open a PR to improve the entrpoint.sh script in shiftfs-module-loader

Excellent, thank you. This PR is still a bit of a playground at the moment.

**Comment by aledbf** [comment]
> For the record, this is refactoring the KOTS installer-job not the ArgoCD job that we use for SaaS.

We just run the installer script, there is no ArgoCD in workspace clusters ;)

**Comment by aledbf** [comment]
https://github.com/gitpod-io/gitpod/pull/12352

**Comment by aledbf** [comment]
> For the record, this is refactoring the KOTS installer-job

@MrSimonEmms can we add an option to the installer to not render the initContainer?

**Comment by MrSimonEmms** [comment]
@aledbf yes, absolutely.

**Pull request closed without merging**
