### PR TITLE
Reuse the same workspace patterns

### PR DESCRIPTION
**Pull request by mustard-mh**
## Description

Have a shared regex pattern in `common-go`, and reuse in `ws-proxy`

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/pull/16144#discussion_r1095480371

## How to test

Make sure workspace can be started

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`
- [ ] /werft publish-to-npm

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by akosyakov** [comment]
@mustard-mh it looks good to me, but you need to get an approve from the workspace and webapp teams cc @kylos101 @geropl

**Review by akosyakov — APPROVED** [review]
code changes looks good time

/hold

**Review by WVerlaek — APPROVED** [review]
lgtm

**Comment by kylos101** [comment]
:wave: this is shipping in gen86 "now"

**Pull request merged**
