### PR TITLE
Two rows of 4 option on onboarding IDE selector

### LINKED ISSUE #13497: Update onboarding IDE selector
Nice catch, @andreafalzetti! Agree, let's go with a boring (simple) MVC fix like the two rows of four for now. 🤝 

```diff
diff --git a/components/dashboard/src/settings/SelectIDEModal.tsx b/components/dashboard/src/settings/SelectIDEModal.tsx
index e24318a74..dde3e3504 100644
--- a/components/dashboard/src/settings/SelectIDEModal.tsx
+++ b/components/dashboard/src/settings/SelectIDEModal.tsx
@@ -44,7 +44,7 @@ export default function (props: SelectIDEModalProps) {
             visible={visible}
             onClose={handleContinue}
             closeable={true}
-            className="_max-w-xl"
+            className="max-w-2xl"
             buttons={<button onClick={handleContinue}>Continue</button>}
         >
             <p className="text-gray-500 dark:text-gray-400 text-base pb-3">
```

| BEFORE | AFTER |
|-|-|
| Screenshot 2022-09-30 at 5 05 18 PM (2) | Screenshot 2022-09-30 at 5 05 31 PM (2) |

_Originally posted by @gtsiolis in https://github.com/gitpod-io/gitpod/issues/13488#issuecomment-1263623639_

### PR DESCRIPTION
**Pull request by measutosh**
## Description

This PR solves the issue #13497 as suggested over there : 2 rows, 4 column style on-boarding IDE selector window

## Related Issue(s)

Fixes #13497

## Release Notes

```release-note
   NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@measutosh: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by gtsiolis — APPROVED** [review]
Thanks for contributing, @measutosh! 🍊 

You'll also need to sign a Contributor License Agreement (CLA)[[1](https://en.wikipedia.org/wiki/Contributor_License_Agreement)] once before merging your first contribution. Looping in @meysholdt to reach out about the CLA. 🏓

UX changes look good! ✔️ 

Someone from the `@gitpod-io/engineering-webapp` will pick this up for a code review. 🏀

**Review by svenefftinge — APPROVED** [review]

**Comment by laushinka** [comment]
Very quick, @svenefftinge! Was the CLA signed yet?

**Comment by measutosh** [comment]
> Thanks for contributing, @measutosh! tangerine
> 
> You'll also need to sign a Contributor License Agreement (CLA)[[1](https://en.wikipedia.org/wiki/Contributor_License_Agreement)] once before merging your first contribution. Looping in @meysholdt to reach out about the CLA. ping_pong
> 
> UX changes look good! heavy_check_mark
> 
> Someone from the `@gitpod-io/engineering-webapp` will pick this up for a code review. basketball

thanks @gtsiolis for the MR

**Comment by laushinka** [comment]
Hi @measutosh, thanks for your contribution! However, to continue having your contribution in our code, please sign this [CLA form](https://powerforms.docusign.net/30e1aa46-cce5-4bc6-a933-ad02cd8d5ada?env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&accountId=86335c2c-01b9-4edc-a187-014f5150a112).

**Comment by measutosh** [comment]
> Hi @measutosh, thanks for your contribution! We were a bit too quick, so please sign this [CLA form](https://powerforms.docusign.net/30e1aa46-cce5-4bc6-a933-ad02cd8d5ada?env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&accountId=86335c2c-01b9-4edc-a187-014f5150a112) as soon as you can :)

image

**Comment by gtsiolis** [comment]
@measutosh Are you still seeing this error when opening the CLA form [linked above](https://github.com/gitpod-io/gitpod/pull/13557#issuecomment-1271748796)? The form renders fine here.

**Pull request merged**
