### PR TITLE
[supervisor] Add missing stream api metrics

### PR DESCRIPTION
**Pull request by jeanp413**
## Description

Add missing stream api metrics

## How to test

1. Scale down server to force connection error
2. Check grafana dashboard that error counter increases

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [x] /werft no-test
      Run Leeway with `--dont-test`
- [ ] /werft publish-to-npm

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by jeanp413** [comment]
Error counter increases really fast because we retry to connect every two seconds

image

**Comment by akosyakov** [comment]
@mustard-mh @jeanp413 lets revert auto switch and only do alert reliable

**Review by akosyakov — APPROVED** [review]
analytics is good

/hold

but please remove smart switches, we should be in control

**Pull request merged**
