### PR TITLE
Add CreateAndStartWorkspace to public-api

### PR DESCRIPTION
**Pull request by selfcontained**
## Description

Setting up a CreateAndStartWorkspace endpoint in the public-api that proxies to server's createWorkspace. We had some of the request/response types already defined in proto files, so I left what was there and added on properties for org, workspace class and ide settings. I included region as well since it seems likely we'd want to expose that option too.

Example of calling from a TS client:

```ts
workspaceService.createAndStartWorkspace({
    source: {
        case: "contextUrl",
        value: "https://github.com/gitpod-io/gitpod.git",
    },
    organizationId: "...",
    startSpec: {
        workspaceClass: "g1-standard",
        ideSettings: {
            defaultIde: "code-desktop",
            useLatestVersion: false,
        },
    },
});
```

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖 Generated by Copilot at e62607b</samp>

This pull request adds a new experimental API for creating and starting workspaces with organization and workspace class parameters. It modifies the `workspaces.proto` file and the corresponding TypeScript code, and implements the `CreateAndStartWorkspace` RPC in the `public-api-server` component. This change is part of a larger feature to support organizations and workspace classes in Gitpod.

</details>

### Questions
❓ The protobuf definition for `source` felt a bit confusing to me with how you can provide a `contextUrl` or `prebuildId`. I  wasn't sure if we could simplify, or if we need to keep it this way (it was like this already).

## Related Issue(s)

EXP-440

## How to test

This call is wired into the desktop app in [this branch/pr](https://github.com/gitpod-io/gitpod-desktop-app/pull/43). You can run that version of the desktop app locally and try the steps listed in the PR to create a new workspace from a project entry.

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - brad-publi8eafe73434</li>
	<li><b>🔗 URL</b> - <a href="https://brad-publi8eafe73434.preview.gitpod-dev.com/workspaces" target="_blank">brad-publi8eafe73434.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - brad-public-api-create-workspace-gha.15332</li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [x] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [x] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by mbrevoort** [comment]
I suppose "case" is an existing property name. What does it mean and why is it called that?

**Review by akosyakov — APPROVED** [review]
approving to unblock

**Comment by filiptronicek** [comment]
@mbrevoort `case` is essentially a protobuf-compatible way of saying: this is the data type I'm passing and you deal with it.

We have talked about that in the future, we may want to allow different sources of workspace starts like a context. A context, as opposed to a context URL would be an object representing all of the provider-agnostic metadata needed to start a workspace, akin to this:
```json
{
	"repo": "gitpod"
	"owner": "gitpod-io"
	"ref": "main"
}

**Review by svenefftinge — APPROVED** [review]
lgtm

**Review by filiptronicek — APPROVED** [review]
Looks good. Let's ship this

**Pull request merged**
