### PR TITLE
Update OpenSSH to v9.3p2

### PR DESCRIPTION
**Pull request by aledbf**
## Description

[Update to the latest version to get the CVE fixes](https://www.openssh.com/txt/release-9.3p2)

<details>
<summary>Changes summary and walkthrough generated by Copilot</summary>

</details>

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - aledbf-ssgh</li>
	<li><b>🔗 URL</b> - <a href="https://aledbf-ssgh.preview.gitpod-dev.com/workspaces" target="_blank">aledbf-ssgh.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - aledbf-ssgh-gha.14304</li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by akosyakov** [comment]
I triggered the preview envs, just do smoke tests.

**Comment by akosyakov** [comment]
/gh run recreate-vm=true

super sorry, I will monitor today and unblock

**Comment by akosyakov** [comment]
@aledbf I don't know what is wrong but I cannot get preview envs at all :(

**Comment by aledbf** [comment]
> @aledbf I don't know what is wrong but I cannot get preview envs at all :(

Please try now

**Review by akosyakov — APPROVED** [review]
looks good

**Pull request merged**
