### PR TITLE
[gha] comment ops + recreate_vm

### PR DESCRIPTION
**Pull request by vulkoingim**
## Description

This PR adds a werft-style comment ops to the GHA workflows.

`comment-ops.yaml` is triggered on every comment on a PR and evaluates whether an action should be taken (i.e. if it contains `/gh run ...`. The only supported command option is `recreate_vm`, which will trigger the build workflow, with that additional input. 

The triggered workflow via `workflow_dispatch`, doesn't publish a status check in the commits (has to be done manually), but a comment will be added (see [here for an example](https://github.com/vulkoingim/actions-test/pull/5)).

Also changes the event triggers  to `push, pr_opened, pr_edited`

## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Build Options:

- [x] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-slow-database
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by roboquat** [comment]
@vulkoingim: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by vulkoingim** [comment]
run workflow

**Comment by vulkoingim** [comment]
run workflow

**Comment by vulkoingim** [comment]
test

**Review by vulkoingim — COMMENTED** [review]
comment

**Comment by vulkoingim** [comment]
teststs

**Review by vulkoingim — COMMENTED** [review]
teststs

**Comment by vulkoingim** [comment]
testests

**Review by mads-hartmann — APPROVED** [review]
Neat, didn't review too closely as this is something we can really easily iterate on ☺️

**Pull request merged**
