### PR TITLE
[server] Remove misleading log in AdditionalContentPrefixContextParser

### LINKED ISSUE #4733: [server] Misleading log in `additional-content-prefix-parser.ts`
This error log is misleading. It is logged when the prefix is **NOT** found in the context URL:

https://github.com/gitpod-io/gitpod/blob/66539b0f4b1cc0be717d7bb10f18da225b844e90/components/server/src/workspace/additional-content-prefix-context-parser.ts#L30-L30

### PR DESCRIPTION
**Pull request by corneliusludmann**
Fixes #4733

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4866#" title="Author self-approved">corneliusludmann</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by AlexTugarev — APPROVED** [review]
LGTM!

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 68aa909448a8e9b9a6102b0b903ef431f00e4ef9</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4866#pullrequestreview-709464794" title="Approved">AlexTugarev</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4866#" title="Author self-approved">corneliusludmann</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [AlexTugarev,corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
