### PR TITLE
[dashboard] fix skip confirm modal #6383

### LINKED ISSUE #6383: Do not submit form on enter when there's no focus when deleting user or team
### Bug description

Users can delete their account by going to [`/account`](https://gitpod.io/account), clicking _Delete Account_, and then clicking enter without even focusing on the modal or on any input or button within the modal. ⚠️ 

This is also bypassing the disabled state of the primary action button within the confirmation modal that requires the user to type their email to confirm. ❗ 

This affects :a: user and :b: team deletion.

See also https://github.com/gitpod-io/gitpod/issues/6371.

Cc @laushinka because https://github.com/gitpod-io/gitpod/pull/6058 in case this is related.

### Steps to reproduce

For user deletion bug:

1. Create a team
2. Go to team settings
3. Click Delete Team
4. Press enter without focusing on the modal or typing the team name

For user deletion bug:

1. Go to account settings
2. Click Delete Account
3. Press enter without focusing on the modal or typing the team name

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by iQQBot**
## Related Issue(s)

Fixes #6383 

## How to test

1. Create a team
2. Go to team settings
3. Click Delete Team
5. Press enter without focusing on the modal , it not submit

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by laushinka** [comment]
Thanks for working on this, @iQQBot! 

/werft run

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: b43428dfde74ad507cbe46f067e86a2d0a2bd51a</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6413#issuecomment-956322754" title="LGTM">laushinka</a>*

Associated issue: *#6383*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [laushinka]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
