### PR TITLE
[payment] added more resilience to GitHub payment endpoint

### LINKED ISSUE #6531: [payment-endpoint] GitHub integration: reconcilePlan is broken
https://console.cloud.google.com/errors/CK203s2T2-64mwE?time=P7D&project=gitpod-staging

### PR DESCRIPTION
**Pull request by JanKoehnlein**
## Description
Log errors when reconciling plans with GitHub

## Related Issue(s)
Fixes #6531

## How to test
I fear this cannot be tested.

## Release Notes
```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jankoehnlein** after the PR has been reviewed.

Associated issue: *#6531*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ee/payment-endpoint/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/payment-endpoint/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by JanKoehnlein** [comment]
I think this is the least we can and should currently do on this issue

**Comment by AlexTugarev** [comment]
/lgtm

makes sense 👍🏻

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: a204a9e244c10d267efb310bd124d0f2dc06525b</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6813#issuecomment-975331142" title="LGTM">AlexTugarev</a>*

Associated issue: *#6531*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ee/payment-endpoint/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/payment-endpoint/OWNERS)~~ [AlexTugarev]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
