### PR TITLE
[dashboard] fix missing billing entry

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description
Ensures the settings menu gets rerendered when the dependent state changes.

## Related Issue(s)

Fixes #

## How to test

ensure the billing menu is shown in user settings

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]

**Comment by svenefftinge** [comment]
@gtsiolis you can find the link in the "Build / Install Gitpod (pull_request)" build. Look into "Install Gitpod/Deploy Gitpod to preview environment". There on the bottom.

**Comment by gtsiolis** [comment]
@svenefftinge Ah yes, I now remember seeing the update[[1](https://gitpod.slack.com/archives/C02EN94AEPL/p1678286894698039)] (internal) regarding GH Actions! Thanks for the heads-up! 🍊

**Review by gtsiolis — APPROVED** [review]
UX LGTM! 🌮🌮
 
Billing menu now renders again.

**Comment by gtsiolis** [comment]
Taking a bias for action and removing hold here, since code changes have also been approved.

We can always revert if needed. 🚀 

/unhold

**Pull request merged**
