### PR TITLE
make vm support ssh gateway

### PR DESCRIPTION
**Pull request by iQQBot**
## Description

This PR make harvester VM preview environment support  SSH Gateway

How to archive this?
1. we setup [RouterOS](https://mikrotik.com/software) both in GCP and harvester side
2. setup wireguard between GCP and harvester routeros
3. setup VPC route for `harvester cluster service IP range` to RouterOS GCP side
4. setup route in RouterOS to route this range IP to harvester side RouterOS
5. for every preview environment in harvester, create a `pod` for forwarding traffic and create a `loadbalancer` type `service` for get `public IP address`

This PR only do step 5, Everything else is already done in core-dev and harvester
see internal notion page 

[How to setup routeros in GCP side](https://www.notion.so/gitpod/How-to-setup-routeros-in-GCP-side-949aa866383646758acba76dbd2c2d54)
[How to setup routeros in harvester side](https://www.notion.so/gitpod/How-to-setup-routeros-in-harvester-side-465defa5e6fd4c039c9aef303178bca4)

TODO: 
- [ ] clean loadbalancer after VM delete

## Related Issue(s)

Fixes #

## How to test

run werft job in this PR
start a workspace, check ssh gateway is work

## Release Notes

```release-note
NONE
```

## Documentation

- [x] /werft with-vm=true

### CODE REVIEW

**Review by akosyakov — APPROVED** [review]
I verified that IntelliJ works without any changes from my side.

/hold
But I did not review code changes. I think it is better if @gitpod-io/platform team review them.

**Comment by wulfthimm** [comment]
For the record: This will not work on Harvester VMs as Harvester cannot provide public IPs.

**Comment by akosyakov** [comment]
@iQQBot Could you update the description to elaborate on the approach please? 🙏

**Comment by wulfthimm** [comment]
I think I got it. You create a normal preview-environment on a Harvester VM and a klipper loadbalancer on `core-dev`. When a workspace is requested the DNS will guide you to the klipper endpoint which proxies it to the Harvester preview.

**Review by wulfthimm — APPROVED** [review]

**Comment by akosyakov** [comment]
@iQQBot please unhold when you think it is appropriate

**Pull request merged**
