### PR TITLE
[dashboard] chore: Update copy texts for empty `/workspaces` page

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

This PR updates the copy texts for the empty `/workspaces` page. The changes include updating the text in the heading and subheading, as well as updating the text in the buttons. The goal is to provide clearer and more concise instructions to users on how to create their first workspace or try a demo repository.

| Before | After |
|--------|--------|
| image | image | 

## Related Issue(s)

Fixes OPM-663

## How to test

- Open preview environment
- Complete onboarding
- And, see `/workspaces` :eyes:

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Review by geropl — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by loujaybee** [comment]
Looks good. If we're able to add a bit more margin between the content and the header that would help create some separation from the headers and draw your attention to the middle of the screen, with the videos and CTAs. 

|Before|After|
|-|-|
|image|image|

But more of a nice-to-have. I wouldn't block the PR on it.

**Comment by Siddhant-K-code** [comment]
@loujaybee I've added that in [`ce0c2b4`](https://github.com/gitpod-io/gitpod/pull/19998/commits/ce0c2b45357151934e1bf9460ffdca967e498ae2)


**Updated preview:**

image

**Pull request merged**
