### PR TITLE
[installer]: remove the custom labels from the selector labels

### LINKED ISSUE #11952: Change the Installer customisation to not update the selector labels
We recently added the ability to add custom labels, annotations and envvars to pods. For simplicity, this was added to the selector labels as well. As these are immutable, this was a mistake in retrospect.

The `selectorLabels` should be amended so that they only have the default labels adding, not the custom labels

This is blocking #9926 as this requires custom labels adding to the pods so that they are picked up for backup.

**IMPORTANT** This will introduce a potentially breaking change to the next release of Gitpod which we will need to document @lucasvaltl. The fix is as per the [website](https://www.gitpod.io/docs/self-hosted/latest/advanced/customization#limitations). However, by doing this change, it removes this limitation for future releases.

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Description

Remove a [limitation](https://www.gitpod.io/docs/self-hosted/latest/advanced/customization#limitations) on the custom labels by removing the customisation on the selector labels. These are "reverted" to just using the default labels function instead so they're consistent.

## Related Issue(s)

Fixes #11952

## How to test

Deploy via KOTS.
1. Use a default configuration
2. Upload a configuration as per the [docs](https://www.gitpod.io/docs/self-hosted/latest/advanced/customization):
```yaml
customization:
  - apiVersion: "*"
    kind: "*"
    metadata:
      name: "*"
      labels:
        hello: world
      annotations:
        hello: world
```
3. Redeploy with the default configuration

All of these should install fine.

## Release Notes

```release-note
[installer]: remove the custom labels from the selector labels
```

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@MrSimonEmms: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by MrSimonEmms** [comment]
This is blocked by Go formatting issues, which is being fixed in #11958

**Review by cooperbenson-qz — APPROVED** [review]
Awesome, thanks for making this change!

**Review by andrew-farries — APPROVED** [review]

**Review by aledbf — APPROVED** [review]

**Review by felladrin — APPROVED** [review]

**Review by corneliusludmann — APPROVED** [review]
Change looks good to me.

Would be a good opportunity to add a test (basically a *.golden file with the result of the config you added in the PR description). What do you think?

/hold in case you want to add this

**Comment by MrSimonEmms** [comment]
@corneliusludmann a very good idea, I'll do that

**Pull request merged**
