### PR TITLE
[Admin] Show BillingMode on Team-/UserDetails pages

### PR DESCRIPTION
**Pull request by geropl**
## Related Issue(s)

Fixes #

## How to test
- [signup](https://gpl-12674-bm.preview.gitpod-dev.com/workspaces)
- ping me for admin rights (or get them through DB)
- Search for you [user details page](https://gpl-12674-bm.preview.gitpod-dev.com/admin/users) and see that:
  - BillingMode is displayed and shows "Chargebee"
  - Chargebee stuff is displayed as well (credits, etc.)
 
image

- create a team starting with `Gitpod-xxx`
- Go back to User Details and see that:
  - BillingMode is displayed and shows "usage-based"
  - Chargebee related info and actions is gone
image

- go to your teams details page and see that:
  - BillingMode is displayed and shows "usage-based"

image

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview
- [x] /werft with-payment

### CODE REVIEW

**Comment by AlexTugarev** [comment]
@geropl, please make me admin for this preview env 🙏🏻

**Comment by geropl** [comment]
@AlexTugarev done

**Review by AlexTugarev — APPROVED** [review]
PR works as advertised! Nice!

Screen Shot 2022-09-09 at 09 50 13

One thing I just noticed. Once you switched to UB on the team level, your billing mode switches accordingly, but when you cancel on stripe, the billing mode remains `usage-based`. Is that OK?

**Comment by AlexTugarev** [comment]
@geropl, any Idea about https://github.com/gitpod-io/gitpod/pull/12770#pullrequestreview-1101862012? Is this behavior expected?

**Comment by geropl** [comment]
>  Is this behavior expected?

@AlexTugarev Yes: [code](https://github.com/gitpod-io/gitpod/blob/2d2c70f62c4799fe1bf0dca0aa55d4c70bb09386/components/server/ee/src/billing/billing-mode.ts#L98-L160), [tests](https://github.com/gitpod-io/gitpod/blob/a988c44f04ff8f99e5378ea62ad8bea29d169e8d/components/server/ee/src/billing/billing-mode.spec.db.ts#L156-L480)

**Pull request merged**
