### PR TITLE
[test] experimental inner loop with isolation network and process tree

### PR DESCRIPTION
**Pull request by iQQBot**
## Description

this PR is an experimental inner loop with an isolation network and process tree and special root filesystem, this PR focus on custom docker image

## Related Issue(s)

Fixes #

## How to test

1. start a workspace in this preview environment
2. create a Dockerfile in this workspace
3. use following command to export docker filesystem to `/.debug/rootfs` folder
```bash
sudo rm -rf /.debug/rootfs \
  && sudo mkdir -p /.debug/rootfs \
  && sudo chown -R gitpod:gitpod /.debug/rootfs \
  && DOCKER_BUILDKIT=1 docker build -t inner-loop . \
  && docker rm -f inner-loop-0 &>/dev/null \
  && docker run --name inner-loop-0 inner-loop \
  && echo "exporting filesystem, may take sometimes..." \
  && docker export inner-loop-0 | sudo tar xf - -C /.debug/rootfs
```
4. use `/.supervisor/supervisor inner-loop` to build a new process tree with new root filesystem
6. once you saw `Web UI available at http://localhost:23000` it means IDE is ready, you add prefix `debug-` in your workspace URL, to access debug wokspace.
7. exec `curl lams.sh | sh` in debug workspace, you will see a notification, click open in browser, you can view this port in debug workspace. (url prefix `{port}-debug-{workspaceId}` )
8. you can press `Control + C` to stop debug workspace.

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by roboquat** [comment]
@iQQBot: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by akosyakov** [comment]
I'm going to close it, since we decided to go with `docker run` approach. I've extracted proxy bits in  https://github.com/gitpod-io/gitpod/pull/15910 and https://github.com/gitpod-io/gitpod/pull/15795. I will add @iQQBot as a co-author 🙏 Thank you a lot!

**Pull request closed without merging**
