### PR TITLE
[ws-manager] enable the volume snapshot controller when the VolumeSnapshot CRD exists

### PR DESCRIPTION
**Pull request by jenting**
## Description

For self-hosted, the VolumeSnapshot is optional for now, we should enable the volume_snapshot_controller only when the VolumeSnapshot CRD exists.

## Related Issue(s)

Fixes #
https://gitpod.slack.com/archives/C01KLC56NP7/p1656394622810719?thread_ts=1656366685.819199&cid=C01KLC56NP7

## How to test

1. Scale down the volume snapshot controller.
    ```console
    kubectl scale --replicas=0 deploy/snapshot-controller -n kube-system
    ```
1. Delete the VolumeSnapshot/VolumeSnapshotContent/VolumeSnapshotClass CRDs.
    ```console
    kubectl delete vsclass --all
    kubectl delete crds volumesnapshotclasses.snapshot.storage.k8s.io
    kubectl delete crds volumesnapshots.snapshot.storage.k8s.io
    kubectl delete crds volumesnapshotcontents.snapshot.storage.k8s.io
    ```
1. Restart the ws-manager, and make sure the ws-manager is able to start.
    ```console
    kubectl rollout restart deploy/ws-manager
    kubectl rollout status deploy/ws-manager
    kubectl get pod -l component=ws-manager
    ```

## Release Notes

```release-note
[experimental] enable the volume snapshot controller when the VolumeSnapshot CRD exists
```

## Documentation

N/A

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Review by MrSimonEmms — APPROVED** [review]
Confirm that this works in the June release on a self-hosted cluster

**Review by Furisto — APPROVED** [review]

**Pull request merged**
