### PR TITLE
Add support for Fedora, CentOS, RHEL

### LINKED ISSUE #6449: Add support for Fedora and EL (RHEL, CentOS) based workspace images
Adding support for Fedora and EL, like CentOS/RHEL should be easy, as the detection already handles Amazon Linux. Changes would need to be made to https://github.com/gitpod-io/gitpod/tree/1cf441ab78ef5d9d23eb5ef31ffaaf5f330da1e5/components/image-builder/workspace-image-layer to detect the distro type and pick the correct appended dockerfile.

https://github.com/gitpod-io/gitpod/blob/1cf441ab78ef5d9d23eb5ef31ffaaf5f330da1e5/components/image-builder/workspace-image-layer/scripts/detect-distro.sh#L26-L44

and adding a distro folder to https://github.com/gitpod-io/gitpod/tree/1cf441ab78ef5d9d23eb5ef31ffaaf5f330da1e5/components/image-builder/workspace-image-layer/gitpod-layer

I am willing to add a PR, but was wondering how to test this properly. This is a duplicate/re-request of #2456

### PR DESCRIPTION
**Pull request by gbraad**
## Description
Renamed the Amazon Linux folder to allow the re-use for Fedora and the
Enterprise Linux derivatives.

## Related Issue(s)
Fixes #6449

## How to test
Test with a CentOS, Amazon, or Fedora derived workspace definition:
  * https://gitpod.io/#https://github.com/gbraad/gitpod-template-fedora

^^^ Haven't been able to do this just ye. However since Amazon is a derivative of RHEL, this should 
just work. The same for Fedora, as the Dockerfile and script do not refer to a lot of specifics. Though,
would like to be able to test this. Any suggestions?

### CODE REVIEW

**Comment by roboquat** [comment]
@gbraad: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **aledbf** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @aledbf` in a comment when ready.

Associated issue: *#6449*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/image-builder/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by gbraad** [comment]
@csweichel any guidance on this?

**Comment by gbraad** [comment]
> image builder mk3

No idea about this. Any way to track this or see when this would be available?

**Comment by csweichel** [comment]
Hey, sorry for coming in so late.

We're about to replace the image-builder component with a newer version (which we refer to as image-builder mk3). Unlike its predecessor, mk3 no longer adds a Gitpod layer, hence makes adaption to the individual distributions unnecessary. 

However, getting mk3 to run in production satisfactorily has proven tedious, and I cannot give a good timeline for this. We'll make another push next week, but there's no guarantee that we'll get it out then :/

**Comment by gbraad** [comment]
In that case closing this PR

**Pull request closed without merging**
