### PR TITLE
[preview] Disable fail-fast and limit parallel jobs to 1

### PR DESCRIPTION
**Pull request by WVerlaek**
## Description

When one of the delete jobs fails they cancel the other ongoing deletion jobs in the matrix, setting `fail-fast` to false prevents that. Also limiting the concurrency to 1, as some are failing to acquire the TF lock (presumably cause multiple jobs in the matrix are trying that at the same time)

## Related Issue(s)

Related: https://github.com/gitpod-io/gitpod/pull/18025#issuecomment-1602765618

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`
</details>

/hold

### CODE REVIEW

**Review by kylos101 — APPROVED** [review]
Nice find, @WVerlaek ! 

@mads-hartmann @vulkoingim for :eyes: , this is based on [this](https://github.com/gitpod-io/gitpod/pull/18025#issuecomment-1602765618) conversation.

**Review by vulkoingim — APPROVED** [review]
The locks are not shared, they are per-env. 

I think they linger, because when the runner gets killed it sends SIGKILL to the process which doesn't let tf release the lock :(

**Comment by WVerlaek** [comment]
@vulkoingim ah I see yeah, in that case I'll put back the parallelism

**Pull request merged**
