### PR TITLE
[registry-facade] Refactoring

### PR DESCRIPTION
**Pull request by aledbf**
## Related Issue(s)

Fixes #

## Release Notes

```release-note
[registry-facade] Revert removal of DisableKeepAlives
[registry-facade] Check redis connection on start
[registry-facade] Separate Redis manifest cache from IPFS
[registry-facade] Check if the keys exist and use MULTI
[registry-facade] Use sync.Pool as buffer

Include error in probe log
```

### CODE REVIEW

**Comment by roboquat** [comment]
@aledbf: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by corneliusludmann — APPROVED** [review]
Looked at the installer changes only. That looks good so far. :balloon:

**Review by csweichel — APPROVED** [review]

**Pull request merged**
