### PR TITLE
Remove disabled checkbox for account notifications

### PR DESCRIPTION
**Pull request by gtsiolis**
## Description

Reviving https://github.com/gitpod-io/gitpod/pull/14746.

Cross-posting relevant comment in https://github.com/gitpod-io/gitpod/pull/14746#issuecomment-1344492785.

See also [relevant RFC](https://www.notion.so/gitpod/0d887671f3c544babdc3248741c0c607) (internal). Cc @chrifro @taliamoyal 

<details>
<summary>Changes summary and walkthrough generated by Copilot</summary>

</details>

## How to test

Go to `/notifications` and notice there's no longer a disabled checkbox for the account notifications.

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - gt-remove-e8c87586ba</li>
	<li><b>🔗 URL</b> - <a href="https://gt-remove-e8c87586ba.preview.gitpod-dev.com/workspaces" target="_blank">gt-remove-e8c87586ba.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - gt-remove-account-notifications-gha.13984</li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [X] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by gtsiolis** [comment]
@mustard-mh Usually it takes a while to reflect the changes, not sure why. Maybe because of this, it takes a while to make the checkbox feel reactive? Could you try to check or uncheck something and wait a bit?

**Comment by mustard-mh** [comment]
> @mustard-mh I could check or uncheck all other checkboxes there. Usually it takes a while to reflect the changes, not sure why. Maybe because of this, it takes a while to make the checkbox feel reactive? Could you try to check or uncheck something and wait a bit?

@gtsiolis I see, it's because my `additionData` don't have `emailNotificationSettings`, so [it will not work](https://github.com/gitpod-io/gitpod/blob/ad1287722f5ccc699931a242fd26b8a3a252a356/components/dashboard/src/user-settings/Notifications.tsx#L64) for me.

Maybe there're lots of users affected, going to create an issue

**Review by mustard-mh — APPROVED** [review]
Code LGTM

**Comment by gtsiolis** [comment]
Thanks @mustard-mh for taking a look, and taking a bias for action by opening EXP-288. 🏓 

/unhold

**Pull request merged**
