### PR TITLE
Created a Global Prettier File

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
## Description
I have created a global .prettierrc.js file for Typescript and Js Files in order to remove inconsistent linting configurations which spanned across files.

### CODE REVIEW

**Comment by roboquat** [comment]
@Harry-Hopkinson: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by Harry-Hopkinson** [comment]
@mustard-mh should be ready for review 😄

**Comment by easyCZ** [comment]
There's a json version of prettier config in the [repo](https://github.com/gitpod-io/gitpod/blob/main/.prettierrc.json). Perhaps makes sense to extend that one with the options proposed here.

**Comment by Harry-Hopkinson** [comment]
Oh I did notice, thanks.

**Pull request closed without merging**
