### PR TITLE
[dashboard] Fix Dashboard lint errors for Login.tsx

### LINKED ISSUE #3841: [dashboard] Lint warnings
### Bug description
```console
Compiled with warnings.

src/App.tsx
  Line 57:8:   React Hook useEffect has a missing dependency: 'setUser'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
  Line 67:13:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images   jsx-a11y/alt-text

src/Login.tsx
  Line 26:9:    img elements must have an alt prop, either with meaningful text, or an empty string for decorative images   jsx-a11y/alt-text
  Line 71:8:    React Hook useEffect has a missing dependency: 'setUser'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
  Line 86:25:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images   jsx-a11y/alt-text
  Line 112:29:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images   jsx-a11y/alt-text
  Line 122:41:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images   jsx-a11y/alt-text

src/admin/UserSearch.tsx
  Line 41:8:  React Hook useEffect has a missing dependency: 'searchResult.rows'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

src/admin/WorkspacesSearch.tsx
  Line 51:8:  React Hook useEffect has a missing dependency: 'searchResult.rows'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
  Line 57:8:  React Hook useEffect has a missing dependency: 'search'. Either include it or remove the dependency array             react-hooks/exhaustive-deps

src/components/Menu.tsx
  Line 49:21:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text

src/components/Modal.tsx
  Line 44:8:  React Hook useEffect has a missing dependency: 'handler'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

src/settings/EnvironmentVariables.tsx
  Line 29:45:   Unexpected whitespace after spread property operator  rest-spread-spacing
  Line 137:38:  Unnecessary escape character: \*                      no-useless-escape

src/settings/Integrations.tsx
  Line 48:8:    React Hook useEffect has a missing dependency: 'updateCurrentScopes'. Either include it or remove the dependency array                                                                                                                                                                                                                                                                                                                           react-hooks/exhaustive-deps
  Line 443:8:   React Hook useEffect has missing dependencies: 'props.mode', 'props.provider.host', 'props.provider.oauth.callBackUrl', 'props.provider.oauth.clientId', 'props.provider.oauth.clientSecret', and 'props.provider.type'. Either include them or remove the dependency array. If 'setType' needs the current value of 'props.provider.type', you can also switch to useReducer instead of useState and read 'props.provider.type' in the reducer  react-hooks/exhaustive-deps
  Line 447:8:   React Hook useEffect has a missing dependency: 'validate'. Either include it or remove the dependency array                                                                                                                                                                                                                                                                                                                                      react-hooks/exhaustive-deps
  Line 545:19:  Using target="_blank" without rel="noreferrer" is a security risk: see https://html.spec.whatwg.org/multipage/links.html#link-type-noopener                                                                                                                                                                                                                                                                                                      react/jsx-no-target-blank
  Line 546:13:  Using target="_blank" without rel="noreferrer" is a security risk: see https://html.spec.whatwg.org/multipage/links.html#link-type-noopener                                                                                                                                                                                                                                                                                                      react/jsx-no-target-blank
  Line 567:21:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                                                                                                                                                                                                                                                                                                                        jsx-a11y/alt-text
  Line 594:25:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                                                                                                                                                                                                                                                                                                                        jsx-a11y/alt-text
  Line 611:21:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                                                                                                                                                                                                                                                                                                                        jsx-a11y/alt-text
  Line 617:21:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                                                                                                                                                                                                                                                                                                                        jsx-a11y/alt-text

src/settings/Notifications.tsx
  Line 21:20:  Unexpected whitespace after spread property operator  rest-spread-spacing
  Line 22:24:  Unexpected whitespace after spread property operator  rest-spread-spacing
  Line 24:28:  Unexpected whitespace after spread property operator  rest-spread-spacing

src/settings/Plans.tsx
  Line 35:1:     Unexpected default export of anonymous function                                                                                                                                                                                                                                                                                                                   import/no-anonymous-default-export
  Line 73:8:     React Hook useEffect has missing dependencies: 'handleTeamClaim', 'pollAccountStatementTimeout', and 'server'. Either include them or remove the dependency array                                                                                                                                                                                                 react-hooks/exhaustive-deps
  Line 110:39:   Unexpected mix of '&&' and '||'                                                                                                                                                                                                                                                                                                                                   no-mixed-operators
  Line 110:81:   Unexpected mix of '&&' and '||'                                                                                                                                                                                                                                                                                                                                   no-mixed-operators
  Line 207:70:   Expected '===' and instead saw '=='                                                                                                                                                                                                                                                                                                                               eqeqeq
  Line 234:18:   Unexpected whitespace after spread property operator                                                                                                                                                                                                                                                                                                              rest-spread-spacing
  Line 253:70:   Expected '===' and instead saw '=='                                                                                                                                                                                                                                                                                                                               eqeqeq
  Line 274:18:   Unexpected whitespace after spread property operator                                                                                                                                                                                                                                                                                                              rest-spread-spacing
  Line 298:81:   The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  Line 298:127:  Script URL is a form of eval                                                                                                                                                                                                                                                                                                                                      no-script-url
  Line 321:81:   The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  Line 321:127:  Script URL is a form of eval                                                                                                                                                                                                                                                                                                                                      no-script-url
  Line 347:81:   The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  Line 347:127:  Script URL is a form of eval                                                                                                                                                                                                                                                                                                                                      no-script-url
  Line 396:21:   The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  Line 396:118:  Script URL is a form of eval                                                                                                                                                                                                                                                                                                                                      no-script-url
  Line 398:33:   The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  Line 398:85:   Script URL is a form of eval                                                                                                                                                                                                                                                                                                                                      no-script-url
  Line 399:29:   The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  Line 399:81:   Script URL is a form of eval                                                                                                                                                                                                                                                                                                                                      no-script-url
  Line 405:17:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                                                                                                                                                                                                                                         jsx-a11y/alt-text
  Line 406:129:  Using target="_blank" without rel="noreferrer" is a security risk: see https://html.spec.whatwg.org/multipage/links.html#link-type-noopener                                                                                                                                                                                                                       react/jsx-no-target-blank
  Line 413:25:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                                                                                                                                                                                                                                         jsx-a11y/alt-text
  Line 417:25:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                                                                                                                                                                                                                                         jsx-a11y/alt-text
  Line 430:25:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                                                                                                                                                                                                                                         jsx-a11y/alt-text
  Line 539:62:   Expected '===' and instead saw '=='                                                                                                                                                                                                                                                                                                                               eqeqeq

src/settings/Preferences.tsx
  Line 39:25:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 44:25:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text

src/settings/Teams.tsx
  Line 108:8:    React Hook useEffect has a missing dependency: 'pollForAdditionalSlotsBought'. Either include it or remove the dependency array                     react-hooks/exhaustive-deps
  Line 154:8:    React Hook useEffect has missing dependencies: 'isChargebeeCustomer' and 'pendingPlanPurchase'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 162:8:    React Hook useEffect has a missing dependency: 'pendingSlotsPurchase'. Either include it or remove the dependency array                             react-hooks/exhaustive-deps
  Line 463:119:  Using target="_blank" without rel="noreferrer" is a security risk: see https://html.spec.whatwg.org/multipage/links.html#link-type-noopener         react/jsx-no-target-blank
  Line 576:25:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                           jsx-a11y/alt-text
  Line 605:8:    React Hook useEffect has a missing dependency: 'getPlan'. Either include it or remove the dependency array                                          react-hooks/exhaustive-deps
  Line 627:17:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                           jsx-a11y/alt-text
  Line 663:8:    React Hook useEffect has a missing dependency: 'plan.chargebeeId'. Either include it or remove the dependency array                                 react-hooks/exhaustive-deps
  Line 705:17:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                           jsx-a11y/alt-text
  Line 755:10:   'Slot' is already defined                                                                                                                           @typescript-eslint/no-redeclare
  Line 842:44:   Unexpected mix of '&&' and '||'                                                                                                                     no-mixed-operators
  Line 842:121:  Unexpected mix of '&&' and '||'                                                                                                                     no-mixed-operators
  Line 863:21:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                           jsx-a11y/alt-text

src/settings/settings-menu.ts
  Line 7:1:  Assign array to a variable before exporting as module default  import/no-anonymous-default-export

src/start/CreateWorkspace.tsx
  Line 270:6:   React Hook useEffect has a missing dependency: 'p.error.data'. Either include it or remove the dependency array                                                                                                                                                                               react-hooks/exhaustive-deps
  Line 301:21:  Assignments to the 'pollTimeout' variable from inside React Hook useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside useEffect  react-hooks/exhaustive-deps

src/start/StartPage.tsx
  Line 85:7:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text

src/start/StartWorkspace.tsx
  Line 103:9:  Do not assign to the exception parameter                                                                                                  no-ex-assign
  Line 312:7:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                 jsx-a11y/alt-text
  Line 345:6:  React Hook useEffect has missing dependencies: 'logsEmitter' and 'props.workspaceId'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 373:6:  React Hook useEffect has missing dependencies: 'logsEmitter' and 'props.workspaceId'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

src/utils.ts
  Line 30:27:  Function declared in a loop contains unsafe references to variable(s) 'delayInSeconds'  no-loop-func

src/workspaces/StartWorkspaceModal.tsx
  Line 35:55:  React Hook useEffect has a missing dependency: 'computeSelection'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

src/workspaces/WorkspaceEntry.tsx
  Line 167:42:  Comparing to itself is potentially pointless  no-self-compare
  Line 173:41:  Comparing to itself is potentially pointless  no-self-compare
  Line 179:42:  Comparing to itself is potentially pointless  no-self-compare

src/workspaces/Workspaces.tsx
  Line 119:41:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
```

### Steps to reproduce

Requires changes from https://github.com/gitpod-io/gitpod/pull/3830
Run `craco build`

### Expected behavior

-

### Example repository

-

### PR DESCRIPTION
**Pull request by Palanikannan1437**
## Related Issue(s)
* Closes #3841 's Login Page Errors 

## Description
- Fixes the lint issues in Login.tsx page
  - Fixes the absence of alt text for images in the welcome login page
  - Fixed the missing dependency of hostFromContext while fixing the multiple render bug!
- Additional Improvement
  - The urlHash i.e. domain/#`https://github.com/P......` part is calculated thrice in each page load to find the hostProvider, hence I've fixed it to just be calculated once by maintaining appropriate states while fixing the missing dependency issue!

| Before (the hash calc function runs thrice) | After (the function runs once) |
|:-----|:--------:|
| before | after |

## How to test
- Go to ./components/dashboard
- Run the command `yarn run start` and set appropriate environment variables `GP_DEV_HOST` & `GP_DEV_COOKIE` 
- Now you can see there's no lint errors regarding Login.tsx

| Before | After |
|:-----|:--------:|
| image  | image |

## Release Notes
```
Fixed lint warnings and multiple re-render bug in Login page 
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by roboquat** [comment]
@Palanikannan1437: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by gtsiolis — COMMENTED** [review]
Thanks for contributing, @Palanikannan1437! 🍊 

1. I'd rely on someone from the `@gitpod-io/engineering-webapp` to take a closer look at the code changes.
2. You'll also need to sign a CLA[[1](https://powerforms.docusign.net/30e1aa46-cce5-4bc6-a933-ad02cd8d5ada?env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&accountId=86335c2c-01b9-4edc-a187-014f5150a112)] once before merging your first contribution. Cc @meysholdt

/hold

**Comment by Palanikannan1437** [comment]
> Thanks for contributing, @Palanikannan1437! 🍊 
> 
> 1. I'd rely on someone from the `@gitpod-io/engineering-webapp` to take a closer look at the code changes.
> 2. You'll also need to sign a CLA[[1](https://powerforms.docusign.net/30e1aa46-cce5-4bc6-a933-ad02cd8d5ada?env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&accountId=86335c2c-01b9-4edc-a187-014f5150a112)] once before merging your first contribution. Cc @meysholdt
> 
> /hold

Hey @gtsiolis ,for sure... I've signed the CLA now from my side 🚀🚀

**Review by geropl — APPROVED** [review]
LGTM from WebApp :wave:

**Comment by Palanikannan1437** [comment]
> LGTM from WebApp 👋

Awesome thanks so much for the super quick review @gtsiolis @geropl 🧡

**Comment by meysholdt** [comment]
Thank you for singing the CLA @Palanikannan1437!

**Comment by gtsiolis** [comment]
@Palanikannan1437 Could you squash commits in this one? 🏓

**Comment by Palanikannan1437** [comment]
Hey @gtsiolis, for sure! I've squashed them into one😄

**Comment by gtsiolis** [comment]
Thanks @Palanikannan1437! Removing hold as this has been already approved from the `@gitpod-io/engineering-webapp` team in https://github.com/gitpod-io/gitpod/pull/16158#pullrequestreview-1280756333 and CLA has been signed in  https://github.com/gitpod-io/gitpod/pull/16158#issuecomment-1429706806.

/werft run

/hold

**Pull request merged**
