### PR TITLE
Enable OIDC client in preview environments

### PR DESCRIPTION
**Pull request by AlexTugarev**
This PR builds on top of https://github.com/gitpod-io/gitpod/pull/15440

The contents are essentials to run the OIDC flows in a preview environment:
* [proxy route /iam/*](https://github.com/gitpod-io/gitpod/commit/bebc686c75e4a5f6b12862c09f44561ba03593c1)
* [networkpolicy](https://github.com/gitpod-io/gitpod/commit/b4af8a7a1cc23a08bcf18f6b327698ba310808a3)
* [preview-env config](https://github.com/gitpod-io/gitpod/commit/58f49f4cbc6a7d6c920c6dd99ebd28071ff1cc1b)

## How to test
`https://at-oidc-proxy.preview.gitpod-dev.com/iam/oidc/start` should be accessible in the preview environment.

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

/hold as it depends on #15440

### CODE REVIEW

**Review by mads-hartmann — APPROVED** [review]
The deploy-gitpod.sh changes LGTM

**Comment by easyCZ** [comment]
This PR is again pretty huge. Can we make the lives of reviewers a bit easier and also make our progress towards a goal more incremental? This would also allow other contributors to see incrementally get up to speed rather than feel overwhelmed with a significant volume of changes.

I do see you've got individual commits, but the issue is at deployment time. With so many changes at once, we're not able to deploy them incrementally and therefore we deploy the whole batch. That in turns makes our lives harder when something goes wrong and we have to debug.

I appreciate that breaking the changes into smaller chunks can feel like overhead. But we need to *optimise for the team velocity, not an individual velocity*. Smaller, and incremental changes allow others to stay on top of the project, and in turn ensure you have others who understand the context of your next changes. You are also better communicating progress, and providing visibility on where we are with a project.

In this PR, there are multiple changes which are loosely correlated. For example:
1. Installer changes can be separate
2. Proxy config can be seperate
3. Application implementation can be seperate
4. Follow-ups from previous PR should be also separate

If you'd like, I'm more than happy to work with you to identify how we can split this up, and how to approach identifying incremental pieces in subsequent work - let me know if you'd like to work on this together.

**Comment by AlexTugarev** [comment]
@easyCZ, I think it should be clear from the description, that it wasn't on purpose. A quick ask would have clarified this.

So your suggestion is to split up the PR and create individual PRs for the three commits? Would that be much more helpful than selecting individual changes from https://github.com/gitpod-io/gitpod/pull/15441/files? 

Screenshot 2022-12-22 at 11 32 29

Happy to do so, if that's the only problem here.

**Review by ArthurSens — APPROVED** [review]
All good from the installer perspective 🙂

**Comment by AlexTugarev** [comment]
@mads-hartmann and @ArthurSens, 🙏🏻 really sorry for the noise! I had to split this apart to make it easier to review: 

https://github.com/gitpod-io/gitpod/pull/15482
https://github.com/gitpod-io/gitpod/pull/15481
https://github.com/gitpod-io/gitpod/pull/15483

**Comment by mads-hartmann** [comment]
@AlexTugarev All good, I appreciate you taking the time to slit it up 🧡

**Pull request closed without merging**
