### PR TITLE
[spicedb] Change readiness probe to unblock startup

### PR DESCRIPTION
**Pull request by geropl**
## Description

On new cell creation with k8s version 1.27.7 we experienced a dead lock on pod startup of spicedb, because the readiness probe check state that depends on the pod being ready... :upside_down_face: 
This PR solves it by weakening the readiness probe a bit, but adds a livenessProbe for the full check instead.

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖 Generated by Copilot at d80016b</samp>

Improve probes for `spicedb` component. Use TCP socket for readiness and exec command for liveness.

</details>

## Related Issue(s)

Fixes EXP-906

## How to test
 - I already tested in the cell where the problem occurred: [link](https://linear.app/gitpod/issue/EXP-906/spicedb-deployment-fails-in-gitpod-dedicated#comment-a27e49b3)
 - you can check the preview and see how it works with:
   - kubectl scale deployment/spicedb --replicas=0
   - kubectl scale deployment/spicedb --replicas=2
   - both pods come up as expected :heavy_check_mark: 

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by akosyakov** [comment]
@geropl do you just need an approve? I'm not sure how to verify?

@mustard-mh maybe you can have a second look at?

**Comment by geropl** [comment]
@akosyakov Thx for asking. You can verify that it works in the preview, but I did that as well.

Also, I tested this in a cell where we saw this error, and it worked fine. :heavy_check_mark: 

So yeah, a approve is ok I think!

**Comment by geropl** [comment]
Thank you @akosyakov ! :pray:

**Comment by mustard-mh** [comment]
> The [kubelet](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) uses liveness probes to know when to restart a container. For example, liveness probes could catch a deadlock, where an application is running, but unable to make progress. Restarting a container in such a state can help to make the application more available despite bugs. [[src](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)]

@geropl Then it will cause restart?

**Comment by geropl** [comment]
> @geropl Then it will cause restart?
> 
> I don't understand the changes 😞

Thanks for asking - yes, it does! The problem is that the way the health probe is implemented in spicedb, we hit a problem in fresh cells where it ends up in a dead lock.
So we weaken the readiness probe to not check the whether it's ready, but only do a pod-local check (see if a port is opened - note that we are constrained in our options here due to the reduced docker image we don't control): This avoids the dead-lock in the beginning.
But still, we want to get feedback if there are real problems with the connectivity of the pods, so we put the liveness probe in place.

**Pull request merged**
