### PR TITLE
[ws-daemon] Umount dangling mask mounts

### LINKED ISSUE #6732: [ws-daemon] proc mount leaks masking tmpfs mounts
### Bug description

When we produce a proc mount in ws-daemon, we mask the mount prior to moving it in place. It would seem that the `move_mount` operation leaves the masks dangling in the "proc mount staging". 

This is most likely because of [`OPEN_TREE_CLONE` flag](https://github.com/gitpod-io/gitpod/blob/a30a1bff483b02df67e01791b44dfb5bf025d344/components/ws-daemon/pkg/iws/iws.go#L578). We need `OPEN_TREE_CLONE ` so that we can use `AT_RECURSIVE`. We need `AT_RECURSIVE` to move the mask mounts as well.

When we have too many of those dangling mask mounts, at some point we fail to mount more and proc mounts start to fail. This affects content init and workspace startup.

### Steps to reproduce

Start a workspace.

### PR DESCRIPTION
**Pull request by csweichel**
## Description
This PR unmounts mask mounts used during proc and sysfs mount preparation.

## Related Issue(s)

Fixes #6732

## How to test
1. Start a workspace
3. Look at the ws-daemon filesystem and ensure there are no dangling tmpfs mounts in `/tmp/staging-*`
4. Ensure that you cannot unmount any of the `/proc` masks, e.g. `sched_debug`
5. Run `docker run --rm -it alpine:latest umount /proc/sched_debug` which should fail with a permission denied error
6. Check there are no errors in ws-daemon

## Release Notes

```release-note
[ws-daemon] Fix resource leak during proc mounts
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **csweichel** after the PR has been reviewed.

Associated issue: *#6732*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by csweichel** [comment]
We also need to umount the proc/sysfs again thanks to CLONE_TREE

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 33ee4ee75b4f304cdea362f6c73c485df8ba1e70</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6733#issuecomment-970482018" title="Approved">aledbf</a>*

Associated issue: *#6732*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)~~ [aledbf]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by csweichel** [comment]
This change - as simple as it may seem - causes all sorts of problems:
1. breaks `kubectl logs ws-dameon-...`
2. breaks proc mounts for Docker container within the workspace

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 70af2f17b56a6b5df03aec4d0987cafdf2fb6b62</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6733#issuecomment-973945746" title="LGTM">aledbf</a>*

Associated issue: *#6732*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)~~ [aledbf]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
