### PR TITLE
[content-service] Refactor upload to GCS

### PR DESCRIPTION
**Pull request by aledbf**
## Description

Remove creation of chunks and CRC from the upload of backups. This is one the sources of CPU/RAM utilization in ws-daemon

## How to test

- Check tests
```
cd test && \
go test -timeout 300s \
  -run ^TestObjectUpload$ github.com/gitpod-io/gitpod/content-service/pkg/storage -v
```
or use docker
```
go test -timeout 300s \
  -run ^TestObjectUpload$ github.com/gitpod-io/gitpod/content-service/pkg/storage -v -args -with-docker
```

```
=== RUN   TestObjectUpload
=== RUN   TestObjectUpload/valid_1M_backup
 - - [06/May/2022:15:55:09 -0400] "POST /storage/v1/b?alt=json&prettyPrint=false&project=fake-project HTTP/1.1" 200 161
 - - [06/May/2022:15:55:09 -0400] "GET /storage/v1/b/gitpod-dev-user-fake-owner/o/workspaces%2Ffake-workspace%2Ffull.tar?alt=json&prettyPrint=false&projection=full HTTP/1.1" 404 59
 - - [06/May/2022:15:55:09 -0400] "POST /upload/storage/v1/b/gitpod-dev-user-fake-owner/o?alt=json&name=workspaces%2Ffake-workspace%2Ffull.tar&prettyPrint=false&projection=full&uploadType=multipart HTTP/1.1" 200 536
 - - [06/May/2022:15:55:09 -0400] "GET /gitpod-dev-user-fake-owner/workspaces/fake-workspace/full.tar HTTP/1.1" 200 1001984
=== RUN   TestObjectUpload/valid_100M_backup
 - - [06/May/2022:15:55:09 -0400] "POST /storage/v1/b?alt=json&prettyPrint=false&project=fake-project HTTP/1.1" 200 161
 - - [06/May/2022:15:55:10 -0400] "GET /storage/v1/b/gitpod-dev-user-fake-owner/o/workspaces%2Ffake-workspace%2Ffull.tar?alt=json&prettyPrint=false&projection=full HTTP/1.1" 404 59
 - - [06/May/2022:15:55:10 -0400] "POST /upload/storage/v1/b/gitpod-dev-user-fake-owner/o?alt=json&name=workspaces%2Ffake-workspace%2Ffull.tar&prettyPrint=false&projection=full&uploadType=resumable HTTP/1.1" 200 337
 - - [06/May/2022:15:55:10 -0400] "POST /upload/resumable/0a59d243db09ba73ba636e0dc4c23eb3 HTTP/1.1" 200 474
 - - [06/May/2022:15:55:10 -0400] "POST /upload/resumable/0a59d243db09ba73ba636e0dc4c23eb3 HTTP/1.1" 200 474
 - - [06/May/2022:15:55:10 -0400] "POST /upload/resumable/0a59d243db09ba73ba636e0dc4c23eb3 HTTP/1.1" 200 474
 - - [06/May/2022:15:55:10 -0400] "POST /upload/resumable/0a59d243db09ba73ba636e0dc4c23eb3 HTTP/1.1" 200 474
 - - [06/May/2022:15:55:10 -0400] "POST /upload/resumable/0a59d243db09ba73ba636e0dc4c23eb3 HTTP/1.1" 200 474
 - - [06/May/2022:15:55:10 -0400] "POST /upload/resumable/0a59d243db09ba73ba636e0dc4c23eb3 HTTP/1.1" 200 538
 - - [06/May/2022:15:55:10 -0400] "GET /gitpod-dev-user-fake-owner/workspaces/fake-workspace/full.tar HTTP/1.1" 200 100001792
--- PASS: TestObjectUpload (0.97s)
    --- PASS: TestObjectUpload/valid_1M_backup (0.02s)
    --- PASS: TestObjectUpload/valid_100M_backup (0.95s)
PASS
ok      github.com/gitpod-io/gitpod/content-service/pkg/storage 0.979s
```

## Release Notes
```release-note
[content-service] Refactor upload to GCS
```

### CODE REVIEW

**Comment by roboquat** [comment]
@aledbf: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by aledbf** [comment]
```
❯ go test -timeout 60s -run ^TestObjectUpload$ github.com/gitpod-io/gitpod/content-service/pkg/storage -count=1 -v
=== RUN   TestObjectUpload
=== RUN   TestObjectUpload/valid_1M_backup
 - - [06/May/2022:18:47:27 -0400] "POST /storage/v1/b?alt=json&prettyPrint=false&project=fake-project HTTP/1.1" 200 161
 - - [06/May/2022:18:47:27 -0400] "GET /storage/v1/b/gitpod-dev-user-fake-owner/o/workspaces%2Ffake-workspace%2Ffull.tar?alt=json&prettyPrint=false&projection=full HTTP/1.1" 404 59
 - - [06/May/2022:18:47:27 -0400] "POST /upload/storage/v1/b/gitpod-dev-user-fake-owner/o?alt=json&name=workspaces%2Ffake-workspace%2Ffull.tar&prettyPrint=false&projection=full&uploadType=multipart HTTP/1.1" 200 536
 - - [06/May/2022:18:47:27 -0400] "GET /gitpod-dev-user-fake-owner/workspaces/fake-workspace/full.tar HTTP/1.1" 200 1050112
=== RUN   TestObjectUpload/valid_100M_backup
 - - [06/May/2022:18:47:27 -0400] "POST /storage/v1/b?alt=json&prettyPrint=false&project=fake-project HTTP/1.1" 200 161
 - - [06/May/2022:18:47:29 -0400] "GET /storage/v1/b/gitpod-dev-user-fake-owner/o/workspaces%2Ffake-workspace%2Ffull.tar?alt=json&prettyPrint=false&projection=full HTTP/1.1" 404 59
 - - [06/May/2022:18:47:29 -0400] "POST /upload/storage/v1/b/gitpod-dev-user-fake-owner/o?alt=json&name=workspaces%2Ffake-workspace%2Ffull.tar&prettyPrint=false&projection=full&uploadType=resumable HTTP/1.1" 200 337
 - - [06/May/2022:18:47:29 -0400] "POST /upload/resumable/69e4d23e240f9dcb137c28eb4b9fe2ef HTTP/1.1" 200 474
 - - [06/May/2022:18:47:29 -0400] "POST /upload/resumable/69e4d23e240f9dcb137c28eb4b9fe2ef HTTP/1.1" 200 538
 - - [06/May/2022:18:47:29 -0400] "GET /gitpod-dev-user-fake-owner/workspaces/fake-workspace/full.tar HTTP/1.1" 200 104859136
=== RUN   TestObjectUpload/valid_1GB_backup
 - - [06/May/2022:18:47:30 -0400] "POST /storage/v1/b?alt=json&prettyPrint=false&project=fake-project HTTP/1.1" 200 160
 - - [06/May/2022:18:47:33 -0400] "GET /storage/v1/b/gitpod-dev-user-fake-owner/o/workspaces%2Ffake-workspace%2Ffull.tar?alt=json&prettyPrint=false&projection=full HTTP/1.1" 404 59
 - - [06/May/2022:18:47:33 -0400] "POST /upload/storage/v1/b/gitpod-dev-user-fake-owner/o?alt=json&name=workspaces%2Ffake-workspace%2Ffull.tar&prettyPrint=false&projection=full&uploadType=resumable HTTP/1.1" 200 337
 - - [06/May/2022:18:47:33 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:33 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:33 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:33 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:34 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:34 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:35 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:35 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:36 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:37 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:38 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:39 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:40 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:41 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:42 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:43 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 474
 - - [06/May/2022:18:47:44 -0400] "POST /upload/resumable/4f9700cc631a2df2cae7cf8ad7c097a2 HTTP/1.1" 200 539
 - - [06/May/2022:18:47:45 -0400] "GET /gitpod-dev-user-fake-owner/workspaces/fake-workspace/full.tar HTTP/1.1" 200 1073743360
--- PASS: TestObjectUpload (19.70s)
    --- PASS: TestObjectUpload/valid_1M_backup (0.01s)
    --- PASS: TestObjectUpload/valid_100M_backup (2.41s)
    --- PASS: TestObjectUpload/valid_1GB_backup (17.27s)
PASS
ok  	github.com/gitpod-io/gitpod/content-service/pkg/storage	19.733s

```

**Review by csweichel — COMMENTED** [review]
Took the liberty to push a commit which simplifies the content upload to GCloud further.

I'm not all that hopeful that this change will actually decrease memory use in practice, because of 
image

If anything, the code that existed prior (albeit a ton more complicated) would give us some control over the amount of buffering we do.

**Comment by aledbf** [comment]
> Took the liberty to push a commit which simplifies the content upload to GCloud further.

That was on purpose :) 
I want to ensure we run the upload in a dedicated goroutine and remove any doubt of interference with other parts of ws-daemon

**Comment by aledbf** [comment]
> If anything, the code that existed prior (albeit a ton more complicated) would give us some control over the amount of buffering we do.

but we are setting a value https://github.com/gitpod-io/gitpod/pull/9836/files#diff-c42db953f8fdf32db52a02ec07b01ac4193206a1fe63ffa86201a31dc7e83bd8R374

**Comment by csweichel** [comment]
> 

Ooops. Please just drop the commit then :D

**Comment by csweichel** [comment]
> > If anything, the code that existed prior (albeit a ton more complicated) would give us some control over the amount of buffering we do.
> 
> but we are setting a value https://github.com/gitpod-io/gitpod/pull/9836/files#diff-c42db953f8fdf32db52a02ec07b01ac4193206a1fe63ffa86201a31dc7e83bd8R374

We are indeed - good point. Max memory usage this should produce then is `numberOfWorkspaces * 64MiB`.

**Comment by aledbf** [comment]
>  Max memory usage this should produce then is numberOfWorkspaces * 64MiB.

I cannot use more 200MB after the refactoring (I even tried to upload 10GB)

**Review by csweichel — APPROVED** [review]
🚀

**Review by akosyakov — APPROVED** [review]
lgtm

**Review by MrSimonEmms — APPROVED** [review]

**Comment by aledbf** [comment]
>  What's the trade-off in terms of upload speed?

Good question. Right now we lose nodes due to the memory utilization. That said, I don't see the current behavior to be too fast.

Screenshot from 2022-05-10 11-11-52
Screenshot from 2022-05-10 11-11-31

(last 7hs)

**Review by geropl — APPROVED** [review]
Code changes LGTM, did not test. :+1:

**Review by Furisto — APPROVED** [review]

**Pull request merged**
