### PR TITLE
[metrics] exclude VS Code Browser from error reporting

### PR DESCRIPTION
**Pull request by akosyakov**
## Description

They are too noisy right now. We still report observability. Later we are going to reconsider to report only from our components to make it more useful.

## Related Issue(s)

Fixes #

## How to test

The build should pass.

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - ak-no-browser-errors</li>
	<li><b>🔗 URL</b> - <a href="https://ak-no-browser-errors.preview.gitpod-dev.com/workspaces" target="_blank">ak-no-browser-errors.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - ak-no_browser_errors-gha.12507</li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`
</details>

/hold

### CODE REVIEW

**Review by mustard-mh — COMMENTED** [review]
Code LGTM, going to enable preview to test

**Comment by akosyakov** [comment]
@mustard-mh is it good to land?

**Review by mustard-mh — APPROVED** [review]
Tested in preview env, 

- It will log once if requests are coming from not expected components
- It can report errors if components are allowed

image

**Pull request merged**
