### PR TITLE
[proxy] return 503 for /analytics errors, instead of 502

### PR DESCRIPTION
**Pull request by kylos101**
## Description

The default ErrorHandler for `httputil.NewSingleHostReverseProxy` returns 502 status codes. Let us instead return a 503 status code for the /analytics endpoint. 

Why? This will help us trigger the [ProxyBadGateway](https://github.com/gitpod-io/gitpod-dedicated/blob/main/ops/telemetry/alerts/proxy.yaml) alert less often, ideally when there are proxy failures breaking the user experience.

Background:
It fires more often in Enterprise, for /analytics/v1/batch, which routes to telemetry-exporter (and then to Firehose and S3), but is likely having trouble with telemetry-exporter. 

More background:
I checked the logs for telemetry-exporter and could not find a record of a failure. Therefore, I opted for this change, so as to make the ProxyBadGateway alert more valuable by excluding /analytics requests.

## Related Issue(s)

Related to ENT-268
Fixes ENT-331

## How to test

With a kube context for the preview, do:
```
kubectl set env deployment/proxy ANALYTICS_PLUGIN_SEGMENT_ENDPOINT=https://idontexistnope.com/foo
```

Then start a workspace, then check logs and metrics.

In the preview logs:
image

In metrics:
image

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - kylos101-ent-268</li>
	<li><b>🔗 URL</b> - <a href="https://kylos101-ent-268.preview.gitpod-dev.com/workspaces" target="_blank">kylos101-ent-268.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - kylos101-ENT-268-gha.26903</li>
	<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-kylos101-ent-268%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws-manager-mk2%22%0A;duration=P1D?project=gitpod-dev-preview" target="_blank">GCP Logs Explorer</a></li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [x] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [x] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by kylos101** [comment]
@akosyakov you probably have the most experience in this space, could I ask for a review, time permitting?

**Comment by akosyakov** [comment]
@kylos101 why does it fires more often on Enterprise? Should we fix the root cause? Don't we miss analytics then?

**Comment by geropl** [comment]
> Why? This will help us trigger the [ProxyBadGateway](https://github.com/gitpod-io/gitpod-dedicated/blob/main/ops/telemetry/alerts/proxy.yaml) alert less often, ideally when there are proxy failures breaking the user experience.

@kylos101 Did we try to ignore the route in proxy for error reporting? This feels like "too far away" from the impact, and can actually be misleading to others as well. This could help us find time (and prioritize) to fix the underlying root cause as Anton mentioned.

**Comment by kylos101** [comment]
👋 thanks for the review, @akosyakov ! Let me know if this helps or if you need more info?

> @kylos101 why does it fires more often on Enterprise? 

There is a separate issue causing the send of analytics to fail sometimes for Enterprise.

> Should we fix the root cause? Don't we miss analytics then?

Yes, but, that is a separate problem, I will create a Linear issue. In other words, this PR aims to avoid returning errors as 502 for /analytics failures. 

When Proxy returns 502 error code, we'll notify in PagerDuty. For the 503 error code, we'll notify in Slack. This way, failures for /analytics don't wake someone up at night.

**Review by akosyakov — APPROVED** [review]

**Comment by kylos101** [comment]
👋 @geropl , let me know if this helps, or if you'd like more info?

> @kylos101 Did we try to ignore the route in proxy for error reporting? 

What status code would you expect Proxy to return on ignore for /analytics failures?

Based on docs I've read and testing I've done, changes to the error handler must be done in code (rather than the Caddyfile). ℹ️ The default error code in Caddy reverse proxy is 502.

By returning a 503 for errors associated with /analytics, it provides us with flexibility at the alerting level. Ideally 502's would trigger alerts that route to PagerDuty (to wake someone up), but 503's would trigger alerts which route to Slack (to not wake someone up). This change only impacts the analytics handler, the default handler for others will continue to return 502.

Presently the /analytics/v1/batch endpoint is the only one producing 502 errors on a regular basis with Enterprise, since it's not user facing, that is why I changed it to 503. 

> This feels like "too far away" from the impact, 

How so? Can you elaborate?

I'll share a separate issue for the analytics failures potentially caused by telemetry-exporter. ([ref](https://github.com/gitpod-io/gitpod/pull/19970#issuecomment-2191475804))

> and can actually be misleading to others as well. 

What do you mean / misleading how? 

The new normal will be to get PagerDuty alerts for increased thresholds of 502. That will result in us bug fixing and/or changing the underlying handler to a different status code (depending on whether we want to wake someone up or not for that handler). For example, if the handler is for user facing traffic, we'd do nothing to the error handler (so it continues to send 502). However, if it's not user facing, we could consider changing to a 503 (or some other code).

> This could help us find time (and prioritize) to fix the underlying root cause as Anton mentioned.

Returning a 503 finds time by avoiding the triggering of this alert to PagerDuty. We can create a new alert that routes 503 alerts to Slack. Would that work?

As discussed above, I'll make a separate issue for the root cause. What I'm trying to solve here, is alerting via PagerDuty for /analytics failures.

**Comment by geropl** [comment]
@kylos101 Sorry for the noise! I was thinking about using a [replace_status](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#replace_status) directive, but checked, and we directly call the plugin... :see_no_evil:

**Review by geropl — APPROVED** [review]

**Comment by kylos101** [comment]
For posterity, I created https://linear.app/gitpod/issue/ENT-346/, to get to the root cause for the /analytics failures.

**Pull request merged**
