### PR TITLE
[gitpod-db] don't leak DBUser

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description

Encapsulates the DBUser object graph within user-db-impl

## Related Issue(s)

Fixes #

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - se-user-object</li>
	<li><b>🔗 URL</b> - <a href="https://se-user-object.preview.gitpod-dev.com/workspaces" target="_blank">se-user-object.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`
</details>

/hold

### CODE REVIEW

**Review by geropl — APPROVED** [review]
Basic things work in preview. :heavy_check_mark: 

Let's give this a try!

**Review by AlexTugarev — APPROVED** [review]
LGTM!

Would you change the PR target to main?

**Comment by svenefftinge** [comment]
> Would you change the PR target to main?

happens automatically once the target branch gets merged into main

**Pull request merged**
