### PR TITLE
Remove ide-proxy network-policy

### LINKED ISSUE #7562: In preview environment, ide image in setting is broken
### Bug description

In preview environment, ide image in setting is broken

### Steps to reproduce

open a new preview environment

image

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by iQQBot**
## Description

Fixes in preview environment, ide image in setting is broken

This is because we use different policies in helm and installer, as a proxy it is not necessary to add any network policy, so now remove it

## Related Issue(s)

Fixes #7562 

## How to test

go to https://pd-remove-ide-net-polic.staging.gitpod-dev.com/ and change to setting preference, you can see the ide logo is here

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
@iQQBot: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **iqqbot** after the PR has been reviewed.

Associated issue: *#7562*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[installer/pkg/components/ide-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ide-proxy/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7563#issuecomment-1010867213" title="Approved">iQQBot</a>*

Associated issue: *#7562*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [iQQBot]
- ~~[installer/pkg/components/ide-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ide-proxy/OWNERS)~~ [iQQBot]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by akosyakov — APPROVED** [review]
/lgtm
/approve

images are there

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 9dcbc63df114c8592a63327cceafd8a2ba16331d</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7563#pullrequestreview-850255546" title="Approved">akosyakov</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7563#issuecomment-1010867213" title="Approved">iQQBot</a>*

Associated issue: *#7562*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [akosyakov,iQQBot]
- ~~[installer/pkg/components/ide-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ide-proxy/OWNERS)~~ [akosyakov,iQQBot]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
