### PR TITLE
Workspaces list mobile adjustments.

### PR DESCRIPTION
**Pull request by nisarhassan12**

### CODE REVIEW

**Comment by jankeromnes** [comment]
@nisarhassan12 Many thanks for improving the Gitpod dashboard for mobile devices!

As a small suggestion, I notice that the PR title "mobile improvements" is very generic. Instead of doing multiple improvements in a single Pull Request, do you think you could make only one improvement per PR, to keep PRs smaller and allow merging them faster / risking fewer conflicts?

For example, you could try to make one small PR to fix each of these issues separately (also, doing one PR after the other is fine, especially if you think that one PR will depend on work done in another PR -- no need to do them all in parallel):
- https://github.com/gitpod-io/gitpod/issues/1857
- https://github.com/gitpod-io/gitpod/issues/1855
- https://github.com/gitpod-io/gitpod/issues/1858

**Comment by nisarhassan12** [comment]
@jankeromnes Many for the suggestion. I have changed the Pr title as it had relevant changes for the workspaces list and for other things I'll make small Prs as you suggested.

**Comment by jankeromnes** [comment]
That's awesome, many thanks @nisarhassan12! 💯

**Pull request closed without merging**
