### PR TITLE
moved job to build code-nightly from werft to github-actions

### PR DESCRIPTION
**Pull request by wulfthimm**
## Description

This moves the nightly build job for vscode to GitHub actions and removes the job from werft.

## Related Issue(s)

Fixes #https://github.com/gitpod-io/ops/issues/360

## How to test

The build has already been tested and can be viewed [here](https://github.com/gitpod-io/gitpod/runs/4352619395?check_suite_focus=true).
The image is published [here](https://console.cloud.google.com/gcr/images/gitpod-core-dev/eu/build/ide/code@sha256:c56400e427dc930627ba10b95f65c9b6feb6642f99110cb10959307bce8fb555/details?project=gitpod-core-dev).

### CODE REVIEW

**Comment by roboquat** [comment]
@wulfthimm: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mrsimonemms** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mrsimonemms` in a comment when ready.

Associated issue: *#360*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by jeanp413 — APPROVED** [review]
Thanks @wulfthimm

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 5688bedfd88e3bcd687354da4ba3e5121cb0e6e0</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6961#pullrequestreview-817828869" title="Approved">jeanp413</a>*

Associated issue: *#360*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [jeanp413]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6961#issuecomment-981658406" title="Approved">jeanp413</a>*

Associated issue: *#360*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [jeanp413]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jeanp413** [comment]
@wulfthimm I think you need to set the release notes to `NONE` so it can be merged

**Comment by ArthurSens** [comment]
@wulfthimm, the `do-not-merge/release-note-label-needed` is there because all PRs should have a release note.

Our changelog automation depends on it. I'm adding it for you but please do it yourself next time 😬

**Pull request merged**
