### PR TITLE
[WIP][fga] WorkspaceService: watchWorkspaceImageBuildLogsm getHeadlessLog, WorkspaceService.sendHeartBeat

### PR DESCRIPTION
**Pull request by geropl**
## Description
Ticks the FGA boxes for the following methods:

- watchWorkspaceImageBuildLogs
- getHeadlessLog
- WorkspaceService.sendHeartBeat

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖 Generated by Copilot at b55df37</samp>

Refactored headless log and workspace image build logic to use `WorkspaceService` class. Moved constants and types to appropriate modules. Simplified and deprecated old methods in `GitpodServerImpl`. Added tests for `WorkspaceService`.

</details>

## Related Issue(s)
Parts of [EXP-207](https://linear.app/gitpod/issue/EXP-207)
Based on: https://github.com/gitpod-io/gitpod/pull/18535

## How to test
- signup as regular users 1 and 2, and enable [centralizedPermissions](url) for your userIDs on ConfigCat
- user 1: start a workspace
- user 1: open devtools and run `await window._gp.gitpodService.server.sendHeartBeat("your-instance-id")` :heavy_check_mark: 
- user 2: open devtools, and run  `await window._gp.gitpodService.server.sendHeartBeat("same-instance-id")`: should fail with `Error: Workspace xyz not found.` :heavy_check_mark: 

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - gpl-fga-ws-misc-2</li>
	<li><b>🔗 URL</b> - <a href="https://gpl-fga-ws-misc-2.preview.gitpod-dev.com/workspaces" target="_blank">gpl-fga-ws-misc-2.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - gpl-fga-ws-misc-2-gha.15554</li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by svenefftinge** [comment]
Can you rebase? It's not clear what changes belong to this PR.

**Comment by geropl** [comment]
> Can you rebase? It's not clear what changes belong to this PR.

Done. Not sure why it did not rebase automatically...? Due to the squash?

**Review by svenefftinge — APPROVED** [review]
I would have assumed the two log related methods would go into headless-log-service but it might not be so easy to draw the line between that and the workspace service, so let's go with this for now and see how we can improve this in future.
otherwise code LGTM

**Comment by geropl** [comment]
> I would have assumed the two log related methods would go into headless-log-service

I was torn here as well. :+1:

**Pull request merged**
