### PR TITLE
Default to letsencrypt cert issuer

### PR DESCRIPTION
**Pull request by vulkoingim**
## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by mads-hartmann** [comment]
⬆️ Ah wait, that won't work as it will still use .werft from main. Will start a a job from the CLI instead. I'm can't personally get a certificate working with either of the issuers so I'm using this to test if I'm just extremely unlucky :P

**Comment by mads-hartmann** [comment]
[Job](https://werft.gitpod-dev.com/job/gitpod-build-aa-cert-issuer-def.2)

```sh
werft job run github -a with-preview=true
```

**Review by mads-hartmann — APPROVED** [review]
Change LGTM, adding hold as I'm just verifying that it works (I can't get a certificate with either issuer on branches off main so using this to test)

**Comment by vulkoingim** [comment]
> [Job](https://werft.gitpod-dev.com/job/gitpod-build-aa-cert-issuer-def.2)
> 
> ```shell
> werft job run github -a with-preview=true
> ```

You'll need to destroy everything first as changing the issuer on an existing cert resource doesn't seem to work.

**Comment by mads-hartmann** [comment]
> You'll need to destroy everything first as changing the issuer on an existing cert resource doesn't seem to work. For good measure remove associated certificaterequests, orders, challenges if there are any remaining.

Given I got two concurrent jobs running because I didn't mange to stop .1 in time I'm just going to remove the hold and experiment on fresh branches off main instead ☺️

**Pull request merged**
