### PR TITLE
Use User.fgaRelationshipsVersion instead of User.additionalAttributes.fgaRelationshipsVersion

### PR DESCRIPTION
**Pull request by geropl**
## Description
To be able to add indexes, and separate concerns.

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖 Generated by Copilot at 141a7cc</samp>

This pull request implements the FGA migration, which moves the FGA version from the `additionalData` field to a separate column in the `d_b_user` table. It updates the user data model, the database schema and migrations, the user database service and its tests, the relationship updater and its tests, and the user controller and service. It also fixes a typo in an unrelated migration.

</details>

## Related Issue(s)

Fixes EXP-726

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - gpl-726-fga-version</li>
	<li><b>🔗 URL</b> - <a href="https://gpl-726-fga-version.preview.gitpod-dev.com/workspaces" target="_blank">gpl-726-fga-version.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - gpl-726-fga-version-gha.17912</li>
	<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-gpl-726-fga-version%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws-manager-mk2%22%0A;duration=P1D?project=gitpod-core-dev" target="_blank">GCP Logs Explorer</a></li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by geropl** [comment]
@svenefftinge The related query turned up #3 on Monday while FGA was on. This PR just creates a new column and uses that, which is ok I thought because of the version 3 migration that has to be done anyway. WDYT?

**Review by svenefftinge — APPROVED** [review]
thanks, that makes sense!

**Pull request merged**
