### PR TITLE
Update probot lib

### PR DESCRIPTION
**Pull request by jeanp413**
## Description

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖 Generated by Copilot at 466b4f1</samp>

Updated `probot` dependency in `components/server/package.json` to fix GitHub integration issues.

</details>

## Related Issue(s)

Relates [EXP-418](https://linear.app/gitpod/issue/EXP-418/gitpod-core-devbuildserver)

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - jp-clear-snipe</li>
	<li><b>🔗 URL</b> - <a href="https://jp-clear-snipe.preview.gitpod-dev.com/workspaces" target="_blank">jp-clear-snipe.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - jp-clear-snipe-gha.16021</li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by AlexTugarev** [comment]
I wonder if there is a way to test it in a preview env. We'd need to create the setup of a GH App manually, right?

**Comment by svenefftinge** [comment]
@jeanp413 could you share the reason for this update?

**Comment by AlexTugarev** [comment]
This is part of EXP-504.

**Pull request merged**
