### PR TITLE
cleanup k3s cluster in core-dev

### LINKED ISSUE #7135: werft gitpod-wipe-devstaging is broken due k3scluster is destroy
### Bug description

werft gitpod-wipe-devstaging is broken due k3scluster is destroy

### Steps to reproduce

see https://werft.gitpod-dev.com/

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by iQQBot**
## Description

cleanup k3s cluster in core-dev

## Related Issue(s)

Fixes #7135

## How to test

see https://werft.gitpod-dev.com/job/gitpod-wipe-devstaging-pd-werft-wipe-devstaging-7135.0

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
@iQQBot: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **laushinka** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @laushinka` in a comment when ready.

Associated issue: *#7135*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by kylos101** [comment]
Hey @iQQBot , can we also remove `.werft/values.k3sWsCluster.yaml`? It doesn't look like it is used anymore.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7136#issuecomment-990060796" title="Approved">kylos101</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **laushinka** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @laushinka` in a comment when ready.

Associated issue: *#7135*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: e14d26a64f2a54c819a8f21a50e2446043e8fe6b</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7136#issuecomment-990061495" title="LGTM">kylos101</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **laushinka** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @laushinka` in a comment when ready.

Associated issue: *#7135*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by kylos101** [comment]
Hi @laushinka may we ask for your help to review this PR? [It should help solve the issue we found here.](https://gitpod.slack.com/archives/C020VCB0U5A/p1638994616407900)

Thank you @iQQBot for putting this together!

**Comment by kylos101** [comment]
Hey @laushinka sorry about the spam! Rather than assign to you directly, I've set to the Meta team. This way it [becomes visible here](https://github.com/gitpod-io/gitpod/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3A%22team%3A+meta%22+-label%3A%22cla%3A+pending+%3Ahourglass_flowing_sand%3A%22+-label%3Ado-not-merge%2Fwork-in-progress+).

**Comment by geropl** [comment]
/lgtm

:+1:

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7136#issuecomment-990709300" title="LGTM">geropl</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7136#issuecomment-990061495" title="LGTM">kylos101</a>*

Associated issue: *#7135*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [geropl]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by laushinka** [comment]
> Hi @laushinka may we ask for your help to review this PR? [It should help solve the issue we found here.](https://gitpod.slack.com/archives/C020VCB0U5A/p1638994616407900)

@kylos101 Oops sorry I just saw this! Glad that Gero came to the rescue 🤗

**Pull request merged**
