### PR TITLE
[dashboard] closeable limit-reached-modal

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description
Allow closing the limit reached modal when starting a workspace from the new create workspace page.

## Related Issue(s)

Fixes #

## How to test

create an org without credits and try starting a workspace within. See a dialog telling you about limit reached and try closing it.

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by AlexTugarev** [comment]
'Testing.

**Review by easyCZ — APPROVED** [review]
Worked for me. Added hold in case you want to wait for Alex's review as well.

**Review by AlexTugarev — APPROVED** [review]
This works as described in the description. I see, the Limit Reached modal is closable now.

@svenefftinge just a few questions to better understand the context of this change.

0. Unfortunately, the preview env does not contains the other change about the Create Workspace button, but I can image in combination this will work even better. 
1. This does not touch the Limit Reached modal on restart of a stopped workspace from the list. Given we're adding it for the New Workspace case, would that need to be aligned as well? 
   Screenshot 2023-03-10 at 09 08 32
2. That's independent of this PR, but I was surprised that the workspace entry is still created, even if the usage limit is reached. It makes sense from a technical pov, but it leads to unexpected pollution. Maybe it's worth cutting an issue for that, no?

**Comment by svenefftinge** [comment]
> This does not touch the Limit Reached modal on restart of a stopped workspace from the list.

Yes, that is intentional, as in the old/existing flows you would see this screen on the start workspace screen where you can't do anything. 

> That's independent of this PR, but I was surprised that the workspace entry is still created

Yes, not ideal. I believe we should check credits before starting the workspace and actually already show the lack of credits in the create workspace page. Same for running workspaces on the same context.

**Pull request merged**
