### PR TITLE
(test, please ignore & don't merge)

### PR DESCRIPTION
**Pull request by jankeromnes**
## Description

Just me testing preview environments now that the Stripe key has changed. 🤞 

## Related Issue(s)

Fixes nothing

## Release Notes

```release-note
```

## Werft options:

- [x] /werft with-preview
- [x] /werft with-payment

### CODE REVIEW

**Comment by roboquat** [comment]
@jankeromnes: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jankeromnes** [comment]
Whoops:

Screenshot 2022-08-22 at 15 11 33


```
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"server","version":"jx-test-stripe.2"},"stack_trace":"Error: Multiple teams have billing enabled.\n    at UserServiceEE.<anonymous> (/app/node_modules/@gitpod/server/dist/src/user/user-service.js:207:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/@gitpod/server/dist/src/user/user-service.js:19:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","component":"server","severity":"ERROR","time":"2022-08-22T13:09:19.809Z","context":{"userId":"a04e0198-d849-4e40-8530-6069ec674a60"},"message":"EntitlementService error: mayStartWorkspace","error":"Error: Multiple teams have billing enabled.\n    at UserServiceEE.<anonymous> (/app/node_modules/@gitpod/server/dist/src/user/user-service.js:207:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/@gitpod/server/dist/src/user/user-service.js:19:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"component":"server","severity":"INFO","time":"2022-08-22T13:09:19.810Z","context":{"userId":"a04e0198-d849-4e40-8530-6069ec674a60"},"message":"Request createWorkspace unsuccessful: 500/\"Error in Entitlement Service.\"","payload":{"method":"createWorkspace","args":[{"contextUrl":"https://github.com/autofix-dev/autofix","mode":"select-if-running","forceDefaultConfig":false},{"_isCancelled":false}]}}
```

This should have been a modal to select your billing account. Regression?

**Comment by jankeromnes** [comment]
Subscribing & reporting usage seems to work! ✨ 

<table><tr><td>
Screenshot 2022-08-22 at 15 19 34
</td><td>
Screenshot 2022-08-22 at 15 19 26
</td></tr></table>

**Comment by jankeromnes** [comment]
Tests completed successfully. ✅

**Pull request closed without merging**
