### PR TITLE
[login] first user must accept ToS

### PR DESCRIPTION
**Pull request by AlexTugarev**
On each Gitpod installation, the first user must accept ToS.

### CODE REVIEW

**Comment by csweichel** [comment]
When clicking on Login I saw the ToS screen: 
image

(did not actually sign up, so there are still no users in the installation).

**Comment by AlexTugarev** [comment]
> (did not actually sign up, so there are still no users in the installation).

correct. you can try. if you delete the account afterwards, it will reappear.

**Comment by svenefftinge** [comment]
looks good, but it should include and point to the actual TOS for self-hosted.

**Comment by AlexTugarev** [comment]
I changed to link to point to `www.gitpod.io/self-hosted-terms` [1] and slightly modified wording, as it sound a bit off in case of a self-hosted installation. Please have a look.

[1] https://github.com/gitpod-io/website/pull/741

**Review by svenefftinge — APPROVED** [review]
works well!

**Pull request merged**
