### PR TITLE
[redis] Deploy component

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

Deploys redis into application cluster.

* No persistence
* Single instance setup

## Related Issue(s)

Fixes #

## How to test

1. Redis comes up in preview k8s

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-slow-database
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by geropl** [comment]
Awesome! :heart_eyes: 

I'd love to :heavy_check_mark: , but there seems to be a config error atm:

image

**Comment by easyCZ** [comment]
> Awesome! 😍
> 
> I'd love to ✔️ , but there seems to be a config error atm:
> 
> image

Ah, it's because I edited the deployment in preview previously, and preview doesn't overwrite/clenaup properly.
This should do it.

/werft run with-clean-slate-deployment=true

**Review by geropl — APPROVED** [review]
Working now :lotus_position: :heavy_check_mark:

**Comment by easyCZ** [comment]
Hey tide, why you no merge this?

**Comment by geropl** [comment]
> Hey tide, why you no merge this?

@gitpod-io/engineering-security-infrastructure-and-delivery :point_up:

**Comment by easyCZ** [comment]
Weird, that ownership was not showing up for my view

**Pull request merged**
