### PR TITLE
New roles

### PR DESCRIPTION
**Pull request by securitymirco**
This pull requests introduces updated administrative permissions and related roles.

### CODE REVIEW

**Review by svenefftinge — APPROVED** [review]
LGTM 
just ADMIN_ROLE is not a great name for a role that allows for deleting users.

/hold in case you want to change that

**Comment by geropl** [comment]
> just ADMIN_ROLE is not a great name for a role that allows for deleting users.

I agree here. @securitymirco Do we want to sync so we can get this out the door? :telephone_receiver:

**Comment by geropl** [comment]
Synced with @securitymirco .

**Summary**:
 - rename to `ADMIN_ROOT`
 - for previews (and as long as we still have the "first user becomes admin" hack), add [here](https://github.com/gitpod-io/gitpod/blob/05e18a58ea13b127e6b3b8ab64ed4a06059f98eb/components/server/src/user/user-service.ts#L160)
 - announced to colleagues here [tomorrow](https://www.notion.so/gitpod/Decision-Time-6d458332bf6a4b39821740e77360c190?pvs=4#ef219798811842b790b4bb3fd2aa0602) (25.04.)

**Comment by geropl** [comment]
Was communicated [here](https://www.notion.so/gitpod/Decision-Time-6d458332bf6a4b39821740e77360c190?pvs=4#ef219798811842b790b4bb3fd2aa0602) :heavy_check_mark: .

Will rebase, and merge afterwards.

**Pull request merged**
