### PR TITLE
Include in the README where to access the development environment when developing dashboards using gitpod

### PR DESCRIPTION
**Pull request by utam0k**
Signed-off-by: utam0k <k0ma@utam0k.jp>

## Description

I was a bit confused when I tried to start developing the dashboard, so I added a README to solve that.

## Related Issue(s)

None

## How to test

None

## Release Notes

```release-notes
NONE
```

## Documentation

No

### CODE REVIEW

**Comment by roboquat** [comment]
@utam0k: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jldec** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jldec` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by utam0k** [comment]
[Render](https://github.com/gitpod-io/gitpod/blob/715b4421aab3a91b3c95608a0cbcba7f9bbfbbab/components/dashboard/README.md#how-to-develop-in-gitpodio)

**Comment by JanKoehnlein** [comment]
/approve no-issue
/lgtm 

Thanks for the PR!

In the future, please make sure your release-note is enclosed in triple backticks like this

<pre>
```release-notes
NONE
```
</pre>

otherwise our changelog parser doesn't recognise it.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 94f9988a94e48974c9dadf55bfba5cc36a97dadf</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7581#issuecomment-1020069119" title="Approved">JanKoehnlein</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/7581#issuecomment-1020069119" title="Approved">JanKoehnlein</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [JanKoehnlein]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
