### PR TITLE
[ws-manager-mk2] Make WorkspaceRunningCondition.LastTransitionTime stable

### PR DESCRIPTION
**Pull request by geropl**
## Description
Avoid bumping the LastTransitionTime of the WorkspaceRunningCondition on every reconciler run by only updating it if the status changed. This is a pattern we seem to be using for all other conditions as well.

## Related Issue(s)

Fixes ENT-48

## How to test
 - IDK, need to ask Thomas

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - gpl-48-sta470ba46621</li>
	<li><b>🔗 URL</b> - <a href="https://gpl-48-sta470ba46621.preview.gitpod-dev.com/workspaces" target="_blank">gpl-48-sta470ba46621.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - gpl-48-stable-running-conditiony-gha.24927</li>
	<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-gpl-48-sta470ba46621%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws-manager-mk2%22%0A;duration=P1D?project=gitpod-dev-preview" target="_blank">GCP Logs Explorer</a></li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [x] with-integration-tests=workspace
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Review by WVerlaek — APPROVED** [review]
nice find

**Comment by geropl** [comment]
Waiting for the integration tests now :eyes:

**Comment by geropl** [comment]
Hm, I see multiple errors in the [integration test logs](https://github.com/gitpod-io/gitpod/actions/runs/8936417998/job/24547572089?pr=19698), but none of those seem related to the changes :thinking: 

@Furisto Could you help discern those?

**Comment by kylos101** [comment]
👋 @geropl I am working on the tests here:

https://github.com/gitpod-io/gitpod/pull/19692

TestOpenWorkspaceFromOutdatedPrebuild fails intermittently, and can be temporarily ignored.

Aside from that, the other two failures I've fixed. The network limiting is failing because the preview environments test user is not UBP.

**Pull request merged**
