### PR TITLE
[db-sync] Enable sync for d_b_prebuilt_workspace and d_b_prebuilt_workspace_updatable

### PR DESCRIPTION
**Pull request by easyCZ**
## Related Issue(s)

* Depends on https://github.com/gitpod-io/gitpod/pull/13163
* Depends on https://github.com/gitpod-io/gitpod/pull/13164

And both need to be rolled out to production.

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by jankeromnes** [comment]
@easyCZ Please rebase this now that https://github.com/gitpod-io/gitpod/pull/13163 and https://github.com/gitpod-io/gitpod/pull/13164 have been merged. 🙏

**Comment by easyCZ** [comment]
> @easyCZ Please rebase this now that #13163 and #13164 have been merged. 🙏

Done. Tho it was not actually needed as the change is not directly dependant on code level. Which is a problem in itself as it shows we're not actually testing db-sync against the migrations

**Comment by easyCZ** [comment]
Migrations have been applied, we can now proceed with this change.

/unhold

**Review by geropl — APPROVED** [review]
LGTM!

**Pull request merged**
