### PR TITLE
Normalize log in and log out verbs

### PR DESCRIPTION
**Pull request by gtsiolis**
## Description

This will update and normalize log in an log out verbs, see [relevant discussion](https://gitpod.slack.com/archives/C01KGM9DVRC/p1682689148308139) (internal).

Cc @mbrevoort @atduarte @lucasvaltl @svenefftinge 

## Related Issue(s)

Fixes #

## How to test
1. Once you log in, go to the user menu and notice the new _Log out_ verb.
2. Inside an org, after adding an OIDC client, open the more actions menu and notice the new _Log in_ verb.

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - gt-normalif4dddf2da2</li>
	<li><b>🔗 URL</b> - <a href="https://gt-normalif4dddf2da2.preview.gitpod-dev.com/workspaces" target="_blank">gt-normalif4dddf2da2.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
</ul>

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [X] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

/hold

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]

**Comment by gtsiolis** [comment]
Thanks for taking a look, @easyCZ. 🌮 🌮 

/unhold

**Comment by easyCZ** [comment]
It's sometimes useful to wait for the build to pass before unholding, as when the PR is in a state where either the build is incomplete, or it fails, it blocks the merge Q for others. Sadly we've not yet fixed that..

**Comment by gtsiolis** [comment]
Ah, ok—didn't know that. Thanks for the insight, @easyCZ. Let me hold this back again and will unhold after the build.

/hold

**Comment by gtsiolis** [comment]
Removing hold.

/unhold

**Pull request merged**
