### PR TITLE
Update copyright of generated file

### PR DESCRIPTION
**Pull request by mustard-mh**
## Description

(This file has no cache and will be generated every time)

To fix GH Action https://github.com/gitpod-io/gitpod/actions/runs/3825836824/jobs/6509111555 and other `gitpod-protocol` related leeway builds

## Related Issue(s)

Fixes #

## How to test

No need

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by akosyakov** [comment]
@mustard-mh build seems to fail

**Comment by mustard-mh** [comment]
@akosyakov build succeed

**Comment by akosyakov** [comment]
I wonder do we need copyright for auto generated files at all or what strategy should be here? Maybe we should not commit it? cc @meysholdt

**Review by easyCZ — APPROVED** [review]

**Pull request merged**
