### PR TITLE
re-enable PVC support

### PR DESCRIPTION
**Pull request by sagor999**
## Description

This PR contains two fixes:
1. Re-enables PVC support in ws-manager
2. Fixes PVC not working when restoring from prebuild.

## Related Issue(s)

Fixes #

Needs following merged and deployed into webapp prod prior to merging:
:heavy_check_mark: https://github.com/gitpod-io/gitpod/pull/12105
:heavy_check_mark: https://github.com/gitpod-io/gitpod/pull/12165
:heavy_check_mark: https://github.com/gitpod-io/gitpod/pull/12180

## Release Notes

```release-note
none
```

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@sagor999: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by kylos101** [comment]
@sagor999 should you undo [this](https://github.com/gitpod-io/gitpod/commit/1fd1173cf1d5f7cfe036b173b85fca5805d73cd1) too? cc: @aledbf

**Comment by sagor999** [comment]
@kylos101 that's already done. check commits in this PR.

**Review by utam0k — APPROVED** [review]

**Comment by kylos101** [comment]
@sagor999 added to our project and set to awaiting deployment

**Pull request merged**
