### PR TITLE
[theia] add css/htm language features extensions

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

`@theia/monaco` does not provide smartness for css/html by default anymore: https://github.com/eclipse-theia/theia/pull/7972 so we should consume them as VS Code extensions.

#### How to test

Check html/css language smartness: http://akosyakov-code-highlighting-emmet-2444.staging.gitpod-dev.com/#https://github.com/vuejs/vue-router

### CODE REVIEW

**Review by AlexTugarev — APPROVED** [review]

**Comment by akosyakov** [comment]
I struggle to find a good version of css language features extension. All of them is failing with `Deprecated` undefined and cannot provide complete support. We need a new version of Theia to make it work.

**Comment by svenefftinge** [comment]
Can we build our own extension?

**Comment by akosyakov** [comment]
> Can we build our own extension?

looking how can i work it around in Gitpod Theia, maybe brining support via Monaco back

**Comment by akosyakov** [comment]
I patched the plugin host process for now to fix completions compatibility

**Pull request merged**
