### PR TITLE
We use the install-values.yaml to attach the node affinity

### PR DESCRIPTION
**Pull request by jenting**
## Description

We see in the production cluster, the rebuild and workspace pod with duplicate node affinity rule.
```yaml
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gitpod.io/workload_workspace_headless
            operator: Exists
          - key: gitpod.io/ws-daemon_ready_ns_default
            operator: Exists
          - key: gitpod.io/registry-facade_ready_ns_default
            operator: Exists
          - key: gitpod.io/workspace-class
            operator: In
            values:
            - default
          - key: gitpod.io/workload_workspace_headless
            operator: Exists
          - key: gitpod.io/ws-daemon_ready_ns_default
            operator: Exists
          - key: gitpod.io/registry-facade_ready_ns_default
            operator: Exists
```

## Related Issue(s)

Fixes #

## Release Notes

```release-note
None
```

## Documentation

None

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@jenting: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jenting** [comment]
Not sure if this is the right way. Wait for @aledbf to review

**Comment by aledbf** [comment]
@jenting no, we cannot remove the affinity here because ws-daemon and registry-facade rely on the values.

We need to remove the duplication in the ops repo.

**Comment by jenting** [comment]
> @jenting no, we cannot remove the affinity here because ws-daemon and registry-facade rely on the values.
> 
> We need to remove the duplication in the ops repo.

Thanks for the explanation 🙏

**Pull request closed without merging**
