### PR TITLE
[dashboard] add modal_dismiss tracking event

### LINKED ISSUE #9790: Analytics: Track modal dismissal
Currently, when triggering a modal close, the `dashboard_clicked` event is triggered. However, for modal dismissing there is no label property applied, only the `path` property, making it hard to distinguish between different clicks to dismiss a modal. 

image

**Proposal** Implement a `modal_dismiss` tracking event that triggers when a modal is closed in any manner: 

1. Use of `esc` button
2. Close via the `X` button
3. etc

Relates to this PR: https://github.com/gitpod-io/gitpod/pull/9663 as part of the epic https://github.com/gitpod-io/gitpod/issues/6707

### PR DESCRIPTION
**Pull request by mustard-mh**
## Description

Add `modal_dismiss` tracking event to clarify how and where this modal dismiss. 

- `manner`: how this modal dismiss, value can be one of `esc` `enter` `x`
- `specify`: specify a key if having the same title and window.location
- `title`: title of <Modal>, that needs to do with `TODO` in this PR

Need preview PR to be merged first
- [x] https://github.com/gitpod-io/gitpod/pull/10131

## Related Issue(s)

Fixed #9790

## How to test

Go to [segment](https://app.segment.com/gitpod/sources/staging_untrusted/debugger) to check if `modal_dismiss` event sent correctly.

1. Go to /workspaces press `enter` after IDE select modal display, see if `modal_dismiss` data like
```js
{
  userId: 'a5ef63c4-53fb-4554-ad4b-4b985349e4ee',
  event: 'modal_dismiss',
  properties: {
    manner: 'enter',
    path: '/workspaces',
    specify: 'workspace_list',
    title: 'Select Editor'
  }
}
```
2. Reset ideSettings of user (or delete user and re-create one), go with `/#github.com/gitpod-io/template-sveltejs` and press `esc` to see if `modal_dismiss` data `manner=esc specify=workspace_start`

The tests above are checking for `specify` of IDE select modal. We can test more `manner` in /variables to easily create a modal here

## Release Notes

```release-note
NONE
```

## Documentation

- [x] /werft analytics=segment|TEZnsG4QbLSxLfHfNieLYGF4cDwyFWoe

### CODE REVIEW

**Comment by mustard-mh** [comment]
@iQQBot Could you help review/test this?

**Comment by geropl** [comment]
build error:
> Validating configuration
> STDERR: Error: error loading config: error unmarshaling JSON: while decoding JSON: json: unknown field "usage"

@mustard-mh  This requires a rebase

**Review by geropl — APPROVED** [review]
Approving because the code looks good and works.

/hold in case you want to react on [this comment](https://github.com/gitpod-io/gitpod/pull/10132#issuecomment-1140841675)

**Comment by mustard-mh** [comment]
> @mustard-mh I tested, and it seems to work as expected.
> 
> But I noticed that it does not seem to pick up modal dismisses when I regularly click the button. Is that by intention? 🤔 If yes: Wouldn't it be easier for later analysis to capture `modal_closure` with `maner: esc | enter | x | accept` instead, to cover all ways a user can "escape" a modal?

👍 Good point, I will go with it. cc @loujaybee

**Comment by mustard-mh** [comment]
> 👍 Good point, I will go with it. cc @loujaybee

@geropl @loujaybee Sometimes when we click on buttons that don't necessarily make the modal disappear. For example, if we need to wait for the result of a request, and the request fails, the modal does not disappear, but waits for the user to make a second click. So we could probably provide a common method to call in `Modal.tsx` instead of directly adding?

Or maybe just go with this PR, and make changes in the future if needed?

**Comment by geropl** [comment]
> Or maybe just go with this PR, and make changes in the future if needed?

@mustard-mh Fine with me! Just wanted to bring it up in case it's "quick and easy". :+1:

**Pull request merged**
