### PR TITLE
Improve organization members filter

### PR DESCRIPTION
**Pull request by gtsiolis**
## Description

UX updates for the organization members page, improving the role filter.

Extracting some first ideas from the [relevant frame](https://www.figma.com/file/r480CWajzC4JJlZmdDiJen/Projects-V2-(Sandbox)?type=design&node-id=1163%3A1302&mode=design&t=K57SriYQSPOBODJy-1) (internal). Cc @loujaybee 

Next steps could include:
1. Dropping the table header
2. Removing the joined date information and move that to an audit log
3. Move the role switch to the context menu to avoid accidental changes and arrow element repetition

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖 Generated by Copilot at 23ef648</samp>

Improved the organization dashboard UI and added a role filter feature. The changes in `Members.tsx` enhance the user experience and clarity of managing team members and their permissions.

</details>

| BEFORE | AFTER |
|--------|--------|
| Screenshot 2023-08-10 at 11 45 47 (2) | Screenshot 2023-08-10 at 12 01 34 (2) |

## Related Issue(s)

Fixes #

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - gt-improvec57208e64c</li>
	<li><b>🔗 URL</b> - <a href="https://gt-improvec57208e64c.preview.gitpod-dev.com/workspaces" target="_blank">gt-improvec57208e64c.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - gt-improve-org-members-filter-gha.15049</li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [X] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by mustard-mh** [comment]
UX LGTM, but when our logic of `loading` is incorrect it should show only when we're loading data. Right now it will show loading when there's no one in the list, and if I'm the only owner filter with members, it will show loading
 https://github.com/gitpod-io/gitpod/blob/23ef6485ecf123582d0560ca0b59dd814ba8fd38/components/dashboard/src/teams/Members.tsx#L165

**Comment by gtsiolis** [comment]
Ah, nice catch, @mustard-mh. ⚾ 

We did replace that part in https://github.com/gitpod-io/gitpod/pull/16417 to avoid showing the _No members found_ message during load time, as we do with other pages like access tokens, etc.

Could you approve to merge this as the described issue is unrelated to the changes here and already existed before the changes? 🏓 

I've opened EXP-419 to keep track of this.

**Review by mustard-mh — APPROVED** [review]
LGTM

**Comment by gtsiolis** [comment]
Thanks, @mustard-mh! 🌮

**Pull request merged**
