### PR TITLE
Web responsiveness

### PR DESCRIPTION
**Pull request by krystofex**
## Description

- Projects page grid columns breakpoints

## How to test

- check `/projects` and `/projects/<some-project>/configure` page and scale down browser window

## Release Notes

```release-note
Responsive grids on:
- /projects
- /projects/<some-project>/configure
```

### CODE REVIEW

**Comment by roboquat** [comment]
@krystofex: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankeromnes** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankeromnes` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by krystofex** [comment]
# Visual changes:
## Projects page
### Before:
image
### After:
image
image
## Configure project page
### Before:
image
### After: 
image

**Comment by jankeromnes** [comment]
Hey, this is awesome! Thank you so much for this @krystofex. 🙏

I'll take a closer look now. 👀

Related question: Do you remember signing a Committer License Agreement for Gitpod contributions yet? (If not, I think @meysholdt can send you a quick docusign)

**Review by jankeromnes — APPROVED** [review]
Code looks great, and I've tested this on mobile (Pixel 5) and on tablet (classic iPad), both in portrait and landscape, and I must say this works like a charm! 🎯 ✨ ❤️

(This contribution also makes me super happy personally because I'm a frequent mobile user and I've wanted more responsiveness from our dashboard for many months now 😅)

---

_Somewhat off-topic_

I wonder -- what has been your experience so far using `grid` for responsiveness? This is my first time seeing `grid` used this way, and I quite like it. In the past I've mostly been using `flex` for responsiveness (e.g. letting a `row` break naturally according to screen size, with a reasonable `min-width` on its elements, or sometimes changing a `flex` `row` to a `flex` `column` when the screen is too narrow).

At first sight, `grid` seems a bit more precise (i.e. no need to fiddle with `min-width` to get the layout you want on each screen size -- you can directly set the number of columns and be done), but maybe it's a bit less "generic"? (I.e. seems like it needs at least two custom breakpoints to fit every screen size)

Anyway, simple precise control does sound more reasonable than aiming for a "super-generic layout formula". I just hope we'll find something like "common patterns" across our many dashboard pages, in order to remove the need for custom responsive work on every page. 💭

---

Good to merge as is, as soon as the CLA situation is cleared. 🚀

/approve no-issue
/lgtm
/hold

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 2a479ad4e68a407627f6ac78775550e60bdd8c69</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7629#pullrequestreview-854094329" title="Approved">jankeromnes</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/7629#pullrequestreview-854094329" title="Approved">jankeromnes</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by krystofex** [comment]
@jankeromnes I haven't sign  a Commiter license agreement yet

**Comment by meysholdt** [comment]
> Good to merge as is, as soon as the CLA situation is cleared. 🚀

hi @krystofex, I've sent a CLA via email/DocuSign your way.

**Comment by meysholdt** [comment]
thx @krystofex, I have received your signed CLA!

**Comment by jankeromnes** [comment]
Awesome, many thanks @meysholdt and @krystofex!

We could now merge this, but unfortunately a conflict snuck in while we were busy with the CLA. @krystofex could you please rebase your commit? 🙏

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by krystofex** [comment]
@jankeromnes I've resolved the conflict, can you please check it out?

**Comment by jankeromnes** [comment]
Sure, many thanks!

/werft run

**Comment by jankeromnes** [comment]
Reroll 🎲

/werft run with-clean-slate-deployment

**Comment by jankeromnes** [comment]
Still looks good, still works great! 🎉

/unhold
/lgtm

**Comment by gtsiolis** [comment]
Great MVC (minimum viable change) work! 🔮 

Thanks @krystofex for contributing, @jankeromnes for reviewing, and @meysholdt for helping with the CLA process! 🏀

**Review by jankeromnes — APPROVED** [review]

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7629#issuecomment-1015653089" title="LGTM">aledbf</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7629#pullrequestreview-854094329" title="Approved">jankeromnes</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/7629#pullrequestreview-854094329" title="Approved">jankeromnes</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by aledbf** [comment]
@jankeromnes I see an error in Tide
`"PR is unmergable. Do the Tide merge requirements match the GitHub settings for the repo? This branch can't be rebased"`
I will remove the lgtm to see this allows the merge of pending PRs in the merge queue

**Comment by aledbf** [comment]
@krystofex please rebase and squash the PR to be able to merge it. Thanks!

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7629#issuecomment-1015653089" title="LGTM">aledbf</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7629#pullrequestreview-854094329" title="Approved">jankeromnes</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **loujaybee**, **mrsimonemms** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @loujaybee @mrsimonemms` in a comment when ready.

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/7629#pullrequestreview-854094329" title="Approved">jankeromnes</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [aledbf,jankeromnes]
- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [jankeromnes]
- ~~[components/ee/payment-endpoint/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/payment-endpoint/OWNERS)~~ [jankeromnes]
- ~~[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)~~ [jankeromnes]
- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [jankeromnes]
- ~~[components/proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/proxy/OWNERS)~~ [jankeromnes]
- ~~[components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/registry-facade/OWNERS)~~ [aledbf]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [jankeromnes]
- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**
- ~~[components/workspacekit/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/workspacekit/OWNERS)~~ [aledbf]
- ~~[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)~~ [aledbf]
- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [aledbf]
- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**
- ~~[installer/pkg/components/proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/proxy/OWNERS)~~ [jankeromnes]
- ~~[installer/pkg/components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/registry-facade/OWNERS)~~ [aledbf]
- ~~[installer/pkg/components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-daemon/OWNERS)~~ [aledbf]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7629#issuecomment-1015653089" title="LGTM">aledbf</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7629#pullrequestreview-854094329" title="Approved">jankeromnes</a>*


*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:


Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by filiptronicek** [comment]
Ooopsie rebasing doopsie, the history got kind of messed up and @krystofex made #7665

**Pull request closed without merging**
