### PR TITLE
tezts

### PR DESCRIPTION
**Pull request by filiptronicek**
## Description
This is a placeholder PR for testing self-hosted with VS Code Desktop :).

## Related Issue(s)

Fixes #

## Release Notes

```release-note
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@filiptronicek: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by filiptronicek** [comment]
Hi @nandajavarma 👋, could you help me with setting up a self-hosted instance from this PR (or even from `main`, does not matter) 🙏? I've been trying with different werft flags but can't get a URL to show up in the Results tab. Am I missing something? 👀

**Comment by nandajavarma** [comment]
/werft run with-sh-preview

Hey @filiptronicek, so the logic to run self-hosted preview is currently outside the main build logic. Hence what the main build does is, run a separate werft job which you will be able to see in the werft dashboard. Once the second job starts, you will also see it listed in `Checks` section at the bottom of the PR. I will re-trigger the job to point you to it.

**Comment by filiptronicek** [comment]
## Release Notes
- [#13376](https://github.com/gitpod-io/gitpod/pull/13376) - TESTING RELEASE NOTE <Contributors usernames="filiptronicek,nandajavarma" />

**Comment by filiptronicek** [comment]
### Release Notes
- [#13376](https://github.com/gitpod-io/gitpod/pull/13376) - TESTING RELEASE NOTE <Contributors usernames="filiptronicek,nandajavarma" />

**Comment by filiptronicek** [comment]
### Release Notes
- [#13376](https://github.com/gitpod-io/gitpod/pull/13376) - TESTING RELEASE NOTE <Contributors usernames="filiptronicek,nandajavarma" />


### Category
Other (no specific category)

**Comment by filiptronicek** [comment]
### Release Notes
- [#13376](https://github.com/gitpod-io/gitpod/pull/13376) - TESTING RELEASE NOTE <Contributors usernames="filiptronicek,nandajavarma" />


### Category
Other (no specific category)

**Comment by filiptronicek** [comment]
### Release Notes
- [#13376](https://github.com/gitpod-io/gitpod/pull/13376) - TESTING RELEASE NOTE <Contributors usernames="filiptronicek,nandajavarma" />


### Category
Other (no specific category)

**Comment by filiptronicek** [comment]
### Release Notes
- [#13376](https://github.com/gitpod-io/gitpod/pull/13376) - TESTING RELEASE NOTE <Contributors usernames="filiptronicek,nandajavarma" />


### Category
Other (no specific category)

**Pull request closed without merging**
