### PR TITLE
[public-api] Define DeleteWorkspace

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

Define DeleteWorkspace RPC. Only proto changes.

Used in https://github.com/gitpod-io/gitpod/pull/15555

## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by easyCZ** [comment]
I'll need to do a pre-PR which updates the license header to remove the extra changes.

**Comment by easyCZ** [comment]
The bulk change of copyright is in https://github.com/gitpod-io/gitpod/pull/15557

**Review by ArthurSens — APPROVED** [review]

**Review by geropl — APPROVED** [review]
:heavy_check_mark:

**Pull request merged**
