### PR TITLE
[#2658] Basic integration tests

### PR DESCRIPTION
**Pull request by geropl**
Fixes https://github.com/gitpod-io/gitpod/issues/2658 to some extend, see [here](https://github.com/gitpod-io/gitpod/issues/2658#issuecomment-793574031) for caveats.

The changes include:
 - werft job (core)
 - werft job (io, see companion PR)
 - tests now are now runnable against all environments (e.g., devstaging, staging and prod)
 - you can choose a `user` to run with (for now, until we have the "setup GitHub/GitLab test user (credentials)" story solved
 - basic context/Git integration tests

### Companion PRs:
 - https://github.com/gitpod-com/gitpod/pull/5177

- [ ] /werft with-integration-tests=true

### CODE REVIEW

**Comment by geropl** [comment]
> +1 started the job as gitpod-build-gpl-2658-int-tests.61

Did not work due to the preview env not being ready it seems.

**Comment by geropl** [comment]
This is a manually triggered run on devstaging that went fine (:crossed_fingers: ): https://werft.gitpod-dev.com/job/gitpod-run-integration-tests-gpl-2658-int-tests.42

**Review by csweichel — APPROVED** [review]
LGTM

**Pull request merged**
