### PR TITLE
Installer Helm wrapper for Docker Registry

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Related Issue(s)

Fixes #

## Release Notes

```release-note
```

### CODE REVIEW

**Comment by roboquat** [comment]
@MrSimonEmms: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **csweichel**, **geropl** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @csweichel @geropl` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/blobserve/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/blobserve/OWNERS)**
- **[components/content-service/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service/OWNERS)**
- **[components/content-service-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service-api/OWNERS)**
- **[components/ee/agent-smith/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/agent-smith/OWNERS)**
- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/image-builder-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder-api/OWNERS)**
- **[components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/registry-facade/OWNERS)**
- **[components/registry-facade-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/registry-facade-api/OWNERS)**
- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**
- **[components/ws-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-proxy/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by MrSimonEmms** [comment]
This is a work in progress example of how to install third-party Helm charts using the installer (I've used the docker-registry one as it's the simplest).

Originally, @aledbf suggested using the method that [linkerd uses to install Jaeger](https://github.com/linkerd/linkerd2/blob/34dc22909fd451004f1089b263aef66a42be1c2e/jaeger/cmd/install.go), but this approach would require us to maintain the Helm charts which I suspect is an overhead we don't want.

What I've done with this is bundled the `Chart.yaml` and `values.yaml` file (with values we've already set) and then written a Helm wrapper to deploy them. Although this uses Helm, it doesn't require Helm to be installed as a dependency for users.

There's still a bit of work to be done, but I'm submitting this as a proposal on how to do things. We'll probably need to add in more of the Helm CLI functionality (and a way of uninstalling) as well.

**Comment by aledbf** [comment]
> Originally, @aledbf suggested using the method that linkerd uses to install Jaeger, but this approach would require us to maintain the Helm charts which I suspect is an overhead we don't want.


Sorry, I should have been more explicit. What I liked was the use of the helm library, not copying the charts in the project.

**Comment by aledbf** [comment]
> What I've done with this is bundled the Chart.yaml and values.yaml file (with values we've already set) and then written a Helm wrapper to deploy them

This makes sense

**Comment by MrSimonEmms** [comment]
@aledbf excellent. Looks like I stumbled upon what you were thinking. I'll do a bit more work on it next week with a more complex dependency (probably the MySQL one) and see how that works with the pattern I've done.

I also need to have a think about how to implement a dependency between the `render` and `docker-registry` commands - I think there may be a cyclic dependency between the certificates (I need to do a bit more investigation to see if I've understood it correctly)

**Pull request closed without merging**
