### PR TITLE
[pvc] add a test for non gitpodified repo

### LINKED ISSUE #13591: [PVC] integration test for testing .gitpod.yml using incorrect repo
### Bug description

Currently we test if opening a repo without .gitpod.yml works when using PVC approach.
It was not due to this: https://github.com/gitpod-io/gitpod/issues/13531
Turns out integration test is running against gitpod-io/empty repo, which does not have any git history.

### Steps to reproduce

n\a

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

#7901

### PR DESCRIPTION
**Pull request by sagor999**
## Description

Add integration test that tests PVC against non gitpodified repo.

## Related Issue(s)

Fixes #13591

## Release Notes

```release-note
none
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-integration-tests=workspace
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@sagor999: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by jenting — APPROVED** [review]
/hold

**Comment by sagor999** [comment]
This depends on this https://github.com/gitpod-io/gitpod/pull/13552 merged first, so holding it in non ready for review until then.

**Comment by jenting** [comment]
CI pass

**Comment by jenting** [comment]
> This depends on this #13552 merged first, so holding it in non ready for review until then.

The PR merged

/unhold

**Pull request merged**
