### PR TITLE
Support custom CA certificates in Helm

### LINKED ISSUE #2615: [Self-Hosted] Support for own CA certificates
### Describe the bug
Can't get Oauth working with self-hosted gitpod and gitlab instance. 

GitPod (version: 0.6.0-beta1): self-hosted deployment in kubernetes 
GitLab: self-hosted premium

image

#### Helm values
```yaml
# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

# This field must be set to your domain name. Leaving it set to its default value will result in
# a non-functional installation.
hostname: {{ gitpod_hostname }}
ingressMode: hosts

# If you have a static IP that your domain resolves to, set it here.
# Leaving this field set to its default value is fine. Kubernetes will assign you an IP address
# during deployment.

components:
  proxy:
    loadBalancerIP: {{ gitpod_proxy_loadbalancer_ip }}

  workspace:
    template:
      default:
        spec:
            dnsConfig:
            nameservers:
            - 10.26.103.10
            - 10.26.103.11
            dnsPolicy: ClusterFirst

# Gitpod needs at least one auth provider to allow users to log in.
# The auth providers below are examples only. Please change/remove them to fit your installation.
authProviders:
- id: "{{ gitpod_authProviders_gitlab_id }}"
  host: "{{ gitpod_authProviders_gitlab_host }}"
  protocol: "https"
  type: "GitLab"
  oauth:
    clientId: "{{ gitpod_authProviders_gitlab_oauth_client_id }}"
    clientSecret: "{{ gitpod_authProviders_gitlab_oauth_client_secret }}"
    callBackUrl: "https://{{ gitpod_hostname }}/auth/{{ gitpod_authProviders_gitlab_host }}/callback"
    settingsUrl: "https://{{ gitpod_authProviders_gitlab_host }}/profile/applications"

# RBAC is enabled by default. If your cluster does not use RBAC, set this flag to false so that
# we do not attempt to install PodSecurityPolicies and the likes.
installPodSecurityPolicies: true

#certificatesSecret: {}
certificatesSecret:
  secretName: proxy-config-certificates
```

#### GitPod Server Logs
```json
{
    "component": "server",
    "severity": "INFO",
    "time": "2020-12-22T09:15:13.772Z",
    "environment": "production",
    "region": "local",
    "message": "Request getFeaturedRepositories unsuccessful: 401/\"User is not authenticated. Please login.\"",
    "payload": {
        "method": "getFeaturedRepositories",
        "args": [
            null,
            {
                "_isCancelled": false
            }
        ]
    }
}
{
    "component": "server",
    "severity": "INFO",
    "time": "2020-12-22T09:15:15.300Z",
    "environment": "production",
    "region": "local",
    "context": {
        "sessionId": "c67e1fc1-339d-4fbc-b170-328dc0e0645f"
    },
    "message": "(Auth) User started the login process",
    "payload": {
        "login-flow": true,
        "clientInfo": {
            "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19041",
            "fingerprint": "36489166f56651e48e01d3a6c34ae05e7f770abd2329a1aed83832dd0530f86c"
        }
    }
}
{
    "component": "server",
    "severity": "INFO",
    "time": "2020-12-22T09:15:18.746Z",
    "environment": "production",
    "region": "local",
    "message": "Auth Provider Callback. Path: /auth/gitlab.garrison.local/callback"
}
{
    "component": "server",
    "severity": "INFO",
    "time": "2020-12-22T09:15:18.746Z",
    "environment": "production",
    "region": "local",
    "context": {},
    "message": "(Auth-With-gitlab.garrison.local) OAuth2 callback call. ",
    "payload": {
        "clientInfo": {
            "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19041",
            "fingerprint": "36489166f56651e48e01d3a6c34ae05e7f770abd2329a1aed83832dd0530f86c"
        },
        "authProviderId": "garrison-gitlab",
        "requestUrl": "/auth/gitlab.garrison.local/callback?code=1bf718b9ef0325287fd89ae7fdb3bf2b045942e2135d6caeaaf67be8ddfbb8fb"
    }
}
{
    "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
    "serviceContext": {
        "service": "server",
        "version": "0.6.0-beta1"
    },
    "stack_trace": "InternalOAuthError: Failed to obtain access token\n    at GenericOAuth2Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:379:17)\n    at /app/node_modules/passport-oauth2/lib/strategy.js:166:45\n    at patchedCallback (/app/node_modules/@gitpod/server/dist/src/auth/generic-auth-provider.js:837:28)\n    at /app/node_modules/oauth/lib/oauth2.js:191:18\n    at ClientRequest.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:162:5)\n    at ClientRequest.emit (events.js:315:20)\n    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket.EventEmitter.emit (domain.js:483:12)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
    "component": "server",
    "severity": "ERROR",
    "time": "2020-12-22T09:15:18.787Z",
    "environment": "production",
    "region": "local",
    "context": {},
    "message": "(Auth-With-gitlab.garrison.local) Redirect to /sorry from verify callback",
    "error": "InternalOAuthError: Failed to obtain access token\n    at GenericOAuth2Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:379:17)\n    at /app/node_modules/passport-oauth2/lib/strategy.js:166:45\n    at patchedCallback (/app/node_modules/@gitpod/server/dist/src/auth/generic-auth-provider.js:837:28)\n    at /app/node_modules/oauth/lib/oauth2.js:191:18\n    at ClientRequest.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:162:5)\n    at ClientRequest.emit (events.js:315:20)\n    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket.EventEmitter.emit (domain.js:483:12)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
    "payload": {
        "authFlow": {
            "host": "gitlab.garrison.local",
            "returnTo": "https://gitpod.garrison.local/workspaces/",
            "returnToAfterTos": "https://gitpod.garrison.local/api/login/?returnTo=https%3A%2F%2Fgitpod.garrison.local%2Fworkspaces%2F&host=gitlab.garrison.local"
        },
        "clientInfo": {
            "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19041",
            "fingerprint": "36489166f56651e48e01d3a6c34ae05e7f770abd2329a1aed83832dd0530f86c"
        },
        "authProviderId": "garrison-gitlab",
        "err": "InternalOAuthError: Failed to obtain access token\n    at GenericOAuth2Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:379:17)\n    at /app/node_modules/passport-oauth2/lib/strategy.js:166:45\n    at patchedCallback (/app/node_modules/@gitpod/server/dist/src/auth/generic-auth-provider.js:837:28)\n    at /app/node_modules/oauth/lib/oauth2.js:191:18\n    at ClientRequest.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:162:5)\n    at ClientRequest.emit (events.js:315:20)\n    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket.EventEmitter.emit (domain.js:483:12)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
    }
}
{
    "component": "server",
    "severity": "INFO",
    "time": "2020-12-22T09:15:19.101Z",
    "environment": "production",
    "region": "local",
    "message": "Request getLoggedInUser unsuccessful: 401/\"User is not authenticated. Please login.\"",
    "payload": {
        "method": "getLoggedInUser",
        "args": [
            null,
            {
                "_isCancelled": false
            }
        ]
    }
}
```

#### GitPod Server Error
``` js
InternalOAuthError: Failed to obtain access token
    at GenericOAuth2Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:379:17)
    at /app/node_modules/passport-oauth2/lib/strategy.js:166:45
    at patchedCallback (/app/node_modules/@gitpod/server/dist/src/auth/generic-auth-provider.js:837:28)
    at /app/node_modules/oauth/lib/oauth2.js:191:18
    at ClientRequest.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:162:5)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

### PR DESCRIPTION
**Pull request by jgallucci32**
Adds support to Helm charts for custom CA certificates. Approach derived from from https://github.com/goharbor/harbor-helm project for variable names and formatting.

Fixes #2615 

Signed-off-by: jgallucci32 <john.gallucci.iv@gmail.com>

### CODE REVIEW

**Comment by jgallucci32** [comment]
@corneliusludmann @geropl @stefanstoeckigt Please review this PR for custom CA certs.

**Comment by corneliusludmann** [comment]
@jgallucci32 Thanks a lot for your contribution. I really appreciate this! I'm currently organizing a review. Thanks for your patience and sorry for the delay.

**Comment by meysholdt** [comment]
hi @jgallucci32, thank you for your contribution!

IIRC `/etc/ssl/certs/ca-certificates.crt` is a generated file and the mount you're introducing overrides it, thus not only adding new certs but also removing pre-existing certs. Can this cause trouble? 

We haven't documented it yet, but we'll need a CLA before we can merge this, I'll reach out to you about it via email.

**Comment by jgallucci32** [comment]
@meysholdt Yes you are correct. It is expected to be a full bundle inclusive of your custom certs. This is typically done by adding your custom certs to a Linux OS (i.e. /etc/pki/ca-trust/source/anchors) and running `update-ca-certificates` to generate a full bundle to be used by Gitpod.

**Comment by stefanstoeckigt** [comment]
@jgallucci32, the ca volume and NODE_EXTRA_CA_CERTS should also be added to the [workspace-template.yaml](https://github.com/gitpod-io/gitpod/blob/master/chart/templates/workspace-template.yaml). This will allow the workspace pod to have access to the ca. Without the NODE_EXTRA_CA_CERTS in the workspace pod you wont be able to download any extensions from within the workspace.

**Comment by jgallucci32** [comment]
@stefanstoeckigt Interesting I hadn't thought about adding it there. We just repackaged the public `workspace-full` image with the `ENV` added to Dockerfile and certs moved over with `COPY` as this is typical for most environments where custom CA certs are used. In addition to `NODE_EXTRA_CA_CERTS` we also found that `REQUESTS_CA_BUNDLE` was required as well for `python pip` to work. I'm sure we will discover more as we have only just scratched the surface of all the software packages contained in the full image.

Do you have a recommendation as to where to add it in `workspace-template.yaml`? I think I would start down the tree of `spec:` on Line 20, but there is very little there I don't want to risk breaking anything.

**Comment by stefanstoeckigt** [comment]
@jgallucci32, i think adding it under the coreWorkspaceConfig section, like below maybe.

```yaml
{{- define "coreWorkspaceConfig" }}
{{- $comp := .comp -}}
spec:
 {{- if $comp.pullSecret }}
  imagePullSecrets:
  - name: {{ toYaml $comp.pullSecret.secretName }}
  {{- end }}
{{- if .Values.caBundleSecretName }}
   containers:
     - name: workspace
        volumeMounts:
{{ include "gitpod.caBundleVolumeMount" . | indent 8 }}
        env:
        - name: NODE_EXTRA_CA_CERTS
           value: /etc/ssl/certs/ca-certificates.crt
   volumes:
{{ include "gitpod.caBundleVolumeMount" . | indent 8 }}
{{- end }}
```

**Comment by jgallucci32** [comment]
@meysholdt @corneliusludmann what are your thoughts about also included the proposed changes for `workspace-template.yaml`?

**Comment by iamulya** [comment]
In image-builder-deployment.yaml, {{- if .Values.caBundleSecretName }} should be replaced with {{- if **$**.Values.caBundleSecretName }} - to reference the global scope.

**Review by corneliusludmann — CHANGES_REQUESTED** [review]
Hi @jgallucci32,

First, an apology that we've been so slow with your great PR. Internally, we are not yet so well attuned to the processing of community PRs. But we will get better. I promise! :smiley:

I left a couple of comments. Please have a look.

For the `workspace-template.yaml` file, I think it makes sense to add the custom CA as well. This diff works for me:
```diff
diff --git a/chart/templates/workspace-template.yaml b/chart/templates/workspace-template.yaml
index 80beebb3..a012a84b 100644
--- a/chart/templates/workspace-template.yaml
+++ b/chart/templates/workspace-template.yaml
@@ -10,6 +10,19 @@ spec:
   imagePullSecrets:
   - name: {{ toYaml $comp.pullSecret.secretName }}
   {{- end }}
+  {{- if .gp.caBundleSecretName }}
+  containers:
+  - name: workspace
+    volumeMounts:
+{{ include "gitpod.caBundleVolumeMount" . | indent 4 }}
+    env:
+    - name: NODE_EXTRA_CA_CERTS
+      value: /etc/ssl/certs/ca-cert-gitpod.crt
+    - name: REQUESTS_CA_BUNDLE
+      value: /etc/ssl/certs/ca-cert-gitpod.crt
+  volumes:
+{{ include "gitpod.caBundleVolume" .root | indent 2 }}
+  {{- end }}
 {{- end }}
 {{- define "coreWorkspaceAffinity" -}}
 {{- $comp := .comp -}}
```

I also suggest, that we add an empty `caBundleSecretName:` property to the `chart/values.yaml` file (probably below `certificatesSecret: …`). Thus, we have some kind of documentation that the configuration value exist.

If you don't have time for this PR right now, please let me know. Then I will gladly take over.

**Comment by jgallucci32** [comment]
@corneliusludmann Thanks for getting back, I'll try to make some time to put in the suggested changes. I'll run through our setup to verify the alternate location for the CA Bundle works without changes (other than the node.js env var). I've always thought you had to use the specific `ca-certificates.crt` bundle but I will verify this as soon as I can.

**Comment by jgallucci32** [comment]
@corneliusludmann I have good news and bad news. I did some preliminary testing on using a different file for the custom CA certs and validated all but the `ws-daemon` using the new configuration. The `blobserve`, `image-builder`, and `registry-facade` are what I assume to be using a Go library which honors any certs located in `/etc/ssl/certs` and as a result can work the way suggested. The `server` pod works because node.js allows for additional certs using the added environment variable (so in theory this could be anything in any directory).

The `ws-daemon` is a different story. Behind the scenes it is making Git client commands and git is a bit trickier to work with. I was able to find the variable `GIT_SSL_CAINFO` which when set to `/etc/ssl/certs/ca-cert-gitpod.crt` allows you to execute a shell into the container and run some git commands. It appears the Go code which is calling git does not honor this environment variable and throws the same error (to an unpatched system). It's possible there are other combos of env vars to set and I will experiment with those.

Long term, this is something the folks at Gitpod need to take into consideration. Option A (current PR) overwrites the bundled CA Certs making it more straightforward to fix certs, but requires all certs to be in the bundle. Option B (suggested change) uses a different CA bundle, but requires use of special environment variables for each client library needing to connect to an endpoint with a custom SSL cert. This method is more explicit, but does not guarantee the bundle can only contain additive certs as some client libraries when using an env var will completely ignore the local ca bundle, defeating the purpose of keeping the bundle to only what you need (node.js does it right with the "EXTRA" approach, but not all clients do this).

Here is the exact error I see in `ws-deamon` should we continue down the path of Option B.
```
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"cannot initialize workspace:
    github.com/gitpod-io/gitpod/content-service/pkg/initializer.InitializeWorkspace
        /tmp/build/components-ws-daemon--content-initializer.3b990f245ba910a11725fbc05699fcfcffc53d71/_deps/components-content-service--lib/pkg/initializer/initializer.go:345
  - git initializer:
    github.com/gitpod-io/gitpod/content-service/pkg/initializer.(*GitInitializer).Run
        /tmp/build/components-ws-daemon--content-initializer.3b990f245ba910a11725fbc05699fcfcffc53d71/_deps/components-content-service--lib/pkg/initializer/git.go:68
  - git clone https://gitlab.domain.local/gitpod/workspace-validation.git . failed (exit status 128): Cloning into '.'...
fatal: unable to access 'https://gitlab.domain.local/gitpod/workspace-validation.git/': SSL certificate problem: unable to get local issuer certificate
","level":"error","message":"content init failed","serviceContext":{"service":"content-initializer","version":""},"severity":"ERROR","time":"2021-03-07T21:29:10Z"}
```

**Comment by aledbf** [comment]
@jgallucci32 @corneliusludmann can we align with Kubernetes and use a TLS secret? 
Using the change proposed in https://github.com/gitpod-io/gitpod/pull/3199

If the secret contains a custom CA, it must be concatenated in the `tls.crt` field

**Comment by jgallucci32** [comment]
> @jgallucci32 @corneliusludmann can we align with Kubernetes and use a TLS secret?
> Using the change proposed in #3199
> 
> If the secret contains a custom CA, it must be concatenated in the `tls.crt` field

@aledbf Kubernetes TLS secrets are primarily used with TLS termination of Ingress resources and requires both a public certificate and private key during creation. Since a custom CA bundle only includes public certificates, it would not make sense to create a TLS secret where you would have to fake the private key in order to create the secret (which may cause issues)

Here is what happens when attempting to create a TLS secret for a CA bundle
```bash
$ kubectl create secret tls my-tls-secret --cert=/etc/ssl/certs/ca-certificates.crt
error: flag key is required
See 'kubectl create secret tls -h' for help and examples
```

**Comment by csweichel** [comment]
> The ws-daemon is a different story. Behind the scenes it is making Git client commands and git is a bit trickier to work with. I was able to find the variable GIT_SSL_CAINFO

Git also supports `GIT_SSL_CAPATH` which can point to a directory of ca certs. We could make that env var point to the CA certs available to ws-daemon. For example, adding the code below to https://github.com/gitpod-io/gitpod/blob/3b4ebc9bad536d6d2b7fa974249fba9aed118c44/components/ws-daemon/pkg/content/initializer.go#L201
```Go
// We need to tell Git where to find CA certs in case someone added custom CA certs
// to ws-daemon. We're re-using ws-daemon's /etc above.
spec.Process.Env = append(spec.Process.Env, "GIT_SSL_CAPATH=/etc/ssl/certs")
```

should do the trick.

**Comment by corneliusludmann** [comment]
> We could make that env var point to the CA certs available to ws-daemon. For example, adding the code below to

@csweichel: Thanks for the hint. I tried this, but this doesn't work. At first, I think we need to add this here instead:

https://github.com/gitpod-io/gitpod/blob/d7bede9fbd166828bf98b98e4119005d747eac00/components/content-service/pkg/git/git.go#L170

like:

```go
env = append(env, "GIT...=....")
```

However, I don't get [`GIT_SSL_CAPATH`  resp. `http.sslCAPath`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpsslCAPath) running. I tried it also directly in an Alpine Docker image but the config seems to be ignored. Don't know why. What works is `GIT_SSL_CAINFO` like this:

```go
	if stat, err := os.Stat("/etc/ssl/certs/ca-cert-gitpod.crt"); err == nil && stat.Size() > 0 {
		// We need to tell Git where to find CA certs in case someone added custom CA certs.
		env = append(env, "GIT_SSL_CAINFO=/etc/ssl/certs/ca-cert-gitpod.crt")
	}
```

but that breaks cloning from github.com (because it uses the `ca-cert-gitpod.crt` CA only).

**Comment by zazizou** [comment]
Hi guys,

Will this feature eventually integrated in the main branch one day ? Is there a plan for that ?

Thanks

Regards

**Comment by jgallucci32** [comment]
@zazizou This is still on my to-do list. This PR was written against version 0.6.0 so in addition to a rebase I am going to need to deploy the latest version in a test cluster to validate it still works as intended. I'm trying to get some time to do this as soon as I can.

**Comment by bmnave** [comment]
This is still needed.

**Comment by SirLemyDanger** [comment]
what about accepting the working solution with the complete bundle first, and only afterwards go for the sophiticated solution? This is a major blocker to use gitpod in internal networks.

**Comment by jgallucci32** [comment]
That is my plan with this MR. My preference is to expect a full bundle and replace the OS certs as that has less maintenance overhead. Anything more sophisticated should come later.

In terms of being blocked, there are workarounds which we’ve been running for 6 months without issue. If you need me to repost them here let me know.

Right now I’m working a complete redeploy as 0.10.0 no longer works on RHEL 8 due to Kernel 5.2 requirement. Looking to get this validated on Ubuntu.

**Comment by SirLemyDanger** [comment]
@jgallucci32 First, thanks a lot for your effort on this MR.

And yes, I would be interested in your workarounds.

**Comment by SirLemyDanger** [comment]
@corneliusludmann Is https://github.com/gitpod-io/gitpod/pull/4322 addressing/solving this issue?

**Comment by jgallucci32** [comment]
> @corneliusludmann Is #4322 addressing/solving this issue?

Looking at the PR it is solving a different problem. It looks like cert-manager is being implemented using its default setup of generating certificates from known sources (i.e. Letsencrypt). If it is being used to sign a self-signed or custom CA, then the certificate stores need to be updated using the methods outlined in this PR.

FYI, I am ready to work this PR but am stuck. 0.10.0 is the latest release but the master contains the changes for image-builder-mk3 which is something I cannot test. How do I deploy the latest helm chart for master? I only know how to deploy what is helm which is 0.10.0 currently.

**Comment by jgallucci32** [comment]
@SirLemyDanger See https://github.com/gitpod-io/gitpod/issues/2615#issuecomment-914334608 for `kubectl patch` commands to apply Custom CA certs to self-hosted Gitpod installation.

**Comment by MrSimonEmms** [comment]
Hi @jgallucci32. I've had a look at releasing from `main` rather than from the 0.10.0 Helm release. As we're currently moving away from Helm releases to releasing from `main` (and with an [Installer](https://github.com/gitpod-io/gitpod/tree/main/installer)), this is going to be a pain point until we have this work finished - for the record, this is currently my main focus, so hopefully it won't be for long.

The `image-builder-mk3:0.10.0` image is not published to the [self-hosted registry](https://github.com/gitpod-io/gitpod/blob/c5c7c6f9df9d52815a0bbac891a58da48e0838d6/.werft/build.ts#L141) There is an image published called `gcr.io/gitpod-io/self-hosted/image-builder-mk3@sha256:23fab89b745436e714d18df33f1bb4543541e3049ef51ea6aa148c58d4399b00`, but I'm not sure what the state of this is.

**Comment by jgallucci32** [comment]
@iQQBot I don't mind, I have no way to test this right now since the `main` branch has deviated from the 0.10.0 installer and the MK3 image builder needs to be fixed, but I can't test it.

I can certainly review your updated PR.

**Comment by gtsiolis** [comment]
Thanks for coming back to this @jgallucci32! @iQQBot feel free to cherry pick any of the commits from @jgallucci32 if needed and open a follow up PR for this. 🏀

**Pull request closed without merging**
