### PR TITLE
[JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)

### PR DESCRIPTION
**Pull request by roboquat**
## Description
This PR updates the Platform Version from JetBrains Backend Plugin (EAP) to the latest version.

## How to test
1. Open the preview environment generated for this branch
2. Choose the _Latest Release (Unstable)_ version of IntelliJ IDEA as your preferred editor
3. Start a workspace using this repository: https://github.com/gitpod-samples/spring-petclinic
4. Verify that the workspace starts successfully
5. Verify that the IDE opens successfully

## Release Notes
```release-note
NONE
```

## Werft options:
- [x] /werft with-preview
- [x] /werft with-large-vm
- [x] /werft with-integration-tests=jetbrains

_This PR was created automatically with GitHub Actions using [this](https://github.com/gitpod-io/gitpod/blob/main/.github/workflows/jetbrains-update-plugin-platform-template.yml) template._

### CODE REVIEW

**Review by mustard-mh — APPROVED** [review]
image
image

Looks good

**Review by akosyakov — APPROVED** [review]
weird, @mustard-mh already approved it

**Comment by mustard-mh** [comment]
> weird, @mustard-mh already approved it

Turn out that we have added `hold` label in action https://github.com/gitpod-io/gitpod/blob/c5dcc42eb9bb5cb34bfe0535ab93aeb459fb1287/.github/workflows/jetbrains-update-plugin-platform-template.yml#L102

Should we remove it? @akosyakov 

/unhold

**Comment by akosyakov** [comment]
@mustard-mh ah this one is on purpose that we don't block the queue, we should not forget to remove it after the approve

**Pull request merged**
