### PR TITLE
fix #15266: decouple deployment of supervisor for image builds

### LINKED ISSUE #15266: Decouple deployment of supervisor from image builds.
Image build should start with a version of supervisor deployed by IDE team and resolved via ide-service.

It should not happen that another version of supervisor is deployed by another team.

### PR DESCRIPTION
**Pull request by akosyakov**
## Description

An incident last week was partially caused because new version of supervisor was deployed without IDE team knowing it. This PR makes sure that supervisor ref is always deployed and resolved by IDE service.

I think we should also remove a reference to supervisor from static layers of registry-facade [[1](https://github.com/gitpod-io/gitpod/blob/96a78364622d5dbb75801df40620046e03aeeebf/install/installer/pkg/components/registry-facade/configmap.go)]. But for now we should keep it for backward compatibility, i.e. till all teams deployed.

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/issues/15266

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by geropl** [comment]
Code LGTM, waiting for the preview env to test...

**Comment by akosyakov** [comment]
@geropl previews should be good, not sure yet how to verify...

for regressions one can start a workspace on https://github.com/gitpod-io/openvscode-server and check whether image build works

**Comment by geropl** [comment]
@akosyakov The env won't load at all. :cry: Jep, that's what I wanted to do.

**Comment by akosyakov** [comment]
@geropl try again

**Review by WVerlaek — APPROVED** [review]
lgtm

**Pull request merged**
