### PR TITLE
Use rabbitMQ built-in channel configuration instead of shell script

### PR DESCRIPTION
**Pull request by ArthurSens**
This PR changes the way we configure messagebus channels when it is first deployed. It uses [RabbitMQ configuration files](https://devops.datenkollektiv.de/creating-a-custom-rabbitmq-container-with-preconfigured-queues.html) instead of a shell script.

### CODE REVIEW

**Comment by meysholdt** [comment]
Thank you for the PR!

I think you need to add the new files here to leeway so that leeway adds them to the docker context and you can use them in the Dockerfile:
https://github.com/gitpod-io/gitpod/blob/376ea276f75542db21fb0688515445f42c262920/components/gitpod-messagebus/BUILD.yaml#L16-L17

I'm not sure we can delete this part:
https://github.com/gitpod-io/gitpod/blob/376ea276f75542db21fb0688515445f42c262920/components/gitpod-messagebus/configure.sh#L17-L25

**Comment by aledbf** [comment]
@meysholdt @ArthurSens is there a reason why the helm [chart for rabbitmq](https://bitnami.com/stack/rabbitmq/helm) is not being used instead of a custom deployment?

**Comment by ArthurSens** [comment]
Sorry @aledbf, I don't know the answer for this one either, perhaps @csweichel?

**Comment by meysholdt** [comment]
Thx for the pointer @aledbf! Is there something the Bitnami chart does that would be valuable for us? On first glance, it looks a good deal more complex than what we have today.

**Comment by csweichel** [comment]
There is no inherent reason we're not using the bitnami template, other than that it was either too complex or not available when we introduced messagebus.

There are a bunch of features we'd like to have in messagebus that we can't have at the moment, e.g.
- ha setup
- less complexity when using messagebus (exchange/topic/queue setup)
- simpler cross cluster setup (shovel)
- more observability into where load comes from (metrics over topics would help)

It's not clear yet if we can get some of those things (e.g. ha setup) by switching to a different template, or if we should be looking at other technology, e.g. NATS

**Comment by aledbf** [comment]
@meysholdt good questions:

**Features:**
- HA
- Use StatefulSet instead of deployments
- Persistence
- Metrics

Example:
```yaml
persistence:
  enabled: true
  size: 10Gi
replicaCount: 2
auth:
  username: <user>
  password: <password>
metrics:
  enabled: true
ingress:
  enabled: false
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [{
          "name": "amqp",
          "password": "<password>",
          "tags": "amqp-client"
        }],
        "permissions": [{
          "user": "amqp",
          "vhost": "amqp",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }],
        "exchanges": [{
          "name": "gitpod.ws",
          "type": "topic",
          "durable": true
        }, {
          "name": "gitpod.ws.local",
          "type": "topic",
          "durable": true
        }, {
          "name": "wsman",
          "type": "topic",
          "durable": false
        }, {
          "name": "consensus-leader",
          "type": "fanout",
          "durable": false
        }],
        "bindings": [{
          "source": "gitpod.ws.local",
          "destination": "gitpod.ws",
          "routing_key": "#"
        }]
      }
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json
```

**Comment by aledbf** [comment]
> It's not clear yet if we can get some of those things (e.g. ha setup) by switching to a different template, or if we should be looking at other technology, e.g. NATS

I also thought in NATS. That said, right now the impact/tome of such change is unknown. Also, is easier to switch to an external chart as an intermediate step, improving what we are using now. Removing the code from the gitpod chart is also a win for me.

**Comment by geropl** [comment]
Some more thoughts:
 - Besides fixing the setup of the `messagebus` deployment we IMO should alsofix our connection code. Note the last paragraph [here](https://www.rabbitmq.com/tutorials/amqp-concepts.html#queues):

   > Before a queue can be used it has to be declared. Declaring a queue will cause it to be created if it does not already exist. The declaration will have no effect if the queue does already exist and its attributes are the same as those in the declaration. When the existing queue attributes are not the same as those in the declaration a channel-level exception with code 406 (PRECONDITION_FAILED) will be raised.

   To avoid running creating diffs between `definition.json` and [this code](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-messagebus/src/messagebus.ts#L76-L78) we'd probably just remove the later.

 - When changing the `messagebus` setup we need to prepare it for extensibility so gitpod-com can add config. Basically a 2nd load_definition.json

**Comment by meysholdt** [comment]
@aledbf I agree with the arguments around simplicity, multi-cluster and HA.

Regarding persistence and StatefulSet I'm not sure we need it, because our messages are not very mission critical: status updates in the dashboard and (today) prebuild-logs. 

I'm quite happy with the fact that today our clusters are stateless; The Bitnami chart would change that because it demands a PersistentVolume for RabbitMQ.

**Comment by aledbf** [comment]
@ArthurSens @meysholdt @csweichel please check https://github.com/gitpod-io/gitpod/pull/3563

**Comment by aledbf** [comment]
> Regarding persistence and StatefulSet I'm not sure we need it, because our messages are not very mission critical: status updates in the dashboard and (today) prebuild-logs.

#3563 uses a statefulset without persistence.

**Comment by ArthurSens** [comment]
> @ArthurSens can we close this now? (#3563)

👍

**Pull request closed without merging**
