### PR TITLE
[Teams & Projects] Minor UX improvements

### PR DESCRIPTION
**Pull request by jankeromnes**
## Description

- [x] Shows `Fetching repository branches ...` with a spinner when loading branches:

Screenshot 2021-09-22 at 12 32 29

- [x] Shows `Connecting to workspace logs ...` when trying to show workspace logs:

Screenshot 2021-09-22 at 12 33 49

- [x] Also sorts Prebuilds by `startedAt` time (descending order) in the Prebuilds page

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/issues/5772

## Release Notes

```release-note
NONE
```

/uncc

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by:

*No associated issue*. Requirement bypassed by manually added approval.

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by AlexTugarev** [comment]
/lgtm

Very nice! Thanks @jankeromnes, it works as advertised!

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 806e38d342b9ef1f1bf9097a5e51b63a36f0898c</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5809#issuecomment-925644832" title="LGTM">AlexTugarev</a>*

Associated issue: *#5772*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [AlexTugarev]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by gtsiolis** [comment]
Didn't have the chance to take a closer look earlier but this looks great in staging! Go spinner! 🍕 

Thanks @jankeromnes for adding this and @AlexTugarev for reviewing this!

**Pull request merged**
