### PR TITLE
[dashboard] Implement a PaymentContext and use it to hide payment features when payment is disabled

### PR DESCRIPTION
**Pull request by jankeromnes**
## Description

- [x] Implement a `PaymentContext` and use it to hide payment features when payment is disabled in a Gitpod installation.

| Without Payment | With Payment |
| --- | --- |
| Screenshot 2022-03-31 at 16 44 20 | Screenshot 2022-04-01 at 11 16 59 |

_Side-note: The dynamic menu does cause [a bit of layout-shifting](https://youtu.be/eWwJk4KHbI0) specifically when refreshing Settings pages, but that should be fine as refreshing Settings is not a common user behavior._

### Temporary drive-by fixes:

- [x] Fix Helm Werft deployments by using a default value for `DB_ENCRYPTION_KEYS`
- [x] Fix Helm Werft deployments by disabling KOTS

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/issues/8916

## How to test

1. Have payments disabled (default for Werft deployments)
2. Open `/settings` -- the menu items `Plans` and `Teams` should **not** be visible
3. Enable payments (for example, re-deploy Werft with `with-payment=true` and `with-helm=true`)
4. Open `/settings` -- the menu items `Plans` and `Teams` should be visible

## Release Notes

```release-note
[dashboard] Implement a PaymentContext and use it to hide payment features when payment is disabled
```

## Documentation

- [x] /werft with-helm=true
- [x] /werft with-payment=true

### CODE REVIEW

**Comment by jankeromnes** [comment]
Same problem as https://github.com/gitpod-io/gitpod/issues/8829 -- `DB_ENCRYPTION_KEYS` is somehow missing when deploying with Helm. 🙄

**Comment by jankeromnes** [comment]
Adding a hold because of the temporary `WIP: Disable KOTS` commit.

/hold

**Comment by jankeromnes** [comment]
Now ready for review! 🎉

Game plan:
1. Allow reviewing this PR with-payment (current deployment)
2. Once approved, remove the two enabling commits and redeploy without payment
3. Re-approve and merge PR

**Comment by jankeromnes** [comment]
@AlexTugarev and @geropl I think you might be the best candidates for this review. Could you please take a look when you have some time?

- This fixes a Self-Hosted issue (hides payment menu entries when payment is disabled)
- but also refactors a bunch of duplicated payment logic we used to spread across several pages
- and it's an important pre-cursor to future payment-related work (like [Team Plans v2](https://github.com/gitpod-io/gitpod/pull/8041) and pretty soon usage-based pricing)

**Comment by AlexTugarev** [comment]
Screen Shot 2022-04-06 at 12 37 04

@jankeromnes on initial navigation to the Settings page, the two additional items were missing. I was confused and double-checked with the PR description. Turns out, I had to hard reload in browser, to get them loaded.

**Comment by jankeromnes** [comment]
Aha, indeed, good catch. Many thanks @AlexTugarev!

I've fixed this by moving the server-querying value-setting effect out of the `PaymentContext` (not always rendered?) and into the `Menu` (after seeing that most other Contexts are also updated in `App` or `Menu`) [like so](https://github.com/gitpod-io/gitpod/compare/c0e571a2c36c202211494040666940a1f528b2e0..a7c49f13dd743f75b823fb74defa0a4e003a8ede).

Problem should no longer reproduce. 👍

**Review by AlexTugarev — APPROVED** [review]
Works as advertised!

**Comment by jankeromnes** [comment]
Woohoo! Many thanks @AlexTugarev! 🔥

**Pull request merged**
