### PR TITLE
use sync.Cond to notify about gitpod config changes

### LINKED ISSUE #5929: port ignore is not working as expected
### Bug description

I have this config:

```yaml
# Ports to expose on workspace startup
ports:
  - port: 3000-3379
    onOpen: ignore
  - port: 3380
    onOpen: open-browser
  - port: 3381-32000
    onOpen: ignore
```

image

In I don't expect to see that message boxes like they are visible for that ignored ports

### Steps to reproduce

use the yaml and have a service that open ports in the ignored space

### Expected behavior

see decs

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by akosyakov**
- [x] /werft with-clean-slate-deployment

## Description

There was some kind of deadlock while one listener was trying to read config changes. I rewrote gitpod config service to use conditional variable to announce changes in gitpod config to avoid synchronisation over map of listeners. I changed clients as well that they don't consider nil config as closed channel and stop reading.

## Related Issue(s)

fix #5929

## How to test

- Start a workspace.
- Change .gitpod.yml to add port ranges ignoring some ports like in #5929
- Try to start ports inside and outside of such port ranges and verify that ignore is respected.
- Change onOpen action for this range, try to restart service on the port and see that changes are applied.

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by akosyakov** [comment]
It does not work either, I will continue investigation tomorrow.

**Comment by akosyakov** [comment]
@corneliusludmann I pushed new changes.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 2a15def33636938f6d2bf452de6d4049b8b74ac3</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6106#issuecomment-943329332" title="LGTM">corneliusludmann</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6106#issuecomment-943139358" title="LGTM">JanKoehnlein</a>*

Associated issue: *#5929*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [JanKoehnlein]
- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
