### PR TITLE
[dashboard] Fix Prebuilds item truncate

### PR DESCRIPTION
**Pull request by flaming-codes**
## Description
This PR fixes a small truncation issue w/ text in the **Prebuilds** items.

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/issues/9103

## How to test
No specific tests for this change are available.

## Release Notes

```release-note
NONE
```

## Screenshots

| Description | Image |
| --- | --- |
| Before fix | Screenshot 2022-06-04 at 20 37 17 |
| After fix | Screenshot 2022-06-04 at 20 37 08 |

### CODE REVIEW

**Comment by flaming-codes** [comment]
@gtsiolis I signed the CLA, so everything should have been fine to merge those changes. Is there anything on my side to do, so that contributions are accepted? Thanks!

**Comment by flaming-codes** [comment]
@gtsiolis What's the status on this from your side? I signed the CLA a long time ago, is there anything to do on my part? Thanks!

**Comment by gtsiolis** [comment]
Thanks for reaching out, @flaming-codes! Let me link the comment from https://github.com/gitpod-io/gitpod/pull/10268#issuecomment-1180397782.

**Review by jankeromnes — APPROVED** [review]
Many thanks for improving this!

Since the preview doesn't want to come up, I tried testing this on the live Gitpod app using my browser devtools.

I believe this improves the situation a bit, but in general, I'm somewhat unhappy with the general state of our table/column layout. We seem to be using `truncate` and `overflow-hidden` somewhat at random (sometimes multiple times on elements and their containers), yet some columns still don't have a consistent width in some layouts.

Ideally, in the future, we could clean this up by:
- Using a consistent width for all "column" root containers of an element, combined with `overflow-hidden` (this strictly prevents columns from growing larger than they should -- e.g. long branchnames currently overflow)
- Using `truncate` on every text sub-element that might have overflowing text (so that the hard cut of the text is not too "brutal" but has an ellipsis `...`)

Still, no point in delaying this improvement of the status quo because there are also other possible improvements to be made. 🙂 Thus, approving this PR.

Many thanks!

**Comment by jankeromnes** [comment]
Trying to bypass the failing build using a build without a preview:

/werft run

**Comment by jankeromnes** [comment]
Thanks! Should pass auto-merge now:

/unhold

**Comment by jankeromnes** [comment]
Paging Tide bot 📟

**Comment by geropl** [comment]
@jankeromnes I'm seeing this, no idea why:
image

**Comment by jankeromnes** [comment]
@geropl Ah, looks like you have more access than I do. In this case, let's unblock the merge queue again:

/hold

@flaming-codes Could you please go through the following steps in order to update this PR?

1. Open this PR in Gitpod, e.g. by clicking this link: https://gitpod.io/#https://github.com/gitpod-io/gitpod/pull/10472
2. In the terminal, run these commands:

```
git pull --rebase upstream main

git push -f origin
```

This should allow merging your PR. 🙂

**Comment by flaming-codes** [comment]
Hi team,

there we a lot of merge conflicts when trying to update my PR with the latest changes - no wonder, as my initial fix is now almost 2 months old, as of writing. 

I think I neither have the time nor energy to spend to fix PR-conflicts for such small changes, therefore I propose to delete this PR and apply the initial fix w/ a new one.

Thanks for all your work and Gitpod as a product, but these super long delays in my PR reviews that result in only fixing conflicts isn't the experience I yearn for.

All the best,
Tom

**Comment by jankeromnes** [comment]
Hi @flaming-codes,

Sorry that it took so long to review your changes that so many conflicts appeared... We're still not very good at reviewing community contributions in a consistent and timely manner, and we have a lot to learn & to improve there.

I'd totally understand if you don't have the time or energy to re-do the fix in a new PR. As an alternative, I believe I could salvage your commit into a new PR, and work towards merging that one. Would you be okay with this? I'd cc you on the new PRs so that you can follow along if interested, and since you've already signed the CLA, there would be no further actions needed on your part.

Thanks again,
Jan

**Comment by flaming-codes** [comment]
Hi Jan,

> As an alternative, I believe I could salvage your commit into a new PR, and work towards merging that one. Would you be okay with this?

Sure, works fine for me!

**Pull request closed without merging**
