### PR TITLE
Support combining SSDs into a raid

### PR DESCRIPTION
**Pull request by csweichel**
Useful for GKE deployments

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **csweichel** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by MrSimonEmms — APPROVED** [review]
/lgtm

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: cdd2fb617237261659421cd5d2f86682773fd08f</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5085#pullrequestreview-724067197" title="LGTM">MrSimonEmms</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [MrSimonEmms]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5085#issuecomment-894065822" title="Approved">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/5085#pullrequestreview-724067197" title="LGTM">MrSimonEmms</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/5085#issuecomment-894065822" title="Approved">csweichel</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [MrSimonEmms,csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jankeromnes** [comment]
@csweichel @aledbf @MrSimonEmms Hi!

FYI, this change seems to be related to a cluster incident where a `ws-daemon` pod keeps crashlooping (happened several times since this PR was deployed).

The symptoms are:

- A `ws-daemon` pod keeps crashlooping, triggering an alert

- `kubectl describe` shows this event:

```
$ kubectl describe pod ws-daemon-zc64j
[...]
Events:
  Type     Reason   Age                   From     Message
  ----     ------   ----                  ----     -------
  Warning  BackOff  112s (x390 over 86m)  kubelet  Back-off restarting failed container
```

- When getting the logs for all containers, it seems to be the first "init container", `raid-local-disks`, that fails with:

```
...
+ DISK_DEV_SUFFIX=(c d e f g h i j)
+ MAX_NUM_DISKS=8
+ NUM_DISKS=0
+ declare -a DISKS
++ seq 0 7
+ for i in `seq 0 $((MAX_NUM_DISKS-1))`
+ CURR_DISK=/dev/sdc
+ '[' '!' -b /dev/sdc ']'
+ break
+ '[' 0 -eq 0 ']'
+ echo 'no local disks detected!'
+ exit 1
no local disks detected!
```

**Comment by jankeromnes** [comment]
Update: We now believe the code is behaving as expected (after also https://github.com/gitpod-io/gitpod/pull/5096), i.e. "fail to init `ws-daemon` if `setupSSDRaid` is enabled but there are no disks for it".

The incident looks rather like a configuration problem (i.e. there is a headless pool in EU, which is unexpected, and it seems to both enable `setupSSDRaid` and have no disks for it, leading its single `ws-daemon` to crashloop).

**Pull request merged**
