### PR TITLE
clean up after #15895

### PR DESCRIPTION
**Pull request by akosyakov**
## Description

removed unused code

## Related Issue(s)

Fixes #

## How to test

Start a workspace with IntelliJ IDEA, check that you can open VS Code Browser and IntelliJ IDEA. While redirection got IntelliJ the origin should be gitpod, not workspace.

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all-ci
- [ ] /werft no-test
      Run Leeway with `--dont-test`

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]

**Comment by jeanp413** [comment]
Do I need to test it in prev env? are prev env still failing?

/hold

**Review by jeanp413 — APPROVED** [review]

**Comment by jeanp413** [comment]
Something is wrong, maybe needs a rebase?
image

**Pull request merged**
