### PR TITLE
Update code-web extension

### PR DESCRIPTION
**Pull request by jeanp413**
## Description

Update code-web extension
https://github.com/gitpod-io/gitpod-code/commit/4e069a6195f3926ba8b84725bc806228f4cb94ec

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by 31031969** [comment]
[1 (1) (1) (1) (2) (2).pdf](https://github.com/gitpod-io/gitpod/files/14302153/1.1.1.1.2.2.pdf)

**Comment by 31031969** [comment]
direct president de la firma a.t.col.mundial.com 
[35425669.pdf](https://github.com/gitpod-io/gitpod/files/14302162/35425669.pdf)

**Review by akosyakov — APPROVED** [review]
any reason what do we change?

**Comment by jeanp413** [comment]
Catches getTeams error as collaborator role doesn't have permission

**Comment by 31031969** [comment]
[1 (1) (1) (1) (2) (2).pdf](https://github.com/gitpod-io/gitpod/files/14319603/1.1.1.1.2.2.pdf)
[35425669.pdf](https://github.com/gitpod-io/gitpod/files/14319604/35425669.pdf)
[72158895 (1) omar (1) (2) (1) (2) (1) (1) (1) (1).pdf](https://github.com/gitpod-io/gitpod/files/14319605/72158895.1.omar.1.2.1.2.1.1.1.1.pdf)

**Pull request merged**
