### PR TITLE
refactor(dashboard/menu): persist team selection

### LINKED ISSUE #10496: Consider remembering team selection when visiting pages like workspaces
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/10309, currently when visiting pages like workspaces, the team scope selection changes back to the personal account unnecessarily, as users may work inside a team most of the team and never use their personal account for adding projects, etc.

This could require users to perform more click actions to get back to their team or project they were working on before switching to workspaces, etc.

Cc @AlexTugarev because https://github.com/gitpod-io/gitpod/pull/10309#pullrequestreview-997633645.

### Proposal

Consider remembering the team selection when visiting pages like workspaces.

### PR DESCRIPTION
**Pull request by aboqasem**
## Description

Persist team selection for better UX.

## Related Issue(s)

Fixes #10496

## How to test

1. Open dashboard
1. Switch teams
1. Click on Workspaces
1. You should still be on your selected team
1. Repeat 2 through 4 and optionally check local storage to see the team selection changing

Then:
1. Visit root URL (`/`)
1. The team selection should still be remembered 

## Release Notes

```release-note
persist selected team across pages
```

### CODE REVIEW

**Comment by aboqasem** [comment]
[ ] Creating a new team should change the persisted team

**Comment by aboqasem** [comment]
Now even `/projects` does not depend on the URL to have `/t/[slug]` 😅. That is a problem AFAIK, right?

**Comment by aboqasem** [comment]
The current behavior I implemented is for pages to be aware of the team even if the URL does not contain the team slug. I do not know whether this is wanted 🙂

**Comment by svenefftinge** [comment]
hey @aboqasem !Super sorry this PR slipped our attention. It's now quite outdated and I didn't see it when I started on #13316 . I'll bring this up with team so we can improve our handling of contributions.

**Pull request closed without merging**
