### PR TITLE
[server] further limit sendHeartbeat

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description

Further increase the rate limiting for sendHeartBeat

## Related Issue(s)

Fixes https://github.com/gitpod-io/ops/issues/8649

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by mbrevoort** [comment]
How often do IDEs sent heartbeats? Once per minute? And this would allow two per minute?

**Review by easyCZ — APPROVED** [review]

**Comment by svenefftinge** [comment]
> How often do IDEs sent heartbeats? Once per minute? And this would allow two per minute?

At most every 30 seconds (plus 5 - 15 seconds) so it's pretty tight indeed. Maybe a better approach is to throttle this on the server side as we are also updating the database, we know when we send the last markActive to ws-manager.

**Comment by mbrevoort** [comment]
If one of the calls from IDE fails because it is rate limited does it retry immediately or just try again on the same interval? If so, the risk of a periodic failure is minor and this rate limit setting would be fine.

**Comment by svenefftinge** [comment]
Yes, the clients just log and try again. I'm more concerned that we see users hitting this limit regularly and with that diluting the signal and polluting the logs.

**Comment by svenefftinge** [comment]
/unhold

Let's go with this change an in case the limit gets triggered regularly, we should reduce the amount of heartbeats from the client. We don't need a signal every 30 seconds

**Comment by atduarte** [comment]
💭  If we removed the close heartbeat and therefore the short (5 minutes) timeouts, we could significantly increase the time between heartbeats

**Pull request merged**
