### PR TITLE
[supervisor] thread-safe terminal listening

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix https://github.com/gitpod-io/gitpod/issues/3127: This PR cleans up the terminal grpc service by making sure that `Send` method is not called from different go routines.

@csweichel I could not trigger hanging terminals with this change anymore, tried for 2 hours following:
- run following node script in one terminal:
```js
(async () => {
    let content = 'a';
    for (let i = 0; i < 4096; i++) {
        content += 'a';
    }
    while (true) {
        console.log(content);
        await new Promise(resolve => setTimeout(resolve, 0.1))
    }
})();
```
- at the same time split terminal, wait to see the prompt, close the terminal
- do it till the first terminal hangs, usually one needs around 5-10 mins

I found that similar approach helped to resolve deadlocks in other libraries: https://gitlab.com/gitlab-org/gitaly/-/merge_requests/2723

#### How to test

- first try to reproduce without this change on some another PR following the description above
- when try to confirm with this PR that it does not happen anymore

### CODE REVIEW

**Comment by akosyakov** [comment]
@csweichel I could not trigger hanging terminals with this changes anymore, tried for 2 hours following:
- run following node script in one terminal:
```js
let dataRate = 0.5;
let titleRate = dataRate * 200;
(async () => {
    let content = 'a';
    for (let i = 0; i < 4096; i++) {
        content += 'a';
    }
    while (true) {
        console.log(content);
        await new Promise(resolve => setTimeout(resolve, dataRate))
    }
})();
(async () => {
    let index = 0;
    while (true) {
        process.title = String(index++)
        await new Promise(resolve => setTimeout(resolve, titleRate))
    }
})();
```
- at the same time spawn another terminal

It does not happen often on master either, but it is possible to reproduce after half an hour of trying for sure. With this PR it does not seem to happen at all.

I found that similar approach helped to resolve deadlocks in other libraries: https://gitlab.com/gitlab-org/gitaly/-/merge_requests/2723

**Review by csweichel — APPROVED** [review]
Lgtm

**Comment by Baneeishaque** [comment]
Issue is still there.

**Pull request merged**
