### PR TITLE
[ws-manager-mk2] Fix prebuild update events

### PR DESCRIPTION
**Pull request by Furisto**
## Description
- Change the snapshot name to be in the format snapshot-[timestamp].tar as was the case with mk1
- During prebuild updates ws-manager-mk2 sends an empty boolean if no condition is set (e.g. for aborted). On ws-manager-bridge in Typescript this is interpreted as true :grimacing:  which leads to ws-manager-bridge thinking that the prebuild has been aborted even though that is not the case
- ws-manager-bridge uses the stopping phase to determine the status of the prebuild and ignores updates for the stopped phase. This means we need to set the snapshot url during the stopping phase otherwise ws-manager-bridge does not register that the snapshot url is available

## Related Issue(s)
n.a.

## How to test
- Start prebuild in [preview environment](https://fo-mk2-preca90815df7.preview.gitpod-dev.com/workspaces)
- Start a workspace from that prebuild

## Release Notes

```release-note
None
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by kylos101** [comment]
@WVerlaek , can you review? @Furisto mentioned that he'd like to include with gen90 for this week's deploy.

**Comment by kylos101** [comment]
Channeling my inner @WVerlaek ... @Furisto , is there an opportunity here to add related tests? :pray:

**Comment by WVerlaek** [comment]
Code lgtm, but getting some errors running prebuilds in the [preview env](https://fo-mk2-preca90815df7.preview.gitpod-dev.com/workspaces):
* Triggered a prebuild, this first created an image build, which succeeded, but the image build workspace got stuck on `Stopping`
* After the image build the prebuild did run, but eventually failed with `SYSTEM ERROR`: `Prebuild failed for system reasons. Please contact support. undefined`
  * The prebuild was in Initializing for a while
  * Then errored, and got stuck in Stopping
* Pressing "Rerun prebuild" or running a new prebuild from the same branch doesn't start a new prebuild

**Comment by Furisto** [comment]
Which repository did you use to start the prebuild?

**Comment by WVerlaek** [comment]
@Furisto https://github.com/WVerlaek/adventofcode and https://github.com/wverlaek/dotfiles

**Comment by Furisto** [comment]
Can reproduce. I received the error the first time I started a prebuild (because workspacekit could not connect to ws-daemon). It worked the second time though. Not sure yet what makes it fail the first time. I suggest we merge this PR anyway because it will improve the situtation for the new cluster generation and then we will follow up with another PR to fix the issue you have observed.
prebuild_fix

**Review by WVerlaek — APPROVED** [review]

**Pull request merged**
