### PR TITLE
[fix] :Preselect editor and class on the new workspace modal on first load

### LINKED ISSUE #15912: Preselect editor and class on the new workspace modal on first load
### Problem to solve

Currently, when opening the new open-in-gitpod modal in the dashboard, there's a preselected **editor** and **class**. However, if you open (toggle) the dropdown, there's no preselected option.

### Proposal

Preselect editor and class on the new workspace modal on first load.

| BEFORE | AFTER |
|-|-|
| Screenshot 2023-01-20 at 12 39 48 AM (2) | Screenshot 2023-01-20 at 12 39 51 AM (2) |
| Screenshot 2023-01-20 at 12 40 00 AM (2) | Screenshot 2023-01-20 at 12 40 01 AM (2) |

### PR DESCRIPTION
**Pull request by yashikajotwani12**
## Description

[screen-capture (1).webm](https://user-images.githubusercontent.com/77020164/213983420-7dfbdc0a-7714-40fc-a563-07684a6e1186.webm)

## Related Issue(s)

Fixes #15912

## Release Notes

```release-note
[fix] :Preselect editor and class on the new workspace modal on first load
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all-ci
- [ ] /werft no-test
      Run Leeway with `--dont-test`
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by gtsiolis — APPROVED** [review]
Thanks for contributing, @yashikajotwani12! 🍊 

UX LGTM, expect when selecting `VS Code · Browser · Latest` which, rolls back the selection to `VS Code · Browser`. This could be out of the scope of these change though.


I'll let the `@gitpod-io/engineering-webapp`  take a closer look and confirm iof the selection bug is related to the changes here.

/hold

**Comment by yashikajotwani12** [comment]
> Thanks for contributing, @yashikajotwani12! tangerine
> 
> UX LGTM, except when selecting `VS Code · Browser · Latest` which rolls back the selection to `VS Code · Browser`. This could be out of the scope of the changes here, though. shrug
> 
> I'll let the `@gitpod-io/engineering-webapp` take a closer look and confirm if the selection bug. ping_pong
> 
> You'll also need to sign a CLA[[1](https://powerforms.docusign.net/30e1aa46-cce5-4bc6-a933-ad02cd8d5ada?env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&accountId=86335c2c-01b9-4edc-a187-014f5150a112)] once before merging your first contribution. Cc @meysholdt
> 
> /hold

Yeah, I have signed the CLA, 
Thanks

**Comment by gtsiolis** [comment]
Removing hold as the CLA has been signed and uploaded to the CLA folder.

Thanks @yashikajotwani12 for your patience! 🌮 🌮 

/unhold

**Pull request merged**
