### PR TITLE
Use Leeway version v0.7.1

### PR DESCRIPTION
**Pull request by mads-hartmann**
## Description

Bumps Leeway to version 0.7.1. The previous version was 0.5.2 so this includes quite a few changes. Most of them is about cleaning up unused features and code, but some notable changes are:

1. in [0.6.0](https://github.com/gitpod-io/leeway/releases/tag/v0.6.0) we "Log go mod download only when verbose" which will drastically reduce the logs you see in Werft (@sagor999 you'll like this I think as you created the [original report of this issue](https://github.com/gitpod-io/leeway/issues/107) - and thanks to @csweichel for making the fix in Leeway)
2. In [0.7.1](https://github.com/gitpod-io/leeway/releases/tag/v0.7.1) Enable running Leeways scripts in parallel. This is needed for https://github.com/gitpod-io/gitpod/issues/14707 and https://github.com/gitpod-io/gitpod/issues/14704

## Related Issue(s)

Part of https://github.com/gitpod-io/gitpod/issues/14707
Part of https://github.com/gitpod-io/gitpod/issues/14704
Fixes https://github.com/gitpod-io/leeway/issues/107

## How to test

I created a preview environment and ran the workspace integration tests against it to validate that the preview environment seems healthy enough ☺️

```
werft job run github -a with-preview=true -a with-integration-tests=workspace
```

And a quick check from a workspace to see that I did indeed upgrade Leeway

```
leeway version
0.7.1-7858d75
```

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by vulkoingim — APPROVED** [review]

**Review by Furisto — APPROVED** [review]

**Review by mustard-mh — COMMENTED** [review]
We have Github Actions using leeway too, could you upgrade them too? (under `.github/workflows` folder)

image

**Comment by mads-hartmann** [comment]
@mustard-mh Sure thing, but I'd like to do so in a folllow up PR if that's okay with you ☺️

**Review by mustard-mh — APPROVED** [review]
> @mustard-mh Sure thing, but I'd like to do so in a folllow up PR if that's okay with you 

LGTM 🙏

**Comment by mads-hartmann** [comment]
@mustard-mh Opened a PR here https://github.com/gitpod-io/gitpod/pull/15232 ☺️

**Pull request merged**
