### PR TITLE
Move publish Kots method under buildAndPublish

### LINKED ISSUE #9080: .werft/publish-kots: Move method under buildAndPublish
👋 coming for a late review 😅 

Does it make sense to move `publish-to-kots` to be a method under `buildAndPublish`?

I'm thinking of keeping `built.ts` as small as possible, while putting logic where it makes sense 🙂 (I can create an issue for that if that's agreed

cc @gitpod-io/platform

_Originally posted by @ArthurSens in https://github.com/gitpod-io/gitpod/issues/9070#issuecomment-1085955827_

### PR DESCRIPTION
**Pull request by ArthurSens**
## Description

Aiming to keep our `build.ts` file as minimal as possible, I'm moving the `publishToKots` method under the `build-and-publish.ts` as it looks more appropriate.

## Related Issue(s)

Fixes #9080 

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by meysholdt — DISMISSED** [review]
Code changes LGTM. 

However, @MrSimonEmms should review this, too (and remove the `hold` label if he approves).

**Comment by ArthurSens** [comment]
Simon just pinged me about the job failing, I'm taking a look at the moment 👀

**Comment by ArthurSens** [comment]
Should be good to go now @MrSimonEmms @meysholdt 

The problem with the failing job was that, before, publishToKots was called after the installation of Gitpod (installer binary was downloaded during deployment)

Since we're publishing earlier now, I just had to download the installer binary early as well

**Review by MrSimonEmms — APPROVED** [review]
Good work @ArthurSens. The KOTS publisher has worked fine

image

**Pull request merged**
