### PR TITLE
Adding prebuild status filter to repo configs list ui

### PR DESCRIPTION
**Pull request by selfcontained**
## Description

Adding a Prebuild status filter to Imported Repositories list that lets a user optionally filter by prebuilds being enabled or disabled.

| Light | Dark |
|--------|--------|
| image | image | 

* I also added a new `<Select>` component to podkit for this UI and tried to style it along our latest designs in figma. It's pretty close, but there's a few states we can improve the styles with I think to get it closer to the designs.
* I updated the query we use for searching projects to optionally allow for this new filter.

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 826dbd8</samp>

This pull request adds a new feature to filter projects and configurations by their prebuilds enabled setting. It modifies the project database, the configuration service, and the public API to support this feature. It also adds a new test case for the project database. The affected files are `project-db.ts`, `project-db-impl.ts`, `project-db.spec.db.ts`, `configuration.proto`, `configuration.pb.go`, `configuration_pb.ts`, `configuration-service-api.ts`, and `projects-service.ts`.

</details>

## Related Issue(s)

Fixes EXP-1001

## How to test

* Import a few repositories and enable prebuilds on at least one of them.
* Go back to the imported repos list page and try using combinations of the search box and the new prebuild status dropdown filter.

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - brad-confi769a77b085</li>
	<li><b>🔗 URL</b> - <a href="https://brad-confi769a77b085.preview.gitpod-dev.com/workspaces" target="_blank">brad-confi769a77b085.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - brad-config-prebuild-filter-gha.21443</li>
	<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-brad-confi769a77b085%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws-manager-mk2%22%0A;duration=P1D?project=gitpod-core-dev" target="_blank">GCP Logs Explorer</a></li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by mustard-mh** [comment]
Should this filter becomes a router like what we do with name?

image

**Review by filiptronicek — APPROVED** [review]
Code looks great. Just one comment about the state where a filter boils the result down to 0 entries.

**Comment by filiptronicek** [comment]
> @mustard-mh Prebuild enable failed

You're looking for EXP-804

**Pull request merged**
