### PR TITLE
[server] allow individual emails in passlist

### LINKED ISSUE #6554: Support pass-listing emails for preview envs
Currently, in preview environments new users that don't have an `@gitpod.io` email address automatically get blocked. 

In this case @shaal got blocked by this :(

image

There are two ways to solve this:
a) `kubectx exec` into the `mysql` pod and edit `blocked` column in the `d_b_identity` table for your user.
b) pass-list the email in 

https://github.com/gitpod-io/gitpod/blob/7af2c7328ef6ffb30dbe9f8b3f5664e0c0f79270/.werft/values.dev.yaml#L49-L52

However, I believe the pass-list currently only supports email domains and not individual email addresses. See the `@` in `@{e}`:

https://github.com/gitpod-io/gitpod/blob/7abe78c91792c18b0c22103c890b25ea3a4cdf05/components/server/src/user/user-service.ts#L142-L143

Proposed solution: Support individual email addresses on the pass-list.

### PR DESCRIPTION
**Pull request by JanKoehnlein**
## Description
Allows full email addresses in the passlist

## Related Issues
Fixes #6554

```release-notes
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jankoehnlein** after the PR has been reviewed.

Associated issue: *#6554*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by JanKoehnlein** [comment]
Close (see workaround in the issue)

**Pull request closed without merging**
