### PR TITLE
[fga] check workspace relationships

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description

We have identified that sometimes workspace relationships are missing without any error from spicedb. 

We used to write them in large chunks. This changes them taht and writes the workspace rleationship per workspace. In addition it checks if the rleationships have actually been written successfully.

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖 Generated by Copilot at 002c934</samp>

This pull request updates the authorization database migration logic and adds a temporary verification check. The changes aim to improve the robustness and consistency of the new authorization model for workspaces, organizations, and users.

</details>

## Related Issue(s)

Fixes #

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Review by geropl — APPROVED** [review]
Code LGTM :heavy_check_mark:

**Comment by geropl** [comment]
Tests are failing, though... :thinking: Can check in ~40mins

**Comment by svenefftinge** [comment]
> Tests are failing, though... 🤔 Can check in ~40mins

Funny enough, I cannot reproduce that failure in my dev environment, but it looks like a case for the sporadic write failure we are trying to tackle. 🤔

**Comment by svenefftinge** [comment]
This happens reliably when running `leeway build server:app` but not when running the unit tests individually or using `yarn test`

**Comment by svenefftinge** [comment]
Turned out to be a problem with the in memory mode of spicedb we use in testing. ([issue](https://github.com/authzed/spicedb/issues/1545)) So I changed the code to write the relationships sequentially.

**Pull request merged**
