### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Furisto**
## Description
Update containerd and buildkit dependencies

## Related Issue(s)
n.a.

## How to test
- Open workspace in preview environment

## Release Notes

```release-note
None
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by roboquat** [comment]
@Furisto: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by kylos101** [comment]
@Furisto how to test must also include integration tests passing :pray:

**Comment by kylos101** [comment]
/werft run with-integration-tests=workspace with-large-vm=true

**Review by felladrin — APPROVED** [review]

**Review by kylos101 — APPROVED** [review]
:bow: :+1:

**Review by Pothulapati — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
