### PR TITLE
[server] implement getAuthenticatedUser RPC

### PR DESCRIPTION
**Pull request by AlexTugarev**
## Description
Based on #19142

This adds server implementation for the `getAuthenticatedUser` RPC.

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 47d9156</samp>

This pull request refactors the user state management in the dashboard app to use the public API and React Query. It removes the `UserContext` component and the `useCurrentUser` hook, and replaces them with the `useAuthenticatedUser` hook. It also updates the user data types and fields, and removes unused or deprecated code.

</details>

## How to test
The feature flag for UserService in dashboard is enabled for this PR. Check dev tools to see that it uses `GetAuthenticatedUser` requests and not the Websocket connection.

Screenshot 2023-12-07 at 17 18 34

Then verify, you can log in, change preferences and so on. Run the https://github.com/gitpod-io/dashboard-playwright-tests, if you like ;-)

Screenshot 2023-12-07 at 17 16 50

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - at-server-1ebf11559a</li>
	<li><b>🔗 URL</b> - <a href="https://at-server-1ebf11559a.preview.gitpod-dev.com/workspaces" target="_blank">at-server-1ebf11559a.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - at-server-getauthenticateduser-gha.21485</li>
	<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-at-server-1ebf11559a%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws-manager-mk2%22%0A;duration=P1D?project=gitpod-core-dev" target="_blank">GCP Logs Explorer</a></li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [x] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by mustard-mh** [comment]
Tested with

- ✅ Dotfile
- ❌ Workspace start option is not remembered (choose small workspace size, but it show standard next time I'm trying to create a new one based on the same repo)
- ❌ Workspace timeout, set to 10m, show 600 as result and use `gp timeout show` in workspace, it said current timeout is 30m (value in workspace should not related to this PR? Or maybe it's because of convert failed)
image

**Comment by mustard-mh** [comment]
Noo, I replied it wrong, should no be in this PR. Sorry

**Review by akosyakov — APPROVED** [review]
looks good

**Pull request merged**
