### PR TITLE
feat(dashboard): greet folks who look at the console and help them

### PR DESCRIPTION
**Pull request by ghuntley**
## Description

When a workspace starts people are now greeted with classy vibe in the console. Opening this up for review to get peoples thoughts. I'm thinking this can be extended with:
- [ ]  troubleshooting information such as please disable browser extensions that are known incompatible
- [x] how to contact Gitpod support.
- [x] where to report securtiy issues.
- [ ] any ideas Gitpodders think are cool.

See also https://github.com/gitpod-io/website/pull/1189

## How to test

1. Boot up the workspace and look at console.log when starting a worksapce.

## Release Notes
```release-note
- When a workspace starts people are now greeted with classy vibe in the console.
```

### CODE REVIEW

**Comment by roboquat** [comment]
@ghuntley: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **corneliusludmann** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @corneliusludmann` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **alextugarev**, **corneliusludmann** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @alextugarev @corneliusludmann` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**
- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **geropl** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @geropl` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by JanKoehnlein** [comment]
/cc @gtsiolis 

as this is kind of an UX thing

**Comment by geropl** [comment]
/werft run

:crossed_fingers:

**Comment by geropl** [comment]
/werft run

Now it should work...

**Comment by geropl** [comment]
Deployments works now: https://gh-consolelog.staging.gitpod-dev.com/projects @gtsiolis 

I kind of like the idea to sent something to `console.log`. Not sure about the message and wording, though.

**Comment by gtsiolis** [comment]
Looking at this now! 👀

**Review by gtsiolis — CHANGES_REQUESTED** [review]
Hey @ghuntley! Thanks for adding this and sorry for taking a while to get back to this.

**issue**: This will probably go unnoticed for most users since :a: the console log is currently overwhelming with output and :b: the default height size of the developer tools console is smaller than the height of this output.

| Console log during workspace start| Example console log |
|-|-|
| Screenshot 2021-12-02 at 2 09 34 PM (2) | Screenshot 2021-11-25 at 4 29 41 PM |
 
**suggestion**: What do you think of making this more compact, friendlier, and maybe drop the monospace font since developer tools have different default preferences across browsers? Maybe also adding some 🍊 emojis and re-using some phrases from `www.gitpod.io`? Open to replacing the marketing phrase.

| Chrome | Firefox | Safari |
|-|-|-|
| Screenshot 2021-12-02 at 3 08 38 PM | Screenshot 2021-12-02 at 3 09 29 PM | Screenshot 2021-12-02 at 3 09 06 PM |

```diff
diff --git a/components/dashboard/src/start/StartWorkspace.tsx b/components/dashboard/src/start/StartWorkspace.tsx
index 14f4f97c..e747c410 100644
--- a/components/dashboard/src/start/StartWorkspace.tsx
+++ b/components/dashboard/src/start/StartWorkspace.tsx
@@ -122,39 +122,9 @@ export default class StartWorkspace extends React.Component<StartWorkspaceProps,
         throw new Error("No result!");
       }
 
-      console.log(`%c
+      console.log("🍊🍊🍊🍊 Welcome to Gitpod! Works on my machine - and yours.");
 
-─────────────────────────────────────────────────────────────────────────────────
-
-      ./shhs           Welconme to Gitpod!
-    :oyhhhhhy
- .ohhhhhhs/-    -//-   We want you to have frictionless experiences when
- yyyyyo:    .:ohhhhhs. interacting with our product and our company: no hurdles,
- yyyy:   .+yhhhhhhhhh. no BS, no unnecessary extra steps and as much automation
- yyyy:  .yyhhhy+ohhhh  as possible.
- yyyy:   :++:.  :hhhh
- yyyys/.      ./shhhh. Just straight to the point solutions that delight.
- -syyyyyy+-:+yyyyyyy-
-   .:osyyyyyyyyyo/.    If Gitpod does not spark joy, please let us know!
-       -+syys+-
-
-─────────────────────────────────────────────────────────────────────────────────
-
-`, `font-family: monospace`);
-
-    console.log("Your workspace instance is: " + result.instanceID);
-
-    console.log(`%c
-
-─────────────────────────────────────────────────────────────────────────────────
-
-   Help and general support      - https://www.gitpod.io/support
-   Community                     - https://www.gitpod.io/community
-   Privacy                       - https://www.gitpod.io/privacy
-   Security disclosures          - https://www.gitpod.io/security
-   Gitpod source code            - https://www.github.com/gitpod-io
-
-   `, `font-family: monospace`);
+      console.log("Opening workspace instance: " + result.instanceID);
 
       // redirect to workspaceURL if we are not yet running in an iframe
       if (!this.runsInIFrame() && result.workspaceURL) {
```

**Review by gtsiolis — COMMENTED** [review]
Triggered by this, but out of the scope of the changes in this PR, we could introduce a welcoming message when someone opens a workspace with no configuration or prebuilds enabled. The message could explain more about workspace-full image and maybe contain quick links to configure a project or add it as a project. 💡

**Comment by JanKoehnlein** [comment]
Sorry, but I think we should close this. It looks like this change didn't cause enough enthusiasm.

**Pull request closed without merging**
