### PR TITLE
nit-fix: Onboarding Text on Login Dashboard

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
> Signed-off-by: Siddhant Khare <siddhant@gitpod.io>

## Description

This PR Proposes to change the text on `/#https://github.com/gitpod-io/empty` Page with our [recent announcements](https://www.gitpod.io/cde)

|Old|New|
|---|---|
|image|image|

## Related Issue(s)

Fixes #[internal](https://gitpod.slack.com/archives/C02EN94AEPL/p1668184183523649)

## How to test

- Open Preview
- do a new Login 

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by svenefftinge** [comment]
Thank you! It is "Cloud Development Environment". Coold you fix the developer/development as well? Have you searched for other occurrences?

**Review by jldec — APPROVED** [review]

**Comment by Siddhant-K-code** [comment]
> @svenefftinge - Thank you! It is "Cloud Development Environment". Coold you fix the developer/development as well? Have you searched for other occurrences?

Yeah, Sure. I just saw it, late now, it is merged. Will create a follow-up PR for this.
Yeah, checked for other occurrences. It was just these two - `README.md` & Login Dashboard file

**Comment by jldec** [comment]
Sorry - I  approved this before I saw Sven's comment - my mistake - I restored the branch so that we can re-push.

**Comment by Siddhant-K-code** [comment]
> I restored the branch so that we can re-push.

I think, I will create a follow up PR for that. 🙏🏼

**Pull request merged**
