### PR TITLE
[content-service] Return ErrNotFound if bucket object does not exists

### PR DESCRIPTION
**Pull request by aledbf**
fixes https://github.com/gitpod-io/gitpod/issues/3772

### CODE REVIEW

**Review by geropl — APPROVED** [review]
LGTM

Thx! :rocket:

**Comment by geropl** [comment]
@aledbf I just checked the client code: It seems we do not properly check for `ErrNotFound`. What about going fixing that as well and move on without this today? :-)

**Comment by aledbf** [comment]
> I just checked the client code

Where exactly? (I read `WorkspaceService` and the code check the error)

**Comment by geropl** [comment]
@aledbf You're absolutely right, I got lost in the `WithError` noise here: https://github.com/gitpod-io/gitpod/blob/e56ed09ccb99dccd27507c3559ca64a49e857786/components/content-service/pkg/service/workspace-service.go#L70-L107

In case of `ErrNotFound` we should default to `Debug()` and not `Error()`.

**Comment by aledbf** [comment]
> In case of ErrNotFound we should default to Debug() and not Error().

Done

**Review by geropl — APPROVED** [review]
Awesome, thank you! :pray:

**Pull request merged**
