### PR TITLE
feat(db): update examples in the dashboard

### PR DESCRIPTION
**Pull request by ghuntley**
This pull-request adds https://github.com/gitpod-io/template-datasette to the examples in Gitpod.

### CODE REVIEW

**Review by geropl — APPROVED** [review]
:+1: Works as expected

**Comment by ghuntley** [comment]
One more time @geropl please 🧡

**Comment by ghuntley** [comment]
Re-confirmed working on https://gh-datasette.staging.gitpod-dev.com/#https://github.com/gitpod-io/template-haskell ❤️

**Pull request merged**
