### PR TITLE
Ensure uncommitted changes are displayed in dashboard 

### LINKED ISSUE #7370: Source changes not reflected in dashboard overview
### Bug description

Source changes not reflected in dashboard overview

CleanShot 2021-12-27 at 14 23 23
CleanShot 2021-12-27 at 14 23 36
CleanShot 2021-12-27 at 14 23 32

Happened to 2 different workspaces, one older, one brand new.

### Steps to reproduce

I reproduced by simply making changes in a workspace and then checked the dashboard.

### Workspace affected

blue-raccoon-uzfqkexx

### Expected behavior

It's really important that the changes are shown in the column, or that the column is not there (either is fine), since I trusted it and deleted a workspace that unfortunately had changes in it.

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Furisto**
## Description
Ensure uncommitted changes are displayed in dashboard. When the workspace was restored from a backup and subsequently stopped, uncommitted changes were not displayed in the dashboard anymore. The reason was that the location we use to check for changes was incorrect, because we get the checkout location from the initializer and the backup initializer does not use git and hence cannot provide the checkout location.

The checkout location is now provided as part of the workspace init request.

## Related Issue(s)
Fixes #7370

## How to test
- Create new workspace
- Modify or create a new file
- Stop the workspace 
- Navigate to dashboard -> changes are displayed for the workspace
- Start the workspace again
- Stop the workspace
- Navigate to dashboard -> changes should still be displayed for the workspace

## Notes for reviewers
It looks like bigger repositories like gitpod itself currently do not backup correctly in the preview environment (unreleated to my changes). I used [this](https://github.com/Furisto/brecht) for testing.

## Release Notes
```release-note
Ensure uncommitted changes are displayed in dashboard when workspace was restored from backup
```

### CODE REVIEW

**Review by princerachit — APPROVED** [review]

**Comment by Furisto** [comment]
@csweichel @aledbf You were requested as reviewers because you are specified as reviewers for the [ws-damon-api](https://github.com/gitpod-io/gitpod/blob/c0a67ee70dda8fc1614d16bd8ae8b0dd171b8274/.github/CODEOWNERS#L63). Is there a specific reason for that or should we change it to team workspace?

**Comment by aledbf** [comment]
@Furisto up to @csweichel. I have no problems changing it to workspace team.

**Comment by csweichel** [comment]
The duplication of the `checkoutLocation` seems odd on second glance. We should rather strive for removing that, akin to #9007.

**Comment by Furisto** [comment]
Closed in favor of #9007

**Pull request closed without merging**
