### PR TITLE
[theia] Add rebornix.ruby@0.27.0 to built-in extensions

### PR DESCRIPTION
**Pull request by jankeromnes**
Fixes https://github.com/gitpod-io/gitpod/issues/2132

### CODE REVIEW

**Comment by svenefftinge** [comment]
I see

Screenshot 2020-11-24 at 12 25 10

**Comment by svenefftinge** [comment]
http://jx-rebornix-ruby.staging.gitpod-dev.com/#https://github.com/gitpod-io/rails_sample_app

**Comment by jankeromnes** [comment]
Hm, then we could also build in the dependency `wingrunr21.vscode-ruby`.

However, @akosyakov says that in prior testing, we realized that having `rebornix.Ruby` installed by default in Gitpod would mean that every developer (regardless of the language) will see a configuration error or extension crash if they don't have the required configuration (which means some Ruby developers and all non-Ruby developers will see the error).

If that's still the case, that's definitely a no-go for installing this extension by default for everyone. 😕

**Comment by svenefftinge** [comment]
ok, let's close the PR then

**Pull request closed without merging**
