### PR TITLE
Decrease spacing between the timestamp table header and the sorting icon

### LINKED ISSUE #12221: Decrease spacing between the timestamp table header and the sorting icon
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/12135#discussion_r949299959, we need to decrease spacing between the timestamp table header and the sorting icon.

| BEFORE | AFTER |
|-|-|
| header-before | header-after |

### PR DESCRIPTION
**Pull request by ashwinair**
## Related Issue(s)

Fixes #12221 

## Release Notes
 
```release-note
Decrease spacing between the timestamp table header and the sorting icon
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@ashwinair: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by geropl — APPROVED** [review]
LGTM

/hold for @gtsiolis to judge :balance_scale:

**Comment by gtsiolis** [comment]
Thanks for contributing, @ashwinair! 🍊 

You'll also need to sign a Contributor License Agreement (CLA)[[1](https://en.wikipedia.org/wiki/Contributor_License_Agreement)] once before merging your first contribution. Looping in @meysholdt to reach out about the CLA. 🏓

**Comment by gtsiolis** [comment]
@ashwinair I just checked with the team for the failing builds above, and it seems we don't support builds in our system for branches including the `#` character.

Opened https://github.com/csweichel/werft/issues/164 as a feature request to support `#` in branch names.

In the meantime, it would help if you could close this PR and open a new one with a branch name not containing any special characters like `#`.

**Comment by ashwinair** [comment]
> In the meantime, it would help if you could close this PR and open a new one with a branch name not containing any special characters like `#`.

ah- sure, closing this PR :)

**Pull request closed without merging**
