### PR TITLE
werft/build: Rename created_vm span attribute

### PR DESCRIPTION
**Pull request by ArthurSens**
## Description
Self-explanatory

## Related Issue(s)

Fixes https://github.com/gitpod-io/ops/issues/2727

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by mads-hartmann — CHANGES_REQUESTED** [review]
🛹

**Comment by ArthurSens** [comment]
> 🛹

Was that supposed to be an approval? 😅

**Review by mads-hartmann — APPROVED** [review]
🛹 (Actually approve this time)

**Comment by mads-hartmann** [comment]
> Was that supposed to be an approval? 😅

@ArthurSens haha yes, sorry!

**Pull request merged**
