### PR TITLE
[usage] Fix month boundaries in usage view

### PR DESCRIPTION
**Pull request by easyCZ**
## Related Issue(s)

* Relates to https://github.com/gitpod-io/gitpod/issues/13521
* Depends on https://github.com/gitpod-io/gitpod/pull/13548

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by svenefftinge** [comment]
Would be great to fix this without switching to the [deprecated](https://momentjs.com/docs/#/-project-status/) moment.js library. 
To fix the underlying issue we need to compute the month start using UTC timezone. 
We can use `Date#getTimezoneOffset()` for that.

**Comment by easyCZ** [comment]
> Would be great to fix this without switching to the [deprecated](https://momentjs.com/docs/#/-project-status/) moment.js library. 

In that case here's removal of it from the entire codebase: https://github.com/gitpod-io/gitpod/pull/13548

**Review by andrew-farries — APPROVED** [review]

**Review by jankeromnes — COMMENTED** [review]
Apologies for the conflict here with https://github.com/gitpod-io/gitpod/pull/13568 ! 🙈 I did the fix as a drive-by since I was already working on this code, and only found out about the issue after opening my PR.

However, maybe a one-line fix is preferable over importing yet another third-party library + a significant code refactoring? 😬

**Comment by easyCZ** [comment]
Firstly, it doesn't just import yet another library, it actually [removes Moment](https://github.com/gitpod-io/gitpod/pull/13548) and replaces it with a much smaller dependency - there's already a win in that.
Secondly, I'd rather pull in a dependency to make future me (and others) not have to spend as much effort understanding the obtuse API that native Date provides when a much cleaner version exists.

**Comment by jankeromnes** [comment]
Many thanks for explaining the context @easyCZ! (And sorry again for the collision 🙈)

I knew Moment was deprecated, but I assumed it continued to work for now as a way to provide nicer "human-readable times" (e.g. "3 months ago" instead of "2022-07-06T08:07:10.243Z").

I didn't know we had decided to replace it with Dayjs (today I learned). For what it's worth, it does seem like a nice drop-in replacement. I especially like that it doesn't pull in any extra dependencies 💯 (on the other hand, it does pull in [a lot of devDependencies](https://github.com/iamkun/dayjs/blob/c9370ea96bf420439ee7eaa4146e8ed643160312/package.json#L68-L98), but I guess that's okay as it impacts only the developers of Gitpod and not all the end users of Gitpod).

I'll do my best not to interfere with this transition again. 🙏

**Comment by easyCZ** [comment]
> I didn't know we had decided to replace it with Dayjs (today I learned)

We didn't decide. I just did it because if usage of it was not gonna get a PR approved, well then we may as well remove it so that others don't fall in the same trap. Ask for forgivness, not permission.

**Pull request closed without merging**
