### PR TITLE
feat: Improved UX for Environment Variable Item List ( Settings )

### LINKED ISSUE #4635: Improve items list component
### Problem to solve

In https://github.com/gitpod-io/gitpod/pull/4454, we've added a reusable items list component used in _Workspaces_, _Environement Variables_, etc. In parallel, we've also fixed the issue with multiple dropdowns, see https://github.com/gitpod-io/gitpod/pull/4502. Cc @corneliusludmann 

However, there's still room for improving the UX and interaction of the items list component and the more actions dropdown.

### Proposal

The items list component could be improved by doing the following:
1. Do not remove the hover state on the more actions button when triggered and moving the cursor away. (_Dropdown B_) 
2. Do not remove the hover state of the list item when triggering the more actions and moving away the cursor. (_Dropdown C_) 

| Dropdown A | Dropdown B | Dropdown C |
|-|-|-|
| list-item-1 | list-item-2 | list-item-3 |

### PR DESCRIPTION
**Pull request by henit-chobisa**
## Description
The below issues propose improvement for the UX of the Environment Variable Components in Settings, by keeping the hovered effect ( the background colors ) of the workspace items till the ItemOverflowMenu is expanded. Please refer the below graphics for reference of the improvement.

## Improvements
https://user-images.githubusercontent.com/72302948/217173813-084a8f18-92b9-46a0-af3c-3d5698c42e80.mov

## Related Issue(s)
* Fixes #4635 

## How to test
- Change your directory from /gitpod to /gitpod/component/dashboard
- Add your host and token as given in the readme
- Start the development server by `yarn run start` and check on `http://localhost:3000` for checking the dashboard

## Release Notes

```release-note
Added Environment Variable Entry Component and associated it with Item List Context Menu, with ChangeMenuState Function, to keep the hovered effect
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`
- [ ] /werft publish-to-npm

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by henit-chobisa** [comment]
Hey @gtsiolis, as we discussed, this is second pull request for Improving the Item List Component, it fixes the Environement Variable List, in the User Preferences. 🐳
Thanks ✌️

**Review by gtsiolis — APPROVED** [review]
Thanks for another contribution, @henit-chobisa! 

UX LGTM! 🏁 

Taking a bias for action and merging this as the code changes look also quite similar to the changes in https://github.com/gitpod-io/gitpod/pull/16151.

Let me also loop in @gitpod-io/engineering-webapp for visibility in case there's anything that looks unnecessary and needs a revert or a different approach. 🏓

**Pull request merged**
