### PR TITLE
[prebuilds] no update status for pending prebuild

### LINKED ISSUE #7794: New commit check doesn't work
### Bug description

With these two PRs #7535, #7661 we have introduced the possibility prevent merging when the prebuild failed on a commit.

It [works well](https://github.com/svenefftinge/testing-gh-app/pull/2) for me in a preview environment, but unfortunately doesn't work in production.

### Steps to reproduce

Install the github app on a repo that has the checks set to `prevent-merge-on-fail`.
E.g. https://github.com/svenefftinge/testing-gh-app

Push a breaking change and create a PR. The commit check should fail, like in [this PR](https://github.com/svenefftinge/testing-gh-app/pull/2).

### Example repository

https://github.com/svenefftinge/testing-gh-app

### PR DESCRIPTION
**Pull request by svenefftinge**
fixes #7794 as well as generally commit checks on PRs turning green too early.

### How to test
Not testable with reasonable effort as it fixes an issue that only happens in production (maybe staging as well).

### Release Notes
```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
@svenefftinge: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankoehnlein** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankoehnlein` in a comment when ready.

Associated issue: *#7794*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by jankeromnes — APPROVED** [review]
Change looks good to me and @JanKoehnlein, merging so that we can test it on staging.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: b23e20d005e10d0385fe8fe410b9cfb5f521d48c</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7804#pullrequestreview-861914721" title="Approved">jankeromnes</a>*

Associated issue: *#7794*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
