### PR TITLE
[usage] Rename ReconcileUsageWithLedger to ReconcileUsage

### PR DESCRIPTION
**Pull request by easyCZ**
## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Review by andrew-farries — APPROVED** [review]
I think this might clash with https://github.com/gitpod-io/gitpod/pull/12903 as that uses a different tool to generate the typescript code from the `.proto` files.

/hold

**Comment by easyCZ** [comment]
> I think this might clash with #12903 as that uses a different tool to generate the typescript code from the `.proto` files.
> 
> /hold

I'll make sure this is rebased.

**Comment by easyCZ** [comment]
Already rebased on latest.

**Pull request merged**
