### PR TITLE
[t&p] added permission

### PR DESCRIPTION
**Pull request by svenefftinge**
to enable t&p UI under development

### CODE REVIEW

**Comment by svenefftinge** [comment]
fixes #4354

**Comment by jankeromnes** [comment]
Thanks! What is the benefit of making this a permission instead of a feature flag?

Screenshot 2021-06-06 at 14 46 47

**Comment by svenefftinge** [comment]
I'll close this as it is a one-liner and you can just do that in your other PR.

**Comment by jankeromnes** [comment]
Thanks! Sure will do.

For what it's worth, I've triggered a `io-dev` deployment to test this PR: https://werft.gitpod-io-dev.com/job/gitpod-build-se-teams-permission.2

**Pull request closed without merging**
