### PR TITLE
Enable VS Code Desktop for stable VS Code Web

### PR DESCRIPTION
**Pull request by akosyakov**
- [x] /werft with-clean-slate-deployment

## Description

- It enables VS Code Desktop in stable VS Code Web.
- It also fixes the issue in the server see https://github.com/gitpod-io/gitpod/pull/5599#issuecomment-915809527
- and adds auth timeout of 30secs to avoid hanging the local app if auth process failed because of server issues or a user simply closing the auth page

## How to test

- Start a workspace and use F1 -> Open VS Code: https://ak-stable-code-desktop.staging.gitpod-dev.com/#github.com/akosyakov/parcel-demo
- Check that VS Code Desktop was opened.

## Release Notes

```release-note
VS Code Desktop support
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **akosyakov** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by gtsiolis — COMMENTED** [review]
Hey @akosyakov!

:a: On the first run, the auth page for the local control client popped up. Clicked _CANCEL_ on purpose and show some lopping logs retrying to connect. See screenshot below.

| Auth page | Output logs |
|-|-|
| Screenshot 2021-09-08 at 3 00 41 PM (2) | Screenshot 2021-09-08 at 3 01 52 PM |

:b: Tried reinstalling the Gitpod extensions and closing remote connections before trying again. VS Code (Stable) worked. VS Code (Insiders) still tries to connect to Gitpod workspace. 💿

**Comment by aledbf** [comment]
It works. My only comment is that the window `Authorize Gitpod local control client` remains open after the authorization.

**Comment by akosyakov** [comment]
> My only comment is that the window Authorize Gitpod local control client remains open after the authorization.

I think it is a minor and can be addressed later. But please file an issue. 🙏

**Comment by akosyakov** [comment]
@rl-gitpod When a user clicks `Cancel` on the authorization screen, there is never redirect to the local app endpoint becuase of this code: https://github.com/gitpod-io/gitpod/blob/757a1594c6e5f14a268833b75411e449637c9d40/components/server/src/oauth-server/oauth-controller.ts#L54-L58 Do you know why we need this check?

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **csweichel** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @csweichel` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**
- **[components/local-app/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/local-app/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by akosyakov** [comment]
Now it tries to auth again and again if a user cancelled, we need a way to communicate it to the extension that it stops.

**Comment by akosyakov** [comment]
@gtsiolis Could you update Gitpod extension in your local VS Code and try again both scenarios?

**Comment by gtsiolis** [comment]
Looking at this now! 👀

**Review by gtsiolis — COMMENTED** [review]
@akosyakov Flawless! 🔮 

:a: Clicking `CANCEL` on the auth page also stopped the local companion app and I was able to retry and successfully authorize. ✔️ 
:b: I was also able to succesfully load workspaces in both local VS Code and VS Code Insiders. 🌟 


Three (3) minor observations:
1. On the first run when the local companion app starts up it takes 15-20 seconds to create the new remote connection. Next workspaces connect instantly. Expected?
2. The local companion app process remains up and running even if you stop the workspace, close the remote connection, or terminate VS Code. Expected?
3. I get two distinct local companion app processes for VS Code and VS Code Insiders but that's probably expected, right?

Screenshot 2021-09-09 at 5 27 52 PM

**Comment by akosyakov** [comment]
> On the first run when the local companion app starts up it takes 15-20 seconds to create the new remote connection. Next workspaces connect instantly. Expected?

Unfortunately, yes. Since VS Code Remote Development has to provision VS Code Server into a Gitpod workspace. Depending on your internet connection it can take a while. Alternatively we could reuse already running by us server, but that is not really aligned with existing users expectations and quite a different approach, see https://gitpod.slack.com/archives/C01KGM9DVRC/p1631077187068000 (internal link)

> The local companion app process remains up and running even if you stop the workspace, close the remote connection, or terminate VS Code. Expected?

It is expected, since it is a daemon which is reused across all VS Code sessions and Gitpod workspaces.

> I get two distinct local companion app processes for VS Code and VS Code Insiders but that's probably expected, right?

In future we maybe be able to do something about it, like discover running daemons via the special file, like suggested here for instance: https://github.com/gitpod-io/gitpod/issues/5602

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5599#issuecomment-916655960" title="Approved">akosyakov</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **csweichel** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @csweichel` in a comment when ready.

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/5599#issuecomment-916655960" title="Approved">akosyakov</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [akosyakov]
- ~~[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)~~ [akosyakov]
- ~~[components/local-app/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/local-app/OWNERS)~~ [akosyakov]
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: ac0a77f821aac4b516e021338de7df44b6b02a61</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5599#issuecomment-916655960" title="Approved">akosyakov</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/5599#issuecomment-916682904" title="Approved">JanKoehnlein</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/5599#issuecomment-916655960" title="Approved">akosyakov</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/5599#issuecomment-916682904" title="Approved">JanKoehnlein</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [JanKoehnlein,akosyakov]
- ~~[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)~~ [akosyakov]
- ~~[components/local-app/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/local-app/OWNERS)~~ [akosyakov]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [JanKoehnlein]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
