### PR TITLE
[dashboard] Clean up old unused images

### PR DESCRIPTION
**Pull request by jankeromnes**
## Description

Our two image directories were starting to get a bit confusing, with many images or icons not being used anywhere in the code, and some of them were very old.

So I thought it would be a good idea to clean up a bit. 🧹

- I've double-checked that every removed image isn't referenced anywhere in the code
- These images also never make it to a public URL (as opposed to all the images in [public](https://github.com/gitpod-io/gitpod/tree/main/components/dashboard/public) 🙈)

## Related Issue(s)

Fixes #

## How to test

- PR should build

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by gtsiolis** [comment]
Looking at this now! 👀

**Review by gtsiolis — APPROVED** [review]
Thanks for cleaning this up, @jankeromnes! 🧹 

UX LGTM!

**Review by easyCZ — APPROVED** [review]
LGTM

**Pull request merged**
