### PR TITLE
Improve workspaces empty state

### PR DESCRIPTION
**Pull request by gtsiolis**
Fix https://github.com/gitpod-io/gitpod/issues/4455.

| BEFORE | AFTER|
|-|-|
| Screenshot 2021-07-20 at 9 03 10 PM | Screenshot 2021-07-20 at 9 02 49 PM |

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4884#" title="Author self-approved">gtsiolis</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **svenefftinge** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @svenefftinge` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
@gtsiolis: [dog image](https://storage.googleapis.com/this-is-fine-images/this_is_fine.png)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/pull/4884#issuecomment-883587863):

>/this-is-fine


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by svenefftinge** [comment]
I like the graphical ingredient, but it moves everything to the bottom of the page, which is not so great. Can we do something that keeps the empty state centered?

**Comment by gtsiolis** [comment]
> I like the graphical ingredient, but it moves everything to the bottom of the page, which is not so great.

Agree! 

> Can we do something that keeps the empty state centered vertically?

Yes we can! Removing the list actions (search and filters) when the list is empty can help move everything slightly upwards just like in the empty state of the _Projects_ page, see screenshots in https://github.com/gitpod-io/gitpod/issues/4455. I've tried this https://github.com/gitpod-io/gitpod/commit/c49bf50917012246d5d7dbe70e962b3389cd7dd1 but not sure if code looks good as the build also failed. WDYT?

**Comment by csweichel** [comment]
ping @svenefftinge

**Comment by svenefftinge** [comment]
> but not sure if code looks good as the build also failed

The build seem to have failed because there were issues with the deployment. Maybe because of a too long branch name?

**Comment by gtsiolis** [comment]
Adding _meta: blocked_ label until improvements in https://github.com/gitpod-io/gitpod/pull/5555 have been merged, see https://github.com/gitpod-io/gitpod/pull/5555#discussion_r714935537.

**Pull request closed without merging**
