### PR TITLE
[code] Add open dashboard menu option to home menu

### LINKED ISSUE #4195: Add menu entry to open dashboard from the VS Code application menu
### Problem to solve

Currently, you can only go back to the dashboard from a running workspace through the command palette using a) the [command palette shortcut](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) and the [remote host button](https://code.visualstudio.com/docs/remote/ssh#_connect-to-a-remote-host) in the status bar.

See also [relevant discussion](https://gitpod.slack.com/archives/C01KGM9BH54/p1620645699054300) (internal).

| Application Menu | Command Palette |
|-|-|
| image | image |

### Proposal

Now that new dashboard is more useful to go back from a workspace, let's add a new item in the application menu in VS Code to open the dashboard. 🙂

### PR DESCRIPTION
**Pull request by jeanp413**
**What it does**
fixes #4195

Changes in Gitpod Code: https://github.com/gitpod-io/vscode/commit/b667bcb6376c418cc5782072b134a49290b83495

**How to test**
- Start a workspace: https://jp-add-open-dashboard-home-4195.staging.gitpod-dev.com/#https://github.com/gitpod-io/template-typescript-node
- Open Home menu and observe that `Gitpod: Open Dashboard` is present, click on it and it should open the dashboard

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jeanp413** after the PR has been reviewed.

Associated issue: *#4195*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jeanp413** after the PR has been reviewed.

Associated issue: *#4195*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by gtsiolis — APPROVED** [review]
Thanks for fixing this @jeanp413! 🔮

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 4287350643d07a9493d62cba591f6b34ba62865b</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5513#pullrequestreview-745773448" title="Approved">gtsiolis</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jeanp413** after the PR has been reviewed.

Associated issue: *#4195*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by akosyakov — APPROVED** [review]
/lgtm

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5513#pullrequestreview-745785514" title="LGTM">akosyakov</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/5513#pullrequestreview-745773448" title="Approved">gtsiolis</a>*

Associated issue: *#4195*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [akosyakov]
- ~~[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)~~ [akosyakov]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
