### PR TITLE
[docker-up] Do not assume container is ubuntu

### PR DESCRIPTION
**Pull request by aledbf**
or based in some of the `gitpod/workspace-*` variants.

fixes https://github.com/gitpod-io/gitpod/issues/3632

### CODE REVIEW

**Comment by aledbf** [comment]
```console
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xz-utils is already the newest version (5.2.4-1ubuntu1).
The following additional packages will be installed:
  libip6tc2 libmnl0 libnetfilter-conntrack3 libnfnetlink0 libnftnl11
  libxtables12
Suggested packages:
  firewalld kmod nftables
The following NEW packages will be installed:
  iptables libip6tc2 libmnl0 libnetfilter-conntrack3 libnfnetlink0 libnftnl11
  libxtables12
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 563 kB of archives.
After this operation, 3362 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 libmnl0 amd64 1.0.4-2 [12.3 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 libxtables12 amd64 1.8.4-3ubuntu2 [28.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal/main amd64 libip6tc2 amd64 1.8.4-3ubuntu2 [19.2 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal/main amd64 libnfnetlink0 amd64 1.0.1-3build1 [13.8 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal/main amd64 libnetfilter-conntrack3 amd64 1.0.7-2 [41.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal/main amd64 libnftnl11 amd64 1.1.5-1 [57.8 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal/main amd64 iptables amd64 1.8.4-3ubuntu2 [390 kB]
Fetched 563 kB in 0s (5750 kB/s)  
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libmnl0:amd64.
Reading package lists... Donets... 99%
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xz-utils is already the newest version (5.2.4-1ubuntu1).
The following additional packages will be installed:
  libip6tc2 libmnl0 libnetfilter-conntrack3 libnfnetlink0 libnftnl11
  libxtables12
Suggested packages:
  firewalld kmod nftables
The following NEW packages will be installed:
  iptables libip6tc2 libmnl0 libnetfilter-conntrack3 libnfnetlink0 libnftnl11
  libxtables12
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 563 kB of archives.
After this operation, 3362 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 libmnl0 amd64 1.0.4-2 [12.3 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 libxtables12 amd64 1.8.4-3ubuntu2 [28.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal/main amd64 libip6tc2 amd64 1.8.4-3ubuntu2 [19.2 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal/main amd64 libnfnetlink0 amd64 1.0.1-3build1 [13.8 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal/main amd64 libnetfilter-conntrack3 amd64 1.0.7-2 [41.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal/main amd64 libnftnl11 amd64 1.1.5-1 [57.8 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal/main amd64 iptables amd64 1.8.4-3ubuntu2 [390 kB]
Fetched 563 kB in 0s (5750 kB/s)  
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libmnl0:amd64.
Reading package lists... Donets... 99%
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xz-utils is already the newest version (5.2.4-1ubuntu1).
The following additional packages will be installed:
  libip6tc2 libmnl0 libnetfilter-conntrack3 libnfnetlink0 libnftnl11
  libxtables12
Suggested packages:
  firewalld kmod nftables
The following NEW packages will be installed:
  iptables libip6tc2 libmnl0 libnetfilter-conntrack3 libnfnetlink0 libnftnl11
  libxtables12
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 563 kB of archives.
After this operation, 3362 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 libmnl0 amd64 1.0.4-2 [12.3 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 libxtables12 amd64 1.8.4-3ubuntu2 [28.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal/main amd64 libip6tc2 amd64 1.8.4-3ubuntu2 [19.2 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal/main amd64 libnfnetlink0 amd64 1.0.1-3build1 [13.8 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal/main amd64 libnetfilter-conntrack3 amd64 1.0.7-2 [41.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal/main amd64 libnftnl11 amd64 1.1.5-1 [57.8 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal/main amd64 iptables amd64 1.8.4-3ubuntu2 [390 kB]
Fetched 563 kB in 0s (5750 kB/s)  
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libmnl0:amd64.
(Reading databa03-28T20:57:03.728071214Z] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728110110Z] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728134468Z] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728153723Z] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728175534Z] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728208880Z] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728238919Z] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728266579Z] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728305936Z] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2021-03-28T20:57:03.728669906Z] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728706425Z] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728724786Z] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728770792Z] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.729284716Z] serving...                                    address=/var/run/docker/containerd/containerd-debug.sock
INFO[2021-03-28T20:57:03.729618871Z] serving...                                    address=/var/run/docker/containerd/containerd.sock.ttrpc
INFO[2021-03-28T20:57:03.729909062Z] serving...                                    address=/var/run/docker/containerd/containerd.sock
INFO[2021-03-28T20:57:03.729984983Z] containerd successfully booted in 0.080615s  
INFO[2021-03-28T20:57:03.737787060Z] parsed scheme: "unix"                         module=grpc
INFO[2021-03-28T20:57:03.737862044Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2021-03-28T20:57:03.737968543Z] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2021-03-28T20:57:03.738018439Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2021-03-28T20:57:03.741708405Z] parsed scheme: "unix"                         module=grpc
INFO[2021-03-28T20:57:03.741748573Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2021-03-28T20:57:03.741774967Z] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2021-03-28T20:57:03.741796343Z] ClientConn switching balancer to "pick_first"  module=grpc
WARN[2021-03-28T20:57:03.852144469Z] Your kernel does not support swap memory limit 
WARN[2021-03-28T20:57:03.852177032Z] Your kernel does not support cgroup rt period 
WARN[2021-03-28T20:57:03.852190952Z] Your kernel does not support cgroup rt runtime 
WARN[2021-03-28T20:57:03.852200281Z] Your kernel does not support cgroup blkio weight 
WARN[2021-03-28T20:57:03.852276968Z] Your kernel does not support cgroup blkio weight_device 
INFO[2021-03-28T20:57:03.852533143Z] Loading containers: start.                   
INFO[2021-03-28T20:57:04.033813741Z] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be u03-28T20:57:03.728071214Z] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728110110Z] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728134468Z] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728153723Z] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728175534Z] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728208880Z] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728238919Z] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728266579Z] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728305936Z] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2021-03-28T20:57:03.728669906Z] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728706425Z] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728724786Z] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728770792Z] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.729284716Z] serving...                                    address=/var/run/docker/containerd/containerd-debug.sock
INFO[2021-03-28T20:57:03.729618871Z] serving...                                    address=/var/run/docker/containerd/containerd.sock.ttrpc
INFO[2021-03-28T20:57:03.729909062Z] serving...                                    address=/var/run/docker/containerd/containerd.sock
INFO[2021-03-28T20:57:03.729984983Z] containerd successfully booted in 0.080615s  
INFO[2021-03-28T20:57:03.737787060Z] parsed scheme: "unix"                         module=grpc
INFO[2021-03-28T20:57:03.737862044Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2021-03-28T20:57:03.737968543Z] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2021-03-28T20:57:03.738018439Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2021-03-28T20:57:03.741708405Z] parsed scheme: "unix"                         module=grpc
INFO[2021-03-28T20:57:03.741748573Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2021-03-28T20:57:03.741774967Z] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2021-03-28T20:57:03.741796343Z] ClientConn switching balancer to "pick_first"  module=grpc
WARN[2021-03-28T20:57:03.852144469Z] Your kernel does not support swap memory limit 
WARN[2021-03-28T20:57:03.852177032Z] Your kernel does not support cgroup rt period 
WARN[2021-03-28T20:57:03.852190952Z] Your kernel does not support cgroup rt runtime 
WARN[2021-03-28T20:57:03.852200281Z] Your kernel does not support cgroup blkio weight 
WARN[2021-03-28T20:57:03.852276968Z] Your kernel does not support cgroup blkio weight_device 
INFO[2021-03-28T20:57:03.852533143Z] Loading containers: start.                   
INFO[2021-03-28T20:57:04.033813741Z] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be u03-28T20:57:03.728071214Z] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728110110Z] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728134468Z] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728153723Z] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728175534Z] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728208880Z] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728238919Z] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728266579Z] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728305936Z] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2021-03-28T20:57:03.728669906Z] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728706425Z] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728724786Z] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.728770792Z] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2021-03-28T20:57:03.729284716Z] serving...                                    address=/var/run/docker/containerd/containerd-debug.sock
INFO[2021-03-28T20:57:03.729618871Z] serving...                                    address=/var/run/docker/containerd/containerd.sock.ttrpc
INFO[2021-03-28T20:57:03.729909062Z] serving...                                    address=/var/run/docker/containerd/containerd.sock
INFO[2021-03-28T20:57:03.729984983Z] containerd successfully booted in 0.080615s  
INFO[2021-03-28T20:57:03.737787060Z] parsed scheme: "unix"                         module=grpc
INFO[2021-03-28T20:57:03.737862044Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2021-03-28T20:57:03.737968543Z] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2021-03-28T20:57:03.738018439Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2021-03-28T20:57:03.741708405Z] parsed scheme: "unix"                         module=grpc
INFO[2021-03-28T20:57:03.741748573Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2021-03-28T20:57:03.741774967Z] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2021-03-28T20:57:03.741796343Z] ClientConn switching balancer to "pick_first"  module=grpc
WARN[2021-03-28T20:57:03.852144469Z] Your kernel does not support swap memory limit 
WARN[2021-03-28T20:57:03.852177032Z] Your kernel does not support cgroup rt period 
WARN[2021-03-28T20:57:03.852190952Z] Your kernel does not support cgroup rt runtime 
WARN[2021-03-28T20:57:03.852200281Z] Your kernel does not support cgroup blkio weight 
WARN[2021-03-28T20:57:03.852276968Z] Your kernel does not support cgroup blkio weight_device 
INFO[2021-03-28T20:57:03.852533143Z] Loading containers: start.                   
INFO[2021-03-28T20:57:04.033813741Z] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
WARN[2021-03-28T20:57:04.034711026Z] unable to disable IPv6 router advertisement   error="open /proc/sys/net/ipv6/conf/docker0/accept_ra: read-only file system"
WARN[2021-03-28T20:57:04.034778032Z] unable to disable IPv6 router advertisement   error="open /proc/sys/net/ipv6/conf/docker0/accept_ra: read-only file system"
INFO[2021-03-28T20:57:04.139801533Z] Loading containers: done.                    
WARN[2021-03-28T20:57:04.152113466Z] Not using native diff for overlay2, this may cause degraded performance for building images: failed to set opaque flag on middle layer: operation not permitted  storage-driver=overlay2
INFO[2021-03-28T20:57:04.152388913Z] Docker daemon                                 commit=99e3ed8 graphdriver(s)=overlay2 version=19.03.15
INFO[2021-03-28T20:57:04.152589407Z] Daemon has completed initialization          
INFO[2021-03-28T20:57:04.256563374Z] API listen on /var/run/docker.sock    
```

**Review by csweichel — COMMENTED** [review]
at the moment we're supporting Debian/Ubuntu based workspace images, and Alpine based images - anything else won't make it through the "gitpod layer image build".

I'm wondering if it would be enough to check whether we can call `apk` or `apt-get` and choose the packages to install based on that. We should certainly pin the versions (unlike before).
I'd hope it would achieve much the same, but with less code/future maintenance.

**Comment by aledbf** [comment]
@csweichel please review again. I refactored the code to embed the binaries in `docker-up`, removing the need for internet access. Also added a check for `apk`, installing the only required dependency, `iptables`.

`docker-up` file details: `-rwxr-xr-x 1 root root 81762530 Mar 29 23:43 /usr/bin/docker-up`

**Review by csweichel — APPROVED** [review]
LGTM

**Pull request merged**
