### PR TITLE
[baseserver] Add prometheus metrics

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

Extends base server (powers `public-api`) with ability to serve prometheus metrics.

## Related Issue(s)

Part of https://github.com/gitpod-io/gitpod/issues/9229
Depends on https://github.com/gitpod-io/gitpod/pull/9300

## How to test

Unit tests

## Release Notes

```release-note
NONE
```

## Documentation

NONE

/hold

### CODE REVIEW

**Comment by roboquat** [comment]
@easyCZ: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by andrew-farries — APPROVED** [review]
Looks good. I guess we could add a test for the case when the server is constructed with a nil metrics registry, but I leave it up to you if you think such tests are worthwhile.

**Comment by easyCZ** [comment]
> with a nil metrics registry, but I leave it up to you if you think such tests are worthwhile.
Will add in a follow-up PR. Thanks!

/unhold

**Pull request merged**
