### PR TITLE
test: fix workspace only ran ws-manager integration test

### PR DESCRIPTION
**Pull request by jenting**
## Description

From the [log](https://werft.gitpod-dev.com/job/gitpod-custom-to-fix-test-output.0/logs) of the integration test, we observed that only the ws-manager component was run.

## Related Issue(s)

Fixes #

## How to test

Check the werft result, all the components should run the integration test
- ws-manager
- image-builder
- content-service
- ws-daemon
- workspace

## Release Notes

```release-note
None
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-large-vm
- [x] /werft with-integration-tests=workspace
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by WVerlaek — APPROVED** [review]
lgtm

**Comment by utam0k** [comment]
@jenting I'm not sure why did you think so?
> From the [log](https://werft.gitpod-dev.com/job/gitpod-custom-to-fix-test-output.0/logs) of the integration test, we observed that only the ws-manager component was run.

**Comment by jenting** [comment]
> @jenting I'm not sure why did you think so?
> 
> > From the [log](https://werft.gitpod-dev.com/job/gitpod-custom-to-fix-test-output.0/logs) of the integration test, we observed that only the ws-manager component was run.

I was wrong... going to revert it.

**Comment by utam0k** [comment]
@jenting Thanks for your quick response :pray:

**Pull request merged**
