### PR TITLE
[docs] Generic doc update for v0.9.0

### LINKED ISSUE #3893: [self-hosted] Release Gitpod Self-Hosted 0.9.0
ToDo:
  - [x] update to latest Gitpod as from gitpod.io (as usual)
  - [x] docs:
    - [x] reflect our [matrix of supported platforms](https://www.notion.so/gitpod/1b9eac5cb33d42e391f86a87f0e37836?v=4f2ec7c943514ee19203b9d4fe096094) more prominently
    - [x] ~update~ remove OAuth config ~to focus on dynamic setup~: the dynamic part is already documented as part of the "regular" docs
  - [x] build missing UI:
    - [x] reinstate terms page: #3920
    - [x] handle SETUP_REQUIRED: #3920
      - [x] initial Git Provider (on demand)
      - [x] first user to be admin
    ~- [ ] handle EE_LICENSE_REQUIRED https://github.com/gitpod-io/gitpod/issues/3918~
      ~- [ ] Upload License page with a website link to buy the license from~
  - [x] remove deprecated installer images
  ~- [ ] #3912: adjust (and fix) terraform scripts so they are not geared towards installers anymore (and fix #3766 along the way)~

### PR DESCRIPTION
**Pull request by geropl**
Fixes #3893.

### Test
release: https://github.com/gitpod-io/gitpod/releases/tag/v0.9.0-alpha1
deployed to: https://gpl.gitpod-self-hosted.com/

### CODE REVIEW

**Comment by aledbf** [comment]
@geropl it seems `messagebus` image is missing.
https://console.cloud.google.com/gcr/images/gitpod-io/GLOBAL/self-hosted/messagebus

**Comment by geropl** [comment]
@aledbf This is currently based on latest `core` (and will get bumped even further once we have more fixes/UI in), so it's using the latest rabbitmq changes of yours, image is: `docker.io/bitnami/rabbitmq:3.8.14-debian-10-r0`

Or am I missing sth? :thinking:

**Comment by geropl** [comment]
Has been merged into https://github.com/gitpod-io/website in the meantime

**Pull request closed without merging**
