### PR TITLE
[server] Deprecate AdditionalContentPrefixContextParser

### PR DESCRIPTION
**Pull request by geropl**
## Description
Deprecating `AdditionalContentPrefixContextParser` was mostly added for debugging purposes.

## Related Issue(s)

Fixes #

## Release Notes

```release-note
remove `/#additionalContent/...` ContextParser
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]
It's not really a deprecation - it's a removal. Do you want to rephrase the release note?

**Comment by geropl** [comment]
> It's not really a deprecation - it's a removal. Do you want to rephrase the release note?

:heavy_check_mark: 

/unhold

**Comment by roboquat** [comment]
@geropl: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
