### PR TITLE
fix: grammar in theia listing

### LINKED ISSUE #1773: minor grammar error for Theia whitelisted workspace option
This should read "Deep dive into Gitpod's open-source IDE (written in TypeScript)." I'd fix this but I'm not sure where to look as taking a search the only results were migration files and I suspect that's not the correct place (is it server-side or something?)
F6BF8FF0-DC40-4D0C-941B-CEDAD7067C00

### PR DESCRIPTION
**Pull request by Rexogamer**
**Fixes #1773**
(I hear this might need to be updated DB-side for existing installs? Either way this will fix it on fresh installs.)

### CODE REVIEW

**Review by jankeromnes — COMMENTED** [review]
Hi @Rexogamer, many thanks for this fix!

Your change looks good to me, although I'm not quite sure why we have two separate repository lists in our migration scripts.

Also, both lists seem outdated now, as we have better examples in descriptions on gitpod.io (I updated the database manually to set them up, but forgot to add a migration script).

Before merging though, I would like a second opinion from @csweichel or @geropl about whether it's safe to modify these migration scripts (or e.g. if we would need to leave them unchanged and instead implement a new migration script at the end of the chain).

**Review by svenefftinge — APPROVED** [review]
Thanks. Yes, it is safe to change the migrations they might not get applied on existing installations, though.

**Comment by csweichel** [comment]
This change broke the migrations, see https://werft.gitpod-dev.com/job/gitpod-build-master.28

Once fixed, please write again and I'll trigger another build.

**Review by csweichel — CHANGES_REQUESTED** [review]
The change breaks the migrations, see https://werft.gitpod-dev.com/job/gitpod-build-master.28
Once fixed we can run another build.

**Comment by Rexogamer** [comment]
I've been having issues with Werft as I can't see anything (the logs don't load). I'm using the desktop site on an iPad.

**Comment by svenefftinge** [comment]
The message is:

> "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's open-source IDE (written in TypeScript).', 4)' at line 1",

So probably the escape isn't working

**Comment by Rexogamer** [comment]
Why isn't it reporting the status?

**Comment by Rexogamer** [comment]
Any news?

**Comment by svenefftinge** [comment]
Sorry, because of a recent change this is no longer applicable as is. 
The typo is now here:
https://github.com/gitpod-io/gitpod/blob/281f7137b5441565b9ecddc5b23d3a0ff6b413de/components/gitpod-db/src/typeorm/migration/1592203031938-Baseline.ts#L63

Instead of escaping we should just use a `"`-quoted string literal.

**Comment by svenefftinge** [comment]
@Rexogamer sorry, a simple fix like this causes so much iterations 🙄

**Pull request closed without merging**
