### PR TITLE
[server] allow members to leave

### LINKED ISSUE #16794: [Orgs] Cannot leave org as a (regular) member
The `Leave organization` action is effectless, and no the JS console I read:

> ConnectError: [permission_denied] operation not permitted: missing update permission on team

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description
Fixes the permissions for remobing org members
 
## Related Issue(s)

Fixes #16794

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by AlexTugarev — APPROVED** [review]
Code change makes sense! 👍🏻 

/hold for testing

**Comment by AlexTugarev** [comment]
@svenefftinge, for some reason, the Dashboard doesn't load for me 🤷🏻‍♂️ 
Your call, I believe the change will work as expected.

**Comment by svenefftinge** [comment]
oh, that seems to be a bug not introduced in this PR 😬

**Pull request merged**
