### PR TITLE
[code] upgrade to VS Code 1.57.0

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix https://github.com/gitpod-io/gitpod/issues/4403
- fix https://github.com/gitpod-io/gitpod/issues/4268
- fix https://github.com/gitpod-io/gitpod/issues/4130

Changes in Gitpod Code: https://github.com/gitpod-io/vscode/commit/bcd47c10d173a0c5cb174ab7451bb5133c4e9bec

#### How to test

- Start a workspace: https://ak-vscode-update.staging.gitpod-dev.com/#https://github.com/gitpod-io/gitpod
- - websockets and workers are properly proxied
    - diff editor should be operatable
    - trigger reconnection with `window.WebSocket.disconnectWorkspace()`, check that old websockets are closed and new opened of the same amount
- that user data are sync across workspaces as well as on workspace restart, especially for extensions
    - test that extensions from .gitpod.yml are installed without sync
- terminals are preserved and resized properly between window reloads
  - try to rename, change color and icon of a terminal. It should be preserved on page reload as well.
- workspace specific commands should work, i.e. F1 → type Gitpod prefix
- that a PR view is preloaded on the PR url
- test gp open and preview
- smoke test on Chrome, FF, and Safari on Mac/iPad

### CODE REVIEW

**Review by JanKoehnlein — CHANGES_REQUESTED** [review]
When I change the icon of a terminal, the IDE stalls (websocket disconnects and fails to reconnect), even for other tabs on the same workspace.

**Comment by akosyakov** [comment]
@JanKoehnlein please try again

**Review by JanKoehnlein — APPROVED** [review]
LGTM now. 

Nit: Changing the icon of a terminal is not reflected in other tabs on the same workspace while rename is. 

I'd love to see @corneliusludmann test as well, as this has big impact.

**Comment by akosyakov** [comment]
> Changing the icon of a terminal is not reflected in other tabs on the same workspace while rename is.

It is limitations of terminal channel protocol. There is an event for changed title, but not an event for changed icon/color.

**Comment by corneliusludmann** [comment]
When I execute `gp open test`, a new workspace tab opens:

https://user-images.githubusercontent.com/24960040/122383599-428e3b80-cf6b-11eb-980b-e40ea3b9b9bc.mp4

**Comment by corneliusludmann** [comment]
Everything else looks good.

**Comment by akosyakov** [comment]
@corneliusludmann gp open is code cli now, ant it has own semantic, I guess you have test folder and it opens this folder in a new tab

**Comment by corneliusludmann** [comment]
> @corneliusludmann gp open is code cli now, ant it has own semantic, I guess you have test folder and it opens this folder in a new tab

You're right! My fault.

**Review by corneliusludmann — APPROVED** [review]

**Pull request merged**
