### PR TITLE
[content-service] Decompress preserving permissions and remap file owners

### PR DESCRIPTION
**Pull request by aledbf**
fixes https://github.com/gitpod-io/gitpod/issues/3174

**How to test:** follow any of the scenarios described in the issue.

### CODE REVIEW

**Comment by fathead9898** [comment]
Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by aledbf** [comment]
**Note:** I tried to use different go libraries but the number of changes in dependencies is too high or it does not work
(the files lose the `suid` or the UID remapping breaks something)

- https://github.com/containers/storage/blob/master/pkg/archive/archive.go
- https://github.com/docker/docker/blob/master/pkg/archive/archive.go
- https://github.com/containers/buildah/blob/master/copier/copier.go
- https://github.com/containerd/containerd/blob/master/archive/tar.go

**Review by csweichel — APPROVED** [review]
Awesome 🚀 
Code LGTM and change works as advertised 🎉 

nit: please squash before merging :)

**Pull request merged**
