### PR TITLE
[payment] don't rely on VERSION env var

### LINKED ISSUE #5187: Payment-endpoint is crash-looping
Commit https://github.com/gitpod-io/gitpod/commit/df20a0ab13dd8f7d1e711b8744be9fb961f97316 sends container `payment-endpoint` crash-looping via 

```
Error: Environment variable undefined or empty: VERSION
    at getEnvVar (/app/node_modules/@gitpod/gitpod-protocol/lib/env.js:45:15)
    at new AbstractComponentEnv (/app/node_modules/@gitpod/gitpod-protocol/lib/env.js:32:24)
    at new Config (/app/node_modules/@gitpod/gitpod-payment-endpoint/lib/config.js:21:9)
    at Object.resolveInstance (/app/node_modules/inversify/lib/resolution/instantiation.js:45:18)
    at /app/node_modules/inversify/lib/resolution/resolver.js:72:42
    at Array.map (<anonymous>)
    at _injectProperties (/app/node_modules/inversify/lib/resolution/instantiation.js:11:57)
    at Object.resolveInstance (/app/node_modules/inversify/lib/resolution/instantiation.js:42:18)
    at /app/node_modules/inversify/lib/resolution/resolver.js:72:42
    at Array.map (<anonymous>)
```

### PR DESCRIPTION
**Pull request by JanKoehnlein**
Fixes #5187

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jankoehnlein** after the PR has been reviewed.

Associated issue: *#5187*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jankoehnlein** after the PR has been reviewed.

Associated issue: *#5187*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by jankeromnes — APPROVED** [review]
Hmm, I don't feel very legitimate in reviewing this change, as I don't see what sort of side-effects it could have.

Still, if this change is urgent, I'll approve it to unblock it. I guess if it builds & deploys fine, it means there are no deal-breaking problems.

If I understand correctly, you're moving `version` from `AbstractComponentEnv` into `Env`, in order to no longer have it in `Config` (what a terribly ambiguous class name 🙈).

Looking through the code, I couldn't spot any obvious dangers, except maybe for this part which looks supicious to me (because it seems to somehow cast `Config` to `Env` and then call `fromEnv`, which relies on `.version` to exist):

https://github.com/gitpod-io/gitpod/blob/6f15a4355420eddec28478b175311c843e4a1198/components/server/src/container-module.ts#L86-L89

But maybe this is actually fine and I just don't understand this code.

An alternative fix could be to not move `version`, but give a default value as second parameter to `getEnvVar` (thus the call wouldn't fail even if `VERSION` isn't set).

For example like so (still in `AbstractComponentEnv`):

```diff
-    readonly version: string = getEnvVar('VERSION');
+    readonly version: string = getEnvVar('VERSION', 'unknown');
```

/hold

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 7d61502ede12f9ab6f28417d2c5ffd942ae01e9a</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5189#pullrequestreview-729677606" title="Approved">jankeromnes</a>*

Associated issue: *#5187*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [jankeromnes]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by JanKoehnlein** [comment]
Thanks @jankeromnes for the review. I think you are very legitimate to judge this change. 

> except maybe for this part which looks suspicious to me (because it seems to somehow cast Config to Env and then call fromEnv, which relies on .version to exist)

That should be fine, because  a) the source is `Env` which has `version` and b) it's in the server component that has the env variable `VERSION` set in its `values.yaml`.

> An alternative fix could be to not move version, but give a default value as second parameter to getEnvVar

That's what I was considering as well, but in the end I decided it's safer to not have a field declared than to allow it have a bogus value.

**Pull request merged**
