### PR TITLE
Update editor preview favicon

### PR DESCRIPTION
**Pull request by gtsiolis**
PR for verifying the change in https://github.com/gitpod-io/vscode/pull/23, see [relevant comment](https://github.com/gitpod-io/vscode/pull/23#issuecomment-890733425). Cc @akosyakov

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rl-gitpod** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @rl-gitpod` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by akosyakov** [comment]
Now there is no icon at all:
Screenshot 2021-08-02 at 13 27 33

Maybe something should be changed here: https://github.com/gitpod-io/gitpod/blob/0e91076d4209b5282872ddd95313c81cc679495f/components/ws-proxy/public/port-not-found.html#L16-L19

**Comment by gtsiolis** [comment]
Closing this, see https://github.com/gitpod-io/vscode/pull/23#issuecomment-896652251.

**Pull request closed without merging**
