### PR TITLE
proposal: feat: Enable and autoinstall shell completions for gp CLI

### PR DESCRIPTION
**Pull request by axonasif**
Previous PR here: https://github.com/gitpod-io/gitpod/pull/13887
Recreated as werft job was failing.

## Description

Glad I stumbled upon the codebase, I was literally about to write the completion scripts for use with my fish shell. It's kind of funny how this wasn't mentioned anywhere how to setup for `bash`, which was already there 😬
This updates the completion command and autoinstalls them for different shells on workspace start.

|fish|
|---|
|Screenshot 2022-10-16 at 12 50 17 AM|

|bash|
|---|
|Screenshot 2022-10-16 at 12 52 41 AM|

|zsh|
|---|
|Screenshot 2022-10-16 at 12 55 22 AM|

## Related Issue(s)

Fixes #

## How to test

1. Open a workspace in preview env
2. Type `gp` and hit `Tab` key.
- To check for other shells, switch to them by running `fish` or `zsh`
- And redo `2.`

## Release Notes

```release-note
feat: Enable and autoinstall shell completions for gp CLI
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by felladrin** [comment]
@axonasif, could you squash and rebase this PR?

**Comment by axonasif** [comment]
> @axonasif, could you squash and rebase this PR?

Done, thank you!

**Comment by filiptronicek** [comment]
@axonasif it seems that there are formatting issues. I've tried looking at them, but couldn't get `gofmt` to change anything, so if you have a spare moment could you try? I would so love to have this

**Comment by axonasif** [comment]
I had rebased on latest `main` branch, that fails on some `supervisor` tests. Reverted the whole change, still fails with something else. Maybe something else is broken or I need to recreate the PR 🤔 

Going to check another recent PR werft build logs to confirm 🙏

**Pull request closed without merging**
