### PR TITLE
[ws-proxy] Configure kube-rbac

### PR DESCRIPTION
**Pull request by aledbf**
## Description

Setup kube-rbac proxy in ws-proxy component

## How to test

- ws-proxy should start without issues
- Access to port 9500 of ws-proxy service IP address should return unauthorized access
 
## Release Notes
```release-note
[ws-proxy] Configure kube-rbac
```

### CODE REVIEW

**Comment by princerachit** [comment]
Is this ready for review? I see a hold label

**Comment by aledbf** [comment]
@princerachit yes, ready for review

**Comment by princerachit** [comment]
When I do a local port forward I see a 404 error. With the external IP it gets stuck. I do not see unauthorized error. am I doing something incorrect?

image

**Review by princerachit — APPROVED** [review]
approving as it is aligned with changes in other files. code lgtm

**Pull request merged**
