### PR TITLE
Wait until k3s apiserver is ready

### PR DESCRIPTION
**Pull request by meysholdt**
## Description
Wait until k3s ApiServer is ready before we interact with k3s.

## Related Issue(s)
Fixes # https://github.com/gitpod-io/gitpod/issues/8680

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by meysholdt** [comment]
I am inclined to check both the api-server and the the kube-system-pod readiness, because there are pods that may not be reflected by the api-server:
```
$ kubectl wait --for=condition=Ready pods --all -n kube-system --timeout=300s
pod/calico-kube-controllers-85b5b5888d-tp27k condition met
pod/calico-node-6dsr9 condition met
pod/coredns-5789895cd-lntlh condition met
pod/local-path-provisioner-6c79684f77-l4zcz condition met
pod/metrics-server-d986f9c8d-rbfxl condition met
```

**Review by ArthurSens — APPROVED** [review]

**Pull request merged**
