### PR TITLE
Use static / non-animated Gitpod cube when workspace is stopped

### PR DESCRIPTION
**Pull request by corneliusludmann**

### CODE REVIEW

**Comment by csweichel** [comment]
I very much like the idea to use the "dynamic" cube whenever the workspace is "active" (is starting/stopping).

The way it's implemented looks a bit odd though. When the workspace stops the cube changes drastically.
Screen Recording 2020-10-12 at 09 28 24

Instead of falling back to the svg, how about we just stopped the animation? I.e. removed the motion and "lights" from the boot animation.

**Comment by corneliusludmann** [comment]
> I very much like the idea to use the "dynamic" cube whenever the workspace is "active" (is starting/stopping).

Thanks for having a look. This PR was a Friday afternoon quicky because I stumbled on it several times when I thought the workspace didn't have stopped yet due to this IMO misleading animation.

> The way it's implemented looks a bit odd though. When the workspace stops the cube changes drastically.

> Instead of falling back to the svg, how about we just stopped the animation? I.e. removed the motion and "lights" from the boot animation.

I couldn't find a simple solution to stop the animation without spending some time investigating this. If you have a spontaneous idea, please let me know!

I also don't find the abrupt change sooo bad. Usually, I don't look at it all the time but come back later and see that the workspace has been stopped. Sure, a smoother transition would be great but nothing I would like to spend to much time now.

However, with your big monitor, these are even worse than with me. I changed the CSS of the static image to fix the position and the size. Now, the cube it as least at the same position and (hopefully) has a similar size.

Peek 2020-10-12 15-39

If you are uncomfortable with merging it this way, then we can put it on hold for now and I will withdraw the PR. Apart from that, I think it is at least functionally better than before.

**Comment by csweichel** [comment]
At least with my resolution this really doesn't look nice.
Stopping the animation shouldn't be that hard. We already pass a flag in the WebGL program for the color in case of an error. I reckon that we could just pass in a "motion factor" that we multiply the phase of `sin`/`cos` in the animation with. When set to zero that would effectively disable the animation.

**Comment by corneliusludmann** [comment]
OK, you got me. Took another look at `bootanimation.ts`. Wasn't hard at all. Now I think we have a clean solution. What do you think?

**Review by svenefftinge — APPROVED** [review]
LGTM

**Pull request merged**
