### PR TITLE
[server] warn when resolve image is unsuccessful

### PR DESCRIPTION
**Pull request by kylos101**
## Description

Related to  https://www.gitpodstatus.com/incidents/86797qj4xnfj

## Related Issue(s)

Related to ENG-470

## How to test

Resolve workspace which are not successful are logged [like so](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-07-18T20:47:20.653435338Z;duration=PT30M;lfeCustomFields=jsonPayload%252FserviceContext%252Fservice;query=--%20without%20protected_secrets%20enabled%0AjsonPayload.kubernetes.host%3D%22preview-kylos101-r084e4a319a%22%0A%22Resolve%20workspace%20was%20unsuccessful%22%0Atimestamp%3D%222023-07-18T20:47:20.653435338Z%22%0AinsertId%3D%221rjxhiaffuwkpn%22;summaryFields=jsonPayload%252Fseverity,jsonPayload%252FserviceContext%252Fservice:false:32:beginning?project=gitpod-core-dev).

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - kylos101-r084e4a319a</li>
	<li><b>🔗 URL</b> - <a href="https://kylos101-r084e4a319a.preview.gitpod-dev.com/workspaces" target="_blank">kylos101-r084e4a319a.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - kylos101-resolve-warning-gha.13727</li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`
- [ ] with-monitoring
</details>

### CODE REVIEW

**Comment by kylos101** [comment]
imagebuild fails with:
```
error: failed to solve: failed to compute cache key: failed to copy: write /workspace/buildkit/runc-overlayfs/content/ingest/1e84794fc11c7e68b408730bb535610e61679c90948a1ced36756cb193592281/data: no space left on device
```

**Comment by kylos101** [comment]
> imagebuild fails with:
> 
> ```
> error: failed to solve: failed to compute cache key: failed to copy: write /workspace/buildkit/runc-overlayfs/content/ingest/1e84794fc11c7e68b408730bb535610e61679c90948a1ced36756cb193592281/data: no space left on device
> ```

Deleting via `leeway run dev/preview:delete-preview`, and then recreating via `leeway run dev:preview`.

**Comment by kylos101** [comment]
@AlexTugarev I removed the hold as we talked about this earlier today, and this way this can be considered for deploy while I sleep.

**Comment by kylos101** [comment]
@jankeromnes and @akosyakov for :eyes:  Re: https://www.gitpodstatus.com/incidents/86797qj4xnfj

**Review by akosyakov — APPROVED** [review]

**Review by AlexTugarev — APPROVED** [review]

**Pull request merged**
