### PR TITLE
[server] Guard against bogus RPC method names

### PR DESCRIPTION
**Pull request by geropl**
## Related Issue(s)

Fixes #

## How to test
 - singup to the preview env
 - start a workspace, and see that everything works as usual

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Review by AlexTugarev — APPROVED** [review]
Tested with starting workspaces and navigating the dashboard. ✔️ 

Also, calling methods marked as protected doesn't work as expected. ✔️ 
```
{"jsonrpc":"2.0","id":13,"error":{"code":400,"message":"Unknown method 'getAccessibleProjects'"}}
```

**Comment by AlexTugarev** [comment]
@geropl, manual test looks good. I wasn't sure, if the PR status is correct. Wanna merge?

**Comment by geropl** [comment]
> manual test looks good. I wasn't sure, if the PR status is correct. Wanna merge?

Thank you @AlexTugarev ! Was waiting for the preview env, but I guess that's done now :-D :point_right: :radio_button:

**Pull request merged**
