### PR TITLE
[usage] smaller UI improvements

### LINKED ISSUE #12803: Indicate current usage period in usage view, and show text when empty
The screenshot below shows usage after clicking on `August` to show usage for August.

- the currently selected period (August) should have a grey background
- the main list area should say `No billed usage for this period.`

Screenshot 2022-09-09 at 09 20 16

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description
Three small UI improvmeents on the usage view:

 - format the total usage number
 - show proper time plus an indicator for running sessions
 - show `No sessions found` on empty list
 - show viewed range

## Related Issue(s)

Fixes #12803

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview
- [x] /werft with-payment

### CODE REVIEW

**Comment by roboquat** [comment]
@svenefftinge: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by andrew-farries — APPROVED** [review]

**Comment by easyCZ** [comment]
Thanks for this. I was just about to cut a ticket for the no results issue.

**Comment by svenefftinge** [comment]
I think the build failed because it couldn't remove some workspace pods. The preview environment is running though.
Here's the invite to team gitpod. https://se-small-u7fbb36847c.preview.gitpod-dev.com/teams/join?inviteId=19a93561-1977-4004-ac68-f870319f3458

Screenshot 2022-09-12 at 13 33 58

**Comment by mads-hartmann** [comment]
@svenefftinge When using the `/werft` command from GH comments you don't need the `--` as Werft will include that in the attribute name so it becomes "--with-clean-slate-deployment` (including `--). See screenshot

Screenshot 2022-09-13 at 09 47 44

**Pull request merged**
