### PR TITLE
[code] update code stable to align all proposal apis

### PR DESCRIPTION
**Pull request by mustard-mh**
## Description

Update code stable to align all proposal apis, code changes according to [Werft result](https://werft.gitpod-dev.com/job/gitpod-build-hw-js-debug.1/results) of [branch](https://github.com/gitpod-io/gitpod/tree/hw/js-debug) which point codeCommit to `gp-code/release/1.71` [[1](https://github.com/gitpod-io/openvscode-server/tree/gp-code/release/1.71)]

## Related Issue(s)

Relates https://github.com/gitpod-io/gitpod/issues/12470

## How to test

- Open workspace in prev env with stable code
- Check if commit hash in `About` is `d96dc4787a7132bffb7d736e96a0b73469a9517e`
- Check `Output` section in terminal area, search with `js-debug` confirm that there is no errors about it

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by mustard-mh** [comment]
image

**Comment by mustard-mh** [comment]
@iQQBot Are you still available to review? I have post the test result in comment

**Review by jeanp413 — APPROVED** [review]

**Pull request merged**
