### PR TITLE
Fixes #10261: Stop running workspaces on logout

### LINKED ISSUE #10261: Stop running workspaces on log out
### Bug description

For security reasons, running workspaces should be stopped on GitPod log out.

### Steps to reproduce

1. Log in to gitpod.io
2. Start a workspace
3. Log out using the avatar dropdown on gitpod.io/workspaces
4. Verify the workspace is still running

### Workspace affected

_No response_

### Expected behavior

When user explicitly logs out, they expect all active sessions to their GitPod account are terminated. Otherwise, the next user of the same machine would be able to access first user's private data (like GitHub token, environment variables, etc).

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by charleswhchan**
## Description
Stop running workspaces when a user logout from Gitpod dashboard. Benefits:
- minimize resource waste by stopping workspaces (containers) as soon as user logout, and
- improve security and avoid an other user from accessing the workspace from the same machine browser

## Related Issue(s)
Fixes #10261 

## How to test
1. Log in to gitpod.io
2. Start a workspace
3. Log out using the avatar dropdown on gitpod.io/workspaces
4. Verify the workspace(s) are stopped

## Release Notes

```release-note
stop running workspaces on logout
```

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

/hold

### CODE REVIEW

**Comment by roboquat** [comment]
@charleswhchan: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by gtsiolis** [comment]
Thanks for contributing, @charleswhchan! 🍊 

Did you know that all workspaces stop after 5 minutes of inactivity? See [relevant docs](https://www.gitpod.io/docs/configure/workspaces/workspace-lifecycle#editor-or-ide-disconnect):

> All inactivity timeouts are dependent on an active editor or IDE connection. Closing your Gitpod connected editor or IDE will reduce the workspace timeout to 5 minutes unless an explicit workspace inactivity timeout is set via user preference, or via the Gitpod CLI.

Let me loop in @atduarte, @geropl, and @svenefftinge for a second opinion on this.

**Comment by charleswhchan** [comment]
@gtsiolis: I didn't know about that, so that's for pointing this out.

However, I am not really sure that setting serves the same purpose and provides the same level of security protection. A user can have 2 windows/tabs open:
- have the dashboard open in first window
- have an IDE session open in second window
- user logout from dashboard in first window
- user can continue to use IDE in second window (and continue to extend the workspace timeout until a deadline)

> Expected behavior: (from #10261)
> When user explicitly logs out, they expect all active sessions to their GitPod account are terminated. Otherwise, the next user of the same machine would be able to access first user's private data (like GitHub token, environment variables, etc).

Look forward to hearing back from the team!

**Comment by svenefftinge** [comment]
Thanks @charleswhchan. I'm finishing (resolving conflicts) this [here](https://github.com/gitpod-io/gitpod/pull/17383).

**Comment by charleswhchan** [comment]
#17383 looks much better than my PR. 😄
Thank you @svenefftinge for finishing it off! 🎉

**Pull request closed without merging**
