### PR TITLE
Add tiny load testing script

### PR DESCRIPTION
**Pull request by mads-hartmann**
## Description

This introduces a tiny script for running load tests against our VM-based preview environments. It prepares a base branch with an empty commit that contains `/werft with-vm` and then pushes as many branches as you have requested so that Werft will run the build job and thus create a VM and deploy Gitpod to it.

The base branch is based off the current branch, that means you can use this to create load tests based on whatever is configured on your branch. E.g. if we wanted to run the load test using a separate VM image than what we have on main then we'd just create a branch where we switch the VM image and then run the load script from that branch.

## Related Issue(s)

Fixes https://github.com/gitpod-io/ops/issues/1215

## How to test

If you just want to try it out you can use it to trigger a single VM with the following.

```
./dev/preview/test/load-test.sh --base-branch-name your-name-vm-load-test --start 1 --end 1
```

I have used this script quite a few times to run small loads tests against Harvester. You can see one analysis of running the script here ([internal link](https://www.notion.so/gitpod/Harvester-tiny-load-test-1b449ab34d1a4d5b9b99a4743b740194)). 

## Release Notes

```release-note
NONE
```

## Documentation

N/A

### CODE REVIEW

**Review by ArthurSens — APPROVED** [review]
Simple yet effective 🚀

**Comment by kylos101** [comment]
/hold

This may be blocking Tide and other PRs from merging.

image

**Comment by kylos101** [comment]
/unhold 

the queue has been processed, let's see if this auto merges now?

**Comment by kylos101** [comment]
Good catch @ArthurSens.

**Comment by ArthurSens** [comment]
Since this change has nothing to do with preview at all, I assume the failure is due to flakyness. Running a job without preview just to the the green lights ✅ 

/werft run no-preview

**Pull request merged**
