### PR TITLE
[bridge] Mark all workspaces as stopped on forced deregisteration

### PR DESCRIPTION
**Pull request by geropl**
## Description
We want to avoid that we keep zombie workspace instances in the DB that are not stopped. To achieve this, we already setting up controllers. But sometimes there is a cases (especially with test clusters) where we simply want to forcefully want to shut down a whole cluster. So far, this created zombie instances that we don't catch yet.

This PR introduces a change in behavior in `gpctl clusters deregister --force` and instead of just logging the zombie-to-be-instances, it forcefully shuts those down.

## Related Issue(s)

Fixes parts of #6770

## How to test
 1. copy the preview-env local bridge over to the `d_b_workspace_cluster` table
 2. start a workspace
 3. run `gpctl clusters deregister --force` and note how the workspace is marked as `stopped` in the DB

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-preview with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by easyCZ** [comment]
In this PR, we introduce a direct trigger to the cluster deregistration to force stop the instances. 

Is it possible to not need the direct trigger for the clean-up? What I mean is would it be possible to setup a controller which does the following:
1. Runs on relatively short schedule
2. Look at all configured clusters
3. Find the set of clusters for all WorkspaceInstances
4. Diff the sets, force-stopping any instances which are on clusters which 
	* Do not exist
	* Are not marked as "drain" or similar

This has the benefit of not relying on the direct deregistration. This is beneficial as it reduces dependencies, allows the deregistration to complete faster, and gives us the "invariant" that eventually all instances on unknown clusters get terminated, irrespective if the `gpctl` tool was used. This can be useful for cases when either the tool is broken or other scenarios happen.

**Comment by geropl** [comment]
> Is it possible to not need the direct trigger for the clean-up?

Jep, that's the ideal solution. And I've come to the conclusion that this PR as-is is 1)unnecessary and 2) dangerous.

> Diff the sets, force-stopping any instances which are on clusters which [...]

It's a tiny bit more complicated, because we for sure also want to have a timeout component in this to guarantee stability. Also, because it's currently impossible to know "all registered clusters". But that will change rather soon with the PRs from @andrew-farries .Once that's in I'll come up with a suggestion!

**Comment by easyCZ** [comment]
> It's a tiny bit more complicated, because we for sure also want to have a timeout component in this to guarantee stability.

Of course, it always is. The above was largely to communicate the idea rather than be exhaustive about the behaviour :)

**Pull request closed without merging**
