### PR TITLE
Update button and navigation styles

### PR DESCRIPTION
**Pull request by gtsiolis**
## Description

Style updates for the primary button, see [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1676389006231579) (internal).

## How to test
Navigate through the dashboard and notice how the new button looks and feels alongside with the toned down top navigation. Notice how there's always only one CTA (call-to-action) per context with the strongest visual emphasis.

| BEFORE | AFTER |
|-|-|
| Screenshot 2023-02-16 at 17 38 40 | Screenshot 2023-02-16 at 17 38 32 |
| Screenshot 2023-02-16 at 17 37 51 (2) | Screenshot 2023-02-16 at 17 38 00 (2) |
| Screenshot 2023-02-16 at 17 36 54 (2) | Screenshot 2023-02-16 at 17 38 10 (2) |
 
## Release Notes

```release-note
Update button and navigation styles
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-slow-database
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [X] /werft with-preview
- [x] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by gtsiolis** [comment]
/werft run with-clean-slate-deployment=true with-preview=true recreate-vm=true

**Comment by gtsiolis** [comment]
/werft run with-clean-slate-deployment=true with-preview=true recreate-vm=true

**Comment by gtsiolis** [comment]
/werft run with-clean-slate-deployment=true with-preview=true recreate-vm=true

**Comment by geropl** [comment]
@gtsiolis Although I saw the internal discussion, I'm not sure everybody is aligned yet. Also, I feel product should ultimately decide.
Would it make sense to hold this PR until then?

**Comment by gtsiolis** [comment]
DEAL—Let's hold this for now until concensus is reached. Thanks for the nudge, @geropl.

/hold

**Comment by gtsiolis** [comment]
/werft run with-clean-slate-deployment=true with-preview=true recreate-vm=true

**Pull request closed without merging**
