### PR TITLE
feat(db): update examples in the dashboard

### PR DESCRIPTION
**Pull request by ghuntley**
- [x] re-establish quickstart template naming convention (`template-language/framework`)
- [x] create new quickstart templates for
	- [x] Ruby on Rails (https://github.com/gitpod-io/template-ruby-on-rails-postgres)
	- [x] Express.js (https://github.com/gitpod-io/template-typescript-node)
	- [x] React (https://github.com/gitpod-io/template-typescript-react)
	- [x] Flask (https://github.com/gitpod-io/template-python-flask)
	- [x] Laravel (https://github.com/gitpod-io/template-php-laravel-mysql)
	- [x] Drupal (https://github.com/gitpod-io/template-php-drupal-ddev)
- [x] rename references in https://www.gitpod.io/docs/quickstart
  - [x] Express.js (https://github.com/gitpod-io/website/pull/598)
- [x] add new references to https://www.gitpod.io/docs/quickstart
  - [x] Ruby on Rails (https://github.com/gitpod-io/website/pull/614)
  - [x] React & Flask (https://github.com/gitpod-io/website/pull/598)
  - [x] Laravel (https://github.com/gitpod-io/website/pull/614)
  - [x] Drupal (https://github.com/gitpod-io/website/pull/614)
- [x] publish these quickstart templates in the dashboard

### CODE REVIEW

**Comment by ghuntley** [comment]
🎗 rename references in https://www.gitpod.io/docs/quickstart as well.

**Comment by ghuntley** [comment]
Supersedes https://github.com/gitpod-io/gitpod/pull/4407

**Comment by svenefftinge** [comment]
Can we order them by popularity? It doesn't need to be 100% accurate but starting out with C# seems a bit off.
JavaScript, Python, Java, PHP, Ruby, etc. seems to be more reasonable.
The list is not in sync with the one on the website atm.

**Comment by mikenikles** [comment]
@svenefftinge I adjusted the sort order and we're tracking the updates to the website in https://github.com/gitpod-io/website/issues/654. If you're 👍 for this PR, please approve and merge 🙏.

**Comment by ghuntley** [comment]
Thanks Mike!

**Review by svenefftinge — APPROVED** [review]

**Pull request merged**
