### PR TITLE
feat(dashboard): redirect /memes to the website

### PR DESCRIPTION
**Pull request by ghuntley**
## Description

It turns out folks are starting to create Gitpod memes. Let's collect them!

## Related Issue(s)

Relates to https://github.com/gitpod-io/website/pull/1281
Relates to https://github.com/gitpod-io/gitpod/issues/6877

## How to test

/memes should head to our website once https://github.com/gitpod-io/website/pull/1281 is merged.

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jldec** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jldec` in a comment when ready.

Associated issue: *#6877*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by JanKoehnlein** [comment]
We should then also add it to the [FORBIDDEN_SLUGS](https://github.com/gitpod-io/gitpod/blob/5d751e330d37680e6b6ab5cf6ef7b5e9496f71be/components/gitpod-db/src/typeorm/team-db-impl.ts#L19), shouldn't we? Is that worth it?

**Comment by gtsiolis** [comment]
> We should then also add it to the FORBIDDEN_SLUGS, shouldn't we?

@JanKoehnlein I could be wrong but now that we have a dedicated slug (`/t/:team`) for teams (see https://github.com/gitpod-io/gitpod/pull/5544), maybe there's no need to use a fixed list of forbidden slugs and we could potentially remove this list, no? Cc @AlexTugarev @svenefftinge

**Comment by JanKoehnlein** [comment]
@gtsiolis Yes, you're right, thanks

/lgtm

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 00cc4c8752827211ac0de3d4919407c39dbe65bc</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6878#issuecomment-980030026" title="LGTM">JanKoehnlein</a>*

Associated issue: *#6877*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [JanKoehnlein]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6878#issuecomment-980033289" title="Approved">JanKoehnlein</a>*

Associated issue: *#6877*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [JanKoehnlein]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
