### PR TITLE
Update telepresence in dev environment

### PR DESCRIPTION
**Pull request by AlexTugarev**
This change updates telepresence to version `0.109`.

### CODE REVIEW

**Comment by AlexTugarev** [comment]
accidentally closed by force-pushing 🤦🏻

**Comment by AlexTugarev** [comment]
Thanks @csweichel! I'm happy to update after #3388 was merged.

**Review by geropl — APPROVED** [review]
Nice, thx!

(as Chris said: Image needs to be re-build)

**Comment by AlexTugarev** [comment]
@geropl, just did so :-)

**Review by geropl — APPROVED** [review]
:heart:

**Pull request merged**
