### PR TITLE
[usage] Implement charge dispute handling - WEB-94

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

Uses the User & Team service to block owners when a dispute is raised.

* Uses `go-vcr` to record a Stripe response with a hook to drop authorization

## Related Issue(s)

* Depends on https://github.com/gitpod-io/gitpod/pull/17034
* Depends on https://github.com/gitpod-io/gitpod/pull/17094

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

/hold

### CODE REVIEW

**Comment by atduarte** [comment]
/reviewpad robin prompt can you find any issue with the OnChargeDispute function logic?

**Review by svenefftinge — APPROVED** [review]
LGTM - Also nice testing setup!
FWIW it doesn't feel great to have a bidirectional dep between server and usage but I guess we'll have to live with it given our architecture. 🤷

**Comment by easyCZ** [comment]
> FWIW it doesn't feel great to have a bidirectional dep between server and usage but I guess we'll have to live with it given our architecture. 🤷

Agree. I'm hoping we can fix the "leadership election" part and merge usage with PAPI. It doesn't remove the bi-directionality, but at least it consolidates it closer to the desired architecture.

**Review by akosyakov — APPROVED** [review]

**Pull request merged**
