### PR TITLE
Update debug script

### PR DESCRIPTION
**Pull request by Furisto**
## Description
- Add required parameter ImageRepoBase
- Bail out if one of the steps fail
- Ensure history of images is kept, so that one can easily switch back to a previous image

## Related Issue(s)
n.a.

## How to test
- Call debug.sh 

## Release Notes
```release-note
NONE
```
/werft no-preview

### CODE REVIEW

**Review by sagor999 — APPROVED** [review]

**Comment by Furisto** [comment]
Yeah, it is just a problem with issuing the certificates

**Comment by mustard-mh** [comment]
/hold
this block merge pool

**Pull request merged**
