### PR TITLE
Start dockerd without experimental flag

### PR DESCRIPTION
**Pull request by Furisto**
## Description
Start dockerd in the workspace without --experimental flag. We originally needed this to support rootless, but it graduated in v20.10

## Related Issue(s)
n.a.

## How to test
- [Browse to preview environment](https://fo-dockerd-exp-flag.staging.gitpod-dev.com/workspaces)
- Open workspace
- Run `docker run busybox sh`
-> this should just work

## Release Notes
```release-note
None
```

### CODE REVIEW

**Comment by sagor999** [comment]
Do we have any tests to verify docker functionality? I am asking because we are upgrading major version of docker here, and there could be unexpected breaking changes or side effects.

**Review by kylos101 — CHANGES_REQUESTED** [review]
Updated the instructions to specify to use this preview environment for testing . ;)

When testing from the preview environment, I see experimental is off on the server (woo hoo!), on for the client (dang), and the versions do not match `20.10.14`. :thinking: 

```
gitpod /workspace/template-python-flask (main) $ which docker
/usr/bin/docker
gitpod /workspace/template-python-flask (main) $ docker version
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.13
  GitCommit:        9cc61520f4cd876b86e77edfeb88fbcd536d1f9d
 gitpod:
  Version:          1.1.0
  GitCommit:        v1.1.0-0-g067aaf85
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
gitpod /workspace/template-python-flask (main) $ docker run busybox sh
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
554879bb3004: Pull complete 
Digest: sha256:caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a
Status: Downloaded newer image for busybox:latest
```

Tested with docker that ships with workspace-images too:
```
gitpod /workspace/template-python-flask (main) $ /bin/docker version
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.13
  GitCommit:        9cc61520f4cd876b86e77edfeb88fbcd536d1f9d
 gitpod:
  Version:          1.1.0
  GitCommit:        v1.1.0-0-g067aaf85
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

References:
[docker cli](https://docs.docker.com/engine/reference/commandline/cli/#experimental-features)
[dockerd cli](https://docs.docker.com/engine/reference/commandline/dockerd/#description)

@sagor999 I recall @utam0k made some docker integration tests recently, but last time I ran them I believe they failed. That said, given the version info I am seeing, I do not think it's a truly a major version upgrade, persay. 

@Furisto is there a burning need to change this now, or can it wait? I feel like even though this file suggests that we're using 19, we may actually be using 20.

**Comment by utam0k** [comment]
This version specification is the version that will be installed when these binaries aren't present in the user's workspace. Therefore, if the workspace image contains a docker, the specified version will not be installed.
https://github.com/gitpod-io/gitpod/blob/a6e23165ae0bd7dda4b7e411cb33edaa17f9df2b/components/docker-up/docker-up/main.go#L282-L287

**Comment by utam0k** [comment]
We can guarantee our version by using the binaries we find, performing a version check and overwriting them if they are below the specified version. However, there may be a better way.

**Comment by csweichel** [comment]
> I want to know if we continue use --experimental, will there be any impact?

Totally agree with this. The driver for this change primarily is optics, which is not enough of a reason to incur complexity. If this had been an easy/straight forward change it would have been worth it. Doesn't look like that though.

I'd vote for closing this now and revisiting the change in a month or two.

**Comment by kylos101** [comment]
Closing in favor of https://github.com/gitpod-io/gitpod/issues/9181, which is currently in our inbox. @Furisto thank you very much for socializing this and sharing with the team. :pray:

**Pull request closed without merging**
