### PR TITLE
[server] Move payment/stripe out of EE, remove EE

### PR DESCRIPTION
**Pull request by easyCZ**
## Related Issue(s)

* Depends on https://github.com/gitpod-io/gitpod/pull/17354

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - mp-server-831f71db0d</li>
	<li><b>🔗 URL</b> - <a href="https://mp-server-831f71db0d.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-831f71db0d.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
</ul>

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

/hold

### CODE REVIEW

**Comment by geropl** [comment]
Starting to review now...

**Comment by geropl** [comment]
Wooo-hoo, that was a tour de force :laughing: Mainly do identify this was a big move op. But LGTM so far!

Took the liberty to push a [minor fix](https://github.com/gitpod-io/gitpod/pull/17357/commits/8e22ec5d1cf2e63961686bbaf994280f5d62903a), which should make the server runnable. Will continue testing in the preview once it's there. :+1:

**Review by geropl — APPROVED** [review]
@easyCZ Code LGTM, tested and works!

I could:
- start workspaces
- upgrade to paid, and benefit from the features

:heavy_check_mark: Do you want to test anything else?

**Comment by easyCZ** [comment]
@geropl Given it should be mostly structural changes, rather than semantic, I think the above test flow covers it. If it goes wrong, we can rollback the change entirely

**Pull request merged**
