### PR TITLE
[dashboard] show error message on new project for Bitbucket-only users

### LINKED ISSUE #6345: New Project page should show message and link to /workspaces when authorized only with Bitbucket
### Bug description

Teams & Projects rolled out with support for GitLab and GitHub projects. The natural next step here is to add support for adding projects from Bitbucket.org git provider, see https://github.com/gitpod-io/gitpod/issues/5980.

However, if you have a Gitpod account that is only connected with a Bitbucket account, adding a project is not possible, see screenshot below.

Screenshot 2021-11-04 at 14 26 39

### Steps to reproduce

1. Create an account on Gitpod with Bitbucket
2. Try adding a project

### Workspace affected

_No response_

### Expected behavior

Instead of the error while showing loading, show the following message

> We are still working working on Bitbucket support for Projects.
> Continue to [workspaces](), or login with GitHub or GitLab to use Projects.   

This ☝️ is a variant of what was proposed originally. 👇 -- thanks  @gtsiolis

> Possibly, if we move forward with fixing this before https://github.com/gitpod-io/gitpod/issues/5980, we could redirect to an error page and informing the user to connect a supported git provider for adding projects. 💡 ~~

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JanKoehnlein**
## Description
Show a message that Bitbucket is not yet supported instead of silently failing for Bitbucket-only users on _New Project_ page.

## Related Issue(s)
Fixes #6345

## How to test
- Log in with a Bitbucket only account
- Open to /new

## Release Notes
```release-note
Bitbucket-only users get an error message now on _New Project_ page
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jankoehnlein** after the PR has been reviewed.

Associated issue: *#6345*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by gtsiolis** [comment]
Re-deploying as Bitbucket is now enabled on preview environments, see [relevant discussion](https://gitpod.slack.com/archives/C01KGM9EBD4/p1636993758304200) (internal).

/werft run

**Review by gtsiolis — COMMENTED** [review]
Gave this an early look! 👀 

@JanKoehnlein What do you think of using the same flow, component, and an alert for providing this feedback to the user instead of leading users to this error page?

| BEFORE | CURRENT | PROPOSAL |
|-|-|-|
| Screenshot 2021-11-17 at 7 22 25 PM (2) | Screenshot 2021-11-17 at 7 30 45 PM (2) | Screenshot 2021-11-17 at 7 28 03 PM (2) |

Cc @jldec since you've added the error page proposal https://github.com/gitpod-io/gitpod/issues/6345. 📝 

Cc @laushinka @geropl @jankeromnes @AlexTugarev in case you have any feebdack on this. 🔮

**Comment by JanKoehnlein** [comment]
@gtsiolis absolutely. This PR is still draft mode because I did a very quick first shot at that and when I tried to look at it the preview env was broken. I can look at that between the meetings today.

**Comment by AlexTugarev** [comment]
I think an entry is missing in https://github.com/gitpod-io/gitpod/blob/9d54786aff9453439a75e0854c3a00cd2261cac3/components/dashboard/src/projects/NewProject.tsx#L435

**Review by geropl — APPROVED** [review]
Tested, LGTM:

image


@AlexTugarev I think this is by design (see screenshot).

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6652#pullrequestreview-810985387" title="Approved">geropl</a>*

Associated issue: *#6345*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [geropl]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: e5f6cc0e787f664e106f1e6258c87bd5f04f047f</details>

**Comment by geropl** [comment]
Whoops, should be a comment :grimacing: But IMO fine anyway. Can create a small follow-up PR if needed @AlexTugarev

**Pull request merged**
