### PR TITLE
[ws-manager] Stop workspaces timing out during backup

### LINKED ISSUE #4937: [ws-manager] Properly stop workspaces that time out during backup
### Bug description

Right now when a workspace times out during backup it remains "stuck in terminating" because we don't set the disposal status annotation, and hence don't remove the finalizer.

### Steps to reproduce

Have the workspace time out in backup, e.g. due to a ws-daemon failure.

### Expected behavior

The workspace should stop properly.

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by csweichel**
Prior to this change workspaces that timed out during backup would never actually stop. Also, the `contentFinalization` timeout was not used during backup.

### How to test
1. Start a workspace
2. Change the `contentFinalization` timeout in `ws-manager-config` to `1s` (quicker testing)
3. Restart ws-manager
4. Once the workspace is running remove ws-daemon (e.g. edit the daemonSet's `affinity`)
5. Stop the workspace

You should see the workspace actually stopping, e.g.
image

fixes #4937

Note: this change will affect prod configuration, as we're now using the correct timeout for content finalization/backup (15m instead of 1h).
/cc @meysholdt

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4943#" title="Author self-approved">csweichel</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
While testing I see the screen above (timeout) but the pod is still dangling in "Terminating". Last line of the ws log is:
```
{"exitCode":0,"level":"debug","message":"supervisor exit","serviceContext":{"service":"supervisor","version":""},"severity":"DEBUG","time":"2021-07-26T08:22:31Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /.workspace/daemon.sock: connect: connection refused\"","level":"error","message":"cannot trigger teardown","ring":0,"serviceContext":{"service":"workspacekit","version":""},"severity":"ERROR","time":"2021-07-26T08:22:31Z"}
```

**Comment by csweichel** [comment]
during offline discussion with @meysholdt we figured that for now we should match the prior 1h timeout for `contentFinalization`

**Comment by csweichel** [comment]
> While testing I see the screen above (timeout) but the pod is still dangling in "Terminating". Last line of the ws log is:
> 
> ```
> {"exitCode":0,"level":"debug","message":"supervisor exit","serviceContext":{"service":"supervisor","version":""},"severity":"DEBUG","time":"2021-07-26T08:22:31Z"}
> {"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /.workspace/daemon.sock: connect: connection refused\"","level":"error","message":"cannot trigger teardown","ring":0,"serviceContext":{"service":"workspacekit","version":""},"severity":"ERROR","time":"2021-07-26T08:22:31Z"}
> ```

This strikes me as a separate issue because this PR does not change that behaviour. I have filed https://github.com/gitpod-io/gitpod/issues/4955

**Comment by csweichel** [comment]
/hold

need to update timeout

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4943#" title="Author self-approved">csweichel</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [csweichel]
- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by geropl — APPROVED** [review]
Code LGTM, tested and works as expected.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 955eee5239067876259569ec38bbd79235991c16</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4943#" title="Author self-approved">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4943#pullrequestreview-714897355" title="Approved">geropl</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [csweichel,geropl]
- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
