### PR TITLE
[code] upgrade stable code with ports onOpen fix

### PR DESCRIPTION
**Pull request by mustard-mh**
## Description

Updates stable VS Code Web to 1.69.0 with 
- https://github.com/gitpod-io/openvscode-server/pull/379 picked

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/issues/11243

## How to test

See How to Test section in https://github.com/gitpod-io/openvscode-server/pull/379

## Release Notes

```release-note
[code] fix `.gitpod.yml` ports onOpen not work on workspace startup
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by jeanp413** [comment]
/hold
in case you want to do a final test @mustard-mh

**Comment by mustard-mh** [comment]
Works

|Remote Explorer|Ports|
|-|-|
|SCR-20220712-5n4|SCR-20220712-5o4|

**Pull request merged**
