### PR TITLE
Track git branches during initial checkout

### PR DESCRIPTION
**Pull request by aledbf**
## Description

Partially reverts #13053 due to not tracking remote branches, something that impacts the commit used in the workspace (not the last one)

Internal report https://gitpod.slack.com/archives/C01KGM9BH54/p1663846572842519

## How to test
- Open a workspace using a branch [https://github.com/gitpod-io/spring-petclinic/tree/ak/vmoptions_test](https://ak-plugins-vmoptions.preview.gitpod-dev.com/#https://github.com/gitpod-io/spring-petclinic/tree/ak/vmoptions_test)
## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=workspace
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@aledbf: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jenting** [comment]
cc @akosyakov

**Review by jenting — APPROVED** [review]
Test against prebuild, regular, and multiple repos. All work well.

**Pull request merged**
