### PR TITLE
[ws-manager] Refactor connectToWorkspaceDaemon

### PR DESCRIPTION
**Pull request by aledbf**
## Description

Reverts https://github.com/gitpod-io/gitpod/pull/11517 and improve error messages

Screenshot from 2022-07-26 19-14-10

## Release Notes
```release-note
NONE
```

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@aledbf: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by kylos101** [comment]
Loadgen test with scale-up:
image

**Comment by utam0k** [comment]
Why do we need to revert https://github.com/gitpod-io/gitpod/pull/11517? I ask because if we revert it, after all, we have to wait until ws-damon pod running, don't we?

**Review by kylos101 — APPROVED** [review]
:+1:

**Comment by aledbf** [comment]
> Why do we need to revert #11517? I ask because if we revert it, after all, we have to wait until ws-damon pod running, don't we?

We updated ws-daemon with the CI image.

**Comment by kylos101** [comment]
Related to #11664

**Comment by sagor999** [comment]
>We updated ws-daemon with the CI image.

I don't understand what you mean. :( 
I am also curious why the check for if pod is running is not needed or was bad?

**Comment by aledbf** [comment]
> I don't understand what you mean. :(

I am sorry. I updated the ws-daemon daemonset image using the werft image from this PR.

> I am also curious why the check for if pod is running is not needed or was bad?

It was bad. That said, we need to review the use of a pool for the connections.

**Comment by sagor999** [comment]
Sorry for being annoying, but for posterity, why was that change bad?
Since it makes sense to check if pod is in running state. Unless that ready state is floppy? Or not reliable and gives false positives somehow?

**Pull request merged**
