### PR TITLE
Update platform version from 'gateway-plugin' to target JetBrains Gateway v2022.2-Nightly

### PR DESCRIPTION
**Pull request by felladrin**
## Description

Update platform version from 'gateway-plugin' to the [nightly](https://www.jetbrains.com/intellij-repository/snapshots) (_com.jetbrains.gateway: 222-NIGHTLY-CUSTOM-SNAPSHOT_), to make use of the latest API.

Also, update the minimum version of the plugin to 222.3048.1, so it can only be installed on new gateway versions (2022.2+) downloaded from https://www.jetbrains.com/remote-development/gateway/ after June 16 2022.
Gateway 2022.1 (221) will is not going to receive new features.

## Related Issue(s)

Follow-up for #10505

## How to test

- Download JetBrains Gateway from https://www.jetbrains.com/remote-development/gateway/ - The download button of this page actually downloads EAP Version. (At the moment of writing, the latest EAP version is 222.3048.1)
- Download the gateway-plugin version built on this PR from https://plugins.jetbrains.com/plugin/18438-gitpod-gateway/versions/dev: get the most recent one containing the title "Gitpod Gateway 0.0.1-felladrin-update-gw-platform"
- Install it (using the "Install plugin from disk" option) on JetBrains Gateway EAP
- Restart the Gateway
- Confirm if the extension is running fine (create a new workspace, connect to a running workspace, change Gitpod Host setting)

## Release Notes

```release-note
NONE
```

## Documentation

- [x] /werft --no-preview=true --clean-slate-deployment=true

### CODE REVIEW

**Review by mustard-mh — COMMENTED** [review]
I tried with Gateway v2022.1.x, install failed as expected.

image

But with Gateway v2022.2 EAP, connect to workspace not works. (My host is `gitpod.io`)

|Plugin Installed| Connect Failed |
|-|-|
|image|image|

**Comment by felladrin** [comment]
Updated. Note: Now it will work only with Gateway v222.3048.1 or later.

**Comment by akosyakov** [comment]
What is the state of this PR? @felladrin @mustard-mh

**Review by mustard-mh — APPROVED** [review]
New plugin version `0.0.1-felladrin-update-gw-platform.7` works for Gateway EAP 2022.2 now

image

**Pull request merged**
