### PR TITLE
Introduce '/headless-log-download' endpoint for transparent log downloads

### LINKED ISSUE #5084: Logs of completed prebuilds are not loaded due to CORS issues
### Bug description

Browser agents won't load prebuild logs from pre-signed URL like

`https://storage.googleapis.com/gitpod-prod-user-000000000000000000000000000/workspaces/teal-sadf-asdf/instances/000000-11111-22222-33333/logs/0?Expires=1628177023&GoogleAccessId=prod-meta-eu01-storage%40gitpod-191109.iam.gserviceaccount.com&Signature=`

CORS error from the network tab is `MissingAllowOriginHeader`
```
blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

cc. @geropl, @csweichel 

### Steps to reproduce

Try to access logs of a prebuild after it's done. 

### Expected behavior

CORS settings are applied to the bucket and GCS will response with the missing headers.

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by geropl**
Fixes #5084.

~ The code is there, but testing was blocked by some devstaging/imagebuild problems. :confused: ~

Added [this](https://github.com/gitpod-io/gitpod/commit/d24f0f997c1c3d234870b90cb0b533e8c7e2db07) to use the old image-builder: works.

### Test
1. go to `https://gpl-5084-download-logs.staging.gitpod-dev.com/admin/users` and give yourself the "teams-and-projects" permission
1. go to https://gpl-5084-download-logs.staging.gitpod-dev.com/teams/new, link with gitlab and create a new team (if you have no repo with prebuild: create one based on the ruby-on-rails template)
1. go to your new team on the dashboard, go to "Branches" and hit "..." -> "rerun prebuild"
1. wait until the prebuild has finished
2. go to "Prebuilds" and hit "..." -> "view prebuild"
3. see the logs without any CORS issues

**Note:** The original issue with CORS is not testable on devstaging and we should verify on staging. We can, however, test that the change did not introduce a regression.

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** after the PR has been reviewed.

Associated issue: *#5084*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/proxy/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** after the PR has been reviewed.

Associated issue: *#5084*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/proxy/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by AlexTugarev — APPROVED** [review]
LGTM!

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: c0ab61100485df23a2f3f2e1bf47359e8435bbb9</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5480#pullrequestreview-747131832" title="Approved">AlexTugarev</a>*

Associated issue: *#5084*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [AlexTugarev]
- ~~[components/proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/proxy/OWNERS)~~ [AlexTugarev]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [AlexTugarev]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5480#pullrequestreview-747131832" title="Approved">AlexTugarev</a>*

Associated issue: *#5084*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/proxy/OWNERS)~~ [AlexTugarev]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [AlexTugarev]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: ddc1716326f647eea5bc2aaf6c66330e78e33134</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5480#issuecomment-913606382" title="LGTM">AlexTugarev</a>*

Associated issue: *#5084*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/proxy/OWNERS)~~ [AlexTugarev]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [AlexTugarev]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
