### PR TITLE
[server] Fix metrics registration

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

We were calling "register default" twice

## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Review by AlexTugarev — APPROVED** [review]

**Review by geropl — APPROVED** [review]
Approving to unblock, still [subject to validation](https://github.com/gitpod-io/gitpod/pull/13231#issuecomment-1255982365), though.

**Pull request merged**
