### PR TITLE
[ws-manager-bridge] Support forced cluster dereg

### PR DESCRIPTION
**Pull request by csweichel**
## Description
This PR adds support for forced workspace cluster deregistration. 
When de-registering a cluster, ws-manager-bridge checks if there are still any workspaces which belong to this cluster and are marked as running. If we removed the cluster in this case, those instances would never again receive a status update - also the reconciliation in ws-manager-bridge would no longer act on those workspaces (the cluster is gone after all, what should we reconcile with).

With the newly added `--force` flag on gpctl, we can override this safety mechanism in exceptional cases, e.g. when introducing new workspace cluster types.

## How to test
1. Register the same ws-manager as dynamic cluster and give it a very high score
2. Start a workspace on that cluster
3. Deregister the newly added cluster - should not work without `--force`, but should work with it.

## Release Notes

```release-note
[gpctl] Support forceful cluster de-registration
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **csweichel** and additionally assign **jankoehnlein** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankoehnlein` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/OWNERS)**
- **[components/ws-manager-bridge-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge-api/OWNERS)**
- **[dev/gpctl/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/dev/gpctl/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6682#issuecomment-967023535" title="Approved">csweichel</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankoehnlein** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankoehnlein` in a comment when ready.

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/6682#issuecomment-967023535" title="Approved">csweichel</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/OWNERS)**
- ~~[components/ws-manager-bridge-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge-api/OWNERS)~~ [csweichel]
- ~~[dev/gpctl/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/dev/gpctl/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: cc1fc47b4fd6f3698a4cf56f2764cbf94e4dee5d</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6682#issuecomment-967027635" title="LGTM">aledbf</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6682#issuecomment-967023535" title="Approved">csweichel</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankoehnlein** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankoehnlein` in a comment when ready.

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/6682#issuecomment-967023535" title="Approved">csweichel</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/OWNERS)**
- ~~[components/ws-manager-bridge-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge-api/OWNERS)~~ [csweichel]
- ~~[dev/gpctl/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/dev/gpctl/OWNERS)~~ [aledbf,csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
:+1: for the PR. We just need to be aware that leaving dangling workspaces around currently breaks UX for people that started those (bc they might run into an unresolvable "max parallel workspaces" situation). We had this incident end of last week with a temporary `k3-eu102` cluster, for instance.

So fine with merging this as long as we:
 - are careful when using it
 - until we have some kind of garbage collector for "workspace that are not stopped but whose ws cluster is not available anymore (for some time)" (issue: https://github.com/gitpod-io/gitpod/issues/6770)

**Review by geropl — APPROVED** [review]
LGTM , but keep https://github.com/gitpod-io/gitpod/pull/6682#issuecomment-972798585 in mind.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6682#issuecomment-967027635" title="LGTM">aledbf</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6682#issuecomment-967023535" title="Approved">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6682#pullrequestreview-809828422" title="Approved">geropl</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/6682#issuecomment-967023535" title="Approved">csweichel</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/OWNERS)~~ [geropl]
- ~~[components/ws-manager-bridge-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge-api/OWNERS)~~ [csweichel,geropl]
- ~~[dev/gpctl/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/dev/gpctl/OWNERS)~~ [aledbf,csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
