### PR TITLE
[supervisor] Add unit tests for task composition

### LINKED ISSUE #4838: init not working as expected with pre-build
### Bug description

I currently have the following logic in place:

```
tasks:
  - before: |
      printf "\n[settings]\napi_key = $WAKA_TIME_API_KEY\n" > ~/.wakatime.cfg
    prebuild: |
      docker-compose up -d
      yarn install
      yarn run database:migrate
    command: |
      docker-compose down
      docker network prune -f
      yarn run dev
```

This works perfectly, however, the documentation is telling me `prebuild` has been deprecated and I should replace it with `init` however when I do this it doesn't rebuild the init step, it runs during startup. 

### Steps to reproduce

Gitpod up the repository:
https://gitpod.io/#https://github.com/jmcelreavey/dev-job

### Expected behavior

I would expect the GitHub pre-build functionality to see the init and run it prior to me starting the workspace

### Example repository

https://github.com/jmcelreavey/dev-job

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by csweichel**
This PR adds a bunch of unit tests to ensure we're executing the correct set of tasks given any workspace setting.

fixes #4838

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4903#" title="Author self-approved">csweichel</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/content-service/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service/OWNERS)~~ [csweichel]
- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by akosyakov — APPROVED** [review]
LGTM

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 81b40d2ba1e621ad60a744ac5375c0bb66c544a5</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4903#pullrequestreview-713400187" title="Approved">akosyakov</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4903#" title="Author self-approved">csweichel</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/content-service/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service/OWNERS)~~ [akosyakov,csweichel]
- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [akosyakov,csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
