### PR TITLE
[code] configure default layout according to the context

### LINKED ISSUE #2632: File Context is not working when using the Code editor
### Describe the bug

[File Context](https://www.gitpod.io/docs/context-urls/#file-context) is not working when using the Code editor.

> The file context is an extension to the repository context, in that Gitpod will check out the corresponding branch and open the respective file in an editor.

### Steps to reproduce

1. Enable [Feature Preview](https://www.gitpod.io/docs/feature-preview/).
1. Select Code as the [Default IDE](https://www.gitpod.io/docs/feature-preview/#default-ide).
1. For example, open https://gitpod.io/#https://github.com/gitpod-io/NextSimpleStarter/tree/master/pages.

### Expected behavior

This should expand the corresponding folder or open the selected file in the editor, as seen in Theia editor.

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #2632: configure default layout for different workspace contexts

Changes in VS Code: https://github.com/gitpod-io/vscode/pull/6

Default layout is configured only after the gitpod extension is loaded, so it can trigger some UI flickering. In order to minimize this effect we decided to avoid changing as much as possible and do only following things:
- reveal terminals and explorer, we don't preview README anymore
- preload the PR view in the pr context
- reveal file or directory in the file context

#### How to test

- In settings enable Code
- In Access Control grant access to public/private repos
- whatever you test below, at least once test how it behaves on page reload and workspace restart with changed layout:
  - branch: https://ak-code-open-context.staging.gitpod-dev.com/#https://github.com/gitpod-io/go-gin-app
    - terminals and explorer should be revealed
  - file: https://ak-code-open-context.staging.gitpod-dev.com/#https://github.com/gitpod-io/go-gin-app/blob/master/templates/footer.html
    - terminals and explorer should be revealed, file should be opened and revealed in the explorer
  - dir: https://ak-code-open-context.staging.gitpod-dev.com/#https://github.com/gitpod-io/go-gin-app/blob/master/templates
    - terminals and explorer should be revealed, dir revealed in the explorer
  - commit: https://ak-code-open-context.staging.gitpod-dev.com/#https://github.com/gitpod-io/go-gin-app/commit/421240b6504fd214c85a88ecbd889734b5532968
    - terminals and explorer should be revealed
  - issue: https://ak-code-open-context.staging.gitpod-dev.com/#https://github.com/gitpod-io/gitpod/issues/3470
    - terminals and explorer should be revealed
  - github pr: https://ak-code-open-context.staging.gitpod-dev.com/#https://github.com/gitpod-io/gitpod/pull/3465
    - terminals and explorer should be revealed, there should be a PR view preloaded in the action bar

### CODE REVIEW

**Comment by akosyakov** [comment]
TODO:
- [ ] publish latest github.vscode-pull-request-github extension to activate the review mode properly
- [ ] automatically grant access to github.vscode-pull-request-github extension (default trusted extension)

**Review by JanKoehnlein — APPROVED** [review]
LGTM

**Pull request merged**
