### PR TITLE
[image-builder-bob] update to buildkit 0.11.4

### PR DESCRIPTION
**Pull request by kylos101**
## Description

Update builtkit to https://github.com/moby/buildkit/releases/tag/v0.11.4

## Related Issue(s)

Fixes # n/a

## How to test

Integration tests pass - https://werft.gitpod-dev.com/job/gitpod-build-kylos101-gen90-deps.5

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by kylos101** [comment]
/werft run with-integration-tests=workspace with-large-vm=true with-gce-vm=true

**Comment by kylos101** [comment]
/werft run with-integration-tests=workspace with-large-vm=true with-gce-vm=true

**Comment by kylos101** [comment]
/werft run with-integration-tests=workspace with-large-vm=true with-gce-vm=true recreate-vm=true

**Comment by kylos101** [comment]
/werft run with-integration-tests=workspace with-large-vm=true recreate-vm=true

**Comment by kylos101** [comment]
@aledbf for when you come online, may I have your :heavy_check_mark:  for this? It's for the gen90 release.

**Review by easyCZ — APPROVED** [review]

**Comment by aledbf** [comment]
Are you missing the dockerfile buildkit update?

**Review by aledbf — APPROVED** [review]

**Pull request merged**
