### PR TITLE
[Installer]: configure endpoint/region of registry S3 backing

### LINKED ISSUE #9800: KOTS incluster registry S3 dialog doesn't request region
### Bug description

The S3 region defaults to "local" in the installation if one is just using S3 for the the registry backend and not anything else. In order to fix this, the deployment can be edited by hand, but a subsequent redeployment by kots when changing other settings will remove the change.

Introduced by https://github.com/gitpod-io/gitpod/pull/9701

### Steps to reproduce

Install in AWS using the getting starting guide and provide S3 credentials for the incluster registry. 

`kubectl edit deployment registry -n gitpod` 

Change region to correct region, restart just the registry deployment and it works, but doing a redeployment if making another change (or updating) will revert the change.

### Workspace affected

_No response_

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Description

There is no way to independently control the bucket configuration for the main S3 bucket and the registry's S3 backing. This introduces the configuration surface in the Installer and implements it in the KOTS installer. The registry persistence is also disabled if the S3 backing is used - this never becomes ready, so causes Helm to timeout.

There is at least one customer blocked by this. If the object storage wasn't configured and the registry S3 was, it also prevented the Helm install job from ever finishing - see [internal discussion](https://gitpod.slack.com/archives/C01KLC56NP7/p1654717329877249).

## Related Issue(s)

Fixes #9800

## How to test

Configure S3 backing for registry and the main object storage using the in-cluster option.

I have checked that there's no regression in the in-cluster repo too

## Release Notes

```release-note
[Installer]: configure endpoint/region of registry S3 backing
```

### CODE REVIEW

**Comment by roboquat** [comment]
@MrSimonEmms: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by MrSimonEmms** [comment]
This covers some of the same ground as #10208 by @nandajavarma

**Comment by nandajavarma** [comment]
@MrSimonEmms This works well! Just that now that the openSSH install PR is in, this is conflicting. Could you resolve this with a rebase?

**Pull request merged**
