### PR TITLE
flag: add BETA Label to `/tokens` page

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
> Signed-off-by: Siddhant Khare <siddhant@gitpod.io>

## Description
This PR adds a Beta Label to `/tokens` page.

|Preview (Light)|Preview(Dark)|
|---|---|
|image|image|

## Related Issue(s)

Fixes #[internal conversation](https://gitpod.slack.com/archives/C0463A2KQUU/p1670333310895679?thread_ts=1670333253.863319&cid=C0463A2KQUU)

## How to test

- Open Preview
- Go To `/tokens` & see :eyes: (if feature flag is enable for you)

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by easyCZ** [comment]
Screenshot 2022-12-07 at 8 43 27

Should the label be on the second row? I think it should be next to the header

**Review by loujaybee — APPROVED** [review]
Approving from a product perspective, but would prefer an engineer / WebApp approval before merge !

/hold

**Review by gtsiolis — COMMENTED** [review]
> Should the label be on the second row? I think it should be next to the header

+1 — Yes, please!

**Comment by easyCZ** [comment]
Screenshot 2022-12-07 at 13 59 53
Could possibly be sitting a bit higher, to be more aligned with the title. But this works for now.

**Review by easyCZ — APPROVED** [review]

**Comment by Siddhant-K-code** [comment]
> Could possibly be sitting a bit higher, to be more aligned with the title

I had tried that, doesn't seems to get changed as it is coming from the parent class of `PillLabel`. 😞

**Comment by Siddhant-K-code** [comment]
can we `unhold` this one?

**Comment by gtsiolis** [comment]
> I had tried that, doesn't seems to get changed as it is coming from the parent class of PillLabel.

It's ok, @Siddhant-K-code! This happens because of the default (baseline) alignment.

We could override and decrease the padding of label to improve the visual balance with the heading next to it. We've done similar overrides for the label in usage pages, etc, see https://github.com/gitpod-io/gitpod/pull/15017. Didn't come here in time[[1](https://github.com/gitpod-io/gitpod/pull/15201#issuecomment-1341075862)] but opened the following to change this:
- https://github.com/gitpod-io/gitpod/pull/15221

Ideally, we could introduce a new label component variant for smaller labels. Opened the following issue to keep track of these improvements:
- https://github.com/gitpod-io/gitpod/issues/15218

**Comment by Siddhant-K-code** [comment]
Thanks @gtsiolis 🙌🏽

**Pull request merged**
