### PR TITLE
test: fix unmarshal string to int64 failed

### PR DESCRIPTION
**Pull request by jenting**
## Description

Partially revert the change of PR #14786.

Fix an error when running the integration test against the self-hosted environment.
`json: cannot unmarshal string into Go struct field .cpuLimit.limit of type int64`.

According to the [values](https://github.com/gitpod-io/ops/blob/2e6d65c4269da96c5eda85da5363586e3f41839f/deploy/workspace/installer-values.yaml#L49-L50), it's string based. So, quote the values in the preview environment.

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/pull/14786/files#r1029984960

## How to test

Run the integration test on the self-hosted environment.

## Release Notes

```release-note
None
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [x] /werft with-large-vm
- [x] /werft with-integration-tests=workspace
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by aledbf** [comment]
/hold 

This change breaks the compilation

**Review by Furisto — APPROVED** [review]

**Comment by Furisto** [comment]
/werft run with-clean-slate-deployment with-large-vm with-integration-tests=workspace

**Comment by jenting** [comment]
/unhold

We update the values in preview env as string.

**Pull request merged**
