### PR TITLE
[server] remove port 3000 from default config

### PR DESCRIPTION
**Pull request by mustard-mh**
## Related Issue(s)

Fixes #
Fixes [internal chat](https://gitpod.slack.com/archives/C01KGM9BH54/p1666285436242979)

## How to test

- Open https://github.com/gitpod-io/empty workspace in preview env
- Check if port 3000 list in `gp ports list` or PortsView

## Release Notes

```release-note
Fixes port 3000 becomes the default config of ports if there is no `.gitpod.yml` file
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@mustard-mh: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by easyCZ** [comment]
Looks like it's been there for 2 years - since https://github.com/gitpod-io/gitpod/commit/b71f68fc1aaefbe12b62a4c6ab5137e9a3df29a7#diff-d26a92840b8fdcdeb54cc05627962891fbc4bbbe1f6872661f1e8a956f1d5600R161

**Review by Siddhant-K-code — APPROVED** [review]
Working Perfectly 💯 🚀 

| Old | New |
| --- | --- |
| image | image | 


:shipit:

**Review by easyCZ — APPROVED** [review]

**Pull request merged**
