### PR TITLE
Set KOTS/Replicated dependencies to latest

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Description

These have become very outdated. As a way of avoiding this in future, these are set to the latest. 

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Review by jenting — APPROVED** [review]

**Review by adrienthebo — APPROVED** [review]
Verification:

```
 kubectl-kots version
Replicated KOTS 1.78.0
```

Merge conflicts nonwithstanding, LGTM!

**Review by mads-hartmann — APPROVED** [review]
I'd personally prefer not to use latest and instead just bump the version to whatever is latest right now. I understand that we'll then slowly fall behind again but I'd prefer that over accidentally updating Replicated/KOTS the next time someone makes an unrelated change to the Dockerfile - but as this is self-hosted tooling that's your decision to make ☺️

Due to job protection, in order to test your new image in Werft you'll have to trigger a job manually (see related issue https://github.com/gitpod-io/ops/issues/3723)

**Review by andreafalzetti — APPROVED** [review]

**Comment by MrSimonEmms** [comment]
@mads-hartmann yeah, normally I'd be a little reticent about using `latest` on things, but it's proving more painful having it on a (very old) version. This is primarily an experiment to see if using `latest` is better and we can always revert if not. The intention is indeed to let the image get rebuilt regularly so it keeps our tooling mostly up to date (we always recommend using the latest in the docs anyway)

I'll do the job trigger now 👍🏻

**Pull request merged**
