### PR TITLE
[public-api] Bind OIDC HTTP service to Public API

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

Attaches the HTTP OIDC endpoints to Public API. This is part of merging the `iam` component with the `public-api-server` component.

Both `iam` and `public-api-server` will be running these endpoints, and traffic from the proxy remains configured to go to `iam`. But this allows us to test the endpoint works by port-forwarding to it, before make the full switch in subsequent PR.

## Related Issue(s)

* Part of https://github.com/gitpod-io/gitpod/issues/15860

## How to test

1. Preview k8s context
2. `kubectl port-forward deployment/public-api-server 9002:9002`
3. 
	```
	curl localhost:9002/oidc/start
	config not found
	```
4. Config not found is expected, it means we can reach the endpoint and it's handled by `public-api-server`. We will use this endpoint in https://github.com/gitpod-io/gitpod/pull/15940

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all-ci
- [ ] /werft no-test
      Run Leeway with `--dont-test`
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by geropl — APPROVED** [review]
Code LGTM, did the test and worked.

/hold not sure about when to merge, because there have been quite some installer-changes today.

**Comment by easyCZ** [comment]
I can try a rebase, but given this doesn't actually get used in production yet, the worst that could happen is a failing build on main.

**Pull request merged**
