### PR TITLE
werft: Close slice spans

### LINKED ISSUE #639: Docker images based on microsoft/dotnet (like lambci/lambda) don't work in Gitpod
**Describe the bug**
using lambci/lambda dockerfile not working
https://hub.docker.com/r/lambci/lambda/dockerfile

### PR DESCRIPTION
**Pull request by ArthurSens**
## Description

We've always had trace spans for the VM phase, but we don't close them correctly. This PRs just closes all spans at the right time.

You can see the difference in:
* [A trace without closing spans](https://ui.honeycomb.io/gitpod/datasets/werft/result/g3fbJ1RnsjR/trace/GpfcXDkBkKB?span=f5afbf02369a0235)
* [A trace from this PR, which closes spans](https://ui.honeycomb.io/gitpod/datasets/werft/result/txg3SBVddiZ/trace/hCYE53gx18q?span=58297105af92dc9c)

Please pay attention in the `VM` phase

## Related Issue(s)

Fixes https://github.com/gitpod-io/ops/issues/639

## How to test

Start a job and check the trace in honeycomb

PS: We should add the honeycomb trace URL as one of the Werft results 🤔 

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by mads-hartmann — APPROVED** [review]
Awesome 🕺 If you're up for it, it would be super awesome to add the result to Werft. If you don't wan to do it as part of this PR can you create an issue and put it in the inbox? ☺️

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 68d6d2fce4e5690f1e374539b8ad3f1c28d65420</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7984#pullrequestreview-871483645" title="Approved">mads-hartmann</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **geropl** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @geropl` in a comment when ready.

Associated issue: *#639*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ArthurSens** [comment]
> Awesome 🕺 If you're up for it, it would be super awesome to add the result to Werft. If you don't wan to do it as part of this PR can you create an issue and put it in the inbox? ☺️

Actually I tried for half an hour yesterday without success 😅
Not sure how to extract the span ID from the root span

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7984#pullrequestreview-871483645" title="Approved">mads-hartmann</a>*

Associated issue: *#639*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
