### PR TITLE
Clean up Jetbrains Backend plugin

### LINKED ISSUE #6513: Clean up the heartbeat Jetbrains's plugin
It should use the supervisor info endpoint instead of env vars to get information about workspace.

### PR DESCRIPTION
**Pull request by atduarte**
## Description

* Replace usage of environment variables, by using the Supervisor's endpoint `Info`.
* Change `ControllerStatusService` to fail explicitly
* Better error handling

## Related Issue(s)

Fixes #6513

## How to test

Validate heartbeats are still functioning.

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **filiptronicek** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @filiptronicek` in a comment when ready.

Associated issue: *#6513*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **loujaybee** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @loujaybee` in a comment when ready.

Associated issue: *#6513*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by atduarte** [comment]
Before the IDE project starts, an error is logged:
```
2021-11-23 15:25:56,303 [   7812]  ERROR - rvices.ControllerStatusService - Failed to retrieve controller status. 
	...
Caused by: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class io.gitpod.ide.jetbrains.backend.services.ControllerStatusService$Response] value failed for JSON property projects due to missing (therefore NULL) value for creator parameter projects which is a non-nullable type
 at [Source: (String)"{
  "appPid": 997,
  "appVersion": "IU-213.5744.18",
  "runtimeVersion": "11_0_13b1751.19",
  "unattendedMode": true,
  "idePath": "/ide-desktop/backend"
}"; 
	...
```

@corneliusludmann do you think this is an issue? Do you have any suggestion?

**Comment by corneliusludmann** [comment]
> Before the IDE project starts, an error is logged:

> do you think this is an issue? Do you have any suggestion?

When the project is not fully loaded the `projects` property is `null`. I think, we should gracefully handle this case and don't throw an error. Something like this:

```diff
diff --git a/components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/ide/jetbrains/backend/services/ControllerStatusService.kt b/components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/ide/jetbrains/backend/services/ControllerStatusService.kt
index ae99d3c43..5ecfaa12b 100644
--- a/components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/ide/jetbrains/backend/services/ControllerStatusService.kt
+++ b/components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/ide/jetbrains/backend/services/ControllerStatusService.kt
@@ -47,8 +47,8 @@ object ControllerStatusService {
                 throw IOException("Failed to retrieve controller status.", e)
             }
 
-            if (response.projects.isEmpty()) {
-                throw IOException("Failed to fetch controller status as project list is empty.")
+            if (response.projects.isNullOrEmpty()) {
+                return@retry ControllerStatus(false, 0);
             }
 
             ControllerStatus(
@@ -60,7 +60,7 @@ object ControllerStatusService {
     @JsonIgnoreProperties(ignoreUnknown = true)
     private data class Response(
         val appPid: Int,
-        val projects: List<Project>
+        val projects: List<Project>?
     ) {
         @JsonIgnoreProperties(ignoreUnknown = true)
         data class Project(
```

_(the empty return `ControllerStatus(false, 0)` needs to be something sensible, though)_

What do you think?

**Comment by atduarte** [comment]
@corneliusludmann I think that's also reasonable. As we also have errors in the supervisor (?) while checking whether IDEA is up, I didn't consider it to much of an issue but in this case the returned value is actually "true".

**Comment by corneliusludmann** [comment]
Looks great and works as expected. (Took the liberty to rebase the branch. :pray:)

/lgtm
/approve

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: b18dd01ad024dadd3045ab3c547ba2cd2f36f0dd</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6603#issuecomment-981508197" title="Approved">corneliusludmann</a>*

Associated issue: *#6513*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [corneliusludmann]
- ~~[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)~~ [corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
