### PR TITLE
Bug Fix on `/new` & Improve user flow on dashboard

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description
This PR proposes 2 Changes:

- Bug Fix on `/new` - ignore empty spaces while searching repos. on `/new`:

|Before|After|
|:---:|:---:|
|image|image|

- Open Related Docs & Help Support Pages on new Tab. Currently It breaks the user-flow by opening all in a same tab.

## How to test

- Open Preview

### for 1st change:

- Go to `/new` & type some spaces & see search would still work 😉 

### for 2nd change:

- Click on your avatar, Click on `Docs`, `Help`. Similarly, for other related & needed (not all) pages of `Learn More` URLs

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by easyCZ** [comment]
/werft run

Preview is dead

**Comment by Siddhant-K-code** [comment]
I think, i have to rebase my branch. 🏃🏽

**Comment by Siddhant-K-code** [comment]
> Preview is dead

@easyCZ Preview is happy now 😄

**Review by easyCZ — APPROVED** [review]

**Pull request merged**
