### PR TITLE
Move installer to /install

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Description

Move the installer to `/install`. This directory will be used for installation resources (including the KOTS specification)

## How to test

```shell
cd install/installer
go run .
```

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
@MrSimonEmms: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by MrSimonEmms** [comment]
> why moving back joy

Because we're adding in more resources into the `/install` directory. This is the first piece and the next one will be the [KOTS](https://github.com/gitpod-io/replicated/) work

**Comment by MrSimonEmms** [comment]
Thanks @iQQBot

**Comment by corneliusludmann** [comment]
> why moving back 

Sorry for the noise. We do not move it back in the strict sense (was originally `/installer` and is now `/install/installer` :innocent:), we had only let ourselves be diverted temporarily from the[ originally better plan](https://github.com/gitpod-io/gitpod/pull/8149#issuecomment-1035998870) of an `/install` folder.

**Comment by mustard-mh** [comment]
search `components/installer` globally, CODEOWNERS need to update

**Comment by corneliusludmann** [comment]
@MrSimonEmms Could you compare the changed files with the changes from this PR? https://github.com/gitpod-io/gitpod/pull/8149/files

**Comment by MrSimonEmms** [comment]
Have made the `.github/CODEOWNERS` change. It's now the same as the other move now

**Review by corneliusludmann — DISMISSED** [review]

**Review by mustard-mh — DISMISSED** [review]

**Review by JanKoehnlein — DISMISSED** [review]
LGTM

**Review by princerachit — DISMISSED** [review]
please resolve conflict

**Comment by MrSimonEmms** [comment]
Conflicts resolved.

**Review by princerachit — APPROVED** [review]

**Review by corneliusludmann — APPROVED** [review]

**Review by JanKoehnlein — APPROVED** [review]

**Review by mustard-mh — APPROVED** [review]

**Pull request merged**
