### PR TITLE
ws-sync + ws-manager-node = ws-daemon

### PR DESCRIPTION
**Pull request by csweichel**
This PR combines two services running as daemonsets (`ws-sync` and `ws-manager-node`) into one new service named **`ws-daemon`**.
We do that because that split made less and less sense, and combining the two services lets us reduce configuration complexity and easier share code/responsibilities.

I have first renamed `ws-sync` to `ws-daemon`, because ws-sync is the more complex component. After making sure that worked, I then integrated `ws-manager-node` into `ws-daemon`, thereby refactoring the new component's configuration surface.

I've also done some minor renaming of packages, e.g. `resourcegov -> resources`, `hostgov -> hosts`. All in all the packages in ws-daemon are much more sensibly named than they were in ws-sync or ws-manager-node. Other than some naming, I've resisted the urge to "just quickly refactor X", just to keep this reviewable.

Other than renaming `components.wsSync` to `components.wsDaemon` there have been no changes in the `values.yaml` that impact self-hosted or production.

## How to test
- start a workspace without `full_workspace_backup`
- start a workspace with `full_workspace_backup`
- run [cpuburn](https://github.com/patrickmn/cpuburn) and observe `/sys/fs/cgroup/cpu/cpu.cfs_quota_us` to ensure the resource controller (formerly resource governor) is still working
image

### CODE REVIEW

**Comment by svenefftinge** [comment]
There are still references to `ws-manager-node` and `ws-sync`. I guess keeping them in `build.js` for an iteration, but in other places references should be update?

**Comment by svenefftinge** [comment]
With `full_workspace_backup` enabled I see:

Screenshot 2020-10-16 at 08 23 14

**Comment by svenefftinge** [comment]
I could now start a full-workspace-backup WS but restarting it resulted in:

Screenshot 2020-10-16 at 15 50 12

**Comment by csweichel** [comment]
At this point it's pretty much a MinIO issue. Turns out we've never really teste FWB with MinIO, and we're not using minio's metadata capabilities correctly.

**Review by svenefftinge — APPROVED** [review]
Apart from https://github.com/gitpod-io/gitpod/issues/2011 LGTM

**Pull request merged**
