### PR TITLE
[werft] kubectl apply intermittently fails in core-dev

### PR DESCRIPTION
**Pull request by kylos101**
## Description

Assume the `kubectl apply` was successful, rely on the `kubectl rollout status` to marshall whether the deploy was successful.

## Related Issue(s)

N/A

## How to test

1. Build this in werft in an existing preview environment
2. Build this in a clean slate deployment
Both should work without issue.

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **gtsiolis** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @gtsiolis` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by kylos101** [comment]
Hey @wulfthimm let me know what you think? 

This will give the build and deploy job the best possible chance of being successful, even if the `kubectl apply` exits with an error code but actually installed Gitpod.

However, if the `kubectl rollout status` fails with server, it should still fail the job.

**Comment by kylos101** [comment]
There were other issues we had to resolve:
https://github.com/gitpod-io/gitpod/pull/7669
https://github.com/gitpod-io/gitpod/pull/7670

**Pull request closed without merging**
