### PR TITLE
[db] fix creationTime in baseline migration

### PR DESCRIPTION
**Pull request by AlexTugarev**
Fixes https://github.com/gitpod-io/gitpod/issues/5252

As suggested by @geropl, I've changed to fix it by adding an extra db migration.

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **alextugarev** after the PR has been reviewed.

Associated issue: *#5252*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by gtsiolis** [comment]
This will most probably also fix https://github.com/gitpod-io/gitpod/issues/5268. Thanks @AlexTugarev! 🔝

**Comment by jankeromnes** [comment]
Taking a look! 👀

/werft run

**Review by jankeromnes — APPROVED** [review]
Makes total sense to me! 💯 Many thanks @AlexTugarev and @charleswhchan! 🙏 

New migration looks good, and does the job:

**Before**:

```
mysql> describe d_b_snapshot;
+---------------------+--------------+------+-----+----------------------+--------------------------------+
| Field               | Type         | Null | Key | Default              | Extra                          |
+---------------------+--------------+------+-----+----------------------+--------------------------------+
| id                  | char(36)     | NO   | PRI | NULL                 |                                |
| creationTime        | timestamp(6) | NO   | MUL | CURRENT_TIMESTAMP(6) | on update CURRENT_TIMESTAMP(6) |
| originalWorkspaceId | char(36)     | NO   | MUL | NULL                 |                                |
| bucketId            | varchar(255) | NO   |     | NULL                 |                                |
| layoutData          | mediumtext   | YES  |     | NULL                 |                                |
+---------------------+--------------+------+-----+----------------------+--------------------------------+
```

**After**:

```
mysql> describe d_b_snapshot;
+---------------------+--------------+------+-----+----------------------+-------+
| Field               | Type         | Null | Key | Default              | Extra |
+---------------------+--------------+------+-----+----------------------+-------+
| id                  | char(36)     | NO   | PRI | NULL                 |       |
| creationTime        | timestamp(6) | NO   | MUL | CURRENT_TIMESTAMP(6) |       |
| originalWorkspaceId | char(36)     | NO   | MUL | NULL                 |       |
| bucketId            | varchar(255) | NO   |     | NULL                 |       |
| layoutData          | mediumtext   | YES  |     | NULL                 |       |
+---------------------+--------------+------+-----+----------------------+-------+
```

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: c5fea43313052b1ad5e17456237f6cc01716e5c5</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5266#pullrequestreview-738059358" title="Approved">jankeromnes</a>*

Associated issue: *#5252*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)~~ [jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
