### PR TITLE
Draft to detect system theme in port not found page

### LINKED ISSUE #7274: Make port not found page dark theme aware
### Problem to solve

The product already adapts to dark or system theme for the dashboard (see https://github.com/gitpod-io/gitpod/pull/6747) and the editor (see https://github.com/gitpod-io/gitpod/issues/6403). 

However, the `Port XYZ Not Found` page is still using light only theme.

| Port XYZ Not Found |
|-|
| Screenshot 2021-12-17 at 12 17 12 AM (2) |

### Proposal

Let's make `Port XYZ Not Found` page adapt to system or dark theme aware. 🌔

### PR DESCRIPTION
**Pull request by championshuttler**
Fix #7274

### CODE REVIEW

**Comment by roboquat** [comment]
@championshuttler: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **aledbf** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @aledbf` in a comment when ready.

Associated issue: *#7274*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-proxy/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by championshuttler** [comment]
idk how to test this code or if this is right, any help would be appreciated thanks

**Comment by championshuttler** [comment]
> idk

Can you suggest me what can i do now thanks

**Pull request closed without merging**
