### PR TITLE
feature(supervisor): installation of dotfiles via Makefile

### PR DESCRIPTION
**Pull request by ghuntley**
## Description

I and many folks use a `Makefile` as a standard interface to dotfiles. This pull-request adds support for `Makefile`s

## How to test

* Change was directly applied using GitHub editor and is pending test
* Start instance, configure dotfiles repo with `Makefile` - does it work?

## Release Notes

```release-note
feature: installation of dotfiles via Makefile
```

## Documentation

Will require https://www.gitpod.io/docs/config-dotfiles to be updated once this ships.

### CODE REVIEW

**Comment by akosyakov** [comment]
@csweichel @iQQBot does it make sense? Could you review please?

**Comment by andreafalzetti** [comment]
@ghuntley did you run some tests on this?

I think what @iQQBot is saying makes sense, you would not run `Makefile`instead you run the `make` cmd. 

Is that what you do for your dotfiles?

**Pull request closed without merging**
