### PR TITLE
Add code nightly option in dashboard

### PR DESCRIPTION
**Pull request by jeanp413**
## Related Issue(s)

Related #3065

## How to test

1. Go to https://cw-nightly.staging.gitpod-dev.com/workspaces/
2. Go to preferences and select code nightly
3. Open a workspace, check that code commit is the same as the latest commit in https://github.com/gitpod-io/openvscode-server/tree/gp-code/main

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jeanp413** and additionally assign **geropl**, **rl-gitpod** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @geropl @rl-gitpod` in a comment when ready.

Associated issue: *#3065*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/blobserve/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/blobserve/OWNERS)**
- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**
- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jeanp413** [comment]
@akosyakov @csweichel @geropl  it's working now :smile: please take a look at the changes in blobserve

**Comment by akosyakov** [comment]
> Suppose that upon server startup the nightly build cannot be resolved (e.g. network issue), what would happen when users who have "NIGHTLY" selected try to start a workspace?

I think it should fail explicitly.

**Comment by akosyakov** [comment]
@jeanp413 Don't forget to clean up history and rebase, that I can review and merge it tomorrow, thanks!

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: c9a565dddf50f72f5f0ba02132f8fae1b6c10164</details>

**Pull request merged**
