### PR TITLE
Update kumquat colors

### PR DESCRIPTION
**Pull request by gtsiolis**
## Description

Following up from https://github.com/gitpod-io/gitpod/pull/18319, to replace the kumquat color variables used.

Thanks @jeanp413 for noticing! ⚾ 

See [relevant discussion](https://gitpod.slack.com/archives/C05H5UQBW6Q/p1693324295436819) (internal).

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖 Generated by Copilot at 2a0e1f6</samp>

This pull request updates various UI components in the dashboard to use a new color variable `kumquat` instead of the old one `gitpod-kumquat`. This improves the consistency and accessibility of the color scheme. The affected components include blocked email domains, blocked repositories, projects search, teams search, user search, workspaces search, items list, new project repo list, projects, start workspace, OIDC client list item, environment variables, token entry, rename workspace modal, and workspace status indicator.

</details>

## How to test

Start a workspace and seethe pulsating kumuqat dot on the workspaces list. 🍊 

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - gt-update-d7257b6fd7</li>
	<li><b>🔗 URL</b> - <a href="https://gt-update-d7257b6fd7.preview.gitpod-dev.com/workspaces" target="_blank">gt-update-d7257b6fd7.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - gt-update-kumquat-colors-gha.16125</li>
	<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-gt-update-d7257b6fd7%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws-manager-mk2%22%0A;duration=P1D?project=gitpod-core-dev" target="_blank">GCP Logs Explorer</a></li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [X] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by gtsiolis** [comment]
Removing hold, as this is a trivial change—it should work fine. _~famous last words..._ 😅 

/unhold

**Comment by jeanp413** [comment]
Works 🎉

**Review by jeanp413 — APPROVED** [review]

**Comment by gtsiolis** [comment]
Thanks for taking a look, @jeanp413. 🌮

**Comment by mustard-mh** [comment]
> Removing hold, as this is a trivial change—it should work fine. _~famous last words..._ 😅
> 
> /unhold

image

**Pull request merged**
