### PR TITLE
Bump leeway to v0.3.1

### PR DESCRIPTION
**Pull request by csweichel**
## Description
This PR bumps leeway to the latest release to prepare for Go workspaces.

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by adrienthebo — APPROVED** [review]

**Comment by aledbf** [comment]
Can we merge this one first? https://github.com/gitpod-io/gitpod/pull/13275

**Comment by csweichel** [comment]
> Can we merge this one first? #13275

Yep.

/hold

**Review by mads-hartmann — APPROVED** [review]
Awesome. This should also fix https://github.com/gitpod-io/ops/issues/5384 as I just needed to bump the version to 0.3.0 🎉

**Review by felladrin — APPROVED** [review]

**Review by jenting — APPROVED** [review]

**Pull request merged**
