### PR TITLE
Add `maximumBackupCount` and `blobQuota` configuration surface to the installer

### PR DESCRIPTION
**Pull request by andrew-farries**
## Description

One of the Webapp team's [epics for Q2](https://github.com/gitpod-io/gitpod/issues/9097) is to use the Gitpod installer to deploy to Gitpod SaaS. In order to do that we may need to add additional configuration to the installer to make the output suitable for a SaaS deployment as opposed to a self-hosted deployment.

This PR adds configuration for two such values, `maximumBackupCount` and `blobQuota`, which are currently hard-coded in the installer but need to be configurable for SaaS.

## Related Issue(s)

Part of https://github.com/gitpod-io/gitpod/issues/9097.

## How to test

Build the installer and run it with

```
render --config /path/to/config
```

Where the config file contains a `objectStorage` configuration section including the new values, like:

```yaml
objectStorage:
  inCluster: false
  maximumBackupCount: 10
  blobQuota: 2
  cloudStorage:
    project: gitpod-staging
    serviceAccount:
      kind: secret
      name: ws-sync-gcloud
```

The rendered output for the `content-service` configMap should then contain the new values under the `config.json` key:

```yaml
- apiVersion: v1
  data:
    config.json: |-
      {
       "pprof": {
        "address": ":6060"
       },
       "prometheus": {
        "address": ":9500"
       },
       "service": {
        "address": ":8080",
        "tls": {
         "ca": "",
         "crt": "",
         "key": ""
        }
       },
       "storage": {
        "backupTrail": {
         "enabled": true,
         "maxLength": 3
        },
        "blobQuota": 2,
        "gcloud": {
         "credentialsFile": "/mnt/secrets/storage/service-account.json",
         "maximumBackupCount": 10,
         "parallelUpload": 6,
         "projectId": "gitpod-staging",
         "region": "europe-west1"
        },
        "kind": "gcloud",
        "minio": {
         "accessKey": "",
         "accessKeyFile": "",
         "endpoint": "",
         "region": "",
         "secretKey": "",
         "secretKeyFile": ""
        },
        "stage": ""
       }
      }
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    labels:
      app: gitpod
      component: content-service
    name: content-service
```

## Release Notes

```release-note
Make `maximumBackupCount` and `blobQuota` configurable via the installer config file.
```

## Documentation

No changes required as these values should be left at the pre-existing defaults to self-hosted installations.

### CODE REVIEW

**Review by sagor999 — APPROVED** [review]

**Review by jenting — APPROVED** [review]

**Comment by geropl** [comment]
@MrSimonEmms Would you have time to review this? :pray:

**Comment by MrSimonEmms** [comment]
> @MrSimonEmms Would you have time to review this? pray

@geropl anything for my friends in WebApp 🎉

**Review by MrSimonEmms — APPROVED** [review]
Good work.

Is this a value we expect that a self-hosted user would be wanting to change - maybe not a small deployment, but a big bank/govt agency? If so, @gitpod-io/engineering-self-hosted may need to think about how we put this in KOTS (the "advanced" section may be enough)

**Comment by geropl** [comment]
> Is this a value we expect that a self-hosted user would be wanting to change - maybe not a small deployment, but a big bank/govt agency?

@MrSimonEmms Exactly where I'd put it: not interesting for Gitpod 101 Self-Hosted installation, but interesting for installs that are a bit more regulated.

**Comment by MrSimonEmms** [comment]
Great - advanced section it is. That suits me as a) we don't need to do anything and b) it doesn't clutter up the config page with extra things that someone could break

**Pull request merged**
