### PR TITLE
Update Caddy to v2.6.2

### PR DESCRIPTION
**Pull request by aledbf**
## Description

Update Caddy to the latest stable version [v.2.6.2](https://github.com/caddyserver/caddy/releases/tag/v2.6.0)

## How to test
- The dashboard should open
- Workspaces should open without issues

## Release Notes
```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]

**Review by mustard-mh — CHANGES_REQUESTED** [review]
Broken in preview env

image

**Comment by aledbf** [comment]
> Broken in preview env

@mustard-mh fixed.

**Review by jenting — APPROVED** [review]

**Review by mustard-mh — APPROVED** [review]
Tested in VSCode Browser and Desktop (ssh), both worked 🎉

**Pull request merged**
