### PR TITLE
[dashboard, server] App-level notifications to switch to Pay-as-you-go

### PR DESCRIPTION
**Pull request by geropl**
## Description

This PR introduces new app-level notifications by re-using and slightly extending the existing `getNotifications` mechanism.
Those are nudges to switch from old Chargebee:
 - Personal Subscriptions
 - owned Team Subscriptions
 - (co-) owned Team Subscriptions 2
image

This is feature flagged mostly for piece of mind. :lotus_position: 

## Related Issue(s)

Fixes #

## How to test

 - Start [a workspace on this branch](https://gitpod.io/#https://github.com/gitpod-io/gitpod/pull/16490)
 - get your user ID (from websocket responses, for instance)
 - `cd components/server && USER_ID="" ./reset-chargebee-test-subs.sh`
 - Notice the sticky notification following you on each page :heavy_check_mark: 

## Release Notes

```release-note
add app-level notifications for switching to Pay-as-you-go
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-slow-database
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by AlexTugarev — APPROVED** [review]
Code changes look good!
Let's test and proceed.

**Comment by geropl** [comment]
@AlexTugarev Preview env is finally there. Do you want to have another look?

**Comment by geropl** [comment]
No hold... :see_no_evil: Oh well.

**Pull request merged**
