### PR TITLE
[gitpod-protocol] Refactor generation of gitpod-schema.json

### PR DESCRIPTION
**Pull request by aledbf**

### CODE REVIEW

**Comment by aledbf** [comment]
there is something missing? @csweichel @akosyakov 

```console
root /workspace/gitpod/components/gitpod-protocol/hack # ./generate.sh 
+ go get -u github.com/a-h/generate/...
+ node -e 'new (require("typescript-parser").TypescriptParser)().parseFiles(["../src/gitpod-service.ts", "../src/protocol.ts", "../src/workspace-instance.ts"], "../..").then(a => console.log(JSON.stringify(a)))'
+ jq '[.[0] | .declarations[2].methods | .[] | {name: .name, params: .parameters, result: .type}]'
+ go run generate.go
tmp file: /tmp/158859407
generating PlanCoupon
src/gitpod-service.ts (213,9): Type '(target: S, property: keyof S) => S[keyof S]' is not assignable to type '(target: JsonRpcProxy<S>, p: string | symbol, receiver: any) => any'.
  Types of parameters 'property' and 'p' are incompatible.
    Type 'string | symbol' is not assignable to type 'keyof S'.
      Type 'string' is not assignable to type 'keyof S'.
        Type 'string' is not assignable to type 'keyof GitpodServer'.
src/util/skip-if.ts (11,42): Namespace 'Mocha' has no exported member 'ISuiteCallbackContext'.
src/util/skip-if.ts (13,35): Namespace 'Mocha' has no exported member 'IHookCallbackContext'.
src/util/skip-if.ts (21,68): Namespace 'Mocha' has no exported member 'ISuiteCallbackContext'.
src/util/skip-if.ts (21,102): Namespace 'Mocha' has no exported member 'ISuiteCallbackContext'.
src/util/skip-if.ts (24,47): Namespace 'Mocha' has no exported member 'IHookCallbackContext'.
(node:84835) UnhandledPromiseRejectionWarning: Error: No output definition. Probably caused by errors prior to this?
    at Object.<anonymous> (/workspace/gitpod/node_modules/typescript-json-schema/dist/typescript-json-schema.js:1290:23)
    at step (/workspace/gitpod/node_modules/typescript-json-schema/dist/typescript-json-schema.js:44:23)
    at Object.next (/workspace/gitpod/node_modules/typescript-json-schema/dist/typescript-json-schema.js:25:53)
    at /workspace/gitpod/node_modules/typescript-json-schema/dist/typescript-json-schema.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/gitpod/node_modules/typescript-json-schema/dist/typescript-json-schema.js:15:12)
    at Object.exec (/workspace/gitpod/node_modules/typescript-json-schema/dist/typescript-json-schema.js:1269:12)
    at Object.run (/workspace/gitpod/node_modules/typescript-json-schema/dist/typescript-json-schema-cli.js:53:30)
    at Object.<anonymous> (/workspace/gitpod/node_modules/typescript-json-schema/bin/typescript-json-schema:3:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
(node:84835) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:84835) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
cannot parse JSON schema due to a syntax error at /tmp/158859407 line 0, character 0: unexpected end of JSON input
couldn't find the line and character position of the error due to error couldn't find offset 0 in 0 bytes
2021/06/10 22:53:53 exit status 1
exit status 1
```

**Comment by mikenikles** [comment]
As I'm documenting this file in the docs, I notice the following properties are missing in the schema:
* `addCheck`
* `addComment`

**Comment by akosyakov** [comment]
I am not sure that this script is still working. As far as I remember it was one time thing and then we changed gitpod-service.go file manually. cc @csweichel

**Comment by csweichel** [comment]
Indeed. That script is very broken and just helps to start things of. 

We need to rethink the server API implementation so that we don't have to maintain the RPC stack ourselves.

**Comment by aledbf** [comment]
Not sure what I can do here. This PR removes the duplication of the schema and fixes the generation of the mocks.
The script `generate.sh`  is still broken. @csweichel please let me how to proceed.

**Comment by csweichel** [comment]
We should probably remove the `hack/generate.sh` and newly generated artefacts from gitpod-protocol. It falsely suggests that the Go implementation of the Gitpod server API can be auto-generated, when in reality it cannot. Those scripts were useful for the initial generation, but fail afterwards.

**Comment by aledbf** [comment]
> We should probably remove the hack/generate.sh and newly generated artefacts from gitpod-protocol. 

done. I removed the generate.sh script and reverted changes to go code. Only the update of the mocks is present.

**Review by csweichel — APPROVED** [review]
LGTM

**Pull request merged**
