### PR TITLE
Add domain to previewEnvironment config

### PR DESCRIPTION
**Pull request by mads-hartmann**
## Description

This passes the preview domain to the monitoring-satellite configuration so that we can use it to attach it to all spans that go through the OpenTelemetry Collector. See this https://github.com/gitpod-io/observability/pull/47 for the changes to monitoring-satellite.

## Related Issue(s)

Fixes gitpod-io/ops/issues/401

## How to test

From a gitpod-io/gitpod workspace deploy the observability stack using this branch:

```
werft run github -f \
  -a with-observability="" \
  -a with-helm="" \
  -a withObservabilityBranch="mads/add-preview-environment" \
  -a with-clean-slate-deployment=""
```

Here's a [query](https://ui.honeycomb.io/gitpod/datasets/preview-environments/result/8kMJQ8FRaah) showing the preview environment being set (for my preview environment)

Screenshot 2021-12-14 at 15 09 22

## Release Notes

```release-note
NONE
```

## Documentation

N/A

### CODE REVIEW

**Comment by roboquat** [comment]
@mads-hartmann: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mads-hartmann** after the PR has been reviewed.

Associated issue: *#401*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[.werft/observability/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/.werft/observability/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ArthurSens — APPROVED** [review]
Awesome!

image

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7233#pullrequestreview-831573079" title="Approved">ArthurSens</a>*

Associated issue: *#401*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[.werft/observability/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/.werft/observability/OWNERS)~~ [ArthurSens]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
