### PR TITLE
[installer] Remove redundant `len` and `nil` check

### PR DESCRIPTION
**Pull request by Juneezee**
## Description

This pull request is a minor code cleanup.

From the Go specification (https://go.dev/ref/spec#For_range):

> "1. For a nil slice, the number of iterations is 0."
> "3. If the map is nil, the number of iterations is 0."

`len` returns 0 if the slice or map is nil (https://pkg.go.dev/builtin#len). Therefore, checking `len(v) > 0` before a loop is unnecessary.

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖 Generated by Copilot at 6848a1e</samp>

Simplify code in various functions by removing redundant checks for empty slices and maps. This affects the files `mirror_list.go`, `helm.go`, `objects.go`, `deployment.go`, and `validation.go` in the installer package.

</details>

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Review by Juneezee — COMMENTED** [review]
Tip: Hide the whitespace to make the diff easier to read

image

image

**Review by geropl — APPROVED** [review]
Changes LGTM! :heavy_check_mark:

**Comment by geropl** [comment]
Hey @Juneezee ,

thank you for your interest and support for Gitpod! :orange_heart: 

While I personally like your change, we are currently not very well set up for accepting external contributions, and I fear the work required here would be too high for the gain. 
Happy coding!

**Comment by Juneezee** [comment]
@geropl No worries. Thank you for taking the time to review this PR.

**Pull request closed without merging**
