### PR TITLE
[code] upgrade to vscode 1.62.2

### PR DESCRIPTION
**Pull request by jeanp413**
## Description

Upgrade to VS Code 1.62.2 recovery release
Picks up fixes for the following upstream issues
https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22October+2021+Recovery+2%22

## How to test

- Switch to latest VS Code in settings.
- Start a workspace.
- Test following:
  - terminals are preserved and resized properly between window reloads
  - extension host process: check language smartness and debugging
  - extension management (installing/uninstalling)
    - install VIM extension to test web extensions
  - that user data are sync across workspaces as well as on workspace restart, especially for extensions
    - extensions from .gitpod.yml are not installed as sync
    - extensions installed as sync are actually sync in new workspaces
  - settings should not contain any mentions of MS telemetry
  - websockets and workers are properly proxied
    - diff editor should be operatable
    - trigger reconnection with `window.WebSocket.disconnectWorkspace()`, check that old websockets are closed and new opened of the same amount
  - workspace specific commands should work, i.e. F1 → type Gitpod prefix
  - that a PR view is preloaded on the PR url
  - test gp open and preview
  - test open in VS Code Desktop, check gp open and preview in task/user terminals

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jeanp413** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by filiptronicek — APPROVED** [review]
LGTM ✅

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 80150e9b061b479fcc07c7fe7c7dcad5f2b511c0</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6677#pullrequestreview-805111833" title="Approved">filiptronicek</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [filiptronicek]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6677#pullrequestreview-805111833" title="Approved">filiptronicek</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6677#issuecomment-967341385" title="Approved">jeanp413</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/6677#issuecomment-967341385" title="Approved">jeanp413</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [filiptronicek,jeanp413]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
