### PR TITLE
[wip][dashboard] license tab in the admin dashboard

### LINKED ISSUE #8413: [licensing] Add a license page to the admin dashboard
Add a page to the admin dashboard that shows the installed license with properties (number allowed users, actual users, domain restriction etc.).

### PR DESCRIPTION
**Pull request by nandajavarma**
## Description

This PR adds a `License` tab in the admin dashboard listing relevant information about the associated license

## Related Issue(s)

Fixes #8413

## Release Notes

```release-note
```

### CODE REVIEW

**Comment by roboquat** [comment]
@nandajavarma: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jankeromnes** [comment]
Hello @nandajavarma! Many thanks for working on this. 🙏 😊

I notice that this Pull Request has a review request to Team WebApp, but it is also marked as Draft and its title says "[wip]", so our team is currently ignoring the review signal. I'll temporarily remove the review request, but please do feel free to request a review again when the Pull Request is no longer [wip] / a Draft. 🚀

**Comment by nandajavarma** [comment]
Closing this PR to open a clean one!

**Pull request closed without merging**
