### PR TITLE
Change provider dropdown icon size

### PR DESCRIPTION
**Pull request by gtsiolis**
Minor icon size change in the provider dropdown for Teams & Projects, following the initial specs in https://github.com/gitpod-io/gitpod/issues/4352.

| BEFORE | AFTER |
|-|-|
| Screenshot 2021-09-06 at 3 16 26 PM (2) | Screenshot 2021-09-06 at 3 15 23 PM (2) |

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **gtsiolis** after the PR has been reviewed.

Associated issue: *#4352*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by gtsiolis** [comment]
@AlexTugarev could you take a look at this small change since you were involved in https://github.com/gitpod-io/gitpod/pull/4443? 🖖

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 67704712ee2e69b5783dfeaf6752b8668b4e2c11</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5545#issuecomment-913607504" title="LGTM">AlexTugarev</a>*

Associated issue: *#4352*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [AlexTugarev]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by gtsiolis** [comment]
Danke @AlexTugarev! 🏓

**Pull request merged**
