### PR TITLE
Fix incorrect log level setup - IDE-127

### PR DESCRIPTION
**Pull request by mustard-mh**
## Description

In `logrus`, log.Entry 's Logger property is the parent Logger. So we can't use `.Logger.SetLevel` to change log level

https://go.dev/play/p/OtGHXjEm7sL

Change value of `useParentLogger` to see different

## Related Issue(s)

Fixes #

## How to test

You can open PR with Gitpod and use `hot-deploy.sh`

1. Add log.Info("helloooooooooo") to supervisor publicapi.go after configcat Client created `hot-deploy supervisor`
2. Start/Restart workspace in preview env it should log hello
3. Revert fixing changes in common-go and `hot-deploy supervisor`
4. It should log nothing

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - hw-fix-ide-127</li>
	<li><b>🔗 URL</b> - <a href="https://hw-fix-ide-127.preview.gitpod-dev.com/workspaces" target="_blank">hw-fix-ide-127.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [x] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`
</details>
 
/hold

### CODE REVIEW

**Comment by mustard-mh** [comment]
Test result with debug commit https://github.com/gitpod-io/gitpod/pull/17776/commits/51fba827c204a4e36de00e528d9672f1c58f055f
image

**Comment by akosyakov** [comment]
Output is different in production for `gp validate --log debug` compare to this PR.

**Comment by mustard-mh** [comment]
> Output is different in production for gp validate --log debug compare to this PR.

That's because old code will change all log level to Trace @akosyakov 

We can revert `gp validate` changes if you want

**Comment by mustard-mh** [comment]
> What is the good way to test another file?

@akosyakov  See https://github.com/gitpod-io/gitpod/pull/17776#issuecomment-1568043688

You can open PR with Gitpod and use `hot-deploy.sh`

1. Add log.Info("helloooooooooo") to supervisor publicapi.go after configcat Client created
2. It should log hello
3. Revert fixing changes in common-go and `deploy supervisor`
4. It should log nothing

**Review by akosyakov — APPROVED** [review]

**Pull request merged**
