### PR TITLE
[obs] Refactor alerts for image builds

### PR DESCRIPTION
**Pull request by kylos101**
## Description

For the last 30 days:

This new **GitpodImagebuildDoneSuccess** would have triggered once, on January 26 if set to 2h, instead of 4h.  A customer was potentially struggling with the outer loop. [We hit a 60% error rate in Pyrra briefly for image builds done](https://pyrra.gitpod.io/objectives?expr={__name__=%22workspace-imagebuild-buildsdone-success-ratio%22,%20namespace=%22monitoring-central%22,%20team=%22workspace%22}&grouping={}&from=1673297716785&to=1675716916785).

This new **GitpodImagebuildStartSuccess** would have fired once, on Jan 8, [when GCP was having scaling issues](https://gitpod.slack.com/archives/C01TNS8EVQT/p1673173223060219), and would have been correct to do so.

Also, removed the warnings, as Pyrra sends them now for SLOs to #team-workspace-alerts when error budgets burn.

The related runbook are here: https://github.com/gitpod-io/runbooks/pull/410

## Related Issue(s)

Fixes # n/a

Related internal thread: https://gitpod.slack.com/archives/C02EN94AEPL/p1675723039909239?thread_ts=1675503506.839219&cid=C02EN94AEPL

## How to test

n/a

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`
- [ ] /werft publish-to-npm

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by roboquat** [comment]
@kylos101: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by kylos101** [comment]
/hold

Till https://github.com/gitpod-io/runbooks/pull/410 is merged

**Review by aledbf — APPROVED** [review]

**Comment by kylos101** [comment]
/unhold

Runbook is merged

**Comment by kylos101** [comment]
Confirmed alerts were pushed to monitoring central :sweat_smile: , I see [this one](https://github.com/gitpod-io/gitpod/pull/16251/files#diff-daf02e2313174d18ee4e5c91b4a068294d9ac955a92022907ecd5997740f2ea8R104), for example. Argo still works!

**Pull request merged**
