### PR TITLE
Revert "[dashboard] Start at most one workspace after prebuild finished"

### PR DESCRIPTION
**Pull request by jankeromnes**
"Shot in the dark" attempt to fix https://github.com/gitpod-io/gitpod/issues/4908

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4909#" title="Author self-approved">jankeromnes</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by AlexTugarev** [comment]
@jankeromnes, I think it's best to sync with @geropl on this.

As far as I understood this was independent of https://github.com/gitpod-io/gitpod/pull/4875.

**Comment by jankeromnes** [comment]
Might not be the correct fix: https://github.com/gitpod-io/gitpod/issues/4908#issuecomment-884806170

**Comment by ghuntley** [comment]
See https://github.com/gitpod-io/gitpod/issues/4856#issuecomment-882209321

**Comment by jankeromnes** [comment]
Closing for now, as the issue stopped reproducing, and we don't know whether this revert actually achieves anything.

**Pull request closed without merging**
