### PR TITLE
[mini browser] serve local files from own origin

### PR DESCRIPTION
**Pull request by akosyakov**
- [x] /werft https

#### What it does

Serves local files from own origin to isolate them from the workspace origin.

##### Isolation
- Start a workspace. 
- Preview local html file.
  - Don't forget to check that changing local file updates the preview.
- Check in devtools console that there is a new origin (in drop-down box above console)
- Switch to this origin, try to run commands in console like `window.top.document.cookies` or `window.top.localStorage.getItem`, check that `window.document.cookies` does not contain anything from workspace origin

##### URLs preview

- Start a workspace with the dev server, check that preview is still working for it.

##### Webviews

- Install GitLens extension and check that the welcome page was shown.

### CODE REVIEW

**Comment by akosyakov** [comment]
Please wait with the review yet, something wrong with proxying requests to `browser-*`.

**Comment by geropl** [comment]
Tested
 - [x] preview and refresh-on-edit worked using the `browser-` prefix
 - [x] URLs preview
 - [x] webviews (GitLens)
 - [?] `Switch to this origin, try to run commands in console like window.top.document.cookies or window.top.localStorage.getItem, check that window.document.cookies does not contain anything from workspace origin` I tried to do this and it always shows `undefined`, even for the `top` origin, so I'm not sure this is right?

**Comment by akosyakov** [comment]
> Switch to this origin, try to run commands in console like window.top.document.cookies or window.top.localStorage.getItem, check that window.document.cookies does not contain anything from workspace origin I tried to do this and it always shows undefined, even for the top origin, so I'm not sure this is right?

if `preview and refresh-on-edit worked using the browser- prefix` is fine then it should be alright, i.e. it is already another origin. But we can try together if you want to confirm for sure.

**Review by geropl — APPROVED** [review]
Ok, thx. Works as advertised, code looks good!

**Pull request merged**
