### PR TITLE
[installer]: add image pull secrets and custom image registry

### LINKED ISSUE #6979: Wire up the `ImagePullSecrets` for Gitpod components
The Installer `config.yaml` contains a `imagePullSecrets` key which is an array of pull secrets to be used when pulling images by deployments etc. Ensure that this property is wired up in all Gitpod components (ie, not external dependencies from Helm)

### LINKED ISSUE #6989: Wire up the `ImagePullSecrets` for Helm components

### LINKED ISSUE #6990: Configure Helm dependencies to allow them to be pulled from a custom container registry

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Description

Add image pull secrets to Gitpod components

### Limitations

1. This explicitly does not include pulling Gitpod workspace images from a private registry - just images declared by Kubernetes
2. An in-cluster container registry is not supported. You must also pull your images from the same container registry as you push workspace-images to

The limitations are related to the registry-facade only having a single `.dockerconfigjson` set to `/mnt/pull-secret.json` as the configmap only allows a single `AuthCfg`. This means that images such as `docker-up` and `supervisor` won't be downloaded if using a different repository. If we decide to support the above two limitations, the `AuthCfg` will need to accept an array of pull secrets.

### Mirroring

For external image names, the convention of `path/name` is followed which will make it easier to mirror. This means that anything in docker.io is written out in full - eg, `alpine` becomes `library/alpine`. Any Gitpod images just have the given container registry replaced fully - eg, `eu.gcr.io/gitpod-core-dev/build/agent-smith` becomes `mynewrepo.com/agent-smith`

A simple bash script to mirror images to your own registry is contained in #6756

## Related Issue(s)

Fixes #6979
Fixes #6989
Fixes #6990

## How to test

I have a private container registry with the images in. Can share/demo when necessary

## Release Notes

```release-note
[installer]: add image pull secrets to gitpod components
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mrsimonemms** after the PR has been reviewed.

Associated issue: *#6979*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by csweichel** [comment]
did not test this, but code lgtm

/lgtm

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 57172b589fe24af9fdb3620b47085322b4cc3b9a</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6983#issuecomment-987889225" title="LGTM">csweichel</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankeromnes** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankeromnes` in a comment when ready.

Associated issue: *#6756*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- ~~[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)~~ [csweichel]
- ~~[installer/pkg/components/agent-smith/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/agent-smith/OWNERS)~~ [csweichel]
- ~~[installer/pkg/components/blobserve/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/blobserve/OWNERS)~~ [csweichel]
- ~~[installer/pkg/components/image-builder-mk3/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/image-builder-mk3/OWNERS)~~ [csweichel]
- **[installer/pkg/components/proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/proxy/OWNERS)**
- ~~[installer/pkg/components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/registry-facade/OWNERS)~~ [csweichel]
- **[installer/pkg/components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/server/OWNERS)**
- ~~[installer/pkg/components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-daemon/OWNERS)~~ [csweichel]
- **[installer/pkg/components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-manager-bridge/OWNERS)**
- ~~[installer/pkg/components/ws-scheduler/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-scheduler/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6983#issuecomment-987889225" title="LGTM">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6983#issuecomment-987892878" title="LGTM">geropl</a>*

Associated issue: *#6756*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)~~ [csweichel]
- ~~[installer/pkg/components/agent-smith/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/agent-smith/OWNERS)~~ [csweichel]
- ~~[installer/pkg/components/blobserve/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/blobserve/OWNERS)~~ [csweichel]
- ~~[installer/pkg/components/image-builder-mk3/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/image-builder-mk3/OWNERS)~~ [csweichel]
- ~~[installer/pkg/components/proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/proxy/OWNERS)~~ [geropl]
- ~~[installer/pkg/components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/registry-facade/OWNERS)~~ [csweichel]
- ~~[installer/pkg/components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/server/OWNERS)~~ [geropl]
- ~~[installer/pkg/components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-daemon/OWNERS)~~ [csweichel]
- ~~[installer/pkg/components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-manager-bridge/OWNERS)~~ [geropl]
- ~~[installer/pkg/components/ws-scheduler/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-scheduler/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
