### PR TITLE
[installer] release 2022.09.0

### PR DESCRIPTION
**Pull request by adrienthebo**
## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@adrienthebo: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by MrSimonEmms** [comment]
@adrienthebo I've [merged a PR](https://github.com/gitpod-io/gitpod/pull/13358) specifically for this release - it won't need merging into `main` and updated the release notes appropriately.

I've not changed the binaries as the script is not in there.

**Pull request closed without merging**
