### PR TITLE
[installer] Support MariaDB

### PR DESCRIPTION
**Pull request by ZCube**
## Description
Add MariaDB support to the installer.

## How to test
Render using below config
```
...
database:
  inCluster: true
  mariaDB: true
...
```

## Release Notes
```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **metcalfc** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @metcalfc` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by MrSimonEmms** [comment]
@ZCube thanks for this.

What problem does adding MariaDB support solve? I know MySQL and MariaDB are meant to be compatible, but there are some differences (from memory, I think MySQL supports more unquoted statements than MariaDB). My main concern is that we only officially support MySQL for the database and that this may introduce a divergence between self-hosted and SaaS which we're trying to avoid.

If you wanted to use MariaDB, my suggestion would be to use an external MariaDB - I'd suggest that we keep the in-cluster DB to be MySQL only.

**Comment by ZCube** [comment]
> @ZCube thanks for this.
> 
> What problem does adding MariaDB support solve? I know MySQL and MariaDB are meant to be compatible, but there are some differences (from memory, I think MySQL supports more unquoted statements than MariaDB). My main concern is that we only officially support MySQL for the database and that this may introduce a divergence between self-hosted and SaaS which we're trying to avoid.
> 
> If you wanted to use MariaDB, my suggestion would be to use an external MariaDB - I'd suggest that we keep the in-cluster DB to be MySQL only.

okay. I would consider using the External configuration. For MySQL, only x86 is provided. Because of this, I had to use MariaDB to solve this ARM64 #7700 issue.

**Comment by RedstoneWizard08** [comment]
@ZCube we could add the MySQL helm chart to the `bitnami-compat` repo using this image: [docker-library/mysql](https://github.com/docker-library/mysql) (That is the source Dockerfile for this image: [mysql](https://hub.docker.com/_/mysql))
However, we would also have to reproduce the image as it doesn't support arm64. This is easy to do.

**Comment by corneliusludmann** [comment]
Thank you for your understanding. I would close the PR for now then, okay?

**Pull request closed without merging**
