### PR TITLE
[db-sync] Introduce SyncPeriod (with upper limit now - 5s)

### LINKED ISSUE #14560: [db-sync] Fix potential lost update
There is a gap in db-sync that might lead to lost updates/inserts in some scenarios. The details are outlined in [this doc](https://www.notion.so/gitpod/db-sync-data-consistencies-investigation-3393541c4cc94808b96ade68b22d506c).

While we are in the process of https://github.com/gitpod-io/gitpod/issues/9198 we still intend to use it to ensure data quality before we migrate to a different system. So we should find a pragmatic way to fix this. As part of the deprecation we need to come up with tools to measure gaps like this in general.

### PR DESCRIPTION
**Pull request by geropl**
## Description
This intended to be a small and pragmatic fix to db-sync to make it more reliable before we can retire it completely.
Before, it would always sync from ´[previousRun, ...now`. Also, it was using the local processes clock, which is obviously out-of-sync with the DB's.

This PR addresses this by:
- introducing an upperBound of "now - 5s" for SyncPeriods
- use the DB's clock to establish that SyncPeriod
- (fix a minor comparison error in export.ts which made us double-sync on millisecond matches)

## Related Issue(s)

Fixes #14560 

## How to test
 - `leeway build components/gitpod-db:dbtest-init`
 - `(components/ee/db-sync && yarn db-test)`

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]
Looks sensible

**Comment by geropl** [comment]
Did a small change to avoid eating Errors by accident. Will test in staging once the build has finished.

**Comment by geropl** [comment]
/unhold

Testing on staging looking good.

**Pull request merged**
