### PR TITLE
fix(server): cloning bitbucket branches named such as feature/JIRA-123-summary

### PR DESCRIPTION
**Pull request by ghuntley**
Fixes https://github.com/gitpod-io/gitpod/issues/5364

# observations

Assuming `https://bitbucket.org/gitpod/integration-tests/branch/feature/JIRA-123-summary` as test input the logic did not account for n + 1 segments

```
[0] branch [1] feature [2] jira-123-summary
const branch = moreSegments.length > 1 ? moreSegments[1] : "";
[0] feature
more.ref = branch;
```

# cleanup

1. established `gitpod-test` user and adjusted tests to expect this username.
1. Sample-repository was renamed to integration-tests on our bitbucket account so the purpose is clearer
1. @corneliusludmann's forked repository was moved to gitpod/integration-tests-forked-repository

# testing

Here's the output from `npm run test`. You'll need to define the `GITPOD_TEST_TOKEN_BITBUCKET` using the recently created `gitpod-test` user. See the password safe for specifics.

```
export GITPOD_TEST_TOKEN_BITBUCKET='GITPOD_TEST_TOKEN_BITBUCKET={ "username": "gitpod-test", "value": "REDACTED", "scopes": [] }'
```

```
gitpod /workspace/gitpod/components/server $ npm run test
Debugger listening on ws://127.0.0.1:53197/9cf0b5b1-3a04-48f1-b1d9-6aeffe9e0c1a
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> @gitpod/server@0.0.0 test /workspace/gitpod/components/server
> mocha --opts mocha.opts './**/*.spec.ts' --exclude './node_modules/**'

Debugger listening on ws://127.0.0.1:53141/1720965b-7a95-4266-b11d-0e4e24b6946d
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger listening on ws://127.0.0.1:53356/e380b5b5-25b9-4379-b459-3fc5f43efa7a
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Skipping suite TestGithubContextParser because env var 'GITPOD_TEST_TOKEN_GITHUB' is not set
Skipping suite TestGitlabContextParser because env var 'GITPOD_TEST_TOKEN_GITLAB' is not set


  EMailDomainServiceSpec
Loading TypeORM entities and migrations from /workspace/gitpod/components/gitpod-db/lib/typeorm
Using DB: localhost:23306/gitpod
    ✓ internal_check (5031ms)

  GitHub app
    ✓ should not run prebuilds without explicit configuration
    ✓ should not run prebuilds without tasks to execute
    ✓ should behave well with individual configuration

  TestResourceAccess
    ✓ areScopesSubsetOf
    ✓ scopedResourceGuardIsAllowedUnder
    ✓ tokenResourceGuardCanAccess
    ✓ scopedResourceGuardCanAccess
    ✓ workspaceEnvVarAccessGuardCanAccess

  TestBitbucketContextParser
    ✓ testCanHandleBitbucketRepo
    ✓ testCanNotHandleGitHubRepo
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testShortContext_01 (898ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testSrcContext_01 (1188ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testSrcContext_02 (856ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testSrcContext_03 (1245ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testCommitsContext_01 (813ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testBranchContext_01 (854ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testBranchContext_02 (805ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testBranchContext_03 (801ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testCommitsContext_02 (813ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testSrcContext_04 (1307ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testCommitsContext_03 (417ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testFileContext_01 (1643ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testFileContext_02 (1598ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testDirectoryContext_01 (1667ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testPullRequestContext_01 (1239ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testPullRequestContext_02 (1732ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testIssueContext_01 (1160ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testSrcContextForkedRepo_01 (1569ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testFetchCommitHistory (419ms)

  TestBitbucketFileProvider
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testGetFileContents (362ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testGetLastChangeRevision (376ms)

  TestBitbucketLanguageProvider
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testGetLanguages (387ms)
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
{ userId: 'somefox' } Could not get languages of Bitbucket repo.
    ✓ testGetLanguagesNonExistingRepo (328ms)

  TestBitbucketRepositoryProvider
 BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket 
    ✓ testGetRepo (414ms)

  TestConsensusLeaderQuorum
    - testSingleServer
    - testMultipleFixedServer
    - testMultipleServersLoss
    - testMultipleServersStableConsensus

  express-util
    isAllowedWebsocketDomain for dev-staging
      ✓ should return false for workspace-port locations
      ✓ should return true for workspace locations
      ✓ should return true for dashboard
    isAllowedWebsocketDomain for gitpod.io
      ✓ should return false for workspace-port locations
      ✓ should return true for workspace locations

  TestWsLayer
    ✓ testSimple
    ✓ doesNotCallNext
Error: Should be caught
    at Object.<anonymous> (/workspace/gitpod/components/server/src/express/ws-layer.spec.ts:32:29)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/workspace/gitpod/node_modules/ts-node/src/index.ts:435:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/workspace/gitpod/node_modules/ts-node/src/index.ts:438:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /workspace/gitpod/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/workspace/gitpod/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/workspace/gitpod/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/workspace/gitpod/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 { ws: {}, req: {} }
    ✓ errorHandlingSimpleCalled
Error: Should be caught
    at Object.<anonymous> (/workspace/gitpod/components/server/src/express/ws-layer.spec.ts:32:29)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/workspace/gitpod/node_modules/ts-node/src/index.ts:435:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/workspace/gitpod/node_modules/ts-node/src/index.ts:438:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /workspace/gitpod/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/workspace/gitpod/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/workspace/gitpod/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/workspace/gitpod/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 { ws: {}, req: {} }
    ✓ errorHandlingSimpleNotCalled
Error: Should be caught
    at Object.<anonymous> (/workspace/gitpod/components/server/src/express/ws-layer.spec.ts:32:29)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/workspace/gitpod/node_modules/ts-node/src/index.ts:435:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/workspace/gitpod/node_modules/ts-node/src/index.ts:438:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /workspace/gitpod/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/workspace/gitpod/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/workspace/gitpod/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/workspace/gitpod/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 { ws: {}, req: {} }
    ✓ errorHandlingChained
Error: Should be caught
    at Object.<anonymous> (/workspace/gitpod/components/server/src/express/ws-layer.spec.ts:32:29)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/workspace/gitpod/node_modules/ts-node/src/index.ts:435:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/workspace/gitpod/node_modules/ts-node/src/index.ts:438:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /workspace/gitpod/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/workspace/gitpod/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/workspace/gitpod/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/workspace/gitpod/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 { ws: {}, req: {} }
    ✓ errorHandlingRecover
Error: Should be caught
    at Object.<anonymous> (/workspace/gitpod/components/server/src/express/ws-layer.spec.ts:32:29)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/workspace/gitpod/node_modules/ts-node/src/index.ts:435:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/workspace/gitpod/node_modules/ts-node/src/index.ts:438:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /workspace/gitpod/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/workspace/gitpod/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/workspace/gitpod/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/workspace/gitpod/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 { ws: {}, req: {} }
    ✓ errorHandlingDuringErrorHandlingAndRecover

  TestGithubContextParser
    - testErrorContext_01
    - testErrorContext_02
    - testErrorContext_03
    - testErrorContext_04
    - testTreeContext_01
    - testTreeContext_02
    - testTreeContext_03
    - testTreeContext_04
    - testTreeContext_05
    - testTreeContext_06
    - testTreeContext_07
    - testTreeContext_tag_01
    - testReleasesContext_tag_01
    - testCommitsContext_01
    - testCommitContext_01
    - testCommitContext_02_notExistingCommit
    - testCommitContext_02_invalidSha
    - testPullRequestContext_01
    - testPullRequestthroughIssueContext_04
    - testIssueContext_01
    - testIssuePageContext
    - testIssueThroughPullRequestContext
    - testBlobContext_01
    - testBlobContext_02
    - testBlobContextShort_01
    - testBlobContextShort_02
    - testFetchCommitHistory

  TestGitlabContextParser
    - testErrorContext_01
    - testTreeContext_01
    - testTreeContext_01_regression
    - testTreeContext_02
    - testTreeContext_03
    - testTreeContext_04
    - testTreeContext_tag_01
    - testCommitsContext_01
    - testCommitContext_01
    - testCommitContext_02_notExistingCommit
    - testPullRequestContext_01
    - testIssueContext_01
    - testTreeContextSubgroup_01
    - testTreeContextSubgroup_02
    - testTreeContextSubgroup_03
    - testTreeContextSubgroup_04
    - testTreeContextSubgroup_05
    - testTreeContextSubgroup_tag_01
    - testIssueContextSubgroup_01
    - testTreeContextBranchWithSlash
    - testTreeContextBranchWithSlash_NewURLwithDash
    - testTreeContextTagWithSlash
    - testTreeContextBranchWithSlashAndPathWithSpaces
    - testEmptyProject
    - testFetchCommitHistory

  TestAuthenticationGitHub
    - before
    - after
    - testAuthenticationOnRepositories

  PermissionSpec
    ✓ hasPermission_viewer
    ✓ hasPermission_dev

  TestEnvvarPrefixParser
    ✓ testFindPrefixGood
    ✓ testFindPrefixSomewhatOk
    ✓ testFindPrefixBad
    ✓ testHandleGood
    ✓ testHandleDuplicate
    ✓ testHandleBad


  55 passing (28s)
  59 pending

Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```

# final thoughts

We should hook up `npm run test` for `components/server` into Gitpod's CI/CD so that this test path is validated in the future.

## Release Notes

```release-note
- fixed cloning bitbucket branches named such as feature/JIRA-123-summary
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **geropl** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @geropl` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **geropl** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @geropl` in a comment when ready.

Associated issue: *#5364*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
@ghuntley: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by svenefftinge** [comment]
hey @ghuntley can you make this "ready for review", rebase and squash the change set, so we can land it?

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankeromnes** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankeromnes` in a comment when ready.

Associated issue: *#5364*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by mikenikles** [comment]
We have community members who are waiting for this. I'm reopening it since it got closed by stalebot.

@ghuntley see Sven's comment above.

**Comment by blairscott** [comment]
> We have community members who are waiting for this. I'm reopening it since it got closed by stalebot.
> 
> @ghuntley see Sven's comment above.

Thanks @mikenikles, as a quick update I have found a workaround by simply opening the last commit and checking out the branch  in the workspace. If this is potentially going to be resolved soon-ish then that's a pretty acceptable workaround for me in the interim. 

Appreciate the prompt reply.

**Comment by gtsiolis** [comment]
@ghuntley Cross-posting from https://github.com/gitpod-io/gitpod/pull/6652#issuecomment-971759961:
> Bitbucket is now enabled on preview environments, see [relevant discussion](https://gitpod.slack.com/archives/C01KGM9EBD4/p1636993758304200) (internal).

**Comment by JanKoehnlein** [comment]
@ghuntley please remove the `draft` annotation once this is ready for us to review.

**Comment by ghuntley** [comment]
> @ghuntley please remove the `draft` annotation once this is ready for us to review.

@JanKoehnlein can you please put this through the wringer and carefully review.

Test with

```
https://gh-bb.staging.gitpod-dev.com/#https://gh-bb.staging.gitpod-dev.com/#https://bitbucket.org/gitpod/integration-tests/src/bcf3a4b9329385b7a5f50a4490b79570da029cf3/?at=feature%2FJIRA-123-summary
```

If something needs adjusting please make the needed changes. I was unable to re-test after cherrypicking and was greeted with the following error:

Screen Shot 2021-12-01 at 10 03 48 am

**Comment by jankeromnes** [comment]
> I was unable to re-test after cherrypicking and was greeted with the following error

@ghuntley Have your added your `@gitpod.io` address in https://github.com/settings/emails ? (Doesn't need to be the primary, but needs to be in the list and verified)

**Comment by jankeromnes** [comment]
Stealing this review 😇

**Comment by ghuntley** [comment]
Yes, geoff@gitpod.io is in the list and verified. Please steal away and help get this shipped (make sure you double check my work - first PR to the product itself) <3

**Review by jankeromnes — APPROVED** [review]
Wow, so many thanks for fixing this bug and also improving the tests!

Screenshot 2021-12-01 at 10 42 16

- Bug fix looks very good 👍
- Works as intended (could reproduce the bug in prod, but not with this PR)

Unfortunately, I wasn't able to run the integration tests:

```
gitpod /workspace/gitpod/components/server $ npm run test

> @gitpod/server@0.0.0 test
> mocha --opts mocha.opts './**/*.spec.ts' --exclude './node_modules/**'

/workspace/gitpod/node_modules/ts-node/src/index.ts:750
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
ee/src/auth/email-domain-service.ts:8:25 - error TS7016: Could not find a declaration file for module 'swot-js'. '/workspace/gitpod/node_modules/swot-js/lib/swot.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/swot-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'swot-js';`

8 import * as SwotJs from 'swot-js';
                          ~~~~~~~~~
```

and the suggested command didn't help:

```
gitpod /workspace/gitpod/components/server $ npm i --save-dev @types/swot-js
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@gitpod%2fcontent-service - Not found
npm ERR! 404 
npm ERR! 404  '@gitpod/content-service@0.1.5' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

But I guess the problem is located between keyboard and chair. 😅 

/approve
/lgtm

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 07f6711e3acbeae5781548b0bb9b28abc29c2cf9</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5367#pullrequestreview-820049200" title="LGTM">jankeromnes</a>*

Associated issue: *#5364*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
