### PR TITLE
[dashboard] Be more defensive when constructing "invalida billing address" notifications

### PR DESCRIPTION
**Pull request by geropl**
## Description

Instead of executing all calls at once, be more defensive, and check previous calls.

I noticed that for some customers, we did not change them back to billing strategy "other" after they cancelled their subscription... :roll_eyes: But even for those cases, this code does not emit as much errors as before (just one).

## Related Issue(s)

Fixes EXP-1393

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by akosyakov** [comment]
@svenefftinge Could you review please? 🙏

**Comment by geropl** [comment]
@AlexTugarev Would you maybe have time to review? It's only about reducing the amount of error messages we produce on the backend by issuing unnecessary API calls.

**Review by AlexTugarev — APPROVED** [review]
Code change looks good.

**Pull request merged**
