### PR TITLE
Update grpc generator scripts and sync dependencies versions

### PR DESCRIPTION
**Pull request by aledbf**
- The scripts for grpc code generation now use one parent script with common functions and versions (one place for updates)
- The grpc code that is not generated was moved to a file named `not_autogenerated_*.pb.go`

**Dependencies:**
- google.golang.org/grpc v1.36.0
- google.golang.org/protobuf v1.25.0
- github.com/grpc-ecosystem/grpc-gateway/v2 v2.2.0
- github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.2.0

Edit: this is a prefactoring for https://github.com/gitpod-io/gitpod/pull/3413

### CODE REVIEW

**Review by csweichel — APPROVED** [review]
Awesome. Thanks for wading through this mess.

Before merging, please beware that there's a bunch of other PRs that also touch the dev-environment image:
- https://github.com/gitpod-io/gitpod/pull/3388
- https://github.com/gitpod-io/gitpod/pull/3407

**Comment by aledbf** [comment]
Replaces #3407 and https://github.com/gitpod-io/gitpod/pull/3388/files#diff-daad2f3ffca36bb0c13229cde5a438b14232487c402783a8ac0094203613d210R69-R70

**Pull request merged**
