### PR TITLE
[image-builder] Export image config

### LINKED ISSUE #5497: [image-builder] mkIII: imagebuild workspaces seem to ignore "workspace templates"
While testing https://github.com/gitpod-io/gitpod/pull/5480 I was blocked because an `imagebuild` got scheduled to a NodePool where no suitable `ws-daemon` was running (context: https://github.com/gitpod-io/gitpod/pull/5432).

On inspection of the `imagebuild` it did not contain a `nodeAffinity`, but the `workspace-template` ConfigMap did:
 - not for `default`
 - but for all specific workspace types (incl. `imagebuild`)

I did not have time to investigate further. This should be easily reproduceable by triggering an image build in a preview env. (note that you might get lucky and the build succeeds if the workspaces ends up on the "right" node. Please check the pods yaml to verify that there's no nodeAffinity).

### LINKED ISSUE #5597: [image-builder-mk3] Does not carry over env vars from base images
The underlying issues seems to be that env variables from base iamges are not carried over to the resulting image.
For instance, workspaces on `gitpod-io/gitpod` could not find `gcloud` because it was not in the `PATH` (but in the image).
Switching to old `image-builder` did fix this.

Incident: https://www.gitpodstatus.com/incidents/fk6prflgvvth

User reports:
 - https://github.com/gitpod-io/gitpod/issues/5594
 - https://github.com/gitpod-io/gitpod/issues/5589

### PR DESCRIPTION
**Pull request by csweichel**
## Description
This PR makes image-builder properly export the image config when building the workspace image. buildkit does not do this by default and the exporter needs to be told which image-config to export.

This PR also corrects a failure mode introduced by the instability of the `failed` condition of workspace status updates produced by ws-manager. Because of this instability, image-builder would falsely report an image-build as done when it really was not. We solve this by re-resolving the supposedly built image ref and returning a failure condition if it wasn't built. There's also a unit test for this.

## Related Issue(s)

fixes #5597 
fixes #5497

## How to test
TODO: unit tests are upcoming (hence this being a draft)

## Release Notes

```release-note
[image-builder] Include environment variables in the built workspace image
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **csweichel** after the PR has been reviewed.

Associated issue: *#5597*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by aledbf** [comment]
@csweichel I still see the same behavio?

Opening this PR in staging I get the same behavior (not inheriting PATH from dev-environment image)
```
oci-tool fetch image reg.csweichel-image-builder-mk-does-5597.staging.gitpod-dev.com:30099/remote/e0b0b0e4-7075-48b6-8934-53635ad28047:latest
{
  "architecture": "amd64",
  "config": {
    "Env": [
      "PATH=/ide/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "EDITOR=/ide/bin/code",
      "VISUAL=/ide/bin/code",
      "GP_OPEN_EDITOR=/ide/bin/code",
      "GIT_EDITOR=/ide/bin/code --wait",
      "GP_PREVIEW_BROWSER=/ide/bin/code --preview",
      "GP_EXTERNAL_BROWSER=/ide/bin/code --openExternal"
    ],
    "WorkingDir": "/"
  },
```

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **aledbf** after the PR has been reviewed.

Associated issue: *#5597*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **aledbf** after the PR has been reviewed.

Associated issue: *#5597*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **csweichel** after the PR has been reviewed.

Associated issue: *#5597*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**
- **[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by csweichel** [comment]
Things fail oddly here:
```
failed to solve: failed commit on ref \\\"manifest-sha256:1498980c832450ae54c3a055b828eb9afd8417aa31be10597701dca5d35e6c6f\\\": cannot reuse body, request must be retried\"
```

**Comment by csweichel** [comment]
Issue we're facing is https://github.com/containerd/containerd/issues/5978

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **aledbf** and additionally assign **corneliusludmann** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @corneliusludmann` in a comment when ready.

Associated issue: *#5597*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**
- **[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by aledbf** [comment]
https://csweichel-image-builder-mk-does-5597.staging.gitpod-dev.com/#https://github.com/gitpod-io/gitpod/

Screenshot from 2021-09-24 14-44-35

```
{"host":"eu.gcr.io","level":"debug","message":"fetch response received","response.header.accept-ranges":"none","response.header.cache-control":"private","response.header.content-type":"application/json","response.header.date":"Fri, 24 Sep 2021 17:46:08 GMT","response.header.docker-distribution-api-version":"registry/2.0","response.header.server":"Docker Registry","response.header.vary":"Accept-Encoding","response.header.x-frame-options":"SAMEORIGIN","response.header.x-xss-protection":"0","response.status":"404 Not Found","severity":"DEBUG","time":"2021-09-24T17:46:08Z","url":"https://eu.gcr.io/v2/gitpod-core-dev/registry/workspace-images/manifests/5f4d43c7eed6f8277f2ae06148ff9b25b68a87989e6f503eb0ec2545ffc97dc0"}
{"host":"eu.gcr.io","level":"info","message":"trying next host - response was http.StatusNotFound","severity":"INFO","time":"2021-09-24T17:46:08Z"}
```

**Comment by csweichel** [comment]
Unfortunately we don't have an updated preview environment yet :( 
The build doesn't work because of some networking issue in the build cluster

**Comment by csweichel** [comment]
After switching to crane the workspace image push finally works as expected.
Once https://github.com/containerd/containerd/issues/5978 is fixed, we should switch back to buildkit.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: d860ebe7424793dd471a476320c056cf211d66ac</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5693#issuecomment-929117440" title="LGTM">aledbf</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **corneliusludmann** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @corneliusludmann` in a comment when ready.

Associated issue: *#5597*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [aledbf]
- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**
- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [aledbf]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5693#issuecomment-929117440" title="LGTM">aledbf</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/5693#issuecomment-930023877" title="Approved">corneliusludmann</a>*

Associated issue: *#5597*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [aledbf,corneliusludmann]
- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [corneliusludmann]
- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [aledbf]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
