### PR TITLE
Hide the latest editor warning for stopping or stopped workspaces

### PR DESCRIPTION
**Pull request by gtsiolis**
## Description

Pick up changes from the community contribution in https://github.com/gitpod-io/gitpod/pull/16940. Cc @Devansu-Yadav 

For more context, see **[relevant section](https://www.notion.so/gitpod/How-we-develop-e8ce7e562478458a9223eb9b797415b2?pvs=4#ef8b432a56b6425db16039d603ac97f4)** in How we develop.

<details>
<summary>Changes summary and walkthrough generated by Copilot</summary>

</details>

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/issues/11035

## How to test
1. Use Latest for the editor
2. Open a workspace
3. Stop a workspace
4. Notice the latest editor warning is not preset for stopping or stopped workspace

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - gt-merge-16940</li>
	<li><b>🔗 URL</b> - <a href="https://gt-merge-16940.preview.gitpod-dev.com/workspaces" target="_blank">gt-merge-16940.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - gt-merge-16940-gha.13958</li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [X] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by gtsiolis** [comment]
Changes were previously reviewed by @mustard-mh in https://github.com/gitpod-io/gitpod/pull/16940#pullrequestreview-1357054993 but could be worth taking a closer look in case changes are no longer applicable or relevant. 🏓

**Comment by laushinka** [comment]
@gtsiolis Could you rerun the preview? I'll review the PR :)

**Comment by gtsiolis** [comment]
@laushinka I rebased the branch to update it and re-trigger the preview environment.

You can also re-run the preview by re-running all jobs in the **[Install Gitpod](https://github.com/gitpod-io/gitpod/actions/runs/5643060265/job/15284298244?pr=18336)** job.

**Comment by gtsiolis** [comment]
**heads-up**: @laushinka There's seems to be an ongoing issue with creating runners which won't let us spin up a preview environment until it gets resolved, see [relevant discussion](https://gitpod.slack.com/archives/C032A46PWR0/p1691572195326959) (internal). Cc @vulkoingim

**Comment by gtsiolis** [comment]
**heads-up**: @laushinka The issue has been resolved, preview environment is up and running. 💡 
> https://gt-merge-16940.preview.gitpod-dev.com/workspaces

**Comment by laushinka** [comment]
Sorry ended up being swamped. Reviewing now!

**Review by mustard-mh — APPROVED** [review]
LGTM

| Before Stop | Stop |
|:-:|:-:|
|SCR-20230828-mrtf |image |

**Comment by gtsiolis** [comment]
Thanks for taking a look, @mustard-mh. 🌮

**Comment by laushinka** [comment]
Thank you for taking it over, @mustard-mh! Sorry, @gtsiolis for dropping the ball 🙏🏽

**Pull request merged**
