### PR TITLE
Fix dark theme colors and overflowing rounded corners

### PR DESCRIPTION
**Pull request by gtsiolis**
Fix https://github.com/gitpod-io/gitpod/issues/4717.

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **csweichel** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @csweichel` in a comment when ready.

Associated issue: *#4717*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by gtsiolis** [comment]
@jankeromnes could you review these minor changes since you already took a look in https://github.com/gitpod-io/gitpod/issues/4717#issuecomment-910080923? 🏀

**Comment by jankeromnes** [comment]
Sure! Thanks.

Instinctively, I'd really want a `overflow-hidden` next to the container's `rounded-xl`. I think that's a much better solution that playing with `rounded-t-xl` or `rounded-b-xl` in the child containers.

However, let's see how the preview environment looks with the current changes. 🙂

**Comment by gtsiolis** [comment]
> Instinctively, I'd really want ...

@jankeromnes Same here!

Feel free to revert the changes in favor of using `overflow-hidden.

The only push back for not using `overflow-hidden` could be browser support although I think both approaches are well supported for what is needed here. See [`border-top-radius`](https://caniuse.com/?search=border-top-radius) v. [`overflow-hidden`](https://caniuse.com/?search=overflow-hidden).

**Comment by jankeromnes** [comment]
> The only push back for not using `overflow-hidden` could be browser support although I think both approaches are well supported for what is needed here. See [`border-top-radius`](https://caniuse.com/?search=border-top-radius) v. [`overflow-hidden`](https://caniuse.com/?search=overflow-hidden).

`overflow: hidden` seems like a cornerstone of the web that should work everywhere.

The way I read caniuse.com is:

- `border-top-radius` is supported everywhere, except on Opera Mini
- `overflow: hidden` is supported everywhere, even on Opera Mini (also, there are stripes but they're about additional features that we don't use)

**Review by jankeromnes — APPROVED** [review]
Many thanks!

Works like a charm ✨

I'd still prefer an `overflow-hidden` fix, but it's cool to do that later. The most important is that the dashboard looks good (and feels snappy) in any theme and on any device. ☺️

/approve

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 1670f21a75012d81499af497b571e190d50bb11c</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5481#pullrequestreview-743911892" title="Approved">jankeromnes</a>*

Associated issue: *#4717*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by gtsiolis** [comment]
Thanks @jankeromnes! 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢

**Pull request merged**
