### PR TITLE
[vscode] upgrade to 1.54.1

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

It upgrade to 1.54.1. We will need to ugprade again next week, since there will be a recovery release, but we also need new changes to progress with terminals and auth.

Changes in Code: https://github.com/gitpod-io/vscode/commit/2fbcb5732e782832afb686dd2cb128083a930a9c

#### How to test

- Switch to VS Code
- Start a workspace.
- Test follwing:
  - websockets and workers are properly proxied, for instance, diff editor should be operatable
  - terminals are preserved between window reloads (both regular and tasks)
  - extension host process, check debugging and language smartness
  - extension management (installing/uninstalling)
  - code cli should open files
  - user data are sync across workspaces as well as on workspace restart, especially for extensions
  - settings should not contain any mentions of MS telemetry
  - workspace commands, i.e. F1 -> Gitpod: prefix

### CODE REVIEW

**Comment by akosyakov** [comment]
Got some exceptions:
```
 Call not found: setLevel: Error: Call not found: setLevel
    at LoggerChannel.call (/ide/out/vs/gitpod/node/server.js:21488:19)
    at ChannelServer.onPromise (/ide/out/vs/gitpod/node/server.js:13493:35)
    at ChannelServer.onRawMessage (/ide/out/vs/gitpod/node/server.js:13466:33)
    at /ide/out/vs/gitpod/node/server.js:13411:73
    at Emitter.fire (/ide/out/vs/gitpod/node/server.js:4941:38)
    at BufferedEmitter.fire (/ide/out/vs/gitpod/node/server.js:14532:35)
    at PersistentProtocol._receiveMessage (/ide/out/vs/gitpod/node/server.js:14811:41)
    at /ide/out/vs/gitpod/node/server.js:14667:83
    at Emitter.fire (/ide/out/vs/gitpod/node/server.js:4941:38)
    at ProtocolReader.acceptChunk (/ide/out/vs/gitpod/node/server.js:14346:37)
    at /ide/out/vs/gitpod/node/server.js:14315:61
    at Emitter.fire (/ide/out/vs/gitpod/node/server.js:4941:38)
    at /ide/out/vs/gitpod/node/server.js:28841:42
    at afterWrite (_stream_writable.js:490:5)
    at onwrite (_stream_writable.js:470:7)
    at InflateRaw.afterTransform (_stream_transform.js:98:3)
    at Zlib.processCallback (zlib.js:578:8)
```

**Comment by akosyakov** [comment]
I tested it and it worked me. Does anyone want to test too or I can merge it? cc @jankeromnes @JanKoehnlein @svenefftinge @csweichel ?

**Comment by geropl** [comment]
Having alook.

**Comment by geropl** [comment]
Cert error. Will :heavy_check_mark:

**Review by geropl — APPROVED** [review]
:heavy_check_mark:

**Pull request merged**
