### PR TITLE
[code] Gitpod walkthrough

### PR DESCRIPTION
**Pull request by akosyakov**
## Description

Update latest VS Code to bring Gitpod walkthrough: https://github.com/gitpod-io/openvscode-server/pull/110

Gitpod Code commit: https://github.com/gitpod-io/openvscode-server/commit/128bab190731bc4af1a6e58b9324110a0d087884

## Related Issue(s)

Related to https://github.com/gitpod-io/gitpod/issues/5964

## How to test

- Switch to VS Code Insiders: https://ak-gitpod-walkthrough.staging.gitpod-dev.com/preferences
- Start a workspace.
- On the Welcome screen, look for the new walkthrough on the right side
- Review the walkthrough, click links and verify everything works as expected

## Release Notes

```release-note
VS Code: Add a Get Started with Gitpod walkthrough
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **akosyakov** after the PR has been reviewed.

Associated issue: *#5964*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by akosyakov** [comment]
@mikenikles I tried it but it somehow broken, I cannot click on links in the walkthrough.

**Comment by mikenikles** [comment]
Nope, #5964 is a follow-up with a few enhancements. I don't think there's an open issue for the work in this PR.

Regular hyperlinks to docs etc seem to work, the two that are now broken for some reason are the ones that execute a command, e.g. open the ports panel or run a terminal command.

I'm looking into it 👀

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 4a0f2090a00d7e1e8d745141c4ca282a545044a0</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6095#issuecomment-940972267" title="LGTM">corneliusludmann</a>*

Associated issue: *#5964*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)~~ [corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
