### PR TITLE
[supervisor] Do not log error when it has `Unavailable` code

### PR DESCRIPTION
**Pull request by jeanp413**
## Description

Do not log error when it has `Unavailable` code

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by akosyakov — APPROVED** [review]
I have not tried, but code changes looks good.

/hold

@jeanp413 unhold when you think it is good

**Comment by akosyakov** [comment]
@jeanp413 today it helped me to run with both clean slate deployment and recreate, try

**Comment by mustard-mh** [comment]
Why we filter this out? @jeanp413

**Comment by akosyakov** [comment]
@mustard-mh I think because it was very loud, i.e. each 10 mins, if we handle reconnections in public-api-server, i.e. exponential backoff retry there, would we have less reconnections in supervisor?

**Comment by mustard-mh** [comment]
Maybe we should log this `Unavailable` because I can only see `Unavailble` [grpc metrics](https://gitpod.slack.com/archives/C021LT6GUJG/p1677181616809189?thread_ts=1677162220.181449&cid=C021LT6GUJG) but the logging in supervisor all filter out

Because I want to confirm supervisor commit hash to check if users are using old version of supervisor. in this case, we can enable the experimental again

**Comment by akosyakov** [comment]
I guess with your recent changes to auto reconnect it is sensible

**Pull request merged**
