### PR TITLE
werft/job-config: Make previews from 20+ character branches possible

### PR DESCRIPTION
**Pull request by ArthurSens**
Signed-off-by: ArthurSens <arthursens2005@gmail.com>

## Description

This PR effectively makes it possible to create preview environments from super long branch names by cutting it into 20 characters max. The reasons why we can't use more than 20 characters are listed [here](https://github.com/gitpod-io/ops/issues/1252).

**_I'm opening this as a draft because_**:
The initial idea of adding a label does not work out-of-the-box as we expected.

* Label values can't have special characters like `/`, which are commonly used by our branch names
* Label values still have a 63 characters limit

Creating this PR to start the discussion, should we give up on verifying a possible conflicting namespace? Should we go with a mixture of branch name + hash?

## Related Issue(s)

Fixes https://github.com/gitpod-io/ops/issues/1252

## How to test

Create a super long branch(from this PR) and create a new preview

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by wulfthimm** [comment]
This would break SSH access to preview environments https://github.com/gitpod-io/gitpod/blob/adf6a322fbf23b69c5a8be343df5cca32367bcc2/dev/preview/ssh-proxy-command.sh#L3

**Comment by ArthurSens** [comment]
> dev/preview/ssh-proxy-command.sh

Good catch! I've also just noticed that you've opened https://github.com/gitpod-io/gitpod/pull/8316 (platform was not set as reviewers), I'm wondering our best option here is to just merge that one and work to get Harvester done ASAP

**Comment by mads-hartmann** [comment]
@ArthurSens I believe we can close this in favour of https://github.com/gitpod-io/gitpod/pull/8692 now :)

**Comment by ArthurSens** [comment]
Yep :)

**Pull request closed without merging**
