### PR TITLE
CI: Add Hadolint

### PR DESCRIPTION
**Pull request by Kreyren**
Dockerfile linting in CI phase

Signed-off-by: Jacob Hrbek <kreyren@rixotstudio.cz>

### CODE REVIEW

**Comment by Kreyren** [comment]
Tested in https://github.com/Kreyren/gitpod/pull/6

**Comment by JesterOrNot** [comment]
@Kreyren Please use Werft instead that way the tests are in the same place.

**Comment by Kreyren** [comment]
@JesterOrNot Werft doesn't seem to support trigger based on GitHub events https://docs.github.com/en/actions/reference/events-that-trigger-workflows so that would be wasting resources when the CI is not needed to run.

**Comment by JesterOrNot** [comment]
Werft uses caching so it only builds a package when the files change. See a directory's `BUILD.yaml` file for more.

**Comment by csweichel** [comment]
> Please use Werft instead that way the tests are in the same place.

👍  It is very unlikely we'll move to GitHub actions any time soon, or that we'd introduce GH actions just for linting.

> Werft doesn't seem to support trigger based on GitHub events 

Werft is GitHub event triggered, i.e. runs on push.



> Werft uses caching so it only builds a package when the files change. See a directory's `BUILD.yaml` file for more.

In the build job we use a caching build system called [leeway](https://github.com/TypeFox/leeway). If you were to integrate the hadolint checks in the leeway build, that would - as @JesterOrNot already pointed out - cause the linter to run only if relevant code changed.

**Comment by csweichel** [comment]
it's unlikely this PR will be updated again - closing for now.
If we still want hadolint, someone should raise a new one with the changes as outlined.

**Pull request closed without merging**
