### PR TITLE
[supervisor info] don't fail workspace info if workspace root is removed

### LINKED ISSUE #3752: renaming workspace folder/file name breaks the workspace
### Bug description

We assume in many places that after the content initialisation the workspace file/folder name remain unchange, but user can actually change it.

### Steps to reproduce

Open this repo and rename gitpod-ws.theia-workspace file.

### Expected behavior

_No response_

### Example repository

_No response_

Screenshot 2021-04-06 at 09 47 02

### LINKED ISSUE #3848: git checkout breaks workspace
### Bug description

`git checkout \<any-branch\>` triggers the workspace to go into an error state and terminate:

### Steps to reproduce

1. Open https://gitpod.io/#https://github.com/gitpod-io/gitpod
2. `git checkout` any other branch, for instance `git checkout gpl/fix-delete-workspaces`

### Expected behavior

Workspace should stay alive.

### Example repository

_No response_

image

### PR DESCRIPTION
**Pull request by akosyakov**
fix #3752

### CODE REVIEW

**Comment by geropl** [comment]
@akosyakov Branch name too long maybe? (Will add a check today/tomorrow to handle that...)

**Review by csweichel — APPROVED** [review]
LGTM

**Comment by AlexTugarev** [comment]
@akosyakov, please merge if that fix works 🙏🏻

**Comment by akosyakov** [comment]
no way with failed build, will create another branch and PR

**Comment by akosyakov** [comment]
superseded by https://github.com/gitpod-io/gitpod/pull/3968

**Pull request closed without merging**
