### PR TITLE
[usage] Initial setup for component

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

Initial setup for usage-component. This component will be responsible for collecting usage data and eventually creating invoices for SaaS.

This is based on [RFC: Usage based pricing (internal)](https://www.notion.so/gitpod/RFC-Usage-Based-Pricing-Architecture-8c262875318941d7b4e8ac12eeb99210)

## Related Issue(s)

Fixes #

## How to test

https://github.com/gitpod-io/gitpod/pull/10227#issuecomment-1136941727

## Release Notes

```release-note
NONE
```

## Documentation

NONE

### CODE REVIEW

**Comment by jankeromnes** [comment]
Many thanks @easyCZ!

Could you please add a few hints to the `How to test` section? (FYI I tried opening your PR in Gitpod, and looked for a `usage-xyz` pod running, but there was none)

**Comment by easyCZ** [comment]
@jankeromnes there's currently nothing to test really. It's not yet deployed anywhere as this PR only performs component setup.

One test you can run is `cd components/usage && go run main.go` to check it runs. This is in a way already tested through CI as we build the component with werft

**Comment by easyCZ** [comment]
I've changed the hello world in this PR to use `baseserver` and start it. This then runs the metrics and live/ready endpoints os we can better test this.

To run the test, do 
```bash
cd components/usage

go run main.go run
```
and in another terminal, run `curl localhost:9502/metrics` which demonstrates the server running and serving metrics.

**Review by jankeromnes — APPROVED** [review]
Many thanks @easyCZ! 👍

Briefly skimmed the code, looks good, ran the provided test commands, works, and generally Gitpod still seems to work fine. 🎉

**Pull request merged**
