### PR TITLE
[supervisor] Check if git repository is shallow before running --unshallow

### PR DESCRIPTION
**Pull request by aledbf**
## Description

https://git-scm.com/docs/git-rev-parse

## Related Issue(s)

xref: https://cloudlogging.app.goo.gl/iaodaYmM7HfTDpwq8

## How to test
- Start a workspace
- Stop the workspace and wait until is not running
- Reopen the workspace
- Check workspace logs and check it does not contain:
  `fatal: --unshallow on a complete repository does not make sense`
 
## Release Notes
```release-note
NONE
```

### CODE REVIEW

**Comment by jeanp413** [comment]
Thanks @aledbf, but do you know why we get this error? As far as I know we always do a shallow clone and then unshallow so does this mean we are unshallowing twice (or more times) :thinking: ?

**Comment by aledbf** [comment]
> Thanks @aledbf, but do you know why we get this error? As far as I know we always do a shallow clone and then unshallow so does this mean we are unshallowing twice (or more times) thinking ?

I think this happens when you restart a workspace. I can see `jsonPayload.source="from-backup"` (which makes sense)

**Comment by jeanp413** [comment]
From the logs I see this error started happening on may 29th, maybe the root cause is somewhere else, will take a quick look just to be sure

**Review by jeanp413 — APPROVED** [review]

**Pull request merged**
