### PR TITLE
[JetBrains] Upgrade Gateway Plugin stable version to v223.7571.203

### PR DESCRIPTION
**Pull request by felladrin**
## Description

Upgrade JetBrains Gateway Plugin stable version to v223.7571.203. This is the Stable Gateway version since 2022-11-30.

image

Changes in this PR:
- The deletion of the files from `stable` folder.
- The move of files from `latest` to the root of the plugin codebase, as those classes are compatible with all v223 versions until the moment.
- The update of `plugin.xml` and `extensions.xml` to reflect the changes above.

## How to test

1. Ensure you have the Gateway installed from [JetBrains Toolbox App](https://www.jetbrains.com/toolbox-app/) and have it up-to-date.
2. Download the plugin build related to this branch in [Dev Versions](https://plugins.jetbrains.com/plugin/18438-gitpod-gateway/versions/dev), and [install it on the Gateway](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk).
    - Download and check the stable plugin version in Gateway v223.7x.
    - Download and check the latest plugin version in Gateway v223.8x.
4. Create a new workspace from the Gateway (it's ok to use the pre-selected IDE and Repository) and confirm if JetBrains Client can connect to it.

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=jetbrains
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by felladrin** [comment]
I'll disable integration tests, as they have already timed out twice (with "panic: test timed out after 1h0m0s"), and will write instructions on how to test it manually quickly.

**Comment by felladrin** [comment]
I checked it manually, and it worked fine with Stable and Latest ✅ 
Tested it by connecting to workspaces.

image
image

**Review by andreafalzetti — APPROVED** [review]
Tested for both versions and works as expected ✅ 

Thanks @felladrin for updating it 🙌

**Pull request merged**
