### PR TITLE
[GP-CLI] fix `gp preview` not outputting stderr and stdout properly

### PR DESCRIPTION
**Pull request by mustard-mh**
## Related Issue(s)

Fixes ENT-743

## How to test

https://hw-preview-err.preview.gitpod-dev.com/workspaces

- Open a workspace in preview env
- Exec command below, there should have no error and prompt to open `google.com`
```
gp preview --external https://google.com
```
- Exec command below, it should show error messages
```
ELECTRON_RUN_AS_NODE=1 gp preview --external https://google.com
```

image

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Review by akosyakov — APPROVED** [review]
I did not test, the important point that we don't affect the happy path, i.e. we don't start printing anything as before.

**Comment by geropl** [comment]
Testing...

**Review by geropl — APPROVED** [review]
Tested, and as far as I could see, works as before

Anton wrote:
> [...] the important point that we don't affect the happy path, i.e. we don't start printing anything as before.

With this change we would emit everything, always.

@mustard-mh I can't judge how likely this is going to happen. If we were concerned here, we could a) check the return code, and b) only then start writing stderr/stdout to the os.StdXYZ buffers. Leaving it up to you to decide what to do.

In any case, a short comment about this would be :dart:

**Comment by mustard-mh** [comment]
> @mustard-mh I can't judge how likely this is going to happen. If we were concerned here, we could a) check the return code, and b) only then start writing stderr/stdout to the os.StdXYZ buffers. Leaving it up to you to decide what to do.

We can't reply on `exitCode` because it's always 0 in VS Code Browser's case

**Comment by geropl** [comment]
> We can't rely on exitCode because it's always 0 in VS Code Browser's case

Would "len(stderr) == 0" work?

**Comment by mustard-mh** [comment]
> Would "len(stderr) == 0" work?

@geropl  We could update code to pipe `stderr` only (then with or without check length should be the same?)

**Comment by geropl** [comment]
> We could update code to pipe stderr only (then with or without check length should be the same?)

Sounds good to me. Happy to test again if you want! :+1:

**Comment by mustard-mh** [comment]
Code updated https://github.com/gitpod-io/gitpod/pull/20166/commits/f209a5bff968234ecb6009a2c70acc8d95472ff8, changes don't need to test

/unhold

**Comment by mustard-mh** [comment]
In workspace test results
image

**Pull request merged**
