### PR TITLE
[usage] Return extra fields for ListBilledUsage

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

API uses extra fields from the DB.

## Related Issue(s)

* Depends on https://github.com/gitpod-io/gitpod/pull/11444

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@easyCZ: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by easyCZ** [comment]
/hold
for dependency on parent PR

**Comment by easyCZ** [comment]
Fields are not yet set in the DB, but will be in subsequent PR

**Review by andrew-farries — APPROVED** [review]
These fields are still unpopulated:

https://github.com/gitpod-io/gitpod/blob/98bb647e615df8458ea43432b02488878654b98b/components/usage/pkg/controller/reconciler.go#L247-L254

**Pull request merged**
