### PR TITLE
[WIP] Add helm hook for removing node labels

### LINKED ISSUE #2227: node-daemon failing to stay up
I have most of the deployments for gitpod running on a k3s cluster being managed by Rancher 2.4. With the exception of the `node-daemon`  deployment, where I get errors like below on all the nodes, after which they terminate: 

``` 
node/kube-master-9273 not patched
Theia (version v0.4.0) became available BUT we've failed to mark the node (attempt 1/10)
node/kube-master-9273 not patched
Theia (version v0.4.0) became available BUT we've failed to mark the node (attempt 2/10)
node/kube-master-9273 not patched
Theia (version v0.4.0) became available BUT we've failed to mark the node (attempt 3/10)
node/kube-master-9273 not patched
Theia (version v0.4.0) became available BUT we've failed to mark the node (attempt 4/10)
node/kube-master-9273 not patched
Theia (version v0.4.0) became available BUT we've failed to mark the node (attempt 5/10)
node/kube-master-9273 patched
Theia (version v0.4.0) became available - we've marked the node
node/kube-master-9273 not patched
ws-sync became available - we've marked the node
```

Is anyone else seeing this?

### PR DESCRIPTION
**Pull request by supra08**
This PR attempts to tackle the issue with node-daemon failing to launch while reinstalling Gitpod. As mentioned already here in the comment: https://github.com/gitpod-io/gitpod/issues/2227#issuecomment-707130419, the problem is because the labels persist after uninstalling Gitpod. Hence manual removal was required.

Here I am creating a Kubernetes job that would run a script to remove the labels. The job is attached to a Helm hook set to `post-delete`, which would trigger it as soon as a node-daemon release is deleted.

The PR is currently in WIP because I am not sure about the correct approach and is open for discussions.

Fixes #2227

### CODE REVIEW

**Comment by csweichel** [comment]
We should check if the label is already present, and if so not fail in node-daemon.

**Comment by supra08** [comment]
Well I guess the check to see if the label is already present here: https://github.com/gitpod-io/gitpod/blob/master/components/node-daemon/node-daemon.sh#L9
But even though it fails and as suggested by https://github.com/gitpod-io/gitpod/issues/2227#issuecomment-707130419 needs to be manually deleted.
So is this correct or am I missing something?

**Pull request closed without merging**
