### PR TITLE
[dashboard] Fix display of billing period boundaries by using only UTC times - using dayjs

### PR DESCRIPTION
**Pull request by easyCZ**
## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by jankeromnes** [comment]
Many thanks for this @easyCZ!

Will take a look at how this behaves with local time zones and daylight savings. 👀

Also the preview died, let's make a new one:

/werft run

**Review by jankeromnes — APPROVED** [review]
Super nice! I tested whether this would get affected by local time zones or daylight savings, and this works like a charm. ✨ 

Many thanks @easyCZ for going the extra mile with this standardization around `dayjs`. 💯

**Comment by jankeromnes** [comment]
@easyCZ should we merge this first and then https://github.com/gitpod-io/gitpod/pull/14088 ?

**Comment by easyCZ** [comment]
Yeah we can merge into your branch.

**Comment by easyCZ** [comment]
Just merged it into https://github.com/gitpod-io/gitpod/pull/14088

**Pull request merged**
