### PR TITLE
Revert "DO NOT MERGE THIS"

### PR DESCRIPTION
**Pull request by AlexTugarev**
This PR reverts an unwanted change from https://github.com/gitpod-io/gitpod/pull/4876

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4957#" title="Author self-approved">AlexTugarev</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [AlexTugarev]
- ~~[components/licensor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/licensor/OWNERS)~~ [AlexTugarev]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by jankeromnes — APPROVED** [review]
Thanks for the quick fix!

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: a69d3d1f99659a00266fefde1b0c852eeaa384ac</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4957#" title="Author self-approved">AlexTugarev</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4957#pullrequestreview-714922793" title="Approved">jankeromnes</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [AlexTugarev,jankeromnes]
- ~~[components/licensor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/licensor/OWNERS)~~ [AlexTugarev,jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jankeromnes** [comment]
```
  1) AccountServiceSpec
       testRemainingHoursUnlimited:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/tmp/build/components-ee-payment-endpoint--dbtest.9bdaf3507987f4b895fc7e43cefa425973a931c8/src/accounting/account-service.spec.db.ts)
```

Random test timeout / needs an increased timeout.

/werft run

**Pull request merged**
