### PR TITLE
[projects] fix for empty projects page

### PR DESCRIPTION
**Pull request by AlexTugarev**
## Description
This PR fixes rendering of the Project page.

## Related Issue(s)

Fix-up for issues from #5640

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **alextugarev** after the PR has been reviewed.

Associated issue: *#5640*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by jankeromnes — APPROVED** [review]
Oops! Code looks good, and works as intended. 🎉

| Spinner | Branches |
| --- | --- |
| Screenshot 2021-10-01 at 09 15 29 | Screenshot 2021-10-01 at 09 15 38 |

I've also re-tested the "unauthorized" flow, still works like a charm. ✨ 

/approve no-issue

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: a16875c918a0d103456303e26f3b2370a5c1d0d6</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5973#pullrequestreview-768638303" title="Approved">jankeromnes</a>*

Associated issue: *#5640*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
