### PR TITLE
[dashboard] UI experiments

### PR DESCRIPTION
**Pull request by geropl**
## Description
Since we have segment for tracking we gained the ability to make judgements around dashboard decisions based on data. But since our turnarounds are so slow we very seldomly make use of our "data-driven" superpower :superhero: .

This is an attempt to improve on this: It introduces dashboard-local `Experiments`. Every user on login gets assigned a random mix of experiments, which may influence the UI behavior (rendering, routing, etc.), based on their respective configured likelihood. The set is stored in `localStorage` and reported to segment with every interaction.

As a result, we can _measure_ differences in behavior by comparing the experiment group with the rest - "control group" (*) - and make judgement calls on how to improve based on _data_ and not opinions.

Further thoughts:
 - we could easily extend this into `server` by persisting`uiExperiments` in `User.featureFlags`, for instance. This has the benefit that our analytic calls on the backend are able to report `uiExperiments` as well, to offer a complete picture. I went with "dashboard-only" for now to stay simple.

(*) Note that the results are only statistically sound with this approach when we're running a) 1 experiment at a time, or b), they are absolutely independent. Still, I hope are all aware and can use this to gain some valuable insights. :slightly_smiling_face: 

## Related Issue(s)

Fixes #

## How to test
 - go to https://gpl-ui-experiments.staging.gitpod-dev.com/projects
 - see that you have an empty array of experiments set in your local storage:
image

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
/hold

I wanted to have a discussion about this before merging.

**Comment by JanKoehnlein** [comment]
/lgtm

Feel free to unhold

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 1d47de0fc7d5b009f1570273efabb94e9dc93688</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7081#issuecomment-986966381" title="LGTM">JanKoehnlein</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [JanKoehnlein]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
Thx @JanKoehnlein for the review. Waiting for @jakobhero before merging as we already talked about this.

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by geropl** [comment]
/unhold

to move forward. Still looking forward for your feedback @jakobhero , and happy to fix and adjust in a follow-up PR! :pray:

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: db801324e644e4f307b8d3407329aa79dca88faf</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7081#issuecomment-986966381" title="LGTM">JanKoehnlein</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7081#issuecomment-987785169" title="LGTM">laushinka</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [JanKoehnlein,laushinka]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7081#issuecomment-986966381" title="LGTM">JanKoehnlein</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7081#issuecomment-987786055" title="Approved">laushinka</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/7081#issuecomment-987786055" title="Approved">laushinka</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [JanKoehnlein,laushinka]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jakobhero** [comment]
> to move forward. Still looking forward for your feedback @jakobhero , and happy to fix and adjust in a follow-up PR! 🙏

i had a chance to test Experiments with a couple of Segment calls and they look good to me! I appreciate the nested structure as it's going to avoid bloating the structure of event tables once we have many experiments running simultaneously (Segment stringifies nested props before sending them to the data warehouse), but it might cause problems for Mixpanel as it cannot show more than one layer of properties (but it should still be able to store this data). I'm happy to go with this for now and try how difficult it will be to handle this downstream. Thanks for this effort, it's going to be a great addition @geropl !

**Pull request merged**
