### PR TITLE
[metrics] Add metrics for unary and streaming gRPC server

### PR DESCRIPTION
**Pull request by csweichel**
This PR adds metrics for all gRPC servers using https://github.com/grpc-ecosystem/go-grpc-prometheus.

Fixes https://github.com/gitpod-io/gitpod/issues/3090

### How to test
1. Start a workspace to produce some traffic in the system
2. Check the metrics of ws-manager, ws-daemon and image-builder. You should see `grpc_server_started_total`, `grpc_server_sent_total`, `grpc_server_msg_received_total` and `grpc_server_handling_seconds_` metrics.

### CODE REVIEW

**Review by meysholdt — APPROVED** [review]
Glad to see this such a small change and thank you for addressing this so quickly. 

The changes LGTM. Looking forward to trying this on staging.

Since [supervisor also starts a gRPC server](https://github.com/gitpod-io/gitpod/blob/a4956795dcf9d86c08d9dade6bd10a80d479ae0e/components/supervisor/pkg/supervisor/supervisor.go#L583) and we should monitor everything that influences the user experience, would it make sense to include it there, too? if not, I can create a followup-issue.

**Comment by csweichel** [comment]
> Since [supervisor also starts a gRPC server](https://github.com/gitpod-io/gitpod/blob/a4956795dcf9d86c08d9dade6bd10a80d479ae0e/components/supervisor/pkg/supervisor/supervisor.go#L583) and we should monitor everything that influences the user experience, would it make sense to include it there, too? if not, I can create a followup-issue.

We don't collect any metrics from supervisor (yet?!?). It's somewhat tricky because it runs in the workspace itself. We'd probably want to find a way to collect those metrics without hogging ports in the workspace itself. Not sure that's worth the trouble at the moment.

In general though, getting telemetry out of the workspace will become a bigger issue in the future (think traces and metrics).

**Comment by ArthurSens** [comment]
Whaaaat? Do only these changes solve that whole issue?
I was expecting it would remain open for several weeks 

I wanna see it with my own eyes :stuck_out_tongue: 
/werft run

**Review by ArthurSens — APPROVED** [review]
Looking pretty! LGTM :rocket: 

image

**Pull request merged**
