### PR TITLE
Add support for github.dev

### LINKED ISSUE #6258: Support for github.dev: https://gitpod.io/#https://github.dev/org/repository
If someone has a repository open in GitHub.dev then they should be able to open it in Gitpod by appending https://gitpod.io# onto it.

### PR DESCRIPTION
**Pull request by iQQBot**
## Description

Add support for github.dev

## Related Issue(s)

Fixes #6258

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by ghuntley — DISMISSED** [review]
👋🧡 for picking this up.

I don’t think this is the right place to make the change:
- The GitHub Context parser is at https://github.com/gitpod-io/gitpod/blob/main/components/server/src/github/github-context-parser.ts
- I’m not sure where “github.com” routes to above but I guess we will soon. Walk up the container registration.

**Comment by ghuntley** [comment]
👍 have asked for a consult to identify the correct place. Stay tuned.

**Comment by AlexTugarev** [comment]
@iQQBot, the line number from my last comment was outdated :-( 

This is what I meant: look at https://github.com/gitpod-io/gitpod/blob/ec744db3352c6c258b80ff994089b25ab2351976/components/dashboard/src/App.tsx#L359

there we could do the `github.dev` test and immediately redirect to a modified create url.

**Comment by AlexTugarev** [comment]
@iQQBot, yes, that sounds good. Would you change accordingly? Looking forward to test and have this merged.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **alextugarev** after the PR has been reviewed.

Associated issue: *#6258*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: f21f21eb209648886fc0d90c1857883695a0dbf0</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6260#issuecomment-959108597" title="LGTM">JanKoehnlein</a>*

Associated issue: *#6258*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [JanKoehnlein]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by JanKoehnlein** [comment]
Thanks again, @iQQBot !

**Pull request merged**
