### PR TITLE
upgrade to code 1.53.2

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix https://github.com/gitpod-io/gitpod/issues/3069: upgrade to Code 1.53.2

Noteworthy for Gitpod integration:
- terminals are get proper initial layout now and layout is preserved
- support permessage-deflate extension for web sockets

Code migration changes: https://github.com/gitpod-io/vscode/commit/7cb02eeb2279547b8e5ff154f463387fb77748ee

#### How to test

- Enable feature preview and Code
- Language Support should be available, try to edit typescript files
- it should be possible to install/uninstall extensions
- Code CLI should work
- Terminals should be properly opened initially and preserved between page reloads
- User data should be synched between workspaces

### CODE REVIEW

**Review by JanKoehnlein — APPROVED** [review]
LGTM

**Comment by laike9m** [comment]
Has this change been deployed? I seem to remember there's a way to check the current node.js version used by Gitpod, but I can't find it on the UI anymore.

**Comment by akosyakov** [comment]
It will be deployed by the end of next week.

**Pull request merged**
