### PR TITLE
Gitpod CLI: Improve Segment logging

### PR DESCRIPTION
**Pull request by filiptronicek**
## Description

Only enables Segment logging when logging verbose output. It means that Segment errors do not get outputted to standard error, because it is not critical to the CLI's functionality.

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖 Generated by Copilot at 91af8d6</samp>

Add custom logger for telemetry package and expose log level option to user. This improves the visibility and control of the telemetry output in the local-app component.

</details>

## Related Issue(s)

Fixes EXP-912

## How to test

Personally, I tested by changing the client configuration of Segment to some bogus address.

In the first command, the error is not shown. In the second one, we use verbose output and therefore it is. 
image

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - ft-improvebff3ba7aca</li>
	<li><b>🔗 URL</b> - <a href="https://ft-improvebff3ba7aca.preview.gitpod-dev.com/workspaces" target="_blank">ft-improvebff3ba7aca.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - ft-improve-telemetry-logging-gha.20247</li>
	<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-ft-improvebff3ba7aca%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws-manager-mk2%22%0A;duration=P1D?project=gitpod-core-dev" target="_blank">GCP Logs Explorer</a></li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by mustard-mh** [comment]
If I'm a user, I don't care any respond / process for metrics / telemetry / error report ()

Maybe add another level `tracing` ?

**Comment by filiptronicek** [comment]
@mustard-mh fair enough, it maybe should be a different level altogether. Looping in @csweichel, any advice for telemetry logs?

**Review by geropl — APPROVED** [review]
Tested and works, :heavy_check_mark: to unblock.

I like @mustard-mh suggestion to push it down to trace, but silencing it entirely is also fine I think. Leaving it to @filiptronicek to force the discussion here, to move it to a follow-up PR. :lotus_position:

**Comment by filiptronicek** [comment]
While we are in preview, I will leave segment errors in verbose output. It would be great to add another logging level, but that adds some complexity, both technical and user-facing (we have `--verbose`, how would you turn on tracing?).

I also fixed auto-updating by properly proxying the manifest file.

**Pull request merged**
