### PR TITLE
[server,dashboard] improve org default image input placeholder

### PR DESCRIPTION
**Pull request by mustard-mh**
## Description

Add global default workspace image (from value.gitpod.yml) a placeholder of org-level workspace image

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖 Generated by Copilot at aa60b69</samp>

This pull request adds a new API method `getDefaultWorkspaceImage` to the Gitpod server and a corresponding hook `useDefaultWorkspaceImageQuery` to the dashboard, and uses them to display the default workspace image in the team settings UI. It also fixes some type inconsistencies and simplifies the logic for the `defaultWorkspaceImage` setting in the server and the database.

</details>

## Related Issue(s)

Fixes EXP-634
Relates EXP-633

## How to test

- Open preview env, go to your org settings
- Org default workspace image should be empty with a placeholder
- Set it to something else, like `gitpod/workspace-go`, refresh (not need but just to confirm) it should use `gitpod/workspace-go`
- Set it to empty string, refresh, it should go with empty + placeholder

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - hw-org-default</li>
	<li><b>🔗 URL</b> - <a href="https://hw-org-default.preview.gitpod-dev.com/workspaces" target="_blank">hw-org-default.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - hw-org-default-gha.17216</li>
	<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-hw-org-default%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws-manager-mk2%22%0A;duration=P1D?project=gitpod-core-dev" target="_blank">GCP Logs Explorer</a></li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by filiptronicek** [comment]
@mustard-mh IMO we can just replace any image which begins with docker.io/. I would say it's the format most users are used to so no need to specify the host in that case.

**Comment by gtsiolis** [comment]
Looking at this now! 👀

**Review by gtsiolis — APPROVED** [review]
UX LGTM, thanks @mustard-mh. 🌮 

Added one [some designs](https://gitpod.slack.com/archives/C05H5UQBW6Q/p1695194786941829?thread_ts=1695145376.414289&cid=C05H5UQBW6Q) (internal) for improving this in a later iteration. Feedback is welcome!

**Comment by mustard-mh** [comment]
> UX LGTM, thanks @mustard-mh. 🌮
> 
> Added one [some designs](https://gitpod.slack.com/archives/C05H5UQBW6Q/p1695194786941829?thread_ts=1695145376.414289&cid=C05H5UQBW6Q) (internal) for improving this in a later iteration. Feedback is welcome!

🚀 , for further improvement, I'd like to address it on https://linear.app/gitpod/issue/EXP-630. Thank you @gtsiolis

**Pull request merged**
