### PR TITLE
[ws-manager] Remove temporal workaround for kubelet issue

### PR DESCRIPTION
**Pull request by aledbf**
## Description

Due to Kubernetes issue https://github.com/kubernetes/kubernetes/pull/108366 we had to add a workaround to bypass the issue. Now that upstream versions are available (since April 13th) we can remove it.
Affected Kubernetes version with the issue released a fix in:
- [v1.22.9](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#v1229)
- [v1.23.6](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#v1236)

We need to remove the workaround due to additional conditions that can affect the scheduling, like scale-up events.
Creating and deleting pods due to timeouts only add load to the API server.

Edit: example of side effect https://cloudlogging.app.goo.gl/SG2Qx1e21EykbRzNA

## Release Notes

```release-note
NONE
```

## Werft options:

- [X] /werft with-preview

### CODE REVIEW

**Review by sagor999 — APPROVED** [review]

**Comment by jenting** [comment]
Would removing this workaround affect self-hosted if they are not using the Kubernetes version >= v1.22.9 _or_ v1.23.6?

**Comment by aledbf** [comment]
> Would removing this workaround affect self-hosted if they are not using the Kubernetes version >= v1.22.9 _or_ v1.23.6?

Yes? That said, if you are running the affected versions, you will have the same issues as why we added the workaround.
This is not related to Gitpod, creating pods at the same volume that SaaS reproduces the error.

**Comment by sagor999** [comment]
@gitpod-io/engineering-self-hosted FYI ^

**Comment by lucasvaltl** [comment]
I am trying to wrap my head around the potential impact on self-hosted customers here. What is the likelihood that self-hosted customers will run into this? Is there a way to enable the workaround if customers are on the specific versions of K8s that are affected? 

From what I gathered: If you are spinning up nodes at a similar pace to what we do on SaaS AND you are on a K8s version <= v1.22.9 or v1.23.6  you will likely be affected by the bug now that we removed the workaround. I can't tell though how many customers meet both of these conditions. I do know that the default GKE version is `1.22.8-gke.202`and the default EKS version [_seems_ to be `1.22.10`](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)

**Pull request merged**
