### PR TITLE
Add environment variable name/value length validation in UI

### LINKED ISSUE #8045: User environment variable name/value length validation missing
### Bug description

Variable name can not be longer than 255 chars, but the error is never displayed to the user (if console output is not counted).

Similarly for the value (but different limit, 64k).

### Steps to reproduce

Try creating a [variable](https://gitpod.io/variables) with name longer than 255 chars.

After clicking "Add Variable", the dialog will close, but variable will not be added. No indication of an error will be visible in the UI.

Instead, an error message is printed in the dev console:
image

### Workspace affected

_No response_

### Expected behavior

Variable name length validation is expected on "Add Variable" action, together with charset check, in the [`validate`](https://github.com/gitpod-io/gitpod/blob/a33a4a08a8a7cb8407d6239f7b88f808b046946b/components/dashboard/src/settings/EnvironmentVariables.tsx#L152) function.

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by randomir**
Also, decrease maxlen for value from ~64k*3/4 to a nice round 32k.

## Description
On variable save, we now validate:
- name len is shorter than 256
- value len is shorter than 32k+1

and inform the user of the error, instead of silently failing.

The 32k limit might be worth some discussion. The db limit is mysql's `TEXT` max of 64k, but that's after encryption and base64 encoding, resulting with a real current limit of about ~48k. I chose 32k because it looks nicer :laughing:.

## Related Issue(s)

Fixes #8045

## How to test
1. Try to create a variable with either name longer than 255 chars or value longer than 32768 chars.
2. Create a new variable, then try updating the name and value with strings longer than the limits above.

## Release Notes

```release-note
Add user environment variable name length and value length validation in settings UI modal.
```

## Documentation

No update.

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **geropl** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @geropl` in a comment when ready.

Associated issue: *#8045*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by AmirHosseinKarimi — APPROVED** [review]

**Comment by roboquat** [comment]
@AmirHosseinKarimi: changing LGTM is restricted to collaborators

<details>

In response to [this](https://github.com/gitpod-io/gitpod/pull/8046#pullrequestreview-874070842):

>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/8046#pullrequestreview-874070842" title="Approved">AmirHosseinKarimi</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **geropl** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @geropl` in a comment when ready.

Associated issue: *#8045*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by AlexTugarev** [comment]
Unfortunately, the deployment of a preview environment is failing because the name of the branch is too long. (k8s namespace is derived from the branch name.)

On the other hand, it's sufficient to check for a build in a workspace. (⏳ )

**Comment by AlexTugarev** [comment]
@meysholdt, we need you help with a CLA, please! 🙏🏻

**Comment by meysholdt** [comment]
hi @randomir! Great to see a PR from you :-D I've reached out to you via email about the CLA.

**Comment by jankeromnes** [comment]
Well, thank you for nothing Werft 😅

CI failed with:

```
Error Error: there is no subdomain + 'add-env-var-length-validation-issue-8045-fork.staging.gitpod-dev.com' shorter or equal to 63 characters, max. allowed length for CN. No HTTPS certs for you! Consider using a short branch name...
```

**Comment by randomir** [comment]
Thanks @jankeromnes.

I've tried renaming the branch on GH, but that just closed the PR. I've opened a new PR from a shorter branch name in #8248.

**Comment by jankeromnes** [comment]
Aha, that's perfect, many thanks @randomir! 🙏

Then I suggest we move over to the new Pull Request. 🚚

**Pull request closed without merging**
