### PR TITLE
chore: capitalize proper noun Git in dashboard components

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Description

- Capitalize proper noun Git in dashboard components

## Related Issue(s)

Driveby PR, not closing any issue with this.
Retry of PR #5990, let's hope this branch name is short enough. 😄 

## How to test

1. Review changes in the PR for correct spelling/capitalization.
1. Find way to preview dashboard components on a dev server.
1. Find way to run the tests, to confirm I'm not breaking any Jest snapshots or other test files.

This is my first contribution to the Gitpod program itself.
I did not find any developer documentation on how to run a dev server which shows me the components, so I can verify my changes myself.

Also please review/edit my Release Notes below, I hope this is the correct format.

## Release Notes

```release-note
capitalize proper noun Git in dashboard components
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **geropl** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @geropl` in a comment when ready.

Associated issue: *#5990*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by jankeromnes — APPROVED** [review]
Many thanks again! 💯 Same as https://github.com/gitpod-io/gitpod/pull/5990#pullrequestreview-770675816

/lgtm
/approve no-issue
/hold
/werft run

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: cf3327f47e75c203f82e881666488002e4e21c60</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6039#pullrequestreview-771139664" title="Approved">jankeromnes</a>*

Associated issue: *#5990*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jankeromnes** [comment]
@meysholdt Please help unblock this really cool Pull Request by stating whether signing a CLA is required or not. 🙂 🙏

**Comment by JanKoehnlein** [comment]
@meysholdt What's the status of the CLA? (See https://github.com/gitpod-io/gitpod/pull/6039#issuecomment-949352500)

**Comment by HonkingGoose** [comment]
@meysholdt Check your inbox. 😉

**Comment by meysholdt** [comment]
Hi @HonkingGoose, thank you for signing our CLA :)

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 32a18fab30206fe2fd4db726b3a1c1b6ad0620bc</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6039#pullrequestreview-771139664" title="Approved">jankeromnes</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6039#issuecomment-957388166" title="LGTM">JanKoehnlein</a>*

Associated issue: *#5990*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [JanKoehnlein,jankeromnes]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
