### PR TITLE
[wip] [werft] Explicitly pass proxy config to docker daemon

### PR DESCRIPTION
**Pull request by geropl**
Fixes https://github.com/gitpod-com/gitpod-dev/issues/28.

Instead of passing the `HTTP_PROXY` env vars to the docker _daemon_ pass it via client config into the container. This way the daemon does not contact the proxy for downloading docker images/blobs etc. (details explained [here](https://elegantinfrastructure.com/docker/ultimate-guide-to-docker-http-proxy-configuration/)).

- [x] /werft no-cache

### CODE REVIEW

**Comment by csweichel** [comment]
I wasn't entirely sure if all consumers of `HTTP_PROXY` and `HTTPS_PROXY` can handle the URL without scheme. To find out, I've triggered a werft build without cache.

**Comment by geropl** [comment]
> I wasn't entirely sure if all consumers of HTTP_PROXY and HTTPS_PROXY can handle the URL without scheme. To find out, I've triggered a werft build without cache.

The reason I removed the `http(s)://` was that alpine's `apk` does not like the prefix... and now alpine's `curl` does not like it without it. Oh well... :upside_down_face:

**Comment by geropl** [comment]
This is about re-enabling the HTTP proxy for all components, but currently we do not seem to much trouble with it. Closing for now.

**Pull request closed without merging**
