### PR TITLE
[KOTS]: extract images from the Installer and put in the additionalImages array

### LINKED ISSUE #9042: extract images from the Installer and put in the `additionalImages` array
As the Installer manages the all the container images internally, these are not exposed to KOTS for airgapping purposes. To that end, we need to export the images from the Installer and put them in the `additionalImages` array in the `kots-app.yaml` file.

There's already a `mirror list` command which we should be able to use.

See [KOTS docs](https://docs.replicated.com/reference/custom-resource-application#additionalimages)

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Description

For airgapped mode to work, we need to specify the images used if they are not directly specified in the manifests - the Installer image will be the only one included automatically. As we're using the Installer to manage the container images, we must add these to the `additionalImages` spec.

As we already have the `mirror list` command, this creates a `mirror kots` command to add the `additionalImages` into the `kots-app.yaml` file. This uses the same underlying command as the `mirror list` command, but reworks it so the `original` image is added in - KOTS will then process these images and include them in the internal registry when an airgapped installation is requested.

See [KOTS docs](https://docs.replicated.com/reference/custom-resource-application#additionalimages)

## Related Issue(s)

Fixes #9042

## How to test

Manually trigger an airgap build for [this branch](https://vendor.replicated.com/apps/gitpod/channels/278yCdgOMZvEejkxNTAcnSfQ4UV) and ensure that it complete successfully.

Uploaded `kots-app.yaml` - see [release](https://vendor.replicated.com/apps/gitpod/releases/93):

image

Success message - see [build](https://vendor.replicated.com/apps/gitpod/channels/278yCdgOMZvEejkxNTAcnSfQ4UV):

image

## Release Notes

```release-note
[KOTS]: extract images from the Installer and put in the additionalImages array
```

### CODE REVIEW

**Comment by roboquat** [comment]
@MrSimonEmms: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by Pothulapati — APPROVED** [review]
LGTM, and works as expected!

Unrealted question, For most images we are restricted on a specific commit, except for some IDE images for which we also have `latest`. wondering, why? 🤔

**Comment by MrSimonEmms** [comment]
That's a question for @akosyakov and the @gitpod-io/engineering-ide team I think, but my understanding is so that the IDEs get updated whenever the owners push a change. As it's a third-party product, we're not directly involved in the release cycle so don't want to couple it to our releases.

**Comment by akosyakov** [comment]
> Unrealted question, For most images we are restricted on a specific commit, except for some IDE images for which we also have latest. wondering, why?

Stable versions are manually released, latest versions are released on nightly basis.

**Pull request merged**
