### PR TITLE
Use prettier for TypeScript files in .werft

### PR DESCRIPTION
**Pull request by mads-hartmann**
## Description

This PR introduces automatic formatting of all TypeScript files in the `.werft` folder. 

1. It configures [prettier](https://prettier.io/) to perform automatic formatting on all TypeScript files in the `.werft` folder as part of our pre-commit hooks.
2. It adds `esbenp.prettier-vscode` to the list of extensions
3. It configures VSCode to fun "format on save" on TypeScript files and sets prettier as the formatter

This PR also includes performing the automatic formatting, hence the rather large diff. For the actual code review I suggest you focus on [43ca5ee](https://github.com/gitpod-io/gitpod/pull/8245/commits/43ca5ee418fbdf15433134dce9fbbc579d7d1bcb).

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/issues/8066

## How to test

Verify that it performs formatting when you run

```
pre-commit run --all-files --show-diff-on-failure
```

Edit a `ts` file in `server` and verify it doesn't use prettier to format the file when saving (that is, the prettier extension that is now installed as part of the workspace correctly ignores the entire components folder)

## Release Notes

```release-note
NONE
```

## Documentation

N/A

### CODE REVIEW

**Comment by mads-hartmann** [comment]
I have added the hold label. I'm checking with the other teams that write TS to ensure this doesn't break anything for them.

**Comment by ArthurSens** [comment]
Nice job! I'd approve right away if the build didn't fail... looks like it is some unrelated flakiness though, I'll rerun to see if it passes

/werft run

**Comment by ArthurSens** [comment]
What is the status of this one? 

Are we still waiting for IDE/WebApp review? If that's the case I guess we could add them as reviewers? 🙂

**Comment by mads-hartmann** [comment]
@ArthurSens I will try to use the default formatter that VSCode ships with instead of prettier. I can't figure out how to downgrade a PR to DRAFT so instead I'll just close this and reopen a new one once I have experimented ☺️

**Comment by ArthurSens** [comment]
Right top corner :) 

image

**Comment by mads-hartmann** [comment]
@ArthurSens Thanks! Reopened and converted it to draft :D

**Comment by mads-hartmann** [comment]
Closing this, the webapp team is working on adding automatic formatting so I'd rather wait and piggy-back on their implementation. See [internal Slack thread](https://gitpod.slack.com/archives/C02EN94AEPL/p1646735573344059) for reference

**Pull request closed without merging**
