### PR TITLE
[ws-proxy] don't hit blobserve with web sockets

### PR DESCRIPTION
**Pull request by akosyakov**
## Description

instead fallback directly to workspace without additional remote request

Discovered as part of instrumenting http metrics in ws-proxy: https://github.com/gitpod-io/gitpod/pull/17294

There are more 404 errors but they are unfortunately how VS Code bundle source maps for 3rd party extensions. Maybe we can server source maps always from sources. It is out of scope of this PR though.

## Related Issue(s)

Fixes #

## How to test

- Start a workspace
- Check that VS Code is still working, file explorer, extensions

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - ak-ws-prox9086f3011a</li>
	<li><b>🔗 URL</b> - <a href="https://ak-ws-prox9086f3011a.preview.gitpod-dev.com/workspaces" target="_blank">ak-ws-prox9086f3011a.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
</ul>

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [x] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

/hold

### CODE REVIEW

**Comment by akosyakov** [comment]
There are more 404 coming from bogus location of source maps... investigating.

**Comment by akosyakov** [comment]
@iQQBot @kylos101 it is a small one to prevent unnecessary request to blobserve, since it cannot handle web sockets

**Comment by kylos101** [comment]
@akosyakov could I ask for your help with a couple things?

1. Which Linear issue or project does this relate to? 
2. What is the impact is to users w/o this change? I ask to see if we should plan an ad-hoc deploy of `ws-proxy`, or, if we it can wait till next week. I assume it can wait till next week.

**Review by kylos101 — APPROVED** [review]
:shipit: 

Note: added non-blocking questions

**Comment by akosyakov** [comment]
> What is the impact is to users w/o this change? I ask to see if we should plan an ad-hoc deploy of ws-proxy, or, if we it can wait till next week. I assume it can wait till next week.

It is rather 💄 to remove unnecessary calls for web sockets, which we discovered as part of https://github.com/gitpod-io/gitpod/pull/17294 It will insignificantly increase web socket connectivity, but mainly to clean up blobserve error codes.

**Comment by kylos101** [comment]
@akosyakov this is deployed in gen99, we're shifting traffic now

**Pull request merged**
