### PR TITLE
Enable protected secrets by default

### PR DESCRIPTION
**Pull request by Furisto**
## Description
Enable protected secrets by default. This is the part for the workspace side. Once this change is deployed we can also change it on web app side.

## Related Issue(s)
Related to https://github.com/gitpod-io/gitpod/issues/13634

## How to test
- Open workspace in preview environment and check that protected secrets are still used

## Release Notes

```release-note
None
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-large-vm
- [x] /werft with-integration-tests=workspace
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by sagor999** [comment]
/hold
would like to run this through integration tests just to be safe

**Review by sagor999 — APPROVED** [review]
changes LGTM, but placed hold to run through integration tests

**Comment by sagor999** [comment]
@Furisto it seems like image builder test repeatedly fails. Could be related to your changes? :thinking:

**Comment by Furisto** [comment]
@sagor999 Good catch! The image builder did not set the feature flag, so image builds were still using the old method (but imagebuilder set a secret itself, so we are clear here). With the new default behavior the secret set by imagebuilder was overwritten by protected secrets. Fixed with https://github.com/gitpod-io/gitpod/pull/14083/commits/54c2aa29297ae4d95dea06e1a387f7cb4e2fbfa6

**Review by jenting — APPROVED** [review]
LGTM

**Pull request merged**
