### PR TITLE
[server] Remove legacy configuration

### PR DESCRIPTION
**Pull request by geropl**
Fixes https://github.com/gitpod-io/gitpod/issues/4650.

### Validate changes
1. see that `server` starts
2. search for `process.env` in `components/**/*.ts` and verify that all places left are independent of the changes made here
2. compare old and new config
- copy `config` from logs as `new.json`
- create another branch from `main`, wait until the preview env is deployed, and copy the field "new config" from the logs and save as `old.json`
- clean both files with 'replace \\n -> \n' and 'replace \\" -> "' followed by `cat new.json | jq -S > new` resp.
- compare `new` and `old`
  - note that all changes are because of either:
  - different [output format](https://github.com/gitpod-io/gitpod/pull/5496/files#diff-b53cd6a3e7c6f723a548f8c5560dc26b34591c201f4605cdf7c6ca1ced8e651bL213)
  - additions because we now print logs [unfiltered](https://github.com/gitpod-io/gitpod/pull/5496/files#diff-b53cd6a3e7c6f723a548f8c5560dc26b34591c201f4605cdf7c6ca1ced8e651bL227)

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** after the PR has been reviewed.

Associated issue: *#4650*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
@laushinka @jankeromnes It would be awesome if one of you found time to review this until tomorrow morning. This is quite likely to create conflicts (again).

**Review by svenefftinge — APPROVED** [review]
LGTM

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 1d69e6ebf55c254addc854595781def2edca17a7</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5496#pullrequestreview-747346831" title="Approved">svenefftinge</a>*

Associated issue: *#4650*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [svenefftinge]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [svenefftinge]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
