### PR TITLE
Update the error message when you run out of workspace credits.

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
## Description

Before the error message was very vague when one ran out of workspace hours. With this change it makes the error message clearer for the user.

Changes
```
Not enough credits. Please book more.
```

To
```
Not enough monthly workspace hours. Please upgrade your account to get more hours for your workspaces.
```

### CODE REVIEW

**Comment by roboquat** [comment]
@Harry-Hopkinson: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by andrew-farries** [comment]
Thanks for contributing, @Harry-Hopkinson  🧡 

The changes look good.

You'll also need to sign a Contributor License Agreement (CLA)[[1](https://en.wikipedia.org/wiki/Contributor_License_Agreement)] once before merging your first contribution. Looping in @meysholdt to reach out about the CLA. 🏓

**Review by andrew-farries — APPROVED** [review]

**Comment by andrew-farries** [comment]
Rebasing this against upstream `main` should fix the build error.

**Comment by jankeromnes** [comment]
Hi @Harry-Hopkinson, many thanks for improving this error message! Your proposed new phrasing looks much better to me as well. 🎯

Also, thank you @andrew-farries for reviewing this excellent community contribution, and pushing it through the various hurdles! 🙏

---

Adding just a bit more context here in case you're interested:

When you create a new workspace, the error `NOT_ENOUGH_CREDIT` has special handling that shows a nice "Limit Reached" modal with an "Upgrade" button:

https://github.com/gitpod-io/gitpod/blob/b2d07b8bf0d3364cd8b831e487a79fa7ab1fc638/components/dashboard/src/start/CreateWorkspace.tsx#L182-L186

https://github.com/gitpod-io/gitpod/blob/b2d07b8bf0d3364cd8b831e487a79fa7ab1fc638/components/dashboard/src/start/CreateWorkspace.tsx#L328-L333

Unfortunately, we don't handle it the same way when starting an existing workspace: we simply pass it along to `<StartPage>` which then displays it without much handling:

https://github.com/gitpod-io/gitpod/blob/b2d07b8bf0d3364cd8b831e487a79fa7ab1fc638/components/dashboard/src/start/StartWorkspace.tsx#L648-L650

https://github.com/gitpod-io/gitpod/blob/b2d07b8bf0d3364cd8b831e487a79fa7ab1fc638/components/dashboard/src/start/StartPage.tsx#L124-L130

In the future, I think it could be nice to centralize error handling between `CreateWorkspace.tsx` and `StartWorkspace.tsx`, so that, for example, a `NOT_ENOUGH_CREDIT` error would always result in showing the nice "Limit Reached" modal. 💭 

But that's definitely a topic for a future Pull Request. 😁 Many thanks again! 🏀

**Comment by meysholdt** [comment]
hi @Harry-Hopkinson, to get the CLA signed, can you please let me know your email address by sending an email to moritz@gitpod.io? I will then respond with the CLA which you can sign via DocuSign.

**Comment by Harry-Hopkinson** [comment]
@mesysholdt I have sent an email.

**Comment by meysholdt** [comment]
I have received the signed CLA. Thank you, @Harry-Hopkinson.

**Pull request merged**
