### PR TITLE
Fix ws scheduler CPU resource checks

### PR DESCRIPTION
**Pull request by saisrivathsa**

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4842#" title="Author self-approved">saisrivathsa</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **akosyakov** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @akosyakov` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ee/ws-scheduler/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/ws-scheduler/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
Thx for the PR @saisrivathsa and the changes looks good so far.

Before we merge please:
 - update `DebugStringNodes` [here](https://github.com/saisrivathsa/gitpod/blob/18de35a1841cbe7c7229582f01e6e636af5d55a0/components/ee/ws-scheduler/pkg/scheduler/state.go#L479). This will in turn require to update the unit tests in `state_test.go`.
 - extend the `TestGatherPotentialNodesFor` [here](https://github.com/saisrivathsa/gitpod/blob/2b6a56bc40683e4e7cbafda3f8e12b1a6f27af17/components/ee/ws-scheduler/pkg/scheduler/scheduler_test.go#L30) with one positive and one negative test

**Comment by geropl** [comment]
Closing until somehow does pick it up again.

**Pull request closed without merging**
