### PR TITLE
Remove useless escape in email regex

### PR DESCRIPTION
**Pull request by KevSlashNull**
## Description

This removes a useless escape in the email regexp used to validate a user’s email address. The escaped double quotes character is part of the exclusion group that means that double quotes are forbidden in email addresses.

As [reported by eslint](https://eslint.org/docs/latest/rules/no-useless-escape), escaping a double quote in a regex string that’s in /literal/ notation is superfluous.

## Related Issue(s)

#3841 for the broader effort to reduce warnings

## How to test

(This behavior should be identical on `main` and this branch.)

1. In the navbar, click on your avatar
2. Click on **Settings**
3. In the settings UI, add a double quote character (`"`) to your email address
4. Press Enter
5. See that an error is shown
   image
6. Remove the character added in 3
7. See that the form can be saved
   image

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by geropl — APPROVED** [review]
LGTM

**Comment by mads-hartmann** [comment]
/hold
CI is not passing as the job never ran (see comment above https://github.com/gitpod-io/gitpod/pull/15591#issuecomment-1372797647). Holding to unblock the merge queue

**Comment by sagor999** [comment]
/werft run with-clean-slate-deployment=true

this should fix build failure. @KevSlashNull if not, can you please rebase on top of main as well.

**Comment by gtsiolis** [comment]
Thanks for helping out, @sagor999! Unholding as I rebased this earlier[[1](https://github.com/gitpod-io/gitpod/pull/15591#event-8170015784)] and @geropl already approved the code changes.

/unhold

**Pull request merged**
