### PR TITLE
[installer] Add config validation

### LINKED ISSUE #6102: [installer] Validate configuration
installer should be able to validate the user-provided configuration. Rules to check are:
- valid values in all enum fields
- all required values are present
- configuration is not contradictory (e.g. we can only install full clusters with an internal docker registry)

### PR DESCRIPTION
**Pull request by mrsimonemms**
## Description

Validate the given configuration

## Related Issue(s)

Fixes #6102

## How to test

```go run . validate config --config /path/to/config.yaml```

This also can be done with `go run . render --config /path/to/config.yaml`

## Release Notes

```release-note
Installation config validation
```

### CODE REVIEW

**Comment by MrSimonEmms** [comment]
I've decided to keep validating the database/object store until after I've got these connecting to GCP, which is my next job

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **csweichel** after the PR has been reviewed.

Associated issue: *#6102*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by princerachit** [comment]
I am seeing an error while running the command:
```
gitpod /workspace/gitpod/installer $ go run . -v validate config --config example-config.yaml 
Error: unknown command "config" for "gitpod-installer"
Run 'gitpod-installer --help' for usage.
Error: unknown command "config" for "gitpod-installer"
exit status 1
```

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: c040def9fb4b18ed23989477a4e4e336f4b62d57</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6265#issuecomment-948656100" title="LGTM">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6265#issuecomment-946504528" title="LGTM">princerachit</a>*

Associated issue: *#6102*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)~~ [csweichel,princerachit]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
