### PR TITLE
align dashboard plans page wording on website 

### PR DESCRIPTION
**Pull request by lucasvaltl**
## Description
 After watching a YouTube review of gitpod, I noticed the wording around Timeouts on the dashboard/settings/plans page is inconsistent with the wording on our website/pricing page. It can lead to the reader assuming that on the free plan you workspace automatically times out after 30 mins, not that it times out after 30 mins of inactivity. This was also assumed by the reviewer. Hence I added "inactivity" as a qualifier before "timeout" to clarify this. This is also the wording used on the pricing page.

## How to test
Run gitpod, look at the dashboards/settings/plans page to see that the changes came through

## Release Notes
```release-note
Clarified wording of "timeout" feature on the settings/plans page
```

### CODE REVIEW

**Comment by lucasvaltl** [comment]
Note that I did not test this within the workspace at all. Just made the changes to the files.

**Comment by gtsiolis** [comment]
Running build again in case it helps with the build failure[[1](https://werft.gitpod-dev.com/job/gitpod-build-lucas-dashb-wrd-fix.1)].

/werft run

**Review by gtsiolis — APPROVED** [review]
Thanks for making this change, @lucasvaltl! 🔮 

UX changes look good. ✔️ 

Not sure why the buildis failing here. I've noticed others are also running into this error, see [relevant discussion](https://gitpod.slack.com/archives/C032A46PWR0/p1646837123545349) (internal). Let's see what others think.

**Comment by lucasvaltl** [comment]
Seems like there was a quota issue (see [discussion](https://gitpod.slack.com/archives/C032A46PWR0/p1646837123545349) (internal) - let's try this again:

/werft run

**Review by jankeromnes — APPROVED** [review]
Good catch! Many thanks 🙏

Approving because George already approved and this looks safe ✅

**Comment by gtsiolis** [comment]
Thanks, @jankeromnes @lucasvaltl! 🏀

**Pull request merged**
