### PR TITLE
Set default cols and rows when creating pty

### PR DESCRIPTION
**Pull request by jeanp413**
## Description

Set default cols and rows when creating a pty
Align attributes with node-pty
    
Related https://github.com/gitpod-io/gitpod/issues/8055

## How to test

- Use the test from [here](https://github.com/gitpod-io/gitpod/issues/8055#issuecomment-1339590402) with the sourcegraph binary
- Open some repo with lots of taks to check nothing regressed;

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by felladrin** [comment]
This one will need a rebase.

**Review by felladrin — APPROVED** [review]
I've tested it on VS Code and IntelliJ IDEA terminals and haven't seen any regressions ✅ 

image
image

image
image

**Comment by jenting** [comment]
/hold

No idea why this PR blocks the merge queue.

**Comment by jenting** [comment]
/hold
to release the block merge queue
feel free to unhold once CI pass.

**Pull request merged**
