### PR TITLE
Expire spending limit notifications

### LINKED ISSUE #12094: Spending limit notifications do not appear
#11556 introduced spending limit notifications

I have been unable to trigger these notifications while testing spending limits in a preview environment.

I tried both setting a new limit below current usage, and slightly above and then waiting with workspace running. The total usage is updating as expected in the usage list.

### PR DESCRIPTION
**Pull request by AlexTugarev**
and do not block on empty state.

## Related Issue(s)

Fixes #12094

## How to test
* enable UBB on a team; set a low spending limit (e.g. 1 or 2)
* change attribution to team
* create a project
* start a couple of workspaces
* turn to the dashboard and see the notification is shown on reload (it might take a couple of tries, to get the data fly through different systems)

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview
- [x] /werft with-payment

### CODE REVIEW

**Comment by geropl** [comment]
@AlexTugarev I'm testing, and I'm not sure it works as expected:
 - I set the spending limit to "1"
 - I see 0,5 credits on usage view
 - I see the "spending limit reached" notification
image

Is that just the delay of the usage record? Or something else at play here? :thinking:  (by now my usage is beyond 1 already)

**Comment by AlexTugarev** [comment]
@geropl, this works as expected indeed! We need to align our `Total usage` with what we end-up computing on stripe, i.e. we need to round 🆙

**Review by geropl — APPROVED** [review]
Code LGTM, tested and works! :tada:

**Pull request merged**
