### PR TITLE
workspace integration test: refactor TestBackup

### LINKED ISSUE #12497: [integration tests] add regular workspace PVC integration test from PVC test plans
## Is your feature request related to a problem? Please describe

Manually go thru. the PVC test plans take about half a day, and it's too long for each release to manually test against all the PVC test plans.

## Describe the behaviour you'd like

Trying to add more integration tests from the PVC test plans if possible, and make the manual PVC tests as small as possible.
Therefore, we could minimize the deployer only need to test the manually PVC test plans. 

## Describe alternatives you've considered

None

## Definition of Done (DoD)
- Update existing tests with PVC feature flag
  - [x] TestBackup #12620
  - [x] TestRegularWorkspaceTasks #12620
  - [ ] TestGitHubContexts #12650
  - [ ] TestGitActions #12650
  - [ ] TestGitLFSSupport #12650
- Add new tests
  - [x] PVC test plans regular workspace case 2 Existing workspace and enable PVC (Disable PVC ❌ → Enable PVC ✅) #12620
  - [x] PVC test plans regular workspace case 3 Fresh new workspace and enable PVC, then disable PVC (Enable PVC ✅ → Disable PVC ❌ ) #12620

## Additional context

#7901 

@jenting I briefly looked at the below tests, and removed them from scope for now. Can you review, and let me know your thoughts? They seem unnecessary, but, let me know what you think? :pray: 
- Other regular workspace tests, not necessarily needed for PVC
    - [x] TestWorkspaceInstrumentation (creates a user via server API, starts a workspace from gitpod repo, transfers or uses an agent to the workspace pod, sets up a port forward, and asserts it can connect to the agent via RPC...it is unclear how this relates to PVC)?
    - [x] TestLaunchWorkspaceDirectly (this is exercised in most of the tests starting a workspace already)

### PR DESCRIPTION
**Pull request by jenting**
## Description

workspace integration test: refactor TestBackup.

- Use the last status reports from the ws-manager rather than the volume snapshot client to find the VolumeSnapshot within the Kubernetes cluster.
- Remove the volume snapshot client to prevent we encounter any error that we can't connect to the Kubernetes cluster either because the kube-apiserver is busy _or_ the network is unreliable.

## Related Issue(s)

Fixes #12497

## How to test

```console
cd test

go test  -run ^TestBackup$ github.com/gitpod-io/gitpod/test/tests/components/ws-manager -count=1 -namespace=default -kubeconfig=/home/gitpod/.kube/config -v -timeout=20m
```

## Release Notes

```release-note
None
```

## Documentation

None

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Comment by utam0k** [comment]
@jenting I have never seen an error that relates to the volume snapshot client. May I ask you to give this error?

**Comment by jenting** [comment]
> @jenting I have never seen an error that relates to the volume snapshot client. May I ask you to give this error?

Two points:
- The first one is your comment https://github.com/gitpod-io/gitpod/pull/12620#discussion_r962442634
- The second one is when I was working on adding the PVC test to TestBackup, I did not realize we could get the volume snapshot information after the workspace stopped. Therefore, I used the volume snapshot client to find the corresponding VolumeSnapshot object by label selector. However, it's not perfect because it's not how the server component finds the VolumeSnapshot information. The server component knows the VolumeSnapshot information after the ws-manager stops the workspace and notifies the workspace last information via the ws-manager-bridge.

**Comment by utam0k** [comment]
@jenting May I ask you to organize the commits?

**Comment by jenting** [comment]
> @jenting May I ask you to organize the commits?

Done! PTAL.

**Review by utam0k — APPROVED** [review]

**Pull request merged**
