### PR TITLE
test: Plant a lot of logs for QA report

### PR DESCRIPTION
**Pull request by utam0k**
## Related Issue(s)

NONE

## How to test

```console
 ./run.sh -r report.csv -s workspace 
cat report.csv
```

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by roboquat** [comment]
@utam0k: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by kylos101** [comment]
/werft run with-large-vm=true with-preview=true recreate-vm=true

**Comment by kylos101** [comment]
:wave: hey @utam0k and @Furisto , it seems like we may be able to leverage the e2e-framework [features](https://github.com/kubernetes-sigs/e2e-framework/blob/main/docs/design/test-harness-framework.md#test-features), rather than build a custom [report](https://github.com/gitpod-io/gitpod/blob/60ac1337228afd5e7ba5521b725cc6e4d7812c90/test/report.sh#L46) one, to create a [quality assurance report.](https://www.notion.so/gitpod/Create-a-Quality-Assurance-Report-that-details-what-features-are-covered-or-not-by-tests-94af8d7022de4fb1a43eaef6c9c716c3) 

See below for what I am thinking. In short, it'd be ideal to use what we have, rather than maintain our own report generation. Plus, if we want to generate pretty output, we could use something like https://github.com/vakenbolt/go-test-report.

Given this input:
```bash
go test -v ./...     -kubeconfig=/home/gitpod/.kube/config     -namespace=default     -run TestUploadUrl
```

Output looks like this:
```bash
=== RUN   TestUploadUrl
=== RUN   TestUploadUrl/UploadUrlRequest
=== RUN   TestUploadUrl/UploadUrlRequest/it_should_run_content-service_tests
=== RUN   TestUploadUrl/UploadUrlRequest/it_should_run_content-service_tests/simple_name
=== RUN   TestUploadUrl/UploadUrlRequest/it_should_run_content-service_tests/new_user
=== RUN   TestUploadUrl/UploadUrlRequest/it_should_run_content-service_tests/name_with_whitespace
=== RUN   TestUploadUrl/UploadUrlRequest/it_should_run_content-service_tests/name_with_invalid_char
--- PASS: TestUploadUrl (6.22s)
    --- PASS: TestUploadUrl/UploadUrlRequest (6.22s)
        --- PASS: TestUploadUrl/UploadUrlRequest/it_should_run_content-service_tests (6.22s)
            --- PASS: TestUploadUrl/UploadUrlRequest/it_should_run_content-service_tests/simple_name (0.46s)
            --- PASS: TestUploadUrl/UploadUrlRequest/it_should_run_content-service_tests/new_user (0.15s)
            --- PASS: TestUploadUrl/UploadUrlRequest/it_should_run_content-service_tests/name_with_whitespace (0.15s)
            --- PASS: TestUploadUrl/UploadUrlRequest/it_should_run_content-service_tests/name_with_invalid_char (0.15s)
```

To recap, our [agreed upon fields](https://www.notion.so/gitpod/How-to-create-the-Quality-Assurance-Report-for-the-workspace-a8b7ee2570c44a25aed7bd7d4766f1b1#c2ade76ac1e043d29a621dfc53b18132) are feature, component, test name, description, status.

Let's take one test as an example to see the current mapping is done, and relate each to our agreed upon fields:

```bash
            --- PASS: TestUploadUrl/UploadUrlRequest/it_should_run_content-service_tests/simple_name (0.46s)
```
- **Result**: `PASS` is built-in output already provided by `go test` and maps to `status`
- **Function name**: [`TestUploadUrl`](https://github.com/gitpod-io/gitpod/blob/60ac1337228afd5e7ba5521b725cc6e4d7812c90/test/tests/components/content-service/content-service_test.go#L36), we can ignore, or maybe reuse somehow, but it doesn't clearly map to an agreed upon field. `assess` generally contains a better test name string and component, for example.
- **Feature name**: [`UploadUrlRequest`](https://github.com/gitpod-io/gitpod/blob/60ac1337228afd5e7ba5521b725cc6e4d7812c90/test/tests/components/content-service/content-service_test.go#L67), this maps to `feature` nicely
- **Assess**: [`it should run content-service tests`](https://github.com/gitpod-io/gitpod/blob/60ac1337228afd5e7ba5521b725cc6e4d7812c90/test/tests/components/content-service/content-service_test.go#L69), contains both `test name` and `component`, perhaps we can agree on a convention? For example, <component_a-better-test-description>.
- **test struct Name**:  [`simple name`](https://github.com/gitpod-io/gitpod/blob/60ac1337228afd5e7ba5521b725cc6e4d7812c90/test/tests/components/content-service/content-service_test.go#L44), makes for a nice description of the test's corresponding permutation or purpose

See how @utam0k [centralized features](https://github.com/gitpod-io/gitpod/blob/60ac1337228afd5e7ba5521b725cc6e4d7812c90/test/pkg/report/features.go#L7)? I really like that, we should reuse.

Moving on from here, I think we need to do a couple things.

1. refactor existing tests, such that:
   * each uses Feature, adding new Feature where needed
   * Assess string follows a consistent convention, which we must also document, so that it covers both test name and component
2. scaffold new tests, for features and tests we do not have yet

I'll take a stab at updating `content-test` using :point_up: idea and update this PR accordingly.

**Comment by utam0k** [comment]
@kylos101 Thanks for your comment. The first time, I took into consideration the same thing. It would be better to use an existing tool to create QA report. But I have some concerns.

> if we want to generate pretty output, we could use something like https://github.com/vakenbolt/go-test-report.

I also searched for such tools to create the Report and hit it. Unfortunately, it seems not to maintenance actively.

> Let's take one test as an example to see the current mapping is done, and relate each to our agreed upon fields:
>             --- PASS: TestUploadUrl/UploadUrlRequest/it_should_run_content-service_tests/simple_name (0.46s)
Result: PASS is built-in output already provided by go test and maps to status
Function name: [TestUploadUrl](https://github.com/gitpod-io/gitpod/blob/60ac1337228afd5e7ba5521b725cc6e4d7812c90/test/tests/components/content-service/content-service_test.go#L36), we can ignore, or maybe reuse somehow, but it doesn't clearly map to an agreed upon field. assess generally contains a better test name string and component, for example.
Feature name: [UploadUrlRequest](https://github.com/gitpod-io/gitpod/blob/60ac1337228afd5e7ba5521b725cc6e4d7812c90/test/tests/components/content-service/content-service_test.go#L67), this maps to feature nicely
Assess: [it should run content-service tests](https://github.com/gitpod-io/gitpod/blob/60ac1337228afd5e7ba5521b725cc6e4d7812c90/test/tests/components/content-service/content-service_test.go#L69), contains both test name and component, perhaps we can agree on a convention? For example, <component_a-better-test-description>.
test struct Name: [simple name](https://github.com/gitpod-io/gitpod/blob/60ac1337228afd5e7ba5521b725cc6e4d7812c90/test/tests/components/content-service/content-service_test.go#L44), makes for a nice description of the test's corresponding permutation or purpose

Isn't this different from parsing json output, after all? It seems to me that it is making parsing rather difficult.
And should we ignore parents' test cases? e.g. `--- PASS: TestUploadUrl (6.22s)` I think the QA report becomes too noisy with them.

**Comment by kylos101** [comment]
@utam0k and I spoke about this, and left with the following:
1. he will add stubs for new tests
2. I will update existing tests
3. we will use the e2e framework, rather than the one which was written
4. if an alternate export format is needed (it is not now, we'll use go test output for now), we'll write something like https://github.com/vakenbolt/go-test-report or https://github.com/Thatooine/go-test-html-report, via a separate issue
5. and if we wish as part of that separate issue, we'll consider packaging the report output, similar to installer:versions.yaml and other assets we publish in docker...but for now, results are visible in werft

**Comment by kylos101** [comment]
Closing for now, not a current priority.

**Pull request closed without merging**
