### PR TITLE
Update search input style on project pages

### PR DESCRIPTION
**Pull request by gtsiolis**
## Description

Moving changes from https://github.com/gitpod-io/gitpod/pull/16499.

> Minor follow up from https://github.com/gitpod-io/gitpod/pull/16439 to apply the same search input style on project pages, Branches & Prebuilds.

## Release Notes

```release-note
Update search input style on project pages
```

## Build Options:

- [x] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-slow-database
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [X] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by gtsiolis** [comment]
/werft run with-clean-slate-deployment=true with-preview=true recreate-vm=true

**Comment by gtsiolis** [comment]
One more attempt to spin up a preview environment. 🎲 

/werft run with-preview

**Comment by gtsiolis** [comment]
Ready-For-Review 🏓 

There are a few minor spacing differences with the search input in dashboard vs. admin dashboard, but should be fine to merge this as is and tackle this separately with https://github.com/gitpod-io/gitpod/issues/16511.

**Review by easyCZ — APPROVED** [review]

**Pull request merged**
