### PR TITLE
Remove theia IDE

### PR DESCRIPTION
**Pull request by aledbf**
## Release Notes

```release-note
Remove theia IDE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **akosyakov** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @akosyakov` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**
- **[installer/pkg/components/server/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/server/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: ac89023e187b6d557bbf37ecad70fe72b2dab66f</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7395#issuecomment-1003127615" title="Approved">iQQBot</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/7395#issuecomment-1003127615" title="Approved">iQQBot</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [iQQBot]
- ~~[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)~~ [iQQBot]
- ~~[installer/pkg/components/server/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/server/ide/OWNERS)~~ [iQQBot]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jeanp413** [comment]
I still see a lot of theia stuff in the repo `1359 results - 218 files` when searching for theia in the whole repo, also there's this issue open https://github.com/gitpod-io/gitpod/issues/4630, should we close it or is this still WIP? shoudl we schedule the complete removal of theia in the whole repo? cc @akosyakov

**Comment by akosyakov** [comment]
It would be good to clean up old code for sure, but not everything is trviai to remove. If we can have split it and remove bit by bit when someone have spare time it would be good. Otherwise focusing on user valuable issues is better.

**Pull request merged**
