### PR TITLE
Update buildkit to v0.10.4

### PR DESCRIPTION
**Pull request by aledbf**
## Description

https://github.com/moby/buildkit/releases

## How to test
- Open a workspace. Builds should not fail

## Release Notes
```release-note
NONE
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Review by Furisto — APPROVED** [review]

**Comment by jenting** [comment]
image
🤔

**Comment by aledbf** [comment]
@jenting what repository?

**Comment by jenting** [comment]
> @jenting what repository?

I fork youki and add a line https://github.com/jenting/youki/blob/95c4e4959ce4e37d599f1e5406e51f03d45d9e1e/.gitpod.Dockerfile#L10 to make the image builder be triggered. I haven't checked if it is my problem or not.

**Comment by jenting** [comment]
@aledbf  Never mind, I can't reproduce it on the ephemeral cluster. Thank you.

**Pull request merged**
