### PR TITLE
[code] Port telemetry to stable

### PR DESCRIPTION
**Pull request by jeanp413**
- [x] /werft with-clean-slate-deployment

## Description

Port telemetry events to code web stable

## How to test

1. Select stable
2. Open a workspace
3. Check telemetry events (starting with vscode_) are generated in https://app.segment.com/gitpod/sources/staging_untrusted/debugger

## Release Notes

```release-note
NONE
```

/werft analytics=segment|TEZnsG4QbLSxLfHfNieLYGF4cDwyFWoe

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jeanp413** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by filiptronicek — COMMENTED** [review]
I seemingly can't trigger any telemetry events, I tried executing Gitpod commands, starting a few workspaces, opening files but nothing. I also don't see any of the normally available analytic logs like `workspace_started`. Any idea why this could be?

**Comment by jeanp413** [comment]
@filiptronicek have you selected insiders in your preferences?

**Comment by filiptronicek** [comment]
Having some issues... I'll run Werft again with a clean slate to maybe eliminate some problems from the latest deployment. 

image
image

**Comment by jeanp413** [comment]
:thinking: I just rebased hope that fixes it

**Comment by jeanp413** [comment]
Ah it seems it won't be possible to merge this now that https://github.com/gitpod-io/gitpod/pull/7558 got merged, it fails because we updated how we launch the server with the new upstream changes.
I could add a check in `components/ide/code/startup.sh` so that it checks if old `server.sh` exists and use that for stable otherwise use the new executable for insiders or we could just wait for next release.
Will ask for feedback in slack channel

**Comment by filiptronicek** [comment]
@jeanp413 I guess that's why the preview env is acting funny, for some reason there Insiders is just 1.63.2 (https://github.com/gitpod-io/openvscode-server/commit/16d43d2bb89bb32b58ff0c84bef55486269760d6). Please let me know when it's ready to review again 🙂.

**Comment by jeanp413** [comment]
> @jeanp413 I guess that's why the preview env is acting funny, for some reason there Insiders is just 1.63.2 ([gitpod-io/openvscode-server@16d43d2](https://github.com/gitpod-io/openvscode-server/commit/16d43d2bb89bb32b58ff0c84bef55486269760d6)). Please let me know when it's ready to review again slightly_smiling_face.

yeah that's expected when we update the code commit in `WORKSPACE.yaml`, the image that will be updated in the preview env is the insiders image, that's where all the changes in the pointed commit will be reflected

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jeanp413** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[installer/pkg/components/workspace/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/workspace/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jeanp413** [comment]
I updated the PR by using an image build from a commit before #7558 got merged. You can test now by selecting vscode stable 
in settings.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7559#pullrequestreview-852752016" title="Approved">filiptronicek</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [filiptronicek]
- ~~[installer/pkg/components/workspace/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/workspace/ide/OWNERS)~~ [filiptronicek]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7559#issuecomment-1013007610" title="Approved">filiptronicek</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/7559#issuecomment-1013007610" title="Approved">filiptronicek</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [filiptronicek]
- ~~[installer/pkg/components/workspace/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/workspace/ide/OWNERS)~~ [filiptronicek]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
