### PR TITLE
docker-up: Enable rootless mode only in cgroup v1

### LINKED ISSUE #9776: Support docker resource constraints
## Is your feature request related to a problem? Please describe

Docker containers are subject to the resource constraints for their Gitpod workspace. Some customers would like to limit the resources that containers can use. This is to support testing of their applications using resource limits, but also prevent the Docker container from starving the Gitpod workspace of resources. 

## Describe the behaviour you'd like

The ability for customers to [specify resource constraints when running docker containers](https://docs.docker.com/config/containers/resource_constraints/#cpu) in Gitpod workspaces.

## Describe alternatives you've considered

N/A

## Additional context

Presently, the resource constraints are not honored. So, if you start a container with ``cpu="0.5", it'll still try to use as many cores as are available to the Gitpod workspace.

### PR DESCRIPTION
**Pull request by utam0k**
## Description
Enable rootless mode only in cgroup v1 because docker requires systemd when using rootless mode in cgroup v2.

## Related Issue(s)

Fixes #9776

## How to test

Check the following in cgroup v1/v2

1. Open a workspace
2. Run the below command on the workspace
```console
$ docker run --rm --cpus 1 --memory 32m --name stress alexeiled/stress-ng --cpu=2
```
3. Open another console, and run the below command and check if the limit is working
```console
$ docker stats
```

## Release Notes

```release-note
Check the following in cgroup v1/v2
Eliminate dockerd rootless mode in cgroup v2
```

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@utam0k: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by utam0k** [comment]
/hold
until check the behavior in cgroup v2

**Review by jenting — APPROVED** [review]

**Pull request merged**
