### PR TITLE
[werft] Use delete pod --force for stubborn workspaces

### PR DESCRIPTION
**Pull request by geropl**
Fixes the situation where preview environments don't get delete because `kubectl delete pod ...` hangs indefinitely on single workspaces.

### CODE REVIEW

**Comment by wulfthimm** [comment]
Deleting the pod by force will remove the pod from Kubernetes but not from the cluster leaving it in an unknown state. Automating the deletion could obscure the problem and break our preview cluster in the long run.

**Comment by geropl** [comment]
> Deleting the pod by force will remove the pod from Kubernetes but not from the cluster leaving it in an unknown state. Automating the deletion could obscure the problem and break our preview cluster in the long run.

True, but that's a cost I'd like to pay. Especially as we're actively try to cycle nodes ideally each day - which is currently blocked by this very bug.

**Comment by geropl** [comment]
```
copying certificate from "certs/staging-gpl-werft-force-delete" to "staging-gpl-werft-force-delete/proxy-config-certificates"
Error: kubectl get secret staging-gpl-werft-force-delete --namespace=certs -o yaml         | yq d - 'metadata.namespace'         | yq d - 'metadata.uid'         | yq d - 'metadata.resourceVersion'         | yq d - 'metadata.creationTimestamp'         | sed 's/staging-gpl-werft-force-delete/proxy-config-certificates/g'         | kubectl apply --namespace=staging-gpl-werft-force-delete -f - exit with non-zero status code
```
Never had _that_ before... :grimacing: Re-trying

/werft run

**Review by corneliusludmann — APPROVED** [review]
_May the force be with you._

Change looks good so far. Let's hope that this will improve the situation. Thank you, @geropl!

**Pull request merged**
