### PR TITLE
clean up tokens on deauthorize

### PR DESCRIPTION
**Pull request by AlexTugarev**
# clean up tokens on deauthorize
fixes https://github.com/gitpod-io/gitpod/issues/3800

### how to test

1. authorize with two providers
2. disconnect one 
3. verify (in the db 🤷🏻‍♂️) that tokens are (marked as) deleted

# temporarily disable terms acceptance check in API

### CODE REVIEW

**Comment by jankeromnes** [comment]
Thanks Alex!

> ### how to test
> 
> 1. revoke permissions for the OAuth App of Gitpod preview environments
> 2. try to login and decline
> 3. verify to see an error instead of a hanging redirect (and timeout)

This is where I end up at (correct-looking `/sorry` URL, but since I'm not logged in, it shows the login screen instead):

Screenshot 2021-04-09 at 17 58 33

**Comment by AlexTugarev** [comment]
@jankeromnes, thanks for testing!

First of, it tries to redirect is an error page (and not to login) and that's what's expected. 

An error page that is only rendered if logged in is problematic at least. :-(

In this particular case though the flow and the resulting redirect is happening in a separate browser tab, so the target for redirect should not be the sorry page. Indeed it should redirect to /login-error (symmetrical to /login-success) and propagate to the still open login page, which will close the extra tab and, that's the plan, render a message. 

One step at a time.

**Comment by AlexTugarev** [comment]
@jankeromnes, I extracted https://github.com/gitpod-io/gitpod/pull/3915 from here. I turns out there is a tail to that problem.

**Comment by AlexTugarev** [comment]
@csweichel, could you have a look at the changes left in this PR, please?

**Review by csweichel — APPROVED** [review]
Change LGTM

**Pull request merged**
