### PR TITLE
[code] open PR controller in PR context

### LINKED ISSUE #4081: [Gitpod Code] Add a notification on Pull Requests that asks for opening the PR-Overview
Currently, the button to open the "PR Review View" is hidden:
 - in the "PR View"
 - under an icon (top row) that is not very descriptive
 - invisible by default, until you hover above it

Without the "PR- Review View" you cannot "Submit review".

It would be nice if it'd be easier to find that view, be it with an button on the bottom bar or a notification.

### PR DESCRIPTION
**Pull request by JanKoehnlein**
Fixes #4081

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5021#" title="Author self-approved">JanKoehnlein</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **akosyakov** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @akosyakov` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by JanKoehnlein** [comment]
Needs https://github.com/gitpod-io/vscode/pull/24 to be merged as well

**Comment by akosyakov** [comment]
Please don't forget to merge VS Code PR and rebase before unhold. 

/lgtm

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 641ae557e46d8249c70f1695a4f0d9b192451f3f</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5021#issuecomment-890753973" title="LGTM">akosyakov</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/5021#" title="Author self-approved">JanKoehnlein</a>*

Associated issue: *#4081*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)~~ [akosyakov]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5021#issuecomment-890753973" title="LGTM">akosyakov</a>*

Associated issue: *#4081*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)~~ [akosyakov]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by akosyakov** [comment]
I see this dialog for each worskpace on PR now:
Screenshot 2021-08-04 at 08 20 54

Regardless whether GitHub PR extension already has access rights or not.

**Comment by JanKoehnlein** [comment]
https://github.com/gitpod-io/gitpod/issues/4081#issuecomment-892607493

**Pull request closed without merging**
