### PR TITLE
chore(service-waiter): move from `streadway/amqp` to `rabbitmq/amqp091-go`

### PR DESCRIPTION
**Pull request by Juneezee**
## Description

The [`github.com/streadway/amqp`](https://github.com/streadway/amqp) library is no longer actively maintained. The new libary is now maintained by the RabbitMQ core team under a different package name [`github.com/rabbitmq/amqp091-go`](https://github.com/rabbitmq/amqp091-go).

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by Juneezee** [comment]
Not stale

**Comment by Juneezee** [comment]
not stale

**Comment by Juneezee** [comment]
Not stale

**Comment by easyCZ** [comment]
Thanks for the contribution @Juneezee. I'll run this through our preview environment to do some validation.

**Comment by Juneezee** [comment]
> Thanks for your contribution, @Juneezee! Before merging it, we need to have your signed Contributor License Agreement (CLA) on file. You can sign it via [this DocuSign form](https://powerforms.docusign.net/30e1aa46-cce5-4bc6-a933-ad02cd8d5ada?env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&accountId=86335c2c-01b9-4edc-a187-014f5150a112). If you have any questions about this, please let me know via [moritz@gitpod.io](mailto:moritz@gitpod.io)

Hi @meysholdt, I have signed the CLA.

**Comment by meysholdt** [comment]
Excellent, thank you!

**Comment by meysholdt** [comment]
hi @Juneezee ! I see there is trouble with the build. Could you rebase this PR on the latest changes from the `main` branch?

**Comment by Juneezee** [comment]
> hi @Juneezee ! I see there is trouble with the build. Could you rebase this PR on the latest changes from the `main` branch?

@meysholdt Done! Please take a look again. Thank you.

**Review by easyCZ — APPROVED** [review]
LGTM. Thanks for the contribution.

**Pull request merged**
