### PR TITLE
Test --filter=blob:none again

### PR DESCRIPTION
**Pull request by aledbf**
## Related Issue(s)

Fixes #

## Release Notes

```release-note
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@aledbf: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by akosyakov** [comment]
@aledbf I cannot get a working build 🤦

**Comment by aledbf** [comment]
/werft run with-clean-slate-deployment with-integration-tests=workspace

**Comment by akosyakov** [comment]
@filiptronicek could you rebase and then we try it again

cc @jeanp413

**Comment by akosyakov** [comment]
I think it was causing problems like https://github.com/gitpod-io/gitpod/issues/6796 last time.

**Comment by jeanp413** [comment]
Btw codepsaces doesn't use filter either
```
Configuration starting...
Cloning...
$ git -C "/var/lib/docker/codespacemount/workspace" clone --branch main --depth 1 https://github.com/gitpod-io/gitpod "/var/lib/docker/codespacemount/workspace/gitpod"
Cloning into '/var/lib/docker/codespacemount/workspace/gitpod'...
git process exited with exit code 0
$ git -C "/var/lib/docker/codespacemount/workspace/gitpod" config --local remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
git process exited with exit code 0
Using image: mcr.microsoft.com/devcontainers/universal:2

```

**Comment by akosyakov** [comment]
cc @iQQBot @mustard-mh what it was breaking before could be found in https://github.com/gitpod-io/gitpod/pull/13845#issuecomment-1402251166

**Pull request closed without merging**
