### PR TITLE
[dashboard] Allow creating new Projects from templates

### PR DESCRIPTION
**Pull request by jankeromnes**
## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/issues/5583

## Release Notes

```release-note
Allow creating new Projects from a template repository
```

## Documentation

/uncc

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by:

Associated issue: *#5583*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**
- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by:

Associated issue: *#5583*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**
- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jankeromnes** [comment]
Binami flake, let's try again:

/werft run

**Comment by svenefftinge** [comment]
Do we have some sort of design doc for this? It seems a bit underspecified if all we have is the issue that is referenced. 
E.g. would be great to think and be clear about what a "template" really is and how we can add them over time. 
Also, It would be great to allow others to make starter URLs based on their "templates" at least long term, so somehow have such a path in mind.

**Questions we should answer**
 - What does a template look like? Is it an archive? What format? What is the expected contents?
 - Do we support naming a new project such that all the references in a template get updated accordingly? If yes, how does it work / what is the contract?
 - Can we support a context URL that allows third parties to create links that get users into the project creation flow?

**Comment by jankeromnes** [comment]
Closing this work-in-progress Pull Request based on https://github.com/gitpod-io/gitpod/issues/5583#issuecomment-979760177

The current state of this code change is described in https://github.com/gitpod-io/gitpod/issues/5583#issuecomment-982602246

**Pull request closed without merging**
