### PR TITLE
[supervisor] fixes not recycle zombie processes

### LINKED ISSUE #6976: workspace does not recycle zombie processes
### Bug description

workspace does not recycle zombie processes

### Steps to reproduce

use leeway build, you can see lot of zombie processes
image

### Workspace affected

_No response_

### Expected behavior

recycle zombie processes

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by iQQBot**
## Description

[supervisor] fixes not recycle zombie processes

## Related Issue(s)

Fixes #6976

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jeanp413** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jeanp413` in a comment when ready.

Associated issue: *#6976*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by csweichel** [comment]
Great find! Well done indeed.

Other than a small comment nit, this lgtm. Feel free to unhold merge as is, or change the comment :)

/hold
/lgtm

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: e4c87b45a449ee5edb81074776c50e89177e1860</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6977#issuecomment-982386377" title="LGTM">csweichel</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jeanp413** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jeanp413` in a comment when ready.

Associated issue: *#6976*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6977#issuecomment-982391448" title="Approved">akosyakov</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6977#issuecomment-982386377" title="LGTM">csweichel</a>*

Associated issue: *#6976*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [akosyakov]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 947c43f95488352d625def94344ee3cefcf64f98</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6977#issuecomment-982391448" title="Approved">akosyakov</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6977#issuecomment-982849869" title="LGTM">csweichel</a>*

Associated issue: *#6976*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [akosyakov]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
