### PR TITLE
Remove FORBIDDEN_SLUGS

### LINKED ISSUE #6929: [db] remove FORBIDDEN_SLUGS
Now that we have a dedicated slug (/t/:team) for teams (see #5544), maybe there's no need to use a fixed list of forbidden slugs and we could potentially remove the [FORBIDDEN_SLUGS](https://github.com/gitpod-io/gitpod/blob/5d751e330d37680e6b6ab5cf6ef7b5e9496f71be/components/gitpod-db/src/typeorm/team-db-impl.ts#L19) list.

See also https://github.com/gitpod-io/gitpod/pull/6878#issuecomment-979995861

### PR DESCRIPTION
**Pull request by championshuttler**
## Related Issue(s)

Fixes #6929

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
@championshuttler: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **alextugarev** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @alextugarev` in a comment when ready.

Associated issue: *#6929*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by JanKoehnlein** [comment]
Hi @championshuttler, thanks for the contribution! Unfortunately it doesn't compile yet 
```
src/typeorm/team-db-impl.ts(7,1): error TS6133: 'blocklist' is declared but its value is never read.
```
I think the blocklist should still be considered. 

Hint: You can compile that component locally by running
```
leeway build components/gitpod-db:lib
```

**Comment by JanKoehnlein** [comment]
@championshuttler  Sorry for being unresponsive. Could you please re-enable the blocklist checking?

**Comment by JanKoehnlein** [comment]
I am merging this. Thanks a lot for this contribution, @championshuttler !

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 197b0abd989818057641acc6330b4cedd85b9a90</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7320#issuecomment-1005459681" title="LGTM">JanKoehnlein</a>*

Associated issue: *#6929*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)~~ [JanKoehnlein]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
