### PR TITLE
[Future Preview Environments] Use TF to create DNS records

### PR DESCRIPTION
**Pull request by vulkoingim**
## Description

Create DNS records for the preview environment using TF

## Related Issue(s)

Fixes https://github.com/gitpod-io/ops/issues/5817

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by vulkoingim** [comment]
https://github.com/gitpod-io/gitpod/pull/13756 should land first

**Review by mads-hartmann — APPROVED** [review]
Awesome 🐎

**Pull request merged**
