### PR TITLE
add dockerfile for testing image builder

### PR DESCRIPTION
**Pull request by sagor999**
## Description
adds a simple dockerfile for integration tests to test image builder
need to commit as a separate file so that tests can pull it from `main` branch

## Related Issue(s)
#7675 

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **furisto** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @furisto` in a comment when ready.

Associated issue: *#7675*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by kylos101** [comment]
Hey @sagor999 can you share how this is intended to be used by the integration tests? I'm not sure which test you are referring.

For example, normally the image that image builder builds uses a Gitpod image as its base. [Here is an example base image.](https://hub.docker.com/r/gitpod/workspace-base)

**Comment by sagor999** [comment]
Yeah. It will be used here:
https://github.com/gitpod-io/gitpod/blob/e33530913f1d5358e209373a8c5f4b6c75549d0e/test/tests/components/image-builder/builder_test.go#L47

if we pull workspace image it takes a very long to pull it.

**Review by princerachit — APPROVED** [review]

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 18936ad8144e4b58e3cb7e73310f504a38b2b3ae</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7767#pullrequestreview-861850174" title="Approved">princerachit</a>*

Associated issue: *#7675*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [princerachit]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
