### PR TITLE
Add docs that describe how a workspace is started

### PR DESCRIPTION
**Pull request by Furisto**
## Description
Add docs to describe how a workspace is started (workspace components only) and how  namespaces are layered to create a workspace.

[Start workspace](https://raw.githubusercontent.com/gitpod-io/gitpod/39039b8cd1b04c6925a354e0901369a1e2b731b9/docs/workspace/architecture.drawio.svg)
[Namespaces](https://raw.githubusercontent.com/gitpod-io/gitpod/39039b8cd1b04c6925a354e0901369a1e2b731b9/docs/workspace/namespaces.drawio.svg)

## Related Issue(s)
n.a.

## How to test
n.a.

## Release Notes
```release-note
NONE
```

### CODE REVIEW

**Comment by utam0k** [comment]
I'm still working on it, but I've added a few things. I'm not too sure around the ws-manager... 😭 
I may need to change the color of the lines to a color that is visible in both dark and light modes on github. Why don't you ask @csweichel to review it when it is finished?

**Comment by Furisto** [comment]
@csweichel Can you check if everything is depicted correctly?

**Comment by csweichel** [comment]
Re workspace startup: looks pretty comprehensive (from the runtime side :) ) - minor detail
image

**Comment by csweichel** [comment]
Regarding the namespace diagram: a legend for the colours would be very handy :)

**Comment by utam0k** [comment]
@csweichel @Furisto PTAL

**Comment by Furisto** [comment]
Looks good!

**Review by sagor999 — APPROVED** [review]
Excellent work! Thank you! Definitely gave me insight on how this all works.

**Pull request merged**
