### PR TITLE
[code] Update code to 1.86.1

### PR DESCRIPTION
**Pull request by jeanp413**
## Description

- Update code to 1.86.1with support for old linux versions
- ~~Delete code 1.85 option~~

## How to test

Preview env https://jp-sick-perch.preview.gitpod-dev.com/workspaces

Already tested myself:
- Test repo https://github.com/jeanp413/test-gp-prebuild/tree/jp/damaged-aardwolf
- Set default editor to code 1.85, create workspace, delete code 1.85 option restart workspace, it starts successfully
- Created new workspace with ubuntu 18.04 image 

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by jeanp413** [comment]
Only caveat is that ide picker shows warning about old ide option being unsupported, can be fixed by manually setting default editor to code 1.86 in user preferences, but even with autostart or restart workspaces can start successfully
image

**Review by filiptronicek — APPROVED** [review]
🚀

**Comment by 31031969** [comment]
[35425669.pdf](https://github.com/gitpod-io/gitpod/files/14215422/35425669.pdf)

**Comment by 31031969** [comment]
[1 (1) (1) (1) (2) (2).pdf](https://github.com/gitpod-io/gitpod/files/14215424/1.1.1.1.2.2.pdf)

**Pull request merged**
