### PR TITLE
[leeway] Fix leeway vet

### PR DESCRIPTION
**Pull request by csweichel**
`leeway vet` [was broken](https://github.com/gitpod-io/leeway/commit/cb49e6c4b0cee38884aa78f0782d667af6d3ad7d). This PR updates leeway and runs `leeway fmt`.

### CODE REVIEW

**Review by AlexTugarev — APPROVED** [review]
ran `leeway vet --ignore-warnings` without errors ✔️ 
format changes lgtm ✔️ 
🙏🏻

**Comment by AlexTugarev** [comment]
nit: a couple of unpushed changes to .mod/.sum files is left over

**Comment by csweichel** [comment]
The unpushed go.mod changes might be fixed in #3171 already :)

**Pull request merged**
