### PR TITLE
Updated license summary for npm packages

### PR DESCRIPTION
**Pull request by meysholdt**
## Description
Update license summary for npm packages.

generated by running 
```
yarn licenses generate-disclaimer > License.third-party.npm.txt
```

## Related Issue(s)
(none)

## How to test
(not needed)

## Release Notes
```release-note
NONE
```

## Documentation

none.

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **loujaybee** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @loujaybee` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 90bc0be8deef377823a71586d08d96a50b74de4f</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7148#issuecomment-999653232" title="Approved">akosyakov</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/7148#issuecomment-999653232" title="Approved">akosyakov</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [akosyakov]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by kylos101** [comment]
/hold

Tide has many errors for this PR, not sure why:
`failed merging [7148]: status code 422 not one of [201], body: {"message":"Validation Failed","errors":[{"resource":"Status","code":"custom","message":"This SHA and context has reached the maximum number of statuses."}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-a-commit-status"}`

Looks like Tide has been throwing errors for it for 12+ hours, I think the error is preventing a merge.

**Comment by kylos101** [comment]
@akosyakov @loujaybee @meysholdt happy holidays! I held this because it was blocking Tide, preventing merges to main. 

[Also, in looking at this build](https://github.com/gitpod-io/gitpod/pull/7148#issuecomment-999653405), it looks like the werft job failed. 

You may want to rerun the werft job and confirm it passes prior to removing the hold. Either way, you're welcome to remove the hold when you see fit. Happy holidays!

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by meysholdt** [comment]
Thank you @iQQBot. I've squashed the commits.

**Pull request merged**
