### PR TITLE
Fix find authorized user for GHE prebuilds

### PR DESCRIPTION
**Pull request by AlexTugarev**
## Description
Iterate of team owners to find the authorized user to trigger a prebuild for a project on a push event.

## Related Issue(s)

Based on: https://github.com/gitpod-io/gitpod/pull/11584

Fixes https://github.com/gitpod-io/gitpod/issues/11566

## Release Notes

```release-note
Fix broken prebuild trigger for GHE.
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@AlexTugarev: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by geropl — APPROVED** [review]
Tested, and works nicely! :tada: 
image

**Comment by AlexTugarev** [comment]
@geropl, I've seen you added https://github.com/gitpod-io/gitpod/pull/11570/commits/ff83a649477204573aeae9944954691d3c334105 to this branch. 

Is this relevant for this PR? If not, let's remove it, it seems to be unrelated.

**Comment by geropl** [comment]
@AlexTugarev It's already on master, you can remove. I needed it to be able to test in the preview env.

**Review by geropl — APPROVED** [review]
Approving again :heavy_check_mark:

**Pull request merged**
