### PR TITLE
Add a "Documentation" section to the PR template.

### PR DESCRIPTION
**Pull request by mikenikles**
## Description

This PR adds a "Documentation" section to the `pull_request_template.md`.

## Related Issue(s)

Fixes #

## Release Notes

```release-note
[chore] Add a "Documentation" section to the PR template.
```

## Documentation

A bit meta, but no documentation is required for this PR.

### CODE REVIEW

**Comment by roboquat** [comment]
@mikenikles: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **svenefftinge** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @svenefftinge` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by csweichel** [comment]
The question came up the other day how we want to handle documentation issues, and how to make sure they're not forgotten. If we're not tracking them as part of groundwork changes are they'll just remain issues in some repo "far away".

I like the idea to have a documentation section, but would rather ask for direct action and a docs PR rather than a docs issue.

**Comment by mikenikles** [comment]
I'm with you on that, I'd prefer a PR over an issue too. The benefit of an issue is it allows the DCS team to write the docs in a consistent style and place them where they best fit.

Until we have strict writing guidelines and as much automation as possible to enforce it, I think we're better off with an issue and leave it to the DCS team to formally write the docs.

The other benefit I see is that the DCS person who writes the docs is the first non-engineering team member to test new features and can provide feedback from an end-user perspective.

**Review by ghuntley — CHANGES_REQUESTED** [review]
Send the PR to https://github.com/gitpod-io/.github/edit/main/.github/pull_request_template.md instead once we have a decision to direction in this thread.

**Comment by mikenikles** [comment]
Closing in favour of https://github.com/gitpod-io/.github/pull/5 as requested above.

**Pull request closed without merging**
