### PR TITLE
Update images digests

### PR DESCRIPTION
**Pull request by roboquat**
Update images digests using the latest version available for image/s

```release-note
NONE
```

### CODE REVIEW

**Review by filiptronicek — APPROVED** [review]
🚌

**Review by kylos101 — APPROVED** [review]
:shipit:

**Comment by kylos101** [comment]
:wave: @gitpod-io/engineering-security-infrastructure-and-delivery and @gtsiolis for :eyes: and :heavy_check_mark:

**Comment by gtsiolis** [comment]
@kylos101 👋

Friendly reminder that @gtsiolis is an additional reviewer for changes in the `components/dashboard` folder, but not required to additionally approve if someone from `@gitpod-io/engineering-webapp` already approved the changes, see **[CODEOWNERS](https://github.com/gitpod-io/gitpod/blob/0058d68f5e0088c0b4d96b0c694872958dc9da8c/.github/CODEOWNERS#L11)**. 🎗️

**Comment by kylos101** [comment]
> @kylos101 wave
> 
> Friendly reminder that @gtsiolis is an additional reviewer for changes in the `components/dashboard` folder, but not required to additionally approve if someone from `@gitpod-io/engineering-webapp` already approved the changes, see **[CODEOWNERS](https://github.com/gitpod-io/gitpod/blob/0058d68f5e0088c0b4d96b0c694872958dc9da8c/.github/CODEOWNERS#L11)**. reminder_ribbon

:facepalm: I was confused because of:
image

**Comment by gtsiolis** [comment]
Have to agree, it is confusing. I know this only by practice, not relying on GH's UI. 😬

**Comment by kylos101** [comment]
@gitpod-io/engineering-security-infrastructure-and-delivery can we have your help in reviewing this PR?

**Review by mads-hartmann — APPROVED** [review]

**Comment by mads-hartmann** [comment]
Approved by applied the hold label because CI is not passing. I re-triggered it 🤞

**Pull request merged**
