### PR TITLE
[usage] Temporarily remove flaky test

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

Temporarily remove the test until I can properly debug it, this prevents failing main

## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Documentation

NONE
## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@easyCZ: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by easyCZ** [comment]
I don't like this approach but debugging the test will take a bit longer and this unblocks main in the short term. The test only really checks that queries with more than 2^16 values in `WHERE id IN (?, ?)` work so this is somewhat safe in the short term.

**Comment by easyCZ** [comment]
@andrew-farries merging this should unblock you

**Review by jankeromnes — APPROVED** [review]
Yes please! Many thanks. 🙏

**Pull request merged**
