### PR TITLE
Remove workspace_classes_backend feature flag

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

https://gitpod.slack.com/archives/C02F19UUW6S/p1678715506560899

## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by geropl — APPROVED** [review]

**Comment by svenefftinge** [comment]
@easyCZ  there were imports that are now no longer used and break the build

**Comment by easyCZ** [comment]
Taking a look. Bizarre that the build would pass on CI

**Comment by svenefftinge** [comment]
It seems like the build was skipped?

**Comment by easyCZ** [comment]
https://github.com/gitpod-io/gitpod/pull/16827 for a fix

**Comment by easyCZ** [comment]
Raised it in https://gitpod.slack.com/archives/C01KLC56NP7/p1678719266672229

**Pull request merged**
