### PR TITLE
[server] Don't count ToS rejection to login metric

### LINKED ISSUE #4296: Missing terms of service approval on Gitlab causes login error and related SLO impact
New GitLab users who did not accept ToS on gitlab.com, but trying to sign up with Gitpod will be logged as a login failure:

> Error: 403 Forbidden - You (foo) must accept the Terms of Service in order to perform this action. Please access GitLab from a web browser to accept these terms

This impacts the SLO and can result in GitpodLoginErrorBudgetBurn alerts.

Suggestion from @AlexTugarev is "Maybe we need to reduce the log level for this error case."

### PR DESCRIPTION
**Pull request by csweichel**
hopefully

fixes #4296

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4888#" title="Author self-approved">csweichel</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankoehnlein** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankoehnlein` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by AlexTugarev — APPROVED** [review]
LGTM!

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 79a9e670c998cdfc475e6a31ab71cdf892ab838f</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4888#pullrequestreview-711403739" title="Approved">AlexTugarev</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4888#" title="Author self-approved">csweichel</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [AlexTugarev]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
