### PR TITLE
Revert "[installer]: remove all podsecuritypolicies"

### PR DESCRIPTION
**Pull request by MrSimonEmms**
Reverts gitpod-io/gitpod#12173

Caused issue in SaaS due to GKE having PodSecurityPolicies enabled on cluster - see [channel](https://gitpod.slack.com/archives/C03UQ58RG0M)

## Release Notes

```release-note
Revert "[installer]: remove all podsecuritypolicies" #12313
```

### CODE REVIEW

**Comment by roboquat** [comment]
@MrSimonEmms: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by sagor999 — APPROVED** [review]

**Review by adrienthebo — APPROVED** [review]
**EDIT**: the werft build is failing, I've rescinded my approval and am investigating that failure.

**Comment by MrSimonEmms** [comment]
@adrienthebo thank you for that. It was the golden files - have updated and rerun

**Review by adrienthebo — APPROVED** [review]
/unhold 🚢

**Pull request merged**
