### PR TITLE
Remove supervisor gRPC metrics and process metrics

### PR DESCRIPTION
**Pull request by iQQBot**
## Description

Remove supervisor gRPC metrics and process metrics, because we don't interested supervisor metrics [context](https://github.com/gitpod-io/observability/pull/121#issuecomment-1127719705)

## Related Issue(s)

Fixes #

## How to test

1. start a workspace
2. run `curl http://localhost:22999/metrics` it should be emply
3. run `echo "gitpod_some_metric 3.14" | curl --data-binary @- http://localhost:22999/metrics/job/some_job`
4. run `curl http://localhost:22999/metrics` again it should be only have `gitpod_some_metric` and `pushgateway` metrics

image

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
@iQQBot: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by andreafalzetti** [comment]
To help me understand better, in [this PR](https://github.com/gitpod-io/gitpod/pull/9815) we introduced the metrics but we are now removing them. If I understand correctly, we are only removing a subset of the metrics (gRPC metrics and process metrics) but we are keeping some?

What type of metrics are we keeping?

**Comment by mustard-mh** [comment]
> To help me understand better, in https://github.com/gitpod-io/gitpod/pull/9815 we introduced the metrics but we are now removing them. If I understand correctly, we are only removing a subset of the metrics (gRPC metrics and process metrics) but we are keeping some?
> What type of metrics are we keeping?

@andreafalzetti  See also https://github.com/gitpod-io/observability/pull/121#issuecomment-1127719705 we delete it because we are not interesting with it and the storage is expensive

**Review by mustard-mh — APPROVED** [review]
Works like a charm XD

image

**Pull request merged**
