### PR TITLE
Add Parca to preview environments

### PR DESCRIPTION
**Pull request by ArthurSens**
Signed-off-by: ArthurSens <arthursens2005@gmail.com>

## Description

With the recent announcements from [PolarSignals](https://twitter.com/PolarSignalsIO/status/1446494872647741441), I decided to take a look at their Profiling tool. They have eBPF agents([parca-agent](https://github.com/parca-dev/parca-agent)) that transfer pprof profiles via gRPC to a profile storage with a query engine([parca](https://github.com/parca-dev/parca)).

Both applications have jsonnet libraries for deployment, so getting both into our stack was super simple.

This is my first time playing with their tool, so at first I just made it available in previews. I'll see if I can get a better understanding during the weekend 🙂 

## Related Issue(s)

Fixes #

## How to test

Access https://parca-as-parca-profiling.preview.gitpod-dev.com/

## Release Notes

```release-note
```

### CODE REVIEW

**Comment by roboquat** [comment]
@ArthurSens: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankeromnes** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankeromnes` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 3b41de648f2f80e28759321d5dcd1a222f90a02a</details>

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by ArthurSens** [comment]
Hey 👋 -- Asking again just to make sure, are we good to move forward with this?

**Pull request closed without merging**
