### PR TITLE
[server] use options from last instances on start

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description

This change makes the workspace start reusing what has been used for IDE and workspace class on the previous workspace instance.

I think this change can land on its own. In a larger second PR we would allow users to start an existing workspace with options, so users can change/override what IDE and workspace class to use on subsequent workspace starts.

## Related Issue(s)

Fixes WEB-189

## How to test

Create a workspace with non default IDE and was class. Stop the workspace and restart it. It should still use the previously selected IDE and class.

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - se-start-ws-options</li>
	<li><b>🔗 URL</b> - <a href="https://se-start-ws-options.preview.gitpod-dev.com/workspaces" target="_blank">se-start-ws-options.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
</ul>

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

/hold

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]

**Comment by svenefftinge** [comment]
I'm not able to get a working preview env. So trying on a different branch again https://github.com/gitpod-io/gitpod/pull/17298

**Pull request closed without merging**
