### PR TITLE
[installer] manually set `allowPrivilegeEscalation` to false

### PR DESCRIPTION
**Pull request by Pothulapati**
## Description

This PR manually sets the `allowPrivilegeEscalation` container config to false where
we don't need extra capabilities. Though this **does not effect anything** yet, 
This is needed as not setting this explicitely could mean that it could still be `true`
based on some other settings.

This also helps us future proof on any behaviour changes around this.

This skips the following components as they need privilege access:
- `agent-smith` component container
- `ws-daemon` Component container
- `shiftfs` container

Signed-off-by: Tarun Pothulapati <tarun@gitpod.io>

## Related Issue(s)

Part of https://github.com/gitpod-io/security/issues/70

## How to test

Tested that workspaces start correctly through [a preview environment](https://tar-disall94b71aa516.preview.gitpod-dev.com/workspaces)

## Release Notes

```release-note
[installer] manually set `allowPrivilegeEscalation` to false
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by ArthurSens — APPROVED** [review]

**Review by jenting — APPROVED** [review]

**Review by easyCZ — APPROVED** [review]

**Comment by geropl** [comment]
@Pothulapati While I agree that this in theory should not affect anything we should definitely test thoroughly. :100:

**Comment by Pothulapati** [comment]
Update: Manual tests are all good i.e workspaces, prebuilds, etc. Waiting on `integration-tests` to work. Seems to be an issue on the pipeline itself. Will update once I have something

**Comment by Pothulapati** [comment]
Ran [IDE](https://werft.gitpod-dev.com/job/gitpod-custom-tar-disallow-escalation-explicitely.1) & [Workspace](https://werft.gitpod-dev.com/job/gitpod-custom-tar-disallow-escalation-explicitely.0) Integration tests separately, and they seem to pass. 👀

**Pull request merged**
