### PR TITLE
[dashboard] Add workspace status indicator color red for failed status

### LINKED ISSUE #3635: Errored workspaces don't use the correct status indicator
### Problem to solve

The new dasboard surfaces errored workspaces without the correct status indicator.

### Proposal

Use `red-600` for the error status indicator.

| BEFORE | AFTER |
|-|-|
| image |  image |

### PR DESCRIPTION
**Pull request by corneliusludmann**
Fixes #3635

### CODE REVIEW

**Review by gtsiolis — COMMENTED** [review]
Hey @corneliusludmann, do you know if there's an easy way to reproduce this erroneous state on the workspaces list?

**Comment by corneliusludmann** [comment]
> Hey @corneliusludmann, do you know if there's an easy way to reproduce this erroneous state on the workspaces list?

Unfortunately, not. :disappointed: 

What you can do is to alter the database to add a failed condition (as JSON content, unfortunately, I don't have a query handy). However, it seems to me that the value of this is pretty limited since you don't really test how a failed workspace behaves.

**Comment by gtsiolis** [comment]
> However, it ...

DEAL. Shall we merge this as is?

**Review by gtsiolis — APPROVED** [review]

**Comment by corneliusludmann** [comment]
I think it should be safe.

**Pull request merged**
