### PR TITLE
#5774: Improve integration with www.gitpod.io around cookies (gitpod-user, )

### LINKED ISSUE #5774: Let the marketing website know who's logged in
In https://github.com/gitpod-io/website/pull/973, we would like to dynamically update the header nav based on the following criteria:
* Anonymous visitor: Display "Sign Up" and "Login" buttons
* Signed in visitor: Display a "Dashboard" button instead of the "Sign Up" and "Login" buttons

There's a `gitpod-user=loggedIn` cookie, but the website sets that for each visitor so that the Gitpod login screen does not show the welcome section.

My suggestion:
1. The marketing website introduces a `gitpod-marketing-website-visited=true` cookie and no longer sets `gitpod-user=loggedIn`.
2. The login screen needs to be updated to look for this cookie ([source code](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/Login.tsx#L38))
3. The marketing website looks for the `gitpod-user=loggedIn` cookie and displays the Dashboard button if the cookie is present.

What do you think?

### PR DESCRIPTION
**Pull request by geropl**
## Description
This PR includes two commits:
 - respect the (upcoming) `gitpod-marketing-website-visited` to hide the "Welcome" screen ([0a8f92c](https://github.com/gitpod-io/gitpod/commit/0a8f92c6e53a3c007113a7839aca207e09f34566))
 - unify the cookie usage and checking in `dashboard` and `server`. The key/value is now `gitpod-user=true`. ([7d4fa6d](https://github.com/gitpod-io/gitpod/commit/7d4fa6d757995e1813cefb332ee9390ea3dd41c1))
 
 I went with the "backend" solution because there we know which domain Gitpod is configured to be run on, and can refresh the session as a side effect.

## Related Issue(s)

Fixes #5774.

### Positive and subdomain
- login to https://gpl-5774-cookies.staging.gitpod-dev.com/workspaces/
- note that there is only one cookie set, which is valid for 1 year
- start a workspace and note that the gitpod-user cookie is send on subdomain requests (those to a workspace) as well

### Negative and `gitpod-marketing-website-visited`
 - remove the `gitpod-user` cookie for this installation
 - re-visit https://gpl-5774-cookies.staging.gitpod-dev.com/login/ and note how you are "redirect" to `/workspaces` but don't get the cookie set (expected).

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** after the PR has been reviewed.

Associated issue: *#5774*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**
- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
/werft run

:point_up: to get the build green :roll_eyes:

**Comment by geropl** [comment]
/werft run

next try...

**Comment by geropl** [comment]
@AlexTugarev Ready for testing.

**Pull request merged**
