### PR TITLE
[dev] Run `gofmt` after Go 1.19 upgrade

### PR DESCRIPTION
**Pull request by andrew-farries**
## Description

Run `gofmt` in multiple source directories. This is necessary after upgrading to Go 1.19 (https://github.com/gitpod-io/gitpod/pull/11891).

As of Go 1.19, `gofmt` now formats `godoc` comments too; see [here](https://go.dev/blog/go1.19).

## Related Issue(s)

Fixes the broken `main` build. See internal discussion [here](https://gitpod.slack.com/archives/C032A46PWR0/p1659956452028219) and [here](https://gitpod.slack.com/archives/C02F19UUW6S/p1659962481445389).

## How to test

Werft is green again.

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Review by vulkoingim — APPROVED** [review]

**Review by andreafalzetti — APPROVED** [review]

**Review by aledbf — APPROVED** [review]

**Review by jankeromnes — APPROVED** [review]
Werft if indeed green again -- thanks! 🎉 Rubber-stamping for team WebApp.

**Comment by andreafalzetti** [comment]
Thanks, @andrew-farries 🙏

**Pull request merged**
