### PR TITLE
Hide the latest ide alert warning on workspace timeout

### LINKED ISSUE #11035: Remove the latest editor release warning alert on workspace time out
### Bug description

Back in https://github.com/gitpod-io/gitpod/pull/8783, we introduced a warning alert to notify users when they've opted in for using the latest editor release for workspaces.

This is also shown on the workspace pages like `Timed Out`, `Stopping`, `Stopped`  which can be inaccurate as the user may have changed the setting in the meantime.

Instead, relying on showing this warning during workspace (re)start could be better.

**When the latest warning should be shown**
- It's before or (re)starting the workspace -> ref to phases https://github.com/gitpod-io/gitpod/blob/9d2d729b378acfc895f4700922b553655e206d86/components/dashboard/src/start/StartPage.tsx#L26-L50
- Workspaces start/stopped failed for some unexpected reasons (i.e. with exit code from supervisor) -> when it shows error https://github.com/gitpod-io/gitpod/blob/9d2d729b378acfc895f4700922b553655e206d86/components/dashboard/src/start/StartPage.tsx#L116

### Steps to reproduce

1. Go to **[/preferences](https://gitpod.io/preferences)** and opt in for the _Latest Release (Unstable)_ option.
2. Open a new workspace and let it time out (~30 min)
3. Notice the on the _Timed Out_ page we're still showing the latest editor release warning alert.

Screenshot 2022-06-30 at 1 34 34 PM

### PR DESCRIPTION
**Pull request by Devansu-Yadav**
## Description

- Removes the latest ide alert warning on the workspace timeout page and only shows it during workspace (re)start.

## Related Issue(s)

Relates #11035

## How to test

- Open workspace in preview env with a **latest** editor https://hide-editor-alert.preview.gitpod-dev.com/workspaces
- Alert should show during starting workspace
- Stop to see if the latest ide alert does not show up
- Open again with a stable editor
- Alert should not show during starting workspace
- Stop should have no alert

## Release Notes

```release-note
Removes the latest ide alert warning on the workspace timeout page
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [x] /werft with-werft
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-slow-database
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by gtsiolis — APPROVED** [review]
UX LGTM, @Devansu-Yadav! 🌮 🌮 

I could verify the warning is no longer present after the workspace timed out. 🏁 

Approving to unblock merging but holding to pass this to @gitpod-io/engineering-webapp to pull the trigger in case there's anything that looks unnecessary and needs a revert or a different approach. 🏓

Looping in also @mustard-mh who recently edited this file to add this warning in the first place.

/hold

**Comment by Devansu-Yadav** [comment]
> Approving to unblock merging but holding to pass this to @gitpod-io/engineering-webapp to pull the trigger in case there's anything that looks unnecessary and needs a revert or a different approach. 🏓
> 
> Looping in also @mustard-mh who recently edited this file to add this warning in the first place.
> 
> /hold

@gtsiolis Any updates whether any changes are required in this PR or not?

**Comment by mustard-mh** [comment]
> Any updates on whether any changes are required in this PR or not?

Hey @Devansu-Yadav 👋  Thanks for your contributions!! 🧡 

I prefer to call the variable `isTimedOut` and check with `showLatestIdeWarning = !isTimedOut && useLatest`

We will need review from @gitpod-io/engineering-webapp as codeowner

pinged in our development pipeline to resolve the preview env problem 🙏

**Comment by Devansu-Yadav** [comment]
> I prefer to call the variable `isTimedOut` and check with `showLatestIdeWarning = !isTimedOut && useLatest`
> 

@mustard-mh That seems much better! Should I go ahead and make this change?

> We will need review from @gitpod-io/engineering-webapp as codeowner
> 

Sure, I'll wait 😄

**Review by easyCZ — APPROVED** [review]

**Comment by mustard-mh** [comment]
> Should I go ahead and make this change?

@Devansu-Yadav  Sure, let's go with it 🚀 

After your changes, I will do the final test in preview env, and then unhold this PR since you get `approve` from WebApp 👍

**Comment by mustard-mh** [comment]
I tested it in preview env, and it worked with `Timed Out` 

But when with phases like `Stopped` `Stopping`, we still got this warning. I will `unhold` this PR and change the related issue's description for them.  @Devansu-Yadav  Thank you for your contribution! 🧡 

|Stopped| Timed Out|
|:-:|:-:|
|image|image|

**Comment by Devansu-Yadav** [comment]
> But when with phases like `Stopped` `Stopping`, we still got this warning. I ~will~ updated `unhold` this PR and change the related issue's description for them. @Devansu-Yadav Thank you for your contribution! 🧡
> 

Ohh okay, but I guess the scope of this issue mostly focussed on the UX where we don't want to show this warning on the `Timed Out` phase, isn't it @gtsiolis? 😅

If needed I could probably address this either in this same PR or maybe open up a separate PR for them..

**Comment by mustard-mh** [comment]
> > But when with phases like `Stopped` `Stopping`, we still got this warning. I ~will~ updated `unhold` this PR and change the related issue's description for them. @Devansu-Yadav Thank you for your contribution! 🧡
> 
> Ohh okay, but I guess the scope of this issue mostly focussed on the UX where we don't want to show this warning on the `Timed Out` phase, isn't it @gtsiolis? 😅
> 
> If needed I could probably address this either in this same PR or maybe open up a separate PR for them..

@Devansu-Yadav  Yep, we can do it separately 👍 , updated the [issue](https://github.com/gitpod-io/gitpod/issues/11035) description you can pick it up if you want and get time 🙏

**Comment by Devansu-Yadav** [comment]
> @Devansu-Yadav Yep, we can do it separately 👍 , updated the [issue](https://github.com/gitpod-io/gitpod/issues/11035) description you can pick it up if you want and get time 🙏

Great, I'll raise a PR for both these phases once this PR is merged 😄

**Comment by gtsiolis** [comment]
Build seems successful. Removing hold.

Thanks @mustard-mh & @iQQBot for trigger the builds[[1](https://werft.gitpod-dev.com/job/gitpod-build-hide-editor-alert.4)][[2](https://werft.gitpod-dev.com/job/gitpod-build-hide-editor-alert.5)].

/unhold

**Comment by gtsiolis** [comment]
For visibility, I'm trying re-triggering the job with what @vulkoingim suggested[[1](https://gitpod.slack.com/archives/C032A46PWR0/p1678380441920199?thread_ts=1678286877.906469&cid=C032A46PWR0)] (internal).

**Comment by vulkoingim** [comment]
Apologies for the back-and-forth on this issue @Devansu-Yadav . Currently we're doing changes around our build/CI systems and there are still some details we haven't smoothed out. I'll get back to you next week, once we have resolved the outstanding issues and will push this through.

**Comment by Devansu-Yadav** [comment]
> Currently we're doing changes around our build/CI systems and there are still some details we haven't smoothed out. I'll get back to you next week, once we have resolved the outstanding issues and will push this through.

@vulkoingim Any updates on this? 😅

**Comment by vulkoingim** [comment]
> > Currently we're doing changes around our build/CI systems and there are still some details we haven't smoothed out. I'll get back to you next week, once we have resolved the outstanding issues and will push this through.
> 
> @vulkoingim Any updates on this? 😅

Apologies for the delay - got it merged just now. Thank you for your contribution! :)

**Pull request merged**
