### PR TITLE
[common-go] Move db models to common-go

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

Moves DB models to common-go, such that they can be used by `public-api` but also `usage`. Ideally, this wouldn't be in a common package but right now this is not possible as we have DB logic spread across multiple systems. Sharing through common-go is better than duplicating, as that would drift quickly.

Changes performed in this PR:
* Move all DB models from `components/usage/pkg/db` into `components/common-go/db`
* Update packages correspondingly
* Update imports correspondingly
* Update leeway BUILD definition such that `common-go` depends on `gitpod-protocol` for starting the DB
* Removes dependency from `usage` on `gitpod-protocol` for starting the DB
* Updates go.mod/go.sum

## Related Issue(s)

Fixes #

## How to test

CI builds

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by easyCZ** [comment]
@mads-hartmann That got me further. Still failed but with application level problems, not build problems - https://werft.gitpod-dev.com/job/gitpod-build-mp-common-move-db-models.13

**Comment by easyCZ** [comment]
@mads-hartmann I've triggered https://werft.gitpod-dev.com/job/gitpod-build-mp-common-move-db-models.15 which should contain a fix for the application level.

**Comment by easyCZ** [comment]
https://werft.gitpod-dev.com/job/gitpod-build-mp-common-move-db-models.15 failed, but I can't tell why. In any case, it looks like that change does unblock this.

**Review by jenting — APPROVED** [review]

**Comment by mads-hartmann** [comment]
@easyCZ @laushinka Looking at the logs from the most recent job I see

```
[components/ws-daemon:docker|DONE] build succeeded
[install/installer:raw-app] level=warning msg="[runner] Can't run linter goanalysis_metalinter: buildir: failed to load package : could not load export data: no export data for \"github.com/gitpod-io/gitpod/usage/pkg/db\""
[install/installer:raw-app] level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: buildir: failed to load package : could not load export data: no export data for \"github.com/gitpod-io/gitpod/usage/pkg/db\"\n\n"
[install/installer:raw-app] package build failed
[install/installer:raw-app] Reason: exit status 3
[install/installer:raw-app|FAIL] exit status 3
☁️  uploading build artifacts to remote cache
build failed
Reason: build failed
time="2022-11-16T15:50:23Z" level=fatal msg="build failed"
```

That might be worth looking into. In the mean time I will try to get the fix into main - I just have to talk to Chris to understand if the [change](https://github.com/gitpod-io/leeway/compare/mads-dont-check-ephmeral-pkgs-in-transitive-deps?expand=1) is desirable.

**Comment by laushinka** [comment]
> That might be worth looking into.

Taking a look!

**Comment by csweichel** [comment]
/hold 

more discussion needed

**Comment by csweichel** [comment]
This change repeats the `gitpod-protocol` mistake: 
- it turns common-go into more of a kitchen sink than it currently is
- it muddles the dependencies on shared state (the DB)

There are different ways to move forward:
- introduce something like a `go-db` component
- finally split common-go into individual modules

**Comment by laushinka** [comment]
> * introduce something like a `go-db` component

After a discussion, we will go this route. I will work on the changes.

**Comment by easyCZ** [comment]
> introduce something like a go-db component
> finally split common-go into individual modules

Yeah that's also a perfectly viable option.

**Review by svenefftinge — APPROVED** [review]

**Comment by easyCZ** [comment]
Moving to draft, as we'll be adding this to a new module.

**Comment by laushinka** [comment]
Closing this, as it is continued in https://github.com/gitpod-io/gitpod/pull/14770.

**Pull request closed without merging**
