### PR TITLE
Add support for ephemeral storage

### PR DESCRIPTION
**Pull request by aledbf**
## Description

Add new EphemeralStorage field to use ephemeral-storage feature in workspaces

## Release Notes
```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **aledbf** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)**
- **[installer/pkg/components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-manager/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **aledbf** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)**
- **[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)**
- **[installer/pkg/components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-manager/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by csweichel** [comment]
That was an unfortunate confusion. Thanks for clearing this up.

/approve no-issue
/lgtm

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 89a65131c218c16382042bc837eb6dbc5aca203a</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7144#issuecomment-989722363" title="Approved">csweichel</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/7144#issuecomment-989722363" title="Approved">csweichel</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [csweichel]
- ~~[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)~~ [csweichel]
- ~~[installer/pkg/components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-manager/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **aledbf** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)**
- **[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)**
- **[installer/pkg/components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-manager/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by csweichel** [comment]
Was a bit too quick there. The fixture tests don't pass:
```
=== RUN   TestModifyFinalizer/add_finalizer
    annotations_test.go:122: cannot create test pod; this is a bug in the unit test itself: Pod "ws-foo" is invalid: spec.containers[0].resources.requests[storage]: Invalid value: "storage": must be a standard resource for containers
=== RUN   TestModifyFinalizer/add_finalizer_noop
    annotations_test.go:122: cannot create test pod; this is a bug in the unit test itself: Pod "ws-foo" is invalid: spec.containers[0].resources.requests[storage]: Invalid value: "storage": must be a standard resource for containers
=== RUN   TestModifyFinalizer/remove_finalizer
    annotations_test.go:122: cannot create test pod; this is a bug in the unit test itself: Pod "ws-foo" is invalid: spec.containers[0].resources.requests[storage]: Invalid value: "storage": must be a standard resource for containers
=== RUN   TestModifyFinalizer/remove_finalizer_noop
    annotations_test.go:122: cannot create test pod; this is a bug in the unit test itself: Pod "ws-foo" is invalid: spec.containers[0].resources.requests[storage]: Invalid value: "storage": must be a standard 
```

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: c19cde88dc2c83d3e26871735eea2a60daf76fed</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7144#issuecomment-989811418" title="Approved">csweichel</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/7144#issuecomment-989811418" title="Approved">csweichel</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [csweichel]
- ~~[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)~~ [csweichel]
- ~~[installer/pkg/components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/ws-manager/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
