### PR TITLE
[server] allow unsubscribe from onboarding emails

### LINKED ISSUE #5672: Create email unsubscribe link for onboarding emails
The unsubscribe link is necessary for users to unsubscribe from emails with a single click. This is required according to GDPR. We already have email unsubscribe links for DevX and Changelog. And we'd need another link for the onboarding email. When clicking on the unsubscribe link the notification preferences need to be updated and the updates need to be forwarded to customer.io.

The format would be something like this:
` https://gitpod.io/api/unsubscribe?email=christin@gitpod.io&type=onboarding` 

cc @laushinka

### PR DESCRIPTION
**Pull request by JanKoehnlein**
## Description
Added a route to allow users to unsubscribe from onboarding emails

## Related Issue(s)
Fixes #5672

## Release Notes
```release-note
allow users to unsubscribe from onboarding emails
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jankoehnlein** after the PR has been reviewed.

Associated issue: *#5672*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by laushinka — APPROVED** [review]

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: a25085b36ce3ea6288f62a6af62502cbf9ffb344</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5682#pullrequestreview-752989424" title="Approved">laushinka</a>*

Associated issue: *#5672*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [laushinka]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
