### PR TITLE
Update Gateway Plugin to work on JetBrains Gateway 2022.2

### PR DESCRIPTION
**Pull request by felladrin**
## Description

Update JetBrains Gateway Plugin to work on Gateway 2022.2

## Related Issue(s)

None.

## How to test

- Downlaod the JetBrains Gateway 2022.2 EAP version from one of these links:
  - [JetBrainsGateway-222.2270.16-aarch64.dmg](https://download.jetbrains.com/idea/gateway/JetBrainsGateway-222.2270.16-aarch64.dmg)
  - [JetBrainsGateway-222.2270.16.dmg](https://download.jetbrains.com/idea/gateway/JetBrainsGateway-222.2270.16.dmg)
  - [JetBrainsGateway-222.2270.16.exe](https://download.jetbrains.com/idea/gateway/JetBrainsGateway-222.2270.16.exe)
  - [JetBrainsGateway-222.2270.16.tar.gz](https://download.jetbrains.com/idea/gateway/JetBrainsGateway-222.2270.16.tar.gz)
- Download [this Dev version of the Gateway Plugin](https://plugins.jetbrains.com/plugin/18438-gitpod-gateway/versions/Dev/177112) and install it on the EAP Gateway, using the "Install Plugin from Disk" option in Preferences.
- Confirm if the plugin is working fine on **JetBrains Gateway 2022.2**.
  image
- Confirm also if the plugin is still working fine on **JetBrains Gateway 2022.1**.
  image

## Release Notes

```release-note
Add support for JetBrains Gateway 2022.2
```

## Documentation

None.

### CODE REVIEW

**Comment by felladrin** [comment]
We need to wait for a fix [in Gradle IntelliJ Plugin](https://github.com/JetBrains/gradle-intellij-plugin/issues/997#issuecomment-1132971959) before continuing the development of this PR.

**Comment by felladrin** [comment]
JetBrains team fixed it on v1.6.0 of the Gradle Plugin.

https://github.com/gitpod-io/gitpod/blob/2864738c170297cda0c98a08c468d6247460b9e8/components/ide/jetbrains/gateway-plugin/build.gradle.kts#L17

So the PR is now ready for review.

**Review by mustard-mh — APPROVED** [review]
lgtm

Both work fine with me if we define `works find` as connect success and code sync ok

image

image

**Comment by mustard-mh** [comment]
Maybe we can define `works fine` in PR description next time? cc @felladrin

**Comment by felladrin** [comment]
> Maybe we can define `works fine` in PR description next time? cc @felladrin

Good point, @mustard-mh! I should definitely define the parameters for considering it working fine. I'll describe it better next time!

**Pull request merged**
