### PR TITLE
[jetbrains] repo plugins support

### PR DESCRIPTION
**Pull request by akosyakov**
## Description

This PR allows a user to specify JB plugins in .gitpod.yml, for instance: https://github.com/akosyakov/spring-petclinic/blob/8b4a927182ba75656c5d1fc3931482ea548206bd/.gitpod.yml#L33-L35

Unfortunately it is turned out that stable version of JB backend cannot support it. So this PR additionally introduces conditional building of JB backend plugin against stable and latest versions. For stable version support of repo plugins is disabled, and only enabled for EAP.

## Related Issue(s)

fix https://github.com/gitpod-io/gitpod/issues/6508

#### Stable

- Make sure to **disable** latest version in settings: https://ak-jb-repo-plugins.staging.gitpod-dev.com/preferences
- Start a workspace on a repo with JB plugins with IntelliJ: https://ak-jb-repo-plugins.staging.gitpod-dev.com#referrer:jetbrains-gateway/https://github.com/akosyakov/spring-petclinic
- The client should start, but plugins won't be installed, since 2021.3 does not support headless mode properly and cannot install them from cli.

#### Latest
- Make sure to **enable** latest version in settings: https://ak-jb-repo-plugins.staging.gitpod-dev.com/preferences
- Start a workspace on a repo with JB plugins with IntelliJ: https://ak-jb-repo-plugins.staging.gitpod-dev.com#referrer:jetbrains-gateway/https://github.com/akosyakov/spring-petclinic
- The client should start and plugin should be installed.

## Release Notes

```release-note
Allow to configure JetBrains plugins in .gitpod.yml
```

### CODE REVIEW

**Comment by akosyakov** [comment]
I tried with EAP. It is possible to install plugins, but some plugins can freeze the backend startup, so we need a strategy to troubleshoot if we are going forward with it.

**Review by felladrin — APPROVED** [review]
Code is clear and the tests ran accordingly to the description.

✅ Test Case 1: Plugin is not available on Stable Backend IDE.

Screenshot 2022-04-06 at 14 14 30

Screenshot 2022-04-06 at 14 43 49

✅ Test Case 2: Plugin is available on EAP Backend IDE.

Screenshot 2022-04-06 at 14 19 48

Screenshot 2022-04-06 at 14 43 59

**Review by nandajavarma — APPROVED** [review]

**Review by geropl — APPROVED** [review]
WebApp changes look good!

small and kind nudge: the smaller the PR, and number of teams involved, the easier the review - and quicker the approval. :lotus_position:

**Pull request merged**
