### PR TITLE
Remove old headless log infrastructure

### LINKED ISSUE #4911: Remove old headless log remnants
We still have some leftovers from the the old headless log infrastructure in place, e.g. in the ws-manager protocol, or bride when we transfer the log output to messagebus.

We should remove those old code paths.

### PR DESCRIPTION
**Pull request by csweichel**
This PR removes the last leftovers of the old headless log infrastructure.

fixes #4911

Noteworthy:
- there's a protocol change on ws-manager's `SubscriptionResponse` which removes the `oneof`. To my understanding that doesn't affect what's on the wire, i.e. the protocol should remain backwards compatible. That's because neither numbers nor types of the fields change.

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4915#" title="Author self-approved">csweichel</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankeromnes** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankeromnes` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**
- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [csweichel]
- ~~[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)~~ [csweichel]
- **[components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/OWNERS)**
- ~~[components/ws-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-proxy/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: a9e98419e7932402892aaa5ac9a9d0e62311eabb</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4915#issuecomment-885661859" title="LGTM">aledbf</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4915#" title="Author self-approved">csweichel</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankeromnes** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankeromnes` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**
- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [aledbf,csweichel]
- ~~[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)~~ [aledbf,csweichel]
- **[components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/OWNERS)**
- ~~[components/ws-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-proxy/OWNERS)~~ [aledbf,csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
_Maybe_ unrelated, but I'm not able to start a prebuild workspace on https://csweichel-remove-old-headless-log-4911.staging.gitpod-dev.com/#prebuild/https://github.com/gitpod-io/gitpod/tree/gpl/test-prebuild 

The image build pod does not terminate. Logs read:
```
{"command":"{\nsudo -E /app/bob build\n}; exit","level":"info","message":"task terminal has been closed","pid":29,"serviceContext":{"service":"supervisor","version":""},"severity":"INFO","terminal":"4c016f29-13ce-49e0-89b2-f6982037b25f","time":"2021-07-26T08:16:36Z"}
{"component":"workspace","level":"info","message":"","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","taskLogMsg":{"type":"workspaceTaskOutput","data":"🚛 uploading prebuilt workspace"},"time":"2021-07-26T08:16:36Z"}
{"component":"workspace","level":"info","message":"","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","taskLogMsg":{"type":"workspaceTaskDone","data":""},"time":"2021-07-26T08:16:36Z"}
{"alias":"4c016f29-13ce-49e0-89b2-f6982037b25f","level":"info","message":"terminal client left","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","time":"2021-07-26T08:16:36Z"}
{"component":"workspace","level":"info","message":"","pid":29,"serviceContext":{"service":"supervisor","version":""},"severity":"INFO","taskLogMsg":{"type":"workspaceTaskOutput","data":""},"time":"2021-07-26T08:16:36Z"}
{"level":"info","message":"received SIGTERM (or shutdown) - tearing down","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","time":"2021-07-26T08:16:36Z"}
{"level":"debug","message":"tasksManager shutdown","serviceContext":{"service":"supervisor","version":""},"severity":"DEBUG","time":"2021-07-26T08:16:36Z"}
{"level":"info","message":"shutting down API endpoint","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","time":"2021-07-26T08:16:36Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"context canceled","level":"error","message":"cannot provide Docker activation socket","serviceContext":{"service":"supervisor","version":""},"severity":"ERROR","time":"2021-07-26T08:16:36Z"}
{"level":"debug","message":"startAPIEndpoint shutdown","serviceContext":{"service":"supervisor","version":""},"severity":"DEBUG","time":"2021-07-26T08:16:36Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"wait: no child processes","level":"warning","message":"cannot terminate child process","pid":40,"serviceContext":{"service":"supervisor","version":""},"severity":"WARNING","time":"2021-07-26T08:16:36Z"}
{"exitCode":0,"level":"debug","message":"supervisor exit","serviceContext":{"service":"supervisor","version":""},"severity":"DEBUG","time":"2021-07-26T08:16:36Z"}
```

**Comment by geropl** [comment]
Ok, now it started. :shrug: The image build hang for 14-20 mins, but somehow finished, and the prebuild ran flawlessly afterwards.

The second run worked flawlessly.

**Review by geropl — APPROVED** [review]
Tested, works. The hickups are related to image-builder mk3, not this PR.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4915#issuecomment-885661859" title="LGTM">aledbf</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4915#" title="Author self-approved">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4915#pullrequestreview-714590698" title="Approved">geropl</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [geropl]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [geropl]
- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [aledbf,csweichel]
- ~~[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)~~ [aledbf,csweichel]
- ~~[components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/OWNERS)~~ [geropl]
- ~~[components/ws-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-proxy/OWNERS)~~ [aledbf,csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
@csweichel Makes sense to override codecov/patch I assume...?

**Pull request merged**
