### PR TITLE
Improve colors used for labels and headings on dashboard integrations…

### LINKED ISSUE #6762: Improve colors used for labels and headings on dashboard integrations for the dark theme
### Problem to solve

The colors used on the `/integrations` page within the dashboard do not follow the pattern used in `/workspaces` list.

### Proposal

Change label and heading colors for the dark theme in `/integrations` page.

| BEFORE | AFTER |
|-|-|
|  Screenshot 2021-11-17 at 11 24 31 PM (2) | Screenshot 2021-11-17 at 11 40 36 PM (2) |

The following changes could suffice:

```diff
diff --git a/components/dashboard/src/settings/Integrations.tsx b/components/dashboard/src/settings/Integrations.tsx
index d0a33f39f..7dc77e760 100644
--- a/components/dashboard/src/settings/Integrations.tsx
+++ b/components/dashboard/src/settings/Integrations.tsx
@@ -291,15 +291,15 @@ function GitProviders() {
                     </ItemFieldIcon>
                     <ItemField className="w-4/12 xl:w-3/12 flex flex-col">
                         <span className="my-auto font-medium truncate overflow-ellipsis">{ap.authProviderType}</span>
-                        <span className="text-sm my-auto text-gray-400 truncate overflow-ellipsis">{ap.host}</span>
+                        <span className="text-sm my-auto text-gray-400 truncate overflow-ellipsis dark:text-gray-500">{ap.host}</span>
                     </ItemField>
                     <ItemField className="w-6/12 xl:w-3/12 flex flex-col">
-                        <span className="my-auto truncate text-gray-500 overflow-ellipsis">{getUsername(ap.authProviderId) || "–"}</span>
-                        <span className="text-sm my-auto text-gray-400">Username</span>
+                        <span className="my-auto truncate text-gray-500 overflow-ellipsis dark:text-gray-400">{getUsername(ap.authProviderId) || "–"}</span>
+                        <span className="text-sm my-auto text-gray-400 dark:text-gray-500">Username</span>
                     </ItemField>
                     <ItemField className="hidden xl:w-5/12 xl:flex xl:flex-col">
-                        <span className="my-auto truncate text-gray-500 overflow-ellipsis">{getPermissions(ap.authProviderId)?.join(", ") || "–"}</span>
-                        <span className="text-sm my-auto text-gray-400">Permissions</span>
+                        <span className="my-auto truncate text-gray-500 overflow-ellipsis dark:text-gray-400">{getPermissions(ap.authProviderId)?.join(", ") || "–"}</span>
+                        <span className="text-sm my-auto text-gray-400 dark:text-gray-500">Permissions</span>
                     </ItemField>
                     <ItemFieldContextMenu menuEntries={gitProviderMenu(ap)} />
                 </Item>
@@ -375,7 +375,7 @@ function GitIntegrations() {
         <div className="flex items-start sm:justify-between mb-2">
             <div>
                 <h3>Git Integrations</h3>
-                <h2 className="text-gray-500">Manage Git integrations for GitLab or GitHub self-hosted instances.</h2>
+                <h2>Manage Git integrations for GitLab or GitHub self-hosted instances.</h2>
             </div>
             {providers.length !== 0
                 ?
```

### PR DESCRIPTION
**Pull request by pri1311**
… for the dark theme

## Description
Improve colors used for labels and headings on dashboard integrations for the dark theme. Changes mentioned in the PR were made.

## Related Issue(s)
Fixes #6762 

## Release Notes
```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
@pri1311: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **alextugarev** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @alextugarev` in a comment when ready.

Associated issue: *#6762*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by gtsiolis — APPROVED** [review]
Thanks for contributing, @pri1311! 🌟 

Changes look great! 🏁 

I've also triggered a preview environment (deployment) where you can see a deployed version with the changes in this PR, see https://github.com/gitpod-io/gitpod/pull/7068#issuecomment-987195251. 🌔 

You'll also need to sign a Contributor License Agreement (CLA)[[1](https://en.wikipedia.org/wiki/Contributor_License_Agreement)] once before merging your first contribution. Looping in @meysholdt to reach out about the CLA. 🏓 

Approving but holding until the CLA process is complete.

/hold

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: f26cb2bade94a899c1f7c0bdf19780f6f6099a42</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7068#pullrequestreview-824472205" title="Approved">gtsiolis</a>*

Associated issue: *#6762*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [gtsiolis]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by meysholdt** [comment]
Hi Priya,

I've sent you a CLA via DocuSign, can you please sign it so that we can merge this PR? 
thank you!

**Comment by pri1311** [comment]
Hey @meysholdt 
Have signed the document.

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by gtsiolis** [comment]
Rebased and shortened the commit message. Removing hold.

/hold cancel

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: f26cb2bade94a899c1f7c0bdf19780f6f6099a42</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7068#issuecomment-1001668099" title="LGTM">gtsiolis</a>*

Associated issue: *#6762*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)~~ [gtsiolis]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
