### PR TITLE
[test] Update integration tests to work with installer

### LINKED ISSUE #6604: [test] 9 tests fail with "error parsing DB_PORT" for self-hosted
### Bug description

We'll need to [extend the test framework](https://github.com/gitpod-io/gitpod/blob/a9dca2a2bf7f1562ee90e53b038d63f9cbba824f/test/pkg/integration/apis.go#L432) as the DB port comes from a secret now.

### Steps to reproduce

[Follow these steps](https://github.com/gitpod-io/gitpod/tree/main/test#manually-against-a-kubernetes-cluster) against a self-hosted installation of Gitpod.

### Workspace affected

n/a

### Expected behavior

The tests should pass.

### Example repository

_No response_

### Anything else?

Will require a cluster in GCP to do testing. 

1 test was failing due to `minio.default.svc.cluster.local: no such host`. This may have been resolved in a recent commit, but double check. If not, see if it can be resolved.

4 tests were failing (even with the saas) due to `cannot start workspace`. This may have been resolved in a recent commit, but double check.

The failures were found in #6518.

### PR DESCRIPTION
**Pull request by kylos101**
## Description

Update integration tests to work with installer (which uses a secret to store database connectivity details).

## Related Issue(s)

Fixes #6604

## How to test

[Run this and have tests pass.](https://github.com/gitpod-io/gitpod/tree/main/test#manually-against-a-kubernetes-cluster)

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankoehnlein** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankoehnlein` in a comment when ready.

Associated issue: *#6604*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by kylos101** [comment]
Here is the current status for running the tests against my GKE self hosted install:
1. We retrieve the secret value for `mysql`, and we're definitely connecting, `TestBuiltinUserExists` passes now.
2. Various goroutine errors are thrown with stack traces, these appear to be related to retries for connections requiring TLS.
3. My particular GKE cluster is unable to provision a certificate from Lets Encrypt for the domain I am testing with, hence the issue with (2).

Next steps:
1. Reach out to the team for help with my cluster's TLS & debug tests against the GKE self hosted install once resolved
2. Run the integration tests against the core-dev namespace for this branch, to assert tests still work with the ENV VAR

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jankeromnes**, **mrsimonemms** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jankeromnes @mrsimonemms` in a comment when ready.

Associated issue: *#6604*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/dashboard/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/OWNERS)**
- **[components/ee/db-sync/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/db-sync/OWNERS)**
- **[components/ee/payment-endpoint/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/payment-endpoint/OWNERS)**
- **[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)**
- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**
- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by kylos101** [comment]
Will create a new PR with a clean branch.

**Pull request closed without merging**
