### PR TITLE
Last tidying around  https://github.com/gitpod-io/gitpod/issues/12964

### PR DESCRIPTION
**Pull request by mrzarquon**
Typos in policy declarations

```release-note
[AWS Infra] Terraform code updated to create correct policies for S3 buckets
```

## Description
Third times a charm?

### CODE REVIEW

**Review by MrSimonEmms — APPROVED** [review]
LGTM

**Comment by sagor999** [comment]
/hold
build is failing and blocking tide

**Comment by MrSimonEmms** [comment]
@sagor999 rerunning the Werft build and it now passes the test. It looks like the Yarn package failed to publish (not changed as part of this PR)

/unhold

**Pull request merged**
