### PR TITLE
werft/VM: Use different auth-provider secret for previews on Harvester VMs

### PR DESCRIPTION
**Pull request by ArthurSens**
## Description

This PR was built on top of https://github.com/gitpod-io/gitpod/pull/7505, just so I can see it working end to end.

It changes the auth-provider secret in case the preview environment is running on Harvester VMs. The secret `preview-envs-authproviders-harvester` was created manually.

It also adds an additional license to the werft job's pod. It was necessary because our licenses are bound to a specific domain, and our previews running on harvester are using a new domain

## Related Issue(s)

Fixes https://github.com/gitpod-io/ops/issues/652

## How to test

Start a new werft job with the `with-vm=true` annotation. 

The preview environment should have oauth configured.

## Release Notes

```release-note
NONE
```

/werft with-vm=true

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **iqqbot** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @iqqbot` in a comment when ready.

Associated issue: *#652*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/as/VM-stability/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **iqqbot** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @iqqbot` in a comment when ready.

Associated issue: *#652*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by meysholdt — APPROVED** [review]

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 6d49eb7b4156c1bc196e025b1d7b970cfee4a0c6</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7528#pullrequestreview-849143219" title="Approved">meysholdt</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **iqqbot** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @iqqbot` in a comment when ready.

Associated issue: *#652*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ArthurSens** [comment]
We have access to the dashboard! 🎉 

image

**Review by mads-hartmann — APPROVED** [review]
Awesome 🎉  Thanks for the detailed PR description on why the license was needed.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 00b0028773cc047c5ee0ca532321205e2baa1d93</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7528#pullrequestreview-850213809" title="Approved">mads-hartmann</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7528#pullrequestreview-849143219" title="Approved">meysholdt</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **iqqbot** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @iqqbot` in a comment when ready.

Associated issue: *#652*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7528#pullrequestreview-850213809" title="Approved">mads-hartmann</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7528#pullrequestreview-849143219" title="Approved">meysholdt</a>*

Associated issue: *#652*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
