### PR TITLE
[supervisor] Start IDE in a terminal

### PR DESCRIPTION
**Pull request by csweichel**
This PR starts the IDE in a terminal to allow for easier debugging.

### How to test
1. `/.supervisor/supervisor terminal list`

### CODE REVIEW

**Comment by akosyakov** [comment]
It did not for me for this repo: https://github.com/TypeFox/monaco-languageclient
```
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"cannot start PTY:\n    github.com/gitpod-io/gitpod/supervisor/pkg/terminal.(*Mux).Start\n        github.com/gitpod-io/gitpod/supervisor/pkg/terminal/terminal.go:57\n  - fork/exec /ide/startup.sh: operation not permitted","level":"fatal","message":"IDE failed to start","serviceContext":{"service":"supervisor","version":""},"severity":"CRITICAL","time":"2021-04-24T19:14:08Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"exit status 1","level":"error","message":"unexpected exit","ring":1,"serviceContext":{"service":"workspacekit","version":""},"severity":"ERROR","time":"2021-04-24T19:14:08Z"}
```

Running IDE as a terminal still ensures that we see IDE logs in GCP?

**Comment by svenefftinge** [comment]
We discussed allowing connecting to the supervisor tasks from the local companion app. Would be good to mark system tasks somehow so they are not listed by default.

**Comment by csweichel** [comment]
> We discussed allowing connecting to the supervisor tasks from the local companion app. Would be good to mark system tasks somehow so they are not listed by default.

💯 right now they get a `supervisor: true` annotation (see [here](https://github.com/gitpod-io/gitpod/pull/4049/files#diff-38855a295b4f047d2f93ba019f506a7d51edef9c2aed4c47cfcc2f0a01bf3835R421-R423))

**Pull request closed without merging**
