### PR TITLE
[bugfix] Add database fields to support storage of cluster and project specific details

### PR DESCRIPTION
**Pull request by princerachit**
## What
This is the first PR for the series of changes that will be required to fix https://github.com/gitpod-io/gitpod/issues/4166.

### Changes
1. Update Readme file for typeform changes
1. Add migration script to add `clusterName` and `projectName` fields to `d_b_workspace_instance` table
1. Add `clusterName` and `projectName` to the `WorkspaceInstance` interface and `namespaceName` to the `WorkspaceInstanceStatus` interface
1. Update tests to include the newly added fields
1. Update WorkspaceStarter to have default empty string value while creating the workspace

## Testing
Manually tested by creating a workspace in the werft preview deployment. I could see empty values for the fields in the database.

## Impact
This should not break anything as the fields are not used anywhere other than while creating a workspace.
Database performance impact: TODO

### CODE REVIEW

**Comment by aledbf** [comment]
@princerachit  please rebase. The fix for the failure was merged minutes ago

**Comment by csweichel** [comment]
We have a good part of this information in the database already, specifically each `d_b_workspace_instance` has an inaptly named `region` field which points to the cluster where the instance is running.

If we added more metadata to the corresponding `d_b_workspace_cluster` entries (e.g. generic `annotations`)  then we could provide these links without needing to introduce additional (possibly redundant) data on `d_b_workspace_instance`.

**Comment by princerachit** [comment]
Hey Chris, thanks for pointing out the region field. Whereas this PR was to fix only the pluggable cluster admin links issue, I now have a separate question about database calls.

1. Do we prefer to update the models/create new views to reduce database calls? e.g. if I want both the workspace instance details and the information about the cluster, as evident in the current scenario, I would require either run a join query and have a corresponding model in my code OR I can run two db queries for each table.
2. Based on what I understand, we don't keep stale cluster information in the d_b_workspace cluster, right? Why don't we do that? If we clear the old cluster entries, we essentially lose information about where this workspace ran. I am not sure if region field provides that information clearly


Based on what you suggested above do you think this is ok:
1. Add column `annotations` of type JSON to `d_b_workspace` cluster
2. Create a model with the following structure to map to the above field:
```typescript
interface annotations {
  projectName?: string
  clusterName?: string
}

```
3. Above interface would be modified as and when we deem more fields necessary

**Comment by princerachit** [comment]
I have described in detail how I am storing the [cluster urls in this comment on the original issue](https://github.com/gitpod-io/gitpod/issues/4166#issuecomment-847638186)

**Pull request closed without merging**
