### PR TITLE
[dev] reverted images for werft

### PR DESCRIPTION
**Pull request by JanKoehnlein**

### CODE REVIEW

**Comment by JanKoehnlein** [comment]
See https://gitpod.slack.com/archives/C01KGM9AW4W/p1622732913357400 (internal discussion)

**Comment by JanKoehnlein** [comment]
Seems like you cannot have different images for werft and dev, as it makes the `gitpod-config_test.go` fail.

**Review by aledbf — APPROVED** [review]
LGTM

**Pull request merged**
