### PR TITLE
Add `toxic-config` component to configure Toxiproxy instances with latency toxics

### PR DESCRIPTION
**Pull request by andrew-farries**
## Description

As part of #9198 we will run a [Toxiproxy](https://github.com/Shopify/toxiproxy/) instance in the application cluster to allow us to simulate a high-latency connection to the Gitpod database. Installation and configuration of this Toxiproxy instance is done in some preceding PRs:

* https://github.com/gitpod-io/gitpod/pull/14359
* https://github.com/gitpod-io/gitpod/pull/14388
* https://github.com/gitpod-io/gitpod/pull/14423
* https://github.com/gitpod-io/gitpod/pull/14430
* https://github.com/gitpod-io/gitpod/pull/14437

Toxiproxy allows declarative configuration of proxies via a config file, but configuration of [toxics](https://github.com/Shopify/toxiproxy/blob/master/README.md#toxics) has to be done dynamically while Toxiproxy is running.

This PR adds a new component `toxic-config`, intended to run as a sidecar container in a Kubernetes pod alongside Toxiproxy, that configures a given proxy with a [latency toxic](https://github.com/Shopify/toxiproxy/blob/master/README.md#latency).

For example, with a Toxiproxy instance running on `localhost:8474` with a proxy called `mysql` configured:

```
go run . --proxy mysql --latency=1000 --jitter=250
```

will configure the `mysql` proxy with a [latency toxic](https://github.com/Shopify/toxiproxy#latency) with `latency` and `jitter` set to the provided values.

A later PR will run this process as a sidecar container in the Toxiproxy pod.

## Related Issue(s)

Part of #9198

## How to test

* Port forward to the `toxiproxy` service in the preview environment:
```
kubectl port-forward svc/toxiproxy 8474:8474
```

* Run `toxic-config` against the `toxiproxy` instance:

```
cd components/toxic-config
go run . --proxy mysql --latency=1000 --jitter=250
```

* See that the `mysql` proxy now has a `latency` toxic configured.
```
docker run --rm --net=host --entrypoint="/toxiproxy-cli" -it ghcr.io/shopify/toxiproxy inspect mysql
```

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-slow-database
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by easyCZ** [comment]
Thanks for the change. Why does this need to be configured in go code rather than a configuration file? I feel like I'm missing  a piece here.

**Comment by andrew-farries** [comment]
Toxiproxy allows declarative configuration of proxies via a config file, but configuration of [toxics](https://github.com/Shopify/toxiproxy/blob/master/README.md#toxics) has to be done dynamically while Toxiproxy is running. The ability to configure toxics via the config file is a requested feature (https://github.com/Shopify/toxiproxy/issues/447), but currently unimplemented. 

I think this stems from our use of Toxiproxy in a way that falls slightly outside it's intended use case of automated tests; in that case the toxics are much more dynamic and are added/removed via tests. For our use case, we want to configure one toxic and then leave it in place forever, for which a config file is more suitable.

FWIW, we do configure Toxiproxy with a `mysql` proxy via a config file:

https://github.com/gitpod-io/gitpod/blob/main/install/installer/pkg/components/toxiproxy/configmap.go

it would be nice to have the latency toxic configured in there too, but that isn't possible.

**Comment by andrew-farries** [comment]
Longer term, we could make the change upstream to allow toxic configuration via config file. That would allow us to delete this `toxic-config` sidecar.

**Comment by easyCZ** [comment]
@andrew-farries Thanks, that makes more sense now.

**Review by easyCZ — APPROVED** [review]

**Pull request merged**
