### PR TITLE
Testing latest gitpod-io/main

### PR DESCRIPTION
**Pull request by shaal**
Testing latest Gitpod

### CODE REVIEW

**Comment by shaal** [comment]
Thank you @gtsiolis 

Do you know for how long that environment is going to be up and running? does it get wiped automatically at some point?

**Comment by gtsiolis** [comment]
It should be up for a couple of hours before it gets wiped @shaal. ⏱️

**Comment by shaal** [comment]
I tried testing repos `prebuild`, using the latest gitpod environment:
`https://main-fork.staging.gitpod-dev.com/#prebuild/https://github.com/shaal/ddev-gitpod/pull/18`
It seems to start rebuilding, although the display is different than the current Gitpod where I could see the commands that are running as part of prebuild.
Then it stops the workspace and display a button to start the workspace again. When I click to start the workspace it gets stuck.

**Comment by jankeromnes** [comment]
Many thanks for testing this @shaal! 💯 

> I tried testing repos `prebuild`, using the latest gitpod environment:
> `https://main-fork.staging.gitpod-dev.com/#prebuild/https://github.com/shaal/ddev-gitpod/pull/18`
> It seems to start rebuilding, although the display is different than the current Gitpod where I could see the commands that are running as part of prebuild.

Indeed, the (pre)build logs view wasn't implemented yet, but I'm about to merge https://github.com/gitpod-io/gitpod/pull/3560 which adds them.

With this latest change, you should be able to view the prebuild logs in progress (both immediately in the `/#prebuild/` page, and if you try to open a repository while a prebuild was already in progress).

> Then it stops the workspace and display a button to start the workspace again. When I click to start the workspace it gets stuck.

This sounds like a bug with headless workspaces. Maybe it's already fixed in the aforementioned PR (I fixed a few things related to headless workspaces in the start page), but if not we should fix this too.

**Comment by shaal** [comment]
Can we have a stable url for staging server that is always available with the latest changes of Gitpod repo?
Otherwise I need to call the bot, and it will tell me I'm not authorized again... 🙄

**Comment by gtsiolis** [comment]
> Can we have a stable url for staging server that is always available with the latest changes of Gitpod repo?

We do have a staging server but our current release strategy does not continuously deploy latest changes from the repository. In the future, we could change this.

Also, the preview environment triggered from this PR is also deployed on a fixed domain. We'll have to trigger another deployment to get this up and running.

@shaal Let me know if you push any new changes that you need to verify in a preview environment before requesting a code review. 🏀

**Comment by jankeromnes** [comment]
> Can we have a stable url for staging server that is always available with the latest changes of Gitpod repo?

Actually there is https://main.staging.gitpod-dev.com/ which is always automatically deployed from the `main` branch here.

**Comment by shaal** [comment]
@jankeromnes I find https://main.staging.gitpod-dev.com to be down most of the time.
Is it possible to keep it up somehow?

**Comment by jankeromnes** [comment]
@shaal Unfortunately, Werft deployments are garbage-collected quite aggressively: Any temporary deployment that isn't "used"* for 2 hours gets dismantled by "sweeper".

*(I think "used" means: some events are happening, e.g. workspaces are created or started, DB values are changed, etc.)

I'm not sure what the right solution is here. E.g., disable sweeper for `main`? But then we'd have one deployment constantly consuming / taking up resources, even if it's unused for long periods of time. I think a better solution would be a way to grant trusted community members Werft rights.

**Comment by shaal** [comment]
@jankeromnes yes please, for granting trusted community members Werft rights.

Otherwise, I'm chasing currently available staging builds in the wild.

I am testing a repo on one of these staging builds, I noticed that after I am stopping the workspace, the screen that offers starting the workspace again - the link points to`https://gitpod-dev.com/start/#pink-bug-ekkp9xyd`. It seems that it's hardcoded `gitpod-dev.com`, instead of running the workspace on the specific build I was testing with (`https://se-cache-extension-resolution.staging.gitpod-dev.com/`)

So instead, I go to the link that I know will start the workspace again -
https://se-cache-extension-resolution.staging.gitpod-dev.com/start/#copper-junglefowl-feok9gdx
or
https://copper-junglefowl-feok9gdx.ws-dev.se-cache-extension-resolution.staging.gitpod-dev.com/

But as you can see in the screenshot, it wouldn't restart the workspace.
Another small issue, in the headline `Oh, no! Something went wrong!1`, the last digit `1` should probably not be there. 

image

**Comment by aledbf** [comment]
@shaal can we close this PR?

**Comment by shaal** [comment]
@aledbf This PR was created to find the way to contribute back to Gitpod
(Because I have no way to run it and test it)

I wish we'll find a way to do that.

**Pull request closed without merging**
