### PR TITLE
Fix minio ws download

### LINKED ISSUE #2593: [self-hosted] Download of workspace failed with self-hosted / minio (at least with gitpod-k3s)
Downloading of workspace content from the workspace history list does not work. You simply get a `/sorry` page with “Error”. That's what the proxy logs:
```
2020/12/17 08:31:24 [error] 125#125: *1512 lua entry thread aborted: runtime error: access_by_lua(lib.locations.conf:107):3: http2 requests not supported yet
stack traceback:
coroutine 0:
	[C]: in function 'capture'
	access_by_lua(lib.locations.conf:107):3: in function <access_by_lua(lib.locations.conf:107):1>, client: 10.42.0.1, server: gitpod.dev.ludmann.org, request: "GET /workspace-download/get/a45cdd20-931d-4604-86bb-ac7e56071596 HTTP/2.0", host: "gitpod.dev.ludmann.org", referrer: "https://gitpod.dev.ludmann.org/workspaces/"
```

After removing `http2` from `vhost.server.conf` this error disappears. However, workspace downloads still not work. Instead, you get a `/sorry` page that says `404`. The var `ngx.var.targetUrl` in `lib.locations.conf` looks good and points to the `minio` pod. At least form the proxy pod, the `targetUrl` is reachable via `curl` (but gives 403 - unauthorized).

### PR DESCRIPTION
**Pull request by corneliusludmann**
Fixes #2593

### CODE REVIEW

**Comment by geropl** [comment]
I think removing `http2` is ok because:
 - scenarios in which `nginx` is the front-facing proxy is self-hosted only, and there we don't know (yet) of large installations, so having the increase in connection count (due to the loss of multiplexing) is ok
 - all other scenarios we have a LB that downgrades to HTTP1.x anyways
 
 Regarding the `stage`: This change will break all existing Gitpod Self-Hosted installations. Do we want to be backwards compatible here?

**Comment by csweichel** [comment]
We left out the stage on purpose. It was required for GCP because there buckets are global, but not so in MinIO.
I don't think we should introduce the stage here. In the past we've had to introduce several indirections and have multiple places where we map one stage name to another (they happen to change over time).

Instead, we should remove the bucket name computation from the server and do everything in the content-service.
All other components (ws-manager for FWB and ws-daemon) already use content-service for this purpose.

**Comment by csweichel** [comment]
I reckon the `-http2` change has unintended side-effects. nginx crashes with
```
021/01/04 07:52:40 [emerg] 1#1: BIO_new_file("/etc/nginx/certificates/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certificates/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] BIO_new_file("/etc/nginx/certificates/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certificates/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

**Comment by corneliusludmann** [comment]
> I reckon the `-http2` change has unintended side-effects. nginx crashes with
> 
> ```
> 021/01/04 07:52:40 [emerg] 1#1: BIO_new_file("/etc/nginx/certificates/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certificates/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> nginx: [emerg] BIO_new_file("/etc/nginx/certificates/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certificates/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> ```

@csweichel: I think this error is independent and occurs when the SSL certificates are missing. See also #2569.

**Comment by csweichel** [comment]
I'm not sure those are related. If I create a fresh deployment without HTTPS from master the proxy runs just fine without `fullchain.pem`.

**Comment by csweichel** [comment]
It doesn't really make sense that removing `http2` support should introduce the "no certificate crashes proxy" issue.
That said, I wonder why we're not seeing this issue when deploying a fresh branch from master, and what would happen if we merged this and ended up with a broken master. That said, considering #2655, that might not be a problem for long :)

Let's merge and see.

**Review by csweichel — APPROVED** [review]

**Pull request merged**
