### PR TITLE
Update go.sum files to avoid having them changed when workspace starts

### PR DESCRIPTION
**Pull request by felladrin**
## Description

| Before | After |
| --- | --- |
| image | image |

After these files were committed and pushed, I've reopened the workspace a few times to ensure nothing else was being changed during the startup.

I've also run a [prebuild from this branch](https://gitpod.io/t/gitpod/gitpod/421035b8-f922-4333-9ccd-6cf8f995dfe5), and confirmed the prebuild is not re-changing them.

The hard part will be to get the approval of every code-owner before someone else changes one of those files in the main branch and generates a file conflict. But I'll keep this branch up to date until we merge it.

Internal discussions: [[1](https://gitpod.slack.com/archives/C02EN94AEPL/p1671092590802639)][[2](https://gitpod.slack.com/archives/C02EN94AEPL/p1670586284936429?thread_ts=1670573389.952759&cid=C02EN94AEPL)][[3](https://gitpod.slack.com/archives/C02EN94AEPL/p1670164618788119)][[4](https://gitpod.slack.com/archives/C032A46PWR0/p1671179618175619)]

Previous fix attempt: [[1](https://gitpod.slack.com/archives/C032A46PWR0/p1671179964603239?thread_ts=1671179618.175619&cid=C032A46PWR0)][[2](https://github.com/gitpod-io/gitpod/pull/15311)]

## How to test

- Check if Werft Build succeeds.
- Open a workspace from this PR in gitpod.io (https://gitpod.io/#https://github.com/gitpod-io/gitpod/pull/15497) and confirm there's no file changed when the workspace starts.

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by jankeromnes — APPROVED** [review]
Yes please! ❤️ These changes are so annoying 🙈

**Review by sagor999 — APPROVED** [review]

**Comment by sagor999** [comment]
/hold
Feel free to unhold when everyone approved and it is ready to get merged.

**Review by ArthurSens — APPROVED** [review]

**Review by andreafalzetti — APPROVED** [review]

**Review by vulkoingim — APPROVED** [review]

**Comment by felladrin** [comment]
image
Due to code-owner rules, we'll also need approval from @Furisto, @akosyakov, @aledbf, @csweichel, and @geropl.

**Review by aledbf — APPROVED** [review]

**Review by akosyakov — APPROVED** [review]

**Review by svenefftinge — APPROVED** [review]

**Review by Furisto — APPROVED** [review]

**Comment by aledbf** [comment]
@felladrin how are you updating the values?

**Comment by felladrin** [comment]
> @felladrin how are you updating the values?

Rebasing, then waiting for the prebuild and then checking if opening a new workspace starts with any go.sum file changed. If there's any, I commit and force-push.

**Comment by aledbf** [comment]
> Rebasing, then waiting for the prebuild, and then checking if opening a new workspace starts with any go. sum file changed. If there's any, I commit and force-push.

Please use `leeway run components:update-go-modules`. The go.sum changes are required only in three modules.
https://github.com/gitpod-io/gitpod/pull/15521

We need to track what is introducing the other changes and avoid manual changes to `go.sum` files, that later will be lost when we update a dependency.

**Comment by felladrin** [comment]
> We need to track what is introducing the other changes and avoid manual changes to `go.sum` files, that later will be lost when we update a dependency.

What is causing the changes is definitely this line from Go's `init` task:
https://github.com/gitpod-io/gitpod/blob/24a7d195db6f54d629ef49563b84d148d4175bdd/.gitpod.yml#L68

---

> Please use leeway run components:update-go-modules. The go.sum changes are required only in three modules.
https://github.com/gitpod-io/gitpod/pull/15521

I noticed that `leeway run components:update-go-modules` calls

https://github.com/gitpod-io/gitpod/blob/24a7d195db6f54d629ef49563b84d148d4175bdd/components/BUILD.yaml#L192

but it's a problem, because during prebuild, `go mod verify` undo everything that `go mod tidy` does, bringing back the changes to `go.sum` files. (I couldn't understand why, but you can open a wokspace using the prebuild of https://github.com/gitpod-io/gitpod/pull/15521 to confirm it)

---

So maybe a more straightforward solution could be changing
```
leeway exec --filter-type go -v -- go mod verify 
```
by
```
leeway exec --filter-type go -v -- go mod tidy 
```
in [.gitpod.yml](https://github.com/gitpod-io/gitpod/blob/main/.gitpod.yml).

**Comment by aledbf** [comment]
> What do you think?

I think we need to remove that line. But what you proposed is not that extreme. 
So please make that change :pray:

**Comment by felladrin** [comment]
Hey all 👋  Good news: What was causing the issue was actually the GoLand Prebuild, which was warming up all Go projects from the repo and updating `go.sum` files during this.
https://github.com/gitpod-io/gitpod/blob/24a7d195db6f54d629ef49563b84d148d4175bdd/.gitpod.yml#L86-L89

I've removed it and will discuss it with the IDE team before putting it back.
With this, we also reduce a lot the prebuild time.

Please review to this other PR for the fix:
- https://github.com/gitpod-io/gitpod/pull/15529

After it's merged, we won't need this one anymore, so I'll close it.

**Pull request closed without merging**
