### PR TITLE
[ws-daemon] Add ws-daemon headless service

### PR DESCRIPTION
**Pull request by rl-gitpod**
Use endpoint on the ws-manager node to avoid pod/nodePort access issues.
Addresses https://github.com/gitpod-io/gitpod/issues/2956

### CODE REVIEW

**Comment by geropl** [comment]
Thx for your contribution @rl-gitpod ! 

Approach and implementation look good to me. @csweichel ?

**Comment by aledbf** [comment]
@rl-gitpod, why not just replace the current approach? Adding an option without any additional check for the CNI will lead to the same restriction and problems.

**Comment by rl-gitpod** [comment]
> @rl-gitpod, why not just replace/improve/fix the current approach? Adding an option without any additional check for the CNI will lead to the same restriction and problems.

@aledbf - not sure I follow. 
This replaces/fixes the current approach for ws-manager accessing ws-daemon as per #2956

I agree that there is a much bigger and potentially more impactful aspect of using the nodePort and the existing wso.HostIP() elsewhere throughout the code base - which is perhaps what you are referring to? If so, that was the thinking but beyond the scope of this issue and I'm unsure of where that fits in the short/medium term.

**Comment by aledbf** [comment]
@csweichel friendly ping

**Review by csweichel — APPROVED** [review]
LGTM

**Pull request merged**
