### PR TITLE
[oidc] Implement Get OIDC Client Config API

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

Implements Get OIDC Client Config API

## Related Issue(s)

* Fixes https://github.com/gitpod-io/gitpod/issues/15152
* Depends on https://github.com/gitpod-io/gitpod/pull/15925

## How to test

* Unit tests

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all-ci
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

/hold for dependency on https://github.com/gitpod-io/gitpod/pull/15925

### CODE REVIEW

**Comment by AlexTugarev** [comment]
:-( requires a rebase now. maybe PRs wasn't targeting the base PR.

**Review by AlexTugarev — APPROVED** [review]
LGTM!

/hold for the rebase

**Comment by easyCZ** [comment]
rebased

**Pull request merged**
