### PR TITLE
[ws-man-bridge-api] Always set govern to true

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

We no longer have a concept of app clusters being governing or not. The single app cluster we have is always governing, so we default to govern=true

## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-slow-database
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by geropl** [comment]
@easyCZ I haven't thought it through, but: Don't we have other areas with more potential for cleanup? :thinking:

**Comment by easyCZ** [comment]
> @easyCZ I haven't thought it through, but: Don't we have other areas with more potential for cleanup? 🤔

This is intended as a way to prevent human errors. In practice the non-governance doesn't make sense, and always defaulting to true for governing just ensures we don't accidentally not set it, or otherwise get into an odd state.

**Review by svenefftinge — APPROVED** [review]

**Comment by easyCZ** [comment]
@gitpod-io/engineering-workspace Would you be able to please take a look? Happy to go through it sync, if you need more context.

**Review by WVerlaek — COMMENTED** [review]
should we keep the flag but make it unused first? Such that we can remove any usages of the flag, as there are a few places that set `--hint-govern`: https://github.com/search?q=org%3Agitpod-io+hint-govern&type=code Otherwise those commands will fail with an unknown flag error

**Review by WVerlaek — APPROVED** [review]

**Pull request merged**
