### PR TITLE
[jb-remote] hook gp cli

### PR DESCRIPTION
**Pull request by akosyakov**
## Description

This PR enables support of gp CLI in JB products, namely credential helper, open and preview commands.
Caveat: It breaks gp cli in VS Code running alongside of JB products. We will have a look into separately: https://gitpod.slack.com/archives/C01KGM9BH54/p1644223793552719

This PR also include project specific IntelliIJ configs to enable dog fooding.

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/issues/7980, fixes https://github.com/gitpod-io/gitpod/issues/7848

## How to test

- Start a workspace with IntelliJ: https://ak-jb-remote-git.staging.gitpod-dev.com/#referrer:jetbrains-gateway/https://github.com/gitpod-io/spring-petclinic
- Try git push from cli and UI, you should see a notification about missing scopes in both cases. Clicking on the link should take you in access control page.
  - Sometimes UI is buggy and git integration is stuck, try to reopen then. It is not related to changes in this PR.
- Grand missing scopes in the access control page and check that you can now trigger push from cli and UI without issues.
- `gp open pom.xml` should open pom.xml file from terminal
- `gp open pom.xml --wait` should open pom.xml file from terminal and block it till file is not closed
- `gp preview $(gp url 8080)` should open the browser page

## Design Review

You can find pair review with @felladrin [here](https://drive.google.com/file/d/1qh7eaGOsmHa5Jb2gag3oEcLq8JX5QBbQ/view?usp=sharing).

gp-idea drawio

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
@akosyakov: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **akosyakov** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **akosyakov** after the PR has been reviewed.

Associated issue: *#7980*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **akosyakov** after the PR has been reviewed.

Associated issue: *#7980*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-cli/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-cli/OWNERS)**
- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by akosyakov** [comment]
@felladrin should be addressed, please double check before approving 🙏 

otherwise do approve and let's deploy it tomorrow for testing with JB

**Comment by felladrin** [comment]
> @felladrin should be addressed, please double check before approving 🙏
> 
> otherwise do approve and let's deploy it tomorrow for testing with JB

Thanks! Rechecking now!

**Review by felladrin — APPROVED** [review]
Code reviewed ✅ 

Tested with the same steps mentioned on the PR description ✅ 

> Start a workspace with IntelliJ: https://ak-jb-remote-git.staging.gitpod-dev.com/#referrer:jetbrains-gateway/https://github.com/gitpod-io/spring-petclinic

Screenshot

> Try git push from cli and UI, you should see a notification about missing scopes in both cases. Clicking on the link should take you in access control page.

Trying to push via CLI:

Screenshot

Screenshot

Trying to push via UI:

Screenshot

Screenshot

Screenshot

Screenshot

> Grant missing scopes in the access control page and check that you can now trigger push from cli and UI without issues.

Access control page _before_ setting permissions:

Screenshot

Access control page _after_ setting permissions:

Screenshot

After setting permissions, `git push` works as expected:

Screenshot

Screenshot

> gp open pom.xml should open pom.xml file from terminal

Screenshot

> gp open pom.xml --wait should open pom.xml file from terminal and block it till file is not closed

Screenshot

Screenshot

> gp preview $(gp url 8080) should open the browser page

Screenshot

Screenshot

**Pull request merged**
