### PR TITLE
[ws-manager] Refactor notification signals

### PR DESCRIPTION
**Pull request by aledbf**
Refactor signal handing to use `controller-runtime` helper that provides a Go `Context`.

This is done as a prefactor for the introduction of shared informers in `ws-manager` (that require a channel to start and signal stop)

### CODE REVIEW

**Review by csweichel — APPROVED** [review]
LGTM

**Comment by aledbf** [comment]
@csweichel from gitpod-build-signal.2 CI is passing but status is not being reported?

**Comment by csweichel** [comment]
Indeed. this is an issue with werft on forks. Feel free to merge anyways, as the build is green.

**Pull request merged**
