### PR TITLE
[supervisor] Lint code

### PR DESCRIPTION
**Pull request by aledbf**
## Description

Cleanup

## Release Notes
```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jeanp413** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @jeanp413` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by csweichel** [comment]
What did you use for linting?

**Comment by aledbf** [comment]
> What did you use for linting?

`golangci-lint run --allow-parallel-runners --timeout 5m ./... --enable-all -D wrapcheck -D testpackage`

**Comment by corneliusludmann** [comment]
Would it make sense to add this lint command to our CI job to make sure that we always lint the code like this? Otherwise, I personally think that it would not make sense if we lint our code once only when we do not enforce this during the daily coding. WDYT?

**Comment by aledbf** [comment]
> Would it make sense to add this lint command to our CI job to make sure that we always lint the code like this? Otherwise, I personally think that it would not make sense if we lint our code once only when we do not enforce this during the daily coding. WDYT?

We already have that but with a number of checks disabled https://github.com/gitpod-io/gitpod/blob/main/WORKSPACE.yaml#L17
If we enable all checks, we will not merge any PR :(

**Comment by akosyakov** [comment]
/assign @corneliusludmann 

Could you review it please when you have a moment? Thank you! 🙏

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 1d2ee9f21f5182f78bb3d2de7463055705740b76</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6483#issuecomment-959141870" title="LGTM">corneliusludmann</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6483#issuecomment-959142704" title="Approved">corneliusludmann</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/6483#issuecomment-959142704" title="Approved">corneliusludmann</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
