### PR TITLE
Add `function:sendHeartBeat` scope

### PR DESCRIPTION
**Pull request by akosyakov**
## Description

Add `function:sendHeartBeat` scope for vscode clients

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@akosyakov: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by akosyakov** [comment]
Don't forget that it should be deployed before we release new version of VS Code Desktop extension 🙏 Maybe we should open it for review already?

**Comment by geropl** [comment]
@jeanp413 Could you elaborate on the motivation for this change?
It sounds reasonable, but why did it work beforehand? I thought `supervisor` was responsible for sending hearbeats - why extending it to clients? :thinking:

**Comment by jeanp413** [comment]
@geropl previous way still works, but we are trying to improve it in the cases where there's a disconnection, if user looses ssh connection in vscode desktop then as long as it has some activity in the vscode local window heartbeat should be send so workspace doesn't stop due to the 5 min timeout

**Review by geropl — APPROVED** [review]

**Comment by mustard-mh** [comment]
Rebased to main to make preview env available

**Comment by geropl** [comment]
@jeanp413 @mustard-mh I'm unsure in what state this PR is in. Can we either merge it or move it back to draft state, please? :pray:

**Comment by jeanp413** [comment]
Sorry, I'll merge, was using the prev env to test it.

**Pull request merged**
