### PR TITLE
Hw/ide encrypt

### PR DESCRIPTION
**Pull request by mustard-mh**
## Related Issue(s)

Fixes #

## How to test

- Open workspace in preview env with latest browser code
- Check localStorage if `credentials.providers` is encrypted

**compatible#1**
- Close workspace and change default IDE to stable browser code
- Re-open workspace, check if everything is alright (compatible)

**compatible#2 old workspace reopen**
- Copy credentials.provider from production and set
- Re-open workspace use stable browser code
- Check if it encrypted again and the decrypted value is the same with just copied value

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`
- [ ] /werft publish-to-npm

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by roboquat** [comment]
@mustard-mh: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mustard-mh** [comment]
Don't really know if the credentials is loaded correctly or not since remove it from localStorage and refresh we will get the same value.

cc @akosyakov @jeanp413

**Comment by mustard-mh** [comment]
close as completed

**Pull request closed without merging**
