### PR TITLE
[public-api] Move existing API definitions to stable package

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

To indicate what is stable, and what is experimental.

Inside stable, we can follow our existing maturity model (alpha, beta, ga) if we want to, but for now it better communicates quality of the APIs.

There's currently no traffic on the API so this move is "safe", albeit the change itself is non-backwards compatible.

## Related Issue(s)

Fixes #

## How to test

Builds

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by akosyakov** [comment]
I wonder what is the definition of stable. From times of Theia/VS Code I remember it was like there are sufficient number of adopters relying on these API and it was not change since then for a while. Maybe it is too premature till we don't have at least internal adopters?

**Comment by easyCZ** [comment]
> I wonder what is the definition of stable. From times of Theia/VS Code I remember it was like there are sufficient number of adopters relying on these API and it was not change since then for a while. Maybe it is too premature till we don't have at least internal adopters?

It mostly a question if we're happy to commit to it or not. I'd try not get too hung up the precise definition at this point and mostly use it as a "place to put stuff if you're not sure this will work"

**Comment by csweichel** [comment]
We should have a definition of what stable means, mainly from a _compatibility guarantees_ perspective. E.g. things like: 
- Services, calls, types and fields are not removed without following the deprecation policy (TBD).
- Nothing is ever renamed.
- Expected errors are described exhaustively.

**Comment by easyCZ** [comment]
@csweichel Is that something you're keen to include in this PR? I can try to do this and put it into the Readmes or did you have something else in mind?

**Comment by easyCZ** [comment]
I'll also try to configure the buf [Breaking Detector](https://docs.buf.build/breaking/overview) for the stable directory once we settle on the approach.

**Comment by geropl** [comment]
> We should have a definition of what stable means, mainly from a compatibility guarantees perspective.

@easyCZ I understand that this PR is more about the technical aspect, but I think - and agree with the others - it makes sense to sort out the (minimal) definition first.

> Inside stable, we can follow our existing maturity model (alpha, beta, ga) if we want to, but for now it better communicates quality of the APIs.

But does `beta` not contradict `stable`? I feel you might have something in mind here with regards to user experience, but I don't see it, yet.

I propose we:
 - but this PR back into draft
 - quickly align between you, me and Anton about the guarantees _they_ need to move forward (and maybe define that it as something ala `beta`: so some guarantees, but not GA yet)
 - find a way to package that, and describe those steps in a README in this PR
 - re-open the PR for review
WDYT?

**Comment by easyCZ** [comment]
Sure. This grouping into `stable` and `experimental` is based on the [(internal) RFC](https://www.notion.so/gitpod/Public-API-Beyond-Hello-World-b45d5a44dd7944ad8d6b15aa3a75156e#d9a22c3aff80483fa06ba5d473d809b4).

The grouping here largely communicates how much we expect to break the protocol going forward. When we define in the `stable` category, we are prohibited from doing any of the following (outside of regular deprecation cycles):
* Rename fields
* Delete fields
* Stop populating fields with data
* Change the package name (or the full package structure)

We can still make backwards compatible changes but we are comitting to protocol and data level compatibility.

With protobuf, any change to the package name is NON-backwards compatible. 

The implication is that if we also choose to support maturity stages within the `stable` group, and encode these into the package, then every time you move a maturity level you have to re-define the API, and re-implement in code (yes, you can call into a common function) but the previous maturity stages must continue to exist to remain backwards compatible.

**Review by aledbf — APPROVED** [review]

**Comment by easyCZ** [comment]
I've cut a separate PR with just the definitions for stable and experimental - https://github.com/gitpod-io/gitpod/pull/13914 suggestions extremely welcome.

**Comment by easyCZ** [comment]
Closing in favour of https://github.com/gitpod-io/gitpod/pull/13987

**Pull request closed without merging**
