### PR TITLE
Update team creation link in projects

### PR DESCRIPTION
**Pull request by gtsiolis**
## Description

Following up from https://github.com/gitpod-io/gitpod/pull/13920, to update the correct line of code.

## How to test

See instructions in https://github.com/gitpod-io/gitpod/pull/13920.

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [X] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@gtsiolis: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by easyCZ** [comment]
Shall we also revert the change in https://github.com/gitpod-io/gitpod/pull/13920?

**Comment by gtsiolis** [comment]
Thanks, @easyCZ! I was about to ask about the change in https://github.com/gitpod-io/gitpod/pull/13920 since I could not spot any UX difference with that change, but let's revert to be on the safe side.

Updated in 95ce6d7. Let me know if you'd prefer the revert in a separate commit.

Ready-To-Merge.

**Review by easyCZ — APPROVED** [review]

**Comment by easyCZ** [comment]
LGTM, just needs a release note.

**Comment by gtsiolis** [comment]
Thanks, @easyCZ! 🍻

**Pull request merged**
