### PR TITLE
Make TakeSnapshot more reliable

### LINKED ISSUE #5862: Cannot generate a workspace snapshot
### Bug description

After opening DrupalPod in Gitpod, I open the hamburger menu on top-left corner, and choose `Gitpod: Share Workspace Snapshot`

I see `Capturing workspace snapshot` dialog -
image

After a few minutes, it displays an error -
image

Errors in console:
image

(Using Gitpod's VScode v1.59)

### Steps to reproduce

1. Open DrupalPod in gitpod:
  https://gitpod.io/#https://github.com/shaal/DrupalPod
1. Open the hamburger menu on top-left corner
1. Choose `Gitpod: Share Workspace Snapshot`

### Expected behavior

I was able to take snapshots of DrupalPod workspace in the past, but somehow I can no longer able to.

### Example repository

https://github.com/shaal/DrupalPod

### Anything else?

I am able to create workspace snapshot on 'simpler' repos, such as - https://gitpod.io/#https://github.com/gitpod-io/template-typescript-node

### PR DESCRIPTION
**Pull request by geropl**
## Description
This fixes #5862 by following this idea: https://github.com/gitpod-io/gitpod/issues/5862#issuecomment-946721722

### In detail
 - we add a `state: 'pending' | 'error' | 'available''` field to `Snapshot` (+ `message` and `availableTime`)
 - we add a method `content-service.WorkspaceSnapshotExists`
 - we make sure `ws-daemon.TakeSnapshot` returns early
 - we add an API method `server.waitForSnapshot`
 - we add a `SnapshotService` to `server` which is responsible for making sure all 
 - we change the semantics fo `server.takeSnapshot` to:
   - return as early as we have the upload file URL from `ws-daemon`, stored that in the DB (with state: 'pending') and return the `snapshotId`
   - we make sure `SnapshotService` monitors this DB entry and regularly checks if it's done or timed out, resulting in an update to the DB
   - clients have to take that `snapshotId` and have to call `server.waitForSnapshot` to wait for the snapshot to become `available` (or `error` in case sth went south). This internally waits for the same Promise `SnapshotService` is already driving

### Regarding deployment
This change has breaking changes to IDE and workspace. To untangle and make the deployment as easy as possible:
 - once reviewed (and tested) split this PR into two: IDE and workspace + meta
 - `server` and workspace are fully backwards-compatible to each other; `server` API is backwards compatible as well. Thus we have to make sure meta is deployed before IDE, the rest does not matter.
 
 

## Related Issue(s)

Fixes #5862

IDE companion PR: https://github.com/gitpod-io/openvscode-server/pull/169

## How to test
- open a dev workspace on this branch: https://gitpod.io/#https://github.com/gitpod-io/gitpod/pull/6144
- **prepare** to execute `kubectl rollout restart deployment proxy`
-  start a test workspace with this link: https://gpl-5862-snapshot.staging.gitpod-dev.com/#https://github.com/shaal/gitpod-test-failing-snapshot (thx @shaal ! :pray: )
- F1 -> snapshot -> enter
- **execute** `kubectl rollout restart deployment proxy` from the dev workspace (this simulates ws connection loss)
- note how the call fails (shows that it's backwards compatible!)
- ~note how the snapshot process is not interrupted in the IDE of the test workspace~
- ~note that after ~2mins the snapshot is successful~
- ~test the snapshot link and note that it works~

## Release Notes

```release-note
make "snapshots" more reliable
```

## Documentation

- [ ] /werft with-clean-slate-deployment

### CODE REVIEW

**Comment by roboquat** [comment]
@geropl: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** and additionally assign **akosyakov** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @akosyakov` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/ide/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ide/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by JanKoehnlein** [comment]
/lgtm

Awesome! I am happy we're finally getting this fixed.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 25bf7c8b1832a6ebc9bc29b7c64136ddabe19b70</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6144#issuecomment-957302148" title="LGTM">JanKoehnlein</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **csweichel** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @csweichel` in a comment when ready.

Associated issue: *#5682*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [JanKoehnlein]
- **[components/content-service/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service/OWNERS)**
- **[components/content-service-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service-api/OWNERS)**
- ~~[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)~~ [JanKoehnlein]
- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [JanKoehnlein]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [JanKoehnlein]
- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**
- **[components/ws-daemon-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon-api/OWNERS)**
- **[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)**
- **[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
> Awesome! I am happy we're finally getting this fixed.

Thx for the review. Going to split this up into 2 PRs: IDE and workspace/meta to allow for easier deployments.

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6144#issuecomment-957302148" title="LGTM">JanKoehnlein</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **csweichel** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @csweichel` in a comment when ready.

Associated issue: *#5682*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/content-service/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service/OWNERS)**
- **[components/content-service-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service-api/OWNERS)**
- ~~[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)~~ [JanKoehnlein]
- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [JanKoehnlein]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [JanKoehnlein]
- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**
- **[components/ws-daemon-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon-api/OWNERS)**
- **[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)**
- **[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
/werft run

another try---

**Comment by geropl** [comment]
/werft run

...and again

**Comment by geropl** [comment]
/unhold

Ready to merge now

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: e74e73cd5ea3964fe6b81a871af7253bdf9429f6</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6144#issuecomment-960641592" title="LGTM">JanKoehnlein</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **csweichel** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @csweichel` in a comment when ready.

Associated issue: *#5862*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/content-service/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service/OWNERS)**
- **[components/content-service-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service-api/OWNERS)**
- ~~[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)~~ [JanKoehnlein]
- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [JanKoehnlein]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [JanKoehnlein]
- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**
- **[components/ws-daemon-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon-api/OWNERS)**
- **[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)**
- **[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by gtsiolis — COMMENTED** [review]
Tried this for a workspace larger than 3.5GB which used to fail and worked as expected! 🔮 

Thanks @geropl! 🏁

**Comment by csweichel** [comment]
did not test, but API and service changes lgtm

/lgtm

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6144#issuecomment-960661897" title="LGTM">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6144#issuecomment-960641592" title="LGTM">JanKoehnlein</a>*

Associated issue: *#5862*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/content-service/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service/OWNERS)~~ [csweichel]
- ~~[components/content-service-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service-api/OWNERS)~~ [csweichel]
- ~~[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)~~ [JanKoehnlein]
- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [JanKoehnlein]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [JanKoehnlein]
- ~~[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)~~ [csweichel]
- ~~[components/ws-daemon-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon-api/OWNERS)~~ [csweichel]
- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [csweichel]
- ~~[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by shaal** [comment]
I can't wait for this feature to be working again 🎉  
When do you expect this to be available on gitpod.io ?

**Comment by gtsiolis** [comment]
Thanks, @shaal! The fix should probably land in production within a week.

FYI, we're trying to get better at deploying to production sooner and more often. We currently deploy changes to the dashboard at least once per week and aim at deploying least twice a week. 💡

**Comment by geropl** [comment]
@gtsiolis Just to clarify: This PR is just introducing the server/workspace changes. IDE change will land later, I expect next week.

**Comment by gtsiolis** [comment]
Thanks for clarifying, @geropl!

Do we have an open issue for the IDE changes?

Cc @shaal

**Comment by geropl** [comment]
It's the same issue: https://github.com/gitpod-io/gitpod/issues/5862

Draft PR is here: https://github.com/gitpod-io/openvscode-server/pull/169

**Pull request merged**
