### PR TITLE
[gitlab] support nested repos in envvar patterns

### LINKED ISSUE #2702: Unable to set user environment variables for GitLab repos with nested groups
### Describe the bug

I can't set environment variable for nested groups, for instance, `nifty-panini/backend/gitpod-example`.
Gitlab allows to create nested groups and place repo at under needed group, it's very often use case.

So I wanna have ability set variables like `NPM_TOKEN` under root group to use this variable on all repos under group without need to set variable to each repo.

Currently I can't set variable due to some bug or it's not implemented. 

### Steps to reproduce

1. Go to Settings UI and set environment variable `BARFOO` with value `foobat` and `Organization/Repository` with value `nifty-panini/*` 
2. Open with GitPod with enabled Code editor by default by using link:
https://gitpod.io/#/https://gitlab.com/nifty-panini/backend/gitpod-example/-/tree/master/
3. echo `$BARFOO` to verify that environment variable is present.
4. BARFOO is not set

I've tested it on **Code / Theia** editor, **it doesn't work on both**.

### Expected behavior

I wanna set env variable for nested group on Gitlab and use this variable on each repo that belongs to the group.

### Additional information

image

Workspace about info: 
```bash
Version: 1.49.0
Commit: 20ded0d97c41cb686098d14b9e1f0533177300d1
Date: 2020-12-17T09:27:27.064Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 OPR/73.0.3856.284
Workspace ID: c81ce827-d4bb-4c8f-b989-6fb869640014
```

### Example repository

https://gitlab.com/nifty-panini/backend/gitpod-example/-/tree/master/

### PR DESCRIPTION
**Pull request by JanKoehnlein**
## Description
Support nested repos in user-scoped env var patterns.

## Related Issue(s)
Fixes #2702

## How to test
See #2702

## Release Notes
```release-note
[gitlab] user-scoped env vars can now be filtered for nested repos on Gitlab
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jankoehnlein** after the PR has been reviewed.

Associated issue: *#2702*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by JanKoehnlein** [comment]
Don't know whether we want that as we deprecate the patterns anyway.

**Comment by jankeromnes** [comment]
Agree that the repository pattern is deprecated and should go away.

However, this does seem like a risk-free short-term quality-of-life improvement, so I'd be happy to test / review / approve it, especially since the use case of "personal env var specific to a project" is not currently supported without the prefix:

| | Exposed everywhere | Exposed in team projects | Exposed in single project |
| --- | --- | --- | --- |
| **Owned by user** | ☑️ user-level, `*/*` pattern | ☑️ user-level, `xyz/*` pattern | ☑️ user-level, `xyz/abc` pattern |
| **Owned by team** | ✖️ | ✖️<sup><a href="https://github.com/gitpod-io/gitpod/issues/7881">1</a></sup> | ✅ project-level |

**Comment by JanKoehnlein** [comment]
Closed in favor of https://github.com/gitpod-io/gitpod/pull/7978 with a shorter branch name that doesn't crash the preview env

**Pull request closed without merging**
