### PR TITLE
Replace AlertBox with Alert component

### LINKED ISSUE #9411: Migrate AlertBox components to the new Alert component
### Problem to solve

Back in https://github.com/gitpod-io/gitpod/pull/8783, we've added the next iteration of the alert component which introduces component variants for using the alert component for informing users, alerting users, etc.

Currently, there're two more `Alert`-like components which include `InfoBox` and `AlertBox`, see example screenshots below.

| Component: InfoBox | Component: Alert, Variant: Info |
|-|-|
|  info-before | info-after |

| Component: AlertBox | Component: Alert, Variant: Warning |
|-|-|
| alert-before | alert-after |

### Proposal

Migrate [`InfoBox`](https://github.com/gitpod-io/gitpod/blob/dac6262d29e9424908fe7440a88c06265c4f8b1c/components/dashboard/src/components/AlertBox.tsx) ([8 component instances](https://github.com/gitpod-io/gitpod/search?q=%22%2Fcomponents%2FInfoBox%22)) and [`AlertBox`](https://github.com/gitpod-io/gitpod/blob/dac6262d29e9424908fe7440a88c06265c4f8b1c/components/dashboard/src/components/AlertBox.tsx) ([5 component instances](https://github.com/gitpod-io/gitpod/search?q=%22%2Fcomponents%2FAlertBox%22)) components to the new [`Alert`](https://github.com/gitpod-io/gitpod/blob/dac6262d29e9424908fe7440a88c06265c4f8b1c/components/dashboard/src/components/Alert.tsx) component. ➿

### PR DESCRIPTION
**Pull request by KevSlashNull**
## Description

This PR replaces the old `AlertBox` with the new `Alert` component (type `warning`) across the dashboard. This change is a part of the overall effort to migrate to the new `Alert` component in #9411.

| Where | Before | After |
| --- | --- | --- |
| Integration activation | image | image |
| Project variables | image | image |
| Upgrade modal | image | image |
| Team plan pricing | image | image |
| Confirmation modal, warning text | image | image |

## Related Issue(s)
Fix #9411 

### Integration activation

1. Go to **Settings** > **Integrations**
1. Click on **New Integration**
1. Fill it with dummy data (e.g. Provider Host Name: `example.codingpa.ws`, Application ID: `test`, Secret: `test`)
1. Click on **Activate integration**
1. Close the popup
1. See the changed alert

### Project variables

1. Go to a project (or create one)
2. Go to **Settings** > **Variables** in the project
3. Click on **New variable**
4. See the changed alert

### Upgrade modal

1. Go to **Settings** > **Plans**
2. Click on a plan (You need to not be on that plan)
3. See the changed alert in the modal

### Team plan pricing

1. Go to **Settings** > **Team Plans**
2. Click on **Create Team Plan**
3. See the changed alert

### Confirmation modal

1. Go to a team (or create one)
2. In the team, go to **Settings**
3. Click on **Delete Team**
4. See the changed alert in the modal

## Release Notes

```release-note
Migrate AlertBox component instances to Alert component
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@KevSlashNull: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by gtsiolis — APPROVED** [review]
Thanks for contributing, @KevSlashNull! 

1. Re-posting from https://github.com/gitpod-io/gitpod/pull/10170#issuecomment-1134689448, let me loop in @meysholdt to reach out about the CLA. 🏓
2. UX and code changes look good! ✔️ 
3. Opened a new follow up issue for the InfoBox component migration in https://github.com/gitpod-io/gitpod/issues/10205, see https://github.com/gitpod-io/gitpod/issues/9411#issuecomment-1135490807. ➿ 
4. Let me also spin up a preview environment for this PR below. 🚀

**Comment by meysholdt** [comment]
hi @KevSlashNull! To send you our CLA, can you please send me an email to moritz@gitpod.io with your full name? I will then send the CLA via DocuSign to your email address.

**Comment by KevSlashNull** [comment]
Thanks @meysholdt, I’ve sent you an email. :smile:

**Comment by KevSlashNull** [comment]
Closing this PR as I haven’t signed the CLA yet (blocked by #7864) to reduce the signal-noise-ratio. Once that is resolved, I’ll gladly pick this up again.

cc @gtsiolis

**Comment by gtsiolis** [comment]
Let me reopen this, @KevSlashNull! I've pinged the team internally.

Have you signed the CLA that @meysholdt mentioned in https://github.com/gitpod-io/gitpod/pull/10199#issuecomment-1135888840?

**Comment by KevSlashNull** [comment]
@gtsiolis, thanks! I haven't signed the CLA yet because I'm waiting for
#7864 to be resolved. 😅

**Comment by meysholdt** [comment]
hi @KevSlashNull, we've updated our CLA process and the controversial language of https://github.com/gitpod-io/gitpod/issues/7864 is no longer part of our CLA. Can you please sign our CLA via [this DocuSign form](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=30e1aa46-cce5-4bc6-a933-ad02cd8d5ada&env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&v=2)? If there are any questions, you can reach me via moritz@gitpod.io.

**Comment by KevSlashNull** [comment]
@meysholdt, cool, thank you! :smile: I signed the CLA. Once it’s signed by you as well, I’ll push a commit to fix the conflicts to get this PR moving.

**Comment by meysholdt** [comment]
hi @KevSlashNull, thank you for signing! I have signed it as well.

**Comment by gtsiolis** [comment]
Thanks @meysholdt! @KevSlashNull could you resolve conflicts and rebase against main? 🏓

**Comment by KevSlashNull** [comment]
Thanks @meysholdt!

@gtsiolis, I’ve rebased and fixed the conflicts. Back to you! :ping_pong:

**Review by gtsiolis — APPROVED** [review]
Approving once more after running the preview environment. You should be able to access the **[preview environment](https://9411-replafbde2e2e8e.preview.gitpod-dev.com/workspaces)** for the next couple of hours before it times out.

UX and code changes, LGTM. ✔️ 

Thanks again @KevSlashNull for contributing and your patience while our CLA signing process was under the microscope. 🍊 

This will need one more approval from someone from the `@gitpod-io/engineering-webapp`—Explicitly pinging @gitpod-io/engineering-webapp for visibility.

**Review by andrew-farries — APPROVED** [review]

**Comment by gtsiolis** [comment]
Thanks for taking a look @andrew-farries! 🏀

**Comment by KevSlashNull** [comment]
Thanks @gtsiolis and @andrew-farries! :raised_hands:

**Pull request merged**
