### PR TITLE
Update go dependencies

### PR DESCRIPTION
**Pull request by aledbf**
## Description

- Update docker to v23.0.2+incompatible
- Update runc to v1.1.5
- Update containerd to v1.6.20
- Update logrus v1.9.0 

## Release Notes
```release-note
NONE
```

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]

**Comment by kylos101** [comment]
Resolved conflict for `components/usage/go.sum` in https://github.com/gitpod-io/gitpod/compare/bfcd25af651ceaaca93965cad41a2e9986c7903e..000fdd59fc6d8990e5eac3f7b0d3d377b5836fd6

**Review by kylos101 — APPROVED** [review]
* Started, stopped, and restarted a workspace, restoring content that was never pushed.
* Ran `docker run --rm -it redis`
edit: had to delete the preview env with `leeway run dev/preview:delete-preview` and then rebuild with `leeway run dev:preview`

**Comment by kylos101** [comment]
@gitpod-io/engineering-security-infrastructure-and-delivery may we ask you for a review?

**Comment by kylos101** [comment]
@gitpod-io/engineering-ide may we ask you for a review?

**Review by mustard-mh — APPROVED** [review]
👍

**Review by nandajavarma — APPROVED** [review]

**Pull request merged**
