### PR TITLE
Hide editor versions for user prefs

### PR DESCRIPTION
**Pull request by filiptronicek**
## Description

IDE versions were previously shown in user preferences, but workspaces are not based on user preferences - the versions used are fetched from the organization's config. Because of this, we are changing these UIs to hide the version, and only show it in the create workspace page, where the version which will actually be used is shown.

## Related Issue(s)

Fixes EXP-1801

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - ft-user-pr1e95611825</li>
	<li><b>🔗 URL</b> - <a href="https://ft-user-pr1e95611825.preview.gitpod-dev.com/workspaces" target="_blank">ft-user-pr1e95611825.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - ft-user-prefs-no-editor-versions-gha.24424</li>
	<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-ft-user-pr1e95611825%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws-manager-mk2%22%0A;duration=P1D?project=gitpod-core-dev" target="_blank">GCP Logs Explorer</a></li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by laushinka** [comment]
GRABBING THOSE QUICK WINS

**Comment by laushinka** [comment]
We still have two IntelliJs unfortunately 🤔 I wonder how we can do this before the deprecation of 2022.3.3. @svenefftinge

**Comment by filiptronicek** [comment]
> We still have two IntelliJs unfortunately 🤔 I wonder how we can do this before the deprecation of 2022.3.3.

That's true. Only thing I can think of is to explicitly mention the version of these two, or just the 2022 one.

**Comment by svenefftinge** [comment]
The `latest` label should not be shown when no versions are shown

**Comment by svenefftinge** [comment]
We should rename the Jetbrains 2022 entry so it includes the version.
Screenshot 2024-04-19 at 10 38 55

**Comment by svenefftinge** [comment]
Let's remove the latest label on the user settings. In this case it doesn't make sense.

**Review by svenefftinge — APPROVED** [review]

**Pull request merged**
