### PR TITLE
[agent-smith] Disable by default

### LINKED ISSUE #4885: Gitpod Self-Hosted shipped with agent-smith enabled
### Bug description

The agent-smith daemonset fails in deployment of Gitpod 0.10.0-alpha1 on a Self Hosted K8S install.  The log contains the following error:

`{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"program bpf_sys_getrlimit_setrlrimit_x: load program: invalid argument","level":"fatal","message":"error while loading and attaching bpf program","serviceContext":{"service":"agent-smith","version":""},"severity":"CRITICAL","time":"2021-07-20T19:28:01Z"}`

### Steps to reproduce

Deploy Self Hosted Gitpod 0.10.0-alpha1 via helm

### Expected behavior

Pods should start up normally

### Example repository

n/a

### Anything else?

I'm not sure if the error during workspace creation:

`Oh, no! Something went wrong!
cannot initialize workspace: cannot initialize workspace: content initializer failed`

is related to the agent-smith pods failing to spin up?

### PR DESCRIPTION
**Pull request by csweichel**
fixes #4885

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4956#" title="Author self-approved">csweichel</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by geropl — APPROVED** [review]
:+1:

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 29e87f4ebf9e8ed499df1ef730f3ff490203abd2</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4956#" title="Author self-approved">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4956#pullrequestreview-714923012" title="Approved">geropl</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [csweichel,geropl]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
