### PR TITLE
Revert "Refactor backups"

### PR DESCRIPTION
**Pull request by aledbf**
Reverts gitpod-io/gitpod#9589

Two scenarios where the restoration fails:
- https://github.com/gitpod-io/gitpod/pull/9589#issuecomment-1116198441
- https://github.com/gitpod-io/workspace-images

### CODE REVIEW

**Comment by roboquat** [comment]
@aledbf: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by aledbf** [comment]
@mustard-mh let me revert only the restoration part.

**Comment by aledbf** [comment]
@mustard-mh please review https://github.com/gitpod-io/gitpod/pull/9732

**Pull request closed without merging**
