### PR TITLE
Add external button

### PR DESCRIPTION
**Pull request by gtsiolis**
This will add the external button commonly used in README files.

Related to https://github.com/gitpod-io/gitpod/issues/3700.

| BEFORE | AFTER |
|-|-|
|  light-before | light-after | 
| dark-before | dark-after |

### CODE REVIEW

**Comment by gtsiolis** [comment]
**question**: In the meantime, we used to have four variants[[1](https://github.com/gitpod-io/gitpod/blob/0.6.0/components/dashboard/public/button/open-in-gitpod.svg)][[2](https://github.com/gitpod-io/gitpod/blob/0.6.0/components/dashboard/public/button/code-in-gitpod.svg)][[3](https://github.com/gitpod-io/gitpod/blob/0.6.0/components/dashboard/public/button/solve-in-gitpod.svg)][[4](https://github.com/gitpod-io/gitpod/blob/0.6.0/components/dashboard/public/button/review-in-gitpod.svg)]. Are these still needed?

**Comment by gtsiolis** [comment]
WDYT @svenefftinge? I could be missing something. 🔍

**Comment by gtsiolis** [comment]
Two things to also consider:

1. The new one is using a slightly different height `32px` v. `40px`
2. The new one is having a subtle drop shadow.

**Comment by jankeromnes** [comment]
> This will add the external button commonly used in README files.

Wow, great catch! And looks awesome ✨ 

> **question**: In the meantime, we used to have four variants[1][2][3][4]. Are these still needed?

I think we broke them a while ago: https://github.com/gitpod-io/gitpod/issues/3235 but then decided not to fix them and instead deprecate the "add button to issue" feature of the Gitpod GitHub App. I think some people were sad/unhappy about these buttons no longer working.

**Comment by svenefftinge** [comment]
The text in the button seems to sit a bit too high, no?

**Comment by gtsiolis** [comment]
> The text in the button seems to sit a bit too high, no?

Good eyes! 👀  However, this _is_ vertically aligned but visually seems a bit off. We could hack this by adding `1px` offest on the top.

| BEFORE | BEFORE (Spacing)) | AFTER | 
|-|-|-| 
| image |image |  image | 

Here's what it could look like on light and dark GH theme.

| A (Light) | A (Dark) |
|-|-|
| image | image |

Here're some alternative variants we could go with.

| B (Light) | B (Dark) | C (Light) | C (Dark) | D (Light) | D (Dark) |
|-|-|-|-|-|-|
| image | image | image | image | image | image |

What do you think? /cc @svenefftinge @jankeromnes

**Comment by svenefftinge** [comment]
Yes, that's better. I'd prefer the currently proposed variant (white bg / AFTER).

**Comment by gtsiolis** [comment]
Alright, let's do it! Updated the button in https://github.com/gitpod-io/gitpod/pull/3732/commits/72707cd47ff53d30a126fbc1cd5668bf336a7cba and the PR description with some updated screenshots. 🖼️ 

Two points for future reference:
1. The white background could make the button pop up more than expected in dark themes but should be fine as is for now. We can always change this later.
2. I've used the SVG markup from MAD's specs for the button to avoid requesting font files so I've [added a small rectangle](https://github.com/gitpod-io/gitpod/pull/3732/commits/72707cd47ff53d30a126fbc1cd5668bf336a7cba#diff-594b51ad54d97ee19b885313b864b3647d16cbb828c4207c934bad2ed43c02aeR5) above the button label to introduce the `1px` offset.

**Review by svenefftinge — APPROVED** [review]

**Pull request merged**
