### PR TITLE
[supervisor] track cpu/memory usage analytics

### PR DESCRIPTION
**Pull request by akosyakov**
## Description

This PR adds analytics to track cpu and memory consumption by individual workspace instances. It adds 2 new events `gitpod_cpu_changed` and `gitpod_memory_changed` correspondingly. Each event has `buckets` property and reported whenever a workspace instance hit higher bucket.
- CPU buckets: 1, 2, 3, 4, 5, 6 CPUs
- Memory buckets: 1, 2, 4, 8, 16 Gb

It will allow us to segment users by perf requirements and also correlate with other event like active language to see requirements from different languages. Mixpanel is capable to breakdown arrays to individual properties. I've verified it with IDE lab project.

## Related Issue(s)

Fixes #

## How to test

- Start a workspace in prev env: https://ak-perf-anayltics.preview.gitpod-dev.com/#https://github.com/akosyakov/parcel-demo
- Inspect `gitpod_cpu_changed` and `gitpod_memory_changed` events in segment untrusted. I would recommend to filter by instance id. Whenever perf metrics hit a higher bucket you should see a change. If it goes down though we don't report changes.

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview
- [x] /werft analytics=segment|TEZnsG4QbLSxLfHfNieLYGF4cDwyFWoe

### CODE REVIEW

**Comment by roboquat** [comment]
@akosyakov: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by andreafalzetti** [comment]
the prev env is back now, but werft failed so I am trying with:

/werft run with-clean-slate-deployment=true

**Review by andreafalzetti — APPROVED** [review]
Code changes LGTM 🍪 

I've tested it and it works as advertised. I was able to get the CPU to hit the biggest bucket and the reporting worked quite well.

Screenshot 2022-09-06 at 21 26 15

For the memory I also tried to stress it to see reports and I saw up to 4GB, and saw no more reporting but I think it's due to my approach for stressing the memory which is too agressive, I think: `cat /dev/zero | head -c 5G | tail`, and it basically very quickly kills the workspace.

If you have another way to consume more memory, I am interested to know.

/hold 

in case someone wants to review/test further

**Comment by mustard-mh** [comment]
> If you have another way to consume more memory, I am interested to know.

Files in `/tmp` folder will calc as workspace's MEM, you can generate big files here. @andreafalzetti

**Pull request merged**
