### PR TITLE
[installer-tests] fix the subdomain for upgrade tests to include cloud

### PR DESCRIPTION
**Pull request by nandajavarma**
## Description

I introduced a regression earlier today, by which the terraform state names didn't include the cloud provider name. This PR fixes this

## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Review by adrienthebo — APPROVED** [review]
Changes look reasonable, but CI is failing due to replicated errors.

/hold for successful CI run, preemptively approving

**Comment by nandajavarma** [comment]
Rebasing with `main` and testing this!

**Comment by nandajavarma** [comment]
Upon multiple runs of this, I caught an issue with preflights happening in EKS cluster. Looks like reducing the `AWSS3FullAccess`  access on IAM users used for storage in AWS is failing the preflights. I have an issue open for this here, which could potentially be a blocker for the release. I have added[ this ](https://www.notion.so/gitpod/Self-Hosted-Release-2022-09-0-0534b6ba181b476cb1826e358a7149f9#4727768a35784efc8566c75c61f6fafc)as a potential blocker for the release.

In the meantime, /unhold

**Pull request merged**
