### PR TITLE
[JetBrains] Improve integration tests

### PR DESCRIPTION
**Pull request by andreafalzetti**
## Description

Improve JetBrains integration tests.

## Related Issue(s)

- Fixes https://github.com/gitpod-io/gitpod/issues/15563

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-integration-tests=jetbrains
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by roboquat** [comment]
@andreafalzetti: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by felladrin** [comment]
🤔 Even when running only the test for a single IDE, it still can take 40 mins before failing [[1](https://werft.gitpod-dev.com/job/gitpod-build-ide-integration-tests.15)].

**Comment by felladrin** [comment]
Yeah, I've tried connecting with RubyMine with the same repo from the test (https://github.com/gitpod-samples/template-ruby-on-rails-postgres) and it got stuck on connecting:

image

**Comment by felladrin** [comment]
Opening https://github.com/gitpod-io/empty with RubyMine works.

**Comment by felladrin** [comment]
I've confirmed I was able to open https://github.com/forem/forem with RubyMine 2022.3.1.

So there's some issue with https://github.com/gitpod-samples/template-ruby-on-rails-postgres. (cc @Siddhant-K-code)

**Comment by Siddhant-K-code** [comment]
> I've confirmed I was able to open https://github.com/forem/forem with RubyMine 2022.3.1.
>
> So there's some issue with https://github.com/gitpod-samples/template-ruby-on-rails-postgres. (cc @Siddhant-K-code)


@felladrin, On VS Code It seems to be working perfectly 💯 

image

**Comment by felladrin** [comment]
Yeah, it's not working only with RubyMine. Could you test on your side?

**Comment by Siddhant-K-code** [comment]
> Could you test your account to confirm if it was not a problem only on my side?

Aha! No Luck 😞 

image


⚠️  Is Prebuilds acting normally with RubyMine? Since our recent change in teams, projects, and prebuilds, I am sure that `forem` are not under prebuilds enabled... So All tasks would be running after starting the IDE.


(**Unrelated**)Also, When I opened Rubymine & Try connecting w/the workspace URL, Sends out this error =>


https://user-images.githubusercontent.com/55068936/213965083-901891f7-351c-44e8-9d18-81822cfae8af.mov

**Comment by felladrin** [comment]
Thanks for confirming it, @Siddhant-K-code!
Let's take that issue to a separate thread:
- https://github.com/gitpod-io/gitpod/issues/15969

**Comment by felladrin** [comment]
ℹ️ Going to debug the integration test steps [[1](https://www.notion.so/gitpod/JetBrains-Integration-Tests-c8a96526db364f6397f1c4a5d5ff73be)], as we noticed tests are currently failing (timing out) for all IDEs.

**Pull request closed without merging**
