### PR TITLE
Add workspace count metric

### LINKED ISSUE #7202: [agent-smith] Add workspace count metric
agent-smith detects workspaces based on the process structure. It's possible we break that inadvertently. If agent-smith had a metric which told us how many workspaces it's currently seeing, we could detect such situations if they happen.

### PR DESCRIPTION
**Pull request by Furisto**
## Description
Add a metric that shows the difference between what agent-smith is seeing and the workspaces ws-manager knows about. If there is a considerable difference we probably have broken the workspace detection in agent-smith.

agent-smith-detected-workspaces

## Related Issue(s)
Fixes #7202

## How to test
Open Grafana in preview environment, select agent-smith dashboard and look at "Detected workspaces" metric.

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **furisto** after the PR has been reviewed.

Associated issue: *#7202*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ee/agent-smith/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/agent-smith/OWNERS)**
- **[operations/observability/mixins/workspace/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/operations/observability/mixins/workspace/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by Furisto** [comment]
/werft run with-helm with-observability with-clean-slate-deployment

**Comment by Furisto** [comment]
/werft run with-helm with-observability with-clean-slate-deployment

**Comment by Furisto** [comment]
/werft run with-helm with-observability with-clean-slate-deployment

**Review by sagor999 — APPROVED** [review]

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: ebd8833a913e0aaf9cb15dc9fe7c31d687e99ccd</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7816#pullrequestreview-865534348" title="Approved">sagor999</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **furisto** after the PR has been reviewed.

Associated issue: *#7202*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ee/agent-smith/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/agent-smith/OWNERS)**
- **[operations/observability/mixins/workspace/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/operations/observability/mixins/workspace/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7816#issuecomment-1025535940" title="Approved">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/7816#pullrequestreview-865534348" title="Approved">sagor999</a>*

Associated issue: *#7202*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ee/agent-smith/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/agent-smith/OWNERS)~~ [csweichel]
- ~~[operations/observability/mixins/workspace/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/operations/observability/mixins/workspace/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
