### PR TITLE
[server] don't always throw exception in deleteUser

### LINKED ISSUE #5262: Deleting account returns an error and does not log out the user properly
### Bug description

When a user tried to delete their account from the Account section in Settings the product returns an error in console and does not log out the user properly.

```js
Uncaught (in promise) Error: Request deleteAccount failed with message:
```

### Steps to reproduce

1. Go to [`/account`](https://gitpod.io/account)
2. Click _Delete Account_ button.
3. Type your email to confirm.
4. Click _Delete Account_.

### Expected behavior

The user should not see any error in the console and they should be properly logged out.

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JanKoehnlein**
Fixes #5262

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **jankoehnlein** after the PR has been reviewed.

Associated issue: *#5262*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by AlexTugarev — APPROVED** [review]
LGTM!

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: afc681ebe5a329e2074dea9647ad3403adea8cae</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5288#pullrequestreview-734725461" title="Approved">AlexTugarev</a>*

Associated issue: *#5262*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [AlexTugarev]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by JanKoehnlein** [comment]
Branch name too long 👎

**Pull request closed without merging**
