### PR TITLE
Directly tunnel websocket connection to ssh server

### PR DESCRIPTION
**Pull request by jeanp413**
## Description

Created another endpoint `tunnel2` for now to keep backwards compatibility for old versions of local-app

## How to test

- Try connecting tunneling ssh over websocket, it should work

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - jp-test-993</li>
	<li><b>🔗 URL</b> - <a href="https://jp-test-993.preview.gitpod-dev.com/workspaces" target="_blank">jp-test-993.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
</ul>

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

/hold

### CODE REVIEW

**Comment by akosyakov** [comment]
@jeanp413 @mustard-mh Could you add an explanation to the description here please 🙏 I'm missing a context why we need another way.

**Comment by jeanp413** [comment]
@akosyakov this is just tech debt/cleanup and maybe will improve performance slightly as we are removing one indirection, it doesn't make sense to have another ssh server in front of the real one, we can talk about it tomorrow

**Comment by akosyakov** [comment]
We discussed yesterday that original /tunnel endpoint was to enable port forwarding for various ports where SSH was used as an implementation detail. We agreed to add a new endpoint specific only to SSH to easy integration in VS Code Desktop. It won't improve though performance, since it is still TCP over TCP.

**Review by akosyakov — APPROVED** [review]

**Pull request merged**
