### PR TITLE
[usage] Implement usage-capping

### LINKED ISSUE #12264: Cap reported Usage to max(Usage, SpendingLimit) before reporting to Stripe
When creating an invoice, we need to cap the invoice to maximum of the usage limit. This is to ensure we conform to users expectations.

In practice, this means the following:
* When we are updating an invoice with a new value, we need to take into consideration the spending limit set.
* When a spending limit is greater than the current value, do nothing special.
* When the spending limit is lower or equal to current used value, cap the invoice to the spending limit.

Optionally:
* Tag the invoice (in Stripe) with metadata saying what the spending limit is, such that admins are not surprised when it is not increasing and do not need to hunt across multiple systems.

The number of credits used can exceed the spending limit due to eventual consistency in the system between reconciliation of usage starting of new workspaces. As such, this difference is where we are losing money. To monitor how much this diff is, we want to expose a metric which measures the diff between real usage and spending limit for each attribution.

* Add a metric which tracks "billing accuracy" or "credits lost"

Side change:
- Move ownership of the DB Cost Center to the Usage Component

### PR DESCRIPTION
**Pull request by laushinka**
## Description
Implements usage-capping. 

## Related Issue(s)

Fixes #12264 
Depends on #12382 and #12458

## How to test
Unit tests.

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@laushinka: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by laushinka** [comment]
`size_test.go` seems to be flaky.

/werft run

**Comment by easyCZ** [comment]
Closing, as this has changed significantly and is no longer immediate attention.

**Pull request closed without merging**
