### PR TITLE
Enable git integrations of Bitbucket for self-hosted Gitpod

### LINKED ISSUE #9172: [self-hosted] Add bitbucket.org to the list of auth providers configurable during Gitpod install
There is currently no self-hosted configuration UI to setup OAuth for bitbucket.org. Only GitLab and GitHub are supported.

Self-hosted Gitpod users should be able to authenticate with bitbucket.org.

### PR DESCRIPTION
**Pull request by AlexTugarev**
Fixes #9172

### How to test
1. First, log in using GitHub/GitLab
2. Switch to Integrations and create a custom Git Integration for bitbucket.org

```release-notes
Enable git integrations of Bitbucket for self-hosted Gitpod.
```

### Note for reviewers

Initially the branch of this PR contains an extra commit (3007c911bbdaf58f38df1af33385607e131120fa) which is meant to be removed after testing.

### CODE REVIEW

**Comment by AlexTugarev** [comment]
/hold 

 - [ ] remove test commit https://github.com/gitpod-io/gitpod/pull/9894/commits/3007c911bbdaf58f38df1af33385607e131120fa

**Comment by AlexTugarev** [comment]
@jldec, have a look, please!

**Review by jldec — APPROVED** [review]
LGTM
thank you @AlexTugarev 
Configured OAuth consumer for a bitbucket.org workspace under my own account

Copied Permissions from the bitbucket.org config used on gitpod.io (see image below)
Screenshot 2022-05-11 at 10 28 27

Users will see confirmation like this
Screenshot 2022-05-11 at 10 31 16

**Pull request merged**
