### PR TITLE
Fix dotfiles permission

### PR DESCRIPTION
**Pull request by iQQBot**
## Description

In #7569 we change to use content-services API to use download dotfiles, but it is not able to set user credential, so the .dotfiles belong root

Also, it fixes some breaking changes in https://github.com/gitpod-io/gitpod/pull/7569, which is not expected (exec multiple installation scripts, the expect is exec only once: see [document](https://www.gitpod.io/docs/config-dotfiles) )

> Gitpod will recognize and run **one of** the following install scripts from your dotfiles repository.
> If there is **no install script**, your dotfiles will be symlinked into /home/gitpod.

## Related Issue(s)

Fixes #

## How to test

1. Set a dotfiles
2. open workspaces
3. check the ~/.dotfiles permission, it should belong `gitpod`
4. check the behavior, It should work as the [document](https://www.gitpod.io/docs/config-dotfiles)  says

## Release Notes

```release-note
NONE
```

## Documentation

- [x] /werft version=staging-pd-fix-dotfiles
- [x] /werft namespace=staging-pd-fix-dotfiles

### CODE REVIEW

**Review by Furisto — DISMISSED** [review]

**Comment by mustard-mh** [comment]
branch chars too much, not work to build staging 😅

**Comment by mustard-mh** [comment]
image
owner not change 

cc @iQQBot

**Comment by mustard-mh** [comment]
`~/.dotfile` and `~/.dotfile/*` belong to `gitpod` now

**Pull request merged**
