### PR TITLE
Switch registry-facade from hostPort to nodePort and remove hostPort from ws-daemon

### PR DESCRIPTION
**Pull request by aledbf**
## Description

In EKS we see a delay with hostPorts that impacts users during a scale-up event. We found out it takes more than six seconds after the readinessProbes pass to start accepting traffic from the host (containerd). Switching to nodePort solves the issue.

## Release Notes
```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-slow-database
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=workspace
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by kylos101** [comment]
Started again with `with-gce-vm` :crossed_fingers:

**Comment by kylos101** [comment]
/werft run with-integration-tests=workspace with-large-vm=true with-gce-vm=true recreate-vm=true

**Comment by kylos101** [comment]
/werft run with-large-vm=true with-gce-vm=true recreate-vm=true

**Comment by kylos101** [comment]
The configmap has the wrong port #:
```
gitpod /workspace/gitpod (aledbf/nodeport) $ kubectl describe cm ws-manager | grep 30000
    "registryFacadeHost": "reg.aledbf-nodeport.preview.gitpod-dev.com:30000",
```

The installer seems okay:
https://github.com/gitpod-io/gitpod/blob/d3fc6c06b5100bc3273fbc8be8d700c2ea963123/install/installer/pkg/components/ws-manager/configmap.go#L226

Gonna delete and recreate the VM...again.

**Comment by kylos101** [comment]
Made these changes manually via `kubectl edit` and it works now:

```
gitpod /workspace/gitpod (aledbf/nodeport) $ kubectl describe cm ws-manager | grep -B 1 31740
    "wsdaemon": {
      "port": 31740,
gitpod /workspace/gitpod (aledbf/nodeport) $ kubectl describe cm ws-manager | grep registryFacadeHost
    "registryFacadeHost": "reg.aledbf-nodeport.preview.gitpod-dev.com:31750",
```

**Comment by kylos101** [comment]
Via `kubectl edit`

Fixed image pull:
```
gitpod /workspace/gitpod/install/installer (aledbf/nodeport) $ kubectl describe cm ws-manager | grep registryFacadeHost
    "registryFacadeHost": "reg.aledbf-nodeport.preview.gitpod-dev.com:31750",
```

Allows content-init to start:
```
gitpod /workspace/gitpod/install/installer (aledbf/nodeport) $ kubectl describe cm ws-manager | grep -B 1 31740
    "wsdaemon": {
      "port": 31740,
```

But fails with:
```
cannot initialize workspace: timed out attempting to connect to Gitpod ws-daemon
```

:sleepy:

**Comment by aledbf** [comment]
> Does this approach nodePort still go through iptables and do an extra layer of forwarding?
Only iptables. The hostPort approach is an CNI plugin (to calico/cilium) + iptables.

> How about direct using hostNetwork? Are there any security concerns?

Security concerns, and also, we need to reach ws-manager, something that would be difficult to do with hostNetwork.

**Review by vulkoingim — APPROVED** [review]

**Review by kylos101 — APPROVED** [review]
:shipit:

**Pull request merged**
