### PR TITLE
remove with-helm and associated functions

### LINKED ISSUE #9844: Remove "with-helm=true" support from Preview Environments
## Is your feature request related to a problem? Please describe

In preparation to delete the Helm Chart (https://github.com/gitpod-io/gitpod/issues/9842), delete the `with-helm` annotation support from Werft Jobs. With that change, Helm can no longer be used in preview environments. 

## Describe the behaviour you'd like
Delete all code that implements the following flag:

https://github.com/gitpod-io/gitpod/blob/dbc5805c386ab7ae7d000aff044f3ec0618ffc64/.werft/jobs/build/job-config.ts#L90

## Additional context
We should also confirm with all product teams that nobody still depends on this feature.

### PR DESCRIPTION
**Pull request by liam-j-bennett**
## Description
Removes the now unused `with-helm` parameter and underlying functions

## Related Issue(s)

Fixes #9844 

## Release Notes
Remove the `with-helm` option for running preview environments

### CODE REVIEW

**Comment by roboquat** [comment]
@liam-j-bennett: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by meysholdt — APPROVED** [review]
Awesome to see so many LOC go away :-D
Code changes LGTM 🚀

**Pull request merged**
