### PR TITLE
[prebuilds] respect gitpod.yml in GHE

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description
github enterprise integration should respect the `prebuilds` section in the `.gitpod.yml`.

## Related Issue(s)

See #16139

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]

**Comment by geropl** [comment]
@svenefftinge My understanding was that we want to deprecate all configuration of Prebuilds within the repository, and instead rely on Project config completely.

Example:
Imagine two Orgs using the same underlying repo in their Projects. They should be able to configure Prebuilds independently. :lotus_position:

**Comment by svenefftinge** [comment]
> @svenefftinge My understanding was that we want to deprecate all configuration of Prebuilds within the repository, and instead rely on Project config completely.

Yes, this is just a "bug fix"

**Pull request merged**
