### PR TITLE
Server-side apply of ceph CRDs + wait until ready

### PR DESCRIPTION
**Pull request by vulkoingim**
## Related Issue(s)

Fixes https://github.com/gitpod-io/ops/issues/3923
## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by vulkoingim** [comment]
I've run a bunch of jobs and I don't see the error described in the issue happening any longer. @gitpod-io/platform can you ✅ , please?

**Review by mads-hartmann — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
