### PR TITLE
Update go-redis to v9

### PR DESCRIPTION
**Pull request by aledbf**
## Description

The main change in v9 is the removal of asynchronous cancellation based on the context timeout

## Release Notes
```release-note
NONE
```

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by roboquat** [comment]
@aledbf: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by kylos101** [comment]
@aledbf why the upgrade? I recall related to Dedicated. For example, maybe fixes an intermittent bug on image pull? I will try to test briefly in workspace-preview.

**Comment by aledbf** [comment]
@kylos101 this has nothing to do with dedicated but with how the library cancels the context in code.
https://github.com/redis/go-redis/blob/master/CHANGELOG.md

**Comment by kylos101** [comment]
Rebased with main, will add redis to preview (if it isn't there), reconfigure registry-facade to use, and run a brief test.

Note: I tried installing with this build version in `workspace-preview`, which I think has `redis`, but got:
image

**Comment by kylos101** [comment]
rebase with main is :+1: , preview env is online

**Comment by kylos101** [comment]
/hold

We should test briefly in an ephemeral cluster; I will budget time to do later this week.

**Review by kylos101 — APPROVED** [review]
Aside from hold, :+1:

**Comment by kylos101** [comment]
Testing here: https://werft.gitpod-io-dev.com/job/ops-workspace-cluster-new-main.321

**Comment by kylos101** [comment]
No issues starting workspaces with loadgen or running manually.

image

**Comment by kylos101** [comment]
/unhold

:shipit: 

While inspecting logs to observe cluster behavior:
https://github.com/gitpod-io/gitpod/pull/17099
https://linear.app/gitpod/issue/WKS-30/registry-facade-node-labeler-check-yields-tls-handshake-error-from

**Review by akosyakov — APPROVED** [review]

**Pull request merged**
