### PR TITLE
updgrade to VS Code 1.55.x

### LINKED ISSUE #3553: [vscode] terminals resizing issues on reload
### Bug description

On page reload the content is not nicely resized.

### Steps to reproduce

- Start a workspace with VS Code
- Reload the page and output should be nicely formatted.
- But it is rendered narrowly instead.

There are also strange messages in terminals on start sometimes:
```
your 131072x1 screen size is bogus. expect trouble
```

### Expected behavior

_No response_

### Example repository

_No response_

### LINKED ISSUE #3694: updgrade to VS Code 1.55.x
Follow https://www.notion.so/gitpod/Gitpod-Code-Upgrade-1aa1dfcfdc5147869ec5ffcf86f430a6

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #3694: updgrade to VS Code 1.55.x
- fix #3553: see https://github.com/gitpod-io/gitpod/issues/3553#issuecomment-819504638

Changes in Gitpod Code: https://github.com/gitpod-io/vscode/commit/cbe1690286445dde2260d88e6de5bce1413465c6

#### How to test

- websockets and workers are properly proxied
    - diff editor should be operatable
    - trigger reconnection with `window.WebSocket.disconnectWorkspace()`, check that old websockets are closed and new opened of the same amount, it can take around 30s
- that user data are sync across workspaces as well as on workspace restart, especially for extensions
    - test that extensions from .gitpod.yml are installed without sync
    - ignore CORS issues in logs, they are not matter
- terminals are preserved and resized properly between window reloads
- workspace specific commands should work, i.e. F1 → type Gitpod prefix
- that a PR view is preloaded on the PR url, make sure that you grant process scopes for GitHub installation, namely: `user: read` and `repo`
- test gp open and preview

### CODE REVIEW

**Comment by akosyakov** [comment]
Webview are broken:
```
resourceLoader.ts:169 Error: Unable to read file 'vscode-remote://amaranth-crane-ek2ss7ec.ws-dev.akosyakov-updgrade-to-vs-code-x-3694.staging.gitpod-dev.com:443/vscode-resource?{"requestResourcePath":"/ide/extensions/simple-browser/media/codicon.css"}' (Error: Unable to resolve non-existing file 'vscode-remote://amaranth-crane-ek2ss7ec.ws-dev.akosyakov-updgrade-to-vs-code-x-3694.staging.gitpod-dev.com:443/vscode-resource?{"requestResourcePath":"/ide/extensions/simple-browser/media/codicon.css"}')
    at FileService.doReadFileStream (fileService.ts:525)
    at async readFileStream (resourceLoader.ts:75)
    at async loadLocalResource (resourceLoader.ts:153)
    at async IFrameWebview.loadResource (webviewElement.ts:206)
```

**Comment by akosyakov** [comment]
It should be good now.

**Comment by csweichel** [comment]
- websockets and workers are properly proxied
    - ✅  diff editor should be operatable
    - ⚠️ trigger reconnection with `window.WebSocket.disconnectWorkspace()`, check that old websockets are closed and new opened of the same amount ; running `window.WebSocket.disconnectWorkspace()` had no discerneble effect
- that user data are sync across workspaces as well as on workspace restart, especially for extensions
    - ⚠️ test that extensions from .gitpod.yml are installed without sync: could not test due to open-vsx issues
- ✅  terminals are preserved and resized properly between window reloads
- ✅  workspace specific commands should work, i.e. F1 → type Gitpod prefix
- ❌ that a PR view is preloaded on the PR url: I tried to open https://github.com/gitpod-io/gitpod/pull/3937 as context URL and no PR view was shown
- ✅  test gp open and preview

**Comment by akosyakov** [comment]
>  trigger reconnection with window.WebSocket.disconnectWorkspace(), check that old websockets are closed and new opened of the same amount ; running window.WebSocket.disconnectWorkspace() had no discerneble effect

It can take a while, like 30 seconds before disconnect is detected, see below triggered at 23:12, reconnected at 23:32
Screenshot 2021-04-16 at 09 23 36

>  test that extensions from .gitpod.yml are installed without sync: could not test due to open-vsx issues

If it is about CORS errors in devtools, you can ignore them. Most important that search and install from user perspective should work.

> that a PR view is preloaded on the PR url: I tried to open #3937 as context URL and no PR view was shown

Please make sure that you granted proper permissions, otherwise you should see:
Screenshot 2021-04-16 at 09 26 01

**Comment by akosyakov** [comment]
@csweichel I pushed a fix for preloading the PR view.

**Review by csweichel — APPROVED** [review]
Works after signing in

**Pull request merged**
