### PR TITLE
Corrects minio helm repo command

### LINKED ISSUE #4144: [Docs] README error on helm repo add commands
### Bug description

Readme tells me to add two helm repos with the same name. The second fails to add.

### Steps to reproduce

Follow README instructions:

```
helm repo add stable https://charts.helm.sh/stable
helm repo add stable https://helm.min.io/
```

### Expected behavior

Add two helm repos

### Example repository

_No response_

### Anything else?

Minio's own documentation suggests using this so for consistency, I think that should be used.

`helm repo add minio https://helm.min.io/`

### PR DESCRIPTION
**Pull request by flickerfly**
Resolves #4144

### CODE REVIEW

**Review by ghuntley — APPROVED** [review]

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: d4c353a20021c0c9c74e0ad1f3c18f878d0762d7</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4145#pullrequestreview-720787076" title="Approved">ghuntley</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rl-gitpod** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @rl-gitpod` in a comment when ready.

Associated issue: *#4144*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4145#pullrequestreview-720787076" title="Approved">ghuntley</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4145#issuecomment-908000321" title="Approved">rl-gitpod</a>*

Associated issue: *#4144*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [rl-gitpod]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
