### PR TITLE
migrate oss users to ubp

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description
This migration updates the cost centers for all users that have an active free-open-source plan and besides 'free' no other active plan. 
The update includes:
- start the billing cycle the moment the migration runs
- end the billing cycle one month later
- spendingLimit: 1000
- billingStrategy: other (so we finalize the invoice at the end of the period)

NOTE: I ran the SELECT part of the query against the production database. It returns 1247 entries and takes 10 sec.

## Related Issue(s)

Fixes #https://github.com/gitpod-io/gitpod/issues/14819

## How to test

In the preview environment 
- create a user
- grant professional open source in admin dashboard
- manual execute the migration query against the DB
- create a 'Gitpod something' team so the user gets UBP activated
- verify the user has "open source" plan and 1000 credits in billing/admin

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-large-vm
- [x] /werft with-payment
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by roboquat** [comment]
@svenefftinge: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
@svenefftinge What's the motivation to put this into a migration? Note that this will get executed twice against the same data set. Won't that break some assumptions?
In the past we applied this kind of changes directlym and IMO we should do the same with this one.

> NOTE: I ran the SELECT part of the query against the production database. It returns 1247 entries and takes 10 sec.

This is ok-ish, but would be nicer to not trigger more than 1000 changes at a time. That tends to result in bad db-sync behavior.

**Comment by svenefftinge** [comment]
> @svenefftinge What's the motivation to put this into a migration? Note that this will get executed twice against the same data set. Won't that break some assumptions? In the past we applied this kind of changes directlym and IMO we should do the same with this one.
> 
Ah, yes with db-sync this is not great, as we'll end up with twice as many rows. so better to apply this manually as long as db-sync is still active.
Going forward I think we should prefer migrations, as they are applied on all installations and it allows us to keep track of such changes.

**Comment by easyCZ** [comment]
How are we proceeding on this change given the migration is not the way to go?

**Comment by svenefftinge** [comment]
> How are we proceeding on this change given the migration is not the way to go?

We are going to apply the change manually. Will close this PR once that happened.

**Comment by jldec** [comment]
Open Source users' cost centers applied manually.

**Pull request closed without merging**
