### PR TITLE
[content-service] Remove  GetWorkspaceDownloadURL

### PR DESCRIPTION
**Pull request by easyCZ**
## Description

Removes GetWorksapceDownloadURL

## Related Issue(s)

* Relates to https://github.com/gitpod-io/gitpod/issues/14483
* Depends on https://github.com/gitpod-io/gitpod/pull/14522

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

/hold for dependency

### CODE REVIEW

**Review by laushinka — APPROVED** [review]

**Comment by sagor999** [comment]
@easyCZ In your issue description there is a typo? `Depends on https://github.com/gitpod-io/gitpod/pull/14526` which is this PR. So probably it depends on some other PR?

**Comment by easyCZ** [comment]
Thanks. Depends on https://github.com/gitpod-io/gitpod/pull/14522

**Review by jenting — APPROVED** [review]

**Pull request merged**
