### PR TITLE
[ReadMe] - update Integrated Code reviews link

### PR DESCRIPTION
**Pull request by dkp1903**
## Description

The code reviews link in the ReadMe points to a non-existent page. As suggested by @axonasif , updated the link to the right resource.

## Related Issue(s)

[7911](https://github.com/gitpod-io/gitpod/issues/7911)

Fixes #

## How to test
1. Go to: https://github.com/gitpod-io/gitpod - ReadMe.md 
2. Go to Features: https://github.com/gitpod-io/gitpod#features
3. Click "Integrated code reviews" - the URL will go to the existing page of Contexts on Docs 

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
@dkp1903: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **kylos101** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @kylos101` in a comment when ready.

Associated issue: *#7911*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by pawlean — COMMENTED** [review]
LGTM

**Comment by meysholdt** [comment]
Hi Dushyant, thank you for your contribution! We need a signed CLA to merge it - I've reached out to you via email.

**Comment by dkp1903** [comment]
Hi, @meysholdt 

Glad to help. I've signed the CLA

**Comment by meysholdt** [comment]
Hi @dkp1903! Thank you for signing :-D

**Review by gtsiolis — APPROVED** [review]
Thanks for contributing, @dkp1903! 🧡 

Thanks also @pawlean and @meysholdt for helping out. 🏀

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 3ef0da5b1d28794f1f191cb67b96959a424f12af</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7913#pullrequestreview-869811666" title="Approved">gtsiolis</a>*

Associated issue: *#7911*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [gtsiolis]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
