### PR TITLE
Remove unused workspace port auth

### PR DESCRIPTION
**Pull request by AlexTugarev**
Seems to be forgotten about. 

## Related Issue(s)

Fixes #

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`
</details>

/hold

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]
Change looks good, but I've got no context on that feature

**Comment by AlexTugarev** [comment]
> Change looks good, but I've got no context on that feature 

This is obsolete. 

cc. @akosyakov, is that correct?

**Comment by akosyakov** [comment]
> cc. @akosyakov, is that correct?

I do not know this code

**Pull request merged**
