### PR TITLE
Provide endpoint for getting workspace classes from cluster

### PR DESCRIPTION
**Pull request by Furisto**
## Description
Adds an endpoint to ws-manager that allows to retrieve the workspace classes that are supported by the cluster. This will be called by the meta cluster side. The information returned is the identifier and the name of the workspace class. The name is what is displayed to the user and the id is what will be used to refer to the class internally. That way we can change the name without having to update internal references.

## Related Issue(s)

Partially fixes #https://github.com/gitpod-io/gitpod/issues/10842

## How to test
I used this simple test program. You need to get the tls config from ws-manager first using gpctl clusters get-tls-config. Port-forward ws-manager to 12001 and then execute `test --tls ./ws-man`
```
import (
	"crypto/tls"
	"crypto/x509"
	"io/ioutil"
	"path/filepath"

	"github.com/gitpod-io/gitpod/ws-manager/api"
	log "github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/credentials/insecure"
)

var testOpts struct {
	TLSPath string
}

var testCmd = &cobra.Command{
	Use:   "test",
	Short: "test",
	Run: func(cmd *cobra.Command, args []string) {
		var opts []grpc.DialOption
		if testOpts.TLSPath != "" {

			log.Info("Got tls")
			ca, err := ioutil.ReadFile(filepath.Join(testOpts.TLSPath, "ca.crt"))
			if err != nil {
				log.Fatal(err)
			}
			capool := x509.NewCertPool()
			capool.AppendCertsFromPEM(ca)
			cert, err := tls.LoadX509KeyPair(filepath.Join(testOpts.TLSPath, "tls.crt"), filepath.Join(testOpts.TLSPath, "tls.key"))
			if err != nil {
				log.Fatal(err)
			}
			creds := credentials.NewTLS(&tls.Config{
				Certificates: []tls.Certificate{cert},
				RootCAs:      capool,
				ServerName:   "ws-manager",
			})
			opts = append(opts, grpc.WithTransportCredentials(creds))
		} else {
			opts = append(opts, grpc.WithTransportCredentials(insecure.NewCredentials()))
		}

		conn, err := grpc.Dial("localhost:12001", opts...)
		if err != nil {
			log.Fatal(err)
		}
		defer conn.Close()
		client := api.NewWorkspaceManagerClient(conn)

		resp, err := client.DescribeCluster(context.Background(), &api.DescribeClusterRequest{})
		if err != nil {
			log.Fatal(err)
		}

		for _, c := range resp.WorkspaceClasses {
			log.Infof("%v %v", c.Id, c.DisplayName)
		}
	},
}

func init() {
	rootCmd.AddCommand(testCmd)
	testCmd.Flags().StringVar(&testOpts.TLSPath, "tls", "", "path to ws-manager's TLS certificates")
}
```

## Release Notes

```release-note
None
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Review by sagor999 — APPROVED** [review]
LGTM

/hold 
for a comment regarding potentially missing json block. Feel free to unhold if that json block is not necessary there.

**Review by corneliusludmann — APPROVED** [review]
changes is self-hosted owned files look good

**Comment by Furisto** [comment]
Hey @aledbf, can you take a look please?

**Review by aledbf — APPROVED** [review]

**Pull request merged**
