### PR TITLE
fix: Loading Spinner Alignment

### LINKED ISSUE #11696: Improve usage loading spinner style
### Problem to solve

Back in https://github.com/gitpod-io/gitpod/pull/11687, a loading indicator (spinner) was added while the data is loading. Thanks, @laushinka and @easyCZ!

Although, there are no concrete guildelines yet on the loading indicators (spinners), we've been using a slightly different pattern for the loading spinner for fetching data-heavy pages.

| Branches | Prebuilds | Usage |
|-|-|-|
| gitpod-staging com_t_gitpod_gitpod | gitpod-staging com_t_gitpod_gitpod_prebuilds (1) | gitpod-staging com_t_gitpod_usage |

### Proposal

Update the loading indicator (spinner) of the usage page to follow the style of the rest of the instances across the product.

Things to consider:
1. Align horizontally loading spinner with the loading text.
2. Use sentence case instead of uppercase.
3. Use the same top margin from the header.

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description
Fixes Loading Spinner Alignments

## Related Issue(s)

Fixes #11696

## How to test

- Open Preview
- Open Teams Usage 
- See Loading Spinner & text change :eyes:

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by geropl** [comment]
preview env blocked by [this issue](https://gitpod.slack.com/archives/C032A46PWR0/p1672993390520819?thread_ts=1672910366.415729&cid=C032A46PWR0)

**Comment by Siddhant-K-code** [comment]
@geropl I have updated the branch with main (along with this fix: https://github.com/gitpod-io/gitpod/pull/15597)

Builds should be fine now 😄

**Comment by geropl** [comment]
@Siddhant-K-code Can you invite me to your team? I cannot create one due to an unrelated error.

**Comment by Siddhant-K-code** [comment]
> @Siddhant-K-code Can you invite me to your team? I cannot create one due to an unrelated error.

@geropl I've DM'ed you :)

**Review by geropl — APPROVED** [review]
Tested, and LGTM! :pray:

**Comment by gtsiolis** [comment]
Thanks for fixing this, @Siddhant-K-code! 🍪

**Pull request merged**
