### PR TITLE
[code] build stable code image for 1.70.2

### PR DESCRIPTION
**Pull request by jeanp413**
## Description

Build code image for 1.70.2

## Related Issue(s)

Related https://github.com/gitpod-io/gitpod/issues/11638

## How to test

- Check about dialog says 1.70.2

## Release Notes

```release-note
NONE
```

## Werft options:

- [x] /werft with-preview

### CODE REVIEW

**Comment by jeanp413** [comment]
@filiptronicek can you approve :pray:

**Review by filiptronicek — APPROVED** [review]
Looking good bud! (SHA checks out)
image

**Pull request merged**
