### PR TITLE
UI updates to admin dashboard

### LINKED ISSUE #16238: Update the page header in admin dashboard
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/16164#discussion_r1094710110, the admin dashboard:
1. No longer uses an active state for the admin menu at the top.
2. Does not use a generic settings page header as the rest of the product.

### Proposal

Here's a list of MVC steps that could be tackled all in one step or separate PRs.
1. Use a generic page header for all top-level pages in the admin dashboard, see screenshot below.
2. Keep the admin menu at the top active when navigating through the top-level pages in the admin dashboard.
3. https://github.com/gitpod-io/gitpod/issues/7879

| Page header (BEFORE) | Page header (AFTER) |
|-|-|
| Screenshot 2023-02-06 at 4 35 22 PM | Screenshot 2023-02-06 at 4 33 07 PM |
| user-before | user-after |

### PR DESCRIPTION
**Pull request by Devansu-Yadav**
## Description

- Sets an active state for the admin menu when navigating through the top-level pages in the admin dashboard.
- Uses a generic page header for all top-level pages on the dashboard.
- Removes the sidebar menu and uses tabs for all top-level pages.

## Related Issue(s)

Fixes #16238 & #7879 

## Release Notes

```release-note
- Active state on the admin menu for all top-level pages on the admin dashboard.
- Generic page header for all top-level pages.
- Tabs instead of the sidebar menu for all pages on the admin dashboard.
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-ee-license
- [ ] with-slow-database
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by Devansu-Yadav** [comment]
> /werft run with-preview=true
> 
> 👍 started the job as [gitpod-build-update-admin-ui-fork.0](https://werft.gitpod-dev.com/job/gitpod-build-update-admin-ui-fork.0) (with `.werft/` from `main`)

@gtsiolis Seems like this `/werft` job failed. How do I preview the changes? 😅

**Comment by Devansu-Yadav** [comment]
> /werft run with-clean-slate-deployment=true recreate-vm=true
> 
> 👍 started the job as [gitpod-build-update-admin-ui-fork.1](https://werft.gitpod-dev.com/job/gitpod-build-update-admin-ui-fork.1) (with `.werft/` from `main`)

@gtsiolis I'm able to access the preview environment of the dashboard. Could you provide admin access so I can check if the changes made in this PR reflect correctly or not?

**Comment by gtsiolis** [comment]
@Devansu-Yadav DONE!

**Comment by Devansu-Yadav** [comment]
> /werft run with-clean-slate-deployment=true recreate-vm=true
> 
> 👍 started the job as [gitpod-build-update-admin-ui-fork.2](https://werft.gitpod-dev.com/job/gitpod-build-update-admin-ui-fork.2) (with `.werft/` from `main`)

@gtsiolis Seems like I'd need admin access again 😅

**Review by gtsiolis — CHANGES_REQUESTED** [review]
@Devansu-Yadav Overall, looks good. Granted your user admin permissions again.

Some points to consider:
1. Adding width limits (see `.app-container` class) on all pages.
2. Adding some extra top margin on license and settings pages.
3. Make sure the admin menu is active on all top-level pages, not just users.

| Users | Org |
|-|-|
| Screenshot 2023-02-10 at 14 54 58 (2) | Screenshot 2023-02-10 at 14 55 11 (2) |

**Comment by gtsiolis** [comment]
Besides the review comments above in https://github.com/gitpod-io/gitpod/pull/16307#pullrequestreview-1293134051, two more points:
1. You'll also need to sign a CLA[[1](https://powerforms.docusign.net/30e1aa46-cce5-4bc6-a933-ad02cd8d5ada?env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&accountId=86335c2c-01b9-4edc-a187-014f5150a112)] once before merging your first contribution. We're working on optimizing the CLA signing process and could take us a while to get back to this before merging. Cc @meysholdt 
2. We're moving large portions of the admin dashboard to organizations, previously known as teams, which could make some of these changes obsolete soon. Still, experimenting with the tabs could be interesting to adopt for the orgs settings.

Cross-posting [relevant discussion](https://gitpod.slack.com/archives/C032A46PWR0/p1676011323767159) (internal) for visibility. Cc @geropl

**Comment by Devansu-Yadav** [comment]
> 

Thanks for the reply! I'll make the appropriate changes 😄

**Comment by Devansu-Yadav** [comment]
> Some points to consider:
> 
> 1. Adding width limits (see `.app-container` class) on all pages.
> 2. Adding some extra top margin on license and settings pages.
> 3. Make sure the admin menu is active on all top-level pages, not just users.

@gtsiolis Made these changes. Need to check them once through the preview environment with the admin privilege.

**Comment by Devansu-Yadav** [comment]
> 1. You'll also need to sign a CLA[[1](https://powerforms.docusign.net/30e1aa46-cce5-4bc6-a933-ad02cd8d5ada?env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&accountId=86335c2c-01b9-4edc-a187-014f5150a112)] once before merging your first contribution. We're working on optimizing the CLA signing process, this is a heads-up it could take us a while to get back to this before merging. Cc @meysholdt
>    
>    * @Devansu-Yadav Let us know when you've signed the CLA. 🏓

@gtsiolis I have signed the CLA too!

**Comment by gtsiolis** [comment]
/werft run with-clean-slate-deployment=true recreate-vm=true with-preview=true

**Comment by gtsiolis** [comment]
/werft run with-clean-slate-deployment=true recreate-vm=true with-preview=true

**Comment by Devansu-Yadav** [comment]
> /werft run with-clean-slate-deployment=true recreate-vm=true with-preview=true
> 
> 👍 started the job as [gitpod-build-update-admin-ui-fork.5](https://werft.gitpod-dev.com/job/gitpod-build-update-admin-ui-fork.5) (with `.werft/` from `main`)

@gtsiolis I'll need admin user privileges again 😅

**Comment by Devansu-Yadav** [comment]
> @gtsiolis I'll need admin user privileges again 😅

@gtsiolis Seems like I won't need the admin privileges to test out the changes, as I was able to make it work on the development server of the dashboard. 

Here's what the admin dashboard looks like now -

Users	Org
Admin — Gitpod - Google Chrome 14-02-2023 12_30_53	Admin — Gitpod - Google Chrome 14-02-2023 12_31_09

License	Settings
Admin — Gitpod - Google Chrome 14-02-2023 12_32_27	Admin — Gitpod - Google Chrome 14-02-2023 12_33_41

**Comment by gtsiolis** [comment]
/werft run with-clean-slate-deployment=true with-preview=true

**Comment by gtsiolis** [comment]
/werft run with-clean-slate-deployment=true with-preview=true

**Comment by meysholdt** [comment]
Thank you for signing the CLA @Devansu-Yadav!

**Review by gtsiolis — APPROVED** [review]
Thanks for taking a closer look, @Devansu-Yadav! 🍊 

I was troubleshooting granting permissions inside the preview environment, which does not work for some reason but haven't identified yet the root cause. 🤷 

UX changes looks good, overall! 🏁 

❗ **issue(non-blocking)**: There are a few minor issues like column header alignment and missing sorting icons, but these are fine to leave as is now as out of the scope of these changes and can be tackled separately in follow-up issues or PRs. ✔️ 

❗ **issue**: One UX change I find a bit jarring is the _License_ and _Settings_ layout, as expected since they were designs with a different layout.

Two approaches we can take here:
1. **Reuse the left sidebar** which is commonly used for project or org settings, to host two admin settings: _General_ (Usage Statistics and Telemetry settings) and _License_, so that these pages can continue to use the previous layout.
2. **Leave this as is** and open a follow-up issue or PR to tackle the layout reordering for _License_ and _Settings_.

I don't want to hold this back and given our focus shift away from the admin dashboard I'll approve these changes to unblock merging and will open a follow-up issue to keep track of the re-layout for _License_ and _Settings_ in case you're interested in picking this up.

**Comment by Devansu-Yadav** [comment]
> I was troubleshooting granting permissions inside the preview environment, which does not work for some reason but haven't identified yet the root cause. 🤷

Yeah, actually this was why I had to ask for the admin user privileges everytime a new preview environment was created 😅

> ❗ **issue(non-blocking)**: There are a few minor issues like column header alignment and missing sorting icons, but these are fine to leave as is now as out of the scope of these changes and can be tackled separately in follow-up issues or PRs. ✔️

Yes, I noticed this too especially on the Users page. Have you opened any issues regarding this or maybe we could tackle this in #16399 itself?
 
> ❗ **issue**: One UX change I find a bit jarring is the _License_ and _Settings_ layout, as expected since they were designs with a different layout.

I would absolutely ❤ to raise PRs to tackle both of these issues! Thanks for tagging me on issue #16399 😄

**Comment by gtsiolis** [comment]
@Devansu-Yadav I've opened a second follow-up issue in https://github.com/gitpod-io/gitpod/issues/16408 to keep track of some more layout nitpicks and the non-blocking issues described above in https://github.com/gitpod-io/gitpod/pull/16307#pullrequestreview-1297969338. 🏓

**Pull request merged**
