### PR TITLE
change: if statements to switch statements in dashboard

### PR DESCRIPTION
**Pull request by harshsinghatz**
## Description
Changing multiple consecutive if statements to switch cases for better readability and cleaner code

## Release Notes
```release-note
NONE
```

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Comment by roboquat** [comment]
@harshsinghatz: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by laushinka** [comment]
- [ ] @harshsinghatz thanks for opening this PR. Would you mind signing this Contributor License Agreement (CLA) [form](https://powerforms.docusign.net/30e1aa46-cce5-4bc6-a933-ad02cd8d5ada?env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&accountId=86335c2c-01b9-4edc-a187-014f5150a112)? 
Cc @meysholdt

**Comment by harshsinghatz** [comment]
@laushinka Done!, I have signed the CLA

**Review by laushinka — APPROVED** [review]
Thanks, @harshsinghatz!

**Comment by laushinka** [comment]
@harshsinghatz Could you rebase to main? 🙏🏽

**Comment by meysholdt** [comment]
Thank you for signing the CLA, @harshsinghatz!

**Comment by harshsinghatz** [comment]
> @harshsinghatz Could you rebase to main? 🙏🏽

Sorry missed the notification for some reason, can you guide on rebasing the branch on main

**Comment by laushinka** [comment]
> Sorry missed the notification for some reason, can you guide on rebasing the branch on main

@harshsinghatz No worries :) You can run `git pull --rebase origin main` and then `git push -f` Let me know if you run into any issues or conflicts.

**Comment by harshsinghatz** [comment]
> > Sorry missed the notification for some reason, can you guide on rebasing the branch on main
> 
> @harshsinghatz No worries :) You can run `git pull --rebase origin main` and then `git push -f` Let me know if you run into any issues or conflicts.

@laushinka Done!

**Comment by harshsinghatz** [comment]
@laushinka  Is there something else to do?

**Pull request merged**
