### PR TITLE
Address registry-facade dependency issues

### PR DESCRIPTION
**Pull request by aledbf**
## Description

- Update IPFS go modules to the new locations
- Update open telemetry libraries (to keep all in sync)

Relates WKS-251

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - aledbf-cves</li>
	<li><b>🔗 URL</b> - <a href="https://aledbf-cves.preview.gitpod-dev.com/workspaces" target="_blank">aledbf-cves.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - aledbf-cves-gha.12609</li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=workspace
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`
</details>

/hold

### CODE REVIEW

**Comment by kylos101** [comment]
@aledbf can you link the related Linear issue(s)? It it doesn't fix, and "just" relates, that is fine too.

**Review by akosyakov — APPROVED** [review]

**Review by kylos101 — COMMENTED** [review]
@aledbf does this fully fix WKS-251, or is it "just related", because a follow-on PR will be needed? I ask because I do not see a related change for `ws-daemon`.

**Comment by aledbf** [comment]
@kylos101 no. Most the the issues come from gloud, so there is no much we can do.

**Review by kylos101 — APPROVED** [review]
:+1:. 

:information_source: I changed the description from Fixes to Relates, because I'm uncertain about Lacework feedback as it pertains to `ws-daemon` fix versions. 

I don't want to block this PR. Depending on what we learn from @securitymirco , we can do another round of fixes for `ws-daemon`.

**Review by svenefftinge — APPROVED** [review]

**Pull request merged**
