### PR TITLE
[ws-daemon] Check for workspace state

### PR DESCRIPTION
**Pull request by aledbf**
Fixes
```go
{"containerID":"XXXXXX","instanceId":"XXXXXX","level":"debug","message":"resource controller shutting down","serviceContext":{"service":"ws-daemon","version":""},"severity":"DEBUG","time":"2021-08-16T19:49:44Z","userId":"","workspaceId":"XXXXXX"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c21060]

goroutine 1 [running]:
github.com/gitpod-io/gitpod/ws-daemon/pkg/dispatch.(*Dispatch).Close(0xc0002184d0, 0x0, 0x0)
	github.com/gitpod-io/gitpod/ws-daemon/pkg/dispatch/dispatch.go:152 +0x100
github.com/gitpod-io/gitpod/ws-daemon/pkg/daemon.(*Daemon).Stop(0xc00043edc0, 0x0, 0xc000d24eb8)
	github.com/gitpod-io/gitpod/ws-daemon/pkg/daemon/daemon.go:185 +0x39
github.com/gitpod-io/gitpod/ws-daemon/cmd.glob..func6(0x32cc8a0, 0xc000487410, 0x0, 0x3)
	github.com/gitpod-io/gitpod/ws-daemon/cmd/run.go:123 +0x12e5
github.com/spf13/cobra.(*Command).execute(0x32cc8a0, 0xc0004873e0, 0x3, 0x3, 0x32cc8a0, 0xc0004873e0)
	github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x32cc620, 0x9, 0x0, 0x0)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/gitpod-io/gitpod/ws-daemon/cmd.Execute()
	github.com/gitpod-io/gitpod/ws-daemon/cmd/root.go:49 +0x91
main.main()
	github.com/gitpod-io/gitpod/ws-daemon/main.go:15 +0x25

```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **aledbf** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by geropl — APPROVED** [review]
LGTM

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 3fd295de7ac14cb0d358707777d78462b4e6f681</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5229#pullrequestreview-731415298" title="Approved">geropl</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **aledbf** after the PR has been reviewed.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5229#pullrequestreview-731415298" title="Approved">geropl</a>*

*No associated issue*. Requirement bypassed by manually added approval.

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by geropl** [comment]
Looks like we need a rebase+redeploy.

**Pull request merged**
