### PR TITLE
[usage] Remove no longer used ListBilledUsage API

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description
Removes a no longer used API

## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-preview

### CODE REVIEW

**Comment by svenefftinge** [comment]
Can land after https://github.com/gitpod-io/gitpod/pull/12677 landed.

/hold

**Comment by easyCZ** [comment]
Ah, parts of this were already in https://github.com/gitpod-io/gitpod/pull/12688

**Comment by svenefftinge** [comment]
since #12677 landed this could be merged, too.

/unhold

**Review by easyCZ — APPROVED** [review]

**Pull request merged**
