### PR TITLE
Change getDocumentationLink() in GitpodConnector

### PR DESCRIPTION
**Pull request by whytrall**
## Description
This PR removes deprecated API

## Related Issue(s)
Should fix https://youtrack.jetbrains.com/issue/GTW-1976

## How to test
1. Open Gateway
2. Click on More button

## Release Notes

```release-note
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by roboquat** [comment]
@whytrall: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by gtsiolis** [comment]
Thanks @whytrall! ✨ 

1. You'll also need to sign a Contributor License Agreement (CLA)[[1](https://en.wikipedia.org/wiki/Contributor_License_Agreement)] once before merging your first contribution. Looping in @meysholdt to reach out about the CLA. 🏓
2. @felladrin Could you take a look at this since you added this part back in https://github.com/gitpod-io/gitpod/pull/8917 or pass this to someone on the team? 🏀

**Comment by akosyakov** [comment]
@andreafalzetti @felladrin does it still make sense or already fixed on main?

**Comment by andreafalzetti** [comment]
Thanks for the contribution @whytrall 🙏 

As we discussed, we will close this PR in favour of https://github.com/gitpod-io/gitpod/pull/13966

**Pull request closed without merging**
