### PR TITLE
[observability] Team Workspace / Success Criteria dashboard -> no data

### LINKED ISSUE #7335: [observability] Team Workspace / Success Criteria dashboard -> no data
### Bug description

The dashboard is empty, panes should display data.

### Steps to reproduce

[Browse here](https://grafana.gitpod.io/d/jgjwvIc7k/success-criteria?orgId=1)

### Workspace affected

n/a

### Expected behavior

Should contain data

### Example repository

n/a

### Anything else?

Is the datasource set correctly [here](https://github.com/gitpod-io/gitpod/blob/93ed40d14ad2fe166a9f2594e920adec48c0718f/operations/observability/mixins/workspace/dashboards/success-criteria.json)?

### PR DESCRIPTION
**Pull request by kylos101**
## Description

Success critiera dashboard for Team Workspace shows `no data` on page load

## Related Issue(s)

Fixes #7335

## How to test

To recreate the issue:
[Browse here](https://grafana.gitpod.io/d/jgjwvIc7k/success-criteria?orgId=1)

To recreate the fix:
1. Open a Gitpod workspace from this PR's branch
2. `kubectl port-forward svc/grafana 3000:3000`
3. [Start a workspace from here](https://kyleb-ws-dashboard.staging.gitpod-dev.com/workspaces)
4. Browse to Grafana and view the results

Or see the fix in action here:
<a href="https://www.loom.com/share/ece7afd53bc44302ae07f486931b14d5">
    <p>Fix for Team Workspace / Success Criteria dashboard -> no data #7335 - Watch Video</p>
    
  </a>

## Release Notes

```release-note
Fix Team Workspace Success Criteria dashboard
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **csweichel** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @csweichel` in a comment when ready.

Associated issue: *#7335*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[operations/observability/mixins/workspace/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/operations/observability/mixins/workspace/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: eb4fd9f5479b55261d354449ac89f40fcc48122c</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7354#issuecomment-1000433475" title="LGTM">aledbf</a>*

Associated issue: *#7335*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[operations/observability/mixins/workspace/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/operations/observability/mixins/workspace/OWNERS)~~ [aledbf]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7354#issuecomment-1000433475" title="LGTM">aledbf</a>*

Associated issue: *#7335*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[operations/observability/mixins/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/operations/observability/mixins/OWNERS)~~ [aledbf]
- ~~[operations/observability/mixins/workspace/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/operations/observability/mixins/workspace/OWNERS)~~ [aledbf]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by kylos101** [comment]
@aledbf this is all set now, I squashed it and added a Loom video so you can see how this is working in core-dev. :smile:

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: fb9b8c1ea6b33fed539137895dc096d8d23f21c6</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7354#issuecomment-1000528779" title="LGTM">aledbf</a>*

Associated issue: *#7335*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[operations/observability/mixins/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/operations/observability/mixins/OWNERS)~~ [aledbf]
- ~~[operations/observability/mixins/workspace/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/operations/observability/mixins/workspace/OWNERS)~~ [aledbf]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
