### PR TITLE
[ PUBLIC-API ] Added Start Workspace Route for Gitpod Public API

### PR DESCRIPTION
**Pull request by henit-chobisa**
## Description
The current pull request aims to add a new route to the experimental public api for starting user's existing workspaces while returning a unary response in form of json consisting `workspaceID` and `instanceID` by pre-existing definitions in the workspaces.proto file in the public api.

## Related Issue(s)
Adds up to #7900 

## How to test
- Unit tests

## Release Notes
```
NONE
```

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [x] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`
</details>
 
/hold

### CODE REVIEW

**Comment by henit-chobisa** [comment]
Hey @gtsiolis, me and @Palanikannan1437 have been trying to wrap our heads around the public-api, we tried to add a `StartWorkspace` method to the public api, can you please have a look once. 🙏🏼
Thanks 💛

**Comment by gtsiolis** [comment]
Hey @henit-chobisa @Palanikannan1437, I've forwarded this internally to the team for visibility. 🏓

**Comment by henit-chobisa** [comment]
> Hey @henit-chobisa @Palanikannan1437, I've forwarded this internally to the team for visibility. 🏓 

Thank you so much @gtsiolis ✨

**Comment by easyCZ** [comment]
Thanks for the PR. Unfortunately at the moment we're not in a position to progress the Public API with outside contributions. This is primarily due to capacity. The implementation of those APIs is really only the smallest part in overall time/effort commitment as it subsequently requires operational investment (monitoring, maintenance, documentation) which we right now are not in a position to commit.

We hope to be able to to get back to this around Q4.

**Pull request closed without merging**
