### PR TITLE
[gh-app] unsubscribe from pull_request.synchronize

### PR DESCRIPTION
**Pull request by AlexTugarev**
## Description
`pull_request.synchronize` events of Gitpod's GH App are generating noise, but the do not provide any value.

There is a general `push` event handler which takes care of the same thing basically. And what's more, both are receive when the author pushes updates to a PR's branch, which does mean we need to deduplicate on our end.

Check this DB query if you need to see the events rushing in, to verify they are always dupes:
```
select * from d_b_webhook_event   order by creationTime DESC limit 100;
```

To reviewers, if you read `handlePullRequest` you'll find no special handling for PRs in general. The relevant information bit is `contextURL: payload.pull_request.html_url`, which has an in equivalent in `push` event handler. 

Unsubscribing from `pull_request.synchronize` should be zero risk. 

## Related Issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`
- [ ] /werft publish-to-npm

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]

**Comment by svenefftinge** [comment]
I think the default configuration ignores branch pushes and only trigger prebuilds on PR synchronize.

**Comment by AlexTugarev** [comment]
> I think the default configuration ignores branch pushes and only trigger prebuilds on PR synchronize.

@svenefftinge, do you refer to the config of webhook events? 

Given that github-app.ts looks like to live for gitpod.io only, we'd have this under control, no?

**Comment by svenefftinge** [comment]
I mean what I described here https://github.com/gitpod-io/gitpod/issues/16139#issue-1564967453

users having the `.gitpod.yml` untouched will get prebuilds for `PR` events but not for push events that are not on the default branch.

**Comment by geropl** [comment]
I would love to sync on this topic. Sent an invite. :slightly_smiling_face:

**Comment by AlexTugarev** [comment]
@svenefftinge, please ✔️ the revert PR https://github.com/gitpod-io/gitpod/pull/16202

**Pull request merged**
