### PR TITLE
[public api] Add workspace instance to GetWorkspace

### PR DESCRIPTION
**Pull request by jeanp413**
## Description

Add GetActiveWorkspaceInstance to public api

For testing in gitpod-desktop

## How to Test

See PR https://github.com/gitpod-io/gitpod/pull/11310

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by easyCZ** [comment]
@jeanp413 Thanks for the change.

I'm wondering to extend we should make a notion of an Active Worksapce instance first class in the Public API. It's in a way a sub-resource which isn't first-class exposed to the users in our product domain. Instead, it feels like this should be part of the GetWorkspace response, like this - https://github.com/gitpod-io/gitpod/pull/9816

```
// Workspace describes a single workspace
message Workspace {
    // workspace_id is the ID of the workspace
    string workspace_id = 1;
    // owner_id is the ID of the user who created this workspace
    string owner_id = 2;
    // project_id is the ID of the project which this workspace belongs to
    string project_id = 3;
    // context reports the original context the workspace was created from
    WorkspaceContext context = 4;

    // description is a human readable description of the workspace
    string description = 5;

    // status is the current status of this Workspace.
    WorkspaceStatus status = 6;
}

// WorkspaceStatus represents the currently observed status of a Workspace, including data about child resources that belong to this Workspace.
message WorkspaceStatus {
    // instance is the currently assigned WorkspaceInstance to this workspace. Empty when there is no WorkspaceInstance assigned.
    WorkspaceInstance instance = 1;
}
```

The reasoning for this is that it's an anti-pattern to expose a resource called `WorkspaceInstance` on a `WorksapaceService` - it doens't deal with WorkspacInstnaces primarily.
The other reason is that Instances are more-less hidden from users. It is indeed the case that the current websocket API does it this way, but I think we can do better with the Public API. WDYT?

**Comment by jeanp413** [comment]
Sounds good, I used `GetActiveWorkspaceInstance` because I saw it was declared as part of the API already.
@mustard-mh will do the changes as I'm on-call this week.

**Comment by easyCZ** [comment]
👍 If you want, I can re-open https://github.com/gitpod-io/gitpod/pull/9816 and land that for you. Happy to assist in any way also, just let me know.

I'm looking to arrange an API review session to clean up the existing definitions and trim them down to just what we need at this point in time.

**Comment by mustard-mh** [comment]
I updated the `Workspace` message and removed the `ListWorkspacesResponse` instance related fields.

Is it ok that we don't care about the number of proto messages' fields as it's not public and nowhere used right?

cc @easyCZ @jeanp413

**Comment by mustard-mh** [comment]
Rebased to main

**Review by easyCZ — APPROVED** [review]

**Review by jenting — APPROVED** [review]
Workspace component LGTM

**Comment by mustard-mh** [comment]
/unhold

Tested with `gpctl` and it worked

**Pull request merged**
