### PR TITLE
[content-service] Update cloud.google.com/go/storage dependency

### PR DESCRIPTION
**Pull request by aledbf**
Contains several fixes and also updates `google.golang.org/api` to `v0.40.0`

### CODE REVIEW

**Comment by csweichel** [comment]
When I open this in Gitpod I get a ton of `go.sum` changes, virtually undoing https://github.com/gitpod-io/gitpod/pull/3791.
Do you know why that is?

**Comment by aledbf** [comment]
@csweichel how are you updating the dependencies?

**Comment by csweichel** [comment]
I reckon it's the work of the VSCode Go extension that bloats the go.sum files.

The `go mod tidy` run makes perfect sense, but seems to be at odds with something else in the workspace.

**Comment by aledbf** [comment]
@csweichel using the latest build of the go update I don't see changes now running

https://aledbf-go163.staging.gitpod-dev.com/#https://github.com/gitpod-io/gitpod/pull/3809

**Comment by aledbf** [comment]
@csweichel setting `buildCommand` broke all go lib builds. The last commit in this PR fixes that. Is there any other alternative?

**Comment by aledbf** [comment]
@csweichel with the updates in #3820, when you open this PR in gitpod.io, there are no changes now.

**Comment by csweichel** [comment]
> @csweichel with the updates in #3820, when you open this PR in gitpod.io, there are no file changes now.

does that make this PR obsolete?

**Comment by aledbf** [comment]
> does that make this PR obsolete?

No. The goal of this PR is to update the storage dependency

**Review by csweichel — APPROVED** [review]
Got it now. Thanks for the update.

**Pull request merged**
