### PR TITLE
[vscode] fix default theme

### LINKED ISSUE #2497: [VS Code] VS Code always defaults to Light theme
### Describe the bug
Theia by default in Gitpod's configuration is defaulted in dark mode. Visual Studio Code however in my instance does not, as it defaults to light theme almost immediately.

### Steps to reproduce
Reproducible by just creating any workspace in GitHub by selecting VS Code as your default editor.

Video Evidence provided [here](https://twitter.com/satominyaaa/status/1337070518587932672).

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

-  fix #2497: fix default theme

Changes in VS Code: https://github.com/gitpod-io/vscode/pull/7

#### How to test

- Switch to Code, start a new worksapce you should see dark theme without flickering.
- Change theme, start another workspace and check that theme is preserved without flickering as well.

### CODE REVIEW

**Review by svenefftinge — APPROVED** [review]
Works well

**Review by gtsiolis — APPROVED** [review]
Thanks @akosyakov! Works like a charm! 🔮

**Review by sr229 — APPROVED** [review]
Verified works over in a local instance

**Comment by sr229** [comment]
🎉

**Pull request merged**
