### PR TITLE
[server] Fix grpc client leak

### LINKED ISSUE #6852: [server] Mem leak: @grpc/grpc-js channels
[Todays work on dashboards](https://github.com/gitpod-io/gitpod/pull/6845) revealed that we have a memory leak in `server`.
The following screenshot shows before and after deployment. (The steep increase on one instance was me taking a heapsnapshot).
image

After taking heapsnapshots and investigating it seems that it's around grpc-connections, and how we handle cache them/reconnects. There are at least three leaks:
 - we create 4 new clients to `content-service` for each new websocket connection ([link](https://github.com/gitpod-io/gitpod/blob/c494a0ba63e7d167079568f70519004d4f5a3cab/components/server/src/container-module.ts#L200-L219))
 - we leak ws-manager clients/channels [here](https://github.com/gitpod-io/gitpod/blob/9605e0b386e9216719cbbda377bef2e0e8738b36/components/ws-manager-api/typescript/src/client-provider.ts#L92-L104) in cases where old clusters go offline (it seems)
 -  we never close image builder clients that [are not connected anymore](https://github.com/gitpod-io/gitpod/blob/353ddc20fb8703147903de0c1240a128fcc3c5a3/components/image-builder-api/typescript/src/sugar.ts#L56-L69)

What triggered this seems to have been the version bump to [`@grpc/grpc-js 1.4.2`](https://github.com/grpc/grpc-node/releases/tag/%40grpc%2Fgrpc-js%401.4.2) which introduce "channelz" (looks like channel statistics or so) which seems to increase the footprint per channel, and also causes channel to leak if they're not explicitly `close()`d.

A general question would be how to handle channel reconnects at all. There seems to be no auto-reconnect like in other languages (grpc docs mention it's language-specific).

### PR DESCRIPTION
**Pull request by geropl**
## Description
This PR fixes two of the issues identified in #6852:
 - [image-builder client is never explicitly closed](https://github.com/gitpod-io/gitpod/commit/c2c677eb9cd0835fda1957e194e0c0041133a123)
 - we create a lot of ContentService clients without making sure they re-connect or are properly `close`d [3c10694](https://github.com/gitpod-io/gitpod/commit/3c10694a6040e111c019ac809f959da64e2d2472)

Both issues are triggered/got worse by our version upgrade to `@grpc/grpc-js: 1.4.2` it seems.

As a side effect we now re-establish connections from websocket endpoints to `content-service`.

## Related Issue(s)

Fixes #6852.

### Test that code-sync works
 1. open a fresh workspace: https://gpl-server-ram-leak.staging.gitpod-dev.com/#https://github.com/gitpod-io/template-typescript-node
 2. open sync log (F1 -> Sync: log)
 3. install any extension (Gitlens for instance), and note how it shows up in the sync log
 4. open another fresh workspace: https://gpl-server-ram-leak.staging.gitpod-dev.com/#https://github.com/gitpod-io/template-typescript-node
 5. open sync log (F1 -> Sync: log), and note how GitLens is synced and installed :heavy_check_mark: 

### Test that image builds work

 1. find a context with an not-yet-built dockerimage

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** after the PR has been reviewed.

Associated issue: *#6852*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/content-service-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service-api/OWNERS)**
- **[components/image-builder-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder-api/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by AlexTugarev** [comment]
/lgtm 

tested with code sync and it works as expected. code looks good 🙏🏻

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: e9e35f49d28f483dc0f5c9f524c9658b0c8de31c</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6916#issuecomment-979870160" title="LGTM">AlexTugarev</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** after the PR has been reviewed.

Associated issue: *#6852*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/content-service-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service-api/OWNERS)**
- **[components/image-builder-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder-api/OWNERS)**
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [AlexTugarev]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6916#issuecomment-979870160" title="LGTM">AlexTugarev</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/6916#issuecomment-979871524" title="Approved">geropl</a>*

Associated issue: *#6852*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/content-service-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service-api/OWNERS)~~ [geropl]
- ~~[components/image-builder-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder-api/OWNERS)~~ [geropl]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [AlexTugarev,geropl]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
