### PR TITLE
[initializer] Fix issue with publicly signed SCM's on a self-signed Gitpod instance

### PR DESCRIPTION
**Pull request by Pothulapati**
## Description

As per the issue, Using only `GIT_SSL_CAINFO` seems to prevent the
git intializer from reading any of the default certs from the system's trust root
causing problems with publicly signed SCM's.
Though, I couldn't find any documentaiton specifying this but the behaviour 
seems to be that as per various issues in discord, etc and  my own testing.

Setting only `GIT_SSL_CAPATH` to `/etc/ssl/certs` seems to cause problems
with self-signed SCM's even if the certificate is under `/etc/ssl/certs`. It throws
the same `unknown self signed certificate` which means it is not at all reading
the custom cert and probably only reading the `certs.pem` bundle.

Setting them both i.e `GIT_SSL_CAINFO` to the custom cert, and `GIT_SSL_CAPATH`
to the default cert trust store **seems to be the only way to get both publicly signed
and self signed SCM's to work**.

Signed-off-by: Tarun Pothulapati <tarun@gitpod.io>

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/issues/10173

## How to test

Spin up a self-signed `gitpod` instance, and authenticate it with
both a `self-signed` SCM and a public SCM.

An Instance up and running at [tarun.gitpod-self-hosted.com](tarun.gitpod-self-hosted.com)

## Release Notes

```release-note
[initializer] Fix issue with publicly signed SCM's on a self-signed Gitpod instance
```

### CODE REVIEW

**Comment by roboquat** [comment]
@Pothulapati: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by corneliusludmann — APPROVED** [review]

**Review by csweichel — APPROVED** [review]
Did not test, but code LGTM

**Pull request merged**
