### PR TITLE
Frontend development: redirect instead of proxy

### PR DESCRIPTION
**Pull request by geropl**
## Description
This allows you to overlay the Dashboard with any other version, as long as you can reach the source from your browser.

### Steps
Just like before, do:

### Get a workspace with your modified version of dashboard

 1. start a workspace on this branch
 6. start dashboard with `yarn start-local`

### On the Gitpod installation you want to change the dashboard on
In [this preview](https://gpl-frontef258b14851.preview.gitpod-dev.com/workspaces):
  1. login to the preview
 4. become admin by: `leeway run components:make-user-admin` (or as me to do it for you)
    a. go to /admin/users and grant yourself the "developer" role
 7. run `gp url 3000`, and use that value to stick it into the "header editor" of your choice, so it matches this preview
 9. Visit this preview

You should now be able to change the dashboard on the fly, incl. hot-reload. :tada: 

Thank you @selfcontained for the idea and help with webpack!

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 9317b88</samp>

Refactored the proxy plugin for frontend development with hot reloading and live reloading. Renamed the package and module from `workspacedownload` to `frontend_dev` and added unit tests for the index.html rewriting logic. Modified the files `frontend_dev.go`, `frontend_dev_test.go`, and `go.mod`.

</details>

## Related Issue(s)

Fixes #

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - gpl-frontef258b14851</li>
	<li><b>🔗 URL</b> - <a href="https://gpl-frontef258b14851.preview.gitpod-dev.com/workspaces" target="_blank">gpl-frontef258b14851.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - gpl-frontend-dev-direct-gha.21161</li>
	<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-gpl-frontef258b14851%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws-manager-mk2%22%0A;duration=P1D?project=gitpod-core-dev" target="_blank">GCP Logs Explorer</a></li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by mustard-mh** [comment]
> start dashboard with yarn start-local, and make sure to expose port 3000 as "public" 🔓

We could make it open with another port and mark this port as public in `.gitpod.yml`

**Comment by mustard-mh** [comment]
> become admin by: leeway run components:make-user-admin (or as me to do it for you)
> a. go to /admin/users and grant yourself the "developer" role

And make developer role granting as a leeway script

**Comment by geropl** [comment]
@mustard-mh @selfcontained Now also with the relevant commit... :expressionless:

**Review by mustard-mh — APPROVED** [review]
Works like a charm!! 

[nit not blocking] will it be better if we put document inside README.md?

**Pull request merged**
