### PR TITLE
[installation-telemetry]: log data sent to Segment

### LINKED ISSUE #7540: Question - should we log the data we send to console?
> **tl;dr** I'm in favour of this as a point of transparency and in gaining/maintaining the trust of the community

To further prove that we are not collecting anything more than the anonymous data, is it worth displaying what we send as a log message? Normally, it's bad practice to log what you're sending to a data store, but this would transparently display what we're sending so users can see exactly what we're collecting.

The `analytics.Track` object we're sending in the [send](https://github.com/gitpod-io/gitpod/blob/sje/telemetry-client/components/installation-telemetry/cmd/send.go#L48) command would be what's sent to the logs.

/cc @gitpod-io/engineering-self-hosted

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Description

Log data sent to Segment to the console. This is to provide transparency in the data we send and to prove that we're not providing anything that could be used to identify an installation.

## Related Issue(s)

Fixes #7540

## Release Notes

```release-note
[installation-telemetry]: log data sent to Segment
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mrsimonemms** after the PR has been reviewed.

Associated issue: *#7540*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/installation-telemetry/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/installation-telemetry/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by corneliusludmann — APPROVED** [review]
/lgtm
/approve

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: a79cd3aeac31c9ab98d02403d0f7d1333888ff38</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7730#pullrequestreview-859231684" title="Approved">corneliusludmann</a>*

Associated issue: *#7540*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/installation-telemetry/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/installation-telemetry/OWNERS)~~ [corneliusludmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
