### PR TITLE
[server] Fix workspace download for GCP storage

### LINKED ISSUE #3152: Downloading workspaces no longer works (404 page)
### Steps to reproduce

1. Click to Download a workspace (from dashboard or admin panel)

### Expected

Download button downloads the latest workspace backup.

### Actual behavior

Download button opens https://gitpod.io/workspace-download/get/a53fb195-176b-4e30-93a0-9229f2d2ed75 which is a 404 page:

Screenshot 2021-02-06 at 20 38 45

### PR DESCRIPTION
**Pull request by corneliusludmann**
Fixes #3152

### How to test

start and stop a workspace, try to download the workspace

### CODE REVIEW

**Comment by csweichel** [comment]
hoes does this PR relate to #3288 ?

**Comment by corneliusludmann** [comment]
> hoes does this PR relate to #3288 ?

That I now know the root cause for the download bug and that I now cat start with bringing this fix in #3288. It was easier to analyze this base on main because it worked there once.

**Comment by jankeromnes** [comment]
Sweeper is too fast for me 🐌

/werft run

**Review by jankeromnes — APPROVED** [review]
Looks good to me and works like a charm! ⬇️

Many thanks 🙏

**Pull request merged**
