### PR TITLE
update dev image

### PR DESCRIPTION
**Pull request by svenefftinge**
## Description

Updates the dev image to include `zed` and `spicedb`CLI

## Related Issue(s)

Fixes WEB-478

## How to test

start a workspace on this PR and verify the 
 - `zed` command is available
 - `spicedb` command is available

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`
</details>

/hold

### CODE REVIEW

**Comment by svenefftinge** [comment]
@kylos101 Do you know where leeway gets installed?
I couldn't find any mention in the dockerfile

**Comment by kylos101** [comment]
> @kylos101 Do you know where leeway gets installed? I couldn't find any mention in the dockerfile

For posterity, Sven and I talked, he'll update the dev image, wait for a build and get the name of the newly built image, and then update the related dockerfiles to use it. :+1:

**Review by corneliusludmann — APPROVED** [review]

**Review by easyCZ — APPROVED** [review]

**Review by kylos101 — APPROVED** [review]
:+1:

**Pull request merged**
