### PR TITLE
Update grpc dependencies

### PR DESCRIPTION
**Pull request by aledbf**
- `google.golang.org/grpc v1.39.0`
- `google.golang.org/protobuf v1.27.1`
- `github.com/golang/mock v1.6.0`
- `github.com/grpc-ecosystem/grpc-gateway/v2 v2.5.0`
- `github.com/containerd/containerd v1.5.5`

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5004#" title="Author self-approved">aledbf</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **csweichel** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @csweichel` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [aledbf]
- ~~[components/blobserve/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/blobserve/OWNERS)~~ [aledbf]
- ~~[components/common-go/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/common-go/OWNERS)~~ [aledbf]
- ~~[components/content-service/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service/OWNERS)~~ [aledbf]
- **[components/content-service-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service-api/OWNERS)**
- ~~[components/ee/agent-smith/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/agent-smith/OWNERS)~~ [aledbf]
- **[components/ee/kedge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/kedge/OWNERS)**
- ~~[components/ee/ws-scheduler/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/ws-scheduler/OWNERS)~~ [aledbf]
- ~~[components/gitpod-cli/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-cli/OWNERS)~~ [aledbf]
- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- ~~[components/image-builder/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder/OWNERS)~~ [aledbf]
- **[components/image-builder-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder-api/OWNERS)**
- ~~[components/local-app/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/local-app/OWNERS)~~ [aledbf]
- **[components/local-app-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/local-app-api/OWNERS)**
- ~~[components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/registry-facade/OWNERS)~~ [aledbf]
- ~~[components/registry-facade-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/registry-facade-api/OWNERS)~~ [aledbf]
- **[components/service-waiter/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/service-waiter/OWNERS)**
- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [aledbf]
- **[components/supervisor-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor-api/OWNERS)**
- ~~[components/workspacekit/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/workspacekit/OWNERS)~~ [aledbf]
- ~~[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)~~ [aledbf]
- **[components/ws-daemon-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon-api/OWNERS)**
- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [aledbf]
- ~~[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)~~ [aledbf]
- **[components/ws-manager-bridge-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge-api/OWNERS)**
- ~~[components/ws-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-proxy/OWNERS)~~ [aledbf]
- ~~[dev/gpctl/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/dev/gpctl/OWNERS)~~ [aledbf]
- ~~[dev/loadgen/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/dev/loadgen/OWNERS)~~ [aledbf]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **csweichel** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @csweichel` in a comment when ready.

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**
- **[components/blobserve/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/blobserve/OWNERS)**
- **[components/common-go/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/common-go/OWNERS)**
- **[components/content-service/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service/OWNERS)**
- **[components/content-service-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service-api/OWNERS)**
- **[components/ee/agent-smith/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/agent-smith/OWNERS)**
- **[components/ee/kedge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/kedge/OWNERS)**
- **[components/ee/ws-scheduler/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/ws-scheduler/OWNERS)**
- **[components/gitpod-cli/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-cli/OWNERS)**
- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/image-builder/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder/OWNERS)**
- **[components/image-builder-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder-api/OWNERS)**
- **[components/local-app/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/local-app/OWNERS)**
- **[components/local-app-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/local-app-api/OWNERS)**
- **[components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/registry-facade/OWNERS)**
- **[components/registry-facade-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/registry-facade-api/OWNERS)**
- **[components/service-waiter/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/service-waiter/OWNERS)**
- **[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)**
- **[components/supervisor-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor-api/OWNERS)**
- **[components/workspacekit/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/workspacekit/OWNERS)**
- **[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)**
- **[components/ws-daemon-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon-api/OWNERS)**
- **[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)**
- **[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)**
- **[components/ws-manager-bridge-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge-api/OWNERS)**
- **[components/ws-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-proxy/OWNERS)**
- **[dev/gpctl/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/dev/gpctl/OWNERS)**
- **[dev/loadgen/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/dev/loadgen/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5004#issuecomment-889444407" title="Approved">aledbf</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **csweichel** after the PR has been reviewed.

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/5004#issuecomment-889444407" title="Approved">aledbf</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [aledbf]
- ~~[components/blobserve/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/blobserve/OWNERS)~~ [aledbf]
- ~~[components/common-go/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/common-go/OWNERS)~~ [aledbf]
- ~~[components/content-service/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service/OWNERS)~~ [aledbf]
- **[components/content-service-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service-api/OWNERS)**
- ~~[components/ee/agent-smith/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/agent-smith/OWNERS)~~ [aledbf]
- **[components/ee/kedge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/kedge/OWNERS)**
- ~~[components/ee/ws-scheduler/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/ws-scheduler/OWNERS)~~ [aledbf]
- ~~[components/gitpod-cli/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-cli/OWNERS)~~ [aledbf]
- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- ~~[components/image-builder/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder/OWNERS)~~ [aledbf]
- **[components/image-builder-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder-api/OWNERS)**
- ~~[components/local-app/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/local-app/OWNERS)~~ [aledbf]
- **[components/local-app-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/local-app-api/OWNERS)**
- ~~[components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/registry-facade/OWNERS)~~ [aledbf]
- ~~[components/registry-facade-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/registry-facade-api/OWNERS)~~ [aledbf]
- **[components/service-waiter/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/service-waiter/OWNERS)**
- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [aledbf]
- **[components/supervisor-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor-api/OWNERS)**
- ~~[components/workspacekit/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/workspacekit/OWNERS)~~ [aledbf]
- ~~[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)~~ [aledbf]
- **[components/ws-daemon-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon-api/OWNERS)**
- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [aledbf]
- ~~[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)~~ [aledbf]
- **[components/ws-manager-bridge-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge-api/OWNERS)**
- ~~[components/ws-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-proxy/OWNERS)~~ [aledbf]
- ~~[dev/gpctl/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/dev/gpctl/OWNERS)~~ [aledbf]
- ~~[dev/loadgen/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/dev/loadgen/OWNERS)~~ [aledbf]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by akosyakov** [comment]
Does this PR change generated ts files, i.e. apis? Do we need to upgrade Code to check compatibility?

**Comment by aledbf** [comment]
> Does this PR change generated ts files, i.e. apis?

No. There are no changes to generated ts files.

> Do we need to upgrade Code to check compatibility?

There are no breaking changes with the update, only fixes and one new feature that provides details about the [HTTP path](https://github.com/0daryo/grpc-gateway/blob/41eb069383c94f105963d19a90edbaa503564317/docs/docs/operations/annotated_context.md), but this is passed internally in the context.

**Comment by aledbf** [comment]
> Does this PR change generated ts files,

@akosyakov checking the node dependencies, I synced grpc versions, and now there are some changes, but is related to the removal of `handleClientStreamingCall` from the generated code (not used).
The update also removes dependencies (google-auth-library) and improvements in logging.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 388a07be66502ecf1d7da67f7b3eb95e0d7c5b10</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/5004#issuecomment-889444407" title="Approved">aledbf</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/5004#issuecomment-892673942" title="LGTM">csweichel</a>*

Associated issue requirement bypassed by: *<a href="https://github.com/gitpod-io/gitpod/pull/5004#issuecomment-889444407" title="Approved">aledbf</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)~~ [aledbf,csweichel]
- ~~[components/blobserve/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/blobserve/OWNERS)~~ [aledbf,csweichel]
- ~~[components/common-go/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/common-go/OWNERS)~~ [aledbf,csweichel]
- ~~[components/content-service/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service/OWNERS)~~ [aledbf,csweichel]
- ~~[components/content-service-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/content-service-api/OWNERS)~~ [csweichel]
- ~~[components/ee/agent-smith/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/agent-smith/OWNERS)~~ [aledbf,csweichel]
- ~~[components/ee/kedge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/kedge/OWNERS)~~ [csweichel]
- ~~[components/ee/ws-scheduler/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/ws-scheduler/OWNERS)~~ [aledbf,csweichel]
- ~~[components/gitpod-cli/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-cli/OWNERS)~~ [aledbf,csweichel]
- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [csweichel]
- ~~[components/image-builder/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder/OWNERS)~~ [aledbf,csweichel]
- ~~[components/image-builder-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder-api/OWNERS)~~ [csweichel]
- ~~[components/local-app/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/local-app/OWNERS)~~ [aledbf,csweichel]
- ~~[components/local-app-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/local-app-api/OWNERS)~~ [csweichel]
- ~~[components/registry-facade/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/registry-facade/OWNERS)~~ [aledbf,csweichel]
- ~~[components/registry-facade-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/registry-facade-api/OWNERS)~~ [aledbf,csweichel]
- ~~[components/service-waiter/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/service-waiter/OWNERS)~~ [csweichel]
- ~~[components/supervisor/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/OWNERS)~~ [aledbf,csweichel]
- ~~[components/supervisor-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor-api/OWNERS)~~ [csweichel]
- ~~[components/workspacekit/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/workspacekit/OWNERS)~~ [aledbf,csweichel]
- ~~[components/ws-daemon/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/OWNERS)~~ [aledbf,csweichel]
- ~~[components/ws-daemon-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon-api/OWNERS)~~ [csweichel]
- ~~[components/ws-manager/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/OWNERS)~~ [aledbf,csweichel]
- ~~[components/ws-manager-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/OWNERS)~~ [aledbf,csweichel]
- ~~[components/ws-manager-bridge-api/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge-api/OWNERS)~~ [csweichel]
- ~~[components/ws-proxy/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-proxy/OWNERS)~~ [aledbf,csweichel]
- ~~[dev/gpctl/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/dev/gpctl/OWNERS)~~ [aledbf,csweichel]
- ~~[dev/loadgen/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/dev/loadgen/OWNERS)~~ [aledbf,csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
