### PR TITLE
Removing paymentVerificationFlow flag

### PR DESCRIPTION
**Pull request by selfcontained**
## Description

The `paymentVerificationFlow` flag has been released to 100% now. This removes the flag and the code for the old setup intent flow from the dashboard frontend.

A followup will be removing the setup-intent parts of the usage service.

## Related Issue(s)

Fixes WEB-211

## How to test

* Upgrade the billing plan of your organization to verify the flow still works.

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - bmh-cleanup-3ds-flag</li>
	<li><b>🔗 URL</b> - <a href="https://bmh-cleanup-3ds-flag.preview.gitpod-dev.com/workspaces" target="_blank">bmh-cleanup-3ds-flag.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
</ul>

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

/hold

### CODE REVIEW

**Review by easyCZ — APPROVED** [review]
Land at will, and when we no longer need it.

**Review by geropl — APPROVED** [review]
Let's go with this tomorrow morning, I think that's enough time to catch potential errors, given that we saw it working flawlessly already.

:cloud: Do we need to adjust backend code as well? IIRC there were a couple of TODOs in billing.go as well. But can totally be a separate PR :100:

**Comment by selfcontained** [comment]
> Let's go with this tomorrow morning, I think that's enough time to catch potential errors, given that we saw it working flawlessly already.
> 
> ☁️ Do we need to adjust backend code as well? IIRC there were a couple of TODOs in billing.go as well. But can totally be a separate PR 💯

Yup, there’s some cleanup for backed that can follow this, I can do that too.

**Pull request merged**
