### PR TITLE
[ide-service] Always send IdeImageLayers

### PR DESCRIPTION
**Pull request by jeanp413**
## Description

Always send IdeImageLayers in ide-service

## How to test

Start a prebuild check it runs successfully

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [x] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`
- [ ] /werft publish-to-npm

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft with-integration-tests=workspace
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by jeanp413** [comment]
mmm tests are failing but I can run prebuilts from dashboard :thinking:

**Comment by akosyakov** [comment]
> mmm tests are failing but I can run prebuilts from dashboard 🤔

Tests don't respect new layers. @iQQBot has a fix in https://github.com/gitpod-io/gitpod/pull/16168. As soon as merged, will rebase and try again. I assume we can drop last commit as well?

**Review by akosyakov — APPROVED** [review]
I tested manually, and everything works now, i.e. image build, pre-builds, regular starts with web and desktop IDEs.

Workspace tests are green too now, but for some reasons build is hanging: https://werft.gitpod-dev.com/job/gitpod-build-fix-ide-config.10

**Comment by vulkoingim** [comment]
/hold

Adding a hold as it's blocking the merge queue.

**Pull request merged**
