### PR TITLE
docs(installer): update init script

### PR DESCRIPTION
**Pull request by ThePlenkov**
The current script is outdated

### CODE REVIEW

**Comment by roboquat** [comment]
@ThePlenkov: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by MrSimonEmms — COMMENTED** [review]
This is the old, deprecated command.

**Comment by ThePlenkov** [comment]
@MrSimonEmms strange. I was following this guide: https://github.com/gitpod-io/gitpod/tree/main/install/installer#quickstart

And installed the most recent release. In this release init command is not same as in the documentation for the installer.

What is exactly deprectated? `gitpod-installer config` `gitpod-installer init` or `gitpod-installer` in general? Thank you!

**Comment by MrSimonEmms** [comment]
Look at the docs for the most recent tag rather than in the `main` branch. The `init` command is deprecated and replaced by `config init`. This change will be in the September release, scheduled for release next week

**Comment by ThePlenkov** [comment]
Oh ok - now I understand =) Thank you!

**Pull request closed without merging**
