### PR TITLE
[installer]: add validate cluster command to the installer

### LINKED ISSUE #6210: [installer] Check target cluster for installation prerequisites
Prior to installing Gitpod, we should have a check available which ensures that given a configuration Gitpod will likely install and run well. Things to check (not comprehensive):
- kernel version (> 5.4)
- containerd used as CRI
- cert-manager is available
- nodes with all affinity labels are available

### PR DESCRIPTION
**Pull request by mrsimonemms**
## Description

Runs validation checks against the cluster
 - kernel `>= 5.4.0-0`
 - containerd used as runtime
 - cert-manager installed
 - affinity labels applied to nodes

## Related Issue(s)

Fixes #6210 

## How to test

With the appropriate config in `~/.kube/config` (or specifying your own with `--kubeconfig=` or `KUBECONFIG` envvar), run `go run . validate cluster`

## Release Notes

```release-note
Validate the cluster is in a state for Gitpod to be installed to
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mrsimonemms** after the PR has been reviewed.

Associated issue: *#6210*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/6234#issuecomment-944388723" title="Approved">aledbf</a>*

Associated issue: *#6210*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[installer/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/installer/OWNERS)~~ [aledbf]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by MrSimonEmms** [comment]
@aledbf Hmmm, the `5.4.120+` doesn't render as a valid semantic version in the package I've got. I'll rewrite the test so it's a bit more robust to that scenario

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: bc87b63d1b0fcfa7a2fa88e84cba12e8ec3133fd</details>

**Pull request merged**
