### PR TITLE
[dashboard] Redirect `/switch-to-payg` to docs

### PR DESCRIPTION
**Pull request by geropl**
## Description
As discussed [here](https://gitpod.slack.com/archives/C02EN94AEPL/p1680253858918529?thread_ts=1680246650.399619&cid=C02EN94AEPL).

## Related Issue(s)

Fixes #

## How to test
- try visit https://gpl-switch-redirect.preview.gitpod-dev.com/switch-to-payg?personalSubscription=asd

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by geropl** [comment]
/hold

@atduarte in case you want to have a look

**Review by atduarte — APPROVED** [review]
My approval doesn't help much, but here it goes 😁

**Review by easyCZ — APPROVED** [review]

**Pull request merged**
