### PR TITLE
Fix the security reporting URL

### PR DESCRIPTION
**Pull request by mikenikles**
Fixes https://github.com/gitpod-io/website/issues/512

### CODE REVIEW

**Review by fntlnz — APPROVED** [review]

**Comment by Carlos-Schrodinger** [comment]
I believe this should be merged without a doubt as it does not affect any of the website structure at all.

Just an honest opinion since implementing this fix is taking 2 days even though only a word was changed

**Comment by jankeromnes** [comment]
Agreed! Thanks, merging.

**Comment by jankeromnes** [comment]
Well, convincing the CI first.

/werft run

**Comment by jankeromnes** [comment]
Side note: We could also add a redirection from `https://gitpod.io/security` to `https://www.gitpod.io/security` just in case, for example like so:

https://github.com/gitpod-io/gitpod/blob/898b629c82bb692666b64d6cc47f306385c3b5b0/components/dashboard/conf/Caddyfile#L42

**Pull request merged**
