### PR TITLE
Sign in with SSO

### PR DESCRIPTION
**Pull request by AlexTugarev**
## Description
Adds a `Sign in with SSO` option to the Login screen.

This feature is guarded by a hidden flag, as it's hard to use feature flags for that. One can enable it by 

## Related Issue(s)
Fixes https://github.com/gitpod-io/gitpod/issues/15967
Fixes WEB-37

## How to test
1. Enable this feature by adding some magic experimental flag to local storage:
   ```localStorage.setItem("gitpod-ui-experiments", `{"ssoLogin": true}`)```
2. Create OIDC SSO integration for a team
3. Log out and find the `Sign in with SSO` button

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`

<details>
<summary>Publish Options</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer Options</summary>

- [ ] with-dedicated-emulation
- [ ] with-ws-manager-mk2
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by roboquat** [comment]
@AlexTugarev: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by selfcontained — APPROVED** [review]
Looks good and works as expected.

/hold in case there's more you wanted to do here.

**Comment by geropl** [comment]
Really looking forward to this! :heart_eyes: 

One question: How do we guard the login endpoints/AP) on gitpod.io? Is it worth having a feature flag (or do we already have one), maybe transitively, by controlling settings SSO config via API?
Just want to make sure. :slightly_smiling_face:

**Comment by AlexTugarev** [comment]
I think we're good to go here. Let's iterate on it based on this state. Just made another round of testing to have a good answer for Gero's ask:
 * the Login screen addition isn't visible by default, one would need to know which bits to add. 
 * the UI for creating OIDC client configs is behind a feature flag
 * the endpoints of the OIDC flows require to have client configs identifiable, i.e. there is not much to find there

**Pull request merged**
