### PR TITLE
🐛 fix: CLS bug on Git providers settings page

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
### Before on [settings page](https://gitpod.io/user/integrations)

See that [Cumulative Layout Shift](https://web.dev/cls/) bug

https://github.com/gitpod-io/gitpod/assets/55068936/d8362722-4b90-4865-98b2-13a57e933f17

### After on [settings page](https://gitpod.io/user/integrations)

No shift & stable render ✨ 

https://github.com/gitpod-io/gitpod/assets/55068936/6d3a7030-4584-4a69-b25f-25a0399c9cd8

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖 Generated by Copilot at 0ba7cae</samp>

Improved the layout of auth provider permissions in the user settings dashboard. Adjusted the width and max-width of the `ItemField` component in `AuthEntryItem.tsx` to prevent overflow on smaller screens.

</details>

## Related Issue(s)

Fixes #

## How to test

- Open preview
- Go to User settings -> `Git Providers` tab
- See 👀

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - fix-settin124b4654d8</li>
	<li><b>🔗 URL</b> - <a href="https://fix-settin124b4654d8.preview.gitpod-dev.com/workspaces" target="_blank">fix-settin124b4654d8.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - fix-settings-page-cls-issue-gha.15844</li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by akosyakov** [comment]
@gtsiolis Could you have a look please?

**Comment by gtsiolis** [comment]
Looking at this now! 👀 

Thanks for the ping, @akosyakov.

Just re-run all jobs to get the preview environment up.

**Comment by Siddhant-K-code** [comment]
Anything I can help with to review the PR?

**Review by gtsiolis — APPROVED** [review]
UX LGTM. 🏁 

Thanks, @Siddhant-K-code. 🌮 

Took me a while to get back to this.

Removed a class that didn't affect rendering and gave the permissions column a bit more space. Let's merge this.

/unhold

**Comment by Siddhant-K-code** [comment]
@gtsiolis, It doesn't seem to be fixed after your change 😅 


https://github.com/gitpod-io/gitpod/assets/55068936/3bd8a641-e32b-44c0-8d6b-15d94a17e8e8

**Comment by gtsiolis** [comment]
@Siddhant-K-code I can not reproduce this. What browser are you using?

**Comment by Siddhant-K-code** [comment]
> What browser are you using?

I am using Arc. I am able to reproduce that on Microsoft Edge too 😞.

---

I think expected behaviour should be that it should be aligned with the user image (on top right) and shouldn't be outside to that (shouldn't be overflow) -- that's why I've set the max width to don't expand outside of that portion.

image

**Pull request merged**
