### PR TITLE
Revert "Revert "Redirect on workspace stop" (#19323)"

### PR DESCRIPTION
**Pull request by jeanp413**
This reverts commit 827a1a03127bd2ab24ce2503247a19b48326fca5 with a proper fix

## Related Issue(s)

Fixes https://linear.app/gitpod/issue/EXP-1082

### Web editor
1. Select default editor to vscode web
2. Start workspace
3. Stop workspace, it should redirect automatically to the context url or a custom url from configcat

### Desktop editor
4. Select a desktop editor
5. Start workspace, check buttons work
6. Stop workspace, check buttons work

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - jp-retired-snake</li>
	<li><b>🔗 URL</b> - <a href="https://jp-retired-snake.preview.gitpod-dev.com/workspaces" target="_blank">jp-retired-snake.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - jp-retired-snake-gha.22292</li>
	<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-jp-retired-snake%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws-manager-mk2%22%0A;duration=P1D?project=gitpod-core-dev" target="_blank">GCP Logs Explorer</a></li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by jeanp413** [comment]
cc @svenefftinge

**Review by svenefftinge — APPROVED** [review]
Haven'T tested because the preview env was no longer running, but I assume you testet it.

**Review by mustard-mh — CHANGES_REQUESTED** [review]
Tested in preview env, it's working well. But will replace configured url's search params

example: `https://google.com/AA?a=1`

**Review by mustard-mh — APPROVED** [review]
approve to unblock,

**Pull request merged**
