### PR TITLE
fixing lint errors

### PR DESCRIPTION
**Pull request by selfcontained**
## Description

Fixing a batch of lint errors to get us closer to being able to enable the linter as a blocking test. I did my best to avoid any risky changes here, opting to disable a few lint errors on specific useEffect() calls that intentionally have no deps.

## How to test

Clicking around in the following areas to check that they're working as normal:

* Project creation
* main Project page
* Project prebuilds
* Personal Git Integrations
* Personal Billing
* Personal Access Tokens
* Start Workspace modal
* Team Members
* Team Billing
* Team SSO

## Release Notes

```release-note
NONE
```

## Build Options:

- [ ] /werft with-github-actions
      Experimental feature to run the build with GitHub Actions (and not in Werft).
- [ ] leeway-no-cache
      leeway-target=components:all
- [ ] /werft no-test
      Run Leeway with `--dont-test`
- [ ] /werft publish-to-npm

#### Preview Environment Options:
- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

### CODE REVIEW

**Comment by selfcontained** [comment]
I think the SocketSecurity [check is failing](https://github.com/gitpod-io/gitpod/pull/16212/checks?check_run_id=11104846464) because our root `package.json` has a name of `parent`, and it's confusing that with what looks like a malicious or squatting package on npm called [`parent`](https://www.npmjs.com/package/parent). I think we can ignore that specific failure. I'll hold off on telling SocketSecurity to ignore that package though.

**Review by geropl — APPROVED** [review]
LGTM :heavy_check_mark:

**Review by svenefftinge — APPROVED** [review]
🧹 LGTM

**Comment by selfcontained** [comment]
@SocketSecurity ignore parent@0.0.0

**Pull request merged**
