### PR TITLE
Fixed regex for matching size, localhost. Error logging in defer call

### PR DESCRIPTION
**Pull request by saisrivathsa**
- The regexes used are not valid regular expressions and the test cases pass with the changed regex.
- Error handling while using defer and go commands

### CODE REVIEW

**Review by corneliusludmann — CHANGES_REQUESTED** [review]
Hi @saisrivathsa,

Thanks for your contribution! Looks good!

Could you do me a favor and consider the following two things:

**First:** Would you mind squashing/renaming your commits to something more meaningful? I would suggest something like this:
- One commit for the defer close functions with a commit message like `Improve error handling in defer function calls`
- One commit for the regex changes: `Fix regex strings in gitpod-cli and ws-daemon`

**Second:** Would you mind adding the change of my comment to the `size.go` file?

Thanks!

**Comment by gtsiolis** [comment]
@saisrivathsa let us know if you up for picking up this and addressing the comments in https://github.com/gitpod-io/gitpod/pull/3679#pullrequestreview-655548191. You also need to sign a Contributor License Agreement (CLA) before merging this.

**Comment by meysholdt** [comment]
Hi @saisrivathsa! I've reached out to you via email about the CLA.

**Comment by meysholdt** [comment]
hi @saisrivathsa ! Thank you for your contribution. Before we can merge it, we'll need to sign a CLA. I've sent you an email about the next steps.

**Comment by meysholdt** [comment]
hi @saisrivathsa, we've updated our CLA process. Maybe it's easier for you now. Can you please sign our CLA via [this DocuSign form](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=30e1aa46-cce5-4bc6-a933-ad02cd8d5ada&env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&v=2)? If there are any questions, you can reach me via moritz@gitpod.io.

**Pull request closed without merging**
