### PR TITLE
[JetBrains] make plugin support other platforms

### PR DESCRIPTION
**Pull request by zhipengzuo**
## Description

show GitPod Plugin In IDEA
IDEA's remote development have released . the interface in IDEA will be more and more important .
## Related Issue(s)

Fixes #
https://github.com/gitpod-io/gitpod/issues/19296
## How to test

install the plugin in IDEA 
image

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

### CODE REVIEW

**Comment by mustard-mh** [comment]
Manually installing the build in IntelliJ worked, thanks you! 🧡 @zhipengzuo 

image

**Review by mustard-mh — APPROVED** [review]

**Comment by mustard-mh** [comment]
@zhipengzuo Thank you for you contribution

The plugin has been released to the Marketplace, but I just realized that even if I start the workspace from IntelliJ, we will launch the gateway🙈.

**Comment by zhipengzuo** [comment]
> @zhipengzuo Thank you for you contribution
> 
> The plugin has been released to the Marketplace, but I just realized that even if I start the workspace from IntelliJ, we will launch Gateway🙈.

yes , I also notice this . I am trying to communicate  with Jetbrains team .

**Comment by zhipengzuo** [comment]
> @zhipengzuo Thank you for you contribution
> 
> The plugin has been released to the Marketplace, but I just realized that even if I start the workspace from IntelliJ, we will launch Gateway🙈.

https://youtrack.jetbrains.com/issue/GTW-7995 you can see this

**Pull request merged**
