### PR TITLE
Enable integration test for JetBrains IDEs

### PR DESCRIPTION
**Pull request by iQQBot**
## Description

This PR introduces a very rudimentary version of the integration test for JetBrains IDEs
It uses the latest EAP version of Jetbrains Gateway, and test 4 IDEs at the same time (goland intellij phpstorm pycharm)

## Related Issue(s)

Relate #7023

## How to test

1. start gitpod workspace in gitpod.io
2. run command `werft run github --remote-job-path=.werft/ide-integration-tests-startup-jetbrains.yaml github.com/gitpod-io/gitpod:pd/enable-jb-daily-job`
3. see the werft log and following integration test log

The important thing is the overall process of testing, not about test result
1. create a new preview environment
2. start 4 integration test job
3. wait all test done
4. wipe preview environment

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by akosyakov** [comment]
```
 running test: /tests/jetbrains.test
 === RUN   TestJetBrainsGatewayWorkspace
 === RUN   TestJetBrainsGatewayWorkspace/Start_a_workspace_and_let_JetBrains_Gateway_connect
 === RUN   TestJetBrainsGatewayWorkspace/Start_a_workspace_and_let_JetBrains_Gateway_connect/it_can_start_a_workspace_and_let_JetBrains_Gateway_connect
     gateway_test.go:98: get or create user
     gateway_test.go:104: connecting to server...
     gateway_test.go:109: connected to server
     gateway_test.go:111: starting workspace
     gateway_test.go:114: cannot start workspace: "jsonrpc2: code 401 message: Unauthorized"
 --- FAIL: TestJetBrainsGatewayWorkspace (2.82s)
     --- FAIL: TestJetBrainsGatewayWorkspace/Start_a_workspace_and_let_JetBrains_Gateway_connect (2.82s)
         --- FAIL: TestJetBrainsGatewayWorkspace/Start_a_workspace_and_let_JetBrains_Gateway_connect/it_can_start_a_workspace_and_let_JetBrains_Gateway_connect (2.82s)
 FAIL
 Test failed at Mon Apr 11 07:07:52 UTC 2022
 Test suite ended with failure at Mon Apr 11 07:07:52 UTC 2022
```

expected?

**Review by akosyakov — DISMISSED** [review]
It takes really a lot of time and one test failed, but it did work.

**Comment by mustard-mh** [comment]
I meet the same error in `phpstorm` here https://werft.gitpod-dev.com/job/gitpod-ide-run-integration-tests-inte-test-20220411174215.2 three times, seems it'll happen every time?

https://werft.gitpod-dev.com/job/gitpod-ide-integration-tests-startup-jetbrains-pd-enable-j.6/results
https://werft.gitpod-dev.com/job/gitpod-ide-integration-tests-startup-jetbrains-pd-enable-j.5/results
https://werft.gitpod-dev.com/job/gitpod-ide-integration-tests-startup-jetbrains-pd-enable-j.4/results

**Review by mustard-mh — APPROVED** [review]
LGTM

**Pull request merged**
