### PR TITLE
upgrade to code 1.52.1

### PR DESCRIPTION
**Pull request by akosyakov**
- [x] /werft https

#### What it does

Upgrade Code to 1.52.1: https://github.com/gitpod-io/vscode/compare/711fc3e9f4192d725005e63f192c77780306544f...fa5be467f0bb30921faeb8ac2052752dbb8147b2

#### How to test

- Switch to Code as a default IDE.
- Start a new workspace.
- Check that fs is available, language servers are working, debugging working, try to install a new extension, try to open a file with code cli, task terminals and ports should work too,
  - For instance start a Theia repo, check that task terminal is running and port is detected when it is done.
  - Open some ts file to check language support.
  - Debug uri.spec.ts with `Run Mocha Test` launch configuration.
  - Install gitlens extension.
- Stop a workspace and start again. There should be any UI glitches.

### CODE REVIEW

**Comment by csweichel** [comment]
I started the gitpod-io repo and found:
- ✅  FS is available, content is initialised
- ❌  No extensions were installed (Installed: 0) and e.g. Go support was indeed missing. I did have syntax colouring though. Workspace ID: da97562b-98b4-4b29-abfe-e3cf47fe8d1a
- ✅  I was able to install Gitlens
- ❌  Gitlens seems to be working (i.e. it initialises itself), but [remains empty](https://user-images.githubusercontent.com/3210701/104459832-96a48680-55ad-11eb-8d97-f59872736f58.png)
- ✅  stopping the workspace worked fine. There were no glitches (I was actively looking for non-hidden menus or something of the sort)

**Comment by akosyakov** [comment]
@csweichel thanks for checking, i missed await in one place, I pushed a fix after that extension installation should work nicely

**Comment by akosyakov** [comment]
> No extensions were installed (Installed: 0) and e.g. Go support was indeed missing. I did have syntax colouring though. Workspace ID: da97562b-98b4-4b29-abfe-e3cf47fe8d1a

We don't have access to production extensions in GKE blobstorage from preview env, correct?

**Review by csweichel — APPROVED** [review]
works as advertised now :)

**Pull request merged**
