### PR TITLE
[content-service] Fix backup restore

### PR DESCRIPTION
**Pull request by aledbf**
## Description

Partial revert of https://github.com/gitpod-io/gitpod/pull/9589. Only reverts the **restore** part.

## How to test
- Open a workspace. In the terminal execute:
```
touch basic
sudo touch root-file
touch executable-file
chmod +x executable-file
touch suid-file
chmod 2555 suid-file
mkdir suid-directory
chmod g+s suid-directory
```
- Check the output of `ls -lat`, should be similar to
```
drwxr-x--- 8 gitpod gitpod 4096 Apr 28 17:31 .
-r-xr-sr-x 1 gitpod gitpod    0 Apr 28 17:31 suid-file
drwxr-sr-x 2 gitpod gitpod    6 Apr 28 17:31 suid-directory
-rwxr-xr-x 1 gitpod gitpod    0 Apr 28 17:30 executable-file
-rw-r--r-- 1 root   root      0 Apr 28 17:30 root-file
-rw-r--r-- 1 gitpod gitpod    0 Apr 28 17:30 basic
```
- Stop and open the workspace
- Open a terminal and run `ls -lat`
- Compare the outputs

## Release Notes

```release-note
[content-service] Fix backup restoration
```

xref https://github.com/gitpod-io/gitpod/pull/9730

### CODE REVIEW

**Comment by roboquat** [comment]
@aledbf: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by kylos101 — APPROVED** [review]
Works as advertised, plus, will unblock `gitpod-staging.com`.

CC: @geropl @jankeromnes

**Review by mustard-mh — APPROVED** [review]
Tested, now it works

**Comment by geropl** [comment]
Testing...

**Review by geropl — APPROVED** [review]
Works, awesome!

**Review by akosyakov — APPROVED** [review]
LGTM

**Review by MrSimonEmms — APPROVED** [review]

**Pull request merged**
