### PR TITLE
Privacy Policy update notification

### PR DESCRIPTION
**Pull request by filiptronicek**
## Description

Our [Privacy policy](https://www.gitpod.io/privacy) got updated. This PR makes sure users are properly notified about that.

### CODE REVIEW

**Review by Furisto — APPROVED** [review]

**Comment by filiptronicek** [comment]
I'll quickly make a preview environment and make sure the notification is displayed as expected. It's probably not strictly necessary, but it's also been a while since we last did.

**Comment by Siddhant-K-code** [comment]
How will it look with the current notification?

image

**Comment by filiptronicek** [comment]
@Siddhant-K-code good question, didn't have time to test that, but presumably they'd be stacked on top of each other with a `0.5rem` top padding.

Let's see tomorrow on .io

**Comment by filiptronicek** [comment]
See here where we track only the "top notification", which depends on the first-pushed non-dismissed notification in the `useEffect` above:
https://github.com/gitpod-io/gitpod/blob/c435ba226c552a1c64145382e6dcc32ac777c629/components/dashboard/src/AppNotifications.tsx#L192

**Comment by filiptronicek** [comment]
@Siddhant-K-code it sounds sensible to sometimes have more than one presently active notification, or at least signal that to the user. I raised ENT-855 for this

**Pull request merged**
