### PR TITLE
Remove shiftfs module loader

### PR DESCRIPTION
**Pull request by aledbf**
## Description
- The version of the module we ship is ancient
- Ubuntu stable already provides `shiftfs` OOTB
- Depending on the kernel version, we need to use different patches.
- Supported versions https://github.com/toby63/shiftfs-dkms#overview-of-branchesversions
- If the node already supports `shiftfs`, [we don't build the module](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/shiftfs-module-loader/entrypoint.sh#L12-L20)

Note: the initial check could also deliver a false positive because we cannot assume all the nodes are equal

## Release Notes

```release-note
NONE
```

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

### CODE REVIEW

**Comment by MrSimonEmms** [comment]
This will break the `install/installer/scripts/kots-install.sh` file.

Also, not all currently supported cloud providers currently support `shiftfs` - I don't think AKS supports it for one

**Comment by kylos101** [comment]
:wave: @aledbf is it [necessary to do remove shiftfs module loader "now"](https://agilemanifesto.org/principles.html#:~:text=Simplicity%2D%2Dthe%20art%20of%20maximizing%20the%20amount%0Aof%20work%20not%20done%2D%2Dis%20essential.)? Why? 

What are the side effects of removing?

I can think of a couple side effects. Does this sound right?
1. `ws-daemon` starts faster because it has [one less init container operation](https://github.com/gitpod-io/gitpod/pull/14005/files#diff-131eab3a970d46aaf4807ed70b6cbf2dd22bb263f2a7692ebc3dfe6a104f617fL99-L101). 
   1. Do you know how much faster?
2. it increases installation complexity, but only for administrators who do not follow our [ref arch OS recommendations](https://www.gitpod.io/docs/references/compatibility?admin) (which recommends Ubuntu 20 or 22)

Are there any I'm missing that you can add?

**Comment by aledbf** [comment]
> ws-daemon starts faster because it has [one less init container operation](https://github.com/gitpod-io/gitpod/pull/14005/files#diff-131eab3a970d46aaf4807ed70b6cbf2dd22bb263f2a7692ebc3dfe6a104f617fL99-L101).

Yes.

> Do you know how much faster?

At least 10s because the image needs to be pulled.

> it increases installation complexity, but only for administrators who do not follow our [ref arch OS recommendations](https://www.gitpod.io/docs/references/compatibility?admin) (which recommends Ubuntu 20 or 22)

I don't think this is true. The current module (.c file) does not work with 5.15.

**Comment by utam0k** [comment]
> it increases installation complexity, but only for administrators who do not follow our [ref arch OS recommendations](https://www.gitpod.io/docs/references/compatibility?admin) (which recommends Ubuntu 20 or 22)

The shiftfs kernel module needs to be changed in detail for each linux kernel version.
Probably no one is going to use what we are trying to delete. FuseFS is the default now.

**Review by utam0k — APPROVED** [review]
Looks good from my view.

**Review by jeanp413 — APPROVED** [review]

**Comment by MrSimonEmms** [comment]
This is tricky. I can see the benefit to Gitpod SaaS by making this change, it will be problematic for Self-Hosted. Whilst Ubuntu officially supports ShiftFS, it's not enabled in all things we have to support - for example, in Azure AKS, the Ubuntu image doesn't have ShiftFS enabled so we need to use Fuse.

**Comment by corneliusludmann** [comment]
@aledbf: I took the liberty to convert this to “draft” for now due to the concerns raised regarding self-hosted. Feel free to mark it as ready for review once the concerns have been addressed.

**Review by mrsimonemms — APPROVED** [review]
/hold

Broadly ok with the move but can you ensure that `main` has been rebased first - there's changes to the golden files in both branches

**Comment by aledbf** [comment]
Rebased

/hold cancel

**Pull request merged**
