### PR TITLE
ui: enlarge search box on dashboard

### LINKED ISSUE #8812: Search input box is too small. It should be fully flexible since there is no boundary (border) on this `input` box.
Search input box is too small. It should be fully flexible since there is no boundary (border) on this `input` box.

Screen Shot 2021-04-12 at 12 35 17

_Originally posted by @tnir in https://github.com/gitpod-io/gitpod/issues/3727#issuecomment-817455895_

### PR DESCRIPTION
**Pull request by jankeromnes**
_Restored @tnir's excellent community contribution from https://github.com/gitpod-io/gitpod/pull/8813 post [revert](https://github.com/gitpod-io/gitpod/pull/8969)_

## Description
Enlarges the search box on dashboard.

See the (simplified) sample code:

https://codepen.io/tnir/pen/GRyJoRE

## Related Issue(s)
Fixes #8812 (part of #3727)

Improves #3295

## How to test
Prepare an environment and resize the window size responsively.

## Release Notes
```release-note
NONE
```
(or `Enlarge search box on dashboard`)

## Documentation
No.

### CODE REVIEW

**Comment by jankeromnes** [comment]
@easyCZ Could you please approve these changes [again](https://github.com/gitpod-io/gitpod/pull/8813#pullrequestreview-923104706)?

Note: There is now a hold on this Pull Request while we figure out the CLA thing. 🧘

**Comment by easyCZ** [comment]
I believe there still remains the regression outlined in https://github.com/gitpod-io/gitpod/pull/8969#pullrequestreview-923129041. I'm watching this PR so will TAL whenever that is resolved.

**Comment by gtsiolis** [comment]
**fyi**: Converted this to draft PR until _when_ the UX regression issues described in https://github.com/gitpod-io/gitpod/pull/8994#issuecomment-1081680029 have been resolved and this is be ready for review.

**Comment by tnir** [comment]
Signing CLA looks taking longer than expected. It took 13 days just to get the form and there looks like a problem in #7864 so it would take 1 month or so. Before finishing to sign CLA, I would like not to update the changes.

@jankeromnes Close this PR as I cannot update the changes as this PR in @gitpod-io.

**Comment by jankeromnes** [comment]
Sorry for being silly/slow with the CLA 😞 I hope we can do better, because contributor free time and energy are extremely precious and rare. ❤️

Closing this PR as requested. Please re-send a PR once the CLA situation is sorted, and please ping me if I can do anything at all to help.

**Pull request closed without merging**
