### PR TITLE
Fix PAPI conversion

### PR DESCRIPTION
**Pull request by AlexTugarev**
## Description

<details>
<summary>Summary generated by Copilot</summary>

### <samp>🤖 Generated by Copilot at 99bc2de</samp>

This pull request updates the projects API to make the `enable_prebuilds` field of the `PrebuildSettings` message optional. This allows users to configure prebuilds for their projects without specifying a boolean value, and to inherit the default settings from the team or the global configuration. The pull request modifies the proto, Go, and TypeScript definitions of the message and the related types.

</details>

## Related Issue(s)

Fixes #

#### Preview status

<p>Gitpod was successfully deployed to your preview environment.</p>
<ul>
	<li><b>🏷️ Name</b> - at-fix-papi-convert</li>
	<li><b>🔗 URL</b> - <a href="https://at-fix-papi-convert.preview.gitpod-dev.com/workspaces" target="_blank">at-fix-papi-convert.preview.gitpod-dev.com/workspaces</a>.</li>
	<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your preview environment.</li>
	<li><b>📦 Version</b> - at-fix-papi-convert-gha.16979</li>
	<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-at-fix-papi-convert%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws-manager-mk2%22%0A;duration=P1D?project=gitpod-core-dev" target="_blank">GCP Logs Explorer</a></li>
</ul>

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [x] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

### CODE REVIEW

**Review by geropl — APPROVED** [review]
LGTM! :heavy_check_mark:

**Comment by AlexTugarev** [comment]
Screenshot 2023-09-15 at 12 14 47
Screenshot 2023-09-15 at 12 14 51
Screenshot 2023-09-15 at 12 14 57

@geropl, just verified that it's behaving as expected.

**Pull request merged**
